libs/api/domains/license-service/src/lib/licenseService.service.ts
libs/api/domains/rights-portal/src/lib/healthCenter/healthCenter.service.ts
libs/service-portal/health/src/lib/messages.ts
libs/service-portal/health/src/screens/Dentists/BillsTable.tsx
libs/service-portal/health/src/screens/HealthCenter/HealthCenter.tsx
libs/service-portal/health/src/screens/HealthCenter/HistoryTable.tsx
libs/service-portal/health/src/screens/HealthOverview/HealthOverview.tsx

Adding fixes to production
- feature flags
- messages
- license service bug

fix(service-portal): Hotfixing bugs

---

libs/application/templates/transport-authority/change-operator-of-vehicle/src/forms/ChangeOperatorOfVehicleForm/InformationSection/mainOperatorSubSection.ts

fix(samgongustofa change operator): main operator missing

---

libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/Conclusion/index.tsx
libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/forms/ReviewSeller.ts
libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/ChangeCoOwnerOfVehicleTemplate.ts
libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/messages/conclusion.ts
libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/Conclusion/index.tsx
libs/application/templates/transport-authority/change-operator-of-vehicle/src/forms/ReviewSeller.ts
libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/ChangeOperatorOfVehicleTemplate.ts
libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/messages/conclusion.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Conclusion/index.tsx
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/forms/ReviewSeller.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/forms/TransferOfVehicleOwnershipForm/InformationSection/vehicleSubSection.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/TransferOfVehicleOwnershipTemplate.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/messages/conclusion.ts

feat(transport-authority): car owner payment screen release

---

libs/application/template-api-modules/src/lib/modules/templates/social-insurance-administration/social-insurance-administration-utils.ts
libs/application/template-api-modules/src/lib/modules/templates/social-insurance-administration/social-insurance-administration.service.ts
libs/clients/social-insurance-administration/src/clientConfig.yaml
libs/clients/social-insurance-administration/src/lib/socialInsuranceAdministrationClient.service.ts

Feat(old age pension): send application fix

---

libs/application/template-api-modules/src/lib/modules/shared/api/driving-license/driving-license.service.ts

fix(application): Driving License Client needs to listen to legacy params

---

libs/application/templates/parental-leave/src/fields/DraftRequiresAction/index.tsx
libs/application/templates/parental-leave/src/lib/messages.ts

fix(parental-leave): Change text when employer rejects period

---

libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.service.ts
libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/utils/index.ts

These started failing on production.
Easy fix

fix(application-driving-license): Remove country code from phone

---

libs/application/templates/criminal-record/src/fields/ConfirmationField/index.tsx
libs/application/templates/no-debt-certificate/src/fields/ConfirmationField/index.tsx
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/TransferOfVehicleOwnershipTemplate.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/messages/application.ts

fix(criminal-record): error topic card is redirecting

---

libs/application/templates/announcement-of-death/src/fields/RealEstateRepeater/index.tsx
libs/application/templates/estate/src/fields/RealEstateRepeater/AdditionalRealEstate.tsx
libs/clients/syslumenn/src/lib/syslumennClient.utils.ts

fix(estate): Property and lot lookup

---

apps/web/components/ChatPanel/types.ts
apps/web/pages/s/stafraent-island/1ynznw78TAgrDqesmPTVkb/index.ts
apps/web/screens/Organization/StafraentIsland/DigitalIcelandWebChat.tsx
apps/web/utils/organization.ts

feat(web): Add custom page for web chat between organizations and Digital Iceland

---

apps/web/components/ChatPanel/types.ts
apps/web/components/Organization/Wrapper/Themes/TryggingastofnunTheme/TryggingastofnunHeader.css.ts
apps/web/components/Organization/Wrapper/Themes/TryggingastofnunTheme/TryggingastofnunHeader.tsx
apps/web/pages/s/stafraent-island/1ynznw78TAgrDqesmPTVkb/index.ts
apps/web/screens/Organization/StafraentIsland/DigitalIcelandWebChat.tsx
apps/web/utils/organization.ts

* https://github.com/island-is/island.is/pull/12517
* https://github.com/island-is/island.is/pull/12551

feat(web): Hotfix - header change and digital iceland web chat added

---

apps/judicial-system/api/infra/judicial-system-api.ts
charts/judicial-system/values.dev.yaml
charts/judicial-system/values.prod.yaml
charts/judicial-system/values.staging.yaml

increased the resource limits for the judicial system api to stop it crashing

fix: increased the resource limits for the judicial system api to stop it crashing

---

libs/application/templates/announcement-of-death/src/lib/dataSchema.ts
libs/clients/syslumenn/src/lib/syslumennClient.utils.ts

fix(application-estate): Property mapping fixes

---

libs/application/templates/passport/src/fields/HasDisabilityLicenseMessage/index.tsx
libs/application/templates/passport/src/fields/index.ts
libs/application/templates/passport/src/forms/Draft.ts
libs/application/templates/passport/src/forms/infoSection/childsPersonalInfo.ts
libs/application/templates/passport/src/forms/infoSection/personalInfo.ts
libs/application/templates/passport/src/lib/constants.ts
libs/application/templates/passport/src/lib/dataSchema.ts
libs/application/templates/passport/src/lib/utils.ts

fix(passport): disabilityLicense (#12554)

---

libs/application/templates/estate/src/lib/dataSchema.ts

fix(estate): debts validation

---

libs/application/template-api-modules/src/lib/modules/templates/transport-authority/digital-tachograph-drivers-card/digital-tachograph-drivers-card.service.ts
libs/application/template-api-modules/src/lib/modules/templates/transport-authority/digital-tachograph-drivers-card/types.ts
libs/application/templates/transport-authority/digital-tachograph-drivers-card/src/forms/DigitalTachographDriversCardForm/CardTypeSection/index.ts

fix(samgongustofa okuritakort): fix fieldname for photo and signature

---

apps/application-system/form/infra/application-system-form.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

fix: added missing network grants for application system form

---

apps/application-system/form/infra/application-system-form.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

* fix: added missing network grants for application system form
* added missing islandis grant
---------

fix: added missing network grants for application system form (#12583)

---

libs/application/templates/passport/src/lib/utils.ts

fix(passport): small bug fix for disability checkbox

---

apps/contentful-apps/pages/fields/embed-link-field.tsx

feat(web): Allow powerbi embed for Embed content type in CMS

---

libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.service.ts

fix(application-driving-license): Driving license phone external fix

---

apps/judicial-system/backend/migrations/20231031174234-create-indexes.js

[Add obvious missing indexes](https://app.asana.com/0/1199153462262248/1205833686449569/f)
- Adds two indexes to the DB.
- Attempting to speed up queries.

chore(j-s): DB Indexes

---

apps/consultation-portal/screens/Case/Case.tsx

https://github.com/island-is/island.is/pull/12604

fix(consultation-portal): Hotfix kam 1843

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/assignEmployerEmail.ts
libs/application/template-api-modules/src/lib/modules/templates/reference-template/emailGenerators/assignEmail.ts

fix(parental-leave): Fix type in emails

---

apps/judicial-system/web/src/routes/CourtOfAppeal/Overview/Overview.tsx
apps/judicial-system/web/src/routes/CourtOfAppeal/Result/Result.tsx
apps/judicial-system/web/src/routes/CourtOfAppeal/components/CaseOverviewHeader/CaseOverviewHeader.tsx

[Réttarvörslugátt - ábendingar submission](https://app.asana.com/0/1199153462262248/1205884302369814)
Fix COA Overview and Result screens
To display all relevant info for COA judges

fix(j-s): Re-add missing COA overview and result info

---

apps/judicial-system/web/src/components/DefenderInfo/DefenderInfo.strings.ts

[Tvöfaldur Contentful lykill](https://app.asana.com/0/1199153462262248/1205878307358463/f)
- Fixes duplicate Contentful ids.
- We cannot update Contentful strings when there are duplicate ids.

fix(j-s): Contentful String

---

apps/consultation-portal/hooks/api/useFetchEmail.ts
apps/consultation-portal/screens/Case/utils/shouldShowStakeholdersBox.ts
apps/consultation-portal/screens/Subscriptions/components/SubscriptionsSkeleton/SubscriptionsSkeleton.tsx

https://veflausnir.atlassian.net/browse/KAM-1853
- Fetch email if screen is my subscriptions
- Change date to show stakeholders box

fix(consultation-portal): Kam 1853 my subscriptions not showing up

---

apps/consultation-portal/lib/shared.json
apps/consultation-portal/screens/Case/Case.tsx
apps/consultation-portal/screens/Case/CaseDesktop.tsx
apps/consultation-portal/screens/Case/CaseMobile.tsx
apps/consultation-portal/screens/Case/components/AdviceForm/AdviceForm.tsx
apps/consultation-portal/screens/Case/components/CaseStatusBox/CaseStatusBox.tsx
apps/consultation-portal/screens/Subscriptions/Subscriptions.json
apps/consultation-portal/types/interfaces.ts

* take out "um" in subscription text
* KAM-1852: change wording of publishing rule
* KAM-1852: Checkpoint
* KAM-1852: fix false text and ordering
Summary:
---------
https://veflausnir.atlassian.net/browse/KAM-1852
https://github.com/island-is/island.is/pull/12632
Remove "um" in subscription text
Add "í gáttinni" to publishNever text

fix(consultation-portal): Hotfix kam 1852

---

apps/consultation-portal/hooks/api/useFetchEmail.ts
apps/consultation-portal/screens/Case/utils/shouldShowStakeholdersBox.ts
apps/consultation-portal/screens/Subscriptions/components/SubscriptionsSkeleton/SubscriptionsSkeleton.tsx

…12643)
* KAM-1853: Show my subscriptions
* KAM-1853: Change date for showing stakeholders box
---------
My subscriptions not showing up
https://github.com/island-is/island.is/pull/12643
https://veflausnir.atlassian.net/browse/KAM-1853
Fetch email if screen is my subscriptions
Change date to show stakeholders box

fix(consultation-portal): Hotfix kam 1853

---

apps/consultation-portal/lib/shared.json
apps/consultation-portal/screens/Case/Case.json
apps/consultation-portal/screens/Case/components/AdviceForm/AdviceForm.tsx
apps/consultation-portal/screens/Case/components/AdviceList/AdviceList.tsx
apps/consultation-portal/screens/Case/components/CaseStatusBox/CaseStatusBox.tsx
apps/consultation-portal/screens/Case/components/CaseStatusText/CaseStatusText.tsx
apps/consultation-portal/screens/Case/components/index.ts

https://veflausnir.atlassian.net/browse/KAM-1857
Change wording in status box
CaseStatusText returns an array so that we can get formatting on the link

fix(consultation-portal): KAM-1857: fix wording in statuses

---

apps/consultation-portal/screens/Case/Case.json

https://veflausnir.atlassian.net/browse/KAM-1860
Change wording for hiding advice

fix(consultation-portal): KAM-1860: fix wording

---

libs/api/domains/communications/src/lib/emailTemplates/serviceWebForms.ts

* There was a request to change what emails "Vottorð" cases get sent to
* This was requested by the district commissioner organization

feat(web): Change email for Sýslumenn service web form submissions

---

apps/web/layouts/main.tsx
apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacanciesList.tsx
apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacancyDetails.tsx
libs/api/domains/icelandic-government-institution-vacancies/src/lib/icelandic-government-institution-vacancies.resolver.ts

https://github.com/island-is/island.is/pull/12656

feat(web): Hotfix - Add option for alert banner on /starfatorg

---

apps/web/components/ChatPanel/WatsonChatPanel/WatsonChatPanel.tsx
apps/web/components/ChatPanel/WatsonChatPanel/directorateOfImmigrationChatUtils.ts
apps/web/components/ChatPanel/WatsonChatPanel/index.ts
apps/web/components/ChatPanel/WatsonChatPanel/utils.ts
apps/web/components/ChatPanel/types.ts
apps/web/components/Organization/Wrapper/config.ts
apps/web/components/ServiceWeb/config.ts
apps/web/screens/Article/components/ArticleChatPanel/config.ts
apps/web/screens/Project/components/ProjectChatPanel/config.ts

Before
After - Icelandic
After - English

feat(web): Directorate of immigration chat widget UI changes

---

apps/service-portal/src/screens/Dashboard/Dashboard.tsx
libs/service-portal/assets/src/screens/Lookup/Lookup.graphql
libs/service-portal/assets/src/screens/Lookup/Lookup.tsx
libs/service-portal/finance/src/components/FinanceStatusDetailTable/FinanceStatusDetailTable.tsx
libs/service-portal/finance/src/components/FinanceStatusTableRow/FinanceStatusTableRow.tsx
libs/service-portal/information/src/module.tsx
libs/service-portal/occupational-licenses/src/components/LicenseDetail.tsx

Hotfix:
https://github.com/island-is/island.is/pull/12668
https://github.com/island-is/island.is/pull/12665
https://github.com/island-is/island.is/pull/12671

fix(service-portal): Hotfix - Vehicles, company settings, finance xsl

---

apps/consultation-portal/hooks/api/useFetchEmail.ts
apps/consultation-portal/screens/Case/utils/shouldShowStakeholdersBox.ts
apps/consultation-portal/screens/Subscriptions/components/SubscriptionsSkeleton/SubscriptionsSkeleton.tsx

…12643)
* KAM-1853: Show my subscriptions
* KAM-1853: Change date for showing stakeholders box
---------
#My subscriptions not showing up
https://github.com/island-is/island.is/pull/12643
https://veflausnir.atlassian.net/browse/KAM-1853
Fetch email if screen is my subscriptions
Change date to show stakeholders box

fix(consultation-portal): hotfix My subscriptions not showing up

---

apps/consultation-portal/lib/shared.json
apps/consultation-portal/screens/Case/Case.tsx
apps/consultation-portal/screens/Case/CaseDesktop.tsx
apps/consultation-portal/screens/Case/CaseMobile.tsx
apps/consultation-portal/screens/Case/components/AdviceForm/AdviceForm.tsx
apps/consultation-portal/screens/Case/components/CaseStatusBox/CaseStatusBox.tsx
apps/consultation-portal/screens/Subscriptions/Subscriptions.json
apps/consultation-portal/types/interfaces.ts

https://veflausnir.atlassian.net/browse/KAM-1852
https://github.com/island-is/island.is/pull/12632
- Remove "um" in subscription text
- Add "í gáttinni" to publishNever text

fix(consultation-portal): fix spelling and wording

---

apps/consultation-portal/screens/Case/components/AdviceForm/AdviceForm.tsx

https://github.com/island-is/island.is/pull/12650
https://veflausnir.atlassian.net/browse/KAM-1855
- Fix location of strings

fix(consultation-portal): KAM-1855: fixed location (#12650)

---

apps/system-e2e/src/tests/judicial-system/smoke/custody-prosecutor.spec.ts

Add in checking a radio button
To fix tests

test(j-s): Fix e2e test

---

apps/services/user-profile/src/app/user-profile/e2e/userProfile.spec.ts
apps/services/user-profile/src/app/user-profile/verification.service.ts
apps/services/user-profile/src/app/v2/user-profile.service.ts

Adding #12693 to release.
To fix Nova SMS sending in user profile.
N/A

fix(user-profile): Reverting using formatted phone number in sms verification

---

apps/consultation-portal/screens/Case/utils/shouldShowStakeholdersBox.ts

https://veflausnir.atlassian.net/browse/KAM-1865
- Change date in date check for shouldShowStakeholdersBox to 10th
- Change comparison of dates to getTime()

fix(consultation-portal): KAM-1865: changed launch date

---

libs/api/domains/license-service/src/lib/graphql/genericLicense.model.ts
libs/api/domains/license-service/src/lib/licenceService.type.ts
libs/api/domains/license-service/src/lib/mappers/ehicCardMapper.ts
libs/service-portal/licenses/src/screens/LicenseDetail/LicenseDetail.tsx

Makes the downloadCard actually download a pdf
Broke

fix(ehic): DownloadPDF button

---

apps/application-system/api/infra/application-system-api.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

fix(utlendingastofnun - citizenship): Add missing infra in application system

---

apps/service-portal/src/components/ContentBreadcrumbs/ContentBreadcrumbs.tsx
apps/service-portal/src/components/TabNavigation/TabNavigation.tsx
libs/api/domains/license-service/src/lib/graphql/genericLicense.model.ts
libs/api/domains/license-service/src/lib/licenceService.type.ts
libs/api/domains/license-service/src/lib/mappers/ehicCardMapper.ts
libs/service-portal/health/src/components/FootNote/helper.tsx
libs/service-portal/health/src/lib/messages.ts
libs/service-portal/health/src/screens/HealthCenterRegistration/HealthCenterRegistration.tsx
libs/service-portal/health/src/screens/HealthOverview/HealthOverview.tsx
libs/service-portal/health/src/screens/Medicine/Medicine.tsx
libs/service-portal/health/src/screens/Medicine/TabPanes/MedicineCalculator.tsx
libs/service-portal/health/src/screens/Medicine/TabPanes/MedicineLicence.tsx
libs/service-portal/health/src/screens/Medicine/TabPanes/MedicinePurchase.tsx
libs/service-portal/health/src/screens/Medicine/components/DrugRow/DrugRow.tsx
libs/service-portal/health/src/screens/Medicine/components/QuantityCounter/QuantityCounter.tsx
libs/service-portal/health/src/screens/MedicineCertificate/MedicineCertificate.tsx
libs/service-portal/health/src/screens/Payments/Payments.tsx
libs/service-portal/health/src/screens/Payments/TabPanes/PaymentOverview.tsx
libs/service-portal/health/src/screens/Payments/TabPanes/PaymentParticipation.tsx
libs/service-portal/licenses/src/screens/LicenseDetail/LicenseDetail.tsx

https://github.com/island-is/island.is/pull/12704
https://github.com/island-is/island.is/pull/12692
Fix broken things on prod

fix(service portal): health and pdf fixes

---

apps/services/license-api/src/app/modules/license/license.service.ts
libs/clients/license-client/src/lib/clients/firearm-license-client/services/firearmLicenseUpdateClient.service.ts

fix(firearm-license): firearm license log

---

libs/service-portal/licenses/src/screens/LicenseDetail/LicenseDetail.tsx

fix(service-portal): download button

---

libs/service-portal/licenses/src/screens/LicenseDetail/LicenseDetail.tsx

fix(service-portal): Hotfix - download button 

---

apps/judicial-system/backend/src/app/modules/case/case.service.ts

[Hotfix](https://app.asana.com/0/1199153462262248/1205924191397154/f)
- Hotfix
- Performance issue

chore(j-s): Hotfix

---

libs/service-portal/assets/src/screens/VehicleHistory/VehicleHistory.tsx

[Issue](https://www.notion.so/Tengja-label-vi-input-kut-kjaferli-c94ee31dd2a14576b739c52a77a27553?pvs=4)
Fix issue
Fix issue

fix(service-portal): adding id to checkbox

---

apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
apps/judicial-system/web/src/components/FormProvider/limitedAccessCaseGql.ts
apps/judicial-system/web/src/components/RulingModifiedModal/RulingModifiedModal.strings.ts
apps/judicial-system/web/src/components/RulingModifiedModal/RulingModifiedModal.tsx
apps/judicial-system/web/src/routes/Defender/CaseOverview.strings.ts
apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.strings.ts
apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
libs/service-portal/licenses/src/screens/LicenseDetail/LicenseDetail.tsx

[LR : Enduropna dómaraflæði og geta gert breytingar. ](https://app.asana.com/0/1199153462262248/1205724728618403)
Add missing COA appeal result modified info to overviews
Because everyone is meant to see information on the modified result

fix(j-s): COA appeal result modified 

---

README.md
apps/services/auth/delegation-api/infra/delegation-api.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml

Add the contents of #12729 to release
To increase memory of api in production.
N/A

chore(delegation-api): Increase delegation api memory

---

libs/application/template-api-modules/src/lib/modules/templates/social-insurance-administration/social-insurance-administration-utils.ts
libs/application/template-api-modules/src/lib/modules/templates/social-insurance-administration/social-insurance-administration.service.ts
libs/clients/social-insurance-administration/src/clientConfig.yaml

feat(old-age-pension): Save the application on TR servers

---

libs/service-portal/health/src/lib/messages.ts

fix(service-portal): update link

---

libs/service-portal/health/src/module.tsx

fix(service-portal): wrong scope

---

apps/consultation-portal/components/Layout/components/Footer/Footer.tsx
apps/consultation-portal/components/Layout/components/Menu/Menu.tsx
apps/consultation-portal/context/IsSsrMobileContext.tsx
apps/consultation-portal/context/index.ts
apps/consultation-portal/hooks/useIsMobile.ts
apps/consultation-portal/hooks/useIsWindowSize.ts
apps/consultation-portal/pages/_app.tsx
apps/consultation-portal/screens/Error404/Error404.json
apps/consultation-portal/screens/Home/Home.tsx

* KAM-1869: links for logos
* adding space between text and emal
* useIsMobile now with ssr
* check for ssr mobile in _app
* useWindowSize hook
* IsSsrMobileContext hook
* add to context index file
* MobileFilter loaded after initial rendering
---------
https://veflausnir.atlassian.net/browse/KAM-1869
https://github.com/island-is/island.is/pull/12745
- Logos should be clickable links
- Remove the cls for mobile

fix(consultation-portal): Kam 1869 fix problems from qa (#12745)

---

libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.service.ts
libs/application/templates/driving-license/src/forms/draft/draft.ts
libs/application/templates/driving-license/src/forms/draft/subSectionPhone.ts
libs/application/templates/driving-license/src/forms/draft/subSectionTempInfo.ts
libs/application/templates/driving-license/src/lib/messages.ts

fix(application-driving-license): Add phone field explicitly. (#12759)

---

libs/service-portal/health/src/screens/Therapies/TherapiesOccupational.tsx
libs/service-portal/health/src/screens/Therapies/TherapiesPhysical.tsx
libs/service-portal/health/src/screens/Therapies/TherapiesSpeech.tsx
libs/service-portal/health/src/screens/Therapies/wrapper/TherapiesWrapper.tsx

hotfix for therapies nav in health

fix(service-portal): health therapies nav

---

libs/application/templates/social-insurance-administration/old-age-pension/src/lib/OldAgePensionTemplate.ts
libs/application/templates/social-insurance-administration/old-age-pension/src/lib/oldAgePensionUtils.ts

feat(old-age-pension): Make sure additionalDocumentsRequired don't get sent twice to TR when requesting more documents

---

libs/service-portal/health/src/lib/paths.ts

fix(service-portal): tweak heilsa urls

---

libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/TransferOfVehicleOwnershipTemplate.ts

fix(transport authority): Add missing extradata to payment state

---

libs/island-ui/core/src/lib/PdfViewer/PdfViewer.css.ts
libs/island-ui/core/src/lib/PdfViewer/PdfViewer.tsx
libs/service-portal/documents/src/components/DocumentActionBar/DocumentActionBar.css.ts
libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
libs/service-portal/documents/src/components/DocumentRenderer/DocumentRenderer.tsx
libs/service-portal/documents/src/lib/types.ts
libs/service-portal/documents/src/utils/customUrlHandler.ts

Hotfix:
https://github.com/island-is/island.is/pull/12780
https://github.com/island-is/island.is/pull/12770

fix(service-portal): Document handling in inbox. RSK link and annotation layer.

---

libs/service-portal/health/src/lib/messages.ts
libs/service-portal/health/src/screens/HealthOverview/HealthOverview.tsx
libs/service-portal/health/src/screens/Medicine/MedicineCalculator.tsx
libs/service-portal/health/src/screens/Medicine/MedicineLicense.tsx
libs/service-portal/health/src/screens/Medicine/MedicinePurchase.tsx

Add button to download health insurance confirmation pdf

fix(service-portal): add download health insurance confirmation button

---

libs/service-portal/core/src/components/TabNavigation/TabNavigation.tsx
libs/service-portal/health/src/screens/Medicine/MedicineCalculator.tsx
libs/service-portal/health/src/screens/Medicine/MedicineLicense.tsx
libs/service-portal/health/src/screens/Medicine/MedicinePurchase.tsx
libs/service-portal/health/src/screens/Medicine/wrapper/MedicineWrapper.tsx
libs/service-portal/health/src/screens/Payments/PaymentOverview.tsx
libs/service-portal/health/src/screens/Payments/PaymentParticipation.tsx
libs/service-portal/health/src/screens/Payments/wrapper/PaymentsWrapper.tsx
libs/service-portal/health/src/screens/Therapies/TherapiesOccupational.tsx
libs/service-portal/health/src/screens/Therapies/TherapiesPhysical.tsx
libs/service-portal/health/src/screens/Therapies/TherapiesSpeech.tsx
libs/service-portal/health/src/screens/Therapies/wrapper/TherapiesWrapper.tsx

Add correct label to nav in heath
Test is not a good label

fix(service-portal): fix heath nav

---

libs/service-portal/core/src/components/TabNavigation/TabNavigation.tsx
libs/service-portal/health/src/lib/messages.ts
libs/service-portal/health/src/screens/HealthOverview/HealthOverview.tsx
libs/service-portal/health/src/screens/Medicine/MedicineCalculator.tsx
libs/service-portal/health/src/screens/Medicine/MedicineLicense.tsx
libs/service-portal/health/src/screens/Medicine/MedicinePurchase.tsx
libs/service-portal/health/src/screens/Medicine/wrapper/MedicineWrapper.tsx
libs/service-portal/health/src/screens/Payments/PaymentOverview.tsx
libs/service-portal/health/src/screens/Payments/PaymentParticipation.tsx
libs/service-portal/health/src/screens/Payments/wrapper/PaymentsWrapper.tsx
libs/service-portal/health/src/screens/Therapies/TherapiesOccupational.tsx
libs/service-portal/health/src/screens/Therapies/TherapiesPhysical.tsx
libs/service-portal/health/src/screens/Therapies/TherapiesSpeech.tsx
libs/service-portal/health/src/screens/Therapies/wrapper/TherapiesWrapper.tsx

- Add download button for insurance confirmation
- fix labels on mobile heath navs

fix(service-portal): health labels and insurance confirmation pdf

---

libs/application/templates/estate/src/forms/Sections/representative.ts

[Attach a link to issue if relevant
](https://app.asana.com/0/1204431115744096/1205939903295173)
add * to the email field
- [ x I have rebased against main before asking for a review

chore(estate): add required icon to representative email

---

libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/utils/healthDeclarationMapper.ts

Fix mapping
Causing errors for some users. Because the api does not accept alphabetical charaters.

fix(driving-licence): Sanitize phone number 

---

libs/application/template-api-modules/src/lib/modules/templates/index.ts
libs/application/template-api-modules/src/lib/modules/templates/social-insurance-administration/social-insurance-administration.module.ts
libs/application/template-api-modules/src/lib/modules/templates/social-insurance-administration/social-insurance-administration.service.spec.ts
libs/application/template-api-modules/src/lib/modules/templates/social-insurance-administration/social-insurance-administration.service.ts
libs/application/templates/social-insurance-administration/old-age-pension/src/dataProviders/index.ts
libs/application/templates/social-insurance-administration/pension-supplement/src/dataProviders/index.ts
libs/application/templates/social-insurance-administration/pension-supplement/src/fields/Period/index.tsx
libs/application/templates/social-insurance-administration/pension-supplement/src/forms/PensionSupplementForm.ts
libs/application/templates/social-insurance-administration/pension-supplement/src/forms/Prerequisites.ts
libs/application/templates/social-insurance-administration/pension-supplement/src/lib/PensionSupplementTemplate.ts
libs/application/templates/social-insurance-administration/pension-supplement/src/lib/dataSchema.ts
libs/application/templates/social-insurance-administration/pension-supplement/src/lib/messages.ts
libs/application/templates/social-insurance-administration/pension-supplement/src/types.ts

feat(pension-supplement): Get applicant info

---

libs/application/templates/estate/src/forms/OverviewSections/assetsAndDebts.ts
libs/application/templates/estate/src/forms/Sections/estateAssets.ts

[Attach a link to issue if relevant
](https://app.asana.com/0/1204431115744096/1205878853652594)
remove the stock section for estate without assets

chore(estate): remove stocksection for estate without assets

---

libs/application/templates/estate/src/fields/EstateMembersRepeater/index.tsx
libs/application/templates/estate/src/forms/Sections/testamentInfo.ts
libs/application/templates/estate/src/lib/dataSchema.ts
libs/application/templates/estate/src/lib/messages.ts
libs/application/templates/estate/src/lib/utils.ts

fix(estate): creditor name validation

---

libs/application/templates/estate/src/forms/Sections/deceasedInfoFields.ts

[Attach a link to issue if relevant](https://app.asana.com/0/1204431115744096/1205939902430852)
date should be dd.MM.yyyyy not date should be dd/MM/yyyyy not

fix(estate): change date format for death date

---

libs/api/domains/rights-portal/src/lib/drug/models/drugCertificate.model.ts
libs/clients/icelandic-health-insurance/rights-portal/src/clientConfig.json
libs/service-portal/health/src/lib/messages.ts
libs/service-portal/health/src/screens/Medicine/Medicine.graphql
libs/service-portal/health/src/screens/Medicine/MedicineLicense.tsx
libs/service-portal/health/src/screens/MedicineCertificate/MedicineCertificate.graphql
libs/service-portal/health/src/screens/MedicineCertificate/MedicineCertificate.tsx

Hotfix health certificate statuses

fix(service-portal): add correct statuses to medicine certificates (#12873)

---

libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/InformationSection/MaritalStatusSubSection.ts

Error was occuring when text field got null value and validation was failing on optional fields

fix(citizenship): null check added for optional text fields

---

apps/services/auth/ids-api/infra/identity-server.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml

Configure urls that are whitelisted for redirect after user profile info editing.
So users can be returned to the page where they initiated the action.

feat(ids): Configure allowed uris for staging and prod.

---

libs/application/templates/estate/src/fields/EstateMembersRepeater/index.tsx
libs/application/templates/estate/src/forms/Sections/announcerInfo.ts
libs/application/templates/estate/src/lib/dataSchema.ts
libs/application/templates/estate/src/lib/messages.ts

fix(estate): estate without assets - relation to deceased

---

libs/application/template-api-modules/src/lib/modules/templates/children-residence-change-v2/children-residence-change.service.ts

Update uploadDataId in payload to syslumenn
Requested by stakeholder

feat(crc-v2): Update uploadDataId in payload to syslumenn

---

libs/application/templates/complaints-to-althingi-ombudsman/src/lib/ComplaintsToAlthingiOmbudsmanTemplate.ts
libs/feature-flags/src/lib/features.ts

Add feature flag to Complaints to Althingi Ombudsman application
It should not be accessible on production at the moment

feat(ctao): Add Feature Flag

---

libs/service-portal/core/src/components/IntroHeader/IntroHeader.tsx
libs/service-portal/education/src/screens/EducationGraduationDetail/EducationGraduationDetail.tsx

Update default provider for intro header
Add provider for graduation details
It will default to minjastofnun if not provided 🤷

fix(service-portal): Update default provider for intro header

---

libs/service-portal/assets/src/screens/VehicleMileage/VehicleMileage.tsx

Set loading for the title while fetching first info
The state of the title can change. Default is loading, then the state is shown once we know it from the API.

fix(service-portal): Mileage title loading

---

apps/system-e2e/src/tests/islandis/application-system/acceptance/car-recycling.spec.ts
libs/application/templates/car-recycling/src/fields/Review/review-groups/BaseInformation.tsx
libs/application/templates/car-recycling/src/fields/VehiclesOverview/VehiclesOverview.tsx
libs/application/templates/car-recycling/src/index.ts
libs/application/templates/car-recycling/src/lib/CarRecyclingTemplate.ts

feat(car-recycling): Added e2e tests

---

libs/service-portal/assets/src/lib/messages.ts
libs/service-portal/assets/src/screens/VehicleDetail/VehicleDetail.tsx
libs/service-portal/assets/src/screens/VehicleMileage/VehicleMileage.tsx

* Fix mileage external link
* Update placeholder default
* Button overflow on vehicle overview
* Fix strings
Bugfixing 🐛 🐞 🐻

fix(service-portal): Minor mileage page issues

---

libs/application/templates/social-insurance-administration/household-supplement/src/dataProviders/index.ts
libs/application/templates/social-insurance-administration/household-supplement/src/fields/Review/review-groups/BaseInformation.tsx
libs/application/templates/social-insurance-administration/household-supplement/src/forms/HouseholdSupplementForm.ts
libs/application/templates/social-insurance-administration/household-supplement/src/forms/Prerequisites.ts
libs/application/templates/social-insurance-administration/household-supplement/src/lib/HouseholdSupplementTemplate.ts
libs/application/templates/social-insurance-administration/household-supplement/src/lib/dataSchema.ts
libs/application/templates/social-insurance-administration/household-supplement/src/lib/messages.ts

feat(household-supplement): Get applicant info

---

libs/service-portal/health/src/screens/HealthOverview/HealthOverview.tsx
libs/service-portal/health/src/screens/Medicine/wrapper/MedicineWrapper.tsx
libs/service-portal/health/src/screens/Payments/wrapper/PaymentsWrapper.tsx

fix: check if isInsured is false for determining insurance status

---

apps/service-portal/src/components/Layout/NarrowLayout.tsx
apps/service-portal/src/components/Loaders/AuthOverlay/AuthOverlay.tsx
apps/service-portal/src/components/Sidebar/NavItem/SubNav.tsx
apps/service-portal/src/components/Sidemenu/Sidemenu.css.ts
apps/service-portal/src/components/Sidemenu/SidemenuItem.tsx
libs/service-portal/health/src/screens/HealthOverview/HealthOverview.tsx
libs/service-portal/health/src/screens/Medicine/Medicine.css.ts
libs/service-portal/health/src/screens/Medicine/MedicinePurchase.tsx

Medicine billing lines not showing properly
Users need to see the purchases

fix(service-portal):  medicine purchase billing lines

---

libs/application/templates/parental-leave/src/forms/EditOrAddEmployersAndPeriods.ts

feat(parental-leave): Fix edit or add employers for older applications

---

libs/application/templates/parental-leave/src/forms/EditOrAddEmployersAndPeriods.ts

fix(parental-leave): Fix edit or add employers for older applications

---

libs/application/core/src/lib/fieldBuilders.ts

Let onChange funnel down to TextFormField from buildTextField
OnChange on text input are needed to avoid making custom components for text fields that have their value change.

feat(application-system): Introduce onChange to buildTextField

---

apps/web/pages/en/o/[slug]/news/[newsSlug]/index.tsx

fix(web): Incorrect english news import path

---

apps/web/pages/en/o/[slug]/news/[newsSlug]/index.tsx

fix(web): English news import was incorrect

---

libs/application/templates/estate/src/forms/Sections/estateAssets.ts
libs/application/templates/estate/src/lib/dataSchema.ts
libs/application/templates/inheritance-report/src/forms/sections/assets.ts
libs/application/templates/inheritance-report/src/lib/dataSchema.ts

Add nationalId field for claims in estate application and inhertance report

chore(estate): add national id for claims

---

apps/service-portal/src/components/Layout/NarrowLayout.tsx
apps/service-portal/src/components/Loaders/AuthOverlay/AuthOverlay.tsx
apps/service-portal/src/components/Sidebar/NavItem/SubNav.tsx
apps/service-portal/src/components/Sidemenu/Sidemenu.css.ts
apps/service-portal/src/components/Sidemenu/SidemenuItem.tsx
libs/service-portal/health/src/screens/HealthOverview/HealthOverview.tsx
libs/service-portal/health/src/screens/Medicine/Medicine.css.ts
libs/service-portal/health/src/screens/Medicine/MedicinePurchase.tsx

Hotfix for invisible medicine purchase lines

fix(service-portal): health medicine purchase lines

---

libs/api/domains/vehicles/src/lib/api-domains-vehicles-mileage.resolver.ts
libs/api/domains/vehicles/src/lib/api-domains-vehicles-shared.resolver.ts
libs/api/domains/vehicles/src/lib/api-domains-vehicles.module.ts
libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts
libs/feature-flags/src/lib/features.ts

Add feature flag for vehicle mileage resolver
It's missing.

fix(vehicles): Add feature flag for vehicle mileage resolver

---

libs/api/domains/vehicles/src/lib/api-domains-vehicles-mileage.resolver.ts
libs/api/domains/vehicles/src/lib/api-domains-vehicles-shared.resolver.ts
libs/api/domains/vehicles/src/lib/api-domains-vehicles.module.ts
libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts
libs/feature-flags/src/lib/features.ts

hotfix: https://github.com/island-is/island.is/pull/12937

fix(vehicles): Add feature flag for vehicle mileage resolver (#12937)

---

apps/services/user-notification/src/app/modules/notifications/notifications.controller.ts

feat(user-notification-worker): Nicer logs & cleanup

---

libs/application/templates/estate/src/forms/OverviewSections/assetsAndDebts.ts

https://app.asana.com/0/1204431115744096/1206065680243311
wrong title in 2 places

chore(estate): add missing titlevariants

---

apps/consultation-portal/screens/EmailVerified/EmailVerified.json

https://github.com/island-is/island.is/pull/12979
https://veflausnir.atlassian.net/browse/KAM-1919
Change wording on email verified page

fix(consultation-portal): Hotfix/kam 1919

---

libs/application/template-api-modules/src/lib/modules/shared/api/driving-license/driving-license.service.ts

fix(application-driving-license): Fix category mapping (#12982)

---

apps/application-system/api/infra/application-system-api.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

fix: increased application system api worker limits

---

apps/api/infra/api.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
infra/src/dsl/xroad.ts

fix(clients-social-insurance-administration): add TR_XROAD_PATH to infra

---

apps/web/components/DefaultHeader/DefaultHeader.css.ts
apps/web/components/DefaultHeader/DefaultHeader.tsx
apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/Themes/VinnueftirlitidTheme/VinnueftirlitidHeader.css.ts
apps/web/components/Organization/Wrapper/Themes/VinnueftirlitidTheme/VinnueftirlitidHeader.tsx
apps/web/components/Organization/Wrapper/Themes/VinnueftirlitidTheme/index.tsx

feat(web): Add header for Vinnueftirlitið organization page

---

libs/application/templates/estate/src/forms/Sections/estateWithoutAssets.ts
libs/application/templates/estate/src/lib/messages.ts

https://app.asana.com/0/1204431115744096/1206090774490792

chore(estate): add text field for asset radio

---

libs/application/templates/estate/src/fields/TextFieldsRepeater/index.tsx
libs/application/templates/estate/src/forms/OverviewSections/assetsAndDebts.ts
libs/application/templates/estate/src/lib/utils.ts

See title
The calculated value was not accurate enough without the decimal

fix(estate): allow decimal in faceValue and calculated value

---

apps/services/auth/ids-api/src/app/delegations/delegations.controller.spec.ts

chore(ids-api): Try fix flaky pers. repr. tests.

---

libs/application/templates/estate/src/forms/Sections/approveSubmission.ts

chore(estate): same checkbox style

---

apps/services/university-gateway/infra/university-gateway.ts
charts/islandis/values.dev.yaml

Readiness now redirects to liveness
Liveness is an accurate indicator of readiness for the service, previously no readiness indicator was defined

fix(University gateway): fix readiness

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/Themes/HljodbokasafnIslandsTheme/HljodbokasafnIslandsHeader.css.ts
apps/web/components/Organization/Wrapper/Themes/HljodbokasafnIslandsTheme/HljodbokasafnIslandsHeader.tsx
apps/web/components/Organization/Wrapper/Themes/HljodbokasafnIslandsTheme/index.ts

feat(web): Add hljodbokasafn islands header

---

apps/application-system/api/infra/application-system-api.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

The car recycling gql base path was missing the gql path after the service path.
To fix the path.
N/A

fix(application-system-api): Adding gql path to the service path for the gql base path in infra

---

apps/application-system/api/infra/application-system-api.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

…the gql base path in infra (#13070)
* Adding gql path to the service path for the gql base path.
* chore: charts update dirty files
---------

fix(application-system-api): Adding gql path to the service path for car recycling

---

apps/judicial-system/backend/src/app/modules/case/case.service.ts
apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Defendant/Defendant.tsx
apps/judicial-system/web/src/utils/validate.ts
libs/judicial-system/types/src/index.ts
libs/judicial-system/types/src/lib/case.ts

[Ekki hægt að halda áfram með rannsóknarmál sem dómur er búinn að skrá talsmann eða fulltrúa á](https://app.asana.com/0/1199153462262248/1206150415175529/f)
- Fixes the validation of the prosecutor defenadant step in investigation cases.

fix(j-s): Defendant Step Validation

---

apps/judicial-system/backend/src/app/modules/case/case.controller.ts
apps/judicial-system/web/src/routes/CourtOfAppeal/Ruling/Ruling.spec.tsx
apps/judicial-system/web/src/routes/CourtOfAppeal/Ruling/Ruling.tsx

[Landréttur geti breytt lengd (gæslu, einangrun, farbann) ef úrskurði héraðs er breytt](https://app.asana.com/0/1199153462262248/1205581325881986/f)
- Fixes changes to valid to dates at the court of appeals.
- The dates can only be changes for restriction cases that where accepted by the district court.
- Dates in custody cases that where changed to travel ban cases by the district court can not be changed.
- Dates are prefilled by the current valid to dates when the district court first enters the ruling page for the case.

fix(j-s): Court of Appeals Valid to Dates

---

.github/CODEOWNERS

fix(energy funds): update codeowners

---

libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts

fix(application-estate): Correct to which application the <18 applies

---

libs/application/core/src/lib/messages.ts
libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
libs/application/template-api-modules/src/lib/modules/templates/estate/utils/fakeData.ts
libs/application/templates/estate/src/lib/utils.ts
libs/clients/syslumenn/project.json
libs/clients/syslumenn/src/clientConfig.json
libs/clients/syslumenn/src/lib/syslumennClient.config.ts
libs/clients/syslumenn/src/lib/syslumennClient.service.ts
libs/clients/syslumenn/src/lib/syslumennClient.types.ts
libs/clients/syslumenn/src/lib/syslumennClient.utils.ts

fix(application-estate): Estate entry requirements

---

libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts

fix(application-estate): Young heir validation

---

apps/air-discount-scheme/backend/src/app/modules/discount/discount.service.ts

Hotfix of https://github.com/island-is/island.is/pull/13045
Explicit codes need both fake to and fake from flight legs when we want to go both ways,

fix(ads): explicit discount code sometimes needs flightlegs to and from

---

.github/CODEOWNERS
apps/application-system/form/src/auth.ts
libs/api/domains/energy-funds/src/lib/graphql/main.resolver.ts
libs/application/templates/energy-funds/src/lib/EnergyFundsTemplate.tsx
libs/auth/scopes/src/lib/api.scope.ts

Use correct custom scope for the application "Energy funds": @island.is/applications/samgongustofa-vehicles -> @island.is/applications/orkusjodur
Update codeowners for application
Note: Has already been updated on main

fix(energy funds): use correct custom scope + update codeowners

---

libs/application/templates/transport-authority/digital-tachograph-drivers-card/src/dataProviders/index.ts

fix(digital tachograph drivers card): Allow birthplace to be empty

---

apps/contentful-apps/pages/fields/organization-subpage-slug-field.tsx
libs/application/core/src/lib/messages.ts
libs/application/template-api-modules/src/lib/modules/shared/api/user-profile/user-profile.service.ts
libs/application/template-api-modules/src/lib/modules/templates/energy-funds/energy-funds.service.ts
libs/application/templates/energy-funds/project.json
libs/application/templates/energy-funds/src/dataProviders/index.ts
libs/application/templates/energy-funds/src/lib/messages/information.ts
libs/application/types/src/lib/template-api/shared-api/shared-api-definitions/user-profile-api.ts

Needed a bankInformation parameter to stop applicant in dataProvider step if no bank account

fix(energy-funds): UserProfile parameter and price update

---

libs/service-portal/finance/src/lib/messages.ts
libs/service-portal/finance/src/screens/FinanceLoans/FinanceLoans.tsx

fix(service-portal): Hotfix - Update finance messages

---

libs/portals/admin/signature-collection/src/lib/messages.ts
libs/portals/admin/signature-collection/src/lib/utils.ts
libs/portals/admin/signature-collection/src/screens/AllLists/index.tsx

fix(signature-collection): Admin - add filter by candidate

---

libs/application/template-api-modules/src/lib/modules/templates/energy-funds/energy-funds.service.ts
libs/application/templates/energy-funds/src/lib/dataSchema.ts

fix(energy-funds): small fix for grant information

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

* Fixed period
* Fixed Sync VMST period when start is less then date 20
---------

feat(parental-leave): Fixed period (#13017)

---

libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
libs/application/template-api-modules/src/lib/modules/templates/estate/utils/fakeData.ts

fix(application-estate): Resolved !== vs === bug and modified test data

---

libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
libs/application/template-api-modules/src/lib/modules/templates/estate/utils/fakeData.ts

fix(application-estate): Estate young heir validation bugfix

---

libs/application/templates/inheritance-report/src/fields/CalculationsOfTotal/CalculateTotalAssets/index.tsx
libs/application/templates/inheritance-report/src/forms/sections/assets.ts
libs/application/templates/inheritance-report/src/lib/dataSchema.ts
libs/application/templates/inheritance-report/src/lib/messages.ts

https://app.asana.com/0/1204431115744096/1205990261973339
money and deposits should not be a repeater but a single textarea and an input for currency

chore(inheritance-report): change money and deposits to textfield

---

libs/application/templates/inheritance-report/src/forms/sections/assets.ts

https://app.asana.com/0/1204431115744096/1205990261973331
remove format from bankaccount field
to allow entry non icelandic bankaccounts

chore(inheritance-report): remove icelandic format on asset bankaccount

---

apps/skilavottord/ws/src/app/modules/recyclingRequest/dto/createRecyclingRequest.input.ts
apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts
apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequestAppSys.resolver.ts
apps/skilavottord/ws/src/app/modules/vehicle/vehicleAppSys.resolver.ts
libs/application/template-api-modules/src/lib/modules/templates/car-recycling/car-recycling.service.ts
libs/application/templates/car-recycling/src/lib/CarRecyclingTemplate.ts
libs/clients/car-recycling/src/lib/carRecyclingClient.service.ts

Fix an issue to save the recycling requests

fix(car-recycling): Fix recycling request not being saved

---

apps/skilavottord/ws/src/app/modules/recyclingRequest/dto/createRecyclingRequest.input.ts
apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts
apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequestAppSys.resolver.ts
apps/skilavottord/ws/src/app/modules/vehicle/vehicleAppSys.resolver.ts
libs/application/template-api-modules/src/lib/modules/templates/car-recycling/car-recycling.service.ts
libs/application/templates/car-recycling/src/lib/CarRecyclingTemplate.ts
libs/clients/car-recycling/src/lib/carRecyclingClient.service.ts

* Fix recycling request not being saved
* Trim fullname
* Remove delete button after submit
* Added back throw exception
merged from #9b53b5d

fix(car-recycling): Fix recycling request not being saved (#13118)

---

libs/application/templates/inheritance-report/src/fields/CalculationsOfTotal/CalculateTotalAssets/index.tsx
libs/application/templates/inheritance-report/src/forms/sections/assets.ts
libs/application/templates/inheritance-report/src/lib/dataSchema.ts

https://app.asana.com/0/1204431115744096/1205990256457311
Inventory should be one textarea for description and another for total value

chore(inheritance-report): change inventory input to textarea

---

apps/web/components/connected/vehicles/KilometerFee.tsx
apps/web/components/connected/vehicles/index.ts
apps/web/utils/richText.tsx

This was requested by Digital Iceland

feat(web): Kilometer fee connected component

---

apps/system-e2e/src/tests/islandis/application-system/acceptance/car-recycling.spec.ts

Remove and fix test code that is no longer needed because of change of components
Fixed E2E failing

feat(car-recycling): Fix E2E tests

---

apps/consultation-portal/screens/Advices/Advices.json
apps/consultation-portal/screens/Case/Case.json
apps/consultation-portal/screens/Subscriptions/Subscriptions.json

https://github.com/island-is/island.is/pull/13139
Fix non binary friendly language

fix(consultation-portal): Hotfix kam 1949

---

apps/consultation-portal/screens/Advices/Advices.json
apps/consultation-portal/screens/Case/Case.json
apps/consultation-portal/screens/Subscriptions/Subscriptions.json

https://veflausnir.atlassian.net/browse/KAM-1949
Fix non binary friendly language

fix(consultation-portal): KAM-1949: Fix non binary friendly language

---

apps/judicial-system/xrd-api/src/app/app.controller.ts
apps/judicial-system/xrd-api/src/app/app.interceptor.ts
apps/judicial-system/xrd-api/src/app/app.service.ts

[Logga requestur frá LÖKE](https://app.asana.com/0/1199153462262248/1206153194238641/f)
- Logs all incomming requests.
- Posts a Slack event for all failed requests, including malformed requests.
- To help with debugging operational issues.

chore(j-s): XRD API Logging

---

libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/sections/VehicleSection.tsx
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/VehiclesField/VehicleRadioField.tsx
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/VehiclesField/VehicleSelectField.tsx
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/forms/TransferOfVehicleOwnershipForm/InformationSection/vehicleSubSection.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/dataSchema.ts

feat(transfer of vehicle ownership): Make mileage required

---

libs/application/templates/energy-funds/src/forms/Prerequisites/index.ts
libs/application/templates/energy-funds/src/lib/messages/externalData.ts

fix(energy-funds): Adding contentful text

---

libs/application/templates/inheritance-report/src/forms/sections/assets.ts

https://app.asana.com/0/1204431115744096/1204431618037813

chore(inheritance-report): add currency format to total value

---

libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

feat(parental-leave): Revert period fix

---

libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

feat(parental-leave): Revert period fix (#13147)

---

apps/consultation-portal/screens/Case/Case.json

https://veflausnir.atlassian.net/browse/KAM-1952
Fix gender text in login box to send advice in case detail page

fix(consultation-portal): fix non binary friendly text

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/Themes/HljodbokasafnIslandsTheme/HljodbokasafnIslandsHeader.css.ts
apps/web/components/Organization/Wrapper/Themes/HljodbokasafnIslandsTheme/HljodbokasafnIslandsHeader.tsx
apps/web/components/Organization/Wrapper/Themes/HljodbokasafnIslandsTheme/index.ts

feat(web): Hotfix - Add hljodbokasafn islands header (#13069)

---

apps/web/components/connected/vehicles/KilometerFee.tsx
apps/web/components/connected/vehicles/index.ts
apps/web/utils/richText.tsx

https://github.com/island-is/island.is/pull/13126
https://github.com/island-is/island.is/pull/13156

feat(web): Hotfix - Kilometer fee calculator

---

apps/web/components/connected/AdministrationOfOccupationalSafetyAndHealthCourses/AdministrationOfOccupationalSafetyAndHealthCourses.tsx

* We want to be able to pre-filter courses with an includes check rather than exact match to be able to match a prefix
* A lot of courses are in a subcategory of the same name like "Byggingakrananámskeið - Enska" and so forth, we want to be able to type in "Byggingakrananámskeið" to display all those related courses in the different languages

feat(web): Replace === with .includes() for administration of occupational safety and health course cards

---

libs/application/templates/healthcare-license-certificate/src/forms/HealthcareLicenseCertificateForm/index.ts
libs/application/templates/healthcare-license-certificate/src/forms/HealthcareLicenseCertificateForm/personalSection.ts
libs/application/templates/healthcare-license-certificate/src/lib/messages/confirmation.ts
libs/application/templates/healthcare-license-certificate/src/lib/messages/error.ts
libs/application/templates/healthcare-license-certificate/src/lib/messages/information.ts
libs/application/templates/healthcare-license-certificate/src/utils/getChargeItemCodes.ts
libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/forms/ChangeCoOwnerOfVehicleForm/InformationSection/ownerSubSection.ts
libs/application/templates/transport-authority/change-operator-of-vehicle/src/forms/ChangeOperatorOfVehicleForm/InformationSection/ownerSubSection.ts
libs/application/templates/transport-authority/digital-tachograph-drivers-card/src/forms/DigitalTachographDriversCardForm/ApplicantSection/userInformationSubSection.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/forms/TransferOfVehicleOwnershipForm/InformationSection/sellerSubSection.ts

fix(healtcare license certificate): Small fixes after testing

---

libs/application/templates/estate/src/fields/EstateMembersRepeater/AdditionalEstateMember.tsx

fix(application-estate): Young heir validation frontend bugfix

---

apps/services/auth/ids-api/infra/identity-server.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml

Add environment variables for https://github.com/island-is/identity-server.web/pull/646

chore(ids): Add env vars for user identifier redaction in metrics.

---

libs/application/template-api-modules/src/lib/modules/templates/healthcare-license-certificate/healthcare-license-certificate.service.ts
libs/application/templates/healthcare-license-certificate/src/fields/SelectLicenseField/index.tsx
libs/application/templates/healthcare-license-certificate/src/forms/HealthcareLicenseCertificateForm/personalSection.ts
libs/application/templates/healthcare-license-certificate/src/lib/messages/error.ts

fix(healtcare license certificate): Small fixes after testing - more fixes

---

apps/air-discount-scheme/backend/src/app/modules/discount/discount.service.ts

hotfix: https://github.com/island-is/island.is/pull/13162

fix(ADS): hotfix - fixing credit issues

---

apps/skilavottord/ws/src/app/modules/vehicle/vehicle.resolver.ts
apps/skilavottord/ws/src/app/modules/vehicle/vehicle.service.ts

* adding update mileage
* resolver input fix
Hotfix 
---------

feat(skilavottord): adding update mileage resolver (#13169)

---

apps/skilavottord/web/auth/utils.ts
apps/skilavottord/web/components/CarDetailsBox/CarDetailsBox.tsx
apps/skilavottord/web/i18n/locales/en.json
apps/skilavottord/web/i18n/locales/is.json
apps/skilavottord/web/i18n/locales/translation.d.ts
apps/skilavottord/web/pages/deregister-vehicle-km/[id].tsx
apps/skilavottord/web/pages/deregister-vehicle-km/index.ts
apps/skilavottord/web/pages/deregister-vehicle-km/select.tsx
apps/skilavottord/web/pages/en/deregister-vehicle-km/[id].tsx
apps/skilavottord/web/pages/en/deregister-vehicle-km/index.ts
apps/skilavottord/web/pages/en/deregister-vehicle-km/select.tsx
apps/skilavottord/web/screens/DeregisterVehicleKm/Confirm/ConfirmKM.tsx
apps/skilavottord/web/screens/DeregisterVehicleKm/Overview/Overview.tsx
apps/skilavottord/web/screens/DeregisterVehicleKm/Overview/components/CarsTable/CarsTable.tsx
apps/skilavottord/web/screens/DeregisterVehicleKm/Overview/components/CarsTable/index.ts
apps/skilavottord/web/screens/DeregisterVehicleKm/Overview/index.tsx
apps/skilavottord/web/screens/DeregisterVehicleKm/Select.tsx
apps/skilavottord/web/screens/DeregisterVehicleKm/index.tsx
apps/skilavottord/web/screens/index.ts

* - Added milage and mileage input
- Add tmp /deregister-vehicle-km to test the the mileage
* Remove debug code
* Fix the call to the new mileage update resolver
* Show 0 instead of empty
* Remove unused imports
* Fix after review
Hotfix: https://github.com/island-is/island.is/pull/13185
---------

feat(skilavottord): Add mileage input 

---

apps/web/components/Organization/Wrapper/Themes/HljodbokasafnIslandsTheme/HljodbokasafnIslandsHeader.css.ts

fix(web): Remove lines from HBS header

---

apps/web/components/DefaultHeader/DefaultHeader.tsx
apps/web/components/Organization/Wrapper/Themes/HljodbokasafnIslandsTheme/HljodbokasafnIslandsHeader.css.ts
apps/web/components/Organization/Wrapper/Themes/HljodbokasafnIslandsTheme/HljodbokasafnIslandsHeader.tsx

fix(web): Hotfix - Remove lines from HBS header (#13195)

---

libs/financial-aid/shared/src/lib/taxCalculator.ts

https://app.asana.com/0/1205807691300420/1206229863640719/f
Use correct amount and percentage for tax calculations performed in 2024.

fix(fa): update tax percentage and alllowance for 2024

---

apps/skilavottord/ws/src/app/modules/auth/auth.guard.ts
apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.resolver.ts
apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts

Hotfix
* adding mileage
* adding mileage resolver
* minor fix
* minor fix
* fix error logging
* remove mileage null
* remove console-logs
---------

fix(skilavottord): mileage-to-samgongustofu (#13216)

---

apps/web/screens/ServiceWeb/Forms/utils.ts
libs/api/domains/communications/src/lib/emailTemplates/serviceWebForms.ts

* Change what categories are available in the contact form
* Change what emails receive the form submissions depending on selected category

feat(web): Transport authority service web contact form

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/children/children.service.ts

fix(parental-leave): Fixed error in provideChildren when adoption

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/children/children.service.ts

fix(parental-leave): Fixed error in provideChildren when adoption 

---

libs/application/template-api-modules/src/lib/modules/templates/energy-funds/energy-funds.service.ts
libs/application/templates/energy-funds/src/fields/SelectVehicle/VehicleCheckboxField.tsx
libs/application/templates/energy-funds/src/fields/SelectVehicle/VehicleSelectField.tsx
libs/application/templates/energy-funds/src/lib/dataSchema.ts

fix(energy-fund): adding import code

---

apps/skilavottord/ws/src/app/modules/auth/auth.guard.ts

Hotfix
Add back IdsUserGuard
Solving Invalid User error

fix(skilavottord): Add back IdsUserGuard (#13256)

---

libs/application/templates/estate/src/fields/EstateMembersRepeater/AdditionalEstateMember.tsx
libs/application/templates/estate/src/fields/EstateMembersRepeater/index.tsx
libs/application/templates/estate/src/fields/LookupPerson/index.tsx
libs/application/templates/estate/src/lib/constants.ts
libs/application/templates/estate/src/lib/dataSchema.ts
libs/application/templates/estate/src/lib/messages.ts
libs/application/templates/estate/src/types.ts

fix(estate): properly validate estatemembers (#13213)

---

libs/application/templates/signature-collection/signature-list-creation/src/forms/Prerequisites.ts
libs/application/templates/signature-collection/signature-list-creation/src/lib/messages.ts
libs/application/templates/signature-collection/signature-list-signing/src/forms/Draft.ts
libs/application/templates/signature-collection/signature-list-signing/src/forms/Prerequisites.ts
libs/application/templates/signature-collection/signature-list-signing/src/lib/messages.ts
libs/service-portal/signature-collection/src/lib/messages.ts

fix(signature-collection): text tweaks

---

libs/api/domains/signature-collection/src/lib/models/area.model.ts
libs/api/domains/signature-collection/src/lib/models/signatureList.model.ts
libs/clients/signature-collection/src/lib/types/area.dto.ts
libs/clients/signature-collection/src/lib/types/bulkUpload.dto.ts
libs/clients/signature-collection/src/lib/types/collection.dto.ts
libs/clients/signature-collection/src/lib/types/list.dto.ts
libs/clients/signature-collection/src/lib/types/signature.dto.ts

Check if max signatures are reached

feat(singature-collection): max reached check

---

libs/application/templates/social-insurance-administration/core/src/lib/constants.ts
libs/application/templates/social-insurance-administration/household-supplement/src/forms/AdditionalDocumentsRequired.ts
libs/application/templates/social-insurance-administration/household-supplement/src/forms/HouseholdSupplementForm.ts
libs/application/templates/social-insurance-administration/old-age-pension/src/forms/AdditionalDocumentsRequired.ts
libs/application/templates/social-insurance-administration/old-age-pension/src/forms/OldAgePensionForm.ts

feat(social-insurance-administration): Add file upload shared props to constants in sia core

---

apps/judicial-system/web/src/components/FormProvider/FormProvider.tsx

[Notandi er alltaf fluttur beint á innskráningarsíðu Stafræns Íslands þegar hann fer á forsíðu RVG](https://app.asana.com/0/1199153462262248/1206270978194195/f)
- Does not redirect unauthenticated users that are accessing RVGs root page.
https://github.com/island-is/island.is/assets/795382/542555d3-2c57-4818-b4aa-756bee578a19

fix(j-s): Unauthenticated Redirect

---

apps/web/components/ServiceWeb/config.ts
apps/web/screens/Project/components/ProjectChatPanel/config.ts

Remove Grindavík chat from project page and service web

chore(web): Remove grindavik chat

---

libs/service-portal/assets/src/screens/VehicleMileage/VehicleMileage.tsx
libs/service-portal/assets/src/utils/readDate.ts

minor refactor for readdatetoday function

fix(service-portal): read date today

---

apps/system-e2e/src/support/api-tools.ts

Added missing change from previous test changes
It somehow got left behind and is needed for tests to run

test(j-s): Fix missing file change

---

libs/portals/admin/signature-collection/src/screens/AllLists/getAllSignatureLists.graphql
libs/portals/admin/signature-collection/src/screens/List/getSignatureList.graphql

fix(signature-collection): build fix

---

libs/application/templates/energy-funds/src/lib/dataSchema.ts
libs/application/templates/energy-funds/src/lib/messages/error.ts

feature(energy-fund): Contentful update

---

libs/application/templates/energy-funds/src/lib/dataSchema.ts
libs/application/templates/energy-funds/src/lib/messages/error.ts

feat(energy-fund): Contentful update release

---

libs/api/domains/vehicles/src/dto/getVehiclesForUserInput.ts
libs/api/domains/vehicles/src/lib/api-domains-vehicles.resolver.ts
libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts
libs/api/domains/vehicles/src/models/usersVehicles.model.ts
libs/clients/vehicles/src/clientConfig.json
libs/service-portal/assets/src/components/VehicleCard.tsx
libs/service-portal/assets/src/screens/Overview/Overview.graphql
libs/service-portal/assets/src/screens/Overview/Overview.tsx

Hotfix: https://github.com/island-is/island.is/pull/13273 🔥

feat(service-portal): Add vehicle list v3 (hotfix)

---

libs/application/templates/inheritance-report/src/forms/form.ts
libs/application/templates/inheritance-report/src/forms/sections/applicationInfo.ts
libs/application/templates/inheritance-report/src/lib/messages.ts

https://app.asana.com/0/1204431115744096/1205990256457299
Add information section

chore(inheritance-report): add information section

---

libs/api/domains/signature-collection/src/lib/signatureCollection.resolver.ts
libs/api/domains/signature-collection/src/lib/signatureCollection.service.ts
libs/clients/signature-collection/src/lib/signature-collection.service.ts
libs/portals/admin/signature-collection/src/lib/messages.ts
libs/portals/admin/signature-collection/src/screens/List/components/extendDeadline/extendDeadline.graphql
libs/portals/admin/signature-collection/src/screens/List/components/extendDeadline/index.tsx

fix(signature-collection): extendDeadline success

---

libs/application/templates/family-matters/children-residence-change-v2/src/forms/ChildrenResidenceChangeForm.ts
libs/application/templates/family-matters/children-residence-change-v2/src/forms/PrerequisitesForm.ts
libs/application/templates/family-matters/children-residence-change-v2/src/lib/ChildrenResidenceChangeTemplate.ts
libs/application/templates/family-matters/children-residence-change-v2/src/lib/constants.ts
libs/application/types/src/lib/ApplicationTypes.ts

- Move prerequisites to it's own state
- Update prune times
- Update slugs 
So it's ready for production

feat(crc): Move prerequisites to it's own state and update prune times

---

libs/service-portal/documents/src/components/DocumentRenderer/DocumentRenderer.tsx

hotfix: https://github.com/island-is/island.is/pull/13364 🔥

fix(service-portal): Overview fallback url Hotfix

---

libs/application/templates/social-insurance-administration/core/src/lib/messages.ts
libs/application/templates/social-insurance-administration/household-supplement/src/fields/Review/review-groups/BaseInformation.tsx
libs/application/templates/social-insurance-administration/household-supplement/src/forms/HouseholdSupplementForm.ts
libs/application/templates/social-insurance-administration/household-supplement/src/forms/Prerequisites.ts
libs/application/templates/social-insurance-administration/household-supplement/src/lib/HouseholdSupplementTemplate.ts
libs/application/templates/social-insurance-administration/household-supplement/src/lib/constants.ts
libs/application/templates/social-insurance-administration/household-supplement/src/lib/householdSupplementUtils.ts

- Add applicant and spouse info

feat(household-suppliment): Add applicant and spouse info

---

apps/web/screens/LifeEventPage/LifeEventPage.tsx
apps/web/screens/LifeEventPage/config.ts

So that a custom message can be displayed when a user opens up the 'ad-eldast' chat window
This was requested by Digital Iceland

feat(web): Change chat config for 'ad-eldast' life event

---

libs/application/templates/social-insurance-administration/additional-support-for-the-elderly/src/forms/AdditionalSupportForTheElderlyForm.ts
libs/application/templates/social-insurance-administration/additional-support-for-the-elderly/src/forms/Prerequisites.ts

change period section title in pre and form for application additional support for the elderly

fix(tr): change period section title

---

libs/service-portal/signature-collection/src/screens/SigneeView/index.tsx

fix(service-portal): sc tweak for signee empty

---

libs/application/templates/aosh/change-machine-supervisor/src/lib/ChangeMachineSupervisorTemplate.ts
libs/feature-flags/src/lib/features.ts

fix(ChangeMachineSupervisor): Adding feature flag for changeMachineSupervisor application

---

apps/services/auth/ids-api/infra/ids-api.ts
apps/services/user-notification/esbuild.json
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml
libs/clients/user-profile/src/lib/userProfileClient.config.ts

Apply following fixes from main to fix release 27.1.0
- #13394 
- #13395 
To fix release.
N/A

fix(user-profile,user-notification): Fix user profile and notification

---

apps/services/user-notification/infra/user-notification.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

Adding missing env secret for NationalRegistry B2C client.
Required for the service to function.
N/A

fix(user-notification): Adding NatReg B2C secret env var.

---

apps/services/user-notification/infra/user-notification.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

See PR title
To fix service startup.
N/A

fix(user-notification): Adding NatReg B2C secret env var. (#13404)

---

apps/services/user-notification/infra/user-notification.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

Add IDS client config for the service infra. Technically its only required by the worker, but we need to refactor the module setup of the notifications service a bit, and I don´t want to do that in a rush.
To fix the service to be able to startup.
N/A

fix(user-notifications): Add IDS client config env var for service infra

---

apps/services/user-notification/infra/user-notification.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

Apply #13414 to pre release
To unblock release.
N/A

fix(user-notification): Add IDS client config env var for service infra.

---

libs/application/templates/energy-funds/src/dataProviders/index.ts
libs/application/templates/energy-funds/src/forms/EnergyFundsForm/InformationSection/UserInformation.ts
libs/application/templates/energy-funds/src/forms/Prerequisites/index.ts
libs/application/templates/energy-funds/src/lib/EnergyFundsTemplate.tsx

fix(energy-fund): Change to identity api (#13397)

---

apps/services/auth/ids-api/infra/ids-api.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml

Apply #13425 to release
To unblock IDS in release.
N/A

fix(auth-ids-api): String needs to be json string for user profile client scope.

---

libs/application/template-api-modules/src/lib/modules/templates/signature-collection/signature-list-creation/signature-list-creation.service.ts

fix(signature-collection): catch email

---

libs/island-ui/core/src/lib/IconRC/iconMap.ts
libs/island-ui/core/src/lib/IconRC/icons/SwapVertical.tsx
libs/portals/admin/signature-collection/src/lib/messages.ts
libs/portals/admin/signature-collection/src/screens/List/components/signees.tsx
libs/portals/admin/signature-collection/src/screens/List/components/sortSignees/index.tsx

fix(admin): sorting signatures

---

libs/clients/signature-collection/src/lib/signature-collection.service.ts
libs/clients/signature-collection/src/lib/types/collection.dto.ts

fix(signature-collection): expired collection 

---

apps/judicial-system/web/pages/_app.tsx

[Asana](https://app.asana.com/0/1199153462262248/1206359764638961/f)
Add RUM monitoring
To monitor frontend errors in datadog

chore(j-s): Add RUM monitoring

---

libs/application/template-api-modules/src/lib/modules/templates/energy-funds/energy-funds.service.ts
libs/application/templates/energy-funds/src/fields/SelectVehicle/VehicleCheckboxField.tsx

fix(energy-fund): energy fund itemcode added

---

apps/services/user-notification/infra/user-notification.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

chore: update release resource limit

---

.github/workflows/pullrequest.yml
.github/workflows/push.yml

chore: test summary

---

apps/web/infra/web.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
infra/src/dsl/dsl.ts

ci: Adding readiness and liveliness delay and timout parameters

---

.github/CODEOWNERS

Update codeowners
Forgot to update in PR: https://github.com/island-is/island.is/pull/13459

chore(user-notification): Update codeowners

---

libs/content-search-indexer/src/lib/cache-invalidation.service.ts

chore(search-indexer): Improve cache invalidation logs

---

apps/web/components/Organization/Wrapper/Themes/SAkTheme/SAkHeader.css.ts
apps/web/components/Organization/Wrapper/Themes/SAkTheme/SAkHeader.tsx

feat(web): Change SAk header

---

apps/application-system/form/src/auth.ts
apps/portals/admin/src/auth.ts

Adding scopes to auth files for admin portal and application system.

fix(signature-collection): add scopes to auth files

---

libs/content-search-indexer/src/lib/cache-invalidation.service.ts

fix(search-indexer): Log textual response from cache invalidation endpoint

---

libs/application/template-api-modules/src/lib/modules/templates/estate/utils/processUploadData.ts

fix(application-estate): Estate unconditional marshalling (#13495)

---

apps/air-discount-scheme/api/infra/api.ts
apps/air-discount-scheme/backend/infra/backend.ts
apps/air-discount-scheme/web/infra/web.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

chore: reduced scaling from requests for ads

---

apps/services/user-notification/infra/user-notification.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

chore: only allow 2 notification workers to run

---

apps/services/user-notification/infra/user-notification.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

Temporarily disable user-notification-worker
Because it has a major bug.

fix: Disable user-notification-worker

---

apps/services/search-indexer/infra/search-indexer-service.ts
apps/web/infra/web.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
libs/content-search-indexer/src/lib/cache-invalidation.service.ts

fix(search-indexer): Call internal web link when invalidating cache

---

apps/services/user-notification/infra/user-notification.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

fix: Min replica needs to be >=1

---

apps/services/user-notification/src/app/modules/notifications/messageProcessor.service.spec.ts
apps/services/user-notification/src/app/modules/notifications/messageProcessor.service.ts

Apply PR #13523 to release
To fix user notification
N/A

fix(user-notification): Hotfix user notification worker

---

apps/services/user-notification/infra/user-notification.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

chore(infra): Scale user-notification-worker up following latest fix

---

apps/services/user-notification/infra/user-notification.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

chore(infra): Set max replicacount for user-notification worker to 3

---

apps/services/user-notification/infra/user-notification.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
infra/src/uber-charts/islandis.ts

ci: add user-notification-cleanup-worker to chart

---

libs/content-search-indexer/src/lib/cache-invalidation.service.ts
libs/content-search-indexer/src/lib/indexing.service.ts

chore(search-indexer): Remove logs and cache invalidation delay

---

libs/application/templates/healthcare-license-certificate/src/lib/HealthcareLicenseCertificateTemplate.ts

fix(healthcare-licence-certificate): shortened lifecycle

---

apps/judicial-system/web/src/components/Table/PastCasesTable/PastCasesTable.tsx

Same as #13507, just forgot it in one place..

fix(j-s): Remove margin from single tags in past cases table

---

libs/clients/signature-collection/src/lib/signature-collection.service.ts

fix(signature-collection): filter not started collections

---

apps/web/components/connected/HousingBenefitCalculator/SpecificHousingBenefitSupportCalculator.tsx
apps/web/components/connected/HousingBenefitCalculator/index.ts
apps/web/screens/queries/HousingBenefitCalculator.ts
apps/web/utils/richText.tsx
libs/api/domains/housing-benefit-calculator/src/lib/dto/specificSupportCalculation.input.ts
libs/api/domains/housing-benefit-calculator/src/lib/housing-benefit-calculator.resolver.ts
libs/clients/housing-benefit-calculator/src/clientConfig.json
libs/clients/housing-benefit-calculator/src/lib/housing-benefit-calculator.service.ts

https://github.com/island-is/island.is/pull/13558

feat(web): Hotfix - Housing benefit calculator for specific support

---

infra/package.json
infra/yarn.lock

fix: revert infra version upgrades

---

libs/application/templates/estate/src/dataProviders/EstateNoticeProvider.ts
libs/application/templates/estate/src/dataProviders/index.ts
libs/application/templates/estate/src/forms/Prerequisites.ts
libs/application/templates/estate/src/lib/EstateTemplate.ts
libs/application/templates/estate/src/lib/dataSchema.ts
libs/application/templates/estate/src/lib/messages.ts

fix(application-estate): Estate application pre collection

---

libs/application/templates/estate/src/forms/Sections/announcerInfo.ts
libs/application/templates/estate/src/lib/dataSchema.ts

autonomous radio should have a default value

fix(estate): add default value to autonomous radio

---

libs/application/templates/estate/src/lib/dataSchema.ts
libs/application/templates/estate/src/lib/messages.ts

user should be able to advance the application, if not autonomous

chore(estate): add error message when not autonomous is selected

---

apps/services/auth/ids-api/infra/identity-server.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml

Add urls for application system to allowed redirect urls. Add localhost urls to allowed urls on dev.
So the application system can integrate with user profile collection on the IDS.

feat(ids): Add application system urls. Add localhost to dev.

---

.github/actions/cache/action.yml
.github/workflows/config-values.yaml
.github/workflows/external-checks.yml
.github/workflows/pullrequest.yml
.github/workflows/push.yml

ci: bring back islandis custom cache

---

.github/actions/cache/action.yml
.github/workflows/config-values.yaml
.github/workflows/external-checks.yml
.github/workflows/pullrequest.yml
.github/workflows/push.yml

- ci: bring back islandis super cache (#13623)
- ci: simplify node and generated files cache key gen (#13624)

fix: actions cache revert

---

libs/clients/signature-collection/src/lib/signature-collection.config.ts

fix(signature-collection): Add scope to admin

---

libs/clients/signature-collection/src/lib/signature-collection.config.ts

fix(signature-collection): reverting scope

---

apps/services/university-gateway/infra/university-gateway.ts
apps/services/university-gateway/src/app/modules/program/internalProgram.service.ts
charts/islandis/values.prod.yaml

Worker now runs every hour on prod and has improved error handling.

feat(university-gateway): Update worker schedule and add error resiliency

---

apps/consultation-portal/graphql/queries.graphql.ts
apps/consultation-portal/screens/Case/components/CaseOverview/CaseOverview.tsx
apps/consultation-portal/screens/Home/components/Cards/Cards.tsx
apps/consultation-portal/types/interfaces.ts
libs/api/domains/consultation-portal/src/lib/models/caseItemResult.model.ts
libs/api/domains/consultation-portal/src/lib/models/caseResult.model.ts
libs/clients/consultation-portal/src/clientConfig.json

https://veflausnir.atlassian.net/browse/KAM-2111
https://github.com/island-is/island.is/pull/13680
We should not show created date but publishOnWeb date

fix(consultation-portal): Fix/kam2111

---

apps/web/next.config.js
apps/web/screens/UniversitySearch/LandingPage.tsx

fix(university-gateway): changing reroute to haskolanam

---

apps/web/screens/UniversitySearch/LandingPage.tsx

fix(university-gateway): show footer false

---

libs/application/templates/announcement-of-death/src/fields/RealEstateRepeater/index.tsx
libs/application/templates/announcement-of-death/src/forms/overviewSections.ts

fix(application-aod): Fix property shares

---

libs/portals/admin/signature-collection/src/screens/AllLists/index.tsx
libs/portals/admin/signature-collection/src/screens/List/index.tsx
libs/service-portal/signature-collection/src/components/SignedList/index.tsx
libs/service-portal/signature-collection/src/lib/messages.ts

and hiding "úrvinnslu lokið" until the endpoints are ready

fix(signature-collection): nondigital signature tag in service-portal

---

libs/application/template-api-modules/src/lib/modules/templates/passport/passport.service.ts

Increasing observability of onsubmit event

feat(application-system): Logging onsubmit application

---

libs/api/domains/signature-collection/src/lib/decorators/acessRequirement.decorator.ts
libs/api/domains/signature-collection/src/lib/decorators/needsOwner.decorator.ts
libs/api/domains/signature-collection/src/lib/guards/userAccess.guard.ts
libs/api/domains/signature-collection/src/lib/signatureCollection.resolver.ts

Restrict access of actors for users who are not candidates.

feat(signature-collection): restrict access for actors for regular users

---

libs/api/domains/signature-collection/src/lib/models/signature.model.ts
libs/api/domains/signature-collection/src/lib/models/signatureList.model.ts
libs/api/domains/signature-collection/src/lib/signatureCollection.resolver.ts
libs/api/domains/signature-collection/src/lib/signatureCollection.service.ts
libs/application/template-api-modules/src/lib/modules/templates/signature-collection/signature-list-signing/signature-list-signing.service.ts
libs/application/templates/signature-collection/signature-list-signing/src/lib/errors.ts
libs/clients/signature-collection/src/clientConfig.json
libs/clients/signature-collection/src/lib/signature-collection-admin.service.ts
libs/clients/signature-collection/src/lib/signature-collection-manager.service.ts
libs/clients/signature-collection/src/lib/signature-collection-shared.service.ts
libs/clients/signature-collection/src/lib/signature-collection.service.ts
libs/clients/signature-collection/src/lib/signature-collection.types.ts
libs/clients/signature-collection/src/lib/types/list.dto.ts
libs/clients/signature-collection/src/lib/types/signature.dto.ts
libs/clients/signature-collection/src/lib/types/success.dto.ts
libs/clients/signature-collection/src/lib/types/user.dto.ts
libs/portals/admin/signature-collection/src/screens/AllLists/components/compareLists/compareLists.graphql
libs/portals/admin/signature-collection/src/screens/List/getListSignees.graphql
libs/portals/admin/signature-collection/src/screens/List/index.tsx
libs/service-portal/signature-collection/src/components/SignedList/index.tsx
libs/service-portal/signature-collection/src/hooks/graphql/queries.ts
libs/service-portal/signature-collection/src/hooks/index.ts
libs/service-portal/signature-collection/src/lib/messages.ts
libs/service-portal/signature-collection/src/screens/SigneeView/index.tsx

feat(signed-collection): singedLists and canUnsign

---

libs/api/domains/signature-collection/src/lib/models/status.model.ts
libs/api/domains/signature-collection/src/lib/signatureCollectionAdmin.resolver.ts
libs/api/domains/signature-collection/src/lib/signatureCollectionAdmin.service.ts
libs/clients/signature-collection/src/clientConfig.json
libs/clients/signature-collection/src/lib/signature-collection-admin.service.ts
libs/clients/signature-collection/src/lib/types/collection.dto.ts
libs/clients/signature-collection/src/lib/types/list.dto.ts

Add status endpoints for collection and list. 
Toggle review state and process collection endpoint.

feat(signature-collection): Collection and list status, toggle review and process

---

libs/api/domains/vehicles/src/models/getVehicleMileage.model.ts
libs/service-portal/assets/src/screens/VehicleMileage/VehicleDetail.graphql
libs/service-portal/assets/src/screens/VehicleMileage/VehicleMileage.tsx

Update number mileage inputs
Forgot to update put in previous PR.
Number assertion is needed for inputs in post+put.

fix(service-portal): Update number mileage inputs

---

libs/api/domains/vehicles/src/models/getVehicleMileage.model.ts
libs/service-portal/assets/src/screens/VehicleMileage/VehicleDetail.graphql
libs/service-portal/assets/src/screens/VehicleMileage/VehicleMileage.tsx

fix(service-portal): Hotfix - Update number mileage inputs

---

apps/application-system/api/infra/application-system-api.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

add UNIVERSITY_GATEWAY_API_URL to env variables
fixing error

fix(university-gateway): adding university-gateway-url to application-system env variables

---

libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils/mappers.ts
libs/application/templates/inheritance-report/src/fields/CalculationsOfTotal/CalculateTotalDebts/index.tsx
libs/application/templates/inheritance-report/src/fields/ReportFieldsRepeater/index.tsx
libs/application/templates/inheritance-report/src/forms/sections/debts.ts
libs/application/templates/inheritance-report/src/lib/dataSchema.ts
libs/application/templates/inheritance-report/src/types.ts

https://app.asana.com/0/1204431115744096/1205990261973349
This is now just a single input field

chore(inheritance-report): remove repeater for public charges value

---

libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils/mappers.ts
libs/application/templates/announcement-of-death/src/forms/draft/subSectionProperties.ts
libs/application/templates/inheritance-report/src/fields/ReportFieldsRepeater/index.tsx
libs/application/templates/inheritance-report/src/forms/OverviewSections/OverviewAssets.ts
libs/application/templates/inheritance-report/src/forms/sections/assets.ts
libs/application/templates/inheritance-report/src/lib/dataSchema.ts
libs/application/templates/inheritance-report/src/lib/messages.ts
libs/application/templates/inheritance-report/src/lib/utils/helpers.spec.ts
libs/application/templates/inheritance-report/src/lib/utils/helpers.ts
libs/application/templates/inheritance-report/src/types.ts

https://app.asana.com/0/1204431115744096/1206526308524914

chore(inheritance-report): add property share and more misc changes/fixes

---

charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
charts/judicial-system/values.dev.yaml
charts/judicial-system/values.prod.yaml
charts/judicial-system/values.staging.yaml
infra/src/dsl/output-generators/map-to-helm-values.ts
infra/src/dsl/pdb.spec.ts

* chore(infra): Tune down PDB strictness
* chore: update test
---------
Co-authored-by: andes-it <builders@andes.is>

chore(infra): Tune down PDB strictness (#13775)

---

libs/application/templates/parental-leave/src/lib/dataSchema.ts

Remove validation
Is not needed anymore

fix(parental-leave): Removed employer selfEmployed file from dataSchema

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx

feat(web): Use default footer for social insurance administration (TR)

---

libs/application/templates/parental-leave/src/fields/Duration/Duration.tsx
libs/application/templates/parental-leave/src/fields/PeriodPercentage/PeriodPercentage.tsx

fix(parental-leave): Fix duration error

---

libs/application/templates/parental-leave/src/fields/Duration/Duration.tsx
libs/application/templates/parental-leave/src/fields/PeriodPercentage/PeriodPercentage.tsx

* fix duration error
* Fixed dependency array
---------

fix(parental-leave): Fix duration error (#13792)

---

apps/services/sessions/docker-compose.yml
apps/services/sessions/infra/sessions.ts
apps/services/sessions/local-db/extensions.sql
apps/services/sessions/migrations/20240214153321-clear-ip-location-column.js
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
libs/service-portal/sessions/src/components/LogTable/LogTable.css.ts
libs/service-portal/sessions/src/components/LogTable/LogTable.tsx
libs/service-portal/sessions/src/components/LogTable/LogTableMobile.tsx
libs/service-portal/sessions/src/lib/messages.ts

Apply #13787  and #13772 to release branch .
To hotfix production.
N/A

fix(services-sessions): Fix geoip update and UI tweaks

---

libs/service-portal/sessions/src/components/LogTable/LogTableMobile.tsx
libs/service-portal/sessions/src/lib/messages.ts

The table headers for expended components where wrong, this is a fix for that
fix translations

fix(sessions): Fix translation strings

---

libs/api/domains/communications/src/lib/emailTemplates/serviceWebForms.ts

This was requested by Digital Iceland

chore(web): Change email for transport authority service web contact form

---

libs/service-portal/assets/src/lib/messages.ts
libs/service-portal/assets/src/screens/Overview/Overview.tsx

Update recycle car url, add to cms
Someone (me) forgot to add this to the CMS when we were adding all the urls for vehicles.

fix(service-portal): Update recycle car url, add to CMS

---

libs/service-portal/assets/src/lib/messages.ts
libs/service-portal/assets/src/screens/Overview/Overview.tsx

hotfix https://github.com/island-is/island.is/pull/13810 🔥

fix(service-portal): hotfix - Update recycle car url

---

libs/api/domains/intellectual-properties/src/lib/models/intellectualProperty.model.ts
libs/service-portal/assets/src/screens/IntellectualPropertiesOverview/IntellectualPropertiesOverview.graphql
libs/service-portal/assets/src/screens/IntellectualPropertiesOverview/IntellectualPropertiesOverview.tsx

fix(ip): Fix query

---

apps/services/sessions/migrations/20240216101538-change-user-agent-column-datatype.js
apps/services/sessions/src/app/sessions/constants.ts
apps/services/sessions/src/app/sessions/session.model.ts
apps/services/sessions/src/app/sessions/sessions.service.spec.ts
apps/services/sessions/src/app/sessions/sessions.service.ts
libs/service-portal/sessions/src/components/LogTable/LogTableMobile.tsx
libs/service-portal/sessions/src/lib/messages.ts

Fixes: 
* Fixtranslation strings: [Here 🔗 ](https://github.com/island-is/island.is/pull/13802)
* Session column too large values: [Here 🔗 ](https://github.com/island-is/island.is/pull/13811)

fix(sessions): Hotfix - Sessions translations and large column

---

libs/api/domains/intellectual-properties/src/lib/models/intellectualProperty.model.ts
libs/service-portal/assets/src/screens/IntellectualPropertiesOverview/IntellectualPropertiesOverview.graphql
libs/service-portal/assets/src/screens/IntellectualPropertiesOverview/IntellectualPropertiesOverview.tsx

fix(ip): Hotfix - ip query

---

apps/services/university-gateway/migrations/20240215161647-change-program-duration-type.js
apps/services/university-gateway/src/app/modules/program/model/program.ts

fix(university-gateway): Change data type of Program.durationInYears from int to float

---

libs/application/template-api-modules/src/lib/modules/templates/signature-collection/signature-list-creation/emailGenerators/applicationSubmitted.ts
libs/clients/signature-collection/src/lib/signature-collection-admin.service.ts
libs/clients/signature-collection/src/lib/signature-collection.service.ts
libs/clients/signature-collection/src/lib/signature-collection.types.ts
libs/clients/signature-collection/src/lib/types/area.dto.ts
libs/clients/signature-collection/src/lib/types/bulkUpload.dto.ts
libs/clients/signature-collection/src/lib/types/collection.dto.ts
libs/clients/signature-collection/src/lib/types/list.dto.ts
libs/clients/signature-collection/src/lib/types/user.dto.ts
libs/service-portal/signature-collection/src/components/SignedList/index.tsx
libs/service-portal/signature-collection/src/hooks/graphql/queries.ts
libs/service-portal/signature-collection/src/screens/CandidateView/index.tsx

fix(signature-collection): fixes for testing

---

apps/system-e2e/README.md

Add a readme how to test with mountebank
It is a great tool. Should be used more often.
Top hat emoji is mountebank emoji 🎩

chore(system-e2e): Add mountebank Readme

---

apps/services/university-gateway/migrations/20240212234719-modify-options-in-program_extra_application_field.js
apps/services/university-gateway/src/app/modules/program/model/programExtraApplicationField.ts
libs/clients/university-application/university-of-iceland/src/lib/utils/mapUglaPrograms.ts

fix(university-gateway): Change data type of Program.program_extra_application_field.options from string to jsonb

---

apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculator.css.ts
apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculator.tsx
apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculatorResults.tsx
apps/web/screens/Organization/SocialInsuranceAdministration/translationStrings.ts
apps/web/screens/Organization/SocialInsuranceAdministration/utils.ts
libs/api/domains/social-insurance/src/lib/dtos/pensionCalculation.input.ts
libs/api/domains/social-insurance/src/lib/utils.ts

feat(web): Swap out datepicker for select components in pension calculator

---

charts/islandis/values.prod.yaml
infra/src/dsl/xroad.ts

chore(workpoint-arborg): Update prod url

---

apps/financial-aid/open-api/src/app/app.config.ts
libs/portals/admin/signature-collection/src/lib/messages.ts
libs/portals/admin/signature-collection/src/screens/AllLists/AllLists.loader.ts
libs/portals/admin/signature-collection/src/screens/AllLists/index.tsx
libs/portals/admin/signature-collection/src/screens/List/List.loader.ts
libs/portals/admin/signature-collection/src/screens/List/components/paperUpload/index.tsx
libs/service-portal/signature-collection/src/screens/CandidateView/index.tsx
libs/service-portal/signature-collection/src/screens/SigneeView/index.tsx
libs/shared/connected/src/lib/SignatureLists/SignatureLists.tsx

fix(signature-collection): Minor fixes after testing 20.02

---

apps/services/auth/ids-api/infra/identity-server.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml

chore(ids): Set dd runtime metrics env var to true

---

libs/portals/admin/signature-collection/src/screens/AllLists/index.tsx
libs/portals/admin/signature-collection/src/screens/List/components/extendDeadline/index.tsx
libs/portals/admin/signature-collection/src/screens/List/components/listInfoAlert/index.tsx
libs/portals/admin/signature-collection/src/screens/List/components/signees.tsx
libs/portals/admin/signature-collection/src/screens/List/index.tsx

fix(signature-collection): adding candidate id to admin

---

libs/portals/admin/signature-collection/src/screens/AllLists/index.tsx
libs/portals/admin/signature-collection/src/screens/List/index.tsx

fix(signature-collections): compare lists fix

---

libs/application/templates/parental-leave/src/lib/parentalLeaveClientUtils.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveTemplateUtils.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

Notion: https://www.notion.so/Code-standard-Function-syntax-86d5c6d562dd4ca88ea3a2ea7eecd80b

fix(parental-leave): Change functions to const

---

apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Indictment.tsx
package.json
yarn.lock

[Asana](https://app.asana.com/0/1199153462262248/1206609756562387/f)
Update package `beygla` to the newest version.
The newest version includes a `strict` mode that does not decline names unless they are Icelandic. This is a feature we need in the judicial-system.

chore(j-s): Update beygla package

---

apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequestAppSys.resolver.ts
apps/skilavottord/ws/src/app/modules/samgongustofa/samgongustofa.service.ts
apps/skilavottord/ws/src/app/modules/samgongustofa/test/samgongustofa.service.spec.ts
apps/skilavottord/ws/src/app/modules/vehicle/vehicleAppSys.resolver.ts
apps/skilavottord/ws/src/app/modules/vehicleOwner/vehicleOwnerAppSys.resolver.ts

Hotfix from
https://github.com/island-is/island.is/pull/13870
* Added logger to get more details of what is happening
* Removed commented code
* Fix unit test issues
---------

fix(skilavottord):  Adding more logger for debug purpose

---

apps/judicial-system/web/src/routes/CourtOfAppeal/WithdrawnAppealCase/WithdrawnAppealCase.strings.ts
apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
apps/judicial-system/web/src/routes/Shared/Cases/useFilter.tsx
apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
apps/judicial-system/web/src/utils/hooks/useSections/index.ts
apps/judicial-system/web/src/utils/hooks/useSections/useSections.spec.tsx

[Asana](https://app.asana.com/0/1199153462262248/1205942829380443/f)
Fixes issues with form stepper in the PR above
Bugs

fix(j-s): Form stepper fixes

---

libs/service-portal/core/src/lib/messages.ts
libs/service-portal/education/src/screens/EducationGraduation/EducationGraduation.tsx
libs/service-portal/education/src/screens/SecondarySchoolCareer/SecondarySchoolCareer.tsx
libs/service-portal/education/src/screens/SecondarySchoolGraduationDetail/SecondarySchoolGraduationDetail.tsx
libs/service-portal/education/src/screens/SecondarySchoolGraduationOverview/SecondarySchoolGraduationOverview.tsx
libs/service-portal/education/src/screens/SecondarySchoolGraduationSingle/SecondarySchoolGraduationSingle.tsx

chore(service-portal): Hotfix - education screens error no data

---

.github/CODEOWNERS

Update co owners for service portal education.
For the past few months we are the only team updating these modules.

chore(service-portal): Update co owners for service portal education

---

apps/web/components/ChatPanel/WatsonChatPanel/WatsonChatPanel.tsx

chore(web): Hide chat panel on print

---

libs/application/templates/passport/src/dataProviders/index.ts

Requirements have been amended to allow applicants to not live in iceland.
Citizenship status is being checked however.

fix(application-passport): Domicile requirements change

---

libs/application/templates/passport/src/dataProviders/index.ts

fix(application-passport):  Domicile requirement change

---

libs/service-portal/education/src/screens/SecondarySchoolCareer/SecondarySchoolCareer.tsx

fix(service-portal): hotfix - Update secondary school namespace

---

apps/web/components/ListViewCard/ListViewCard.tsx
apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudies.css.ts
apps/web/pages/en/university-studies/about-haskolanam-is.tsx
apps/web/screens/UniversitySearch/AboutPage.tsx
apps/web/screens/UniversitySearch/LandingPage.tsx
apps/web/screens/UniversitySearch/UniversitySearch.tsx
apps/web/screens/UniversitySearch/UniversitySearchDetails.tsx
apps/web/screens/UniversitySearch/useSetZIndexOnHeader.tsx
apps/web/utils/useUniversitySearch.tsx

fix(university-gateway): Hotfix for university day

---

libs/application/templates/social-insurance-administration/old-age-pension/src/lib/oldAgePensionUtils.spec.ts
libs/application/templates/social-insurance-administration/old-age-pension/src/lib/oldAgePensionUtils.ts

fix(old-age-pension): Fix Leap Year error in unit test

---

infra/src/secrets.ts

`logger.debug` does not output anything since the LOG_LEVEL is not debug. Therefore we don't get any value.

infra: fix broken secrets output

---

libs/clients/university-application/reykjavik-university/src/clientConfig.json

feat(university-gateway): re-trigger codegen

---

.github/CODEOWNERS
libs/service-portal/signature-collection/src/components/SignedList/index.tsx
libs/service-portal/signature-collection/src/screens/SigneeView/index.tsx
libs/shared/connected/src/lib/SignatureLists/SignatureLists.tsx
libs/shared/connected/src/lib/SignatureLists/useGetSignatureLists.ts

fix(signature-collections): sort candidates

---

apps/services/auth/personal-representative/infra/personal-representative.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml

Add #14010 to release 
To fix personal representative api startup

fix(personal-representative-api): Add missing infra variables for the personal representative api.

---

apps/web/components/connected/GrindavikResidentialPropertyPurchaseCalculator/GrindavikResidentialPropertyPurchaseCalculator.tsx

* To improve the user experience when filling out the form we now autofocus the newly appended loan input field (see videos below)
https://github.com/island-is/island.is/assets/43557895/0c9364f9-2c0f-4cb4-a7b0-7b324b1c43c6
https://github.com/island-is/island.is/assets/43557895/ec8bf088-db5f-417b-9b65-15e82285e79f

feat(web): Grindavík property purchase calculator - Autofocus appended loan input fields

---

apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudies.css.ts
apps/web/screens/UniversitySearch/LandingPage.tsx
apps/web/screens/UniversitySearch/UniversitySearch.tsx
apps/web/screens/UniversitySearch/UniversitySearchDetails.tsx
apps/web/screens/UniversitySearch/UniversitySubPage.tsx

fix(university-gateway): Accessibility on header

---

libs/application/templates/aosh/deregister-machine/src/forms/DeregisterMachineForm/InformationSection/deregisterSubSection.ts

fix(aosh): Making fateOfMachine field required

---

libs/application/templates/aosh/deregister-machine/src/forms/DeregisterMachineForm/InformationSection/deregisterSubSection.ts

fix(aosh): making fateOfMachine as required field

---

libs/application/template-api-modules/src/lib/modules/templates/grindavik-housing-buyout/grindavik-housing-buyout.service.ts
libs/application/templates/grindavik-housing-buyout/src/forms/GrindavikHousingBuyoutForm.ts
libs/application/templates/grindavik-housing-buyout/src/lib/dataSchema.ts
libs/application/templates/grindavik-housing-buyout/src/lib/messages/application.ts
libs/application/templates/grindavik-housing-buyout/src/lib/messages/errors.ts
libs/application/templates/grindavik-housing-buyout/src/utils/loan.ts

fix(ghb): Add loan provider checkbox and remove other one

---

libs/application/template-api-modules/src/lib/modules/templates/grindavik-housing-buyout/grindavik-housing-buyout.service.ts
libs/application/templates/grindavik-housing-buyout/src/forms/GrindavikHousingBuyoutForm.ts
libs/application/templates/grindavik-housing-buyout/src/lib/constants/index.ts
libs/application/templates/grindavik-housing-buyout/src/lib/dataSchema.ts
libs/application/templates/grindavik-housing-buyout/src/lib/messages/application.ts
libs/application/templates/grindavik-housing-buyout/src/lib/messages/approved.ts
libs/application/templates/grindavik-housing-buyout/src/lib/messages/errors.ts
libs/application/templates/grindavik-housing-buyout/src/lib/messages/rejected.ts
libs/application/types/src/lib/Fields.ts
libs/application/ui-fields/src/lib/TableRepeaterFormField/TableRepeaterFormField.tsx

- Add preferred delivery date input
- Add option to pick non-specified loan provider
- Add option to pick preemptive right type

feat(ghb): Preferred delivery date, non-specified loan providers and preemptive-rights

---

apps/web/screens/Regulations/RegulationPage.tsx
libs/clients/regulations/src/lib/regulations.service.ts
libs/clients/regulations/src/lib/regulations.spec.ts

fix(regulations): Hotfix - Show 404 instead of 500 error

---

libs/application/template-api-modules/src/lib/modules/templates/grindavik-housing-buyout/grindavik-housing-buyout.service.ts
libs/application/templates/grindavik-housing-buyout/src/forms/GrindavikHousingBuyoutForm.ts
libs/application/templates/grindavik-housing-buyout/src/lib/constants/index.ts
libs/application/templates/grindavik-housing-buyout/src/lib/dataSchema.ts
libs/application/templates/grindavik-housing-buyout/src/lib/messages/application.ts
libs/application/templates/grindavik-housing-buyout/src/lib/messages/approved.ts
libs/application/templates/grindavik-housing-buyout/src/lib/messages/errors.ts
libs/application/templates/grindavik-housing-buyout/src/lib/messages/rejected.ts
libs/application/types/src/lib/Fields.ts
libs/application/ui-fields/src/lib/TableRepeaterFormField/TableRepeaterFormField.tsx

- Add preferred delivery date input
- Add option to pick non-specified loan provider
- Add option to pick preemptive right type

feat(ghb): Preferred delivery date, non-specified loan providers and preemptive-rights 

---

libs/application/template-api-modules/src/lib/modules/templates/grindavik-housing-buyout/grindavik-housing-buyout.service.ts
libs/application/template-api-modules/src/lib/modules/templates/grindavik-housing-buyout/grindavik-housing-buyout.utils.ts
libs/application/templates/grindavik-housing-buyout/src/fields/AdditionalOwnersOverview/index.tsx
libs/application/templates/grindavik-housing-buyout/src/fields/AdditionalOwnersRepeater/index.tsx
libs/application/templates/grindavik-housing-buyout/src/forms/GrindavikHousingBuyoutForm.ts
libs/application/templates/grindavik-housing-buyout/src/lib/dataSchema.ts
libs/application/templates/grindavik-housing-buyout/src/lib/messages/application.ts
libs/application/templates/grindavik-housing-buyout/src/lib/messages/errors.ts
libs/application/templates/grindavik-housing-buyout/src/sections/applicant.ts
libs/application/templates/grindavik-housing-buyout/src/sections/index.ts

- Add bank information for applicant and other owners
- Move preemptive rights screen

feat(ghb): bankinfo and move preemptive rights

---

libs/api/domains/university-gateway/src/lib/graphql/main.resolver.ts
libs/api/domains/university-gateway/src/lib/graphql/models/program.model.ts
libs/api/domains/university-gateway/src/lib/graphql/models/programFilter.model.ts
libs/api/domains/university-gateway/src/lib/graphql/university.resolver.ts
libs/nest/pagination/src/lib/graphql/paginated.response.ts

We got the call from Digital Iceland to hotfix in this speed improvement for the university related search

chore(university-gateway): Hotfix - Cache graphql calls (#14032)

---

libs/application/templates/passport/src/lib/utils.ts

fix(passport): parentB error fix

---

libs/application/templates/grindavik-housing-buyout/src/forms/GrindavikHousingBuyoutForm.ts
libs/application/templates/grindavik-housing-buyout/src/lib/GrindavikHousingBuyoutTemplate.ts
libs/application/templates/grindavik-housing-buyout/src/lib/constants/index.ts
libs/application/types/src/lib/ApplicationTypes.ts

- Add `uiForms.application` translation namespace
- Add translations for preemptive-rights in overview

fix(ghb): Missing translations

---

libs/application/templates/passport/src/lib/utils.ts

fix(passport): parentB error fix (#14062)

---

libs/api/domains/communications/src/lib/emailTemplates/serviceWebForms.ts

feat(web): Add support category email for district commissioner form on service web (#14068)

---

apps/skilavottord/web/i18n/locales/en.json
apps/skilavottord/web/i18n/locales/is.json
apps/skilavottord/ws/migrations/20240307280301-add-indexes.js
apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.module.ts
apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts
apps/skilavottord/ws/src/app/modules/vehicle/vehicle.service.ts
apps/skilavottord/ws/src/app/modules/vehicleOwner/vehicleOwner.module.ts
apps/skilavottord/ws/src/app/services/icelandicTransportAuthority.module.ts
apps/skilavottord/ws/src/app/services/icelandicTransportAuthority.services.ts

Hotfix
Fix slow queries in skilavottord (#14051)
Added check for current owner when recycling company deregister vehicle (#13997)

fix(skilavottord): Fix slow queries in skilavottord and check current owner

---

apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts

[TRS-12](https://dit-iceland.atlassian.net/browse/TRS-12)
Rollback previous changes 
We need to rollback changes since we don't have access to Samgöngustofu REST service

fix(skilavottord): Rollback owner check

---

apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts

fix(skilavottord): Rollback owner check (#14078)

---

apps/web/screens/UniversitySearch/UniversitySearch.tsx
apps/web/utils/useUniversitySearch.tsx

https://github.com/island-is/island.is/pull/14071

feat(university-gateway): change search results, make more fair

---

libs/api/domains/energy-funds/src/lib/energyFunds.service.ts
libs/api/domains/energy-funds/src/lib/graphql/models/getVehicleWithGrant.model.ts
libs/application/template-api-modules/src/lib/modules/templates/energy-funds/energy-funds.service.ts
libs/application/templates/energy-funds/src/graphql/queries.ts
libs/application/ui-fields/src/lib/FindVehicleFormField/FindVehicleFormField.tsx

fix(energy-funds): submit object wrong and adding 2 field in findVehicleFormField

---

apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.strings.ts
apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.tsx

Fix duplicate contentful string

fix(j-s): Duplicate contentful strings

---

libs/auth-api-lib/migrations/20240227133212-migrate-application-admin-scope.js

https://github.com/island-is/island.is/pull/13998
https://github.com/island-is/island.is/pull/14087

chore(auth-api-lib):migrate application admin scope

---

libs/application/templates/grindavik-housing-buyout/src/forms/GrindavikHousingBuyoutForm.ts
libs/application/templates/grindavik-housing-buyout/src/lib/messages/application.ts

Add description to preemption screen

fix(ghb): Add description to preemption screen

---

apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculator.tsx
apps/web/screens/Organization/SocialInsuranceAdministration/translationStrings.ts

* Removed "Fær meðlag greitt með" field
* Moved "Erlendur grunnlífeyrir field below "Fjármagnstekjur"
* Added placeholder for "Fyrsta örorkumat" and "Fyrsta endurhæfingarmat"
* This was requested by the social insurance administration (Tryggingastofnun)

chore(web): Pension Calculator - change visuals after feedback from social insurance administration

---

libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanApplication.ts
libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanSubmitted.ts
libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/confirmation.ts

Add missing translations for conclusion screen

fix(ctao): Add missing conclusion translations

---

.github/CODEOWNERS

Update CODEOWNERS in collaboration with core team.

chore(document-provider): Update CODEOWNERS

---

libs/service-portal/documents/src/screens/Documents.loader.ts

fix(service-portal): Update single doc display (#14179)

---

libs/shared/connected/src/lib/SignatureLists/SignatureLists.tsx

fix(signature-collections): small revert on endtime display

---

libs/shared/connected/src/lib/SignatureLists/SignatureLists.tsx

fix(signature-collections): small revert on endtime display (#14182)

---

infra/scripts/container-scripts/create-db.sh

chore: fix DB_NAME assignment

---

infra/scripts/container-scripts/create-db.sh

ci: fix unbound var

---

infra/scripts/container-scripts/create-db.sh

ci: fix create-db unbound var

---

libs/island-ui/core/src/lib/IconRC/icons/TimerOutline.tsx

Fixing errors caused by dashed seperated properties in svg file.
To fix console errors on the client

fix(ui-core): Set correct properties on icon

---

apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.tsx

fix(j-s): Overview

---

libs/api/domains/fishing-license/src/graphql/models/fishing-license-list-options.model.ts

Make optional fields nullable from graphQL 
Fields are marked as optional and can be null from api. 

fix(Application-glf): Optional properties

---

libs/application/templates/driving-license/src/forms/draft/draft.ts
libs/application/templates/driving-license/src/forms/draft/subSectionPhone.ts

fix(application-driving-license): Fix missing phone section (#14216)

---

apps/contentful-apps/pages/fields/link-group-link-field.tsx

feat(contentful-apps): Allow link references for link group fields (#14215)

---

libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
libs/service-portal/documents/src/screens/Documents.loader.ts

Update display single only on url match
Now we're trying too often.

fix(service-portal): Update display single only on url match

---

libs/api/domains/license-service/src/lib/mappers/huntingLicenseMapper.ts
libs/clients/hunting-license/src/lib/huntingLicenseClient.types.ts

fix(hunting-license): missing link

---

libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
libs/service-portal/documents/src/screens/Documents.loader.ts

continue: https://github.com/island-is/island.is/pull/14223

fix(service-portal): document display single param

---

libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
libs/service-portal/documents/src/screens/Documents.loader.ts

hotfix: https://github.com/island-is/island.is/pull/14225

fix(service-portal-documents): hotfix - single doc path

---

libs/api/domains/communications/src/lib/emailTemplates/serviceWebForms.ts

feat(web): Change which email "umferd" service web form submissions get sent to

---

libs/api/domains/communications/src/lib/emailTemplates/serviceWebForms.ts

feat(web): Change which email "umferd" service web form submissions get sent to (#14228)

---

libs/api/domains/social-insurance/src/lib/socialInsurance.service.ts
libs/clients/social-insurance-administration/src/lib/socialInsuranceAdministrationClient.service.ts
libs/service-portal/social-insurance-maintenance/src/lib/messages.ts
libs/service-portal/social-insurance-maintenance/src/screens/PaymentPlan/PaymentPlan.tsx

* Fix empty state display in service portal
* Change logic in client pertaining to null responses
* Better handling

fix(social-insurance-administration): empty states

---

apps/contentful-apps/pages/fields/link-group-link-field.tsx

This reverts commit d2d727a8786b9431ef7e9e3ba6a09261ac7d0fd0.

fix(contentful-apps): revert Handle case when link group is created separately (#14244)

---

libs/shared/connected/src/lib/SignatureLists/SignatureLists.tsx

* fix(web): signature collection restruct
---------

fix(web): signature collection restruct (#14235)

---

libs/api/domains/fishing-license/src/graphql/models/fishing-license-list-options.model.ts

Reverts island-is/island.is#14214

"fix(Application-glf): revert Optional properties"

---

libs/api/domains/license-service/src/lib/licenseService.service.ts

Fix pkpass verification.
Currently it can only verify driving licenses (which has both functions) but not other pkpass licenses.

fix(api): Fix pkpass verification

---

.github/CODEOWNERS
.github/actions/cache/action.yml
.github/actions/unit-test/action.yml
.github/workflows/config-values.yaml
.github/workflows/pullrequest.yml
.github/workflows/push.yml

Pull in all changes in `.github/*` from https://github.com/island-is/island.is/commit/1349cdb2c41706dcb3f4132f04ca2224513b0253 for reverting CI cache changes.

ci: revert cache changes

---

libs/api/domains/license-service/src/lib/licenseService.service.ts

fix(api): Fix pkpass verification [HOTFIX]

---

apps/contentful-apps/pages/fields/link-group-link-field.tsx

fix(contentful-apps): Handle case when link group is created separately (#14260)

---

apps/web/components/Organization/Wrapper/Themes/DigitalIcelandTheme/DigitalIcelandHeader.tsx
apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunAusturlandsTheme/HeilbrigdisstofnunAusturlandsHeader.tsx
apps/web/components/Organization/Wrapper/Themes/LandkjorstjornTheme/LandskjorstjornHeader.tsx
apps/web/components/Organization/Wrapper/Themes/RettindagaeslaFatladsFolksTheme/RettindagaeslaFatladsFolksHeader.tsx
apps/web/components/Organization/Wrapper/Themes/SjukratryggingarTheme/SjukratryggingarHeader.tsx
apps/web/components/Organization/Wrapper/Themes/TransportAuthorityTheme/TransportAuthorityHeader.tsx
apps/web/components/Project/Header/DefaultProjectHeader.tsx
apps/web/components/Project/Header/EntryProjectHeader.tsx
apps/web/components/Project/Header/GrindavikProjectHeader.tsx
apps/web/components/Project/Header/UkraineProjectHeader.tsx

The header main title should be h1 for organization and project pages

chore(web): Set header text to h1

---

apps/web/components/DefaultHeader/DefaultHeader.tsx
apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/Themes/HljodbokasafnIslandsTheme/HljodbokasafnIslandsHeader.tsx
apps/web/components/Organization/Wrapper/Themes/VinnueftirlitidTheme/VinnueftirlitidHeader.tsx
apps/web/screens/Project/components/ProjectHeader/ProjectHeader.tsx
apps/web/screens/queries/Organization.tsx
apps/web/screens/queries/Project.tsx
libs/cms/src/lib/models/organizationTheme.model.ts

feat(web): Hotfix of: Default header - text offset and have the option to set different background on mobile screens (#14300)

---

libs/api/domains/social-insurance/src/lib/models/payment.model.ts
libs/api/domains/social-insurance/src/lib/models/paymentGroup.model.ts
libs/api/domains/social-insurance/src/lib/models/paymentMonth.model.ts
libs/api/domains/social-insurance/src/lib/socialInsurance.service.ts

Tighten up model definitions
Non-nullable warnings

fix(social-insurance): modelling issues

---

libs/api/domains/vehicles/src/utils/basicVehicleInformationMapper.ts
libs/service-portal/assets/src/screens/VehicleDetail/VehicleDetail.tsx

Fix buttons in vehicle detail
remove insurance display for non displayable data
request from SGS

fix(service-portal): Buttons on detail + insurance

---

apps/contentful-apps/pages/fields/link-group-link-field.tsx

fix(contentful-apps): Hotfix - Link group app - Make sure that nothing renders until load is complete (#14329)

---

apps/web/components/Organization/NewsArticle/NewsArticle.tsx

fix(web): Hotfix - News - embedded video goes above floated image (#14331)

---

libs/service-portal/assets/src/lib/messages.ts
libs/service-portal/assets/src/screens/VehicleMileage/VehicleMileage.tsx
libs/service-portal/licenses/src/utils/dataMapper.tsx

hotfix:
https://github.com/island-is/island.is/pull/14356
https://github.com/island-is/island.is/pull/14354

fix(service-portal): hotfix - mileage and type

---

apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculator.tsx

feat(web): Hotfix -Pension Calculator - Remove "has lived abroad" question for disability assessment type of pensions #14363

---

libs/application/templates/transport-authority/order-vehicle-license-plate/src/fields/PickPlateSize.tsx

fix(sgs): Fixing default value for rearplate because of dataschema validation problem

---

apps/web/screens/ServiceWeb/Forms/Forms.tsx
apps/web/screens/queries/ServiceWeb.ts
libs/cms/src/lib/generated/contentfulTypes.d.ts
libs/cms/src/lib/models/serviceWebPage.model.ts

feat(web): Hotfix - Service web contact form disclaimer #14388

---

libs/application/template-api-modules/src/lib/modules/templates/signature-collection/signature-list-signing/signature-list-signing.service.ts
libs/application/templates/signature-collection/signature-list-signing/src/lib/errors.ts
libs/shared/connected/src/lib/SignatureLists/SignatureLists.tsx
libs/shared/connected/src/lib/SignatureLists/useGetSignatureLists.ts

fix(signature-collections): openlists and area error fixes

---

apps/web/components/ServiceWeb/Background/Background.tsx
apps/web/components/ServiceWeb/Background/Variations/SocialInsuranceAdministration/SocialInsuranceAdministration.css.ts
apps/web/components/ServiceWeb/Background/Variations/SocialInsuranceAdministration/SocialInsuranceAdministration.tsx

feat(web): Hotfix - Social Insurance Administration - Service web header #14402

---

apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculator.tsx

feat(web): Hotfix - Pension Calculator - Offset start month by one (#14393)

---

libs/application/templates/grindavik-housing-buyout/src/lib/GrindavikHousingBuyoutTemplate.ts

chore(gbh):  Extend inReview lifetime

---

libs/api/domains/license-service/src/lib/dto/CreateBarcodeResult.dto.ts
libs/services/license/src/lib/barcode.service.ts

Fix expire time logic in server and app
Date is not guaranteed to be the same on the server and the app

fix(license-service): Fix license barcode expire time

---

apps/native/app/ios/IslandApp/IslandApp.entitlements
apps/web/public/.well-known/apple-app-site-association
apps/web/public/.well-known/assetlinks.json

Hotfix - Add associated domains #14438

feat(web): Hotfix - add associated domains

---

libs/api/domains/transport-authority/src/lib/graphql/models/getCurrentVehicles.model.ts
libs/api/domains/transport-authority/src/lib/transportAuthority.module.ts
libs/api/domains/transport-authority/src/lib/transportAuthority.service.ts
libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/VehiclesField/VehicleRadioField.tsx
libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/VehiclesField/VehicleSelectField.tsx
libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/forms/ChangeCoOwnerOfVehicleForm/InformationSection/vehicleSubSection.ts
libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/graphql/queries.ts
libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/dataSchema.ts
libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/messages/error.ts
libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/shared/types.ts
libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/utils/getSelectedVehicle.ts
libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/VehiclesField/VehicleRadioField.tsx
libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/VehiclesField/VehicleSelectField.tsx
libs/application/templates/transport-authority/change-operator-of-vehicle/src/forms/ChangeOperatorOfVehicleForm/InformationSection/vehicleSubSection.ts
libs/application/templates/transport-authority/change-operator-of-vehicle/src/graphql/queries.ts
libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/dataSchema.ts
libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/messages/error.ts
libs/application/templates/transport-authority/change-operator-of-vehicle/src/shared/types.ts
libs/application/templates/transport-authority/change-operator-of-vehicle/src/utils/getSelectedVehicle.ts
libs/application/templates/transport-authority/order-vehicle-license-plate/src/utils/getSelectedVehicle.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/VehiclesField/VehicleSelectField.tsx
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/forms/TransferOfVehicleOwnershipForm/InformationSection/vehicleSubSection.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/graphql/queries.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/dataSchema.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/messages/error.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/shared/types.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/getSelectedVehicle.ts
libs/application/ui-fields/src/lib/FindVehicleFormField/FindVehicleFormField.tsx
libs/clients/vehicles/project.json
libs/clients/vehicles/src/clientConfig.json

fix(sgs): km registration bug fix/change

---

libs/application/templates/aosh/transfer-of-machine-ownership/src/lib/TransferOfMachineOwnershipTemplate.ts
libs/application/templates/aosh/transfer-of-machine-ownership/src/utils/getExtraData.ts

fix(aosh): Adding extra data to eigendaskipti tækis

---

apps/web/components/ChatPanel/LiveChatIncChatPanel/LiveChatIncChatPanel.tsx
apps/web/components/ChatPanel/types.ts
apps/web/components/Organization/Wrapper/config.ts
apps/web/screens/Article/components/ArticleChatPanel/ArticleChatPanel.tsx
apps/web/screens/Article/components/ArticleChatPanel/config.ts
package.json
yarn.lock

feat(web): Hotfix - Livechat for Administration of Occupational Safety and Health (#14467)

---

apps/application-system/api/infra/application-system-api.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

fix(infra): Adding missing configs for vehicle-mileage xroad

---

apps/services/user-notification/infra/user-notification.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

Add PR #14578 to release
This fixes aws network communciations (along with Andes manual label fixes on the clusters)

fix(user-notification): Fix user notification infra

---

apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.ts

fix(notification-worker): Fix from address in notification email template

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
libs/application/templates/parental-leave/README.md
libs/application/templates/parental-leave/src/fields/EditOrAddEmployersAndPeriodsReview/index.tsx
libs/application/templates/parental-leave/src/forms/EditOrAddEmployersAndPeriods.ts
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveTemplateUtils.ts

[UUFV-346](https://dit-iceland.atlassian.net/browse/UUFV-346)

fix(parental-leave): Employer file upload fix

---

libs/service-portal/information/src/components/PersonalInformation/Forms/ProfileForm/ProfileForm.tsx

Apply #14610 to relese
To fix company onboarding UX

fix(service-portal): Fix onboarding modal for companies

---

libs/api/domains/transport-authority/src/lib/transportAuthority.service.ts

fix(transfer-vehicle-ownership): validation for mileage reading fix

---

libs/api/domains/transport-authority/src/lib/transportAuthority.service.ts

fix(samgongustofa): adding null check to mileage reading

---

apps/web/screens/UniversitySearch/UniversitySearch.css.ts
apps/web/screens/UniversitySearch/UniversitySearch.tsx

https://github.com/island-is/island.is/pull/14630

fix(university-gateway): Showing university icons in search results, cleanup comparison code, mobile fix for query params

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.spec.ts
libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.ts
libs/application/templates/parental-leave/src/lib/dataSchema.ts

[TS-271](https://dit-iceland.atlassian.net/browse/TS-371) and [TS-396](https://dit-iceland.atlassian.net/browse/TS-396)
Adding PR that didn't make the release and removing validation for residence grant file

fix(parental-leave): Remove pension fund and validation

---

libs/application/templates/car-recycling/src/lib/CarRecyclingTemplate.ts

* TRS-14 Add custom to allowedDelegations
Hotfix: #14724
---------

fix(car-recycling): Add custom delegation

---

apps/services/auth/ids-api/infra/ids-api.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml

chore(ids-api): Hotfix ids api cleanup worker infra

---

apps/contentful-apps/pages/fields/link-group-link-field.tsx

fix(contentful-apps): Hotfix - Add retry logic to link group field app (#14753)

---

libs/api/domains/housing-benefits/src/lib/dto/getHmsLoansPaymenthistory.input.ts
libs/clients/hms-housing-benefits/src/clientConfig.json
libs/service-portal/finance/src/components/HousingBenefitsPayments/HousingBenefitsFilter.tsx
libs/service-portal/finance/src/components/HousingBenefitsPayments/HousingBenefitsTable.tsx
libs/service-portal/finance/src/lib/messages.ts
libs/service-portal/finance/src/screens/HousingBenefits/HousingBenefits.tsx
libs/service-portal/finance/src/screens/HousingBenefits/useHousingBenefitsFilters.ts

fix(housing-benefits): hotfix - Update housing benefits filter (#14776)

---

libs/application/templates/driving-license/src/forms/done.ts
libs/application/templates/driving-license/src/forms/prerequisites/sectionApplicationFor.ts
libs/application/templates/driving-license/src/lib/messages.ts
libs/application/templates/driving-license/src/lib/types.ts
libs/application/ui-forms/src/lib/formConclusionSection/formConclusionSection.ts

Hotfix of license requirement and #14735

fix(application-driving-license): Driving license requirements

---

apps/web/components/ActionCategoryCard/ActionCategoryCard.tsx
apps/web/components/ListViewCard/ListViewCard.tsx
apps/web/screens/UniversitySearch/LandingPage.tsx
apps/web/screens/UniversitySearch/UniversitySearch.css.ts
apps/web/screens/UniversitySearch/UniversitySearch.tsx
libs/plausible/src/lib/webEvents.ts

https://github.com/island-is/island.is/pull/14788/

feat(university-gateway): Plausible analytics for Haskolanam + Minor fixes

---

apps/web/public/.well-known/assetlinks.json

This is to allow us to test passkey authentication in test builds.

chore(web): Connect test version of android app to island.is domain [HOTFIX]

---

apps/web/screens/UniversitySearch/UniversitySearch.tsx
libs/plausible/src/lib/webEvents.ts

fix(university-gateway): Fixing localization error and adding shortened id to programs to make them unique + changing filters event

---

apps/api/src/app/graphql-options.factory.ts
apps/web/public/.well-known/assetlinks.json
libs/cache/src/lib/cache.ts

fix: redis timeout

---

apps/api/infra/api.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

fix:  resources 

---

apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts

fix(skilavottord): Comment out owners check

---

libs/auth-api-lib/src/lib/delegations/DelegationConfig.ts

individuals should not be able to grant the delegation @skagafjordur.is/ibuagatt

feat(ids-auth): adding @skagafjordur.is/ibuagatt to delegation config

---

libs/application/template-api-modules/src/lib/modules/templates/aosh/transfer-of-machine-ownership/emailGenerators/applicationRejectedEmail.ts
libs/application/template-api-modules/src/lib/modules/templates/aosh/transfer-of-machine-ownership/transfer-of-machine-ownership.service.ts
libs/application/templates/aosh/change-machine-supervisor/src/forms/ChangeMachineSupervisorForm/InformationSection/machineSubSection.ts
libs/application/templates/aosh/change-machine-supervisor/src/forms/ChangeMachineSupervisorForm/InformationSection/pickMachineSubSection.ts
libs/application/templates/aosh/change-machine-supervisor/src/utils/getSelectedMachine.ts
libs/application/templates/aosh/deregister-machine/src/forms/DeregisterMachineForm/InformationSection/pickMachineSubSection.ts
libs/application/templates/aosh/deregister-machine/src/utils/getSelectedMachine.ts
libs/application/templates/aosh/request-for-inspection/project.json
libs/application/templates/aosh/request-for-inspection/src/forms/RequestMachineForInspectionForm/InformationSection/pickMachineSubSection.ts
libs/application/templates/aosh/request-for-inspection/src/lib/messages/conclusion.ts
libs/application/templates/aosh/request-for-inspection/src/utils/getSelectedMachine.ts
libs/application/templates/aosh/street-registration/src/forms/StreetRegistrationForm/InformationSection/pickMachineSubSection.ts
libs/application/templates/aosh/street-registration/src/utils/getSelectedMachine.ts
libs/application/templates/aosh/transfer-of-machine-ownership/src/fields/Location/index.tsx
libs/application/templates/aosh/transfer-of-machine-ownership/src/fields/Overview/index.tsx
libs/application/templates/aosh/transfer-of-machine-ownership/src/fields/Overview/sections/LocationSection.tsx
libs/application/templates/aosh/transfer-of-machine-ownership/src/forms/Rejected.ts
libs/application/templates/aosh/transfer-of-machine-ownership/src/forms/TransferOfMachineOwnershipForm/InformationSection/buyerSubSection.ts
libs/application/templates/aosh/transfer-of-machine-ownership/src/forms/TransferOfMachineOwnershipForm/InformationSection/pickMachineSubSection.ts
libs/application/templates/aosh/transfer-of-machine-ownership/src/graphql/queries.ts
libs/application/templates/aosh/transfer-of-machine-ownership/src/lib/TransferOfMachineOwnershipTemplate.ts
libs/application/templates/aosh/transfer-of-machine-ownership/src/lib/messages/conclusion.ts
libs/application/templates/aosh/transfer-of-machine-ownership/src/lib/messages/information.ts
libs/application/templates/aosh/transfer-of-machine-ownership/src/utils/getSelectedMachine.ts
libs/application/templates/aosh/transfer-of-machine-ownership/src/utils/isPaymentRequired.ts
libs/application/ui-fields/src/lib/FindVehicleFormField/FindVehicleFormField.tsx
libs/application/ui-forms/src/lib/formConclusionSection/formConclusionSection.ts
libs/clients/work-machines/src/lib/workMachines.service.ts
libs/clients/work-machines/src/lib/workMachines.types.ts

Fixing payment bug for AOSH,
Removing date field,
Fixing Contentful script,
Adding error logs for emails and sms for AOSH,
Few message fixes,
Fixing location component and adding moreInfo text in locationSection

fix(AOSH): Fixing a few minor bugs on AOSH applications

---

libs/application/template-api-modules/src/lib/modules/templates/financial-aid/financial-aid.service.ts

fix(fa): fixing application-system-api adding check on children (#14912)

---

libs/application/templates/new-primary-school/src/fields/Review/review-groups/Parents.tsx
libs/application/templates/new-primary-school/src/fields/Review/review-groups/Relatives.tsx
libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm.ts
libs/application/templates/new-primary-school/src/lib/dataSchema.ts
libs/application/templates/new-primary-school/src/lib/messages.ts
libs/application/templates/new-primary-school/src/lib/newPrimarySchoolUtils.spec.ts
libs/application/templates/new-primary-school/src/lib/newPrimarySchoolUtils.ts
libs/application/templates/new-primary-school/src/types.ts

[TS-799](https://dit-iceland.atlassian.net/browse/TS-799) Implement parent page

feat(new-primary-school):  Implement parent page

---

libs/application/ui-fields/src/lib/FindVehicleFormField/FindVehicleFormField.tsx

fix(SGS): Fixing bug in FindVehicleFormField for Order-Plate

---

libs/service-portal/licenses/src/components/QRCodeModal/PkPass.tsx

fix(licenses): pkpass safari error

---

apps/web/next.config.js

feat(web): Redirects for Social Insurance Administration service web contact page (#14940)

---

.github/actions/dist/main.js
.github/actions/main.ts
.github/workflows/pullrequest.yml
.github/workflows/push.yml
scripts/ci/00_prepare-base-tags.sh
scripts/ci/_nx-affected-targets.sh

Reverts island-is/island.is#14990

Revert "fix: last good build"

---

libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm.ts
libs/application/templates/new-primary-school/src/lib/dataSchema.ts
libs/application/templates/new-primary-school/src/lib/messages.ts

[TS-800](https://dit-iceland.atlassian.net/browse/TS-800)

feat(new-primary-school): Implement school when to start page

---

libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm.ts
libs/application/templates/new-primary-school/src/lib/messages.ts

[TS-815](https://dit-iceland.atlassian.net/browse/TS-815)

feat(new-primary-school): Implement conclusion page

---

libs/application/template-api-modules/src/lib/modules/templates/criminal-record-submission/criminal-record-submission.service.ts
libs/application/template-api-modules/src/lib/modules/templates/criminal-record-submission/criminal-record-submission.spec.ts
libs/application/templates/criminal-record/src/dataProviders/index.ts
libs/application/templates/criminal-record/src/fields/ConfirmationField/index.tsx
libs/application/templates/criminal-record/src/forms/CriminalRecordForm.ts
libs/application/templates/criminal-record/src/lib/CriminalRecordTemplate.ts
libs/application/templates/criminal-record/src/lib/messages.ts
libs/clients/syslumenn/src/clientConfig.json
libs/clients/syslumenn/src/lib/syslumennClient.service.ts
libs/clients/syslumenn/src/lib/syslumennClient.types.ts

fix(criminal-record): update to flow of criminal record application

---

libs/application/templates/new-primary-school/src/fields/Review/index.tsx
libs/application/templates/new-primary-school/src/fields/Review/review-groups/Photography.tsx
libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm.ts
libs/application/templates/new-primary-school/src/lib/NewPrimarySchoolTemplate.ts
libs/application/templates/new-primary-school/src/lib/dataSchema.ts
libs/application/templates/new-primary-school/src/lib/messages.ts
libs/application/templates/new-primary-school/src/lib/newPrimarySchoolUtils.ts

Added photography section for new primary school application
https://dit-iceland.atlassian.net/browse/TS-813

feat(new-primary-school): Photography section

---

libs/api/domains/documents/src/lib/documentV2.service.ts
libs/clients/documents-v2/src/lib/dto/document.dto.ts

hotfix: https://github.com/island-is/island.is/pull/15012

fix(documents): Content detection.

---

libs/api/domains/documents/src/lib/documentV2.service.ts

fix(documents): Document total count as number - Hotfix

---

.github/workflows/pullrequest.yml
libs/application/templates/new-primary-school/src/fields/Review/index.tsx
libs/application/templates/new-primary-school/src/fields/Review/review-groups/Siblings.tsx
libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm.ts
libs/application/templates/new-primary-school/src/lib/constants.ts
libs/application/templates/new-primary-school/src/lib/dataSchema.ts
libs/application/templates/new-primary-school/src/lib/messages.ts
libs/application/templates/new-primary-school/src/lib/newPrimarySchoolUtils.ts
libs/application/templates/new-primary-school/src/types.ts

[[TS-807] Implement language page](https://dit-iceland.atlassian.net/jira/software/c/projects/TS/boards/82?issueParent=59643&selectedIssue=TS-812)

feat(new-primary-school): Implement siblings page (v1)

---

apps/web/components/connected/HousingBenefitCalculator/HousingBenefitCalculator.tsx

feat(web): Hotfix - Housing benefit calculator, display 5 and 6 or more household member options #15033

---

libs/clients/district-commissioners-licenses/project.json
libs/clients/district-commissioners-licenses/src/clientConfig.json
libs/clients/district-commissioners-licenses/src/lib/districtCommissionersLicenses.config.ts
libs/clients/district-commissioners-licenses/src/lib/districtCommissionersLicenses.module.ts
libs/clients/district-commissioners-licenses/src/lib/districtCommissionersLicenses.service.ts

fix(district-commissioners-licenses): HOTFIX - update client

---

libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm.ts
libs/application/templates/new-primary-school/src/lib/messages.ts

[TS-808](https://dit-iceland.atlassian.net/browse/TS-808)

feat(new-primary-school): School bus page

---

libs/auth-api-lib/src/lib/delegations/DelegationConfig.ts

Delegation config was no longer needed, removing

fix(ids-api): Removing VER applications delegation config

---

libs/api/domains/documents/src/lib/documentV2.service.ts
libs/api/domains/documents/src/lib/models/v2/documents.input.ts
libs/service-portal/documents/src/hooks/useDocumentList.ts

hotfix: https://github.com/island-is/island.is/pull/15112

fix(service-portal): Update get for documents hotfix

---

libs/application/templates/health-insurance/src/lib/HealthInsuranceTemplate.ts

Submit was not throwing on error thus allowing users to continue without actually submitting

fix(hs): Throw error on submit

---

libs/application/templates/new-primary-school/src/forms/Prerequisites.ts
libs/application/templates/new-primary-school/src/lib/messages.ts

[TS-816](https://dit-iceland.atlassian.net/browse/TS-816)
- Update text after MMS workshop 30 may

feat(new-primary-school): No children page text update

---

libs/application/templates/new-primary-school/src/lib/messages.ts

[TS-813](https://dit-iceland.atlassian.net/browse/TS-813)
- Text update after MMS workshop 30may

feat(new-primary-school): Photo usage approval page text update

---

libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm.ts
libs/application/templates/new-primary-school/src/lib/messages.ts

[TS-800](https://dit-iceland.atlassian.net/browse/TS-800)
- Update text after MMS workshop 30may

feat(new-primary-school): Starting school page update text after workshop

---

libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm.ts
libs/application/templates/new-primary-school/src/lib/messages.ts

[TS-808](https://dit-iceland.atlassian.net/browse/TS-808)
- Remove after MMS workshop 30may

feat(new-primary-school): School school bus page removal

---

libs/application/templates/new-primary-school/src/lib/messages.ts

[TS-815](https://dit-iceland.atlassian.net/browse/TS-815)
- Improve text after MMS workshop

feat(new-primary-school): Conclusion page text update 30may

---

libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm.ts
libs/application/templates/new-primary-school/src/lib/messages.ts

[TS-810](https://dit-iceland.atlassian.net/browse/TS-810)
- Update text according MMS workshop 30 may

feat(new-primary-school):  Support page update text after workshop

---

libs/cms/src/lib/cms.contentful.service.ts

feat(web): Hotfix - Project page - Fetch 5 levels of data depth (#15142)

---

libs/auth-api-lib/seeders/data/add-social-insurance-api-scopes-to-clients-application-system.ts

fix(auth-api-lib): Add TR scopes for application system

---

libs/application/templates/driving-instructor-registrations/src/forms/instructorRegistrations.ts

fix(driving-license-instructor): set dataprovider behind feature flag

---

apps/web/components/DefaultHeader/DefaultHeader.tsx
apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx

feat(web): Hotfix - Social Insurance Administration - header title color change (#15202)

---

scripts/ci/cache/__config.mjs
scripts/ci/cache/_utils.mjs

ci: key generated files cache

---

libs/application/templates/new-primary-school/src/fields/Review/index.tsx
libs/application/templates/new-primary-school/src/fields/Review/review-groups/ReasonForApplication.tsx
libs/application/templates/new-primary-school/src/fields/Review/review-groups/Siblings.tsx
libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm.ts
libs/application/templates/new-primary-school/src/lib/NewPrimarySchoolTemplate.ts
libs/application/templates/new-primary-school/src/lib/constants.ts
libs/application/templates/new-primary-school/src/lib/dataSchema.ts
libs/application/templates/new-primary-school/src/lib/messages.ts
libs/application/templates/new-primary-school/src/lib/newPrimarySchoolUtils.ts

[[TS-803] Implement reason page](https://dit-iceland.atlassian.net/jira/software/c/projects/TS/boards/82?issueParent=59643&selectedIssue=TS-803)

feat(new-primary-school): Implement reason page

---

apps/web/hooks/useLinkResolver/useLinkResolver.ts

fix(web): Hotfix - Language toggle not working for organization news #15231

---

apps/native/app/src/components/offline/offline-banner.tsx
apps/native/app/src/hoc/offline-hoc.tsx
apps/native/app/src/screens/app-lock/app-lock.tsx
apps/native/app/src/stores/auth-store.ts

fix(native-app): offline banner now works correctly

---

libs/application/templates/new-primary-school/src/fields/Review/review-groups/Languages.tsx
libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm.ts
libs/application/templates/new-primary-school/src/lib/dataSchema.ts
libs/application/templates/new-primary-school/src/lib/newPrimarySchoolUtils.ts

[[TS-807] Implement language page](https://dit-iceland.atlassian.net/jira/software/c/projects/TS/boards/82?issueParent=59643&selectedIssue=TS-807)

feat(new-primary-school): Added multi select option to languages

---

libs/application/templates/driving-license/src/fields/EligibilitySummary/useEligibility.ts
libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts

fix(driving-license): Hotfix - BE license fixes 

---

libs/application/templates/new-primary-school/src/fields/Review/review-groups/AllergiesAndIntolerances.tsx
libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm.ts
libs/application/templates/new-primary-school/src/lib/dataSchema.ts
libs/application/templates/new-primary-school/src/lib/newPrimarySchoolUtils.ts

[[TS-816] Implement Allergies and intolerances page](https://dit-iceland.atlassian.net/jira/software/c/projects/TS/boards/82?issueParent=59643&selectedIssue=TS-806)

feat(new-primary-school): Added multi select option to allergies and intolerances

---

.github/workflows/config-values.yaml

ci: revert

---

libs/application/templates/new-primary-school/src/fields/CurrentSchool/CurrentSchool.css.ts
libs/application/templates/new-primary-school/src/fields/CurrentSchool/CurrentSchool.tsx
libs/application/templates/new-primary-school/src/fields/Review/review-groups/Child.tsx
libs/application/templates/new-primary-school/src/fields/Review/review-groups/Parents.tsx
libs/application/templates/new-primary-school/src/fields/index.ts
libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm.ts
libs/application/templates/new-primary-school/src/lib/NewPrimarySchoolTemplate.ts
libs/application/templates/new-primary-school/src/lib/constants.ts
libs/application/templates/new-primary-school/src/lib/dataSchema.ts
libs/application/templates/new-primary-school/src/lib/messages.ts
libs/application/templates/new-primary-school/src/lib/newPrimarySchoolUtils.ts
libs/application/templates/new-primary-school/src/types.ts
libs/island-ui/core/src/lib/CategoryCard/CategoryCard.tsx

Added Child info section for new primary school application
https://dit-iceland.atlassian.net/browse/TS-811

feat(new-primary-school): Child info section

---

apps/api/infra/api.ts
apps/services/auth/ids-api/infra/ids-api.ts
apps/services/auth/personal-representative-public/infra/personal-representative-public.ts
apps/services/auth/personal-representative/infra/personal-representative.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

fix: tuned memory limits for multiple services

---

apps/api/infra/api.ts
apps/services/auth/ids-api/infra/ids-api.ts
apps/services/auth/personal-representative-public/infra/personal-representative-public.ts
apps/services/auth/personal-representative/infra/personal-representative.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

fix: tuned memory limits for multiple services (#15350)

---

libs/service-portal/occupational-licenses/src/components/LicenseDetail.tsx
libs/service-portal/occupational-licenses/src/screens/v1/EducationalDetail/EducationalDetail.tsx
libs/service-portal/occupational-licenses/src/screens/v2/OccupationalLicensesDetail/OccupationalLicensesDetail.tsx

fix(education-license): HOTFIX - education license teacher cutoff

---

apps/service-portal/src/components/Notifications/NotificationLine.tsx
libs/service-portal/information/src/screens/Notifications/Notifications.tsx
libs/service-portal/information/src/utils/notificationLinkResolver.ts

fix(service-portal): hotfix - Add fallback image to notifications

---

libs/application/templates/financial-aid/src/fields/Summary/SummaryForm.tsx

* adding sortable feature
* Revert "adding sortable feature"
This reverts commit d9691c54de2c2fb244cf89e49c0bfe6cd7857603.
* adding more detail for api
* removing white space break just adding html element to the db
* adding children to api
* hot fixes
* removing
* good point from R
---------

fix(fa): application finanical aid adding array check  (#15371)

---

apps/service-portal/src/components/Notifications/NotificationButton.tsx
libs/clients/documents-v2/src/lib/documentsClientV2.service.ts
libs/clients/documents-v2/src/lib/dto/document.dto.ts
libs/service-portal/core/src/lib/messages.ts
libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
libs/service-portal/documents/src/components/NoPDF/NoPDF.tsx
libs/service-portal/documents/src/hooks/useMailActionV2.ts
libs/service-portal/documents/src/screens/Overview/Overview.tsx
libs/service-portal/documents/src/utils/messages.ts
libs/service-portal/documents/src/utils/useSubmitMailAction.ts

fix(service-portal): Documents rsk a11y - hotfix

---

.github/dependabot.yml

chore: add dependabot to scripts

---

libs/application/template-api-modules/src/lib/modules/templates/health-insurance-declaration/health-insurance-declaration.service.ts

fix(hid): Use correct id to get attachments on submit

---

libs/application/templates/new-primary-school/src/fields/RelativesTableRepeater/index.tsx
libs/application/templates/new-primary-school/src/fields/Review/review-groups/Relatives.tsx
libs/application/templates/new-primary-school/src/fields/index.ts
libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/childrenNParentsSection/relativesSubSection.ts
libs/application/templates/new-primary-school/src/lib/constants.ts
libs/application/templates/new-primary-school/src/lib/dataSchema.ts
libs/application/templates/new-primary-school/src/lib/messages.ts
libs/application/templates/new-primary-school/src/lib/newPrimarySchoolUtils.ts
libs/application/templates/new-primary-school/src/types.ts

[[TS-805] Implement relatives page](https://dit-iceland.atlassian.net/jira/software/c/projects/TS/boards/82?issueParent=59643&selectedIssue=TS-805)

feat(new-primary-school): Relatives - Data implementation

---

libs/service-portal/core/src/lib/messages.ts
libs/service-portal/social-insurance-maintenance/src/lib/messages.ts
libs/service-portal/social-insurance-maintenance/src/lib/navigation.ts
libs/service-portal/social-insurance-maintenance/src/screens/PaymentPlan/PaymentPlan.tsx

* fix:init
* chore: improts
* fix: messages
---------

fix(social-insurance-maintenance): HOTFIX - Add labels

---

libs/api/domains/driving-license/src/lib/graphql/models/drivingLicense.model.ts
libs/api/domains/driving-license/src/lib/graphql/models/remark.model.ts
libs/application/template-api-modules/src/lib/modules/shared/api/driving-license/driving-license.service.ts
libs/application/template-api-modules/src/lib/modules/shared/api/driving-license/types.ts
libs/application/templates/driving-license/src/fields/EligibilitySummary/useEligibility.ts
libs/application/templates/driving-license/src/fields/HealthRemarks.tsx
libs/application/templates/driving-license/src/lib/constants.ts
libs/application/templates/driving-license/src/lib/types.ts
libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
libs/clients/driving-license/src/lib/drivingLicenseApi.types.ts

fix(application-driving-license): Remarks revamped and bugfixes

---

.github/workflows/config-values.yaml

fix: chart

---

infra/src/common.ts
package.json

chore: force

---

libs/application/templates/healthcare-work-permit/src/fields/CustomFormConclusionSectionField/index.tsx
libs/application/templates/healthcare-work-permit/src/lib/messages/error.ts

fix(health-directorate): Adding #markdown to contentful strings and updating file names that are downloaded

---

libs/application/types/src/lib/ApplicationTypes.ts
libs/application/ui-fields/src/lib/FindVehicleFormField/FindVehicleFormField.tsx

fix(application-system): aosh fixes. Allow for 7 value license plates for machines and adding prefix for contentful

---

libs/clients/university-application/agricultural-university-of-iceland/src/lib/agriculturalUniversityOfIcelandClient.config.ts
libs/clients/university-application/agricultural-university-of-iceland/src/lib/apiConfiguration.ts
libs/clients/university-application/bifrost-university/src/lib/apiConfiguration.ts
libs/clients/university-application/bifrost-university/src/lib/bifrostUniversityClient.config.ts
libs/clients/university-application/holar-university/src/lib/apiConfiguration.ts
libs/clients/university-application/holar-university/src/lib/holarUniversityClient.config.ts
libs/clients/university-application/iceland-university-of-the-arts/src/lib/apiConfiguration.ts
libs/clients/university-application/iceland-university-of-the-arts/src/lib/icelandUniversityOfTheArtsClient.config.ts
libs/clients/university-application/reykjavik-university/src/lib/apiConfiguration.ts
libs/clients/university-application/reykjavik-university/src/lib/reykjavikUniversityClient.config.ts
libs/clients/university-application/university-of-akureyri/src/lib/apiConfiguration.ts
libs/clients/university-application/university-of-akureyri/src/lib/universityOfAkureyriClient.config.ts
libs/clients/university-application/university-of-iceland/src/lib/apiConfiguration.ts
libs/clients/university-application/university-of-iceland/src/lib/universityOfIcelandClient.config.ts

fix(university-gateway): Removed fetch timeout

---

apps/services/endorsements/api/src/app/modules/endorsement/endorsement.service.ts

fix(services-endorsements-api): Postnumer fix (#15565)

---

apps/services/endorsements/api/src/app/modules/endorsement/endorsement.service.ts

fix(services-endorsements-api): Sveitafelag fix (#15572)

---

libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
libs/application/template-api-modules/src/lib/modules/templates/estate/utils/fakeData.ts

fix(application-estate): Selection bugfix (#15575)

---

libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts

fix(parental-leave): change lifecycle (#15591)

---

libs/service-portal/documents/src/hooks/useMailActionV2.ts

fix(service-portal): Only display toast for multi archive - hotfix

---

libs/application/templates/social-insurance-administration/income-plan/src/fields/Review/index.tsx
libs/application/templates/social-insurance-administration/income-plan/src/lib/IncomePlanTemplate.ts
libs/application/templates/social-insurance-administration/income-plan/src/lib/messages.ts

feat(income-plan): text changes

---

apps/services/license-api/esbuild.json

fix(license-api): Hotfix- Missing packages

---

apps/services/user-notification/src/config.ts
infra/src/uber-charts/islandis.ts

fix(user-notification): Env cleanup revert hotfix

---

libs/application/template-api-modules/src/lib/modules/shared/services/attachment-s3.service.ts
libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
libs/application/template-api-modules/src/lib/modules/templates/p-sign-submission/p-sign-submission.service.ts

fix(application-system): Use s3Uri to get attachment bucket (hotfix)

---

libs/application/templates/social-insurance-administration/income-plan/src/forms/IncomePlanForm.ts
libs/application/types/src/lib/Fields.ts
libs/application/ui-fields/src/lib/TableRepeaterFormField/TableRepeaterFormField.tsx

[[TS-848] Jafnar tekjur á mánuði](https://dit-iceland.atlassian.net/jira/software/c/projects/TS/boards/82?selectedIssue=TS-848)

feat(income-plan): Even income

---

libs/application/templates/social-insurance-administration/income-plan/src/fields/Review/index.tsx
libs/application/templates/social-insurance-administration/income-plan/src/forms/IncomePlanForm.ts
libs/application/templates/social-insurance-administration/income-plan/src/lib/IncomePlanTemplate.spec.ts
libs/application/templates/social-insurance-administration/income-plan/src/lib/IncomePlanTemplate.ts
libs/application/templates/social-insurance-administration/income-plan/src/lib/dataSchema.ts
libs/application/templates/social-insurance-administration/income-plan/src/lib/incomePlanUtils.ts
libs/application/templates/social-insurance-administration/income-plan/src/lib/messages.ts
libs/application/templates/social-insurance-administration/income-plan/src/types.ts
libs/application/types/src/lib/Fields.ts
libs/application/ui-fields/src/lib/TableRepeaterFormField/TableRepeaterFormField.tsx

[[TS-849] uneven income](https://dit-iceland.atlassian.net/jira/software/c/projects/TS/boards/82?issueParent=60310&selectedIssue=TS-849)

feat(income-plan): Uneven income

---

libs/application/template-api-modules/src/lib/modules/templates/financial-statement-individual-election/financial-statement-individual-election.service.ts

fix(fsie-application): Fix error handling

---

libs/shared/connected/src/lib/generalPetition/GeneralPetitionLists/GeneralPetitionLists.tsx
libs/shared/connected/src/lib/generalPetition/GeneralPetitionLists/useGetPetitionLists.ts

fix(general-petitions): hotfix - web pagination revert (#15768)

---

libs/api/domains/occupational-licenses/src/lib/models/occupationalLicense.model.ts
libs/api/domains/occupational-licenses/src/lib/occupationalLicenses.service.ts
libs/service-portal/occupational-licenses/src/components/LicenseDetail.tsx
libs/service-portal/occupational-licenses/src/screens/v1/HealthDirectorateDetail/HealthDirectorateDetail.tsx
libs/service-portal/occupational-licenses/src/screens/v1/OccupationalLicensesOverview/OccupationalLicensesOverviewV1.tsx

* chore: init
* chore: fix version
* chore: remove console.log
* chore: revert some

chore(occupational-licenses): HOTFIX - Display license number in health directorate licenses

---

libs/application/templates/social-insurance-administration/income-plan/src/forms/IncomePlanForm.ts
libs/application/templates/social-insurance-administration/income-plan/src/lib/dataSchema.ts
libs/application/ui-fields/src/lib/TableRepeaterFormField/TableRepeaterFormField.tsx

[[TS-889] fix validation for currency](https://dit-iceland.atlassian.net/jira/software/c/projects/TS/boards/82?issueParent=60310&selectedIssue=TS-889)

fix(income-plan): fix validation for currency

---

libs/application/template-api-modules/src/lib/modules/templates/social-insurance-administration/social-insurance-administration-utils.ts
libs/application/template-api-modules/src/lib/modules/templates/social-insurance-administration/social-insurance-administration.service.ts
libs/application/templates/social-insurance-administration/income-plan/src/dataProviders/index.ts
libs/application/templates/social-insurance-administration/income-plan/src/fields/TemporaryCalculationTable/index.tsx
libs/application/templates/social-insurance-administration/income-plan/src/forms/IncomePlanForm.ts
libs/application/templates/social-insurance-administration/income-plan/src/forms/Prerequisites.ts
libs/application/templates/social-insurance-administration/income-plan/src/index.ts
libs/application/templates/social-insurance-administration/income-plan/src/lib/IncomePlanTemplate.spec.ts
libs/application/templates/social-insurance-administration/income-plan/src/lib/IncomePlanTemplate.ts
libs/application/templates/social-insurance-administration/income-plan/src/lib/dataSchema.ts
libs/application/templates/social-insurance-administration/income-plan/src/lib/incomePlanUtils.ts
libs/application/templates/social-insurance-administration/income-plan/src/lib/messages.ts
libs/application/templates/social-insurance-administration/income-plan/src/types.ts
libs/clients/social-insurance-administration/src/lib/socialInsuranceAdministrationClient.service.ts

feat(income-plan): income plan conditions

---

libs/cms/src/lib/cms.contentful.service.ts

https://github.com/island-is/island.is/pull/15848

fix(cms): getOrganizations endpoint - Lower include depth to 4

---

libs/application/template-api-modules/src/lib/modules/templates/announcement-of-death/announcement-of-death.service.ts

fix(application-aod): Fix expander for firearm data to sysl (#15862)

---

apps/application-system/api/infra/application-system-api.ts
charts/islandis/values.staging.yaml

* fix: fixed application system api staging path
* chore: charts update dirty files
---------

fix: fixed application system api staging path (#15875)

---

libs/application/template-api-modules/src/lib/modules/templates/directorate-of-immigration/citizenship/citizenship.service.ts
libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/PersonalSection/UserInformationSubSection.ts
libs/application/templates/directorate-of-immigration/citizenship/src/lib/CitizenshipTemplate.ts

fix(citizenship): name error fix

---

libs/application/templates/healthcare-license-certificate/src/lib/HealthcareLicenseCertificateTemplate.ts

fix(application-system): Removing EES requirement for healthcare license certificate

---

libs/api/domains/social-insurance/src/lib/models/income/category.model.ts
libs/api/domains/social-insurance/src/lib/socialInsurance.service.ts
libs/service-portal/social-insurance-maintenance/src/screens/IncomePlanDetail/IncomePlanDetail.graphql
libs/service-portal/social-insurance-maintenance/src/screens/IncomePlanDetail/IncomePlanDetail.tsx

* fix: wrong field used
* fix: use correct
#15916 
---------

fix(social-insurance-maintenance): HOTFIX - wrong field used

---

apps/services/auth/admin-api/src/app/v2/scopes/test/me-scopes.spec.ts
apps/services/user-profile/src/app/user-profile/e2e/userProfile.spec.ts
apps/services/user-profile/src/app/user-profile/userProfile.controller.ts
apps/services/user-profile/src/app/user-profile/userProfile.service.ts
libs/auth-api-lib/src/lib/resources/admin/admin-scope.service.ts

Apply fixes in #15968 and #15990 to current release
To: 
- Fix delegation setting ghost bug in IDS Admin
- Remove unique constraint error logs on duplicate device token for same national Id.
N/A

fix(ids-admin|user-profile): Apply 15968 and 15990 to current release

---

libs/application/templates/parental-leave/src/forms/OtherParentApproval.ts

Allow other parent to approve transfer of rights if start date is in current month rather than after current date.

fix(parental-leave): Amend conditions in other parent approval

---

apps/web/screens/LifeEvents/LifeEvents.tsx

fix(web): Life events 404 fix

---

apps/web/screens/Organization/SocialInsuranceAdministration/translationStrings.ts

Cherry picked from: https://github.com/island-is/island.is/pull/16070

fix(web): Hotfix -  Pension calculator translation changes

---

libs/service-portal/core/src/components/Modal/Modal.css.ts
libs/service-portal/core/src/components/Modal/Modal.tsx
libs/service-portal/health/src/components/RegisterModal/RegisterModal.css.ts
libs/service-portal/health/src/components/RegisterModal/RegisterModal.tsx
libs/service-portal/health/src/components/RegisterModal/index.ts
libs/service-portal/health/src/screens/DentistRegistration/DentistRegistration.tsx
libs/service-portal/health/src/screens/HealthCenterRegistration/HealthCenterRegistration.tsx

Revert modal upgrade (#16080) - HOTFIX 🔥

feat(service-portal): Revert modal upgrade (#16080)

---

libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/NationalIdWithName/index.tsx
libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/dataSchema.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/CoOwnerAndOperatorRepeater/CoOwnerAndOperatorRepeaterItem.tsx
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/CoOwnerAndOperatorRepeater/index.tsx
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/NationalIdWithName/index.tsx
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/ReviewCoOwnerAndOperatorRepeater/ReviewCoOwnerAndOperatorRepeaterItem.tsx
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/dataSchema.ts

fix(transfer-of-vehicle-ownership): removing age validation for operators

---

apps/services/auth/admin-api/src/app/v2/clients/me-clients.controller.ts
apps/services/auth/admin-api/src/openApi.ts
libs/auth-api-lib/src/lib/delegations/admin/delegation-admin-custom.service.ts
libs/auth-api-lib/src/lib/delegations/constants/zendesk.ts
libs/clients/zendesk/src/lib/zendesk.service.ts

Validate that the Zendesk ticket referenced in delegation is valid, status should be Solved, tags should include the 'umsokn_um_umboð_a_mínum_síðum' tag (we might change the tag later to not include the ´minum_siður´ part.
Also the nationalIds in the ticket should match the ones on the delegation
Also makes small changes needed to get a valid openApi.yaml to use with Postman
Validate papar delegations info from Zendesk

feat(auth-admin): Create paper delegation zendesk integration

---

libs/application/templates/health-insurance-declaration/src/forms/HealthInsuranceDeclarationForm.ts

fix(hid-application): Remove old condition (hotfix)

---

libs/application/templates/new-primary-school/src/fields/Review/review-groups/School.tsx
libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/childrenNParentsSection/childInfoSubSection.ts
libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/overviewSection.ts
libs/application/templates/new-primary-school/src/lib/messages.ts
libs/application/templates/new-primary-school/src/lib/newPrimarySchoolUtils.ts
libs/application/types/src/lib/Fields.ts
libs/application/ui-fields/src/lib/ActionCardListFormField/ActionCardListFormField.tsx

[[TS-811] Implement child info page (Current school)](https://dit-iceland.atlassian.net/jira/software/c/projects/TS/boards/82?selectedIssue=TS-811)

feat(new-primary-school): Current school

---

apps/skilavottord/web/components/CarDetailsBox2/CarDetailsBox2.tsx
apps/skilavottord/web/screens/DeregisterVehicle/Confirm/Confirm.tsx
apps/skilavottord/ws/src/app/modules/vehicle/vehicle.resolver.ts
apps/skilavottord/ws/src/app/modules/vehicle/vehicle.service.ts

Hotfix #16120 
* TS-916 Fix issue with numberplate count
* TS-916 Fix code after code rabbit review
* TS-916 Fix code after code rabbit review
---------

fix(skilavottord): Fix issue with numberplate count (#16120)

---

apps/web/components/Charts/v2/utils/format.ts
apps/web/components/connected/BenefitsOfDigitalProcessesCalculator/BenefitsOfDigitalProcessesCalculator.tsx
apps/web/components/connected/BenefitsOfDigitalProcessesCalculator/translation.strings.ts
apps/web/components/connected/BenefitsOfDigitalProcessesCalculator/utils.ts
apps/web/utils/richText.tsx

https://github.com/island-is/island.is/pull/16139

feat(web): Hotfix - Benefits of digital processes - Calculator (#16139)

---

apps/skilavottord/web/screens/DeregisterVehicle/Confirm/Confirm.tsx
apps/skilavottord/web/screens/RecyclingCompanies/RecyclingCompanies.tsx
apps/skilavottord/web/screens/RecyclingCompanies/RecyclingCompanyUpdate/RecyclingCompanyUpdate.tsx
apps/skilavottord/ws/src/app/modules/samgongustofa/samgongustofa.service.ts

fix(skilavottord): Fix view recycling company and add loggers

---

libs/service-portal/core/src/components/TabNavigation/TabNavigation.tsx
libs/service-portal/core/src/components/TabNavigation/TabNavigationInstitutionPanel.tsx

fix(service-portal-core): Conditional org query in tab navigation

---

libs/portals/admin/regulations-admin/src/utils/fileUploader.ts

hotfix: https://github.com/island-is/island.is/pull/16106

chore(regulations-admin): hotfix - Update presigned url for file uploader

---

libs/application/templates/directorate-of-immigration/citizenship/src/fields/CriminalRecords/index.tsx
libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/ChildrenSupportingDocuments/ChildrenOtherDocumentsSubSection.ts
libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/SupportingDocumentsSection/OtherDocumentsSubSection.ts
libs/application/templates/directorate-of-immigration/citizenship/src/lib/dataSchema.ts
libs/application/templates/directorate-of-immigration/citizenship/src/lib/messages/error.ts
libs/clients/directorate-of-immigration/src/lib/apiConfiguration.ts

fix(citizenship): upload files required and timeout release

---

libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/ChildrenSupportingDocuments/ChildrenOtherDocumentsSubSection.ts
libs/application/templates/directorate-of-immigration/citizenship/src/lib/dataSchema.ts

fix(citizenship): fixing file upload

---

libs/island-ui/core/src/lib/PdfViewer/PdfViewer.tsx

fix(island-ui): Update url for pdf worker - hotfix

---

libs/application/templates/aosh/register-new-machine/src/fields/MachineType/index.tsx

Was using old answer in setvalue

fix(register-new-machine): setvalue

---

libs/application/templates/signature-collection/parliamentary-list-creation/src/fields/CopyLink/index.tsx

fix(template-plc): Slug fix (#16424)

---

libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/ViewList/Signees/PaperSignees.tsx
libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/index.tsx

9451f1dfe5698303452caf5c39e8666c9d2ffa65 hotfix

fix(signature-collection): remove tooltip (#16437)

---

libs/api/domains/signature-collection/src/lib/signatureCollection.resolver.ts

Cherry pick of 525e166654034a22df1aace47440e26521ee5212

fix(signature-colletion): allow manager on paper upload (#16427)

---

libs/application/template-api-modules/src/lib/modules/templates/signature-collection/parliamentary-list-creation/emailGenerators/applicationSubmitted.ts
libs/application/template-api-modules/src/lib/modules/templates/signature-collection/parliamentary-list-creation/parliamentary-list-creation.service.ts
libs/application/template-api-modules/src/lib/modules/templates/signature-collection/parliamentary-list-signing/parliamentary-list-signing.service.ts
libs/clients/signature-collection/src/lib/signature-collection.types.ts

feat(signature-collection): Fix after rounds of testing

---

libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/ChildrenSupportingDocuments/ChildrenOtherDocumentsSubSection.ts
libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/ChildrenSupportingDocuments/ChildrenPassportSubSection.ts

fix(citizenship): fixing indexing for child documents

---

apps/application-system/api/infra/application-system-api.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
infra/src/uber-charts/islandis.ts

fix(application-system): Add notification url

---

libs/portals/admin/signature-collection/src/lib/messages.ts
libs/portals/admin/signature-collection/src/screens-parliamentary/Constituency/index.tsx
libs/portals/admin/signature-collection/src/screens-parliamentary/List/paperSignees/index.tsx
libs/portals/admin/signature-collection/src/screens-parliamentary/index.tsx
libs/portals/admin/signature-collection/src/shared-components/completeReview/index.tsx

fix(signature-collection): hotfix signature collection admin

---

libs/application/template-api-modules/src/lib/modules/shared/api/payment/payment.service.ts

fix(application-system): add check to payment

---

apps/web/screens/Organization/SocialInsuranceAdministration/translationStrings.ts

feat(web): Hotfix - Pension calculator translations for 2025 comparison (#16561)

---

apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculatorResults.css.ts
apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculatorResults.tsx
apps/web/screens/Organization/SocialInsuranceAdministration/translationStrings.ts

feat(web): Hotfix - Pension calculator 2025 comparision - Change button styles (#16565)

---

libs/api/domains/signature-collection/src/lib/signatureCollection.resolver.ts
libs/api/domains/signature-collection/src/lib/signatureCollection.service.ts
libs/clients/signature-collection/src/lib/signature-collection-admin.service.ts
libs/clients/signature-collection/src/lib/signature-collection.service.ts
libs/portals/admin/signature-collection/src/lib/messages.ts
libs/service-portal/signature-collection/src/hooks/graphql/mutations.ts
libs/service-portal/signature-collection/src/lib/messages.ts
libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/ViewList/Signees/EditPage/index.tsx
libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/ViewList/Signees/index.tsx

…number (#16581)
* Add endpoint for candidacy to update signature page number
* UI - edit page
* message id
* input value
* msg id's
---------

feat(signature-collection): Allow candidacy to update signature page number (#16581)

---

libs/api/domains/documents/src/lib/documentV2.resolver.ts
libs/api/domains/documents/src/lib/models/v2/document.input.ts
libs/service-portal/documents/src/components/DocumentLine/DocumentLineV3.tsx

#16606 
Detailed logs for documents subpoena 

fix(api): more logs for documents (#16606)

---

libs/application/templates/id-card/src/lib/IdCardTemplate.ts

fix(citizenship): application card info update

---

libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/ChildrenSupportingDocuments/ChildrenOtherDocumentsSubSection.ts

fix(citizenship): update condition for childrens support documents

---

libs/application/templates/id-card/src/forms/Approved.ts
libs/application/templates/id-card/src/forms/ParentB.ts
libs/application/templates/id-card/src/lib/IdCardTemplate.ts
libs/application/templates/id-card/src/lib/messages/externalData.ts

fix(id-card): fixing texts

---

apps/skilavottord/web/infra/skilavottord-web.ts
apps/skilavottord/ws/infra/skilavottord-ws.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

Hotfix #16630
* TS-930 Expand the CPU and memory
* TS-930 Expand the CPU and memory
* chore: charts update dirty files
---------

chore(skilavottord): Expand cpu and ram size (#16630)

---

apps/web/components/ChatPanel/ChatBubble/ChatBubble.tsx
apps/web/components/ChatPanel/ChatBubble/EmbedDisclaimer/EmbedDisclaimer.css.ts
apps/web/components/ChatPanel/ChatBubble/EmbedDisclaimer/EmbedDisclaimer.tsx
apps/web/components/ChatPanel/WatsonChatPanel/WatsonChatPanel.tsx

feat(web): Hotfix - Add disclaimer for UTL web chat (#16577)

---

apps/air-discount-scheme/README.md
apps/air-discount-scheme/backend/infra/air-discount-scheme-backend.ts
apps/air-discount-scheme/backend/seeders/20211108100835-development.js
apps/air-discount-scheme/backend/src/app/modules/common/test/unit/auth.guard.spec.ts
apps/air-discount-scheme/backend/src/app/modules/nationalRegistry/nationalRegistry.service.ts
apps/air-discount-scheme/backend/src/environments/environment.ts
apps/air-discount-scheme/web/screens/Admin/consts.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
libs/air-discount-scheme/consts/src/lib/flight.ts
libs/portals/admin/air-discount-scheme/src/screens/Overview/consts.ts
libs/service-portal/air-discount/src/lib/messages.ts
libs/service-portal/air-discount/src/screens/AirDiscountOverview/AirDiscountOverview.tsx

hotfix: https://github.com/island-is/island.is/pull/16655

feat(air-discount-scheme): Add myflug + add more logs to ads hotfix

---

libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification-v2.utils.ts

fix(accident-notification): improve representative handling

---

libs/application/templates/aosh/register-new-machine/src/utils/getStreetRegistrationInformation.ts

fix(register-new-machine): fixing type

---

apps/services/bff/src/app/modules/proxy/proxy.service.ts

Fix to exclude content encoding headers
Breaking bff proxy to download service

fix(services-bff): Fix proxy headers

---

apps/services/bff/src/app/modules/proxy/proxy.service.ts

Fix to exclude content encoding headers
Breaking bff proxy to download service

fix(services-bff):  Proxy service headers fix

---

libs/application/templates/aosh/register-new-machine/README.md

fix(register-new-machine): readme

---

apps/download-service/infra/download-service.ts
charts/islandis/values.dev.yaml
charts/islandis/values.staging.yaml

fix: disable global-auth on download-service

---

charts/islandis/values.prod.yaml
infra/src/dsl/bff.ts

fix: BFF_ALLOWED_REDIRECT_URIS as array

---

charts/islandis/values.prod.yaml
infra/src/dsl/bff.ts

This went out on the release branch but was forgotten to move to main

fix(services-bff): Fix prod infra config

---

apps/services/bff/src/app/modules/ids/ids.service.ts

This PR moves all client id and secrets from request body to authorization header instead
Client secret was leaking to identity server logs. Duenedes documentation alters from Auth0 2.0 documentation
https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1

fix(services-bff): Bff secret log leak fix

---

libs/application/templates/health-insurance/src/lib/dataSchema.ts

fix(health-insurance): Fixing zod schema 

---

libs/application/templates/parental-leave/src/lib/answerValidationSections/utils.ts

fix(parental-leave): Change maxStartDate calculation

---

libs/application/template-api-modules/src/lib/modules/templates/financial-statement-political-party/financial-statement-political-party.service.ts
libs/application/templates/inao/financial-statement-political-party/src/fields/Overview/Overview.tsx

fix(financial-statement-political-party): Submit application fix

---

libs/api/domains/vehicles/project.json
libs/api/domains/vehicles/src/lib/dto/getBulkVehicleMileageRequestOverview.input.ts
libs/api/domains/vehicles/src/lib/messages.ts
libs/api/domains/vehicles/src/lib/models/v3/bulkMileage/bulkMileageRegistrationRequestError.model.ts
libs/api/domains/vehicles/src/lib/resolvers/bulkMileage.resolver.ts
libs/api/domains/vehicles/src/lib/services/bulkMileage.service.ts
libs/api/domains/vehicles/src/lib/services/errorCodes.ts
libs/api/domains/vehicles/src/lib/services/vehicles.service.ts
libs/api/domains/vehicles/src/lib/vehicles.module.ts
libs/clients/vehicles-mileage/src/clientConfig.json
libs/service-portal/assets/src/lib/messages.ts
libs/service-portal/assets/src/screens/VehicleBulkMileage/VehicleBulkMileage.tsx
libs/service-portal/assets/src/screens/VehicleBulkMileage/VehicleBulkMileageRow.tsx
libs/service-portal/assets/src/screens/VehicleBulkMileageJobDetail/VehicleBulkMileageJobDetail.graphql
libs/service-portal/assets/src/screens/VehicleBulkMileageJobDetail/VehicleBulkMileageJobDetail.tsx
libs/service-portal/assets/src/screens/VehicleBulkMileageJobOverview/VehicleBulkMileageJobOverview.tsx
libs/service-portal/assets/src/screens/VehicleBulkMileageUpload/VehicleBulkMileageUpload.tsx
libs/service-portal/assets/src/utils/parseFileToMileage.ts

* fix: display latest reg
* feat: add error code map
* feat: add errors
* fix: csv parse
* fix: jobs sorting
* fix: remove strip
* fix: translations
* fix: add sanitization on number
* fix: sanitization
* fix: add secret from aws paramter store
* fix: sanitize bit less powerfully
* fix: more handling
* Update libs/service-portal/assets/src/screens/VehicleBulkMileageUpload/VehicleBulkMileageUpload.tsx
* fix: coderabbit suggestions
---------

feat(bulk-mileage): HOTFIX - update errors (#16720)

---

.github/dependabot.yml

[CI failures](https://github.com/island-is/island.is/pull/16505/checks?check_run_id=32915422579) :cry:

chore(ci): Quote dependabot times

---

libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.spec.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

https://github.com/island-is/island.is/pull/16814
* fix(parental-leave): If startDate is the 31st then the endDate should be 1 day later
* fix period length in months calculation and tests
---------

fix(parental-leave): If startDate is the 31st then the endDate should be 1 day later (#16814)

---

apps/services/bff/src/app/modules/user/user.service.ts

fix(services-bff): Fix refresh token condition

---

package.json

chore: force rebuild

---

nx.json

fix: remove force build hack

---

apps/contentful-apps/pages/fields/chart-component-source-data-key-field.tsx

fix(contentful-apps): Add missing variable in check for pie chart type

---

libs/api/domains/email-signup/src/lib/services/campaignMonitor/campaignMonitor.service.ts

fix(api): Hotfix - campaign monitor email signup content type header #16936

---

infra/package.json
infra/scripts/Dockerfile
infra/yarn.lock
package.json

This reverts commit d81308c6672184a11cb407696f461324ed81f8ca.
Error during merge to `main`. Reverting to prevent fallout.

revert: "chore(infra): Upgrade helm build yarn (#16890)"

---

libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

https://github.com/island-is/island.is/pull/16953

fix(parental-leave): Period calculator fix for february endDate (#16953)

---

libs/portals/admin/delegation-admin/src/screens/CreateDelegation/CreateDelegation.tsx
libs/portals/admin/delegation-admin/src/screens/DelegationAdminDetails/DelegationAdmin.tsx
libs/portals/admin/delegation-admin/src/screens/Root.tsx
libs/portals/shared-modules/delegations/src/components/delegations/DelegationViewModal.tsx

fix(admin-portal): Fix bff hooks to not use old auth hooks

---

libs/portals/admin/service-desk/src/screens/Companies/Companies.action.ts
libs/portals/admin/service-desk/src/screens/Companies/Companies.tsx
libs/portals/admin/service-desk/src/screens/Users/Users.action.ts
libs/portals/admin/service-desk/src/screens/Users/Users.tsx

Stop redirecting when only one result
causes loop when going back now that we have query in url

fix(portals-admin): Stop redirecting when only one result

---

libs/clients/form-system/src/lib/FormSystemClient.config.ts

Fix form system client config in production.
The form system is not ready in production, and there are no env variables for it.

fix: Make FormSystemClientConfig optional

---

libs/portals/admin/regulations-admin/src/components/impacts/EditChange.tsx
libs/portals/admin/regulations-admin/src/components/impacts/ImpactDate.tsx
libs/portals/admin/regulations-admin/src/components/impacts/ReferenceText.tsx
libs/portals/admin/regulations-admin/src/lib/messages.ts

fix(regulations-admin): Update strings, fix impactname (hotfix)

---

libs/application/templates/directorate-of-immigration/citizenship/src/assets/Logo.tsx
libs/application/templates/directorate-of-immigration/citizenship/src/fields/HiddenTextInput/index.tsx
libs/application/templates/directorate-of-immigration/citizenship/src/fields/SelectedChildrenExtra/SelectedRepeaterItem.tsx
libs/application/templates/directorate-of-immigration/citizenship/src/fields/SelectedChildrenExtra/index.tsx
libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/ChildrenSupportingDocuments/ChildrenOtherDocumentsSubSection.ts
libs/application/templates/directorate-of-immigration/citizenship/src/utils/childrenInfo.ts

fix(citizenship): child error indexing release

---

libs/application/templates/inheritance-report/src/forms/sections/applicant.ts
libs/application/templates/inheritance-report/src/forms/sections/heirs.ts
libs/application/templates/inheritance-report/src/lib/messages.ts

fix(inheritance-report): separating texts

---

libs/application/template-api-modules/src/lib/modules/templates/directorate-of-immigration/citizenship/citizenship.service.ts
libs/application/templates/directorate-of-immigration/citizenship/src/fields/Review/ChildrenPassportReview.tsx
libs/application/templates/directorate-of-immigration/citizenship/src/fields/Review/DocumentReview.tsx
libs/application/templates/directorate-of-immigration/citizenship/src/fields/SelectChildren/index.tsx
libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/ChildrenSupportingDocuments/ChildrenOtherDocumentsSubSection.ts
libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/ChildrenSupportingDocuments/ChildrenPassportSubSection.ts
libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/SupportingDocumentsSection/PassportSubSection.ts
libs/application/templates/directorate-of-immigration/citizenship/src/lib/dataSchema.ts
libs/application/templates/directorate-of-immigration/citizenship/src/utils/childrenInfo.ts
libs/application/templates/directorate-of-immigration/citizenship/src/utils/selectedIndividual.ts

fix(citizenship): error indexing children

---

apps/air-discount-scheme/backend/src/app/modules/discount/discount.service.ts
apps/air-discount-scheme/backend/src/app/modules/discount/test/unit/discount.service.spec.ts
apps/air-discount-scheme/backend/src/app/modules/user/user.service.ts
libs/clients/health-directorate/src/lib/clients/vaccinations/clientConfig.json
libs/portals/my-pages/core/src/components/SortableTable/SortableTable.tsx
libs/portals/my-pages/health/src/screens/HealthOverview/HealthOverview.tsx
libs/portals/my-pages/health/src/screens/Vaccinations/VaccinationsWrapper.tsx
libs/portals/my-pages/health/src/screens/Vaccinations/tables/SortedVaccinationsTable.tsx

Hotfixing:
https://github.com/island-is/island.is/pull/17193 - ADS
https://github.com/island-is/island.is/pull/17138 - Vaccine tweaks

fix(ads-my-pages): vaccine, ads explicit - hotfix

---

apps/services/bff/src/app/modules/auth/auth.service.ts
libs/react-spa/bff/src/lib/BffPoller.tsx
libs/react-spa/bff/src/lib/BffProvider.tsx
libs/react-spa/bff/src/lib/bff.hooks.ts

https://github.com/island-is/island.is/pull/17212
https://github.com/island-is/island.is/pull/17213
Fixes broadcaster broadcating to bff only not everything on same domain
Log warning for missing attempt key instead of error

fix(services-bff): Bff fixes

---

apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculator.tsx
apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculatorResults.tsx
apps/web/screens/Organization/SocialInsuranceAdministration/translationStrings.ts
apps/web/screens/Organization/SocialInsuranceAdministration/utils.ts
libs/api/domains/social-insurance/src/lib/dtos/pensionCalculation.input.ts
libs/api/domains/social-insurance/src/lib/utils.ts

feat(web): Hotfix - Pension Calculator,  "After September 1 2025" year option #17117

---

libs/application/templates/social-insurance-administration/income-plan/src/fields/Review/index.tsx
libs/application/templates/social-insurance-administration/income-plan/src/lib/IncomePlanTemplate.spec.ts
libs/application/templates/social-insurance-administration/income-plan/src/lib/IncomePlanTemplate.ts
libs/application/templates/social-insurance-administration/income-plan/src/lib/messages.ts

feat(income-plan): remove edit functionality

---

apps/unicorn-app/src/app/page.tsx

chore: testing mergequeue

---

libs/application/templates/aosh/register-new-machine/src/lib/dataSchema.ts

fix(register-new-macine): making street registration optional

---

libs/application/templates/inheritance-report/src/fields/CalculateShare/index.tsx
libs/application/templates/inheritance-report/src/fields/Overview/OverviewAssets/rows.ts
libs/application/templates/inheritance-report/src/types.ts

fix(inheritance-report): Fix bank account calculation (#17382)

---

libs/clients/transport-authority/vehicle-operators/src/lib/vehicleOperatorsClient.service.ts

fix(change-operator): Add missing mileage field when removing all operators

---

apps/web/pages/api/rss/index.ts
apps/web/screens/queries/Events.ts
libs/cms/src/lib/models/event.model.ts

https://github.com/island-is/island.is/pull/17270
https://github.com/island-is/island.is/pull/17282
https://github.com/island-is/island.is/pull/17297

feat(web): Hotfix - RSS feed for generic lists and events

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts

fix(parental-leave): pdf attachments not uploading (#17114)

---

apps/download-service/src/app/modules/finance-documents/document.controller.ts
libs/portals/my-pages/core/src/utils/documentFormSubmission.ts
libs/portals/my-pages/finance/src/screens/FinanceStatus/FinanceStatus.tsx

fix(my-pages): annual doc query dl - hotfix

---

libs/api/domains/driving-license/src/lib/drivingLicense.spec.ts
libs/residence-history/src/lib/computeCountryResidence.spec.ts
libs/residence-history/src/lib/computeCountryResidence.ts

So other changes can be hotfixed I suggest we hotfix this fix for a broken unit test

fix(client-driving-license): Hotfix - Leap year edge issues (#17415)

---

libs/cms/src/lib/cms.elasticsearch.service.ts
libs/cms/src/lib/search/importers/genericListItem.service.ts
libs/cms/src/lib/search/importers/teamList.service.ts

https://github.com/island-is/island.is/pull/17226
https://github.com/island-is/island.is/pull/17115

fix(web): Hotfix - Generic List order

---

apps/web/screens/Organization/DirectorateOfLabour/MyPages.tsx

feat(web): Hotfix - Add custom top login button item to VMST "My Pages" page #17453

---

apps/web/components/ChatPanel/BoostChatPanel/BoostChatPanel.tsx

feat(web): Hotfix - Boost.ai, set language depending on activeLocale #17461

---

libs/application/templates/marriage-conditions/src/fields/PaymentInfo/index.tsx

fix(marriage-conditions): certificates fix (#17487)

---

apps/web/screens/ServiceWeb/utils/index.ts

fix(web): Service web contact banner for Digital Iceland #17493

---

apps/web/components/ServiceWeb/Forms/StandardForm/StandardForm.tsx

fix(web): Hotfix, Service web - FormProvider moved to top of component #17495

---

libs/portals/my-pages/information/src/components/PersonalInformation/Forms/ProfileForm/components/Inputs/BankInfoForm.tsx
libs/portals/my-pages/information/src/components/PersonalInformation/Forms/ProfileForm/components/Inputs/Email.tsx
libs/portals/my-pages/information/src/components/PersonalInformation/Forms/ProfileForm/components/Inputs/Phone.tsx
libs/portals/my-pages/signature-collection/src/screens/Parliamentary/OwnerView/ViewList/Signees/PaperSignees.tsx

wrap user-profile form context settings
fix after inputcontroller update

fix(my-pages): user-profile form context settings

---

apps/download-service/src/app/modules/documents/document.controller.ts
libs/portals/my-pages/information/src/components/PersonalInformation/Forms/ProfileForm/components/Inputs/BankInfoForm.tsx
libs/portals/my-pages/information/src/components/PersonalInformation/Forms/ProfileForm/components/Inputs/Email.tsx
libs/portals/my-pages/information/src/components/PersonalInformation/Forms/ProfileForm/components/Inputs/Phone.tsx

Hotfix 🔥 
* https://github.com/island-is/island.is/pull/17505
* https://github.com/island-is/island.is/pull/17502

fix(my-pages): hotfix - my pages docs and settings

---

libs/shared/form-fields/src/lib/InputController/InputController.tsx

fix(shared): Hotfix - InputController relies on FormContext being provided (#17511)

---

apps/skilavottord/web/auth/utils.ts
apps/skilavottord/ws/src/app/modules/auth/auth.guard.ts

- Rollback debug made in #17499

fix(skilavottord): Rollback debug

---

libs/clients/syslumenn/src/lib/syslumennClient.service.ts

fix(marriage): hotfix/marriage electronicid

---

libs/application/templates/social-insurance-administration/old-age-pension/src/forms/OldAgePensionForm.ts
libs/application/templates/social-insurance-administration/old-age-pension/src/forms/Prerequisites.ts
libs/application/templates/social-insurance-administration/old-age-pension/src/lib/messages.ts

feat(old-age-pension): Change text and remove screen

---

libs/clients/documents-v2/src/lib/dto/document.dto.ts
libs/clients/documents-v2/src/utils/htmlConfig.ts

chore(documents): Allow SVG in HTML sanitation - hotfix

---

libs/application/templates/family-matters/core/src/utils/index.ts

fix(crc): Fix home childrenLiveWithApplicant selection

---

libs/application/template-api-modules/src/lib/modules/templates/aosh/work-accident-notification/work-accident-notification.service.ts
libs/application/templates/aosh/work-accident-notification/src/fields/Occupation/index.tsx
libs/application/templates/aosh/work-accident-notification/src/forms/WorkAccidentNotificationForm/AccidentSection/about.ts
libs/application/templates/aosh/work-accident-notification/src/forms/WorkAccidentNotificationForm/AnnouncementSection/index.ts
libs/application/templates/aosh/work-accident-notification/src/forms/WorkAccidentNotificationForm/ConclusionSection/index.ts
libs/application/templates/aosh/work-accident-notification/src/forms/WorkAccidentNotificationForm/EmployeeSection/employee.ts
libs/application/templates/aosh/work-accident-notification/src/forms/WorkAccidentNotificationForm/InformationSection/companySection.ts
libs/application/templates/aosh/work-accident-notification/src/forms/WorkAccidentNotificationForm/InformationSection/projectPurchase.ts
libs/application/templates/aosh/work-accident-notification/src/lib/WorkAccidentNotificationTemplate.ts
libs/application/templates/aosh/work-accident-notification/src/lib/dataSchema.ts
libs/application/templates/aosh/work-accident-notification/src/lib/messages/employee.ts
libs/application/templates/aosh/work-accident-notification/src/lib/messages/externalData.ts
libs/auth/scopes/src/lib/api.scope.ts

fix(application-system): Multiple minor fixes after testing

---

.github/workflows/dd-metrics.yml

chore: Disable DD actions custom metrics

---

.github/workflows/pullrequest.yml

fix: chunks from gh vars

---

.github/workflows/pullrequest.yml
.github/workflows/push.yml
scripts/ci/get-node-version.mjs

Dockerhub is rate limiting us, let's pin the node dockertag for now.

fix: use pinned dockertag

---

scripts/ci/Dockerfile

* Revert "chore(CI): Refactor Dockerfile (#17531)"
This reverts commit 50217b7f461f2130926658dcb57b36ebf58cfab1.
* Remove output-local

revert: chore(CI): Refactor Dockerfile (#17531) (#17691)

---

apps/web/components/ServiceWeb/Forms/StandardForm/StandardForm.tsx
apps/web/screens/ServiceWeb/Forms/utils.ts

fix(web): Revert "feat(web): Service web, Iceland Health - Contact form category changes (#17614)" (#17662)

---

scripts/ci/Dockerfile

ci(dockerfile): fix missing WORKDIR

---

scripts/ci/Dockerfile

ci(dockerfile): use ecr node

---

libs/application/templates/social-insurance-administration/income-plan/src/lib/IncomePlanTemplate.ts
libs/application/templates/social-insurance-administration/old-age-pension/src/forms/OldAgePensionForm.ts

feat(income-plan): Temporarily don't show withholding tax

---

apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.spec.tsx
apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.tsx

- Fixing incident and broken laws descriptions
- Not working as expected

fix(j-s): fix bugs for speeding

---

libs/application/templates/inheritance-report/src/fields/HeirsRepeater/index.tsx

fix(application-ir):  total rounding

---

libs/application/templates/marriage-conditions/src/fields/PaymentInfo/index.tsx
libs/application/templates/marriage-conditions/src/forms/application.ts
libs/application/templates/marriage-conditions/src/lib/MarriageConditionsTemplate.ts

fix(marriage-conditions): switched codes setup in template (#17756)

---

.github/workflows/pullrequest-close.yml

fix: pipeline debug

---

libs/shared/utils/src/lib/clearInputsOnChange.spec.ts
libs/shared/utils/src/lib/clearInputsOnChange.ts

* fix(application-system): Fix clearOnChange
* Fix test

fix(application-system): Fix clearOnChange (#17729)

---

.github/workflows/pullrequest-close.yml
apps/unicorn-app/src/app/page.tsx

chore: adding stuff

---

apps/unicorn-app/src/app/page.tsx

adding stuff smore

---

apps/web/components/ServiceWeb/Forms/StandardForm/StandardForm.tsx
apps/web/screens/ServiceWeb/Forms/utils.ts

feat(web): Service web, Iceland Health - Contact form category changes (#17777)

---

apps/web/screens/Organization/SubPage.tsx
apps/web/screens/queries/Organization.tsx
libs/cms/src/lib/generated/contentfulTypes.d.ts
libs/cms/src/lib/models/organizationSubpage.model.ts

https://github.com/user-attachments/assets/48c29350-4419-4ca6-b7c8-50d4fc10f44d

feat(web): Organization subpage full width bottom slices

---

.github/workflows/pullrequest.yml

Fixes stuck PRs implemented [here](https://github.com/island-is/island.is/pull/17887)

ci(automerge): fail on automerge when features

---

apps/web/components/Organization/Slice/OrganizationParentSubpageListSlice/OrganizationParentSubpageListSlice.tsx
apps/web/screens/queries/fragments.ts
libs/cms/src/lib/generated/contentfulTypes.d.ts
libs/cms/src/lib/models/organizationParentSubpageList.model.ts

feat(web): Hotfix -  Organization Parent Subpage List - See more link #17907

---

.github/workflows/push.yml

- **feat(web): Hotfix -  Organization Parent Subpage List - See more link #17907 (#17909)**
- **ci: fix cache-key (#17916)**

ci: fix cache-key (#17916)

---

libs/application/templates/secondary-school/src/forms/secondarySchoolForm/extraInformationSection/index.ts

Hotfix to allow uploading multiple files

fix(application-system): Set uploadMultiple to true (#17920)

---

libs/application/templates/social-insurance-administration/income-plan/src/lib/IncomePlanTemplate.ts
libs/application/templates/social-insurance-administration/income-plan/src/lib/incomePlanUtils.ts

* feat(income-plan): Default income types
* check if latestIncomePlan is empty
---------

feat(income-plan): default-income-types

---

libs/application/template-api-modules/src/lib/modules/templates/social-insurance-administration/social-insurance-administration-utils.ts
libs/clients/social-insurance-administration/src/lib/socialInsuranceAdministrationClient.type.ts

* add distributeIncomeByMonth to incomePlanDTO
* format
* Update libs/application/template-api-modules/src/lib/modules/templates/social-insurance-administration/social-insurance-administration-utils.ts
Co-authored-by: helgifr <helgifreyr95@gmail.com>
* add curly bracket
* formatting
---------
Co-authored-by: helgifr <helgifreyr95@gmail.com>

feat(income-plan): Add new distribute income by month variable (#17932)

---

scripts/ci/Dockerfile

Reverts island-is/island.is#17963

revert: "ci: Codegen in Dockerfile & add `static-base` layer for caching"

---

libs/application/template-api-modules/src/lib/modules/templates/aosh/work-accident-notification/work-accident-notification.service.ts
libs/application/templates/aosh/work-accident-notification/src/fields/PdfOverview/index.tsx
libs/application/templates/aosh/work-accident-notification/src/lib/dataSchema.ts

Fixing pdf livetime and verkkaupi validation

fix(application-system): hotfix/slysaskraning pdf verkkaupi

---

libs/application/templates/aosh/work-accident-notification/src/lib/WorkAccidentNotificationTemplate.ts

fix(application-system): Fixing lifecycle to save application in draft

---

libs/application/template-api-modules/src/lib/modules/templates/aosh/work-accident-notification/work-accident-notification.service.ts
libs/application/templates/aosh/work-accident-notification/src/forms/WorkAccidentNotificationForm/InformationSection/companySection.ts
libs/application/templates/aosh/work-accident-notification/src/forms/WorkAccidentNotificationForm/InformationSection/projectPurchase.ts
libs/application/templates/aosh/work-accident-notification/src/lib/dataSchema.ts
libs/application/templates/aosh/work-accident-notification/src/lib/messages/information.ts

fix(application-system): changes to branch information

---

.github/workflows/docker.yml
scripts/ci/generate-chunks.sh

Reverts island-is/island.is#17779

revert: "feat(ci): Use new docker build"

---

libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts

feat(parental-leave): add on Exit to states

---

libs/application/templates/parental-leave/src/lib/directorateOfLabour.utils.ts
libs/clients/vmst/src/clientConfig.yaml

* fix(parental-leave): map error for undefined values
* Fix typescript compilation error
---------

fix(parental-leave): map error for undefined values (#18033)

---

libs/application/template-api-modules/src/lib/modules/templates/operating-license/operatingLicense.module.ts
libs/application/template-api-modules/src/lib/modules/templates/operating-license/operatingLicense.service.ts

fix(application-ol): Remove/replace criminal record service

---

apps/skilavottord/ws/src/app/modules/recyclingPartner/recyclingPartner.service.ts
apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts

TS-989 fix error when de-registering vehicles

fix(skilavottord): Error when de-registering vehicles (#18088)

---

libs/api/domains/occupational-licenses-v2/src/lib/occupationalLicensesV2.service.ts
libs/portals/my-pages/information/src/components/FamilyMemberCard/FamilyMemberCard.tsx
libs/portals/my-pages/information/src/screens/BioChild/BioChild.tsx
libs/portals/my-pages/information/src/screens/ChildCustody/ChildCustody.graphql
libs/portals/my-pages/information/src/screens/ChildCustody/ChildCustody.tsx

fix(my-pages): HOTFIX - health and info

---

libs/clients/financial-statements-inao/src/lib/financialStatementsInaoClient.service.ts

fix(inao): application submit

---

package.json
scripts/ci/docker/const.mjs

chore: test prod and staging

---

apps/web/pages/s/[...slugs]/index.tsx
apps/web/screens/GenericList/GenericListItem.tsx

fix(web): Hotfix - Generic list slug mapping #18211

---

apps/services/search-indexer/infra/search-indexer-service.ts
charts/islandis-services/search-indexer-service/values.prod.yaml
charts/islandis/values.prod.yaml

* fix(search-indexer-service): use correct prod domain
* chore: charts update dirty files
---------
Co-authored-by: andes-it <builders@andes.is>

fix(search-indexer-service): use correct prod domain (#18229)

---

apps/portals/my-pages/src/components/Header/Header.tsx
apps/portals/my-pages/src/components/Sidemenu/Sidemenu.css.ts
apps/portals/my-pages/src/components/Sidemenu/Sidemenu.tsx

fix(my-pages): revert using isMobile hook (#18237)

---

apps/services/contentful-entry-tagger/infra/contentful-entry-tagger-service.ts
charts/islandis-services/contentful-entry-tagger-service/values.prod.yaml
charts/islandis/values.prod.yaml

fix(contentful-entry-tagger): Fix prod url

---

scripts/ci/docker/const.mjs

ci: declare future release branches (#18316)

---

apps/contentful-apps/pages/fields/organization-parent-subpage-slug-field.tsx
apps/contentful-apps/pages/sidebars/preview-link.tsx
apps/contentful-apps/utils/index.ts

fix(contentful-apps): Hotfix, Organization subpage slug check logic adjustments (#18324)

---

apps/application-system/api/project.json
libs/application/template-api-modules/src/lib/modules/templates/aosh/training-license-on-a-work-machine/emailGenerators/applicationDeleteEmail.ts
libs/application/template-api-modules/src/lib/modules/templates/aosh/training-license-on-a-work-machine/emailGenerators/requestReviewEmail.ts
libs/application/template-api-modules/src/lib/modules/templates/aosh/training-license-on-a-work-machine/smsGenerators/requestReviewSms.ts
libs/application/template-api-modules/src/lib/modules/templates/aosh/training-license-on-a-work-machine/training-license-on-a-work-machine.utils.ts
libs/application/templates/aosh/training-license-on-a-work-machine/src/forms/ReviewForm/index.ts
libs/application/templates/aosh/training-license-on-a-work-machine/src/forms/TrainingLicenseOnAWorkMachineForm/OverviewSection.ts
libs/application/templates/aosh/training-license-on-a-work-machine/src/forms/TrainingLicenseOnAWorkMachineForm/index.ts
libs/application/templates/aosh/training-license-on-a-work-machine/src/lib/TrainingLicenseOnAWorkMachineTemplate.ts
libs/application/templates/aosh/training-license-on-a-work-machine/src/lib/constants.ts

Application has been tested on dev and are in final test faces on prod.
* Missing object in project.json so the images are visible in email.
* Changes to email message.
* Missing initReview and some changes to companyinfo in service.
* Removing unnecessary conclusion screen because of conclusion issue on last screens.

fix(training-license-on-a-work-machine): hotfix training license fixes

---

libs/application/templates/aosh/work-accident-notification/src/forms/WorkAccidentNotificationForm/AccidentSection/about.ts
libs/application/templates/aosh/work-accident-notification/src/lib/dataSchema.ts

fix(application-system): adding required to exactLocation and min/max

---

.github/actions/update-helm-values/action.yml
.github/workflows/install.yml
.github/workflows/merge-queue.yml
scripts/ci/docker/generate-tag.mjs

ci: push helm values for release to a different branch (#18370)

---

libs/application/template-api-modules/src/lib/modules/templates/index.ts
libs/application/template-api-modules/src/lib/modules/templates/rental-agreement/rental-agreement-email.ts
libs/application/template-api-modules/src/lib/modules/templates/rental-agreement/rental-agreement.module.ts
libs/application/template-api-modules/src/lib/modules/templates/rental-agreement/rental-agreement.service.ts
libs/application/templates/rental-agreement/src/fields/Summary/SummaryEdit.tsx
libs/application/templates/rental-agreement/src/forms/draft/summaryDraftSection.ts
libs/application/templates/rental-agreement/src/lib/RentalAgreementTemplate.ts
libs/application/templates/rental-agreement/src/lib/getAssigneesNationalIdList.ts
libs/email-service/src/tools/design/copy.hbs
libs/email-service/src/tools/design/heading.hbs
libs/email-service/src/tools/design/headingblock.hbs
libs/email-service/src/tools/design/left.hbs
libs/email-service/src/tools/design/right.hbs
libs/email-service/src/tools/helpers/index.ts

feat(rental-agreement): Email contract summary for review

---

.github/workflows/config-values.yaml

chore: increase timeoujt for helm validation

---

.github/actions/main.ts

chore: rebuild

---

.github/actions/force-build.mjs
nx.json

fix: force rebuild

---

libs/application/templates/rental-agreement/src/forms/draft/rentalHousing/rentalHousingSpecialProvisions.ts
libs/application/templates/rental-agreement/src/lib/messages/housing/specialProvisions.ts

feat(rental-agreement): Add conditional warning banner to "Sérákvæði" step

---

.github/actions/force-build.mjs

chore: forcee rebuild

---

.github/actions/setup-yarn/action.yml
.github/workflows/docker.yml
.github/workflows/install.yml
.github/workflows/merge-queue.yml
.github/workflows/pullrequest.yml
.github/workflows/push.yml

fix: setup-yarn

---

apps/services/auth/ids-api/esbuild.json

Fix migration issue in auth ids api for release.
Unblock release.
N/A

fix(ids-api): Fix auth ids migration release

---

.github/actions/force-build.mjs
README.md

chore: force build again

---

.github/actions/force-build.mjs
scripts/ci/generate-docker-chunks.sh

chore: fix rebuild chunks

---

.github/actions/force-build.mjs
README.md

fix: Fforce build again again

---

apps/air-discount-scheme/web/infra/web.ts
charts/islandis-services/air-discount-scheme-web/values.dev.yaml
charts/islandis-services/air-discount-scheme-web/values.prod.yaml
charts/islandis-services/air-discount-scheme-web/values.staging.yaml
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

fix: remove ads path rewrite and move to aws

---

libs/application/templates/inheritance-report/src/lib/InheritanceReportTemplate.ts

chore(application-ir): Update pruning for application (#18455)

---

.github/actions/force-build.mjs

Rebuild for hotfix xroad fix ojoi

fix(ojoi): rebuild for ojoi hotfix

---

libs/auth-api-lib/migrations/20241121135100-migrate-rikiskaup-to-fjs.js

Re-add the Rikiskaup -> FJS migration script to release.
The previous attempt didn't handle possible uniqueness issue. 
N/A

fix(ids-api): Fix fjs migration release

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/children/children.service.ts

feat(parental-leave): connect otherParent to primary application when added manually

---

scripts/ci/docker/get-data.mjs

fix: sha url

---

.github/actions/force-build.mjs
.github/workflows/merge-queue.yml

Reverts island-is/island.is#18613

Revert "ci: remove setup yarn mq"

---

.github/workflows/merge-queue.yml
.github/workflows/pre-checks.yml
.github/workflows/push.yml

Reverts island-is/island.is#18611

Revert "ci: arc-shared runners"

---

.github/workflows/push.yml

ci: fix pre-release workflow

---

apps/web/components/SearchInput/SearchInput.tsx
apps/web/screens/queries/Search.tsx
libs/cms/src/lib/search/importers/utils.ts

Cherry picked from: #18621 and #18623

fix(web): Hotfix - Organization subpage suggested search fix

---

apps/web/screens/Layouts/SidebarLayout.css.ts
apps/web/screens/OfficialJournalOfIceland/OJOIAdvert.tsx
apps/web/screens/OfficialJournalOfIceland/OJOICasesInProgress.tsx
apps/web/screens/OfficialJournalOfIceland/OJOICategories.tsx
apps/web/screens/OfficialJournalOfIceland/OJOISearch.tsx

PR resulting from running this on `main`:
```bash
yarn nx run-many -t lint --fix --parallel 10
```

chore(web): Lintfix web

---

libs/application/template-api-modules/src/lib/modules/templates/children-residence-change-v2/children-residence-change.service.ts

fix(crc): Remove throw for empty postal code

---

apps/web/components/Header/LoginButton.tsx

Cherry picked commit from #18625

fix(web): Login button hydration error fix

---

apps/web/components/Header/LoginButton.tsx

fix(web): Fix hydration error for LoginButton component #18666

---

apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculator.tsx
apps/web/screens/Organization/SocialInsuranceAdministration/translationStrings.ts

feat(web): Hotfix - Pension calculator markdown text

---

libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/fields/Review/index.tsx
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/fields/Review/review-groups/Attachments.tsx
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/fields/Review/review-groups/Questions.tsx
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/forms/MedicalAndRehabilitationPaymentsForm/generalInformationSection/questionsSubSection.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/lib/constants.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/lib/dataSchema.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/lib/medicalAndRehabilitationPaymentsUtils.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/lib/messages.ts

[[TS-1017] Questions Screen](https://dit-iceland.atlassian.net/jira/software/c/projects/TS/boards/82?selectedIssue=TS-1017)

feat(medical-and-rehabilitation-payments): Questions Screen

---

libs/application/templates/rental-agreement/src/fields/PropertySearch/components/PropertyTableHeader.tsx
libs/application/templates/rental-agreement/src/fields/PropertySearch/components/PropertyTableRow.tsx
libs/application/templates/rental-agreement/src/fields/PropertySearch/components/PropertyTableUnits.tsx
libs/application/templates/rental-agreement/src/fields/PropertySearch/index.tsx
libs/application/templates/rental-agreement/src/fields/Summary/PropertyInfoSummary.tsx
libs/application/templates/rental-agreement/src/fields/Summary/RentalInfoSummary.tsx
libs/application/templates/rental-agreement/src/fields/Summary/SummaryEdit.tsx
libs/application/templates/rental-agreement/src/fields/Summary/SummaryNoEdit.tsx
libs/application/templates/rental-agreement/src/forms/draft/rentalHousing/rentalHousingPropertyInfo.ts
libs/application/templates/rental-agreement/src/forms/draft/rentalHousing/rentalHousingSpecialProvisions.ts
libs/application/templates/rental-agreement/src/lib/constants.ts
libs/application/templates/rental-agreement/src/lib/dataSchema.ts
libs/application/templates/rental-agreement/src/lib/messages/housing/registerProperty.ts
libs/application/templates/rental-agreement/src/lib/messages/summary.ts
libs/clients/hms/src/lib/hms.config.ts
libs/clients/hms/src/lib/hms.provider.ts

- [https://app.asana.com/0/1208271027457465/1208588707209371/f](https://app.asana.com/0/1208271027457465/1208588707209371/f)
- [https://app.asana.com/0/1208271027457465/1209408125565357/f](https://app.asana.com/0/1208271027457465/1209408125565357/f)
When choosing a property unit you can edit/change: 
- Edit/change the size of the rented property
- Add number of rooms being rented
Validation for: 
- Sum of number of rooms for chosen units cannot be less than 1 
- If property size is edited, description is needed
Add updated/added items to summary
If tenant is only renting part of the property (one room within an apartment etc.) the size of the rented unit needs to be accordingly.
---------------------
---------------------
---------------------

feat(rental-agreement): Propertysearch chosen units and changed values

---

libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/fields/Review/index.tsx
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/fields/Review/review-groups/SickPay.tsx
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/forms/MedicalAndRehabilitationPaymentsForm/generalInformationSection/sickPaySubSection.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/lib/dataSchema.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/lib/medicalAndRehabilitationPaymentsUtils.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/lib/messages.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/utils/constants.ts

[TS-1018](https://dit-iceland.atlassian.net/browse/TS-1018
)

feat(marp): Add sickPay

---

libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/forms/MedicalAndRehabilitationPaymentsForm/certificateForSicknessAndRehabilitationSection/activityAndParticipationImpairment.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/forms/MedicalAndRehabilitationPaymentsForm/certificateForSicknessAndRehabilitationSection/applicationForMedicalAndRehabilitationPayments.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/forms/MedicalAndRehabilitationPaymentsForm/certificateForSicknessAndRehabilitationSection/index.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/forms/MedicalAndRehabilitationPaymentsForm/certificateForSicknessAndRehabilitationSection/information.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/forms/MedicalAndRehabilitationPaymentsForm/certificateForSicknessAndRehabilitationSection/managedBy.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/forms/MedicalAndRehabilitationPaymentsForm/certificateForSicknessAndRehabilitationSection/mentalImpairment.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/forms/MedicalAndRehabilitationPaymentsForm/certificateForSicknessAndRehabilitationSection/physicalImpairment.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/forms/MedicalAndRehabilitationPaymentsForm/index.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/lib/messages.ts

[[TS-1021] Certificate for Sickness and Rehabilitation Screen](https://dit-iceland.atlassian.net/jira/software/c/projects/TS/boards/82?selectedIssue=TS-1021)

feat(medical-and-rehabilitation-payments): Certificate for Sickness and Rehabilitation Screen

---

libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/fields/Review/index.tsx
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/fields/Review/review-groups/RehabilitationPlan.tsx
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/forms/MedicalAndRehabilitationPaymentsForm/index.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/forms/MedicalAndRehabilitationPaymentsForm/rehabilitationPlanSection/comprehensiveAssessment.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/forms/MedicalAndRehabilitationPaymentsForm/rehabilitationPlanSection/index.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/forms/MedicalAndRehabilitationPaymentsForm/rehabilitationPlanSection/information.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/forms/MedicalAndRehabilitationPaymentsForm/rehabilitationPlanSection/rehabilitationObjective.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/forms/MedicalAndRehabilitationPaymentsForm/rehabilitationPlanSection/serviceProvider.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/lib/dataSchema.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/lib/medicalAndRehabilitationPaymentsUtils.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/lib/messages.ts

[[TS-1022] Rehabilitation Plan Screen](https://dit-iceland.atlassian.net/jira/software/c/projects/TS/boards/82?selectedIssue=TS-1022)

feat(medical-and-rehabilitation-payments): Rehabilitation Plan Screen

---

scripts/ci/generate-docker-chunks.sh

Downstream deps are not being correctly set for FDs

fix: removed affected flag from generate docker chunks

---

infra/src/feature-env.ts

Fix for typing in infra files to unblock release

fix: fix typing for release 36 1 0

---

.github/workflows/push.yml
infra/src/feature-env.ts
scripts/ci/generate-docker-chunks.sh

* Revert "revert: argo feature deployments (#18813)"
This reverts commit 4b70c2fff580591ba3b78b2aa4cdc03c443a183b.
* force deploy
* removed force deploy
* added debug logging
* fixed debugging

revert: argo feature deployments (#18813) (#18814)

---

apps/payments/components/ThreeDSecure/ThreeDSecure.tsx
apps/payments/pages/_app.tsx
apps/payments/pages/app.css

Including #18841  in the release

fix(payments): Fix 3ds success layout inside iframe (#18841)

---

apps/payments/messages/generic.ts
apps/payments/utils/error/error.ts
apps/services/payments/src/app/cardPayment/cardPayment.controller.ts
libs/shared/constants/src/lib/paymentErrorCodes.ts

fix(payments): Verify that paid amount is correct (#18857)

---

libs/application/templates/social-insurance-administration/core/src/lib/messages.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/forms/Prerequisites/externalDataSubSection.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/lib/messages.ts

[TS-1015](https://dit-iceland.atlassian.net/browse/TS-1015)

feat(medical-and-rehabilitation-payments):  Prerequisites providers text

---

libs/application/template-api-modules/src/lib/modules/shared/api/national-registry/national-registry.service.ts
libs/application/template-api-modules/src/lib/modules/templates/secondary-school/utils.ts
libs/application/templates/secondary-school/src/fields/overview/CustodianOverview.tsx
libs/application/templates/secondary-school/src/forms/secondarySchoolForm/userInformationSection/custodianSubSection.ts
libs/application/types/src/lib/template-api/shared-api/models/national-registry/custodian.ts

fix(application-system): using name instead of givenName - release

---

libs/portals/my-pages/health/src/screens/Medicine/wrapper/MedicinePaymentParticipationWrapper.tsx

fix(my-pages-health): hotfix - health messages navigation (#18899)

---

libs/application/template-api-modules/src/lib/modules/templates/aosh/training-license-on-a-work-machine/training-license-on-a-work-machine.utils.ts
libs/application/templates/aosh/training-license-on-a-work-machine/src/fields/HandleApproveOrReject/index.tsx
libs/application/templates/aosh/training-license-on-a-work-machine/src/forms/ReviewForm/ApplicationStatusSection.ts
libs/application/templates/aosh/training-license-on-a-work-machine/src/forms/TrainingLicenseOnAWorkMachineForm/AssigneeInformationSection.ts
libs/application/templates/aosh/training-license-on-a-work-machine/src/lib/messages/overview.ts
libs/application/templates/aosh/training-license-on-a-work-machine/src/utils/getAssigneeInformation.ts
libs/application/templates/aosh/training-license-on-a-work-machine/src/utils/getMachineTenureInformation.ts
libs/application/templates/aosh/training-license-on-a-work-machine/src/utils/index.ts

fix(training-license-on-a-work-machine): hotfix

---

libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/ChildrenSupportingDocuments/ChildrenOtherDocumentsSubSection.ts

fix(citizenship):  hotfix error in child other document

---

libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/lib/MedicalAndRehabilitationPaymentsTemplate.ts
libs/feature-flags/src/lib/features.ts

[TS-1032](https://dit-iceland.atlassian.net/browse/TS-1032)
Add feature flag isMedicalAndRehabilitationPaymentsEnabled

chore(medical-and-rehabilitation-payments): Add feature flag

---

libs/application/templates/aosh/seminars/src/utils/getChargeItems.ts

fix(seminars): quantity update release

---

libs/clients/secondary-school/src/clientConfig.json
libs/clients/secondary-school/src/lib/secondarySchoolClient.service.ts

fix(secondary school): Update clientConfig for secondarySchool (release)

---

apps/contentful-apps/components/editors/OverviewLinksEditor/OverviewLinksEditor.tsx
libs/cms/src/lib/models/overviewLinks.model.ts

feat(web): Hotfix - Overview links, "english locale" in JSON field (#19049)

---

.github/workflows/pullrequest-close.yml

Fixes workflows not running when triggered via automation (e.g. https://github.com/island-is/island.is/pull/19097)

fix: use valid token

---

apps/payments/components/PageCard/PageCard.css.ts
apps/payments/components/PageCard/PageCard.tsx
apps/payments/i18n/withLocale.tsx
apps/payments/messages/3ds.ts
apps/payments/messages/card.ts
apps/payments/messages/generic.ts
apps/payments/messages/invoice.ts
apps/payments/pages/3ds/index.tsx
apps/payments/pages/[locale]/[paymentFlowId]/index.tsx
apps/payments/pages/index.tsx
apps/payments/project.json
apps/payments/utils/error/error.ts

Automated cherry-pick of 1d9f5c76c21e34dc9bd9cdab751b67dca22219c6

chore: automated cherry-pick of 1d9f5c76c21e34dc9bd9cdab751b67dca22219c6

---

apps/application-system/api/infra/application-system-api.ts
charts/islandis-services/application-system-api/values.dev.yaml
charts/islandis-services/application-system-api/values.staging.yaml
charts/islandis/values.dev.yaml
charts/islandis/values.staging.yaml
libs/application/template-api-modules/src/lib/modules/templates/complaints-to-althingi-ombudsman/complaints-to-althingi-ombudsman.utils.ts
libs/application/template-api-modules/src/lib/modules/templates/complaints-to-althingi-ombudsman/models/complaint.ts
libs/application/templates/complaints-to-althingi-ombudsman/src/fields/ComplaintOverview/ComplainedFor.tsx
libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanApplication.ts
libs/application/templates/complaints-to-althingi-ombudsman/src/index.ts
libs/application/templates/complaints-to-althingi-ombudsman/src/lib/dataSchema.ts
libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/information.ts
libs/application/templates/complaints-to-althingi-ombudsman/src/shared/constants.ts
libs/application/templates/complaints-to-althingi-ombudsman/src/utils.ts
libs/clients/althingi-ombudsman/src/clientConfig.yml
libs/clients/althingi-ombudsman/src/lib/clients-althingi-ombudsman.config.ts

…þingi (#17812)
* intital setup pre design
* undoing change to user-monitor.ts
* Adding gender to on behalf of complainers info
* Update complaints-to-althingi-ombudsman.service.ts
* Update complaints-to-althingi-ombudsman.service.ts
* Testing if this works on dev without gender changes
* Update dataSchema.ts
* adding gender back in
* removing a log line i added
* Update complaints-to-althingi-ombudsman.service.ts
* Update constants.ts
* updating config
* Updating stuff after feedback from gopro
* Cleanup and metadata
* Update complaints-to-althingi-ombudsman.utils.ts

fix(kvortun-althingi): Althingi gender hotfix

---

libs/application/templates/secondary-school/src/forms/secondarySchoolForm/schoolSection/utils.ts
libs/application/templates/secondary-school/src/forms/secondarySchoolForm/userInformationSection/personalSubSection.ts
libs/application/templates/secondary-school/src/utils/helperFunctions/getSchoolsData.ts
libs/application/templates/secondary-school/src/utils/helperFunctions/index.ts

fix(secondary school): Add check Array.isArray when fetching schools data from external data (release)

---

libs/auth-api-lib/seeders/data/scope-landspitali-patient-data.ts

chore(auth): add lsh scope (#19239)

---

libs/api/domains/official-journal-of-iceland-application/src/models/getUserInvolvedParties.response.ts

fix(ojoi): national id return res - hotfix

---

.github/workflows/config-values.yaml

See
- https://github.com/island-is/island.is/actions/runs/15585852610/job/43891959498?pr=19279#step:21:7
- https://islandis.slack.com/archives/C019LNRM6LE/p1749645326202349
- https://islandis.slack.com/archives/C01QUBMEYQ4/p1749648370211049?thread_ts=1749639430.772169&cid=C01QUBMEYQ4

fix(ci): `Post Setup yarn` fails because of missing region

---

libs/application/template-api-modules/src/lib/modules/templates/directorate-of-immigration/citizenship/citizenship.service.ts
libs/application/templates/directorate-of-immigration/citizenship/src/fields/Review/DocumentReview.tsx
libs/application/templates/directorate-of-immigration/citizenship/src/lib/dataSchema.ts

fix(citizenship): fixed nullable error in child documents

---

libs/application/template-api-modules/src/lib/modules/templates/hms/fire-compensation-appraisal/fire-compensation-appraisal.service.ts

Make sure auth goes with request to hms

fix(hms-fca): auth headers hotfix

---

apps/web/components/OfficialJournalOfIceland/OJOIAdvertDisplay.tsx

fix(ojoi): Update appendix display - hotfix

---

libs/application/templates/aosh/practical-exam/src/fields/Components/ExamInputs.tsx
libs/application/templates/aosh/practical-exam/src/forms/PracticalExamForm/ExamineeSection/index.ts
libs/application/templates/aosh/practical-exam/src/forms/PracticalExamForm/InstructorSection/index.ts
libs/application/templates/aosh/practical-exam/src/lib/dataSchema.ts
libs/application/templates/aosh/practical-exam/src/lib/messages/examCategories.ts
libs/island-ui/core/src/lib/Select/Select.css.ts

fix(application-system): Hotfix-ing issues with practical exam and slysaskraning

---

libs/application/api/payment/src/lib/payment.service.ts

feat(application-system-api): Change getReturnUrl to also return cancelUrl for payment #19427

---

.github/CODEOWNERS
apps/web/pages/stjornartidindi/nr/index.ts

* fix(ojoi): query params are wrong
* also make hugsmidjan codeowners for stjornartidindi pages

fix(ojoi): query params are wrong (#19509)

---

libs/clients/national-registry/v3-applications/src/lib/nationalRegistryV3Applications.service.ts

fix(application-system): Fix handling of unknown spouse (#19521)

---

libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/forms/MedicalAndRehabilitationPaymentsForm/conclusionSection.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/lib/messages.ts

[TS-1026](https://dit-iceland.atlassian.net/browse/TS-1026)

feat(medical-and-rehabilitation-payments): Conclusion screen

---

libs/api/domains/user-profile/src/lib/V2/userProfile.service.ts
libs/api/domains/user-profile/src/lib/userProfile.model.ts
libs/portals/my-pages/graphql/src/lib/queries/getUserProfile.ts
libs/portals/my-pages/information/src/components/PersonalInformation/Forms/ProfileForm/ProfileForm.tsx
libs/portals/my-pages/information/src/screens/UserProfile/UserProfile.tsx

Hotfix Íslykla service error catch in GQL from #19506 
So user profile details will be returned if íslyklaservice is having troubles.

fix(user-profile): Add a bankInfoError boolean flag in GQL to handle Islykla errors.

---

apps/web/pages/stjornartidindi/nr/index.ts

fix(ojoi): Find recordId parameter case-insensitively (#19526)

---

libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/forms/MedicalAndRehabilitationPaymentsForm/generalInformationSection/employeeSickPaySubSection.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/forms/MedicalAndRehabilitationPaymentsForm/generalInformationSection/unionSickPaySubSection.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/lib/messages.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/utils/constants.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/utils/medicalAndRehabilitationPaymentsUtils.ts

[TS-1019](https://dit-iceland.atlassian.net/browse/TS-1019)
- Disable dates in the future if “Lokið” and disable dates in the past if “Lýkur” (for union AND employee sick pay)
- Remove file upload from union sick pay
- Fix typo

feat(medical-and-rehabilitation-payments): Update union and employee sick pay screens

---

apps/web/components/OfficialJournalOfIceland/OJOIAppendix.tsx
apps/web/components/OfficialJournalOfIceland/OJOIHomeIntro.tsx
apps/web/components/OfficialJournalOfIceland/OJOIUtils.ts
apps/web/screens/OfficialJournalOfIceland/OJOIAdvert.tsx
apps/web/screens/OfficialJournalOfIceland/OJOIHome.tsx
apps/web/screens/OfficialJournalOfIceland/OJOISearch.tsx
apps/web/screens/OfficialJournalOfIceland/hooks/useAdverts.ts
apps/web/screens/OfficialJournalOfIceland/lib/advert-params.mapper.ts
apps/web/screens/OfficialJournalOfIceland/messages.ts
libs/api/domains/official-journal-of-iceland/src/lib/models/advert.input.ts
libs/api/domains/vehicles/src/lib/utils/basicVehicleInformationMapper.ts
libs/clients/official-journal-of-iceland/public/src/clientConfig.json

fix(ojoi): Filter params by year hotfix

---

libs/api/domains/social-insurance/src/lib/models/general/countries.model.ts
libs/api/domains/social-insurance/src/lib/models/general/country.model.ts
libs/api/domains/social-insurance/src/lib/models/general/educationalInstitution.model.ts
libs/api/domains/social-insurance/src/lib/models/general/educationalInstitutions.model.ts
libs/api/domains/social-insurance/src/lib/models/general/general.model.ts
libs/api/domains/social-insurance/src/lib/models/general/union.model.ts
libs/api/domains/social-insurance/src/lib/resolvers/general.resolver.ts
libs/api/domains/social-insurance/src/lib/socialInsurance.service.ts
libs/application/template-api-modules/src/lib/modules/templates/social-insurance-administration/social-insurance-administration-utils.ts
libs/application/template-api-modules/src/lib/modules/templates/social-insurance-administration/social-insurance-administration.service.ts
libs/application/templates/social-insurance-administration/core/src/graphql/queries.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/dataProviders/index.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/fields/RehabilitationPlan/index.tsx
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/forms/MedicalAndRehabilitationPaymentsForm/generalInformationSection/benefitsFromAnotherCountrySubSection.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/forms/MedicalAndRehabilitationPaymentsForm/generalInformationSection/index.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/forms/MedicalAndRehabilitationPaymentsForm/generalInformationSection/questionsSubSection.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/forms/MedicalAndRehabilitationPaymentsForm/generalInformationSection/unionSickPaySubSection.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/forms/Prerequisites.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/lib/MedicalAndRehabilitationPaymentsTemplate.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/lib/dataSchema.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/lib/messages.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/types.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/utils/conditionUtils.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/utils/constants.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/utils/medicalAndRehabilitationPaymentsUtils.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/utils/overviewFields.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/utils/overviewItems.ts
libs/clients/social-insurance-administration/src/clientConfig.json
libs/clients/social-insurance-administration/src/lib/socialInsuranceAdministrationClient.service.ts
libs/clients/social-insurance-administration/src/lib/socialInsuranceAdministrationClient.type.ts

[[TS-1017] Questions Screen](https://dit-iceland.atlassian.net/jira/software/c/projects/TS/boards/82?issueParent=69125&selectedIssue=TS-1017)
[[TS-1070] Move "Færðu greiðslur frá öðru landi...?" to separate screen](https://dit-iceland.atlassian.net/jira/software/c/projects/TS/boards/82?selectedIssue=TS-1070)

feat(medical-and-rehabilitation-payments): Update Questions Screen

---

libs/api/domains/user-profile/src/lib/islykill.service.ts

Hotfix #19576 
To fix adding bank info for new profiles.
N/A

fix(user-profile): Fix bank info update for new profiles (#19576)

---

libs/application/templates/directorate-of-immigration/citizenship/src/fields/CriminalRecords/index.tsx
libs/application/templates/directorate-of-immigration/citizenship/src/fields/Parents/ParentRepeaterItem.tsx
libs/application/templates/directorate-of-immigration/citizenship/src/fields/Parents/index.tsx

fix(citizenship): fixing infinite loop release

---

libs/application/templates/hms/terminate-rental-agreement/src/forms/completedForm/index.ts
libs/application/templates/hms/terminate-rental-agreement/src/forms/mainForm/chooseContractSection.ts
libs/application/templates/hms/terminate-rental-agreement/src/forms/mainForm/fileUploadSection.ts
libs/application/templates/hms/terminate-rental-agreement/src/forms/mainForm/overviewSection.ts
libs/application/templates/hms/terminate-rental-agreement/src/lib/dataSchema.ts
libs/application/templates/hms/terminate-rental-agreement/src/lib/messages/chooseContractMessages.ts
libs/application/templates/hms/terminate-rental-agreement/src/lib/messages/miscMessages.ts
libs/application/templates/hms/terminate-rental-agreement/src/lib/template.ts
libs/application/types/src/lib/ApplicationTypes.ts

* Change text key to markdown
* Fix conclusionmessage
* User can not delete completed applications
* Enable uploading max 3 docs
* Remove terminationTypeOverview
* Fix done message
* Roll back multi upload due to api limitation
* Fix data schema
* Change application name and actionCard title
* Contracts to singular
* lintfix

fix(application-system): Terminate rental agreement fixes (#19653)

---

apps/contentful-apps/components/sitemap/EditMenu.tsx
apps/contentful-apps/components/sitemap/MoveNodesButton.tsx
apps/contentful-apps/components/sitemap/SitemapNode.css.ts
apps/contentful-apps/components/sitemap/SitemapNode.tsx
apps/contentful-apps/components/sitemap/SitemapNodeContent.tsx
apps/contentful-apps/components/sitemap/SitemapTreeField.css.ts
apps/contentful-apps/components/sitemap/SitemapTreeField.tsx
apps/contentful-apps/components/sitemap/SitemapTreeFieldDialog.tsx
apps/contentful-apps/components/sitemap/utils.ts
libs/shared/types/src/lib/api-cms-domain.ts

feat(contentful-apps): Hotfix, Sitemap - Categories can now have a status (draft, published) (#19683)

---

apps/unicorn-app/src/app/page.tsx

fix: Make sure unicorn are deployed

---

libs/api/domains/social-insurance/src/lib/models/medicalDocuments/certificateForSicknessAndRehabilitation.model.ts
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/fields/CertificateForSicknessAndRehabilitation/index.tsx
libs/application/templates/social-insurance-administration/medical-and-rehabilitation-payments/src/graphql/queries.ts

#19714
Updated Certificate for Sickness and Rehabilitation

feat(medical-and-rehabilitation-payments): Updated Certificate for Sickness and Rehabilitation

---

apps/services/form-system/infra/form-system.ts
charts/islandis-services/services-form-system-api/values.dev.yaml
charts/islandis/values.dev.yaml

Reverts island-is/island.is#19798

Revert "fix: add national registry to env and secret"

---

libs/application/templates/official-journal-of-iceland/src/hooks/useAdverts.ts

hotfix:: https://github.com/island-is/island.is/pull/19818

fix(ojoi): Update query to use full - hotfix

---

apps/web/screens/queries/fragments.ts
libs/clients/vehicles/src/lib/vehiclesClient.config.ts
libs/portals/my-pages/assets/src/screens/VehicleBulkMileageUpload/VehicleBulkMileageUpload.tsx
libs/portals/my-pages/information/src/lib/messages.ts
libs/portals/my-pages/information/src/screens/UserInfo/UserInfo.tsx

fix(my-pages): vehicle timeout - grant card - legal residence tooltip

---

apps/application-system/api/src/app/modules/application/application.controller.ts
apps/application-system/api/src/app/modules/application/charge/application-charge.service.ts
libs/application/template-api-modules/src/lib/modules/shared/api/payment/payment.service.ts
libs/application/templates/examples/example-payment/src/lib/examplePaymentTemplate.ts
libs/clients/charge-fjs-v2/src/lib/chargeFjsV2Client.service.ts
libs/clients/charge-fjs-v2/src/lib/chargeFjsV2Client.utils.ts

* Fetch flowid from paymentUrl
* Trigger user-profile
* Add paymentservice
* Stop deleting the payment model when user deletes application
* Logging
* Allow delete of completed examples
* More logging
* Example payment delete charge
* lintfix
* More logging
* Fix payment.definition parse
* Cleanup

fix(): fix getpaymentId (#19826)

---

libs/application/templates/hms/fire-compensation-appraisal/src/lib/dataSchema.ts

fix(application-system): Fix usage unit validation

---

apps/services/auth/public-api/infra/auth-public-api.ts
charts/identity-server-services/services-auth-public-api/values.dev.yaml
charts/identity-server-services/services-auth-public-api/values.prod.yaml
charts/identity-server-services/services-auth-public-api/values.staging.yaml
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml

fix: test ids path

---

libs/application/templates/general-fishing-license/src/dataProviders/index.ts
libs/application/templates/general-fishing-license/src/dataProviders/mockPaymentCatalog.ts
libs/application/templates/general-fishing-license/src/fields/Overview/index.tsx
libs/application/templates/general-fishing-license/src/forms/GeneralFishingLicensePrerequisitesForm/externalDataSection.ts
libs/application/templates/general-fishing-license/src/lib/GeneralFishingLicenseTemplate.ts
libs/application/templates/general-fishing-license/src/lib/dataSchema.ts
libs/application/templates/general-fishing-license/src/lib/messages/fishingLicense.ts
libs/application/templates/general-fishing-license/src/lib/messages/shipSelection.ts
libs/application/templates/general-fishing-license/src/shared/constants.ts
libs/application/templates/general-fishing-license/src/types/index.ts
libs/clients/fishing-license/src/lib/types/index.ts

Adding a new general fishing license type
It was requested

fix(general-fishing-license): New fishing license type

---

apps/services/auth/public-api/infra/auth-public-api.ts
charts/identity-server-services/services-auth-public-api/values.dev.yaml
charts/identity-server-services/services-auth-public-api/values.prod.yaml
charts/identity-server-services/services-auth-public-api/values.staging.yaml
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml

Reverts island-is/island.is#19941

fix: Revert "fix: test ids path"

---

apps/services/auth/public-api/infra/auth-public-api.ts
charts/identity-server-services/services-auth-public-api/values.dev.yaml
charts/identity-server-services/services-auth-public-api/values.prod.yaml
charts/identity-server-services/services-auth-public-api/values.staging.yaml
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml

fix: revert route changes

---

apps/download-service/src/app/modules/vehicles-documents/vehicle-document.controller.ts
libs/api/domains/vehicles/src/lib/resolvers/vehicles.resolver.ts
libs/clients/vehicles/src/clientConfig.json
libs/clients/vehicles/src/lib/input/ownershipReport.input.ts
libs/clients/vehicles/src/lib/vehiclesClient.service.ts

hotfix: https://github.com/island-is/island.is/pull/20125

fix(my-pages-assets): Certificate of ownership hotfix

---

apps/web/components/connected/landspitali/Grants/Grants.tsx
apps/web/components/connected/landspitali/Grants/translation.strings.ts
apps/web/components/connected/landspitali/MemorialCards/MemorialCards.tsx
apps/web/components/connected/landspitali/MemorialCards/translation.strings.ts

https://github.com/user-attachments/assets/a52c2ed8-a973-4420-8668-73e6df2c4c30
https://github.com/user-attachments/assets/6b8a4e00-9a02-4063-b867-06a7a43122d7

feat(web): Visual changes for grants and memorial cards on the web

---

libs/api/domains/official-journal-of-iceland-application/src/lib/ojoiApplication.service.ts
libs/api/domains/official-journal-of-iceland-application/src/models/getUserInvolvedParties.input.ts
libs/api/domains/official-journal-of-iceland-application/src/models/postComment.input.ts
libs/application/templates/official-journal-of-iceland/src/hooks/useComments.ts
libs/application/templates/official-journal-of-iceland/src/hooks/useInvolvedParties.ts
libs/application/templates/official-journal-of-iceland/src/lib/messages/involved-parties.ts
libs/clients/official-journal-of-iceland/application/src/clientConfig.json

hotfix: https://github.com/island-is/island.is/pull/20219

fix(ojoi): Name from application (hotfix)

---

libs/application/templates/directorate-of-immigration/citizenship/src/fields/CriminalRecords/index.tsx
libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/SupportingDocumentsSection/OtherDocumentsSubSection.ts

fix(citizenship): adding multiple uploads release
