libs/auth-nest-tools/src/lib/jwt.payload.ts, libs/auth-nest-tools/src/lib/jwt.strategy.spec.ts, libs/auth-nest-tools/src/lib/jwt.strategy.ts
=> feat(auth-nest-tools): Support for renamed actor claim

.github/workflows/push.yml, apps/web/pages/_document.tsx, infra/src/dsl/feature-jobs.ts, infra/src/dsl/serialize-to-yaml.ts
- dummy change
- fixing error in CI
- Another dummy change
- fixing one more bug in the ci
=> chore: post-helm config migration fixes

apps/api/infra/api.ts, apps/application-system/api/infra/application-system-api.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml
Bugged the helm charts config - fixxing it now.
=> fix(helm-config-payment): fixed config errors

libs/application/templates/party-application/src/fields/SupremeCourtOverview/index.tsx, libs/application/templates/party-application/src/graphql/queries.ts, libs/application/templates/party-letter/src/graphql/queries.ts
Taking out invalidated from endorsement metadata queries
=> fix(party-applocation): cleaning out usage of invalidated

apps/api/infra/api.ts, apps/application-system/api/infra/application-system-api.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml
=> fix(application-payment): wrong env variables set in charts

apps/application-system/form/src/auth.ts, apps/service-portal/src/auth.ts
Scopes related to the endorsement systems need to be revised.
We are removing them to fix dev deployments.
=> chore: Remove problematic scopes

apps/judicial-system/web/src/utils/hooks/use-case/requestSignatureGql.ts, apps/judicial-system/web/src/utils/hooks/use-case/useCase.tsx, apps/judicial-system/web/src/utils/mutations.ts
https://app.asana.com/0/1199153462262248/1200521822561059/f
bugfix
bug
=> fix(judical-system): Fixes infinite loop when notifying prison

package.json, yarn.lock
=> chore(core): security fix

libs/feature-flags/README.md
=> docs: fix feature flag page formatting

.github/workflows/config-values.yaml
=> fix: CI secrets check silently failing

apps/services/auth-public-api/src/environments/environment.ts
=> fix(auth-public-api): Add openid to requested scope

charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml, infra/src/uber-charts/islandis.ts, libs/application/templates/party-application/src/lib/PartyApplicationTemplate.ts, libs/application/templates/party-letter/src/lib/PartyLetterApplicationTemplate.ts
This is needed to deploy these systems
- Added template config
- Added helm config
=> chore: Enable party application systems

apps/judicial-system/backend/src/app/formatters/requestPdf.ts, apps/judicial-system/backend/src/app/formatters/rulingPdf.ts
https://app.asana.com/0/1199153462262248/1200358894827725
Fix
Fix
=> fix(judicial-system): Fixes issues in ruling pdf

libs/clients/payment/src/lib/payment.ts
Advania & Fjársýslan updated their services, changing the path.
=> fix(application-system-api): Updated FJS path

apps/services/auth-public-api/src/app/modules/delegations/delegations.controller.ts
=> feat(auth-public-api): fix null pointer exception

charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml, infra/src/uber-charts/islandis.ts, libs/api/domains/endorsement-system/src/lib/endorsementSystem.resolver.ts, libs/application/templates/party-application/src/fields/BulkUpload/index.tsx, libs/application/templates/party-application/src/fields/FileUploadDisclaimer/index.tsx, libs/application/templates/party-application/src/graphql/mutations.ts, libs/application/templates/party-application/src/lib/PartyApplicationTemplate.ts, libs/application/templates/party-application/src/lib/messages.ts, libs/application/templates/party-letter/src/fields/BulkUpload/index.tsx, libs/application/templates/party-letter/src/fields/FileUploadDisclaimer/index.tsx, libs/application/templates/party-letter/src/graphql/mutations.ts, libs/application/templates/party-letter/src/lib/PartyLetterApplicationTemplate.ts, libs/application/templates/party-letter/src/lib/messages.ts
chore: Enable party application systems (#4418)
fix(party-application): Application templates party application/fix bulk upload (#4401)
=> fix(application-templates-party-application): Deployments

scripts/ci/Dockerfile
This closes island-is/infrastructure#805
=> fix: libxml security vulnerability in docker-static

libs/auth-nest-tools/src/lib/auth.middleware.ts
=> fix(auth-public-api): Use isomorphic fetch

libs/application/template-api-modules/src/lib/modules/templates/funding-government-projects/funding-government-projects.service.ts, libs/application/template-api-modules/src/lib/modules/templates/institution-collaboration/institution-collaboration.service.ts
- Fix attachments issues for FUNDING_GOVERNMENT_PROJECTS and INSTITUTION_COLLABORATION
=> fix(samstarf,fjarmognun-rikisverkefni): attachment key

libs/application/template-api-modules/src/lib/modules/templates/funding-government-projects/funding-government-projects.service.ts, libs/application/template-api-modules/src/lib/modules/templates/institution-collaboration/institution-collaboration.service.ts
- cherry pick to release branch
=> fix(samstarf,fjarmognun-rikisverkefni): attachment key (#4434)

workspace.json
- fixing the CI
- fixing secrets checking + allowing the workflow to be manually invoked
- fix(application-templates-party-application): Deployments (#4423)
- opening for access to new services from application-system namespace
- generating values
- fix(samstarf,fjarmognun-rikisverkefni): attachment key (#4434) (#4437)
- trying to fix schema generation errors
=> fix: schema generation

libs/auth-api-lib/src/lib/services/delegations.service.ts
=> fix(public-auth-api): Log last digits in nationalid

libs/application/templates/driving-assessment-approval/src/lib/DrivingAssessmentApprovalTemplate.ts
We want to open this application for live testers. Real people
=> fix(driving-assessment-approval): opening application for production

libs/application/template-api-modules/src/lib/modules/templates/health-insurance/health-insurance.utils.spec.ts, libs/application/template-api-modules/src/lib/modules/templates/health-insurance/health-insurance.utils.ts, libs/application/templates/health-insurance/src/forms/HealthInsuranceForm.ts
* fix(health-insurance): support single digit month and date in Icelandic national registry dates
* Make email and phone number editable
=> fix(health-insurance): support single digit month and date (#4409)

apps/application-system/api/webpack.config.js, libs/application/template-api-modules/src/lib/modules/templates/funding-government-projects/funding-government-projects.service.ts, libs/application/template-api-modules/src/lib/modules/templates/institution-collaboration/institution-collaboration.service.ts, libs/application/templates/institution-collaboration/src/forms/application.ts, libs/file-storage/src/lib/file-storage.service.ts
- cherry pick for release branch
=> fix(file-storage): get key from S3 uri and escape special chars from files (#4459)

apps/services/auth-public-api/src/environments/environment.ts, libs/auth-api-lib/src/lib/services/delegations.service.ts, libs/auth-nest-tools/src/lib/auth.middleware.ts
Bug fixes for token exchange in the delegations endpoint of auth-public-api.
So that it is possible to get a list of available delegations from Þjóðskrá while signed in as someone else.
- [ x] I have performed a self-review of my own code
- [x ] My changes generate no new warnings
- [ x] Formatting passes locally with my changes
- [ x] I have rebased against main before asking for a review
=> fix(auth-public-api): Token exhange fixes

apps/services/party-letter-registry-api/esbuild.json, apps/services/temporary-voter-registry-api/esbuild.json
Seeders are missing some packages to run
=> fix(application-template-party-application): Seeder packages

libs/application/templates/parental-leave/src/dataProviders/Children/Children-utils.spec.ts, libs/application/templates/parental-leave/src/dataProviders/Children/Children-utils.ts, libs/application/templates/parental-leave/src/fields/ChildSelector/index.tsx, libs/application/templates/parental-leave/src/fields/Duration/index.tsx
=> fix(parental-leave): Include fixes for one active application and duration screen

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/constants.ts, libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.ts, libs/application/templates/parental-leave/src/fields/EmployerApprovalExtraInformation/index.tsx, libs/application/templates/parental-leave/src/fields/Review/index.tsx, libs/application/templates/parental-leave/src/lib/parentalLeaveClientUtils.ts
Union is optional, in the case when no union is selected, send the default 'no union selected' (`F000`)
To not get an error when sending an application because it is required in the API
=> chore(parental-leave): Send empty union value to API if no union was selected

apps/application-system/api/infra/application-system-api.ts, apps/services/endorsements/api/src/app/modules/endorsement/endorsement.service.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml, libs/application/templates/party-application/src/graphql/queries.ts, libs/application/templates/party-application/src/hooks/useHasEndorsed.ts, libs/application/templates/party-letter/src/hooks/useHasEndorsed.ts
Users were getting locked out of submitting endorsements.
- Changed submit to email
- Fixed has endorsed check
- Removed unused input variables
=> fix(application-templates-party-application): Endorsement submissions

libs/application/templates/payable-dummy-template/src/lib/PayableDummyTemplate.ts
The payment team needs this deployed for testing the production env
=> chore(payable-dummy-template): enabling payable dummy template prod

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.ts, libs/clients/vmst/src/clientConfig.yaml
=> fix(parental-leave): Send an empty true date of birth (#4524)

nx.json
Consistent schema generation
We do not like surprises especially bad ones.
=> fix: Changing NX cache folder location to avoid being cached with node_modules by default

apps/judicial-system/web/src/routes/Court/InvestigationRequest/Overview/OverviewForm.tsx, apps/judicial-system/web/src/routes/Court/RestrictionRequest/Overview/Overview.tsx, apps/judicial-system/web/src/routes/Court/RestrictionRequest/Overview/OverviewForm.tsx, apps/judicial-system/web/src/routes/Court/SharedComponents/CourtCaseNumber/CourtCaseNumber.tsx
https://app.asana.com/0/1199153462262248/1200582953169120
Add loading indicator to createCourtCase button while we are creating a court case number
This is a regression.
=> fix(judicial-system): Add loading indicator to createCourtCase button

libs/application/template-api-modules/src/lib/modules/templates/children-residence-change/utils.spec.ts, libs/application/template-api-modules/src/lib/modules/templates/children-residence-change/utils.ts
=> fix(crc): Change email address values (#4537)

apps/financial-aid/api/src/app/modules/auth/auth.controller.ts, apps/financial-aid/api/src/app/modules/auth/auth.service.ts, apps/financial-aid/api/src/app/modules/user/user.model.ts, apps/financial-aid/api/src/environments/environment.ts, apps/financial-aid/web-osk/pages/index.tsx, apps/financial-aid/web-veita/src/routes/Login/login.tsx, libs/financial-aid/shared/src/lib/types.ts
https://app.asana.com/0/1200526945324403/1200368932625373
=> feat(financial-aid): Veita user support

libs/application/templates/accident-notification/src/dataProviders/index.ts, libs/application/templates/accident-notification/src/forms/InformationAndDataProviderForm.ts, libs/application/templates/accident-notification/src/index.ts, libs/application/templates/accident-notification/src/lib/AccidentNotificationTemplate.ts, libs/application/templates/accident-notification/src/lib/messages/externalData.ts, libs/application/templates/accident-notification/src/lib/messages/index.ts, libs/application/templates/accident-notification/src/types/index.ts
https://app.clickup.com/t/nz7p1e
Added data provider screen
Needed for the application
=> feat(an): Data provider screen

apps/web/components/IcelandicNamesSearcher/data/index.ts, apps/web/hooks/useLinkResolver/useLinkResolver.ts, libs/application/templates/party-application/src/fields/EndorsementDisclaimer/index.tsx, libs/application/templates/party-application/src/lib/messages.ts, libs/service-portal/endorsements/src/lib/messages.ts, libs/service-portal/endorsements/src/screens/Endorsements/Endorsements.tsx
Cherry picked small fixes
* #4397
* #4546
* #4523
* #4547
=> fix: a batch of small hotfixes

libs/application/templates/party-application/src/lib/messages.ts
a tiny text tweak for party-application
=> fix(party-application): small text tweak

libs/application/templates/accident-notification/src/forms/InformationAndDataProviderForm.ts, libs/application/templates/accident-notification/src/lib/dataSchema.ts, libs/application/templates/accident-notification/src/lib/messages/applicantInformation.ts, libs/application/templates/accident-notification/src/lib/messages/error.ts, libs/application/templates/accident-notification/src/lib/messages/hindrances.ts, libs/application/templates/accident-notification/src/lib/messages/index.ts
Applicant information screen added
Needed for the applicant to provide information to sjukra.is
=> feat(an): Applicant information screen added

apps/api/infra/api.ts, apps/api/src/app/app.module.ts, apps/api/src/app/environments/environment.ts, apps/application-system/api/infra/application-system-api.ts, apps/application-system/api/src/environments/environment.ts, apps/web/components/Webreader/Webreader.tsx, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml, libs/clients/driving-license/README.md, libs/clients/driving-license/src/clientConfig.json, libs/clients/driving-license/src/lib/drivingLicense.module.ts
WebReader instability causing white outs.
Driving license endpoints must be updated.
From:
* #4553 
* #4556
=> fix: Hotfix for driving license endpoints and webreader

libs/application/template-api-modules/src/lib/modules/shared/shared.service.ts, libs/application/template-api-modules/src/lib/modules/shared/shared.utils.ts, libs/application/template-api-modules/src/lib/modules/templates/document-provider-onboarding/document-provider-onboarding.service.ts, libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts, libs/application/template-api-modules/src/lib/modules/templates/party-application/party-application.service.ts, libs/application/template-api-modules/src/lib/modules/templates/party-letter/party-letter.service.ts, package.json
- Configure the assignEmail expiry by application
=> fix(application-system): configure expiry by application for the assignEmail token

libs/application/template-api-modules/src/lib/modules/shared/shared.service.ts, libs/application/template-api-modules/src/lib/modules/shared/shared.utils.ts, libs/application/template-api-modules/src/lib/modules/templates/document-provider-onboarding/document-provider-onboarding.service.ts, libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts, libs/application/template-api-modules/src/lib/modules/templates/party-application/party-application.service.ts, libs/application/template-api-modules/src/lib/modules/templates/party-letter/party-letter.service.ts, package.json
- Cherry pick https://github.com/island-is/island.is/pull/4560
=> fix(application-system): configure expiry by application for the assignEmail token (#4560)

apps/service-portal/src/components/MobileMenu/MobileMenu.tsx, apps/service-portal/src/components/Sidebar/ModuleNavigation.tsx, apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.service.ts, libs/application/templates/party-application/src/lib/messages.ts, libs/service-portal/endorsements/src/lib/messages.ts, libs/service-portal/endorsements/src/screens/Endorsements/Endorsements.tsx, package.json, yarn.lock
#4576 
#4557 
The ability to de-register recommendations
=> fix: Application system tweaks and text fixes

apps/service-portal/src/components/Sidebar/Sidebar.tsx, libs/service-portal/endorsements/src/lib/messages.ts, libs/service-portal/endorsements/src/screens/Endorsements/Endorsements.tsx
Invalid lists not being filtered out on my-pages
=> fix: a few hotfixes for minar sidur endorsements

libs/service-portal/endorsements/src/lib/messages.ts, libs/service-portal/endorsements/src/screens/Endorsements/Endorsements.tsx
* splitting up endorsement lists by list tag
* tag label for signed lists
Co-authored-by: kksteini <77672665+kksteini@users.noreply.github.com>
=> fix(service-portal): splitting up endorsement lists by list tag

package.json, yarn.lock
=> fix: 08-05-2021 yarn audit

SUMMARY.md, apps/financial-aid/README.md
Readme for financial aid system.
=> feat(rb): Readme

apps/financial-aid/api/src/app/modules/auth/auth.controller.ts, apps/financial-aid/api/src/app/modules/auth/auth.module.ts, apps/financial-aid/api/src/environments/environment.ts
https://app.asana.com/0/inbox/1108390964729019/1200599419152080/1200817396359053
=> fix(financial-aid): Fixed an issue with the veita login

yarn.lock
Running `yarn` on main results in a changed yarn.lock file. This is most likely due to someone forgetting to check the file in at some point.
The lock file is not up to date on main
=> fix(core): Update yarn.lock

libs/api/domains/license-service/src/lib/client/driving-license-client/drivingLicenseService.api.ts
=> fix(license-service): strip dash from SmartSolution nationalId

apps/judicial-system/backend/src/app/formatters/formatters.spec.ts, apps/judicial-system/backend/src/app/formatters/formatters.ts, apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
https://app.asana.com/0/1199153462262248/1200352906978953
☝️ 
For clarity
=> feat(judicial-system): Adds reference to rettarvorslugatt in prosecutor sms

apps/judicial-system/backend/src/app/formatters/requestPdf.ts
https://app.asana.com/0/322488613152836/1200564628078187
Request PDF copy update. Note that this only changes the layout, the actual copy can be changed in Contentful.
Better readability
=> fix(judicial-system): Request PDF copy update

libs/application/template-api-modules/src/lib/modules/templates/children-residence-change/children-residence-change.service.ts, libs/application/templates/family-matters/children-residence-change/src/forms/ChildrenResidenceChangeForm.ts
Hides mocking implementation in crc
=> fix(crc): hides mocking implementation.

apps/judicial-system/web/src/routes/Court/InvestigationRequest/Overview/Overview.tsx, apps/judicial-system/web/src/routes/Court/InvestigationRequest/Overview/OverviewForm.tsx, apps/judicial-system/web/src/routes/Court/RestrictionRequest/Overview/Overview.tsx, apps/judicial-system/web/src/routes/Court/RestrictionRequest/Overview/OverviewForm.tsx, apps/judicial-system/web/src/routes/Court/SharedComponents/CourtCaseNumber/CourtCaseNumber.tsx, apps/judicial-system/web/src/utils/hooks/use-case/useCase.tsx
https://app.asana.com/0/1199153462262248/1200824238764839
☝️ 
Was not working correctly
=> fix(judicial-system): Fixes receive case by court

libs/application/template-api-modules/src/lib/modules/templates/children-residence-change/children-residence-change.service.ts, libs/application/templates/family-matters/children-residence-change/src/forms/ChildrenResidenceChangeForm.ts
This reverts commit a26a4dfdba7ea3f6ea0676bc77ddd5e2fef36e03.
=> fix(crc): Hides mocking implementation

apps/judicial-system/backend/src/app/formatters/formatters.spec.ts, apps/judicial-system/backend/src/app/formatters/formatters.ts, apps/judicial-system/backend/src/app/modules/notification/notification.service.ts, apps/judicial-system/web/src/routes/Court/InvestigationRequest/CourtRecord/CourtRecord.tsx, apps/judicial-system/web/src/routes/Court/InvestigationRequest/HearingArrangements/HearingArrangements.tsx, apps/judicial-system/web/src/routes/Court/InvestigationRequest/HearingArrangements/HearingArrangementsForm.tsx, apps/judicial-system/web/src/routes/Court/RestrictionRequest/CourtRecord/CourtRecord.tsx, apps/judicial-system/web/src/routes/Court/RestrictionRequest/HearingArrangements/HearingArrangements.tsx
https://app.asana.com/0/1199153462262248/1200747911475686
https://app.asana.com/0/1199153462262248/1200824369419382
☝️ Various fixes
Notifications were broken
=> fix(judicial-system): Fixes issues with court date notifications

apps/judicial-system/api/infra/judicial-system-api.ts, charts/judicial-system/values.staging.yaml
=> feat(judicial-system): Unhide Investigation Cases on Staging

apps/application-system/api/infra/application-system-api.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml
This is a cherry-pick from main
=> feat(application-system-api): add internal ingress for api from x-road

apps/services/endorsements/api/infra/endorsement-system-api.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml
=> fix(endorsement-api): fixing TLS issue with SOFFIA endpoint

libs/content-search-toolkit/src/services/elastic.service.ts
Merges fix in: 27acbe34cba0562a91b6547b4ff60d8145063fec
=> fix(service-search-indexer): Services search indexer chunk size

apps/services/endorsements/api/infra/endorsement-system-api.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml
=> fix(endorsement-api): fixing TLS issue with SOFFIA endpoint (#4744)

libs/application/templates/driving-assessment-approval/src/fields/StudentLookupField.tsx
Cherry-picking #4783 into the release
=> fix(application-template-driving-assessment): fixing an undefined value

apps/judicial-system/backend/src/app/formatters/requestPdf.ts
https://app.asana.com/0/1199153462262248/1200844715490175
Use a heading from Contentful instead of a hardcoded one
=> fix(judicial-system): Request PDF

libs/application/templates/parental-leave/src/config.ts
☝️ 
To match the minimum period length
=> chore(parental-leave): Change minimum months from 1 to 0.5

apps/judicial-system/web-e2e/cypress.json, apps/judicial-system/web-e2e/src/integration/Prosecutor/stepTwo.spec.ts, package.json, yarn.lock
=> fix: Upgrades tar because of security vulnerability

apps/judicial-system/backend/src/app/formatters/formatters.spec.ts, apps/judicial-system/backend/src/app/formatters/formatters.ts, apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
https://app.asana.com/0/1199153462262248/1200879524950241
Fixes for ☝️ 
Bug
=> fix(judicial-system): Removes duplicate conclusion from prison ruling email

apps/judicial-system/backend/src/app/modules/case/case.service.ts
https://app.asana.com/0/1199153462262248/1200214145052862
Fix fyrir ☝️ 
Bug
=> fix(judicial-system): Fixes case files overview upload

apps/financial-aid/web-osk/babel.config.json, apps/financial-aid/web-veita/babel.config.json
Adds babel config for import for fa-clients
=> fix(fa): babel conf

apps/financial-aid/web-osk/babel.config.json, apps/financial-aid/web-veita/babel.config.json
Removes babel confs to fix prod
=> fix(fa): Removes babel configs

.github/workflows/pullrequest.yml, apps/application-system/api/infra/application-system-api.ts, apps/application-system/api/src/environments/environment.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml, libs/application/templates/driving-assessment-approval/src/lib/DrivingAssessmentApprovalTemplate.ts
Cherry-picking from main (fix for assessment/dl submission)
Also cherry picking an npm-audit disabling commit from petar so the build can complete
=> fix(driving-license-assessment-submission): fixing missing env vars and error checking

apps/judicial-system/backend/migrations/20210902135522-update-case.js, apps/judicial-system/web/messages/Core/laws.ts, apps/judicial-system/web/src/utils/laws.ts, libs/judicial-system/formatters/src/lib/formatters.ts, libs/judicial-system/types/src/lib/case.ts
https://app.asana.com/0/1199153462262248/1200860710789579
Add case custody provisions to custody restriction cases
A prosecutor commented that this is needed.
=> feat(judicial-system): Add case custody provisions

apps/financial-aid/api/src/environments/environment.ts
Fixes wrong env name for financial aid
=> fix(fa): Env name

libs/clients/driving-license/src/clientConfig.json, libs/clients/driving-license/src/lib/drivingLicense.module.ts
FYI this is a cherry pick of a change going into master.
FYI FYI: This is really horrible, and I need to study the openapi-generator in much greater detail before I figure out how to address this better.
=> fix(clients-driving-license): fixing injected content type by rearranging stuff in the client config

apps/application-system/api/src/app/modules/application/application.controller.ts, libs/application/core/src/lib/messages.ts, libs/application/templates/parental-leave/src/config.ts, libs/application/templates/parental-leave/src/fields/InReviewSteps/index.tsx, libs/application/templates/parental-leave/src/forms/EmployerApproval.ts, libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts, libs/application/templates/parental-leave/src/lib/messages.ts, libs/application/ui-components/src/components/ReviewGroup/ReviewGroup.tsx
- Be able to edit application when waiting for assignment
- Minimum months from 1 to 0.5
- Improve application assignment
- Update employer reject button text and type
=> chore(parental-leave): Include improvements to flow

libs/application/templates/driving-license/src/lib/messages.ts
Keys were all out of date and some of them wrong for the extract strings command. This should address the issue
=> fix(application-templates-driving-license): update string keys in contentful

apps/services/temporary-voter-registry-api/infra/temporary-voter-registry-api.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml
=> fix(endorsement-system): Fixing cross-namespace invocation to temp_voter_registry service

apps/services/endorsements/api/infra/endorsement-system-scripts-update-metadata.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml
=> fix(endorsement-system): Limiting maximum SOFFIA api calls when updating metadata

apps/financial-aid/web-osk/src/components/Files/Files.tsx, apps/financial-aid/web-osk/src/routes/application/IncomeFilesForm/incomeFilesForm.tsx, apps/financial-aid/web-osk/src/routes/application/TaxReturnForm/taxReturnForm.tsx, apps/financial-aid/web-osk/src/routes/status/FileUpload/fileUpload.tsx, libs/financial-aid/shared/src/lib/types.ts
https://app.asana.com/0/1200897217304888/1200749559259981
Fixing the text on incomefiles, realized we using two ways to upload files and decided to join them togeth
Better ux, more reusable code
=> fix(fa): Reuses files component

libs/application/templates/party-application/src/fields/SupremeCourtOverview/index.tsx, libs/application/templates/party-application/src/lib/PartyApplicationTemplate.ts
(cherry picked from commit 26133569fccd3e0eca4b5be90341332cb0146a51)
=> fix(application-templates-party-application): Fix admin overview

libs/application/templates/party-application/src/fields/SupremeCourtOverview/index.tsx
- Added handler for empty voter registry entry
=> fix(application-templates-party-application): Empty handler

libs/application/templates/party-application/src/fields/SupremeCourtOverview/index.tsx
(cherry picked from commit 765c28f6c83402a8c10687a3600909534c5f6e63)
=> fix(application-templates-party-application): Empty handler (#4912)

apps/services/endorsements/api/src/app/modules/endorsementValidator/validators/minAgeByDate/minAgeByDateValidator.service.ts
(cherry picked from commit 3972cfbdee21b9bc7b2f055b144c30e37310983f)
=> fix(services-endorsements-api): Fix age check

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.spec.ts, libs/application/templates/parental-leave/src/forms/EmployerApproval.ts, libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts, libs/application/templates/parental-leave/src/lib/dataSchema.ts, libs/application/templates/parental-leave/src/lib/messages.ts, libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Cherry picking [bdab889](https://github.com/island-is/island.is/commit/bdab88975ed864607e6e88d0a016628c3c016159)
=> chore(parental-leave): Require employer reviewer to insert company national registry id

libs/application/templates/driving-license/src/fields/EligibilitySummary/EligibilitySummary.tsx, libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts
=> feat(application-templates-driving-license): blocking form progress based on requirements

libs/application/templates/party-application/src/fields/SupremeCourtOverview/index.tsx
Currently admins see all submitted endorsements, they should only see chosen endorsements
=> feat(application-templates-party-application): Filter endorsements

libs/application/templates/party-application/src/fields/EndorsementListSubmission/index.tsx, libs/application/templates/party-application/src/fields/SupremeCourtOverview/index.tsx, libs/application/templates/party-application/src/lib/PartyApplicationTemplate.ts
Merges:
d06718592c70df7c76e80c2f146f82bb2e7135de
97e962d6fcca69334bdac15588c8897b53c52329
=> fix(application-templates-party-application): Party application endorsements

apps/financial-aid/web-osk/src/routes/application/AboutForm/aboutForm.tsx, libs/financial-aid/shared/src/lib/const.ts, libs/financial-aid/shared/src/lib/formatters.ts, libs/financial-aid/shared/src/lib/utils.ts
https://app.asana.com/0/1200897217304888/1200940081799649
Creates util function for getting current month.
Displays current month on aboutForm page.
Moves stuff from formatters to utils/conts.
More explicit ui
=> feat(fa): Adds current month to aboutForm

libs/application/templates/party-application/src/fields/EndorsementDisclaimer/index.tsx, libs/application/templates/party-application/src/lib/messages.ts, libs/application/templates/party-letter/src/lib/messages.ts
=> fix(party-application): toast message on endorse and reject button message

apps/services/endorsements/api/infra/endorsement-system-scripts-update-metadata.ts, apps/services/endorsements/api/migrations/20210909175011-arnorhs.js, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml, libs/application/templates/party-application/src/fields/EndorsementDisclaimer/index.tsx, libs/application/templates/party-application/src/lib/messages.ts, libs/application/templates/party-letter/src/lib/messages.ts
- preventing the cron job from updating national registry info every time you run on endorsement list.
- reducing the number of times per day that the meta data is updated for each endorsement.
- some UI related changes in the party application
=> fix(endorsement-system): cherry picks from main

apps/services/endorsements/api/migrations/20210909174012-remove-endorsement-duplicates.js
Now deletes problematic ids on completion. Also removed test ids.
=> fix(endorsement-system): Amended the endorsement system deduplication migration

apps/services/endorsements/api/migrations/20210909174012-remove-endorsement-duplicates.js
Cherry pick of #4941 
and #4946
=> fix(endorsement-system): Hotfix/remove endorsement duplicates

libs/application/data-providers/src/providers/NationalRegistryProvider.ts
Cherry picking from main - fix for national provider
=> fix(application-system-shared-service): cherry-pick national provider fix

.github/workflows/push.yml
=> fix(cd): Image tags can't exceed 63 characters

apps/web/screens/Organization/Syslumenn/Auctions.tsx
Fix tablet and mobile layout for auctions overview
Before:
After:
=> fix(web): Syslumenn auctions responsive

apps/financial-aid/web-veita/src/components/FilesListWithHeader/FilesListWithHeader.tsx
https://app.asana.com/0/1200897217304888/1200908596880392
Checks if files are existing before rendering component
Less clutter
=> fix(fa): Rendering filelist

apps/financial-aid/web-osk/src/utils/useFileUpload.ts
https://app.asana.com/0/1200897217304888/1200951215441482
Encode filename before uploading to s3
We get an error if we don't and upload files with icelandic characters
=> fix(fa): Encodes filename

libs/api/domains/education/src/lib/education.service.ts
Cherry picking this super urgent change from the release branch into main.
preventing siblings from being able to see each others' grades (#4888)
=> chore(service-portal-education): cherry picking privacy fix from release/11.0.0

apps/judicial-system/web/messages/InvestigationCases/Court/hearingArrangements.ts, apps/judicial-system/web/src/routes/Court/InvestigationRequest/CourtRecord/CourtRecord.tsx, apps/judicial-system/web/src/routes/Court/InvestigationRequest/HearingArrangements/HearingArrangementsForm.tsx
https://app.asana.com/0/1199153462262248/1200879524950219
Fixes three things
1. In a remote session, we were not booking that the accused would not attend the hearing in courtAttendees.
2. We decided to add text to the court date popup.
3. The text in the court date popup was not properly set up in CF.
=> fix(judicial-system): Session arrangements iteration fixes

apps/web/components/Project/Header/ElectionProjectHeader.treat.ts, apps/web/components/Project/Header/ElectionProjectHeader.tsx, apps/web/components/Project/index.ts, apps/web/screens/Project/Project.tsx
Add new election theme to project page
Will be used on special page with stepper about "covid election"
=> feat(web): Election project header

libs/application/templates/parental-leave/src/lib/dataSchema.ts
=> fix(parental-leave): Remove person check when validating national id of employer

libs/api/domains/driving-license/src/lib/drivingLicense.service.ts, libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/emailGenerators/drivingAssessmentApproval.ts
=> fix(application-templates-driving-assessment-approval): updating the email text, along with how we find a student's name

libs/api/domains/driving-license/src/lib/drivingLicense.service.ts, libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/emailGenerators/drivingAssessmentApproval.ts, libs/application/templates/driving-license/src/fields/EligibilitySummary/EligibilitySummary.tsx, libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts
=> fix(driving-license): block application on invalids, text changes in assessment, and different student fetching

libs/application/templates/public-debt-payment-plan/src/lib/PublicDebtPaymentPlanTemplate.ts
https://app.clickup.com/t/1e0ykfb
Adding an hour to lifecycle.
Application is not suppose to live longer than an hour because it contains information that can change.
=> feat(pdpp): adding an hour expiration to lifecycle

apps/judicial-system/api/infra/judicial-system-api.ts, charts/judicial-system/values.prod.yaml
=> feat(judicial-system): Unhides investigation cases on prod

apps/judicial-system/backend/migrations/20210915100238-update-case.js
=> fix(judicial-system): Fixes provisions migration

libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
=> fix(api-domains-driving-license): readding quality photo flag

libs/application/templates/driving-license/src/fields/ExamplePaymentPendingField.tsx, libs/application/templates/driving-license/src/forms/payment.tsx
auto submit drivers license application after payment confirmed. Move straight from waiting screen after payment to done screen without interaction.
=> fix(application-system): auto submit drivers license application after payment confirmed

libs/api/domains/license-service/src/lib/client/driving-license-client/drivingLicenseService.api.ts, libs/api/domains/license-service/src/lib/licenseService.module.ts, libs/api/domains/license-service/src/lib/licenseService.service.ts
=> fix: missed EXPIRED_ON to TTL; explicitly pass cacheManager from all

charts/air-discount-scheme/values.dev.yaml, charts/air-discount-scheme/values.prod.yaml, charts/air-discount-scheme/values.staging.yaml, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml, charts/judicial-system/values.dev.yaml, charts/judicial-system/values.prod.yaml, charts/judicial-system/values.staging.yaml, infra/src/dsl/serialize-to-yaml.ts, package.json, yarn.lock
Since some developers get quotes when generating chart values,
force quotes on everything for consistency.
=> fix(ci): Force quotes in yaml

charts/air-discount-scheme/values.dev.yaml, charts/air-discount-scheme/values.prod.yaml, charts/air-discount-scheme/values.staging.yaml, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml, charts/judicial-system/values.dev.yaml, charts/judicial-system/values.prod.yaml, charts/judicial-system/values.staging.yaml, infra/src/dsl/serialize-to-yaml.ts, package.json, yarn.lock
Reverts island-is/island.is#4973
=> fix: Revert "fix(ci): Force quotes in yaml"

apps/judicial-system/backend/migrations/20210920091715-update-institution.js, apps/judicial-system/backend/test/e2e.spec.ts
https://app.asana.com/0/1199153462262248/1200943860729010
☝️ 
New prosecutors office being onboarded.
=> feat(judicial-system): Adds a new prosecutors office

libs/api/domains/driving-license/jest.config.js, libs/api/domains/driving-license/src/lib/__mock-data__/drivingAssessment.json, libs/api/domains/driving-license/src/lib/__mock-data__/expiredLicense.json, libs/api/domains/driving-license/src/lib/__mock-data__/finishedSchool.json, libs/api/domains/driving-license/src/lib/__mock-data__/juristictions.json, libs/api/domains/driving-license/src/lib/__mock-data__/notFinishedSchool.json, libs/api/domains/driving-license/src/lib/__mock-data__/requestHandlers.ts, libs/api/domains/driving-license/src/lib/__mock-data__/validLicense.json, libs/api/domains/driving-license/src/lib/drivingLicense.service.ts, libs/api/domains/driving-license/src/lib/drivingLicense.spec.ts, libs/api/domains/driving-license/tsconfig.json
=> feat(api-domains-driving-license): adding tests for driving license service

libs/application/templates/driving-license/jest.config.js, libs/application/templates/driving-license/src/dataProviders/EligibilityProvider.ts, libs/application/templates/driving-license/src/forms/done.ts, libs/application/templates/driving-license/src/forms/payment.tsx, libs/application/templates/driving-license/src/forms/paymentPending.ts, libs/application/templates/driving-license/src/lib/constants.ts, libs/application/templates/driving-license/src/lib/dataSchema.ts, libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.spec.ts, libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts, libs/application/templates/driving-license/src/lib/messages.ts, libs/application/templates/driving-license/src/utils.ts
=> feat(application-templates-driving-license): adding a very basic state transition test

libs/api/domains/auth/src/lib/auth.service.ts, libs/api/domains/auth/src/lib/resolvers/delegation.resolver.ts, libs/auth-api-lib/src/lib/services/delegations.service.ts
* Fixes a filter that removed all delegations.
* Checks that delegations are not created to self.
* Fix scope argument in createAuthDelegation mutation.
So delegations work better.
=> fix(auth): Fix delegation filter

workspace.json
Fix production build for services-auth-api
So everything builds :)
=> chore(build): fix production build for services-auth-api

libs/api/domains/license-service/src/lib/client/driving-license-client/pkpass.client.ts
=> fix(license-service): boundary check off-by-one

apps/financial-aid/web-veita/src/components/ApplicationsTable/ApplicationsTable.tsx
=> fix(fa): unique table index

libs/application/templates/accident-notification/src/forms/InReview.ts, libs/application/templates/accident-notification/src/lib/messages/inReview.ts
https://app.clickup.com/t/1f36kkv
* Remove sidebar nav
* Change title to "Staða tilkynningar"
* Change sidebar title
=> feat(an): changes to titles and removing sidebar

.github/workflows/push.yml, libs/infra-tracing/src/lib/datadog-tracer.ts
Cherry-picking a fix from `main` that needs to go to prod ASAP.
=> fix(infrastructure): Removing PII info from URLs when sending to DataDog (#5083)

apps/judicial-system/backend/src/app/formatters/rulingPdf.ts, apps/judicial-system/backend/src/app/messages/rulingPdf.ts
https://app.asana.com/0/1199153462262248/1200879471149033
Fixes to ☝️ 
Bug fixes
=> fix(judicial-system): Fixes ruling pdf issues

libs/application/template-api-modules/src/lib/modules/template-api.service.ts, libs/application/template-api-modules/src/lib/modules/templates/index.ts, libs/application/template-api-modules/src/lib/modules/templates/public-debt-payment-plan/public-debt-payment-plan.module.ts, libs/application/template-api-modules/src/lib/modules/templates/public-debt-payment-plan/public-debt-payment-plan.service.ts, libs/application/templates/public-debt-payment-plan/src/lib/PublicDebtPaymentPlanTemplate.ts
https://app.clickup.com/t/j59hby
Add a template api so we can post application to TBR backsystem
We need this to eventually post the application to TBR 
=> feat(pdpp): Add template api to Public debt payment plan

apps/judicial-system/web/src/utils/hooks/useCourtUpload.ts
https://app.asana.com/0/1199153462262248/1200905978520084/f
Fix to ☝️ 
Bug
=> fix(judicial-system): Fixes issues with file upload to court

.github/workflows/push.yml
Supports island-is/infrastructure#868
=> fix(cd): Retag helm config latest

apps/judicial-system/backend/src/app/formatters/rulingPdf.ts, apps/judicial-system/web/src/routes/Court/InvestigationRequest/CourtRecord/CourtRecordForm.tsx, apps/judicial-system/web/src/routes/Court/RestrictionRequest/CourtRecord/CourtRecord.tsx
https://app.asana.com/0/1199153462262248/1200978846073179/f
Move isClosedCourtHidden fields
Better UX
=> fix(judicial-system): Move isClosedCourtHidden fields

apps/judicial-system/web/messages/Core/caseFiles.ts, apps/judicial-system/web/src/shared-components/CaseFileList/CaseFileList.spec.tsx, apps/judicial-system/web/src/shared-components/CaseFileList/CaseFileList.tsx
Put "file not found" modal text in CF
=> chore(judicial-system): Put "file not found" modal text in CF

apps/judicial-system/backend/src/app/modules/case/filters/case.filters.spec.ts, apps/judicial-system/backend/src/app/modules/case/filters/case.filters.ts
https://app.asana.com/0/1199153462262248/1200978846073271
☝️ 
Feature
=> feat(judicial-system): Hides old completed cases

libs/application/templates/accident-notification/src/forms/AccidentNotificationForm/aboutTheAccidentSection.ts, libs/application/templates/accident-notification/src/lib/messages/fatalAccident.ts
https://app.clickup.com/t/1f3cx8z
Moved section and updated conditional rendering logic.
Design changed.
=> feat(an): Updated fatalAccident section

libs/application/templates/accident-notification/src/fields/FormOverview/index.tsx, libs/application/templates/accident-notification/src/forms/AccidentNotificationForm/applicantInformationSection.ts, libs/application/templates/accident-notification/src/forms/AccidentNotificationForm/externalDataSection.ts, libs/application/templates/accident-notification/src/lib/dataSchema.ts, libs/application/templates/accident-notification/src/lib/messages/accidentLocation.ts, libs/application/templates/accident-notification/src/lib/messages/attachments.ts, libs/application/templates/accident-notification/src/lib/messages/hindrances.ts, libs/application/templates/accident-notification/src/lib/messages/overview.ts
https://app.clickup.com/t/1f3etru
https://app.clickup.com/t/1f3deq4
https://app.clickup.com/t/1f36wy4
https://app.clickup.com/t/1f36v7f
https://app.clickup.com/t/1f36u9g
https://app.clickup.com/t/1f36trg
https://app.clickup.com/t/1f90fdr
- Added additional data in overview section
- Updated localisation default message
- Overview page was not rendering all information
- Default messages changed.
=> feat(an): UI update

libs/application/templates/accident-notification/src/forms/AccidentNotificationForm/aboutTheAccidentSection.ts, libs/application/templates/accident-notification/src/lib/messages/accidentType.ts, libs/application/templates/accident-notification/src/lib/messages/attachments.ts, libs/application/templates/accident-notification/src/lib/messages/fishingLocationAndPurpose.ts, libs/application/templates/accident-notification/src/lib/messages/hindrances.ts, libs/application/templates/accident-notification/src/lib/messages/locationAndPurpose.ts
- Updated default localisation strings
- Minor ui update 
Requested by PO
=> feat(An): Text update + minor ui fixes

.github/actions/package.json, .github/actions/yarn.lock, infra/package.json, infra/yarn.lock
Dependabot is giving us these warnings.
=> fix(ci): Upgrading what seems to be some vulnerable dependencies

libs/service-portal/finance/src/screens/FinanceTransactions/FinanceTransactions.tsx
Add translation string for transaction dropdown
Fix initial state for transactions
=> fix(service-portal): transactions finance screen

libs/api/domains/national-registry-x-road/src/lib/nationalRegistryXRoad.resolver.ts, libs/api/domains/national-registry-x-road/src/lib/nationalRegistryXRoad.service.ts, libs/api/domains/national-registry-x-road/src/models/nationalRegistryAddress.model.ts, libs/api/domains/national-registry-x-road/src/models/nationalRegistryPerson.model.ts, libs/api/domains/national-registry-x-road/src/models/nationalRegistryResidence.model.ts
A feature for extracting a person's country of residency according to thjodskra - will be used to evaluate whether or not they have spent more than 185 days as a resident in the country for the driver's license application.
=> feat(api-domains-national-registry-x-road): buseta check

apps/judicial-system/web/src/utils/utils.spec.tsx, apps/judicial-system/web/src/utils/validate.ts
https://app.asana.com/0/1199153462262248/1201066148695404
☝️ 
National id validation was too strict.
=> chore(judicial-system): Less strict national id validation

apps/judicial-system/backend/src/app/modules/notification/notification.service.ts, apps/judicial-system/web/src/shared-components/SigningModal/SigningModal.tsx
https://app.asana.com/0/1199153462262248/1200921234108152
Fixes to ☝️ 
Bug fix
=> fix(judicial-system): Fixes duplicate ruling notifications issue and modifies subject in prison admin email

apps/financial-aid/web-osk/pages/_app.tsx, apps/financial-aid/web-osk/src/components/AppLayout/AppLayout.tsx
=> fix(financial-aid): moving header to layout

apps/judicial-system/web/src/routes/Shared/Requests/Requests.tsx, apps/judicial-system/web/src/shared-components/FeatureProvider/FeatureProvider.tsx, libs/judicial-system/types/src/lib/feature.ts
https://app.asana.com/0/1199153462262248/1201104220353316/f
Remove R-Cases feature flag
Housekeeping
=> chore(judicial-system): Remove R-Cases feature flag

libs/application/templates/public-debt-payment-plan/src/forms/PaymentPlanForm.ts, libs/application/templates/public-debt-payment-plan/src/lib/messages/externalData.ts
https://app.clickup.com/t/1e0y38t
Update-ing text in data provider according to design
=> fix(pdpp): data provider text update

libs/application/templates/public-debt-payment-plan/src/fields/DisposableIncome/DisposableIncome.tsx, libs/application/templates/public-debt-payment-plan/src/lib/messages/employer.ts
https://app.clickup.com/t/1fmjd2a
Added alert message into disposable income screen
=> feat(pdpp): alert message in disposable income

apps/air-discount-scheme/backend/src/app/modules/nationalRegistry/nationalRegistry.service.ts
Eagle Air needs their developers to have test codes.
=> chore(air-discount-scheme): Added an Eagle Air developer as a test user to Loftbrú

apps/web/components/ServiceWeb/Forms/SyslumennForms/SyslumennForms.tsx, apps/web/screens/ServiceWeb/ContactBanner/ContactBanner.tsx, apps/web/screens/ServiceWeb/Home/Home.tsx, apps/web/screens/ServiceWeb/SubPage/SubPage.tsx, apps/web/screens/ServiceWeb/utils/getSlugPart.spec.ts, apps/web/screens/ServiceWeb/utils/getSlugPart.ts, apps/web/screens/ServiceWeb/utils/index.ts, libs/api/domains/communications/src/lib/emailTemplates/syslumennForms.ts
- Update ids for support categories
- Make function to pick out institution slug for contact banner
=> chore(web/thjonustuvefur): minor changes

apps/judicial-system/api/src/app/modules/case/interceptors/case.mask.spec.ts, apps/judicial-system/api/src/app/modules/case/interceptors/case.mask.ts, apps/judicial-system/backend/src/app/modules/case/filters/case.filters.spec.ts, apps/judicial-system/backend/src/app/modules/case/filters/case.filters.ts
https://app.asana.com/0/1199153462262248/1200998113077362
https://app.asana.com/0/1199153462262248/1201165655655810/f
Fixes to ☝️ 
=> fix(judicial-system): Fixes court access to investigation case masking and heightened security

apps/judicial-system/web/src/routes/Admin/UserForm/UserForm.tsx
https://app.asana.com/0/1199153462262248/1201126794460967/f
=> chore(judicial-system): Prison institutions job titles

apps/financial-aid/web-osk/src/components/FileUploadContainer/FileUploadContainer.tsx, apps/financial-aid/web-osk/src/components/Files/Files.tsx, apps/financial-aid/web-osk/src/routes/status/FileUpload/fileUpload.tsx
https://app.asana.com/0/1201097099198335/1201060299207177
Shows error message in correct place for data upload in status page
Better and more expected ux
=> fix(fa): Shows error msg in data upload in correct place

.github/CODEOWNERS, apps/financial-aid/web-osk/src/routes/application/IncomeFilesForm/incomeFilesForm.tsx, apps/financial-aid/web-osk/src/routes/application/IncomeForm/incomeForm.tsx, apps/financial-aid/web-osk/src/routes/application/Info/info.tsx
https://app.asana.com/0/1201097099198335/1201038910099147
Changes to relevant time period
=> fix(fa): Extends time period

apps/financial-aid/web-osk/src/components/Status/InProgress.tsx, apps/financial-aid/web-osk/src/routes/application/Confirmation/confirmation.tsx
https://app.asana.com/0/1201097099198335/1201038910099149
=> fix(fa): Copy changes

README.md
Add recommendation for windows users to use Docker and WSL2 setup for development.
To help Windows users with better DX.
=> docs(core): Adding info in prerequisites for windows users

libs/financial-aid/shared/src/lib/const.ts
Changing base api, to have financial-aid unique
=> fix(fa): Changing base api

apps/judicial-system/backend/src/app/modules/file/file.service.ts
https://app.asana.com/0/1199153462262248/1201208777883934
☝️ 
As we need to keep files in memory while transferring them to court, we cannot handle many such requests simultaniously.
=> fix(judicial-system): Throttle file uploads to court

apps/judicial-system/backend/src/app/formatters/formatters.spec.ts, apps/judicial-system/backend/src/app/formatters/formatters.ts, apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
https://app.asana.com/0/1199153462262248/1201174729701932/f
Simplify ruling emails that is sent to prisons and prosecutors
All the info in the body of the email is already stated in the email's attachment.
=> chore(judicial-system): Simplify ruling emails that is sent to prisons and prosecutors

apps/judicial-system/api/src/app/modules/case/case.resolver.ts, apps/judicial-system/backend/src/app/modules/file/file.controller.ts, apps/judicial-system/backend/src/app/modules/notification/notification.controller.ts, apps/judicial-system/web/src/routes/Court/RestrictionRequest/HearingArrangements/HearingArrangements.tsx, apps/judicial-system/web/src/routes/Shared/Requests/Requests.tsx, apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.spec.tsx, apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverviewForm.tsx, apps/judicial-system/web/src/shared-components/AccordionItems/CourtRecordAccordionItem/CourtRecordAccordionItem.tsx, apps/judicial-system/web/src/shared-components/AccordionItems/PoliceRequestAccordionItem/PoliceRequestAccordionItem.tsx, apps/judicial-system/web/src/shared-components/AccordionItems/RulingAccordionItem/RulingAccordionItem.tsx, apps/judicial-system/web/src/shared-components/PageLayout/Sections.ts, apps/judicial-system/web/src/shared-components/PdfButton/PdfButton.tsx, apps/judicial-system/web/src/shared-components/UserProvider/UserProvider.tsx, apps/judicial-system/web/src/utils/constants.ts
https://app.asana.com/0/1199153462262248/1200879471149009/f
Allow prison staff to open accepted cases
=> feat(judicial-system): Allow prison staff to open accepted cases

apps/judicial-system/backend/src/app/modules/case/filters/case.filters.spec.ts, apps/judicial-system/backend/src/app/modules/case/filters/case.filters.ts
https://app.asana.com/0/1199153462262248/1200879471149005
Fix to ☝️ 
Prison should not have access to alternative travel ban.
=> fix(judicial-system): Block alternative travel ban ruling from prison

apps/financial-aid/web-veita/src/components/ApplicationProfile/ApplicationProfile.tsx, apps/financial-aid/web-veita/src/components/Profile/Profile.tsx
☝️ 
https://app.asana.com/0/1201301944561348/1201257203922140
Bug fixing
=> fix(fa): Error state if aid amount is not calculated right

apps/judicial-system/web/messages/Core/selectCourt.ts, apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/HearingArrangements/HearingArrangementsForm.tsx, apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepOne/StepOne.tsx, apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepTwo/StepTwoForm.tsx, apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/SelectCourt/SelectCourt.tsx, apps/judicial-system/web/src/utils/hooks/useInstitution.tsx
https://app.asana.com/0/1199153462262248/1201280144319833/f
Stop setting default court when creating cases
=> chore(judicial-system): Stop setting default court when creating cases

charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml, charts/judicial-system/values.dev.yaml, charts/judicial-system/values.prod.yaml, charts/judicial-system/values.staging.yaml, infra/src/cli/render-urls.ts, infra/src/dsl/feature-values.spec.ts, infra/src/dsl/serialize-to-yaml.ts, infra/src/dsl/types/output-types.ts, infra/src/feature-env.ts
https://github.com/island-is/infrastructure/issues/910
=> feat(cd): Render namespaces in helm chart

libs/application/templates/parental-leave/src/lib/messages.ts
=> fix(parental-leave): Update translation id

apps/api/infra/api.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml, infra/src/dsl/dsl.ts, infra/src/dsl/map-to-values.ts, infra/src/dsl/types/input-types.ts, infra/src/dsl/types/output-types.ts
This closes island-is/infrastructure#923
=> fix(dsl): Add support for files in dsl

libs/application/templates/parental-leave/src/lib/messages.ts
=> fix(parental-leave): Update translation id (#5466)

apps/services/endorsements/api/src/app/modules/endorsement/endorsement.controller.ts, apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.service.ts, apps/services/endorsements/api/src/app/modules/endorsementList/pipes/endorsementListById.pipe.ts, libs/api/domains/endorsement-system/src/lib/endorsementSystem.resolver.ts, libs/api/domains/endorsement-system/src/lib/endorsementSystem.service.ts
- OwnerName was not querying and needed try catch
- Could not get single list if unauthorised, national id now optional
- endorsement scope stopped working due to function missing scope but checking access groups and one resolver function did not use auth  when service layer needed it.
=> fix(endorsement-system-api): Fixing small bugs in endorsement system api

apps/judicial-system/web/messages/Core/signedVerdictOverview.ts
=> fix(judicial-system): Fix conclusion title for signed verdict

libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
=> fix(api-domains-driving-license): using api version 2.0 for applying for a new license

apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
https://app.asana.com/0/1199153462262248/1201312869488023
☝️ 
=> fix(judicial-system): Stops sending custody notices for alternative travel ban

libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification.utils.ts
=> fix(accident-notification): Add subtype for studies

libs/application/templates/accident-notification/src/lib/messages/applicantInformation.ts, libs/application/templates/accident-notification/src/lib/messages/sportsClubInfo.ts
Fixing text translations to make them more general
Different states require more general text
=> chore(accident notification): Fix text translations

libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification-attachments.provider.ts, libs/application/templates/accident-notification/src/forms/AccidentNotificationForm/aboutTheAccidentSection.ts, libs/application/templates/accident-notification/src/forms/InReviewForm/addAttachmentsSection.ts
=> fix(accident-report): File upload and name field fix

libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification.utils.ts
=> fix(accident-notification): Home accident submit fix

apps/judicial-system/web/messages/RestrictionCases/Prosecutor/overview.ts
=> fix(judicial-system): Fix contentful key duplication

apps/web/components/Regulations/Disclaimer.tsx, apps/web/components/Regulations/RegulationChangelog.tsx, apps/web/screens/Regulations/RegulationPage.tsx
=> feat(Regulations/web): Minor tweaks

apps/financial-aid/web-veita/src/components/MunicipalityAdminSettings/MunicipalityAdminSettings.tsx
https://app.asana.com/0/1201301944561348/1201303524769549
Adds bottom margin to municipality settings
=> fix(fa): Municipality settings bottom margin

apps/judicial-system/api/infra/judicial-system-api.ts, charts/judicial-system/values.prod.yaml, charts/judicial-system/values.staging.yaml
https://app.asana.com/0/1199153462262248/1201332587909081/f
☝️ 
New feature
=> chore(judicial-system): Unhides police case files on staging and prod

apps/financial-aid/web-veita/src/components/Profile/EmployeeProfile.tsx, apps/financial-aid/web-veita/src/routes/Employee/employee.tsx
https://app.asana.com/0/1201301944561348/1201338080211635
Adds toaster for updating staff
Fixes import type
Same ux as updating other staff stuff in Veita
=> fix(fa): Adds toast to staff update

apps/judicial-system/web/src/routes/Court/InvestigationRequest/HearingArrangements/HearingArrangementsForm.tsx, apps/judicial-system/web/src/utils/validate.ts
https://app.asana.com/0/1199153462262248/1201337986358686/f
☝️
Session arrangements are required when ruling court hearing arrangements
=> chore(judicial-system): Make session arrangements required in hearing arrangements step in court ruling

apps/judicial-system/web/src/routes/Court/RestrictionRequest/CourtRecord/CourtRecord.tsx, apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepTwo/StepTwoForm.tsx, apps/judicial-system/web/src/utils/validate.ts
https://app.asana.com/0/1199153462262248/1201126794460918/f
Fixes these navigation issues 
- Users could not move from the court record screen unless they refreshed the page
- Users could not move from the requested hearing arrangements screen unless they refreshed the page
- The ruling field was not being validated on the first ruling screen in restriction cases 
These are bugs
=> fix(judicial-system): Fix navigation issues

libs/auth/react/src/lib/Authenticator/Authenticator.spec.tsx, libs/auth/react/src/lib/Authenticator/Authenticator.tsx
Cherry-pick #5498 into the release branch
To fix user session on sign outs.
=> fix(auth): Remove user from session storage when signed out from IDS

libs/infra-nest-server/src/lib/swaggerMiddlewares.ts
Cherry-picking #5558 into release 12.1.0
To fix too many redirect loops in SwaggerUI for `auth-public-api`
=> fix(infra-nest-server): Fix SwaggerUI redirect loop

apps/judicial-system/backend/src/app/modules/notification/notification.service.ts, libs/judicial-system/formatters/src/lib/formatters.spec.ts, libs/judicial-system/formatters/src/lib/formatters.ts
https://app.asana.com/0/1199153462262248/1201325110202007
☝️ 
=> fix(judicial-system): Fixes custody notice with no restrictions

workspace.json
=> fix(services-endorsement-api): add email assets

apps/services/endorsements/api/src/app/modules/endorsement/dto/existsEndorsement.response.ts, apps/services/endorsements/api/src/app/modules/endorsement/e2e/findByAuthEndorsement/findByAuthEndorsement.spec.ts, apps/services/endorsements/api/src/app/modules/endorsement/endorsement.controller.ts, apps/services/endorsements/api/src/app/modules/endorsement/endorsement.service.ts, apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.service.ts, libs/api/domains/endorsement-system/src/lib/dto/existsEndorsement.response.ts, libs/api/domains/endorsement-system/src/lib/endorsementSystem.resolver.ts, libs/application/templates/general-petition/src/graphql/queries.ts, libs/application/templates/general-petition/src/hooks/useHasEndorsed.ts, libs/service-portal/endorsements/src/screens/queries.ts
=> fix(service-endorsement-api): fix 'has endorsed' check

apps/web/components/Regulations/Appendixes.tsx, apps/web/components/Regulations/useRegulationIndexer.ts, apps/web/screens/Regulations/RegulationPage.tsx
Last minute UI fix, based on client-feedback.
[Already merged into main](#5572).
=> fix(Regulations/web): Public launch fixes

apps/judicial-system/web/messages/RestrictionCases/Prosecutor/caseFiles.ts, apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepFive/StepFiveForm.tsx
https://app.asana.com/0/1199153462262248/1201352736538232
☝️ 
=> feat(judicial-system): Adds tooltip for police case file upload

apps/services/endorsements/api/src/app/modules/endorsement/e2e/findByAuthEndorsement/findByAuthEndorsement.spec.ts
Updating tests that where removed in a hotfix for release 12.1.0.
=> fix(service-endorsement-api): Updating tests

apps/financial-aid/backend/esbuild.json
Fixing so migrations using this package run on dev.
=> fix(fa): Adds replace enum to esbuild

libs/application/templates/accident-notification/src/lib/dataSchema.ts
Added AgricultureAccidentLocationEnum option to dataschema.
The option was missing, but should be valid.
=> fix(an): Agriculture accident location

libs/application/templates/public-debt-payment-plan/src/lib/messages/conclusion.ts, libs/application/templates/public-debt-payment-plan/src/lib/messages/externalData.ts
=> fix(public-debt-payment-plan): typo in external data description

apps/judicial-system/api/src/app/modules/case/interceptors/case.transformer.spec.ts, apps/judicial-system/backend/src/app/formatters/rulingPdf.ts, apps/judicial-system/backend/src/app/modules/notification/notification.service.ts, apps/judicial-system/backend/src/app/modules/police/police.service.ts, apps/judicial-system/web/messages/InvestigationCases/Court/rulingStepTwo.ts, apps/judicial-system/web/messages/RestrictionCases/Court/rulingStepTwo.ts, apps/judicial-system/web/src/routes/Court/InvestigationRequest/Ruling/StepTwo/RulingStepTwoForm.tsx, apps/judicial-system/web/src/routes/Court/RestrictionRequest/Ruling/StepTwo/RulingStepTwo.tsx, apps/judicial-system/web/src/shared-components/AccordionItems/CourtRecordAccordionItem/CourtRecordAccordionItem.tsx
https://app.asana.com/0/1199153462262248/1201312869487959
☝️ 
Iteration after user input
=> chore(judicial-system): Iterates the appeal behaviour in all case types

.github/workflows/config-values.yaml
As reported by @eirikurn here https://islandis.slack.com/archives/C019LNRM6LE/p1636966801123000
=> fix(ci): running config values workflow on PRs

apps/judicial-system/web/src/routes/Court/RestrictionRequest/Ruling/StepTwo/RulingStepTwo.tsx, apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepFour/StepFour.tsx
Handle null check for parent case in step four
=> fix(judicial-system): Fix null check for parentCase

scripts/ci/30_test.sh, scripts/ci/Dockerfile.test
=> fix(ci): setting default jest timeout to 10 seconds

apps/judicial-system/web/src/shared-components/AccordionItems/CourtRecordAccordionItem/CourtRecordAccordionItem.tsx
https://app.asana.com/0/1199153462262248/1201371123227960/f
Format appeals in court record accordion so that there is consistency in the rulingPDF and the UI.
=> chore(judicial-system): Format appeals in court record accordion

apps/services/endorsements/api/infra/endorsement-system-api.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml
Allowing endorsement system to send emails https://github.com/island-is/infrastructure/pull/946
=> feat(endorsement-system): Adding service account to endorsement system

workspace.json
See title
To fix race conditions in CI:
https://github.com/island-is/island.is/runs/4214098155?check_suite_focus=true
=> fix(public-debt-payment-plan): generate payment-schedule client before building openapi schemas

apps/github-actions-cache/src/app/handlers.ts, apps/github-actions-cache/src/app/utils.ts
Invalidate reservation automatically after 5 minutes
This closes island-is/infrastructure#953
=> fix(github-actions-cache): Invalidate reservation

libs/application/templates/general-petition/src/forms/ApplicationForm.ts
=> fix(general-petitions): appl form name

apps/web/screens/Organization/Syslumenn/Auctions.tsx
Hotfix #5317 to release/12.1.0
Syslumenn do require this feature in before the end of today.
=> feat(web): Hotfix - Syslumenn Auctions - Auction takes place at 

libs/application/templates/public-debt-payment-plan/src/forms/PaymentPlanForm.ts, libs/application/templates/public-debt-payment-plan/src/lib/messages/application.ts
Separate employer section from disposable income section and add condition to the employer section
Requested after testing
=> fix(public-debt-payment-plan): employer section changes

libs/application/templates/public-debt-payment-plan/src/fields/DisposableIncome/DisposableIncome.tsx, libs/application/templates/public-debt-payment-plan/src/lib/messages/employer.ts
[1kr1auj](https://app.clickup.com/t/1kr1auj)
Fix typos and missing url
Requested after testing
=> fix(public-debt-payment-plan): disposable income text adjustmens

libs/api/mocks/src/domains/cms/factories.ts, libs/api/mocks/src/domains/search/resolvers.ts, libs/api/mocks/src/domains/search/utils.ts
I'm not entirely sure why this didn't fail in #5666 maybe something to do with how we generate types from contentful and not vice versa
=> fix(web): fixing the cms test

apps/financial-aid/web-osk/pages/api/auth/[...nextauth].ts, apps/financial-aid/web-osk/pages/api/auth/logout.ts, apps/financial-aid/web-veita/pages/api/auth/[...nextauth].ts, apps/financial-aid/web-veita/pages/api/auth/logout.ts
=> fix(fa): Adds log out url to env

apps/financial-aid/backend/src/app/guards/application.guard.ts, apps/financial-aid/backend/src/app/guards/roles.guard.ts
We are throwing forbidden exception from some guards, fixing it and throwing unauth.
=> fix(fa): Exception thrown from guards

apps/api/src/app/app.module.ts, apps/api/src/app/environments/environment.ts
=> fix(ci): Schema generation for api service (take 2)

apps/web/components/Regulations/DiffModeToggle.tsx, apps/web/components/Regulations/RegulationChangelog.tsx, apps/web/components/Regulations/RegulationInfoBox.tsx, apps/web/components/Regulations/RegulationsSidebarBox.tsx, apps/web/components/Regulations/useRegulationIndexer.ts, apps/web/screens/Regulations/RegulationPage.tsx, libs/api/domains/regulations/src/lib/api-domains-regulations.resolver.ts, libs/clients/regulations/src/lib/regulations.ts, libs/regulations/src/lib/types-web.ts
Fixes and imrpovements, commit messages tell all.
=> feat(regulations/web): New minor tweaks and features.

libs/service-portal/wip/src/index.ts
A route got accidentally deleted. Restoring the vehicles route.
=> fix: add back missing route vehicles

apps/github-actions-cache/src/app/auth.ts
Trying to get better info in order to understand [this situation](https://app.datadoghq.eu/logs?cols=core_host%2Ccore_service&context_event=AQAAAX1SfV1HqGBXLwAAAABBWDFTZlc3X0FBRFluUGo5QnZOVTlBQUE&event=&from_ts=1637760919639&index=%2A&live=false&messageDisplay=inline&query=host%3Ai-0b35b1035a608ff8e+service%3Agithub-actions-cache+container_id%3A397c190e374e230e5e348dbb1914be67d748277c0982ea88ff146fe2d5f551f4+filename%3A0.log&saved_view&stream_sort=desc&to_event=AQAAAX1Sfackww4YWwAAAABBWDFTZmFwdEFBQ1ZEMmlwZDYteGlRQU8&to_ts=1637766506276&viz=).
=> fix(ci): Better handling of jwt decoding errors in the github action server

apps/api/src/app/environments/environment.ts, libs/application/template-api-modules/src/lib/modules/templates/public-debt-payment-plan/public-debt-payment-plan.service.ts
Hotfixing issues with the public debt payment plan application.
Can't get past the first screen due to not being able to call the service.
=> fix(public-debt-payment-plan): hotfix env and openid

libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.service.ts
=> fix(application-template-driving-license): fix createCharge return value

.github/CODEOWNERS
=> chore(codeowners): Set Kosmos Kaos as Codeowners to Loftbrú

libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.service.ts, libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/emailGenerators/drivingLicenseSubmittedEmail.spec.ts, libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/emailGenerators/drivingLicenseSubmittedEmail.ts
We were referencing the selected jurisdiction with the wrong key in the email confirmation - also we were trying to send the confirmation too early
=> fix(appliation-template-api-module-driving-license): submission fix

apps/financial-aid/web-veita/src/components/Profile/MunicipalityProfile.tsx, apps/financial-aid/web-veita/src/routes/Municipalities/municipalities.tsx
https://app.asana.com/0/1201427499183230/1201338467682550
Allows super user to change activity on municipality on municipality profile
=> feat(financial-aid): change activity on municipality 

apps/judicial-system/web/src/routes/Court/InvestigationRequest/CourtRecord/CourtRecord.tsx, apps/judicial-system/web/src/routes/Court/RestrictionRequest/CourtRecord/CourtRecord.tsx
https://app.asana.com/0/1199153462262248/1201408210753340/f
☝️ 
Improved usabllity.
=> feat(judicial-system): Autofills court start time with court date rather than current time

apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
https://app.asana.com/0/1199153462262248/1201438409829923/f
☝️ 
Bug
=> fix(judicial-system): Fixes ruling date in prison email

apps/web/components/Organization/Slice/TimelineSlice/TimelineSlice.tsx
Errors on the organization page for digital iceland
=> fix(web): Timeline errors

libs/judicial-system/court-client/src/lib/courtClient.service.ts
https://app.asana.com/0/1199153462262248/1201438409829919/f
- Detects expired authentication tokens when creating a new court case.
- Previously, we were detecting expired authentication tokens when uploading files to court.
- In both cases, a relogin is attempted.
Bug
=> fix(judicial-system): Fixes relogin to court when creating a new case

charts/judicial-system/values.dev.yaml, charts/judicial-system/values.prod.yaml, charts/judicial-system/values.staging.yaml
=> fix(build): Fix build after strategy was removed

libs/api/domains/application/src/lib/application.module.ts
Extending timeout for national registry api.
Api is timing out on prod when it needs a cold start.
=> fix(application-system): Extending timeout (#5821)

apps/application-system/api/src/environments/environment.ts
=> fix(application-system-api): use v1 path for v2 endpoint

apps/financial-aid/backend/src/app/modules/application/application.service.ts, libs/financial-aid/shared/src/lib/formatters.ts
https://app.asana.com/0/1201427499183230/1200560425698683
Fixes month and year in emails
Bug fixing
=> fix(fa): Fixes month in emails

apps/financial-aid/web-osk/src/components/Estimation/Estimation.tsx, apps/financial-aid/web-osk/src/utils/hooks/useApplication.ts, libs/financial-aid/shared/src/lib/interfaces.ts
https://app.asana.com/0/1201427499183230/1201445348663400
Fixes type for spouse
So spouseless users can submit application
=> fix(fa): national registry spouse type

libs/application/templates/public-debt-payment-plan/src/lib/dataSchema.ts, libs/application/templates/public-debt-payment-plan/src/lib/messages/employer.ts, libs/application/templates/public-debt-payment-plan/src/lib/messages/externalData.ts
Approving external data is now required
Wording in employer section fixed
Requested after testing
=> fix(public-debt-payment-plan): fixes after testing

libs/application/templates/public-debt-payment-plan/src/forms/PaymentPlanSubmittedForm.ts, libs/application/templates/public-debt-payment-plan/src/lib/PublicDebtPaymentPlanTemplate.ts
[1mmnvmh](https://app.clickup.com/t/1mmnvmh)
Added submit form to template
=> feat(public-debt-payment-plan): add submit form

libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
=> fix(parental-leave): Fetch spouse from deprecated provider data as backup

libs/application/templates/accident-notification/src/fields/FormOverview/index.tsx
https://app.clickup.com/t/1mf0mym
https://app.clickup.com/t/1mf0pux
Some edit buttons were missing in overview
Only allow editing accident location when in draft state
Following design
=> fix(accident-notification): fix edit buttons

apps/judicial-system/backend/src/app/modules/case/case.controller.ts, apps/judicial-system/backend/src/app/modules/case/case.service.ts, apps/judicial-system/backend/src/app/modules/case/dto/index.ts, apps/judicial-system/backend/src/app/modules/case/dto/internalCreateCase.dto.ts, apps/judicial-system/backend/src/app/modules/case/test/createTestingCaseModule.ts, apps/judicial-system/backend/src/app/modules/case/test/internalCreate.spec.ts, apps/judicial-system/backend/src/app/modules/case/test/internalCreateGuards.spec.ts, apps/judicial-system/backend/src/app/modules/police/test/getAll.spec.ts, apps/judicial-system/xrd-api/src/app/app.service.ts, apps/judicial-system/xrd-api/src/app/test/create.spec.ts, apps/judicial-system/xrd-api/src/app/test/createTestingAppModule.ts
https://app.asana.com/0/1199153462262248/1201358781350317/f
- Adds prosecutor national id and chief investigator to the api.
- Improved error handling.
Improved experience.
=> feat(judicial-system): xRoad API Iteration

apps/financial-aid/web-osk/src/routes/application/Info/info.tsx
https://app.asana.com/0/1201427499183230/1201445348663415
Adds loading indicator for national registry
Better ux
=> fix(fa): Adds loading indicator to info page

apps/skilavottord/ws/src/app/modules/auth/auth.guard.ts, apps/skilavottord/ws/src/app/modules/fjarsysla/fjarsysla.resolver.ts, apps/skilavottord/ws/src/app/modules/recyclingPartner/recyclingPartner.resolver.ts, apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.resolver.ts, apps/skilavottord/ws/src/app/modules/samgongustofa/samgongustofa.resolver.ts, apps/skilavottord/ws/src/app/modules/user/user.resolver.ts, apps/skilavottord/ws/src/app/modules/vehicle/vehicle.resolver.ts, apps/skilavottord/ws/src/app/modules/vehicleOwner/vehicleOwner.resolver.ts
=> fix(skilavottord): auth and add guard

apps/financial-aid/web-osk/src/routes/application/Info/info.tsx
Shows error msg when þjóðskrá connection fails
Better info for user
=> fix(fa): Adds error msg for data fetching

apps/services/auth-api/src/app/app.module.ts, apps/services/auth-api/src/app/modules/delegations/delegations.module.ts, apps/services/auth-public-api/src/app/app.module.ts, apps/services/auth-public-api/src/app/modules/delegations/delegations.controller.ts, apps/services/auth-public-api/src/app/modules/delegations/delegations.module.ts, libs/auth-api-lib/src/lib/services/delegations.service.ts, libs/feature-flags/src/lib/features.ts, libs/nest/feature-flags/src/lib/feature-flag.module.ts, libs/nest/feature-flags/src/lib/feature-flag.service.ts
Feature flags to toggle custom, company and legal guardian feature flags.
So we can release these one at a time while still allowing us to test the others on specific users.
=> feat(delegations): Delegation feature flags

.github/workflows/codeql-analysis.yml
Addresses this warning:
To keep CI runs clean of warnings.
=> chore(codeql): Analyze merge commit

.github/workflows/config-values.yaml, .github/workflows/external-checks.yml, .github/workflows/pullrequest.yml, .github/workflows/push.yml
=> chore(github): set github actions node-based tasks to use node 14

apps/services/auth-api/esbuild.json, apps/services/auth-public-api/esbuild.json
=> fix(ci): missing deps

.github/CODEOWNERS
=> fix(ci): Getting Origo team code ownership setup

libs/api/domains/payment-schedule/src/lib/graphql/payment-schedule.resolver.ts, libs/api/domains/payment-schedule/src/lib/payment-schedule.service.ts
Update employer was missing auth
=> fix(pubic-debt-payment-plan): update employer fix

apps/skilavottord/web/components/GDPR/GDPR.tsx, apps/skilavottord/web/components/GDPR/withGDPR.tsx, apps/skilavottord/web/screens/Confirm/Confirm.tsx, apps/skilavottord/web/screens/Handover/Handover.tsx, apps/skilavottord/web/screens/Overview/Overview.tsx, apps/skilavottord/ws/src/app/modules/fjarsysla/fjarsysla.resolver.ts, apps/skilavottord/ws/src/app/modules/gdpr/gdpr.resolver.ts, apps/skilavottord/ws/src/app/modules/samgongustofa/samgongustofa.resolver.ts, apps/skilavottord/ws/src/app/modules/vehicle/vehicle.resolver.ts, apps/skilavottord/ws/src/app/modules/vehicleOwner/vehicleOwner.resolver.ts
=> fix(skilavottord): using currentUser

libs/service-portal/settings/personal-information/src/components/UserOnboardingModal/UserOnboardingModal.tsx
https://github.com/island-is/island.is/pull/5914
=> fix(service-portal): Add prefix to phone create islykill settings

libs/service-portal/settings/personal-information/src/components/UserOnboardingModal/UserOnboardingModal.tsx
Missing prefix on mobile for create islykill
Required in islykill service
=> fix(service-portal): Add mobile prefix to create

apps/skilavottord/web/components/Header/Header.tsx, apps/skilavottord/web/components/Layouts/PageLayout.tsx, apps/skilavottord/web/components/Modal/Modal.tsx, apps/skilavottord/web/context/UserContext.ts, apps/skilavottord/web/i18n/locales/en.json, apps/skilavottord/web/i18n/locales/is.json, apps/skilavottord/web/i18n/locales/translation.d.ts, apps/skilavottord/web/screens/AccessControl/AccessControl.css.ts, apps/skilavottord/web/screens/AccessControl/AccessControl.tsx, apps/skilavottord/web/screens/CompanyInfo/CompanyInfo.tsx, apps/skilavottord/web/screens/Completed/Completed.tsx, apps/skilavottord/web/screens/Confirm/Confirm.tsx, apps/skilavottord/web/screens/DeregisterVehicle/Confirm/Confirm.tsx, apps/skilavottord/web/screens/DeregisterVehicle/Overview/Overview.tsx, apps/skilavottord/web/screens/DeregisterVehicle/Select.tsx, apps/skilavottord/web/screens/Handover/Handover.tsx, apps/skilavottord/web/screens/Overview/Overview.tsx, apps/skilavottord/web/screens/Overview/components/ActionCard/ActionCard.tsx, apps/skilavottord/web/screens/Overview/components/ActionCardContainer/ActionCardContainer.tsx, apps/skilavottord/web/screens/Overview/components/ProgressCard/ProgressCard.tsx, apps/skilavottord/web/screens/Overview/components/ProgressCardContainer/ProgressCardContainer.tsx, apps/skilavottord/web/screens/Overview/types.ts, apps/skilavottord/web/screens/RecyclingFund/Overview/components/CarsTable/CarsTable.tsx, apps/skilavottord/web/tsconfig.json, apps/skilavottord/ws/src/app/modules/accessControl/accessControl.input.ts, apps/skilavottord/ws/src/app/modules/accessControl/accessControl.resolver.ts, apps/skilavottord/ws/src/app/modules/accessControl/accessControl.service.ts
Delete access control functionality
Part of access control feature
=> feat(skilavottord): delete access control functionality

libs/clients/middlewares/src/lib/createEnhancedFetch.spec.ts, libs/clients/middlewares/src/lib/withCache/CacheResponse.ts
=> fix(core): Fix empty response body handling in enhanced fetch cache

apps/financial-aid/web-osk/src/components/Status/Rejected.tsx
https://app.asana.com/0/1201427499183230/1201435229763489
=> fix(fa): Malskot text added

apps/services/endorsements/api/src/environments/environment.ts
=> fix(endorsement-system-api): Hotfix endorsement system api

apps/web/components/Regulations/Appendixes.tsx, apps/web/components/Regulations/regulationUtils.ts
- Diff styles were missing from appendixes
- "Næsta útgáfa" link in timeline pager was directing to /undefined when next version was current
=> fix(regulations/web): Hotfix - missing appendixes diff styles and tweak pager links

libs/application/templates/driving-assessment-approval/src/lib/DrivingAssessmentApprovalTemplate.ts, libs/application/templates/driving-license/src/lib/constants.ts, libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts, libs/application/templates/general-petition/src/lib/generalPetitionApplicationTemplate.ts, libs/application/templates/reference-template/src/lib/ReferenceApplicationTemplate.ts
=> fix(application-templates): only giving the applicant a role in the driving-* applications, and disabling the general petitions module in prod

libs/application/templates/driving-assessment-approval/src/lib/DrivingAssessmentApprovalTemplate.ts, libs/application/templates/driving-license/src/lib/constants.ts, libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts, libs/application/templates/general-petition/src/lib/generalPetitionApplicationTemplate.ts
cherry pick from main: (#5966)
=> fix(application-templates): only giving the applicant a role -- cherry-pick from main

apps/financial-aid/web-osk/src/routes/application/AboutForm/aboutFormApplicant.tsx
https://app.asana.com/0/1201498198362488/1201038910099137
☝️
=> fix(fa): Removing double underline on link in text

package.json, yarn.lock
=> fix(ci): Upgraded configcat to version 6.7.0 to fix buildbreaking bug

apps/skilavottord/ws/src/app/app.module.ts, apps/skilavottord/ws/src/app/modules/accessControl/accessControl.module.ts, apps/skilavottord/ws/src/app/modules/auth/index.ts, apps/skilavottord/ws/src/app/modules/index.ts, apps/skilavottord/ws/src/app/modules/samgongustofa/test/samgongustofa.service.spec.ts, apps/skilavottord/ws/src/app/modules/user/user.module.ts, apps/skilavottord/ws/tsconfig.spec.json
=> fix(skilavottord): fix failing tests

apps/judicial-system/web/messages/Core/selectProsecutor.ts, apps/judicial-system/web/src/routes/Court/InvestigationRequest/CourtRecord/CourtRecordForm.tsx, apps/judicial-system/web/src/routes/Court/InvestigationRequest/Overview/OverviewForm.tsx, apps/judicial-system/web/src/routes/Court/InvestigationRequest/Ruling/StepOne/RulingStepOneForm.tsx, apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/Defendant/DefendantForm.tsx, apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/HearingArrangements/HearingArrangements.tsx, apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/HearingArrangements/HearingArrangementsForm.tsx, apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/PoliceDemands/PoliceDemandsForm.tsx, apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/PoliceReport/PoliceReport.tsx, apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/PoliceReport/PoliceReportForm.tsx, apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepTwo/StepTwo.tsx, apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepTwo/StepTwoForm.tsx, apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/SelectCourt/SelectCourt.tsx, apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/SelectProsecutor/SelectProsecutor.tsx, apps/judicial-system/web/src/utils/useFormHelper.ts, apps/judicial-system/web/src/utils/validate.ts
https://app.asana.com/0/1199153462262248/1201465012065696/f
Cleaning up code that is no longer being used.
This is a technical dept.
=> chore(judicial-system): Dead code cleanup

apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.resolver.ts
fix RecyclingRequestTypes argument for resolver
its breaking skilavottord app
=> fix(skilavottord): RecyclingRequestTypes argument for resolver

apps/web/next.config.js, libs/island-ui/contentful/src/lib/ProcessEntry/ProcessEntry.tsx, libs/island-ui/core/src/lib/BulletList/BulletList.css.ts, libs/island-ui/core/src/lib/BulletList/BulletList.tsx, libs/island-ui/core/src/lib/Footer/Footer.tsx, libs/island-ui/core/src/lib/Text/Text.css.ts
=> fix(web): Process Entries linking to external

apps/judicial-system/web/src/components/AccordionItems/CaseFilesAccordionItem/CaseFilesAccordionItem.tsx
https://app.asana.com/0/1199153462262248/1201481159264530/f
Fix to ☝️ 
Bug
=> fix(judicial-system): Fixes case file access for received cases

apps/financial-aid/backend/src/app/modules/staff/staff.service.ts
https://app.asana.com/0/1201498198362488/1201234405372298
Fixes email sender
=> fix(fa): Email sender

libs/application/templates/login-service/src/fields/Overview/Overview.tsx, libs/application/templates/login-service/src/lib/messages/terms.ts
Stakeholder wanted another title for terms in overview.
=> fix(login-service): adding special message in overview for terms

apps/skilavottord/web/screens/AccessControl/AccessControl.tsx, apps/skilavottord/ws/src/app/modules/accessControl/accessControl.input.ts
=> fix(skilavottord) - remove citizen from dropdown list in access control

apps/financial-aid/backend/src/app/modules/staff/staff.controller.ts, apps/financial-aid/backend/src/app/modules/staff/test/getStaffById.spec.ts, apps/financial-aid/backend/src/app/modules/staff/test/getStaffByNationalId.spec.ts
Adds tests for staff controller find by id
Testing 1, 2, 3
=> test(fa): Staff controller - find by id

apps/judicial-system/backend/src/app/app.module.ts, apps/judicial-system/backend/src/app/filters/allExceptions.filter.ts, apps/judicial-system/backend/src/app/filters/index.ts, apps/judicial-system/backend/src/app/modules/case/case.service.ts
https://app.asana.com/0/1199153462262248/1201444968653725/f
- Adds a filter for HttpExcetion in the backend application.
- An HttpException with statusCode < 500 is logged as info.
- An HttpException with statusCode >= 500 is logged as error.
- Other exceptions are logged by the default exception handler.
To get better information about backend request handling.
=> chore(judicial-system): Logs all http exceptions in the backend

apps/api/esbuild.json
Trying to build locally yields the following:
Then after adding `color-string` it yields the line `[App] Error	12/21/2021, 11:41:41 AM [ExceptionHandler] Cannot find module 'configcat-node'` on starting up the API locally.
Comparing the stacktrace locally to datadog is equivalent. See [datadog](https://app.datadoghq.eu/logs?cols=host%2Cservice&event&from_ts=1640072641572&index=%2A&live=true&messageDisplay=inline&query=status%3Aerror+env%3Astaging+%40stack%3A%22Error%3A+Cannot+find+module+%27configcat-node%27%0ARequire+stack%3A%0A-+%2Fwebapp%2Fmain.js%0A++++at+Function.Module._resolveFilename+%28internal%2Fmodules%2Fcjs%2Floader.js%3A885%3A15%29%0A++++at+Module.require+%28%2Fwebapp%2Fnode_modules%2Frequire-in-the-middle%2Findex.js%3A27%3A27%29%0A++++at+require+%28internal%2Fmodules%2Fcjs%2F …
=> fix(api): Adding configcat-node to api externals

apps/financial-aid/backend/src/app/modules/staff/staff.service.ts, apps/financial-aid/backend/src/app/modules/staff/test/createTestingStaffModule.ts, apps/financial-aid/backend/src/app/modules/staff/test/getStaffForMunicipality.spec.ts
Adds test for fetching staff for municipality
Was told to do this....
=> test(fa): Staff controller - Staff for municipality

apps/services/user-notification/src/app/modules/notifications/dto/createNotification.response.ts, apps/services/user-notification/src/app/modules/notifications/notifications.controller.ts, apps/services/user-notification/src/buildOpenApi.ts
* Fix incorrect output path of openapi docs
* Add response type to creating notification endpoint
=> fix(user-notification): fix open-api docs

apps/financial-aid/backend/src/app/modules/staff/test/createTestingStaffModule.ts, apps/financial-aid/backend/src/app/modules/staff/test/numberOfUsersForMunicipality.spec.ts
=> test(fa): Staff controller - number of users

apps/financial-aid/backend/src/app/modules/staff/test/createStaff.spec.ts
=> test(fa): Staff controller - create

apps/financial-aid/backend/src/app/modules/staff/test/update.spec.ts
Tests for staff controller - update function
=> test(fa): Staff controller - update

apps/financial-aid/backend/src/app/modules/staff/test/getUsers.spec.ts
Tests for staff controller - get users
=> test(fa): Staff controller - get users

apps/financial-aid/backend/src/app/modules/staff/test/getSupervisors.spec.ts
Tests for staff controller - get supervisors
=> test(fa): Staff controller - get supervisors

apps/services/user-notification/infra/user-notification.ts, charts/islandis/values.dev.yaml, charts/islandis/values.staging.yaml, workspace.json
=> chore(services-user-notification): updating image name and adding express

apps/web/components/BackgroundImage/BackgroundImage.tsx, apps/web/layouts/main.tsx
=> chore(web): use layout and crossorigin fix

apps/services/user-notification/infra/user-notification.ts, charts/islandis/values.dev.yaml, charts/islandis/values.staging.yaml
=> feat(user-notification): ingress for x-road

apps/financial-aid/web-veita/src/components/ModalTypes/AcceptModal.tsx
https://app.asana.com/0/1201498198362488/1200931159717888
using state amount instead of aid amount, if the amount is change so will the tax number
right calculations
=> fix(fa): Accept tax calculation fixed

apps/services/user-notification/infra/user-notification.ts, charts/islandis/values.dev.yaml, charts/islandis/values.staging.yaml
=> fix(services-user-notification): fix ingress path

apps/skilavottord/README.md, apps/skilavottord/web/environments/environment.ts, apps/skilavottord/ws/infra/ws.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml
Cleanup charts and update README.md
=> chore(skilavottord): cleanup charts

apps/skilavottord/web-e2e/src/integration/app.spec.ts, apps/skilavottord/web/components/GDPR/withGDPR.tsx, apps/skilavottord/web/components/List/ListItem.css.ts, apps/skilavottord/web/i18n/locales/en.json, apps/skilavottord/web/i18n/locales/is.json, apps/skilavottord/web/i18n/locales/translation.d.ts, apps/skilavottord/web/pages/en/recycle-vehicle/[id]/recycle.tsx, apps/skilavottord/web/pages/recycle-vehicle/[id]/recycle.tsx, apps/skilavottord/web/screens/Handover/Handover.tsx, apps/skilavottord/web/screens/Overview/Overview.tsx, apps/skilavottord/web/screens/Overview/types.ts, apps/skilavottord/web/screens/RecycleCar/RecycleCar.tsx, apps/skilavottord/web/screens/RecycleCar/index.tsx, apps/skilavottord/web/screens/index.ts
Confirmation step to make recycling process more user friendly
Current confirm action is not clear enough
=> feat(skilavottord): recycle confirmation step

apps/financial-aid/backend/src/app/modules/application/test/create.spec.ts, apps/financial-aid/backend/src/app/modules/application/test/createTestingApplicationModule.ts
https://app.asana.com/0/1201498198362488/1201540075577229
Tests for application controller - create
=> test(fa): Application controller - create

apps/skilavottord/web/graphql/errorLink.ts, apps/skilavottord/web/screens/AccessControl/AccessControl.tsx, apps/skilavottord/web/screens/AccessControl/components/AccessControlCreate/AccessControlCreate.tsx, apps/skilavottord/web/screens/AccessControl/components/AccessControlModal/AccessControlModal.tsx, apps/skilavottord/web/screens/AccessControl/components/AccessControlUpdate/AccessControlUpdate.tsx
=> fix(skilavottord): fix access control required input, message, translation

libs/application/templates/financial-aid/src/dataProviders/NationalRegistryProvider.ts, libs/application/templates/financial-aid/src/forms/Application.ts, libs/application/templates/financial-aid/src/lib/application-templates-financial-aid.tsx, libs/application/templates/financial-aid/src/lib/dataSchema.ts, libs/application/templates/financial-aid/src/lib/messages/application.ts, libs/application/templates/financial-aid/src/lib/messages/error.ts, libs/application/templates/financial-aid/src/lib/messages/externalData.ts, libs/application/templates/financial-aid/src/lib/messages/index.ts, libs/application/templates/financial-aid/src/types/index.ts
https://app.asana.com/0/1201498198362488/1201619714498365
Adds data gathering step into AS
Needed step in financial aid application
=> feat(fa): data gathering

libs/application/templates/general-petition/src/fields/ListSubmitted/index.tsx, libs/application/templates/general-petition/src/lib/messages.ts, libs/service-portal/endorsements/src/lib/messages.ts, libs/service-portal/endorsements/src/screens/ViewPetitionAdmin/ViewPetitionAdmin.tsx
Some minor text fixes for endorsement system.
=> fix(endorsement-system): Text fixes

apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.resolver.ts, apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts, apps/skilavottord/ws/src/app/modules/samgongustofa/samgongustofa.service.ts
Array contained undefined values
The array is mutated
=> fix(skilavottord): fix permno of undefined

apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.resolver.ts, apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts, apps/skilavottord/ws/src/app/modules/samgongustofa/samgongustofa.service.ts
https://github.com/island-is/island.is/pull/6189
=> fix(skilavottord): fix permno of undefined (#6189)

apps/financial-aid/api/src/main.ts, apps/financial-aid/backend/docker-compose.yml, apps/financial-aid/web-osk/next.config.js, apps/financial-aid/web-osk/proxy.config.json
https://app.asana.com/0/1201600280110882/1201629325940990
Making fa and as work together locally.
Should test later on dev environment to see if this ruins anything there
We need to be able to run both back-ends together locally to test out flow
=> chore(fa): Changing ports to be able to run both as and fa together locally

apps/skilavottord/web/screens/RecyclingFund/Overview/Overview.tsx, apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.model.ts, apps/skilavottord/ws/src/app/modules/vehicle/vehicle.model.ts, apps/skilavottord/ws/src/app/modules/vehicle/vehicle.resolver.ts, apps/skilavottord/ws/src/app/modules/vehicle/vehicle.service.ts, apps/skilavottord/ws/src/app/modules/vehicleOwner/vehicleOwner.resolver.ts, libs/nest/pagination/src/lib/paginate.ts
* Where and before should be optional
* Relay like pagination of skilavottordAllDeregisteredVehicles
* Cleanup schema
* add infinite scroll
* Provide default type for generic
Co-authored-by: Darri Steinn Konradsson <darrikonn@gmail.com>
Cherry-picked [feat(skilavottord): pagination and infinite scroll  automerge](https://github.com/island-is/island.is/pull/6195)
=> feat(skilavottord): pagination and infinite scroll (#6195)

libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.service.ts
Adds more logging for the submission service
We are still seeing errors that we can't quite put our finger on. This should at least point us in the right direction.
=> chore(application-templates-driving-license): instrumenting more logging in the submit application action

apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
Previous iteration added 30 minutes to the court end time and set that time. That caused the defender to get a invitation 30 minutes after the invitation sent to the prosecutor.
It's a bug
=> fix(judicial-system): Fix iCal end time

libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.service.ts
cherry picking #6197 into the release branch
=> chore(application-templates-driving-license): instrumenting more logging in the DL application

apps/skilavottord/web/pages/api/auth/[...nextauth].ts
=> fix(skilavottord): add missing offline_access scope

apps/skilavottord/web/pages/api/auth/[...nextauth].ts
- fix(skilavottord): add missing offline_access scope (#6222)
=> fix(skilavottord): add offline access scope

libs/application/templates/general-petition/src/fields/ListSubmitted/index.tsx, libs/application/templates/general-petition/src/lib/generalPetitionApplicationTemplate.ts, libs/application/templates/general-petition/src/lib/messages.ts, libs/service-portal/endorsements/src/lib/messages.ts, libs/service-portal/endorsements/src/screens/ViewPetitionAdmin/ViewPetitionAdmin.tsx
=> fix: general petition template access

libs/application/templates/criminal-record/src/lib/CriminalRecordTemplate.ts
=> feat(sakavottord): Update ready for production flag

apps/web/screens/Organization/Syslumenn/Auctions.tsx, apps/web/screens/queries/Organization.tsx, libs/api/domains/syslumenn/src/lib/models/syslumennAuction.ts, libs/clients/syslumenn/src/lib/syslumennClient.types.ts, libs/clients/syslumenn/src/lib/syslumennClient.utils.ts
Hotfix changes merged to main in PR #6244
=> feat(web): Hotfix - Syslumenn auctions, show respondents and petitioners for ships and real estate

apps/skilavottord/web/screens/DeregisterVehicle/Overview/Overview.tsx, apps/skilavottord/web/screens/DeregisterVehicle/Overview/components/CarsTable/CarsTable.tsx, apps/skilavottord/ws/src/app/graphql/connection.ts, apps/skilavottord/ws/src/app/graphql/index.ts, apps/skilavottord/ws/src/app/modules/recyclingRequest/index.ts, apps/skilavottord/ws/src/app/modules/vehicle/vehicle.model.ts, apps/skilavottord/ws/src/app/modules/vehicle/vehicle.resolver.ts, apps/skilavottord/ws/src/app/modules/vehicle/vehicle.service.ts, apps/skilavottord/ws/src/app/modules/vehicleOwner/vehicleOwner.resolver.ts, apps/skilavottord/ws/src/app/modules/vehicleOwner/vehicleOwner.service.ts
- fix(skilavottord): show vehicle list for recycling partners (#6253)
=> fix(skilavottord): fix role check for fetching vehicles

libs/service-portal/assets/src/screens/AssetsOverview/AssetsOverview.tsx
Tiny text changes 
Because they said so
=> fix(service-portal): change real estate asset text

apps/service-portal/src/components/Sidebar/NavItem/NavItem.css.ts
Setting opacity from 0.8 instead of 0 and speeding up the animation from 250ms to 100ms.
Icon were blurry because of will-change. Removed!
Was lagging, blurry and weird
=> fix(service-portal): Sidebar nav item animation fixes

.github/actions/cache/action.yml, .github/workflows/config-values.yaml, .github/workflows/pullrequest.yml, .github/workflows/push.yml
The cache retry is not working, because the cache-hit output is not behaving like I expected.
So I added a success output to the caching action here: https://github.com/island-is/cache/pull/1
This PR starts to use that success output mentioned above.
=> ci: Cache action success

.github/actions/cache/action.yml
Cache action not handling 404 correctly
=> ci: Bump cache action version to handle 404

apps/services/user-notification/esbuild.json
add firebase-admin to esbuild externals
to not fail the build
=> chore(user-notification): add firebase-admin to esbuild externals

libs/nest/swagger/src/lib/documentation.decorator.spec.ts, libs/nest/swagger/src/lib/documentation.decorator.ts
=> feat(documentation): allows setting summary

apps/service-portal/src/store/modules.ts
Remove assets (fasteignir) from feature flagged modules
Ready for production 🥳 
=> fix(service-portal): remove assets from feature flagged modules

apps/judicial-system/api/esbuild.json, apps/judicial-system/backend/esbuild.json, apps/judicial-system/xrd-api/esbuild.json
The Judicial System no longer deploys correctly and the reason seems to be new dependancies that need to be added to the judicial system applications.
The Judicial System cannot be deployed without it.
=> fix(judicial-system): Adds dependencies to fix deployment

SUMMARY.md, libs/api/domains/company-registry/README.md, libs/clients/rsk/README.md, libs/clients/rsk/company-registry/README.md
update company registry documentation
=> docs(rsk): update company registry documentation

apps/air-discount-scheme/api/infra/api.ts, apps/air-discount-scheme/api/src/environments/environment.ts, apps/air-discount-scheme/web/infra/web.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml
=> fix(air-discount-scheme): secrets location

apps/financial-aid/backend/src/app/modules/municipality/municipality.controller.ts, libs/api/domains/municipalities-financial-aid/src/lib/models/aid.model.ts, libs/api/domains/municipalities-financial-aid/src/lib/models/municipality.input.ts, libs/api/domains/municipalities-financial-aid/src/lib/models/municipality.model.ts, libs/api/domains/municipalities-financial-aid/src/lib/municipalitiesFinancialAid.module.ts, libs/api/domains/municipalities-financial-aid/src/lib/municipalitiesFinancialAid.resolver.ts, libs/api/domains/municipalities-financial-aid/src/lib/municipalitiesFinancialAid.service.ts, libs/application/templates/financial-aid/src/dataProviders/NationalRegistryProvider.ts, libs/clients/municipalities-financial-aid/src/index.ts, libs/clients/municipalities-financial-aid/src/municipalityApiProvider.ts
https://app.asana.com/0/1201664508282204/1201645065535610
Fetches municipality data from Veita in data gathering step
Needed data to process application
=> feat(as): Fetches data for municipalities

apps/api/src/app/environments/environment.ts, libs/application/core/src/types/ApplicationTypes.ts, libs/application/templates/public-debt-payment-plan/src/fields/DisposableIncome/DisposableIncome.tsx, libs/application/templates/public-debt-payment-plan/src/fields/EmployerInfo/EmployerIdField.tsx, libs/application/templates/public-debt-payment-plan/src/fields/EmployerInfo/EmployerInfo.tsx, libs/application/templates/public-debt-payment-plan/src/fields/Overview/Overview.tsx, libs/application/templates/public-debt-payment-plan/src/forms/PaymentPlanForm.ts, libs/application/templates/public-debt-payment-plan/src/lib/dataSchema.ts, libs/application/templates/public-debt-payment-plan/src/lib/messages/error.ts
* getting company info from users input
Co-authored-by: Þorvarður Örn Einarsson <thorrik58@gmail.com>
Co-authored-by: Benedikt Jonsson <bensijons@gmail.com>
Adding connection to new rsk company search service as a temp before the real rsk company search is ready.
So the application is ready to be tested by stakeholders.
=> feat(public-debt-payment-plan): rsk company info (#6305)

apps/air-discount-scheme/api/infra/api.ts, apps/air-discount-scheme/api/src/environments/environment.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml
=> fix(air-discount-scheme): ingress route

apps/air-discount-scheme/backend/src/environments/environment.ts, apps/air-discount-scheme/web/auth/utils.ts, apps/air-discount-scheme/web/lib/environment.ts
- [] I have made corresponding changes to the documentation
=> fix(air-discount-scheme): cookies.

charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml, infra/src/dsl/xroad.ts, libs/clients/data-protection-complaint/src/lib/data-protection-complaint.module.ts
=> chore(data-protection-complaint): Update xroad configs

apps/judicial-system/xrd-api/src/app/app.dto.ts
https://app.asana.com/0/1199153462262248/1201678935283984/f
- Makes prosecutorNationalId options.
It should be optional.
=> fix(judicial-system): Fixes optional parameter

libs/application/templates/p-sign/src/forms/application.ts, libs/application/templates/p-sign/src/lib/messages.ts, libs/application/templates/p-sign/src/lib/pSignTemplate.ts
=> fix(p-sign): minor text updates

SUMMARY.md, apps/services/personal-representative-public/README.md, workspace.json
Gitbook update
Also adding dockerizing to workspace settings
=> fix(personal-representative): Gitbook and Docker setup - Clean branch

.github/CODEOWNERS
=> chore: add juni/kosmos as codeowners to user-profile and message-queue

workspace.json
Updating setup in workspace to sync with src setup for production
=> fix(personal-representative): Production build

apps/web/screens/Search/Search.tsx, apps/web/screens/ServiceWeb/Search/ServiceSearch.tsx
=> fix(plausible): Normalize queries with lowercase (#6288)

libs/application/template-api-modules/src/lib/modules/templates/login-service/emailGenerators/applicationOverviewTemplate.ts
[1u63bka](https://app.clickup.com/t/1u63bka)
Adding terms agreement checkmark to email overview
=> fix(login-service): adding terms checkmark to email overview

apps/financial-aid/api/src/app/modules/application/dto/createApplication.input.ts, apps/financial-aid/api/src/services/backend.ts, apps/financial-aid/backend/src/app/modules/application/application.service.ts, apps/financial-aid/backend/src/app/modules/application/dto/createApplication.dto.ts, apps/financial-aid/backend/src/app/modules/application/test/create.spec.ts, apps/financial-aid/web-osk/src/utils/hooks/useApplication.ts, libs/financial-aid/shared/src/lib/interfaces.ts
https://app.asana.com/0/1201664508282204/board
Reads user national id from token instead of input
Security issue
=> fix(fa): National id read from token

apps/financial-aid/backend/esbuild.json
https://app.asana.com/0/1201664508282204/1201698304881585
Fixing deployment environment
This might need more imports but trying to have this minimal
We use it
=> fix(fa): Adds protobuf/aspromise to esbuild

apps/services/personal-representative/src/app/modules/accessLogs/accessLogs.controller.ts, apps/services/personal-representative/src/app/modules/personalRepresentativeTypes/personalRepresentativeTypes.controller.ts, apps/services/personal-representative/src/app/modules/personalRepresentatives/personalRepresentatives.controller.ts, apps/services/personal-representative/src/app/modules/rightTypes/rightTypes.controller.ts
Auth import isolated from other import because of funky build error
=> fix(personal-representative): Auth import isolated from other import because of build error

apps/judicial-system/api/src/app/modules/court/court.service.ts
https://app.asana.com/0/1199153462262248/1201672121837673/f
- Maps RVG's electronic data discovery investigation to the correct court system case type.
Better usability
=> fix(judicial-system): Updates RVG case type to court system case type mapping

apps/judicial-system/web/src/routes/Court/InvestigationRequest/HearingArrangements/HearingArrangements.tsx, apps/judicial-system/web/src/routes/Court/RestrictionRequest/Ruling/StepOne/RulingStepOne.tsx, apps/judicial-system/web/src/utils/hooks/use-case/useCase.tsx
https://app.asana.com/0/1199153462262248/1201634243867932/f
☝️ 
it should.
=> fix(judicial-system): Autofills isCustodyIsolation

.github/CODEOWNERS, libs/application/data-providers/src/index.ts, libs/application/data-providers/src/providers/HasQualityPhotoProvider.ts, libs/application/template-api-modules/src/lib/modules/templates/p-sign-submission/p-sign-submission.service.ts, libs/application/templates/driving-license/src/dataProviders/QualityPhotoProvider.ts, libs/application/templates/driving-license/src/dataProviders/index.ts, libs/application/templates/driving-license/src/fields/QualityPhoto/hooks/useQualityPhoto.ts, libs/application/templates/p-sign/src/dataProviders/QualityPhotoProvider.ts, libs/application/templates/p-sign/src/dataProviders/index.ts, libs/application/templates/p-sign/src/forms/application.ts, libs/application/templates/p-sign/src/lib/messages.ts, libs/application/templates/p-sign/src/lib/pSignTemplate.ts
- minor text fixes in p-sign template
- prefix to base64 sting in p-sign submission
- quality photo provider abstract for application specific functionality in driving license template and p-sign template
=> fix: p sign text and quality photo fix

apps/financial-aid/backend/src/app/modules/application/application.controller.ts, apps/financial-aid/backend/src/app/modules/application/application.service.ts, apps/financial-aid/backend/src/app/modules/application/test/create.spec.ts, apps/financial-aid/backend/src/app/modules/application/test/update.spec.ts, apps/financial-aid/web-veita/src/components/ApplicationHeader/ApplicationHeader.tsx
Allows only applicant that have not applied to create an application.
Only allows users to mutate application if they are allowed to.
Fix spouse endpoint
Removes only on tests and updates tests
Moved change row check in update so we don't update other tables if application is not updated.
Better security and bug fixes.
=> chore(fa): Application hardening

apps/skilavottord/ws/src/app/modules/fjarsysla/fjarsysla.service.ts, apps/skilavottord/ws/src/app/modules/gdpr/gdpr.resolver.ts, apps/skilavottord/ws/src/app/modules/gdpr/gdpr.service.ts, apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.resolver.ts, apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts, apps/skilavottord/ws/src/app/modules/samgongustofa/samgongustofa.service.ts, apps/skilavottord/ws/src/app/modules/vehicle/vehicle.resolver.ts, apps/skilavottord/ws/src/app/modules/vehicle/vehicle.service.ts, apps/skilavottord/ws/src/app/modules/vehicleOwner/vehicleOwner.resolver.ts, apps/skilavottord/ws/src/app/modules/vehicleOwner/vehicleOwner.service.ts
=> fix(skilavottord): logging refactor

apps/judicial-system/backend/src/app/formatters/rulingPdf.ts, apps/judicial-system/backend/src/app/messages/requestPdf.ts, apps/judicial-system/backend/src/app/messages/rulingPdf.ts
https://app.asana.com/0/1199153462262248/1201614149125794/f
https://app.asana.com/0/1199153462262248/1201711459721946/f
- Adds the case stakeholders to the ruling pdf.
- Fixes a few Contentul string definitions.
PDF improvements.
=> feat(judicial-system): Adds case stakeholders to ruling pdf

apps/judicial-system/web/messages/InvestigationCases/Court/courtRecordForm.ts, apps/judicial-system/web/src/routes/Court/InvestigationRequest/CourtRecord/CourtRecord.tsx, apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/Overview/OverviewForm.tsx, apps/judicial-system/web/src/routes/Shared/Requests/PastRequests.tsx
https://app.asana.com/0/1199153462262248/1201256841519082/f
Minor text changes regarding multiple defendants
These are UI bugs
=> fix(judicial-system): Minor text changes regarding multiple defendants

apps/financial-aid/backend/src/app/modules/application/emailTemplates/adminAndEmployeeEmailTemplate.ts, apps/financial-aid/backend/src/app/modules/application/emailTemplates/adminEmailTemplate.ts, apps/financial-aid/backend/src/app/modules/application/emailTemplates/applicantEmailTemplate.ts, apps/financial-aid/backend/src/app/modules/application/emailTemplates/employeeEmailTemplate.ts, apps/financial-aid/backend/src/app/modules/application/emailTemplates/shared.ts
https://app.asana.com/0/1201664508282204/1201709793718726
☝️ 
👆
=> chore(fa): Remove sis logo from emails

apps/financial-aid/backend/src/app/modules/application/application.controller.ts, apps/financial-aid/backend/src/app/modules/application/test/update.spec.ts
=> fix(fa): Throws exception when staff is not found

apps/financial-aid/web-veita/graphql/sharedGql.ts
https://app.asana.com/0/1201664508282204/1201633158617687
Adds spouse national id to update mutation. 
Resolves in error if not fetched when application is updated
=> fix(fa): Adds spouseNationalId to update mutation

.github/workflows/push.yml
This reverts commit 30da07bf8fa460602c929923e057d4681e57f6b0.
=> fix(ci):Revert "adding wretry from marketplace. Lets give it a go (#6390)"

apps/services/personal-representative-public/README.md, apps/services/personal-representative-public/src/main.ts, apps/services/personal-representative/README.md, apps/services/personal-representative/src/main.ts
Swaggerpath set to '' to tackle /swagger -> /swagger/ redirect
=> fix(personal-representative): Handling swagger redirect

apps/financial-aid/web-veita/graphql/sharedGql.ts
=> fix(fa): broken codegen

libs/application/templates/accident-notification/src/lib/AccidentNotificationTemplate.ts
[1mmkyj1](https://app.clickup.com/t/1mmkyj1)
Change progress on each state.
So that it makes more sense for the user.
=> fix(accident-notification): change progress

.github/workflows/push.yml
=> fix(ci): Retry for failed docker build

libs/application/templates/data-protection-complaint/src/fields/AgreementDescription.tsx, libs/application/templates/data-protection-complaint/src/fields/ComplaineeRepeater/ComplaineeRepeaterItem.tsx, libs/application/templates/data-protection-complaint/src/fields/ComplaintConfirmation/ComplaintConfirmation.css.ts, libs/application/templates/data-protection-complaint/src/fields/ComplaintConfirmation/ComplaintConfirmation.tsx, libs/application/templates/data-protection-complaint/src/fields/FieldAlertMessage.tsx, libs/application/templates/data-protection-complaint/src/forms/ComplaintForm.ts, libs/application/templates/data-protection-complaint/src/lib/dataSchema.ts, libs/application/templates/data-protection-complaint/src/lib/messages/confirmation.ts, libs/application/templates/data-protection-complaint/src/lib/messages/delimitation.ts, libs/application/templates/data-protection-complaint/src/lib/messages/error.ts
Fixing issues with personuvernd application
Requested
=> fix(data protection complaint): Hotfix for release

libs/api/domains/driving-license/src/lib/drivingLicense.service.ts, libs/api/domains/driving-license/src/lib/drivingLicense.spec.ts, libs/application/templates/driving-assessment-approval/src/fields/StudentLookupField.tsx, libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
cherry-picking #6411 to release
to fix akstursmat
=> fix(api-domains-driving-license): allowing expired licenses for student lookup

apps/skilavottord/web/components/Header/Header.tsx, apps/skilavottord/web/screens/Completed/Completed.tsx, apps/skilavottord/web/screens/DeregisterVehicle/Overview/Overview.tsx, apps/skilavottord/web/screens/DeregisterVehicle/Select.tsx, apps/skilavottord/web/screens/RecycleCar/RecycleCar.tsx, apps/skilavottord/web/screens/RecyclingFund/Overview/Overview.tsx, apps/skilavottord/ws/src/app/modules/auth/user.model.ts, apps/skilavottord/ws/src/app/modules/gdpr/gdpr.resolver.ts
Fix types
Was failing codecov testing
=> fix(skilavottord): fix types

apps/web/screens/Login/Login.tsx
Merging this one: 
https://github.com/island-is/island.is/pull/6406
Commit: 79a189597e067b26c8d9d7cea61d0446a3b6e85f
=> fix(web): remove beta tag + list on login screen (#6406)

apps/air-discount-scheme/backend/infra/backend.ts, apps/air-discount-scheme/backend/src/app/app.module.ts, apps/air-discount-scheme/backend/src/app/modules/user/test/unit/user.service.spec.ts, apps/air-discount-scheme/backend/src/app/modules/user/user.controller.ts, apps/air-discount-scheme/backend/src/app/modules/user/user.module.ts, apps/air-discount-scheme/backend/src/app/modules/user/user.service.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml
=> fix(air-discount-scheme): rollback

apps/download-service/esbuild.json
=> fix(download-service): pseudomap needed in esbuild

apps/api/infra/api.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml, libs/application/template-api-modules/src/lib/modules/templates/criminal-record-submission/criminal-record-submission.service.ts, libs/application/template-api-modules/src/lib/modules/templates/criminal-record-submission/emailGenerators/syslumennNotification.ts
=> feat(sakavottord): Increase timeout for syslumenn api

apps/services/personal-representative/esbuild.json
=> fix(personal-representative): swagger UI is missing

apps/services/personal-representative-public/esbuild.json
Including SwaggerUI in build for demo and testing purposes
=> fix(personal-representative-public): SwaggerUI fix for demo

apps/services/personal-representative-public/esbuild.json, apps/services/personal-representative-public/src/environments/environment.ts, apps/services/personal-representative/src/environments/environment.ts
Environment variables for identity server matched to helm setup
=> fix(personal-representative): Environment variables matched to helm setup

apps/services/user-notification/infra/user-notification.ts, charts/islandis/values.dev.yaml
=> chore(user-notification): add contentful access token

apps/financial-aid/web-osk/src/routes/application/SummaryForm/spouseSummary.tsx, apps/financial-aid/web-osk/src/routes/application/SummaryForm/summaryForm.tsx, apps/financial-aid/web-osk/src/routes/status/MainPage/mainPage.tsx
https://app.asana.com/0/1201722624788165/1201752115305187
- fixing error message
- requested
=> fix(fa): fixing spelling mistakes in error message

apps/services/user-notification/esbuild.json
=> chore(user-notification): adding stuffs to esbuild

apps/air-discount-scheme/backend/infra/backend.ts, apps/air-discount-scheme/backend/src/app/app.module.ts, apps/air-discount-scheme/backend/src/app/modules/flight/flight.controller.ts, apps/air-discount-scheme/backend/src/app/modules/flight/flight.service.ts, apps/air-discount-scheme/backend/src/app/modules/nationalRegistry/nationalRegistry.service.ts, apps/air-discount-scheme/backend/src/app/modules/user/test/unit/user.service.spec.ts, apps/air-discount-scheme/backend/src/app/modules/user/user.controller.ts, apps/air-discount-scheme/backend/src/app/modules/user/user.module.ts, apps/air-discount-scheme/backend/src/app/modules/user/user.service.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml, charts/judicial-system/values.dev.yaml, charts/judicial-system/values.prod.yaml, charts/judicial-system/values.staging.yaml, infra/src/dsl/dsl.ts, infra/src/dsl/feature-values.spec.ts, infra/src/dsl/initContainer.spec.ts, infra/src/dsl/map-to-values.ts, infra/src/dsl/postgres.spec.ts, infra/src/dsl/types/input-types.ts, infra/src/dsl/types/output-types.ts
=> feat(air-discount-scheme): loftbru-roll-forward

charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml, charts/judicial-system/values.dev.yaml, charts/judicial-system/values.prod.yaml, charts/judicial-system/values.staging.yaml, infra/src/dsl/dsl.ts, infra/src/dsl/feature-values.spec.ts, infra/src/dsl/initContainer.spec.ts, infra/src/dsl/map-to-values.ts, infra/src/dsl/postgres.spec.ts, infra/src/dsl/types/input-types.ts, infra/src/dsl/types/output-types.ts
=> fix: Fixing a bug in the resource limits and requests matching the NodeJS runtime configuration 

apps/judicial-system/backend/src/app/messages/notifications.ts, apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
https://app.asana.com/0/1199153462262248/1201437594297191/f
- Uses different wording for custody cases with and without isolation.
Clearer notifications.
=> feat(judicial-system): Updates modified notification content

apps/judicial-system/web/messages/InvestigationCases/Court/hearingArrangements.ts, apps/judicial-system/web/messages/RestrictionCases/Court/hearingArrangements.ts, apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
https://app.asana.com/0/1199153462262248/1201437594297191/f
Fixes type errors we were getting when pushing strings to Contentful. 
It's a bug
=> fix(judicial-system): Fix CF strings

apps/api/infra/api.ts, apps/application-system/api/infra/application-system-api.ts, apps/download-service/infra/download-service.ts, apps/icelandic-names-registry/backend/infra/icelandic-names-registry-backend.ts, apps/services/documents/infra/documents-service.ts, apps/services/endorsements/api/infra/endorsement-system-api.ts, apps/services/user-profile/infra/service-portal-api.ts, apps/skilavottord/ws/infra/ws.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml, charts/judicial-system/values.dev.yaml, charts/judicial-system/values.prod.yaml, charts/judicial-system/values.staging.yaml, infra/src/environments.ts
=> fix(skilavottord): Configuration for IDS using environment variables again

apps/air-discount-scheme/backend/src/app/modules/user/test/unit/user.controller.spec.ts, apps/air-discount-scheme/backend/src/app/modules/user/test/unit/user.service.spec.ts, apps/air-discount-scheme/backend/src/app/modules/user/user.controller.ts, apps/air-discount-scheme/backend/src/app/modules/user/user.service.ts
- [] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works
=> fix(Loftbru): reykjavik children with countryside parent/s

apps/application-system/api/infra/application-system-api.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml
=> fix(application-system): fixing configuration for application-system-api-worker

apps/judicial-system/web/src/components/InfoCard/InfoCard.tsx, apps/judicial-system/web/src/routes/Court/RestrictionRequest/Ruling/StepTwo/RulingStepTwo.tsx, apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/DefendantInfo/DefendantInfo.tsx
https://app.asana.com/0/1199153462262248/1201337986358804/f
- Removes gender header from defendant info
- Adds a comma after defendant name in conclusion
- Change how we display a defendant's citizenship in info cards
Better ux
=> fix(judicial-system): Various fixes to no national id functionality

apps/application-system/api/infra/application-system-api.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml
=> fix(as): Add missing xroad env to as worker

libs/api/domains/fishing-license/src/graphql/fishing-license.resolver.ts, libs/api/domains/fishing-license/src/lib/api-domains-fishing-license.spec.ts, libs/api/domains/fishing-license/src/lib/fishing-license.service.ts, libs/application/templates/general-fishing-license/src/graphql/queries.ts, libs/clients/fishing-license/src/index.ts, libs/clients/fishing-license/src/lib/apiConfiguration.ts, libs/clients/fishing-license/src/lib/fishing-license-client.module.ts
=> use fiskistofa apis

apps/financial-aid/web-osk/src/components/FormProvider/FormProvider.tsx
=> fix(fa): initialize session storage

libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification.utils.ts, libs/application/template-api-modules/src/lib/modules/templates/accident-notification/types/applicationSubmit.ts, libs/application/templates/accident-notification/src/shared/constants.ts
Replace string values with id's on accident location
Requested by Sjúkra
=> feat(accident notification): Replace string values with id's on accident location

libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification.utils.ts, libs/application/template-api-modules/src/lib/modules/templates/accident-notification/types/applicationSubmit.ts, libs/application/templates/accident-notification/src/shared/constants.ts
=> fix(accident notification): Hotfix id instead of string accident location

libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/data-protection-utils.ts, libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/models/complaint.ts, libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/pdfGenerators/templates/complaintPdf.ts
=> fix(data-protection-complaint): Account for optional nationalid value

libs/service-portal/assets/src/utils/createUnits.ts
Remove appraisal from units of use.
=> feat(service-portal): Remove appraisal from units of use

apps/judicial-system/web/src/utils/hooks/useCourtUpload/index.ts, apps/judicial-system/web/src/utils/hooks/useFileList/index.ts
https://app.asana.com/0/1199153462262248/1201764221089443/f
- Fixes error Apollo error checking in cient.
This was a bug that caused some case file operations to fail silently or with an unhandled exception.
=> fix(judicial-system): Fixes ApolloError handling in client

apps/judicial-system/web/src/components/RulingInput/RulingInput.tsx, apps/judicial-system/web/src/routes/Court/InvestigationRequest/CourtRecord/CourtRecordForm.tsx, apps/judicial-system/web/src/routes/Court/InvestigationRequest/Ruling/StepOne/RulingStepOneForm.tsx, apps/judicial-system/web/src/routes/Court/InvestigationRequest/Ruling/StepTwo/RulingStepTwoForm.tsx, apps/judicial-system/web/src/routes/Court/RestrictionRequest/CourtRecord/CourtRecord.tsx, apps/judicial-system/web/src/routes/Court/RestrictionRequest/Ruling/StepOne/RulingStepOne.tsx, apps/judicial-system/web/src/routes/Court/RestrictionRequest/Ruling/StepTwo/RulingStepTwo.tsx, apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/CaseFiles/CaseFilesForm.tsx, apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/PoliceDemands/PoliceDemandsForm.tsx, apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/PoliceReport/PoliceReportForm.tsx, apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepFive/StepFiveForm.tsx, apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepFour/StepFour.tsx, apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepThree/StepThreeForm.tsx
Automatically expand textareas as the user types into them.
Better UX
https://user-images.githubusercontent.com/3789875/154286313-02959e0c-b57d-44ec-a55f-54c56e4e371a.mov
=> feat(judicial-system): Autoexpand textareas

libs/financial-aid/shared/src/components/TaxBreakdown/TaxBreakdown.css.ts, libs/financial-aid/shared/src/components/TaxBreakdown/TaxBreakdown.tsx, libs/financial-aid/shared/src/components/TaxBreakdown/TaxBreakdownItem.tsx
https://app.asana.com/0/1201813977904020/1201752166226723
- Ux experiance
Mobile
Desktop
=> feat(fa): Direct tax return table mobile friendly

scripts/_run-aws-eks-commands.js
=> fix: proxy script using correct docker image

apps/download-service/src/app/modules/finance-documents/document.controller.ts, libs/service-portal/finance/src/components/DocumentScreen/DocumentScreen.tsx, libs/service-portal/finance/src/components/FinanceStatusDetailTable/FinanceStatusDetailTable.tsx, libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx, libs/service-portal/finance/src/utils/documentFormSubmission.ts, libs/service-portal/licenses/src/components/QRCodeModal/QRCodeModal.tsx, libs/service-portal/licenses/src/screens/DrivingLicenseDetail/DrivingLicenseDetail.tsx, libs/service-portal/licenses/src/screens/LicensesOverview/LicensesOverview.tsx
#6643 - fix finance document download bug 🐞 
#6627 - cleanup console + no category text in driving license bug 🐞 
⬆️
=> fix(service-portal): finance + license bugs

apps/air-discount-scheme/backend/src/app/modules/nationalRegistry/nationalRegistry.service.ts, apps/air-discount-scheme/backend/src/app/modules/user/test/unit/user.service.spec.ts, apps/air-discount-scheme/backend/src/app/modules/user/user.module.ts, apps/air-discount-scheme/backend/src/app/modules/user/user.service.ts, apps/air-discount-scheme/web/graphql/errorLink.ts
Hot fixing some edge cases for users.
Same code as this pull request.
https://github.com/island-is/island.is/pull/6644
=> fix(ads): forsja include self

libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/attachments/providers/pdfFileProvider.ts, libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/data-protection-complaint.service.ts, libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/data-protection-utils.ts, libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/models/complaint.ts, libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/pdfGenerators/constants.ts, libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/pdfGenerators/pdfUtils.ts, libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/pdfGenerators/templates/complaintPdf.ts
=> fix(data-protection-complaint): pdf template updates

libs/financial-aid/shared/src/data/serviceCenters.ts
https://app.asana.com/0/1201849781730850/1201785170450356
Link people who live in Reykjavik straight into Reykjavik's financial aid website.
So users don't need to search for Reykjavik's financial aid website.
=> fix(fa): Fix links to Reykjavik financial aid

apps/judicial-system/web/messages/Core/sections.ts, apps/judicial-system/web/messages/Core/signedVerdictOverview.ts, apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx, apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverviewForm.tsx
https://app.asana.com/0/1199153462262248/1201721844032877/f
- Adds various texts, used when sharing cases with other prosecutors offices, to Contentful.
So they can be changed without releasing a new version.
=> chore(judicial-system): Adds share case texts to Contentful

apps/air-discount-scheme/web-e2e/cypress.json, apps/application-system/form-e2e/cypress.json, apps/auth-admin-web-e2e/cypress.json, apps/gjafakort/web-e2e/cypress.json, apps/service-portal-e2e/cypress.json, apps/skilavottord/web-e2e/cypress.json, apps/system-e2e/cypress.json, apps/web-e2e/cypress.json
https://github.com/island-is/island.is/issues/6563
Adding config to cypress which allows it to retry failed tests.
To make flaky tests less likely
=> ci: All cypress config should have retry

apps/financial-aid/web-osk/src/utils/hooks/useNavigationTree.ts
https://app.asana.com/0/1201849781730850/1201624216643404
Change "Atvinna" to "Staða" in the stepper.
=> fix(fa): Fix wording on stepper

apps/financial-aid/web-osk/src/components/PrivacyPolicyAccordion/PrivacyPolicyAccordion.tsx
https://app.asana.com/0/1201849781730850/1201624025839596
Make a link more visible by using the Link component instead of "a".
Make it more obvious it is a link.
=> fix(fa): Fix link in application

apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
https://app.asana.com/0/1199153462262248/1201721844032877/f
- Update. security level on the server.
Bug
=> fix(judicial-system): Fix removal of heightened security level when sharing a case

apps/air-discount-scheme/backend/src/app/modules/flight/flight.service.ts
=> fix(air-discount-scheme): Activate flight codes for 2022

apps/air-discount-scheme/backend/src/app/modules/flight/flight.service.ts
=> fix(air-discount-scheme): Activate flight codes for 2022 (#6697)

apps/web/components/Organization/Wrapper/Themes/SyslumennTheme/SyslumennFooter.tsx, apps/web/context/GlobalContext/GlobalContext.tsx, apps/web/layouts/main.tsx, apps/web/screens/Search/Search.tsx
=> fix(service-web): remove service web links

SUMMARY.md, apps/air-discount-scheme/backend/src/app/sequelizeConfig.service.ts, apps/application-system/api/src/app/sequelizeConfig.service.ts, apps/financial-aid/backend/src/app/sequelizeConfig.service.ts, apps/icelandic-names-registry/backend/src/app/sequelizeConfig.service.ts, apps/judicial-system/backend/src/app/sequelizeConfig.service.ts, apps/reference-backend/src/app/sequelizeConfig.service.ts, apps/services/documents/src/app/modules/document-provider/controllers/documentsInfra.controller.ts, apps/services/documents/src/app/sequelizeConfig.service.ts, apps/services/endorsements/api/src/app/sequelizeConfig.service.ts, apps/services/user-profile/src/app/sequelizeConfig.service.ts, apps/services/user-profile/src/app/user-profile/userProfileInfra.controller.ts, apps/skilavottord/ws/src/app/sequelizeConfig.service.ts, handbook/technical-overview/devops/README.md, handbook/technical-overview/devops/database.md, libs/auth-api-lib/src/lib/services/sequelizeConfig.service.ts, libs/nest/sequelize/src/lib/sequelize.spec.ts, libs/nest/sequelize/src/lib/sequelize.ts, libs/testing/nest/src/lib/hooks/useDatabase.ts
https://github.com/island-is/infrastructure/issues/1130
Writing up instructions on how to enable read replicas. Additionally I refactored all services that use sequelize get their config from a single library.
So developers can enable read replicas for their service without help and to make that process simpler I refactored the config.
=> chore: Describe how to enable read replicas

apps/judicial-system/web/messages/InvestigationCases/Prosecutor/caseFiles.ts, apps/judicial-system/web/messages/RestrictionCases/Prosecutor/caseFiles.ts, apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/CaseFiles/CaseFilesForm.tsx, apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepFive/StepFiveForm.tsx
https://app.asana.com/0/1199153462262248/1201842203105403/f
Start using general error messages in case files steps
We want to define error messages all in the same place for consistency
=> chore(judicial-system): Start using general error messages in case files steps

apps/financial-aid/api/src/app/modules/application/dto/updateApplication.input.ts
https://app.asana.com/0/1201849781730850/1201892339168944
Make directTaxPayments optional when updating application.
So that we don´t have to send a directTaxPayments object when updating other fields of the application.
=> fix(fa): Fix state change error

apps/web/screens/Organization/Syslumenn/OperatingLicenses.tsx, apps/web/screens/queries/Organization.tsx, libs/api/domains/syslumenn/src/lib/dto/getOperatingLicenses.input.ts, libs/api/domains/syslumenn/src/lib/models/operatingLicense.ts, libs/api/domains/syslumenn/src/lib/models/paginatedOperatingLicenses.ts, libs/api/domains/syslumenn/src/lib/models/paginationInfo.ts, libs/api/domains/syslumenn/src/lib/syslumenn.resolver.ts, libs/clients/syslumenn/src/clientConfig.json, libs/clients/syslumenn/src/lib/__mock-data__/requestHandlers.ts, libs/clients/syslumenn/src/lib/__mock-data__/responses.ts, libs/clients/syslumenn/src/lib/syslumenn.spec.ts, libs/clients/syslumenn/src/lib/syslumennClient.service.ts, libs/clients/syslumenn/src/lib/syslumennClient.types.ts, libs/clients/syslumenn/src/lib/syslumennClient.utils.ts
Cherry-picks merge commit from PR #6421 to release branch. See the PR for more details on the changes.
=> feat(web): Hotfix Syslumenn / Paginated operating licences

.github/actions/ci-io.ts, .github/actions/dist/index.js, .github/actions/local-runner.ts
The script was failing on large changesets since the `nx` command line was getting really long and hitting some limits in the kernel. 
=> fix(ci): change detection failure on large changesets

apps/web/components/StepperFSM/StepperFSM.tsx, apps/web/components/StepperFSM/StepperFSMUtils.tsx, apps/web/screens/Article/Article.css.ts, apps/web/screens/Article/Article.tsx, apps/web/screens/Article/index.ts
* Improved the visuals for the stepper
* Sorted the countries list that arrive from the UI configuration 
* The stepper visuals were out of sync with the other UI
=> feat(web): Improved visuals for the Stepper

libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx, scripts/generate-schemas.sh
Display buttons even though status is equal to 0. 
Users may want to print or download files even though their status is 0.
=> fix(service-portal): print and dl button not visible when status 0

apps/service-portal/infra/service-portal.ts, apps/services/user-profile/infra/service-portal-api.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml
Fixes https://github.com/island-is/island.is/issues/6787
=> fix(service-portal-api): Add resources to service portal api

libs/service-portal/settings/personal-information/README.md
Update modal readme for serviceportal
Make it clearer
=> feat(service-portal): Update modal readme

apps/judicial-system/backend/src/app/factories/date.factory.ts, apps/judicial-system/backend/src/app/factories/index.ts, apps/judicial-system/backend/src/app/formatters/courtRecordPdf.ts, apps/judicial-system/backend/src/app/formatters/rulingPdf.ts, apps/judicial-system/backend/src/app/modules/case/case.service.ts, apps/judicial-system/backend/src/app/modules/case/filters/case.filters.spec.ts, apps/judicial-system/backend/src/app/modules/case/test/extend.spec.ts, apps/judicial-system/backend/src/app/modules/court/court.module.ts, apps/judicial-system/backend/src/app/modules/court/court.service.ts, apps/judicial-system/backend/src/app/modules/court/test/createCourtCase.spec.ts, apps/judicial-system/backend/src/app/modules/court/test/createTestingCourtModule.ts, apps/judicial-system/backend/src/app/modules/file/test/createCaseFile.spec.ts
https://app.asana.com/0/1199153462262248/1201872524630529/f
- Replaces `new Date()` with `now()` from a date factory in production code.
- Replaces `new Date()` with random dates in tests.
Easier testing.
=> chore(judicial-system): Date Factory

apps/judicial-system/web/messages/Core/signedVerdictOverview.ts, apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/CaseDates/CaseDates.tsx, apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverviewForm.tsx
[Asana task](https://app.asana.com/0/1199153462262248/1201900945687150/f)
- add ruling date label translate string
- move ruling date label and use translate string
- placement of the label was in the wrong place
| Before | After |
| - | - |
| ![Screenshot 2022-03-07 at 14 50 28](https://user-images.githubusercontent.com/5700902/157061246-52c040ca-f36a-4d01-b9aa-32ae972d3e69.png) | ![Screenshot 2022-03-07 at 14 50 08](https://user-images.githubusercontent.com/5700902/157061285-2d51eb40-c09d-4ca8-bc26-4104795d7142.png) |
=> fix(judicial-system): move ruling date

apps/judicial-system/web/messages/Core/requests.ts, apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
[Asana task](https://app.asana.com/0/1199153462262248/1201888481479194/f)
- Update wording for requets (Kröfur verða mál)
=> chore(judical-system): update wording for requests

apps/financial-aid/web-osk/src/components/MoreActions/MoreActions.tsx, apps/financial-aid/web-osk/src/routes/application/Confirmation/confirmation.tsx, apps/financial-aid/web-osk/src/routes/status/MainPage/mainPage.tsx, apps/financial-aid/web-veita/src/components/MunicipalityAdminSettings/MunicipalityAdminSettings.tsx
https://app.asana.com/0/1201927126329736/1201873101852457
- Fix links to rules homepage
- Updating municipality settings in Veita was giving a 400 Bad Request error, so I fixed that as well
=> fix(fa): Fix links to rules homepage

libs/logging/src/lib/logging.ts
=> chore(infra): disabling Sentry error reporting

apps/web/components/Project/Header/UkraineProjectHeader.css.ts, apps/web/components/Project/Header/UkraineProjectHeader.tsx, apps/web/screens/Project/Project.tsx
Cherry-picks merge commit from PR https://github.com/island-is/island.is/pull/6821 to release branch. See the PR for more details on the changes.
=> feat(web): Hotfix added banner image to mobile view for Ukraine project page (#6821)

.github/workflows/push.yml, scripts/ci/generate-chunks.sh
=> feat(ci): support for devops team to bypass tests in emergency situations

apps/judicial-system/backend/src/app/modules/case/case.service.ts, apps/judicial-system/backend/src/app/modules/case/test/extend.spec.ts
[Asana task](https://app.asana.com/0/1199153462262248/1201923711961254/f)
- Copy citizenship with defentands when extending cases
=> fix(judicial-system): copy citizenship form defendant when extending case

libs/application/templates/financial-aid/src/fields/IncomeFilesForm/IncomeFilesForm.tsx, libs/application/templates/financial-aid/src/fields/IncomeForm/IncomeForm.tsx, libs/application/templates/financial-aid/src/forms/Spouse.ts, libs/application/templates/financial-aid/src/lib/FinancialAidTemplate.ts, libs/application/templates/financial-aid/src/lib/constants.ts, libs/application/templates/financial-aid/src/lib/dataSchema.ts, libs/application/templates/financial-aid/src/lib/types.ts
https://app.asana.com/0/1201927126329736/1201672092806031
https://app.asana.com/0/1201927126329736/1201672092806033
- Spouse income page
- Spouse income files page
- Make IncomeForm and IncomeFilesForm components reusable for both applicant and spouse flow
So spouse can put in income information.
=> feat(fa): Spouse income

apps/judicial-system/backend/src/app/modules/case/case.controller.ts, apps/judicial-system/backend/src/app/modules/case/case.service.ts, apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
https://app.asana.com/0/1199153462262248/1201962718337617/f
- Fixes request upload on court case creation,.
Bug
=> fix(judicial-system): Fix Request Upload

.github/workflows/pullrequest-close.yml, .github/workflows/pullrequest-lint.yml, .github/workflows/pullrequest.yml, .github/workflows/push.yml
Adding labels for self-hosted runners so that we can change them out easily. All self hosted runners get the self-hosted label by default, so we need to explicitly say which runner type we want to use. 
=> fix(ci): Adding label for self-hosted runners

apps/services/personal-representative-public/README.md, apps/services/personal-representative/README.md
=> docs(Personal Rep): Update readme

apps/financial-aid/web-osk/src/routes/application/StudentForm/studentForm.tsx
https://app.asana.com/0/1201927126329736/1201927124361793
- text update
- requested
=> fix(fa): Student form text updates

libs/application/template-api-modules/src/lib/modules/templates/mortgage-certificate-submission/mortgage-certificate-submission.service.ts
=> fix(vedbokarvottord): submit request missing property number

workspace.json
Cherry picked: https://github.com/island-is/island.is/pull/6881
=> fix(user-profile): Add email asset path to workspace

apps/services/user-notification/README.md, libs/message-queue/README.md
Adding diagrams to help understand system faster and better
diagrams
help understand system faster and better
```mermaid
sequenceDiagram
autonumber
Institution->>Advania:adds new message in mailbox
Advania->>User-Notification-Service:xroad:sends message notification
User-Notification-Service->>AWS SQS:adds processed notification to queue
loop
User-Notification-Worker->>AWS SQS:requests 10 notifications
AWS SQS->>User-Notification-Worker:responds with 0-10 notifications
end
loop if worker throws an unexpected error, it will try 2 more times with 10 minute interval
User-Notification-Worker->>User-Profile-Service:requests notification settings
User-Profile-Service->>User-Notification-Worker:returns user settings and tokens
end …
```
=> feat(user-notification): System Mermaid Diagrams 

apps/judicial-system/api/src/app/modules/case/dto/updateCase.input.ts, apps/judicial-system/api/src/app/modules/case/interceptors/case.transformer.spec.ts, apps/judicial-system/api/src/app/modules/case/interceptors/case.transformer.ts, apps/judicial-system/api/src/app/modules/case/models/case.model.ts, apps/judicial-system/backend/migrations/20220317140117-update-case.js, apps/judicial-system/backend/src/app/formatters/custodyNoticePdf.ts, apps/judicial-system/backend/src/app/formatters/formatters.spec.ts, apps/judicial-system/backend/src/app/formatters/formatters.ts, apps/judicial-system/backend/src/app/formatters/requestPdf.ts, apps/judicial-system/backend/src/app/modules/case/case.service.ts, apps/judicial-system/backend/src/app/modules/case/dto/updateCase.dto.ts, apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts, apps/judicial-system/backend/src/app/modules/case/models/case.model.ts, apps/judicial-system/backend/src/app/modules/notification/notification.service.ts, apps/judicial-system/backend/test/e2e.spec.ts, apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/courtRecord.spec.ts, apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/hearingArrangements.spec.ts, apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/overview.spec.ts, apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/overview.spec.ts, apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionRequests/overview.spec.ts, apps/judicial-system/web/graphql/sharedGql.ts, apps/judicial-system/web/src/components/DefenderInfo/DefenderInfo.tsx, apps/judicial-system/web/src/components/InfoCard/InfoCard.tsx, apps/judicial-system/web/src/routes/Court/InvestigationRequest/CourtRecord/CourtRecord.tsx, apps/judicial-system/web/src/routes/Court/InvestigationRequest/HearingArrangements/HearingArrangementsForm.tsx, apps/judicial-system/web/src/routes/Court/InvestigationRequest/Overview/OverviewForm.tsx, apps/judicial-system/web/src/routes/Court/RestrictionRequest/Overview/OverviewForm.tsx, apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/Overview/OverviewForm.tsx, apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/Overview/Overview.tsx, apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverviewForm.tsx
[Asana task](https://app.asana.com/0/1199153462262248/1201813931659682/f)
- Remove `defenderIsSpokeperson` from the project
- All logic should be dependant on the session arrangement
=> refactor(judicical-system): remove defenderIsSpokePerson

apps/air-discount-scheme/backend/src/app/modules/user/test/unit/user.service.spec.ts, apps/air-discount-scheme/backend/src/app/modules/user/user.service.ts
Temporarily make 500 requests on forsjá return an empty array (for childless people).
This is not present on main in good faith of resolve before next release.
Otherwise, I will be keepin tabs on this on Monday just in case
=> fix(ads): Temporary National Registry 500 patch

libs/shared/form-fields/src/lib/CompanySearchController/CompanySearchController.tsx, libs/shared/form-fields/src/lib/CompanySearchController/CompanySearchItem.tsx
Removing package kennitala from company controller, it was breaking dev.
=> fix(pdpp): removing kennitala from company

scripts/ci/_retag.sh
=> fix(ci): Faulty variable name in retag script

apps/judicial-system/backend/src/app/modules/case/case.controller.ts, apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/PoliceReport/PoliceReportForm.tsx, apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepThree/StepThree.tsx
https://app.asana.com/0/1199153462262248/1201997385090586/f
- Fixes autofill regression
Bug
=> fix(judicial-system): Fixes autofill regression

apps/judicial-system/backend/src/app/formatters/courtRecordPdf.ts
[Asana task](https://app.asana.com/0/1199153462262248/1201976861524348/f)
- Remove newline in court document pdf.
- It was forgotten in other PR to also update the other case type format #6909
=> fix(judicial-system): remove newline in court doucument pdf

apps/application-system/api/esbuild.json
=> fix(application-system): Adding Pseudomap to dependendcies

apps/services/user-profile/README.md, apps/services/user-profile/src/app/user-profile/e2e/userProfile.spec.ts, apps/services/user-profile/src/app/user-profile/userProfile.controller.ts, apps/services/user-profile/src/app/user-profile/userProfile.service.ts, libs/api/domains/user-profile/src/lib/userProfile.service.ts
CHERRY-PICKS #6948
* created findorcreate method
* findorcreate planted
* removed unused dep
* removed redundant comments
* linter warning cleanup
* updated readme, updated tests
* format gitbook linter
* cleaned up some comments
* removed findorcreate from delete
Co-authored-by: Rafn Árnason <rafnarnason@Rafns-MacBook-Pro.local>
- [] I have added tests that prove my fix is effective or that my feature works
- [] I have rebased against main before asking for a review
=> fix(user-profile): Create user-profiles on updates

libs/application/templates/criminal-record/src/lib/messages.ts, libs/application/templates/mortgage-certificate/src/fields/ConfirmationField/index.tsx, libs/application/templates/mortgage-certificate/src/fields/PendingRejected/index.tsx, libs/application/templates/mortgage-certificate/src/fields/PendingRejectedTryAgain/index.tsx, libs/application/templates/mortgage-certificate/src/fields/SelectProperty/RegisteredProperties/index.tsx, libs/application/templates/mortgage-certificate/src/lib/messages.ts, libs/clients/syslumenn/src/lib/syslumennClient.service.ts
=> fix(mortgage-certificate): Small UI fixes

libs/application/templates/criminal-record/src/forms/CriminalRecordForm.ts, libs/application/templates/mortgage-certificate/src/forms/MortgageCertificateForm.ts, libs/application/templates/mortgage-certificate/src/forms/PaymentInfo.ts, libs/application/templates/mortgage-certificate/src/forms/PendingRejectedTryAgain.ts
=> fix(vedbokarvottod): Fixes so back button in browser works correctly

libs/application/templates/criminal-record/src/lib/messages.ts, libs/application/templates/mortgage-certificate/src/fields/ConfirmationField/index.tsx, libs/application/templates/mortgage-certificate/src/fields/PendingRejected/index.tsx, libs/application/templates/mortgage-certificate/src/fields/PendingRejectedTryAgain/index.tsx, libs/application/templates/mortgage-certificate/src/fields/SelectProperty/RegisteredProperties/index.tsx, libs/application/templates/mortgage-certificate/src/lib/messages.ts
This reverts commit 2df4aa1d9ce72cc0a59fbdfb87dd8a3d3fbe77aa.
=> chore: reverting broken change

libs/application/templates/criminal-record/src/lib/messages.ts, libs/application/templates/mortgage-certificate/src/fields/ConfirmationField/index.tsx, libs/application/templates/mortgage-certificate/src/fields/PendingRejected/index.tsx, libs/application/templates/mortgage-certificate/src/fields/PendingRejectedTryAgain/index.tsx, libs/application/templates/mortgage-certificate/src/fields/SelectProperty/RegisteredProperties/index.tsx, libs/application/templates/mortgage-certificate/src/lib/messages.ts, libs/clients/syslumenn/src/lib/syslumennClient.service.ts, libs/island-ui/core/src/lib/PdfViewer/PdfViewer.css.ts, libs/island-ui/core/src/lib/PdfViewer/PdfViewer.tsx
=> fix(vedbokarvottord): Small UI fixes

apps/application-system/api/src/app.ts, apps/application-system/api/src/interceptors.ts
=> fix(application): add sentry interceptor temporarily

package.json, yarn.lock
=> chore: upgrading ioredis dependency in the hope of getting rid of some annoying errors

.github/workflows/codeql-analysis.yml
=> fix(ci): codeql memory fix

apps/web/components/ServiceWeb/Wrapper/Wrapper.tsx, apps/web/screens/ServiceWeb/Home/Home.tsx, apps/web/screens/ServiceWeb/SubPage/SubPage.tsx, apps/web/screens/queries/ServiceWeb.ts, libs/cms/src/lib/generated/contentfulTypes.d.ts, libs/cms/src/lib/models/organization.model.ts
Cherry-pick merge commit from PR https://github.com/island-is/island.is/pull/6959 to release branch. See the PR for more details on the changes.
=> feat(web): Hotfix - service web featured image

libs/application/templates/parental-leave/src/constants.ts, libs/application/templates/parental-leave/src/fields/Review/Review.tsx, libs/application/templates/parental-leave/src/fields/UseUnion/index.tsx
=> fix(parental-leave): fix id field is required for union

libs/application/templates/parental-leave/src/constants.ts, libs/application/templates/parental-leave/src/fields/Review/Review.tsx, libs/application/templates/parental-leave/src/fields/UseUnion/index.tsx
- fix(parental-leave): fix id field is required for union (#6982)
=> fix(parental-leave): no union from constant

apps/web/components/Project/Header/DefaultProjectHeader.css.ts, apps/web/components/Project/Header/DefaultProjectHeader.tsx, apps/web/screens/Project/Project.tsx, apps/web/screens/queries/Project.tsx, libs/cms/src/lib/generated/contentfulTypes.d.ts, libs/cms/src/lib/models/projectPage.model.ts
Cherry-pick merge commit from PR https://github.com/island-is/island.is/pull/6988 to release branch. See the PR for more details on the changes.
=> feat(web): Hotfix - Project page default header image and text background (#6988)

apps/financial-aid/backend/src/app/modules/application/application.service.ts, libs/application/templates/financial-aid/src/fields/Summary/SpouseSummaryForm.tsx, libs/application/templates/financial-aid/src/fields/Summary/SummaryForm.tsx, libs/application/templates/financial-aid/src/lib/FinancialAidTemplate.ts, libs/application/templates/financial-aid/src/lib/utils.ts
https://app.asana.com/0/1202024607727436/1202025305621757
- Municipality check updated 
- Margin not right in summary 
- Temp fix in db
- Needed  & requested
=> fix(fa): Fixing prereq & margin & mismatch in db

apps/financial-aid/backend/src/app/modules/application/test/create.spec.ts
=> fix(fa): Fix tests

.github/workflows/external-checks.yml, libs/cache/src/lib/cache.ts
Trying to fix the issue with application-system-api failing slots refresh. 2 Sec might be too short, so lets give 3 sec a go
Also temporarily disabling external checks due to dockerhub issues. 
=> fix(ci): Increasing slotsRefreshTimout for ioredis

libs/application/templates/parental-leave/src/constants.ts, libs/application/templates/parental-leave/src/fields/Review/Review.tsx, libs/application/templates/parental-leave/src/fields/UsePrivatePensionFund/index.tsx
=> fix(parental-leave): no private pension constant when no is selected

.github/workflows/config-values.yaml
=> fix(ci): removing unused step and fixing the build

libs/api/domains/user-profile/src/lib/islykill.service.ts, libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/components/Inputs/Email.tsx, libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/components/Inputs/Phone.tsx, libs/service-portal/settings/personal-information/src/components/UserOnboardingModal/UserOnboardingModal.tsx
Cherry picked: https://github.com/island-is/island.is/pull/6974
=> fix(service-portal): onboarding form updates

libs/application/ui-components/src/utilities/formatters.spec.tsx, libs/application/ui-components/src/utilities/formatters.ts
=> fix(parental-leave): overview formatters

.github/workflows/codeql-analysis.yml
=> chore(ci): moving codeql execution back to managed runners

scripts/ci/_nx-affected-targets.sh
=> fix(ci): corner case handling when no files have changed

scripts/ci/_nx-affected-targets.sh
=> fix(ci): fix for a hasty fix

apps/service-portal/src/auth.ts, libs/api/domains/license-service/src/lib/graphql/main.resolver.ts, libs/auth/scopes/src/lib/api.scope.ts
Hotfix the license:verify scope into the release branch from PR #7027 
So the app team can update the scanner app to use this scope.
=> refactor(api): Adding license:verify scope for verify endpoint. (#7027)

.github/workflows/external-checks.yml, apps/web/components/ServiceWeb/Wrapper/Wrapper.tsx, apps/web/screens/ServiceWeb/Home/Home.tsx, apps/web/screens/ServiceWeb/SubPage/SubPage.tsx
Cherry-pick merge commit from PR https://github.com/island-is/island.is/pull/7010 to release branch. See the PR for more details on the changes.
=> feat(web): Service web featured image and dynamic page title

libs/application/template-api-modules/src/lib/modules/templates/p-sign-submission/p-sign-submission.service.ts, libs/application/templates/p-sign/src/fields/UploadedPhoto/index.tsx, libs/application/templates/p-sign/src/forms/application.ts, libs/application/templates/p-sign/src/lib/constants.ts, libs/application/templates/p-sign/src/lib/dataSchema.ts, libs/application/templates/p-sign/src/lib/messages.ts, libs/application/templates/p-sign/src/types.ts
=> fix(p-sign): Schema fixes in P-Sign

.github/workflows/external-checks.yml, apps/web/screens/Article/Article.tsx
Cherry-pick merge commit from PR https://github.com/island-is/island.is/pull/7022 to release branch. See the PR for more details on the changes.
=> feat(web): Added a Ukraine chat panel to an article (#7022)

apps/financial-aid/api/src/app/modules/municipality/municipality.resolver.ts, apps/financial-aid/api/src/services/backend.ts, apps/financial-aid/backend/src/app/modules/municipality/municipality.controller.ts, apps/financial-aid/backend/src/app/modules/municipality/municipality.service.ts, apps/financial-aid/web-veita/graphql/sharedGql.ts, apps/financial-aid/web-veita/src/components/AdminProvider/AdminProvider.tsx, apps/financial-aid/web-veita/src/components/LogoMunicipality/Logo.css.ts, apps/financial-aid/web-veita/src/components/LogoMunicipality/index.tsx, apps/financial-aid/web-veita/src/components/ModalTypes/AcceptModal.tsx, apps/financial-aid/web-veita/src/components/MunicipalityAdminSettings/MunicipalityAdminSettings.tsx, apps/financial-aid/web-veita/src/components/Nav/Nav.css.ts, apps/financial-aid/web-veita/src/components/Nav/Nav.tsx, apps/financial-aid/web-veita/src/components/NewUserModal/NewUserModal.tsx, apps/financial-aid/web-veita/src/components/Profile/ApplicationProfile.tsx, apps/financial-aid/web-veita/src/components/StateModal/StateModal.tsx, apps/financial-aid/web-veita/src/routes/Application/application.tsx, apps/financial-aid/web-veita/src/routes/MunicipalitySettings/municipalitySettings.tsx, libs/financial-aid/shared/src/components/Breakdown/Breakdown.tsx, libs/financial-aid/shared/src/components/hooks/useMunicipality.ts
Reverts island-is/island.is#7030
Needs because dev is broken
=> fix(fa): Revert allow all roles to have multiple municipalities

apps/download-service/infra/download-service.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml
=> fix(download-service): increase available resources

apps/services/user-profile/infra/service-portal-api.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml
- fix(service-portal-api): allow access from identity-server namespace (relevant for Dev and Staging)
- generating value files
=> fix(service-portal-api): open access from IDS namespace

.github/actions/ci-io.ts, .github/actions/dist/index.js
=> fix(ci): change detector to use create events as a fallback when push ones are not present

apps/financial-aid/api/src/app/modules/application/dto/createApplication.input.ts, apps/financial-aid/api/src/app/modules/application/dto/updateApplication.input.ts, apps/financial-aid/api/src/app/modules/application/models/application.model.ts, apps/financial-aid/backend/migrations/20220405154052-update-applications-has-fetched-spouse-and-applicatant-direct-tax.js, apps/financial-aid/backend/src/app/modules/application/dto/createApplication.dto.ts, apps/financial-aid/backend/src/app/modules/application/dto/updateApplication.dto.ts, apps/financial-aid/backend/src/app/modules/application/models/application.model.ts, apps/financial-aid/backend/src/app/modules/application/test/create.spec.ts, apps/financial-aid/backend/src/app/modules/application/test/createEvent.spec.ts, apps/financial-aid/backend/src/app/modules/application/test/getById.spec.ts, apps/financial-aid/web-osk/src/components/AppLayout/AppLayout.tsx, apps/financial-aid/web-osk/src/components/FormProvider/FormProvider.tsx, apps/financial-aid/web-osk/src/components/Summary/DirectTaxPaymentCell.tsx, apps/financial-aid/web-osk/src/routes/application/SummaryForm/spouseSummary.tsx, apps/financial-aid/web-osk/src/routes/application/SummaryForm/summaryForm.tsx, apps/financial-aid/web-osk/src/routes/application/TaxReturnForm/taxReturnForm.tsx, apps/financial-aid/web-osk/src/utils/hooks/useApplication.ts, apps/financial-aid/web-osk/src/utils/hooks/useNavigationTree.ts, apps/financial-aid/web-osk/src/utils/hooks/useTaxData.ts, apps/financial-aid/web-osk/src/utils/hooks/useUpdateApplication.ts, apps/financial-aid/web-veita/graphql/sharedGql.ts, apps/financial-aid/web-veita/src/components/Profile/ApplicationProfile.tsx, apps/financial-aid/web-veita/src/utils/applicationHelper.ts, libs/financial-aid/shared/src/lib/interfaces.ts
https://app.asana.com/0/1202037685216853/1202037685216842
- Migration adding two new booleans to application has fetched for applicant and spouse 
- Added to veita check and show the correct message from direct payments 
- Added to osk when creating and updating to the db 
- Update naming from hasDirectTaxPaymentsSuccess to hasFetchedPayments
- Requested feature
=> feat(fa): Adding boolean on if payments were fetched 

apps/financial-aid/web-veita/src/components/Profile/ApplicationProfile.tsx
https://app.asana.com/0/1202037685216853/1201234405372285
- adding stað to greiðsla 
- requested
=> fix(fa): Fixing minor spelling in veita 

libs/financial-aid/shared/src/lib/taxCalculator.spec.ts, libs/financial-aid/shared/src/lib/taxCalculator.ts
https://app.asana.com/0/1202037685216853/1201878367981449
So the calculations make sense.
Before:
After:
=> fix(fa): Make sure tax allowance is not higher then tax amount

apps/judicial-system/backend/infra/judicial-system-backend.ts, charts/judicial-system/values.dev.yaml, charts/judicial-system/values.prod.yaml, charts/judicial-system/values.staging.yaml
[Asana task](https://app.asana.com/0/1199153462262248/1201714251473992/f)
- Add missing required env for `judicial-system`
- The requirement is defined here: https://github.com/island-is/island.is/blob/main/apps/judicial-system/backend/src/app/modules/case/case.config.ts
=> fix(j-s): add missing required env

apps/financial-aid/web-veita/src/routes/PrintableApplication/printableApplication.tsx, apps/financial-aid/web-veita/src/styles.css
https://app.asana.com/0/1202037685216853/1202070037203638
Fix styling of the print page.
So the attachments don't overlap with the timeline component.
Before: 
After:
=> fix(fa): Fix attachments placement when printing application

libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/components/Inputs/Email.tsx, libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/components/Inputs/Phone.tsx, libs/shared/form-fields/src/lib/InputController/InputController.tsx
- Update code inputs
- Add autocomplete optitons to Inputcontroller
- No need for user to autocomplete their use-once verification code.
- Need to be able to disable the autocomplete on inputcontrollers as with input.
=> feat(service-portal): Update code inputs.

apps/financial-aid/api/src/app/modules/municipality/municipality.resolver.ts
https://app.asana.com/0/1202037685216853/1201234405372285
- Getting cannot return null for non-nullable field graphql apollo error
- mutation return object suppose to return array
=> fix(fa): Update municipality settings fixed

apps/judicial-system/backend/migrations/20220408094933-update-case.js
https://app.asana.com/0/1199153462262248/1202090354163198/f
- Removes deprecated fields from the case table in the database.
The fields are no longer used.
=> chore(j-s): DB Cleanup

libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/emailGenerators/drivingAssessmentApproval.ts
Minor text fix in driving assessment approval email.
=> fix(driving-assessment-application): minor text fix

.github/actions/unit-test/action.yml, .github/workflows/pullrequest.yml, .github/workflows/push.yml
=> fix(ci): Force add yarn to unit-tests

.github/actions/unit-test/action.yml, apps/financial-aid/web-veita/src/components/MultiSelection/MultiSelectionMunicipality.tsx
https://app.asana.com/0/1202037685216853/1202104119935581
- Text update 
- Requested
=> fix(fa): Text update on select

.github/actions/unit-test/action.yml, apps/financial-aid/web-veita/src/utils/applicationHelper.ts
https://app.asana.com/0/1202037685216853/1202037685216824
Add return statement on check function
Bug 🐛
=> fix(fa): Fix long comments bug

apps/judicial-system/api/src/app/modules/file/file.controller.ts
Found when working on:
[Asana](https://app.asana.com/0/1199153462262248/1201386801040044/f)
- Pass in the correct audit action when getting custody notice
=> fix(j-s): fix audit action when getting custody notice

apps/financial-aid/backend/src/app/modules/application/application.controller.ts, apps/financial-aid/backend/src/app/modules/application/application.service.ts
https://app.asana.com/0/1202037685216853/1202088096213656
=> feat(fa): Get only applications from staff munici when filtering

apps/web/screens/Article/Article.tsx, apps/web/screens/Article/config.ts
* Added the Ukraine chat panel to an article
* Reordered the imports for the Article screen
=> feat(web): Ukraine chat panel added to an article

.github/workflows/pullrequest.yml
Trying to support the re-run of e2e tests when failing randomly
=> fix(ci): another attempt to be able to re-run failing e2e tests

infra/src/cli/render-secrets.ts
Update get-secrets to return a special identity server secret for local development.
After this change, when you run `get-secrets` for a project which includes a `IDENTITY_SERVER_CLIENT_SECRET`, you'll instead get the secret for the `@island.is/clients/dev` client, which is configured as a `devFallback` in [IdsClientConfig](https://github.com/island-is/island.is/blob/main/libs/nest/config/src/lib/configurations/IdsClientConfig.ts).
For everything to work you should remove the `IDENTITY_SERVER_CLIENT_ID` variable from your `.env.secret` file or update it to match.
To improve DX and make "get-secrets" just work.
=> chore(core): Fix IDS client credential DX

.github/workflows/config-values.yaml
=> fix(ci): secrets workflow stopped working due to missing nodejs

libs/service-portal/family/src/components/FamilyMemberCard/FamilyMemberCardLoader.tsx
Update loader for family member cards.
Looks good.
=> feat(service-portal): Update family card loader

apps/judicial-system/backend/src/app/formatters/requestPdf.ts
[Asana](https://app.asana.com/0/1199153462262248/1202148289367409/f)
Fix case type condition check in request pdf 
It always displays vistun á viðeigandi stofnun
=> fix(j-s): fix condition check for caseTypea in pdf

apps/judicial-system/backend/src/app/formatters/formatters.spec.ts, apps/judicial-system/backend/src/app/formatters/formatters.ts, apps/judicial-system/backend/src/app/formatters/index.ts, apps/judicial-system/backend/src/app/messages/notifications.ts, apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
[Asana](https://app.asana.com/0/1199153462262248/1202148289367416/f)
- Fix body and subject for email sent out to prosecutors when a case is ready for court
=> fix(j-s): fix ready for court mail sent to prosector

package.json, yarn.lock
Update dd-trace library.
Hoping this fixes a memory leak in production services and improves performance and trace quality.
=> chore(deps): Upgrade dd-trace

apps/web/components/Regulations/DiffModeToggle.tsx, apps/web/components/Regulations/HistoryStepper.tsx, apps/web/components/Regulations/RegulationChangelog.tsx, package.json, yarn.lock
* feat: show all impacts in history list
Already merged to main and tested here:
https://beta.dev01.devland.is/reglugerdir/nr/0580-2021
=> feat(regulations): hotfix show all impacts in history list (#7194)

package.json, yarn.lock
Hoping this fixes a memory leak in production services and improves performance and trace quality.
[Attach a link to issue if relevant](https://github.com/island-is/island.is/pull/7187)
=> chore(deps): Upgrade dd-trace (#7187)

apps/judicial-system/web/src/routes/Court/InvestigationCase/Ruling/Ruling.tsx
https://app.asana.com/0/1199153462262248/1202166761828496/f
- Adds missing import for useState.
Bug
=> fix(j-s): Fixes Investigation Ruling

libs/application/templates/general-fishing-license/src/lib/GeneralFishingLicenseTemplate.ts
=> fix(gfl): missing ready for production

libs/application/templates/parental-leave/src/lib/directorateOfLabour.utils.spec.ts, libs/application/templates/parental-leave/src/lib/directorateOfLabour.utils.ts
=> fix(parental-leave): tax percentage calculator

apps/application-system/form/src/routes/Applications.tsx, libs/application/ui-shell/src/lib/ApplicationForm.tsx
Removing user profile logic
There is a bug in the code.
=> fix(application-system): Hotfix/remove userprofile locale logic

apps/judicial-system/web/messages/Core/restrictions.ts, apps/judicial-system/web/messages/Core/sections.ts, apps/judicial-system/web/messages/Core/signedVerdictOverview.ts, apps/judicial-system/web/messages/RestrictionCases/Court/confirmation.ts
- Fix contentful extract string errors
- Invalid namespace fixed `judicial.system.core:sections:title`
- Duplicate id's
- Remove some `defineMessage`
- Fix curly braket alignment
=> fix(j-s): fix contentful upload errors

libs/application/templates/driving-license/src/lib/messages.ts
=> fix(driving-license): title touch up

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/assignEmployerEmail.ts, libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/assignOtherParentEmail.ts
update email template for employer- and spouse approval
https://dit-iceland.atlassian.net/jira/software/projects/UUFV/boards/71?assignee=611f732728ae75006aec3c1f&selectedIssue=UUFV-45
=> feat(parental-leave): Update spouse/employer email template

apps/web/README.md, apps/web/next.config.js, apps/web/utils/featureFlag/featureFlag.spec.ts, apps/web/utils/featureFlag/featureFlag.ts, apps/web/utils/featureFlag/index.ts
Cherry-pick merge commit from PR https://github.com/island-is/island.is/pull/7188 to release branch. See the PR for more details on the changes.
=> feat(web): Hotfix - Feature flag support for web (#7188)

apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
[Asana](https://app.asana.com/0/0/1202203502621819/f)
- Add missing param to contentful string
=> fix(j-s): add missing param to contentful string

libs/nest/swagger/README.md
Devs have been trying to import from `@nestjs/common`
=> chore(swagger): specify what to import in docs

libs/application/templates/parental-leave/src/lib/directorateOfLabour.utils.spec.ts, libs/application/templates/parental-leave/src/lib/directorateOfLabour.utils.ts
* Fix(parental-leave): tax percentage calculator
* fix(parental-leave): format
* fix(parental-leave): fix test case
=> fix(parental-leave): tax percentage calculator (#7235)

apps/service-portal/src/components/GlobalModules/GlobalModules.tsx, apps/service-portal/src/hooks/useNavigation/useNavigation.ts, apps/service-portal/src/hooks/useRoutes/useRoutes.ts, apps/service-portal/src/screens/Dashboard/Dashboard.tsx, apps/service-portal/src/screens/Modules/Modules.tsx, apps/service-portal/src/utils/http.ts, libs/auth/react/src/lib/AuthSettings.spec.ts, libs/auth/react/src/lib/AuthSettings.ts, libs/auth/react/src/lib/Authenticator/Authenticator.mocked.spec.tsx, libs/auth/react/src/lib/Authenticator/Authenticator.spec.tsx, libs/auth/react/src/lib/Authenticator/Authenticator.tsx, libs/auth/react/src/lib/getAccessToken.ts, libs/auth/react/src/lib/userManager.ts, libs/service-portal/core/src/lib/service-portal-core.ts, libs/service-portal/core/src/utils/utils.ts, libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx, libs/service-portal/documents/src/screens/Overview/Overview.tsx, libs/service-portal/finance/src/components/DocumentScreen/DocumentScreen.tsx, libs/service-portal/finance/src/components/FinanceStatusDetailTable/FinanceStatusDetailTable.tsx, libs/service-portal/finance/src/components/FinanceStatusTableRow/FinanceStatusTableRow.tsx, libs/service-portal/finance/src/screens/FinanceBills/FinanceBills.tsx, libs/service-portal/finance/src/screens/FinanceEmployeeClaims/FinanceEmployeeClaims.tsx, libs/service-portal/finance/src/screens/FinanceLocalTax/LocalTax.tsx, libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx, libs/shared/types/src/lib/user.ts, libs/testing/fixtures/src/lib/openIDUser.ts, package.json, yarn.lock
Hotfixing release with PR #7238 
To fix time sensitive issue in prod.
=> chore(core): Update oidc-client library (#7238)

apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/CaseFiles/CaseFilesForm.tsx
https://app.asana.com/0/1199153462262248/1202211680145816/f
- Fixes incorrect usage of MarkdownWrapper
Bug
=> fix(j-s): Fix Markdown Error

libs/application/templates/parental-leave/src/lib/directorateOfLabour.utils.ts
=> fix(parental-leave): fix tax calculator on new year

libs/application/templates/parental-leave/src/lib/messages.ts
Removing optional text, since the field is required.
=> fix(parental-leave): copy for pension fund

charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml, charts/judicial-system/values.dev.yaml, charts/judicial-system/values.prod.yaml, charts/judicial-system/values.staging.yaml, infra/src/dsl/hpa.spec.ts, infra/src/dsl/map-to-values.ts, infra/src/dsl/types/input-types.ts, infra/src/dsl/types/output-types.ts
This is to support this [issue](https://github.com/island-is/helm/pull/627)
Provide a way to configure the irate configuration for services. Not ready for general consumption just yet.
=> feat: configuration DSL supports the new rendering of the HPA, which supports ingress metric scaling

libs/api/domains/driving-license-book/src/drivingLicenseBook.resolver.ts, libs/api/domains/driving-license-book/src/guards/drivingInstructorOrEmployee.guard.ts
A special guard for employee and instructor mutual endpoints in the driving license book.
=> fix(driving-license-book): Mutual guard for employees and instructors

apps/judicial-system/api/src/app/modules/case/restrictedCase.resolver.ts, apps/judicial-system/backend/src/app/modules/case/guards/test/restrictedCaseExistsGuard.spec.ts, apps/judicial-system/backend/src/app/modules/case/restrictedCase.service.ts, apps/judicial-system/web/src/components/FormProvider/restrictedCaseGql.ts, apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverviewForm.tsx
https://app.asana.com/0/1199153462262248/1201993600333872/f
- Fixes various issues discovered during acceptance testing.
=> fix(j-s): Fix Defender View

apps/web/components/Organization/Wrapper/config.ts, apps/web/screens/Article/components/ArticleChatPanel/ArticleChatPanel.tsx, apps/web/screens/Article/components/ArticleChatPanel/config.ts
* Changed the watson id for the sýslumenn chat panel
* This was requested
=> feat(web): Sýslumenn chat panel change

apps/web/components/Organization/Wrapper/config.ts, apps/web/screens/Article/components/ArticleChatPanel/ArticleChatPanel.tsx, apps/web/screens/Article/components/ArticleChatPanel/config.ts
Cherry-pick merge commit from PR https://github.com/island-is/island.is/pull/7351 to release branch. See the PR for more details on the changes.
=> feat(web): Sýslumenn chat panel change (#7351)

libs/application/templates/general-fishing-license/src/dataProviders/generalFishingLicenseProvider.ts
=> fix(general-fishing-license): hotfix remove logger

libs/application/templates/general-fishing-license/src/dataProviders/generalFishingLicenseProvider.ts
Logger will hinder user from getting through!
=> fix(general-fisihing-license): fixing logger

libs/service-portal/vehicles/src/queries/getUsersVehicleDetail.ts, libs/service-portal/vehicles/src/queries/getUsersVehicles.ts, libs/service-portal/vehicles/src/screens/Overview/Overview.tsx
Fixing after rename merge conflict
Changing query names
=> fix(service-portal): fixing vehicles graphql errors

libs/service-portal/vehicles/src/queries/getUsersVehicleDetail.ts, libs/service-portal/vehicles/src/queries/getUsersVehicles.ts, libs/service-portal/vehicles/src/screens/Overview/Overview.tsx
=> fix(service-portal): fixing vehicles graphql errors (#7366)

libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts, libs/application/templates/parental-leave/src/lib/messages.ts
=> feat(parental-leave): translating using Contentful

apps/judicial-system/web/pages/_document.tsx, apps/judicial-system/web/src/components/PageHeader/PageHeader.tsx, apps/judicial-system/web/src/components/PageLayout/PageLayout.css.ts, apps/judicial-system/web/src/components/PageLayout/PageLayout.tsx, libs/island-ui/core/src/lib/FormStepper/FormStepper.tsx, libs/island-ui/core/src/utils/responsiveProp.ts
[Asana](https://app.asana.com/0/1199153462262248/1202238311264768/f)
- Make stepper responsive
https://user-images.githubusercontent.com/5700902/167681063-503d29d2-b465-49ed-8dec-7119809fc59d.mov
=> feat(j-s): mobile stepper

charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml, infra/src/dsl/xroad.ts, libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts, libs/service-portal/vehicles/src/components/VehicleCard.tsx
🔥  HOTFIX 🔥 
* Fix wrong prod path for vehicles xroad 
* Fix mismatch in id lookup
* Add logs
=> fix(service-portal): vehicles wrong path + add logs

charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml, infra/src/dsl/xroad.ts, libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts, libs/service-portal/vehicles/src/components/VehicleCard.tsx
🔥  HOTFIX --> See #7379 
* fix: wrong path + add logs
* fix: simpler log
* fix: mismatch on vehicle number
* fix: update yaml files
=> fix(service-portal): HOTFIX vehicles wrong path + add logs (#7379)

apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
https://app.asana.com/0/1199153462262248/1202236422368718/f
- Send an updated custody notice to prison when custody or isolation length is modified.
The prison needs to be informed.
=> feat(j-s): Updated Custody Notice

libs/clients/middlewares/src/lib/createEnhancedFetch.ts, libs/clients/middlewares/src/lib/e2e/enhancedFetch.spec.ts
Hotfixing release with the enhancedFetch timeout issue fix.
To fix bug in the Child Residence Change application.
=> fix(core): Fixing timeout bug in enhancedFetch. (#7392)

apps/judicial-system/web/tsconfig.app.json, apps/judicial-system/web/tsconfig.json
https://app.asana.com/0/1199153462262248/1202212024251105/f
- Rewrites `tsconfig` files so the build catches `typescript` errors.
Typescript errors were not caught in the ci/cd pipeline.
=> fix(j-s): Fix Client Build

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx, apps/web/components/Organization/Wrapper/Themes/SyslumennTheme/SyslumennFooter.tsx, apps/web/context/GlobalContext/GlobalContext.tsx, apps/web/layouts/main.tsx
Cherry-pick merge commit from PR https://github.com/island-is/island.is/pull/7387 to release branch. See the PR for more details on the changes.
=> feat(web): Hotfix - Sýslumenn footer links to support page

apps/web/layouts/main.tsx, libs/island-ui/core/src/lib/Footer/Footer.tsx
Cherry-pick merge commit from PR https://github.com/island-is/island.is/pull/7400 to release branch. See the PR for more details on the changes.
=> feat(web): Hotfix - Web footer links to support page

libs/application/templates/financial-aid/src/lib/FinancialAidTemplate.ts
https://app.asana.com/0/1202167941440767/1202244723867086
Change flag to true
So the financial aid application can be seen and tested on production.
=> feat(fa): Change readyForProduction flag to trur

libs/api/domains/communications/src/lib/emailTemplates/serviceWebForms.ts
Cherry pick commit from PR #7388
=> chore(web): Hotfix - Updated Sýslumenn's email list (#7388)

libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts, libs/application/templates/parental-leave/src/forms/Prerequisites.ts, libs/application/templates/parental-leave/src/lib/messages.ts
=> fix(parental-leave): Translate in Contentful

apps/web/components/ServiceWeb/Forms/StandardForm/StandardForm.tsx, apps/web/screens/ServiceWeb/Forms/Forms.tsx
* Added a checkbox to the forms on the service web
* Added the email of the sender to the message
=> feat(web):  Service web form checkbox and template update

libs/application/templates/parental-leave/src/fields/Review/Review.tsx, libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
Filtering out private pension funds with the value of X000 to avoid issues with validation.
=> fix(parental leave): filter private pension fund

package.json, yarn.lock
Feature flags broken after recent yarn lock changes.
Rollback to previous yarn lock file
How to reproduce: [Go to minar-sidur](https://beta.dev01.devland.is/minarsidur/) and watch the load time of sidebar. The render of the sidebar depends on the feature flags to have been resolved.
The feature flags have slowed down for some reason.
this.configcat.getValueAsync() seems to be really slow.
=> fix(core): feature flag bugs

libs/api/domains/vehicles/src/lib/api-domains-vehicles.resolver.ts
Vehicle resolver can return null if no data or error.
=> fix(service-portal): vehicles resolver nullable

libs/application/templates/parental-leave/src/fields/Review/Review.tsx, libs/application/templates/parental-leave/src/fields/UseUnion/index.tsx, libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts, libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts, libs/application/templates/parental-leave/src/lib/answerValidators.ts
=> fix(parental-leave): union validation

libs/clients/rsk/personal-tax-return/src/lib/personalTaxReturn.config.ts
The tax people just update their tax url, so we need to update on our end as well.
This PR is just updating the devFallback env variable. Andes will update the env for systems in deployment.
=> fix(fa): Update tax url

apps/web/components/Organization/Wrapper/Themes/MannaudstorgTheme/MannaudstorgFooter.css.ts, apps/web/components/ServiceWeb/Background/Variations/Mannaudstorg/Mannaudstorg.css.ts
Cherry-pick merge commit from PR https://github.com/island-is/island.is/pull/7460 to release branch. See the PR for more details on the changes.
=> feat(web): Hotfix - mannaudstorg service web header change

apps/judicial-system/web/src/components/CaseFileList/CaseFileList.tsx
https://app.asana.com/0/1199153462262248/1202067841576045/f
- Sýnir aftur checkmark við rannsóknargögn sem hlaðið hefur verið í Auði (hjá dómara og dómritara).
Regression
=> fix(j-s): Fix Missing Upload Checkmark

handbook/misc/application-system-org-requests.md
=> docs(application-system): fixes to readme

libs/application/templates/parental-leave/src/fields/Review/Review.tsx, libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
=> fix(parental-leave): fix other parent could not choose personal discount

libs/application/template-api-modules/src/lib/modules/templates/health-insurance/health-insurance.service.ts
=> fix(health-insurance): remove error object

libs/application/core/src/lib/messages.ts, libs/application/ui-shell/src/components/FormExternalDataProvider.tsx
Hotfix error dataprovider error on submit needed for greiðslu áætlun application
=> chore(application-system): Replace error in dataprovider

.github/CODEOWNERS
Make team kolibri-robin-hood the codeowners of the financial-aid template api project.
=> feat(fa): Add project to robin hood codeowner list

apps/service-portal/src/hooks/useModules/useModules.ts, apps/service-portal/src/hooks/useRoutes/useRoutes.ts, apps/service-portal/src/screens/Modules/Modules.tsx, libs/api/domains/user-profile/src/lib/userProfile.service.ts, libs/service-portal/finance-schedule/src/index.ts, libs/service-portal/finance-schedule/src/screens/FinanceSchedule/FinanceSchedule.tsx
Cherry picked:
* https://github.com/island-is/island.is/pull/7519
* https://github.com/island-is/island.is/pull/7521
* https://github.com/island-is/island.is/pull/7522
=> fix(service-portal): Hotfix - Company finance

apps/web/components/ChatPanel/BoostChatPanel/BoostChatPanel.tsx, apps/web/components/ChatPanel/ChatBubble/ChatBubble.tsx
Cherry pick commit from (#7533)
=> feat(web): Hotfix - Pushed the Chat bubble up in the mobile view 

libs/island-ui/core/src/lib/Grid/GridContainer/GridContainer.css.ts
Cherry pick commit from (#7530 )
=> feat(web): Hotfix - GridContainer side padding added back in mobile

libs/application/core/README.md
Added to readme how to add custom error reason
Improved DX.
=> chore(application system): Added to readme how to add custom error reason

infra/package.json, infra/yarn.lock
=> fix(ci): Fixing helm-docker-build step in CI

libs/application/templates/parental-leave/src/lib/messages.ts
Fix text
https://dit-iceland.atlassian.net/jira/software/projects/UUFV/boards/71?selectedIssue=UUFV-77
=> fix(parental-leave): text changes for other parent approval

apps/judicial-system/api/infra/judicial-system-api.ts, apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/signedVerdictOverview.spec.ts, apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/signedVerdictOverview.spec.ts, apps/judicial-system/web/src/components/FeatureProvider/FeatureProvider.tsx, apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverviewForm.tsx, charts/judicial-system/values.prod.yaml, charts/judicial-system/values.staging.yaml, libs/judicial-system/types/src/lib/feature.ts
[Asana - feature flag Leiðrétta úrskurð](https://app.asana.com/0/1199153462262248/1202360581950457/f)
- But Leiðrétta button under feature flag
=> feat(j-s): feature flag modify ruling button

apps/judicial-system/backend/src/app/messages/notifications.ts, apps/judicial-system/backend/src/app/modules/case/case.service.ts
[Verjendur fá link í tölvupósti þó þeir hafi ekki aðgang í RVG](https://app.asana.com/0/1199153462262248/1202363752281264/f)
- Fixes defender email when defender national id is not recorded
Bug
=> fix(j-s): Fix Defender Email

libs/application/templates/financial-aid/src/fields/Status/Estimation/Estimation.tsx, libs/application/templates/financial-aid/src/lib/utils.ts
https://app.asana.com/0/1202167941440767/1202088096213673
Add a check for cohabitation (that is when the applicant has spouse from þjóðskrá but they are not married)
=> fix(fa): Check on cohabitation

apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.resolver.ts, apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts
=> fix(skilavottord): add more logs (#7586)

libs/api/domains/driving-license/src/lib/drivingLicense.spec.ts, libs/application/templates/driving-license/src/lib/messages.ts, libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts, libs/clients/driving-license/src/lib/drivingLicenseApi.types.ts, libs/clients/driving-license/src/v2/clientConfig.json
* if resubmission for temp needed 400 error with error code does not map correctly so recheck can apply for.. and message update
* rm yarn changes
* throw error if not resubmit error
* test fixing
* format
* lock
=> fix(driving-license-servive): Handle temporary license resubmit (#7560)

libs/application/templates/parental-leave/src/lib/directorateOfLabour.utils.spec.ts, libs/application/templates/parental-leave/src/lib/directorateOfLabour.utils.ts
* fix/parental-leave: fix rights calculator
* fix(parental-leave): fix test cases
=> fix(parental-leave): fix rights calculator (#7609)

apps/web/screens/Organization/Syslumenn/Homestay.tsx
Cherry pick commit from (#7627)
=> fix(web): Hotfix - Removed unused runtime config from Homestay page (#7627)

apps/web/screens/Organization/Syslumenn/Homestay.tsx, libs/api/domains/driving-license/src/lib/__mock-data__/requestHandlers.ts, libs/clients/driving-license/README.md, libs/clients/driving-license/src/lib/drivingLicenseApi.config.ts
=> fix(driving-license): Fix env names

apps/application-system/api/esbuild.json
Missing dependencies for conficat causing errors like 'missing p-cancellable' 
=> fix(application-system): Adding conficat dependencies

.github/workflows/config-values.yaml
=> fix(ci): Config Values run on release branch creation

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.module.ts, libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.spec.ts, libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts, libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.ts, libs/application/templates/parental-leave/src/fields/Review/Review.tsx, libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts, libs/application/templates/parental-leave/src/lib/dataSchema.ts, libs/application/templates/parental-leave/src/lib/messages.ts, libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Sending sms when the form is to be reviewed by the employer 
=> feat(parental  leave): add sms notification to employer on form submit

apps/judicial-system/xrd-api/infra/judicial-system-xrd-api.ts, charts/judicial-system/values.dev.yaml, charts/judicial-system/values.prod.yaml, charts/judicial-system/values.staging.yaml
=> fix(j-s): Updates Helm Charts

apps/services/contentful-entry-tagger/infra/contentful-entry-tagger-service.ts, apps/services/contentful-entry-tagger/src/app/app.controller.ts, apps/services/contentful-entry-tagger/src/app/app.middleware.ts, apps/services/contentful-entry-tagger/src/app/app.module.ts, apps/services/contentful-entry-tagger/src/app/health.controller.ts, apps/services/contentful-entry-tagger/src/main.ts, charts/islandis/values.dev.yaml
=> fix(contentful-entry-tagger): Health checks for contentful-entry-tagging service

libs/auth/react/src/lib/AuthSettings.spec.ts, libs/auth/react/src/lib/AuthSettings.ts
Hotfix PR #7657 
To fix regression in auth-react which creates infinite user sessions.
=> fix(auth-react): HOTFIX Auth React automatic token refresh

libs/application/templates/announcement-of-death/src/dataProviders/ExistingApplicationProvider.ts, libs/application/templates/announcement-of-death/src/fields/ExistingApplication/LinkExistingApplication.tsx
=> feat(aod): Revised Existance logic

apps/services/user-profile/src/app/user-profile/e2e/userProfile.spec.ts, apps/services/user-profile/src/app/user-profile/userProfile.controller.ts, apps/services/user-profile/src/app/user-profile/verification.service.ts, libs/api/domains/user-profile/src/lib/userProfile.service.ts, libs/service-portal/core/src/hooks/useDynamicRoutes/useDynamicRoutes.ts, libs/service-portal/graphql/src/hooks/profile/useUpdateOrCreateUserProfile.ts
Hotfix:
https://github.com/island-is/island.is/pull/7652
https://github.com/island-is/island.is/pull/7626
=> fix(service-portal): Settings and minor finance

libs/service-portal/vehicles/src/components/DetailTable/FeeInfoItem.tsx, libs/service-portal/vehicles/src/screens/VehicleDetail/VehicleDetail.tsx
hotfix: https://github.com/island-is/island.is/pull/7669
=> fix(service-portal): Hide insurance

apps/api/infra/api.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml, libs/application/templates/no-debt-certificate/src/dataProviders/NoDebtCertificateProvider.ts, libs/application/templates/no-debt-certificate/src/lib/messages.ts, libs/clients/finance/src/lib/FinanceClientConfig.ts, libs/clients/finance/src/lib/FinanceClientService.ts
These PR into release branch:
https://github.com/island-is/island.is/pull/7588
https://github.com/island-is/island.is/pull/7667
=> fix(skuldleysisvottord): fix error message and increase timeout (again)

.github/workflows/push.yml
Get IDS deployment in island-is
auth-api needs to be deployed by CD
=> feat(infra): Add deployment step for IDS

.github/workflows/push.yml
This reverts commit 6e9efe2900bec6440b813066da65de822e60ddb0.
=> fix(infra): Revert "Add deployment step for IDS"

libs/service-portal/information/src/components/ChildView/ChildView.tsx, libs/service-portal/information/src/lib/messages.ts, libs/service-portal/information/src/screens/UserInfo/UserInfo.tsx
* Add bannmerking button to information
* Add tooltip for family number
* Add change legal resident to child view (if not logged in as child)
* Remove "ókvænt" from marital status
Comments from Þjóðskrá
=> feat(service-portal): add profile information

apps/judicial-system/backend/src/app/modules/case/case.controller.ts
[Disable Functionality](https://app.asana.com/0/1202283346413052/1202372137781449/f)
Temporarily disables queuing while AWS setup is finalized.
Don't want to stop the delivery pipeline.
=> chore(j-s): Disable Queuing

libs/cms/src/lib/cms.resolver.ts
Cherry-pick merge commit from PR https://github.com/island-is/island.is/pull/7719 to release branch. See the PR for more details on the changes.
=> feat(web): Added support for fetching english related articles (#7719)

libs/api/domains/vehicles/README.md, libs/api/domains/vehicles/src/lib/api-domains-vehicles.resolver.ts, libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts
Add more details to vehicle logging. How to run readme
Better logging + better readme = happier developers. 😄
=> chore(service-portal): Add more details to vehicle logging

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts, libs/application/templates/parental-leave/src/lib/answerValidators.spec.ts, libs/application/templates/parental-leave/src/lib/answerValidators.ts
=> fix(parental leave): period and other parent bugs

libs/application/templates/parental-leave/src/types.ts
=> fix(parental-leave): change otherParent type (#7756)

apps/services/auth-api/infra/auth-api.ts, charts/identity-server/values.prod.yaml
=> fix(infra): Auth-api using wrong configuration

.github/workflows/push.yml
=> fix(ci): Fix IDS deployment

apps/auth-admin-web/infra/auth-admin-web.ts, apps/services/auth-api/infra/auth-api.ts, apps/services/auth-api/infra/identity-server.ts, apps/services/personal-representative/infra/personal-representative.ts, charts/identity-server/values.dev.yaml, charts/identity-server/values.prod.yaml, charts/identity-server/values.staging.yaml, infra/src/dsl/ingress.spec.ts, infra/src/dsl/map-to-values.ts
=> fix(infra): IDS DSL and configuration fixes

apps/web/components/Login/LoginTexts.types.ts, apps/web/screens/Login/Login.tsx
Add link to contentful json
Replace link because of redirect
=> fix(service-portal): login old url

apps/system-e2e/cypress.env.json, apps/system-e2e/src/integration/service-portal/homepage.spec.ts, apps/system-e2e/src/integration/web/homepage.spec.ts, apps/system-e2e/src/support/commands.ts, apps/system-e2e/src/support/index.d.ts, apps/web/components/Card/Card.tsx, apps/web/components/IconTitleCard/IconTitleCard.tsx, apps/web/components/LanguageToggler/LanguageToggler.tsx, apps/web/components/Menu/Menu.tsx, apps/web/components/SearchSection/SearchSection.tsx, libs/island-ui/core/src/lib/Link/Link.tsx, libs/island-ui/core/src/lib/Menu/Menu.tsx
=> fix: added cypress.env.json, added missing tests

libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts, libs/application/templates/parental-leave/src/lib/messages.ts
Adding max size file upload error to parental leave
=> feat(parental leave): file upload max size error

libs/clients/islykill/src/clientConfig.yaml
hotfix: https://github.com/island-is/island.is/pull/7796
=> chore(service-portal): hotfix - Update client config in islyklar service

apps/system-e2e/cypress.env.json, apps/system-e2e/src/integration/service-portal/homepage.spec.ts, apps/system-e2e/src/integration/web/homepage.spec.ts, apps/system-e2e/src/plugins/index.js, apps/system-e2e/src/support/commands.ts, apps/web/components/Card/Card.tsx
=> fix: fixing envs and session

apps/system-e2e/src/integration/web/search.spec.ts
=> fix(ci): search feature e2e tests

apps/service-portal/src/auth.ts
Adding missing `ApiScope.licenses` in the requested scopes.
Changed the licenses module to use the licenses scope instead of the internal scope in PR #7793 but forgot this.
=> fix(service-portal): Adding missing licenses scope in requested scopes.

apps/judicial-system/backend/src/app/modules/case/case.module.ts
=> chore(j-s): Disable Queuing on Backend

apps/skilavottord/web/next.config.js, apps/skilavottord/web/pages/_app.tsx
=> infra(skilavottord): adding DataDog RUM integration to frontend

libs/api/domains/auth/src/lib/resolvers/delegation.resolver.ts, libs/api/domains/identity/src/lib/identity.resolver.ts, libs/api/domains/identity/src/lib/identity.service.ts, libs/api/domains/national-registry-x-road/src/lib/nationalRegistryXRoad.resolver.ts, libs/api/domains/national-registry-x-road/src/lib/nationalRegistryXRoad.service.ts
Hotfix prod with PR #7718 
Release the fallback handling in the identity service to prod.
=> fix(api): hotfix - Provide getIdentityWithFallback method in identity service (#7718)

apps/api/infra/api.ts, apps/services/auth-api/infra/auth-api.ts, charts/identity-server/values.dev.yaml, charts/identity-server/values.prod.yaml, charts/identity-server/values.staging.yaml, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml
=> chore(infra): increase resources for api and auth-api

apps/service-portal/src/auth.ts, libs/api/domains/education/src/lib/graphql/main.resolver.ts, libs/api/domains/license-service/src/lib/graphql/main.resolver.ts, libs/auth-api-lib/seeders/data/scope-education-license.ts, libs/auth/scopes/src/lib/api.scope.ts, libs/service-portal/education-license/src/index.ts, libs/service-portal/licenses/src/index.ts
Hotfix PR #7793 
Enable education-license and license menus in prod for legal guardian.
=> feat(service-portal): Adding scopes to enable education-license and license for legal guardian

libs/application/templates/institution-collaboration/src/fields/ReviewScreen/ReviewScreen.tsx, libs/application/templates/institution-collaboration/src/forms/application.ts, libs/application/templates/institution-collaboration/src/lib/template.ts, libs/clients/data-protection-complaint/src/lib/data-protection-complaint.module.ts
Implement the new company search in to the application flow instead of making the user type the company name manually.
Increase timeout for data-protection-comlpaint-client to 60 sec
More fool proof design and prevents errors / misunderstanding
Client timed out sometimes, trying 60 sec for solution.
=> feat(applications-institution-collaboration): Add company search into the form flow

libs/application/ui-shell/src/components/ScreenFooter.tsx
=> fix(application-system): Button spacing

libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
=> fix(parental-leave): get otherParent values

apps/services/user-profile/src/app/user-profile/e2e/userProfile.spec.ts, libs/application/templates/financial-aid/src/fields/Logo/Logo.css.ts
https://app.asana.com/0/1202167941440767/1202412116438909
Make the logo align with the "Halda áfram" button below it.
=> fix(fa): Fix alignment of logo

apps/services/personal-representative-public/infra/personal-representative-public.ts, apps/services/personal-representative/infra/personal-representative.ts, charts/identity-server/values.dev.yaml, charts/identity-server/values.prod.yaml, charts/identity-server/values.staging.yaml
=> fix(personal-rep): DB connection fix after ingres changes

apps/services/personal-representative-public/infra/personal-representative-public.ts, apps/services/personal-representative/infra/personal-representative.ts, charts/identity-server/values.dev.yaml, charts/identity-server/values.prod.yaml, charts/identity-server/values.staging.yaml
Recent ingres changes caused missing db connection. Sholud be fixed with these changes.
=> fix(personal-rep): HOTFIX - DB connection fix after ingres changes

apps/system-e2e/src/integration/web/homepage.spec.ts, scripts/ci/Dockerfile.cypress
Cypress is not getting resolved as a node module, so it is now a local module
=> test(system-e2e): Moving cypress to the correct location

apps/system-e2e/src/integration/web/homepage.spec.ts
Language toggler test case was broken. This PR fixes the test case.
=> fix(qa): Fix broken language-toggler test case

libs/service-portal/core/src/lib/messages.ts, libs/service-portal/documents/src/screens/Overview/Overview.tsx, libs/service-portal/documents/src/utils/messages.ts, libs/service-portal/finance/src/components/DocumentScreen/DocumentScreen.tsx, libs/service-portal/finance/src/screens/Finance.css.ts, libs/service-portal/finance/src/screens/FinanceTransactions/FinanceTransactions.tsx
* Move date fields and category select to the filter in finance section
Cleaner look
=> feat(service-portal): Add finance filter

apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
[Opna aftur á vistun fyrirtökuboða í Auði](https://app.asana.com/0/1199153462262248/1202426975388868/f)
- Only uploads invitation emails to court
- Invitation emails are really what the court wants.
- Uploading emails to the prison was causing problems.
=> chore(j-s): Email Upload to Court Iteration

charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml, infra/src/dsl/xroad.ts, libs/clients/adr-and-machine-license/src/lib/adr-and-machine-license.config.ts, workspace.json
Fixing the service paths, they were wrong
Querying the wrong place
=> fix(service-portal): Correct xroad paths for Adr and Machine license clients

charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml, infra/src/dsl/xroad.ts, libs/clients/adr-and-machine-license/src/lib/adr-and-machine-license.config.ts, workspace.json
=> fix(service-portal): adr machine client xroad path fix

libs/service-portal/vehicles/src/components/DetailTable/FeeInfoItem.tsx, libs/service-portal/vehicles/src/screens/VehicleDetail/VehicleDetail.tsx
Remove insured status - error in service
=> fix(service-portal): remove insurace again

apps/service-portal/src/components/MobileMenu/MobileMenu.tsx, libs/service-portal/settings/access-control/src/components/Accesses/Accesses.tsx, libs/shared/components/src/auth/UserMenu/UserMenu.spec.tsx, libs/shared/translations/src/lib/user.ts
* Change "skipta um umboð" to "skipta um notanda" 
* Add logout text to mobile menu
=> fix(service-portal): tiny text hotfixes

libs/service-portal/information/src/lib/queries/getNationalRegistryUser.ts, libs/service-portal/information/src/screens/UserInfo/UserInfo.tsx
Add fullname display as name from Þjóðskrá
Source of truth for the full name of an individual comes from Þjóðskrá
=> fix(service-portal): Add fullname display as name from thjodskra

libs/service-portal/finance/src/screens/FinanceTransactions/FinanceTransactions.tsx
Add multi select filter to finance transactions
Add extra support to filters.
=> feat(service-portal): Add multi filter to finance transactions

apps/web/components/Organization/Slice/EventSlice/EventSlice.css.ts, apps/web/components/Organization/Slice/EventSlice/EventSlice.tsx, apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
=> feat(web): Hotfix - Update event slice for 2022 conference

apps/web/screens/Article/components/ArticleChatPanel/ArticleChatPanel.tsx, apps/web/screens/Article/components/ArticleChatPanel/config.ts
Cherry pick commit from #7996 so we can hotfix these changes in
=> chore(web): Hotfix - Stop showing Watson chat on some articles (#7996)

apps/judicial-system/message-handler/infra/judicial-system-message-handler.ts, apps/judicial-system/message-handler/src/app/app.module.ts, apps/judicial-system/message-handler/src/app/health.controller.ts, apps/judicial-system/message-handler/src/main.ts, charts/judicial-system/values.dev.yaml, workspace.json
[Vista gögn sjálfkrafa í Auði eftir afgreiðslu ef þau hafa ekki verið vistuð](https://app.asana.com/0/1199153462262248/1201777996978577/f)
- Adds a liveness endpoint to the judicial system message handler service.
To prevent endless restarts.
=> fix(j-s): Message Handler Liveness

apps/api/infra/api.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml
=> fix(application-system-payment): Fix config for XROAD_CHARGE_FJS_V2_PATH

libs/api/domains/finance/src/lib/api-domains-finance.resolver.ts
Hotfix release with #8007 
To fix delegations for only salary scope.
=> fix(service-portal): Update scope for finance tabs method in finance resolver

apps/services/auth-public-api/src/app/modules/delegations/meDelegations.controller.spec.ts, apps/services/auth-public-api/src/app/modules/delegations/meDelegations.controller.ts, libs/auth-api-lib/src/lib/services/delegations.service.ts
Hotfix #7993
To handle invalid delegation ids appropriately.
=> fix(auth-api): Fixing auth api service to check for invalid uuid delegation lookup

apps/service-portal/src/components/ContentBreadcrumbs/ContentBreadcrumbs.tsx, libs/service-portal/core/src/lib/messages.ts, libs/service-portal/core/src/lib/navigation/masterNavigation.ts
Hotfix release with #8013 
To improve breadcrumbs.
=> refactor(service-portal): Refactor ContentBreadcrumbs (#8013)

apps/judicial-system/backend/src/app/modules/user/user.service.ts, apps/judicial-system/backend/src/environments/environment.ts
[Skrítnar upplýsingar um innskráðan admin notanda](https://app.asana.com/0/1199153462262248/1202552066667836/f)
- Adds a title for admin users.
Looks better.
=> chore(j-s): Admin User Title

apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Defendant/Defendant.tsx
[Það ætti að vera hægt að eyða fyrsta varnaraðila ef fleiri en einn varnaraðili er skráður](https://app.asana.com/0/1199153462262248/1202560018861859/f)
- Allows the deletion of any defendant if more than one defendant is specified.
Bug
=> fix(j-s): Delete Defendant

libs/service-portal/core/src/lib/navigation/masterNavigation.ts
Hotfix release with #8030 
Fix real estate breadcrumbs regression.
=> fix(service-portal): Hotfix - Fix real estate breadcrumbs (#8030)

libs/api/domains/license-service/src/lib/client/adr-license-client/adrLicenseService.api.ts, libs/api/domains/license-service/src/lib/client/machine-license-client/machineLicenseService.api.ts
Remove error logging when service returns 403 and 404
Causing error madness in Datadog 🐶 
=> fix(api): error logging when 404

libs/api/domains/license-service/src/lib/client/adr-license-client/adrLicenseService.api.ts, libs/api/domains/license-service/src/lib/client/machine-license-client/machineLicenseService.api.ts
Hotfix for: #8038 
Causing a lot of "error" logs in datadog
=> fix(clients): Fix license client logging

libs/financial-aid/shared/src/components/TaxBreakdown/TaxBreakdown.tsx
https://app.asana.com/0/1202244723867117/1202547235884507
Fix import for getMonth function inside the TaxBreakdown component.
=> fix(fa): Fix import for getMonth function

libs/api/domains/national-registry-x-road/src/lib/nationalRegistryXRoad.service.ts
Þjóðskrá changed their error response when retrieving a spouse that does not exist. It used to be 404 but no we get 400. We have contacted them to ask them about this change, but in the meantime we handle the 400 response in code. 
Discussion about this: https://islandis.slack.com/archives/C019LNRM6LE/p1657731379605769
=> fix(fa): Handle 400 status from Þjóðskrá when getting spouse

apps/web/components/Organization/Slice/FeaturedArticles/FeaturedArticlesSlice.tsx
Change to TopicCard to get style fixes.
=> feat(web): Change LinkCard to TopicCard in featured articles

apps/web/screens/Organizations/Organizations.css.ts, apps/web/screens/Organizations/Organizations.tsx, libs/cms/src/lib/models/organization.model.ts
* Added a select box which allows you to order organizations by title
=> feat(web): Organizations page - order by

apps/application-system/api/infra/application-system-api.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml
=> fix(fjs): generating env values for fjscharge on application-system-api-worker

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx, apps/web/components/Organization/Wrapper/config.ts
=> feat(web): Add chat bot for HSN

.github/workflows/push.yml
Add functionality to feature deploy a pre-release branch, giving us access to check out releases on dev before pushing them forward. 
=> feat(ci): pre release branch feature deploy

libs/application/templates/parental-leave/src/lib/answerValidators.ts, libs/application/templates/parental-leave/src/lib/isValidEmail.ts
=> fix: parental-leave add validation for employer's email

libs/application/templates/driving-license/src/fields/Done/Congratulations.tsx, libs/application/templates/driving-license/src/lib/messages.ts
Temp application gets its own success message.
=> fix(driving-license-application): Temp success message

libs/application/templates/passport/src/forms/infoSection/childsPersonalInfo.ts, libs/application/templates/passport/src/forms/infoSection/personalInfo.ts, libs/application/templates/passport/src/utils/removeCountryCode.ts
=> fix(passport): removing country code from default value in personal info

apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.controller.ts, apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getCourtRecordPdfGuards.spec.ts, apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getRequestPdfGuards.spec.ts, apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getRulingPdfGuards.spec.ts
=> fix(j-s): Defender pdf fix

libs/application/templates/operating-license/src/lib/messages.ts, libs/application/types/src/lib/ApplicationTypes.ts
=> fix(operating-license-application): slug

libs/service-portal/applications/src/screens/ApplicationList/ApplicationList.tsx
Add dynamic url to application url
To be able to host the service portal on any url without breaking links.
=> fix(applications): Add dynamic url to service portal application url

libs/api/domains/communications/src/lib/emailTemplates/tellUsAStory.ts, libs/application/template-api-modules/src/lib/modules/templates/institution-collaboration/emailGenerators/applicationEmail.ts, libs/application/template-api-modules/src/lib/modules/templates/login-service/emailGenerators/applicationEmail.ts
Add reply to as its not allowed to add any email as a sender.
Blocking the release
=> fix(application-system): added reply and reverted from changes

libs/api/domains/communications/src/lib/emailTemplates/tellUsAStory.ts, libs/application/template-api-modules/src/lib/modules/templates/institution-collaboration/emailGenerators/applicationEmail.ts, libs/application/template-api-modules/src/lib/modules/templates/login-service/emailGenerators/applicationEmail.ts
Reverted tell us a story and added reply to application emails
Wrong approach to a fix for application system and should not be needed for the form.
The email service doesn't allow us to assign any email as sender, which makes perfect sense when you think about it. 😅 
=> fix(application-system): Reverted tell us a story and added reply to application emails

libs/application/templates/accident-notification/src/lib/AccidentNotificationTemplate.ts
=> fix(accident-notification): Reintroduce unlist for last role

package.json, yarn.lock
Update to the latest beta version of kennitala@2 package, which includes fixes for gervimenn and typescript `generatePerson` type overload.
Earlier version of kennitala broke our usage, so temporarily we created a fork with our fixes. Now the official package includes the fixes needed for our use.
=> chore(core): Update kennitala package

libs/clients/vehicles/project.json
=> fix(service-portal): client build failing

.github/actions/ci-io.ts, .github/actions/dist/index.js, .github/actions/main.ts, apps/services/auth-api/infra/identity-server.ts, apps/services/auth-api/src/app/modules/clients/clients.controller.ts, charts/identity-server/values.dev.yaml, charts/identity-server/values.prod.yaml, charts/identity-server/values.staging.yaml
=> feat(ids): Add license key secret to config.

.github/actions/dist/index.js, .github/actions/main.ts
Fixing this error - https://github.com/island-is/island.is/runs/7836253831?check_suite_focus=true
=> fix(ci): Removing quotes from branch name

apps/system-e2e/cypress.config.ts
=> test(system-e2e): fix environment name bug

libs/auth/react/src/lib/Authenticator/CheckIdpSession.tsx
https://www.notion.so/SessionInfo-bug-on-computer-sleep-3628b88e47aa46258114d8a78a14b2ec
Refactor Check IDP Session to handle computer sleep and temporary loss of network connection.
For more reliably user session timeout monitoring.
=> refactor(auth-react): Refactor Check IDP Session

libs/service-portal/core/src/lib/service-portal-core.ts
Add clearer documentation regarding a route key in service portal
=> chore(service-portal): documentation for route key in service portal

libs/service-portal/vehicles/src/screens/Overview/Overview.tsx
Hide CSV option until we fix data 
Some data missing
=> fix(service-portal): remove vehicle csv, data missing

apps/download-service/infra/download-service.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml
Add env vars for vehicles
It's Missing
=> fix(download-service): Add env vars for vehicles

apps/download-service/infra/download-service.ts, apps/download-service/src/app/modules/vehicles-documents/vehicle-document.controller.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml
hotfix:
https://github.com/island-is/island.is/pull/8199
https://github.com/island-is/island.is/pull/8199
=> fix(download-service): Vehicle env

apps/application-system/api/infra/application-system-api.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml
=> fix(application-system-worker): Hotfix/missing envs in worker file storage upload bucket

apps/air-discount-scheme/backend/src/app/modules/nationalRegistry/nationalRegistry.service.ts
=> fix(ads): Ensure callee parent is included in custodians (#8220)

apps/system-e2e/src/lib/types.ts
=> chore(system-e2e): resizing timeouts

apps/api/infra/api.ts, charts/islandis/values.dev.yaml, charts/islandis/values.prod.yaml, charts/islandis/values.staging.yaml
=> infra(api): more RAM

libs/api/domains/national-registry/src/lib/dto/FamilyCorrectionInput.input.ts, libs/api/domains/national-registry/src/lib/graphql/correction.resolver.ts, libs/api/domains/national-registry/src/lib/graphql/index.ts, libs/api/domains/national-registry/src/lib/nationalRegistry.module.ts, libs/api/domains/national-registry/src/lib/nationalRegistry.service.ts, libs/clients/national-registry/v1/src/lib/dto/familyCorrection.dto.ts, libs/clients/national-registry/v1/src/lib/nationalRegistryApi.ts, libs/service-portal/information/src/components/ChildView/ChildView.tsx, libs/service-portal/information/src/screens/FamilyMember/Child.tsx, libs/service-portal/information/src/screens/FamilyMember/ChildRegistrationModal.tsx
* Add child registration service back in.
* Allows parents to send a message to Þjóðskrá regarding their children's registration.
=> feat(national-registry-v1): Add child registration service back in

apps/system-e2e/cypress.config.ts, apps/system-e2e/src/support/email-account.ts, apps/system-e2e/src/support/tasks/email.ts, apps/system-e2e/src/support/utils.ts
Move Cypress tasks to separate file to keep cypress.config a bit clean.
=> chore: move tasks to separate file, config cleanup

infra/src/feature-env.ts
=> chore(ci): allow to render values for all services when service name is '*'

scripts/local-e2e.sh
system-e2e build breaks on local machine: linux (Fedora 36) after @aws-sdk/client-ses was added.
`@aws-sdk/signature-v4-crt` seemingly is a missing dependency.
=> fix: added required signature crt package for aws client-ses

apps/web/components/Stepper/StepperHelper/StepperHelper.tsx
* Change variable naming since the Stepper component option values got changed in the frontend
=> chore(web): Stepper helper changes

apps/judicial-system/web/messages/Core/index.ts, apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFiles/CaseFiles.tsx, apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant.tsx, apps/judicial-system/web/src/routes/Prosecutor/Indictments/Processing/Processing.tsx, apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/IndictmentCaseIntro/IndictmentCaseIntro.spec.tsx, apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/IndictmentCaseIntro/IndictmentCaseIntro.tsx, apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/PoliceCaseNumbersTags/PoliceCaseNumbersTags.tsx, apps/judicial-system/web/src/utils/hooks/useSections/index.ts
[Asana ](https://app.asana.com/0/1199153462262248/1202868512043854/f)
- Show court and defendant names on every step in indictment cases
=> feat(j-s): court and defendants on every step in indictment cases

apps/skilavottord/web/components/GDPR/withGDPR.tsx
=> feat: adding pageLayout

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/constants.ts, libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/applicationApprovedByEmployer.ts, libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/applicationApprovedByEmployerToEmployer.ts, libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/assignEmployerEmail.ts, libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/assignOtherParentEmail.ts, libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/employerRejectedEmail.ts, libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/otherParentRejectedEmail.ts, libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
Check for production enviornment before sending email, in the email templates
=> feat(parental leave): email sender on prod

apps/system-e2e/src/integration/applications/acceptance/parental-leave.spec.ts, apps/system-e2e/src/lib/i18n-messages.ts, tsconfig.base.json
Acceptance test for parental leave was not running in the container (after the bundling).
=> fix(qa): fixing the code bundling of the acceptance tests

apps/financial-aid/backend/src/app/modules/application/application.service.ts, apps/financial-aid/web-veita/src/components/Profile/ApplicationProfile.tsx
One field in the NAV connection was receiving wrong string.
Fix typo in error text
These bugs were found after testing with Hafnafjörður.
=> fix(fa): Fix the data sent to nav and the error text

libs/application/template-api-modules/src/lib/modules/templates/p-sign-submission/p-sign-submission.service.ts
Delivery method and district where not being correctly extracted from answers.
=> fix(p-sign-application): Delivery fix

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/applicationApprovedByEmployer.ts, libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/applicationApprovedByEmployerToEmployer.ts, libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/assignEmployerEmail.ts, libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/assignOtherParentEmail.ts, libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/employerRejectedEmail.ts, libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/otherParentRejectedEmail.ts, libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
Reverting email changes since they cause issues on dev.
=> feat: reverting email changes

libs/service-portal/information/src/screens/UserInfo/UserInfo.tsx
Don't show individuals on same family number when in delegation mode.
=> fix(service-portal): No showing family members in delegation

apps/system-e2e/cypress.config.ts, apps/system-e2e/src/integration/air-discount-scheme/smoke/discount-data.spec.ts, apps/system-e2e/src/integration/web/smoke/homepage.spec.ts, apps/system-e2e/src/support/index.d.ts, apps/system-e2e/src/support/utils.ts
=> fix(qa): Disabling unstable tests, improving base url prefix support

libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/pdfGenerators/templates/complaintPdf.ts, libs/application/templates/data-protection-complaint/src/fields/ComplaineeRepeater/ComplaineeTable.tsx
https://app.clickup.com/t/2p7e8zw
https://app.clickup.com/t/2p7eb61
Update PDF for kvortun til persónuverndar
Update form to not display country of operation if it was not selected.
Request from application owner
=> fix(applications): Update PDF for data protection complaint & form rendering error

apps/system-e2e/src/integration/web/smoke/homepage.spec.ts
For more on this see [this](https://github.com/cypress-io/cypress/issues/7062).
=> fix(ci): attempting to fix connectivity issues while running System E2E tests

libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
=> fix(service-portal): add close to doc write

libs/application/templates/login-service/src/fields/IsatInvalid/IsatInvalid.tsx, libs/application/templates/login-service/src/lib/dataSchema.ts
Allow all companies to do login service applicaiton
VAT check is broken, needs to be looked at further.
=> fix(login-service): Allow all companies

libs/application/templates/marriage-conditions/src/dataProviders/NationalRegistryMaritalStatusProvider.ts, libs/application/templates/marriage-conditions/src/lib/MarriageConditionsTemplate.ts, libs/application/templates/marriage-conditions/src/lib/getApplicationFeatureFlags.ts
=> fix(marriage-conditions-application): fakedata featureflagged

libs/application/templates/marriage-conditions/src/dataProviders/NationalRegistryMaritalStatusProvider.ts, libs/application/templates/marriage-conditions/src/lib/MarriageConditionsTemplate.ts, libs/application/templates/marriage-conditions/src/lib/getApplicationFeatureFlags.ts
=> fix(marriage-conditions-application): fakedata featureflagged (#8341)

apps/judicial-system/backend/src/app/formatters/formatters.spec.ts, apps/judicial-system/backend/src/app/formatters/formatters.ts, apps/judicial-system/backend/src/app/formatters/requestPdf.ts, apps/judicial-system/backend/src/app/messages/courtUpload.ts, apps/judicial-system/backend/src/app/messages/notifications.ts, apps/judicial-system/backend/src/app/messages/pdfRequest.ts, apps/judicial-system/backend/src/app/modules/case/case.service.ts, apps/judicial-system/backend/src/app/modules/notification/notification.service.ts, apps/judicial-system/web/src/components/InfoCard/InfoCard.tsx, apps/judicial-system/web/src/routes/Court/InvestigationCase/Overview/Overview.tsx, apps/judicial-system/web/src/routes/Defender/CaseOverviewForm.tsx, apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Overview/Overview.tsx, apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/Overview.tsx, apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
[Asana - Mörg LÖKE-númer](https://app.asana.com/0/1199153462262248/1202868512043864/f)
- fix name for request file uploaded to court
- iterate the ready-for-court email notification for the prosecutor
- change the subject of the court date email to the prosecutor
- move the police case number out of the header in the request pdf
-  add a line break between police case numbers in InfoCard
- Multiple police case numbers iterations
=> feat(j-s): more multiple loke fixes

libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
hotfix: https://github.com/island-is/island.is/pull/8346
=> fix(service-portal): Remove close

libs/api/domains/vehicles/src/models/usersVehicles.model.ts
add default values to users vehicle.
=> fix(service-portal): Add default value to usersvehicle

apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
[Asana - Þingbók "bíður undirritunar" á verjendaskjá](https://app.asana.com/0/1199153462262248/1202882723716231/f)
- Remove message when court record is unsigned
- Court record is not required to be signed, so no message is needed
=> feat(j-s): remove message when court record is unsigned

libs/clients/syslumenn/src/lib/syslumennClient.service.ts
Client generation was faulty in the past.
Fixed hardcoded values.
=> fix(announcement of death): Map relations from API instead of hardcoding

libs/application/template-api-modules/src/lib/modules/templates/p-sign-submission/p-sign-submission.service.ts, libs/application/templates/p-sign/src/forms/applicationSections/sectionDelivery.ts
StarfstodId where unreliable and syslumenn asked to get name and place instead.
=> fix(p-sign-application): Delivery submission requires name

libs/application/template-api-modules/src/lib/modules/templates/p-sign-submission/p-sign-submission.service.ts, libs/application/templates/p-sign/src/forms/applicationSections/sectionDelivery.ts
=> fix(p-sign-application): Delivery submission requires name (#8359)

apps/judicial-system/backend/src/app/modules/case/case.service.ts
[Asana - Mörg Löke númer](https://app.asana.com/0/1199153462262248/1202868512043864/f)
- Remove capitalize for case type for files uploaded to court
- "Krafa um Gæsluvarðhald" þarf það að heita "Krafa um gæsluvarðhald".
=> feat(j-s): remove capitalized case type for court upload files

apps/judicial-system/web-e2e/src/integration/Court/Indictments/overview.spec.ts, apps/judicial-system/web-e2e/src/integration/Court/Indictments/receptionAndAssignment.spec.ts, apps/judicial-system/web/src/routes/Court/Indictments/Overview/Overview.strings.ts, apps/judicial-system/web/src/routes/Court/Indictments/Overview/Overview.tsx, apps/judicial-system/web/src/routes/Court/components/ReceptionAndAssignment/ReceptionAndAssignment.tsx, apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx, apps/judicial-system/web/src/types/index.ts, apps/judicial-system/web/src/utils/hooks/useSections/index.ts, libs/judicial-system/consts/src/lib/consts.ts
[Asana - Yfirlit ákæru sem fyrsta skjá Dómarflæði](https://app.asana.com/0/1199153462262248/1202929644605769/f)
- Make Judge overview screen be the first step in Indictments
=> feat(j-s): make judge overview the first step in Indictments

apps/judicial-system/web/src/components/SelectCourtOfficials/SelectCourtOfficials.tsx
[Asana - Skjár 2: Móttaka og úthlutun](https://app.asana.com/0/1199153462262248/1202861834321035/f)
- Fix tooltip for `SelectCourtOfficials` component
| Before | After |
| - | - |
| ![Screenshot 2022-09-08 at 12 58 53](https://user-images.githubusercontent.com/5700902/189127959-dd8ce8d9-c642-4792-bdca-c024ad93333c.png) | ![Screenshot 2022-09-08 at 12 55 20](https://user-images.githubusercontent.com/5700902/189127842-c7970737-653b-48e7-abe5-0e7917fe58b8.png) |
=> fix(j-s): fix tooltip for SelectCourtOfficials

apps/judicial-system/backend/src/app/formatters/casefilesPdf.ts, apps/judicial-system/backend/src/app/formatters/custodyNoticePdf.ts, apps/judicial-system/backend/src/app/formatters/formatters.spec.ts, apps/judicial-system/backend/src/app/formatters/formatters.ts, apps/judicial-system/backend/src/app/messages/courtUpload.ts, apps/judicial-system/backend/src/app/messages/notifications.ts, apps/judicial-system/backend/src/app/messages/pdfCasefiles.ts, apps/judicial-system/backend/src/app/modules/case/case.service.ts, apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
[Asana - Mörg LÖKE-númer](https://app.asana.com/0/1199153462262248/1202868512043864/f)
- fix resubmit case email for multiple loke numbers
- fix file name uploaded to court
- remove policeCaseNumbers from custodyNoticePdf and casefilesPdf
=> feat(j-s): multi loke cleanup

apps/judicial-system/web/src/routes/Shared/Cases/ActiveCases.tsx, apps/judicial-system/web/src/routes/Shared/Cases/Cases.css.ts, apps/judicial-system/web/src/routes/Shared/Cases/MobileCase.tsx
[Asana - Á sumum tölvuskjám/tækjum sést aðeins í rauða Afturkalla takkann í kröfulistanum.](https://app.asana.com/0/1199153462262248/1202891259672357/f)
- fix dom warning
- fix delete case button peeking out of the container and showing a hairline of its red color
=> fix(j-s): fix delete case button peeking out

libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts, libs/api/domains/vehicles/src/models/getVehicleSearch.model.ts, libs/clients/vehicles/src/lib/vehiclesClient.config.ts, libs/service-portal/core/src/components/TableGrid/TableGrid.tsx, libs/service-portal/vehicles/src/queries/getVehiclesSearch.ts, libs/service-portal/vehicles/src/screens/Lookup/Lookup.tsx, libs/service-portal/vehicles/src/utils/createUnits.ts, libs/service-portal/vehicles/src/utils/vehicleOwnedMapper.ts
Hotfixin vehicles --> #8364 
Fixing errors 
=> fix(service-portal): hotfix vehicles typos and timeout (#8364)

apps/judicial-system/web/src/components/SelectCourtOfficials/SelectCourtOfficials.strings.ts
- Fix contentful namespace 
- Unable to upload to contentful
=> fix(j-s): fix contentful namespace

libs/application/templates/mortgage-certificate/src/fields/PendingRejected/index.tsx, libs/application/templates/mortgage-certificate/src/fields/PendingRejectedTryAgain/index.tsx
Updating buttons that do not work live!
=> fix(mortgage-certificate): buttons to span (#8357)

libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts, libs/service-portal/core/src/components/TableGrid/TableGrid.tsx, libs/service-portal/vehicles/src/components/VehicleCard.tsx, libs/service-portal/vehicles/src/lib/messages.ts, libs/service-portal/vehicles/src/utils/createUnits.ts
#8387 
Hotfixing correct year values for vehicles
=> fix(service-portal): hotfix - null and year fields in vehicles (#8387)

apps/financial-aid/api/project.json
This is a revert of this PR: https://github.com/island-is/island.is/pull/8400. 
That PR was made to test a fix for DEV as it was broken. It did not solve the issue but the issue has been solved by devops. So this PR is reverting that test-fix because it is most likely not needed.
=> fix(fa): Revert change to build

apps/financial-aid/backend/src/app/modules/application/application.service.ts
This is a revert of this PR: https://github.com/island-is/island.is/pull/8310
The original change was "Umsókn" -> "Application" but now the NAV people want it back to "Umsókn" as they have changed their settings to use the Icelandic wording
=> fix(fa): Change nav status to 'Umsókn'

libs/api/domains/vehicles/src/models/getVehicleSearch.model.ts, libs/clients/vehicles/src/clientConfig.json, libs/clients/vehicles/src/lib/vehiclesClient.service.ts, libs/service-portal/core/src/components/TableGrid/TableGrid.tsx, libs/service-portal/vehicles/src/components/DetailTable/AxleTable.tsx, libs/service-portal/vehicles/src/lib/messages.ts, libs/service-portal/vehicles/src/screens/Lookup/Lookup.tsx, libs/service-portal/vehicles/src/screens/VehicleDetail/VehicleDetail.tsx, libs/service-portal/vehicles/src/utils/createUnits.ts
* fix: axle data, timeout, null values
* fix: nullable array issue
* fix: always display name value
See #8408 
=> fix(service-portal): hotfix axle data, timeout, null values (#8408)

apps/judicial-system/web/src/routes/Court/Indictments/Subpoena/Subpoena.tsx
[Fyrirkall](https://app.asana.com/0/1199153462262248/1202861834321039/f)
- Fixes court date notifications for s-cases. No notifications were sent.
Bug
=> fix(j-s): S-Case Court Date Notifications

libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
=> feat(parental-leave): add assign VMST to states

libs/api/domains/financial-statements-inao/src/lib/financialStatementsInao.resolver.ts, libs/api/domains/financial-statements-inao/src/lib/financialStatementsInao.service.ts, libs/api/domains/financial-statements-inao/src/lib/models/config.model.ts, libs/clients/financial-statements-inao/src/lib/financialStatementsInaoClient.service.ts, libs/clients/financial-statements-inao/src/lib/types/index.ts
Add query to get config values for application
Need values that are configured on the backend (Dataverse)
=> feat(financial-statements-inao): Add config values query

apps/air-discount-scheme/backend/esbuild.json
Add missing dependency for air-discount-scheme
air-discount-scheme fails to start without it.
=> fix(air-discount-scheme): Add pseudomap to air-discount-scheme

libs/application/templates/parental-leave/src/forms/EmployerApproveEdits.ts
=> feat: adding union and pension back

apps/judicial-system/backend/src/app/modules/case/case.service.ts, apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliver.spec.ts, apps/judicial-system/backend/src/app/modules/court/court.service.ts, apps/judicial-system/backend/src/app/modules/court/index.ts, apps/judicial-system/backend/src/app/modules/court/test/createDocument.spec.ts, apps/judicial-system/backend/src/app/modules/file/file.service.ts, apps/judicial-system/backend/src/app/modules/file/test/uploadCaseFileToCourt.spec.ts, apps/judicial-system/backend/src/app/modules/notification/notification.service.ts, libs/judicial-system/court-client/src/lib/courtClient.service.ts, libs/judicial-system/court-client/src/lib/courtClientAvailable.service.ts, libs/judicial-system/court-client/src/lib/courtClientUnavailable.service.ts
[Vista dómstólaskjöl S-mála í Auði og LÖKE](https://app.asana.com/0/1199153462262248/1202974314193390/f)
- Stores court documents in the correct folder in Auður.
Bug
=> fix(j-s): Upload Court Documents

.github/CODEOWNERS
* Add Stefna as codeowner of web project
* Stefna has been maintaining and adding features to the web project for a few months now, so I'd say it's time we change the codeowners file to reflect that
=> chore(web): Add Stefna as codeowner of web project

apps/air-discount-scheme/backend/src/app/modules/nationalRegistry/nationalRegistry.service.ts
=> fix(ads): revert to last known good state

libs/service-portal/vehicles/src/screens/Lookup/Lookup.tsx
Move name and address on top of the table. 
Samgöngustofa wants name and address to be more visible
=> refactor(service-portal): move name in vehicle lookup table

libs/application/ui-shell/src/components/ScreenFooter.tsx
=> fix(ui-shell): Changing default message to icelandic for the Back to service portal button

libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
=> feat(parental-leave): Configurate editable periods

apps/web/components/Organization/Wrapper/Themes/RikislogmadurTheme/RikislogmadurFooter.css.ts, apps/web/components/Organization/Wrapper/Themes/RikislogmadurTheme/RikislogmadurFooter.tsx
=> feat(web): Change Ríkislögmaður footer layout

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts, libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts, libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
=> feat(parental-leave): sending application after updated periods

apps/web/components/Project/Header/DefaultProjectHeader.css.ts, apps/web/components/Project/Header/DefaultProjectHeader.tsx, apps/web/screens/Project/Project.tsx, apps/web/screens/Project/components/ProjectFooter/ProjectFooter.tsx, apps/web/screens/Project/components/ProjectFooter/index.ts, apps/web/screens/Project/components/ProjectFooter/themes/OpinberNyskopun/OpinberNyskopunFooter.css.ts, apps/web/screens/Project/components/ProjectFooter/themes/OpinberNyskopun/OpinberNyskopunFooter.tsx, apps/web/screens/Project/components/ProjectHeader/ProjectHeader.tsx, apps/web/screens/queries/Project.tsx, libs/cms/src/lib/generated/contentfulTypes.d.ts, libs/cms/src/lib/models/projectPage.model.ts
Hotfix PR, see original PR here: https://github.com/island-is/island.is/pull/8535
=> feat(web): Hotfix - project page custom footer

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx, apps/web/components/Organization/Wrapper/Themes/LandkjorstjornTheme/LandskjorstjornHeader.css.ts, apps/web/components/Organization/Wrapper/Themes/LandkjorstjornTheme/LandskjorstjornHeader.tsx, libs/cms/src/lib/generated/contentfulTypes.d.ts
* Add header for Landskjörstjórn organization page
=> feat(web): Landskjörstjórn header

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx, apps/web/components/Organization/Wrapper/Themes/LandkjorstjornTheme/LandskjorstjornHeader.css.ts, apps/web/components/Organization/Wrapper/Themes/LandkjorstjornTheme/LandskjorstjornHeader.tsx
Hotfix PR regarding landskjörstjórn header, here's the PR that got merged into main: #8536
=> feat(web): Hotfix - Landskjörstjórn header (#8536)

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/constants.ts, libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts, libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts, libs/application/templates/parental-leave/src/lib/answerValidators.ts, libs/application/templates/parental-leave/src/lib/messages.ts
Moving the file upload field to allow it to be used for more than just the upload of self employed attachments
=> feat(parental-leave): moving the file upload field
