island-is/island.is

apps/web/components/SideMenu/SideMenu.treat.ts
apps/web/screens/Layouts/Layouts.tsx
libs/island-ui/core/src/lib/Footer/Footer.tsx

Very minor layout tweaks

---

apps/services/search-indexer/src/app/indexing.service.ts
libs/api/content-search/src/services/elastic.service.ts

Added delete methods to elastic service

Delete all irrelevant documents in ES during initalSync

---

apps/services/search-indexer/src/main.ts
apps/services/search-indexer/src/migrate.ts

Migrate is only looking at version number === 1 as condition to create a fresh new index,  
made migration check for older index instead
- Changed create new index check
- Added logs

Added potential fix for migrate script

---

libs/api/content-search/src/services/elastic.service.ts

Wildcard to query

---

apps/web/screens/Article.tsx
apps/web/screens/Layouts/Layouts.tsx
libs/island-ui/contentful/src/lib/BorderedContent/BorderedContent.tsx
libs/island-ui/contentful/src/lib/Content/Content.tsx
libs/island-ui/core/src/lib/Grid/GridContainer/GridContainer.treat.ts
libs/island-ui/core/src/lib/Grid/GridRow/GridRow.treat.ts
libs/island-ui/core/src/lib/Grid/GridRow/GridRow.tsx

Introduce Grid to Article layout

---

apps/web/components/SideMenu/SideMenu.treat.ts
apps/web/components/SideMenu/SideMenu.tsx
apps/web/components/SideMenu/components/LinkBox/LinkBox.treat.ts
apps/web/components/SideMenu/components/LinkBox/LinkBox.tsx

+ Fix LinkBox hover and LinkBox equal height issue.
Fix scroll locking on desktop.

Don't scroll SideMenu >mobile.

---

apps/services/search-indexer/src/app/indexing.service.ts

Updated process entry description field

---

apps/judicial-system/api/migrations/20200902200212-update-case.js
apps/judicial-system/api/src/app/modules/case/case.controller.ts
apps/judicial-system/api/src/app/modules/case/case.model.ts
apps/judicial-system/api/src/app/modules/case/case.pipe.ts
apps/judicial-system/api/src/app/modules/case/dto/createCase.dto.ts
apps/judicial-system/api/src/app/modules/case/dto/updateCase.dto.ts
apps/judicial-system/api/src/app/modules/case/e2e/case.spec.ts
apps/judicial-system/api/src/openapi.yaml
apps/judicial-system/web/src/routes/DetentionRequests/DetentionRequests.spec.tsx
apps/judicial-system/web/src/types.ts

Removes description from case model, makes suspect name optional and removes it from case creation

Judicial System: Optional case fields

---

apps/application-system/form/src/app/App.tsx
apps/application-system/form/src/routes/Application.tsx
apps/application-system/form/src/routes/Applications.tsx
libs/application/form/src/components/Screen.tsx
libs/application/form/src/lib/ApplicationForm.spec.tsx
libs/application/form/src/lib/ApplicationForm.tsx
libs/application/form/src/reducer/ApplicationFormReducer.spec.ts
libs/application/form/src/reducer/ApplicationFormReducer.ts
libs/application/form/src/reducer/ReducerTypes.ts
libs/application/form/src/reducer/reducerUtils.ts

Entering route: `/applications/:type` now creates instantly a new application of that type and redirects to `/application/:id` so the self service flow can start.

Refactor application system router and reducer.

---

apps/web/components/Card/Card.treat.ts
apps/web/components/Categories/Categories.tsx
apps/web/components/IntroductionSection/IntroductionSection.tsx
apps/web/components/LifeEventsCardsSection/LifeEventsCardsSection.tsx
apps/web/components/LifeEventsCardsSection/components/LifeEventCard/LifeEventCard.treat.ts
apps/web/components/LifeEventsCardsSection/components/LifeEventCard/LifeEventCard.tsx
apps/web/components/LifeEventsCardsSection/components/LifeEventCard/index.ts
apps/web/components/LifeEventsCardsSection/index.ts
apps/web/components/Section/Section.tsx
apps/web/components/Section/index.ts
apps/web/screens/Home.tsx
libs/island-ui/core/src/lib/Footer/Footer.tsx
libs/island-ui/core/src/lib/Grid/GridColumn/GridColumn.treat.ts
libs/island-ui/core/src/lib/Grid/GridContainer/GridContainer.treat.ts

Implement Life Events for the front page. It uses dummy data so we can display something for the demo tomorrow.
Implement a Section component that deals with section spacing and knows how to deal with background bleeding like this:

Life Events section on front page + Section component

---

apps/auth-api/src/app/modules/clients/client.model.ts

Property name fixed
readonly added to relation

fix readonly of property

---

apps/web/graphql/client.ts
apps/web/next.config.js
apps/web/pages/_app.tsx

- Made readiness check if web has api connection
- Made lifeliness respond 200 if called

Added healthcheck endpoints

---

apps/judicial-system/api/migrations/20200907181858-update-case.js
apps/judicial-system/api/src/app/modules/case/case.model.ts
apps/judicial-system/api/src/app/modules/case/dto/createCase.dto.ts
apps/judicial-system/api/src/app/modules/case/dto/updateCase.dto.ts
apps/judicial-system/api/src/openapi.yaml

Adds suspect name and case state to create api call.

Judicial System: Adds optional create fields

---

apps/air-discount-scheme/web/components/Content/Content.tsx
apps/air-discount-scheme/web/screens/Home/Home.tsx
apps/air-discount-scheme/web/screens/Subsidy/Subsidy.tsx
apps/air-discount-scheme/web/screens/Subsidy/components/UserCredit/UserCredit.tsx
apps/air-discount-scheme/web/screens/TermsOfUse/TermsOfUse.tsx

Ads - custom styles for images in sidebar

---

apps/web/components/LifeEventsCardsSection/components/LifeEventCard/LifeEventCard.treat.ts
apps/web/components/LifeEventsCardsSection/components/LifeEventCard/LifeEventCard.tsx
apps/web/components/NewsCard/NewsCard.treat.ts
apps/web/components/NewsCard/NewsCard.tsx
libs/island-ui/core/src/lib/Link/ArrowLink/ArrowLink.treat.ts
libs/island-ui/core/src/lib/Link/ArrowLink/ArrowLink.tsx

Add correct focus styles to components

---

apps/air-discount-scheme/api.graphql
apps/air-discount-scheme/api/src/app/modules/user/models/fund.model.ts
apps/air-discount-scheme/backend/src/app/modules/user/test/e2e/user.spec.ts
apps/air-discount-scheme/backend/src/app/modules/user/test/unit/user.controller.spec.ts
apps/air-discount-scheme/backend/src/app/modules/user/test/unit/user.service.spec.ts
apps/air-discount-scheme/backend/src/app/modules/user/user.model.ts
apps/air-discount-scheme/backend/src/app/modules/user/user.service.ts
apps/air-discount-scheme/backend/src/openapi.yaml
apps/air-discount-scheme/web/graphql/schema.tsx
apps/air-discount-scheme/web/screens/Subsidy/components/Benefits/Benefits.tsx
libs/air-discount-scheme/types/src/lib/user.ts

Mask nationalId from airline service

---

apps/web/components/SearchInput/SearchInput.treat.ts
apps/web/components/SearchInput/SearchInput.tsx
apps/web/screens/Home.tsx
libs/island-ui/core/src/lib/AsyncSearch/AsyncSearch.treat.ts
libs/island-ui/core/src/lib/AsyncSearch/AsyncSearch.tsx
libs/island-ui/core/src/lib/AsyncSearch/shared/Menu/Menu.treat.ts
libs/island-ui/core/src/lib/Typography/Typography.treat.ts

Updates: 
* Using cursor pointer in relevant places
* Replace search icon for loader
* Stack autocomplete and 'Beint að efninu' on top of each other
* * hide 'Beint að efninu' if there are no results
* Adding href to tag buttons below search bar
Before:
After:

Search box Improvements

---

apps/web/components/LifeEventsCardsSection/components/LifeEventCard/LifeEventCard.treat.ts
apps/web/components/LifeEventsCardsSection/components/LifeEventCard/LifeEventCard.tsx

Dropshadow og border á lífsviðburðaspjöldum

---

apps/web/screens/Article.tsx
apps/web/screens/LifeEvent/LifeEvent.tsx
libs/island-ui/core/src/lib/Breadcrumbs/Breadcrumbs.tsx

Update color of breadcrumbs to match new designs
Before:
After:

Litur á breadcrumbs

---

apps/air-discount-scheme/backend/src/app/modules/nationalRegistry/nationalRegistry.service.ts
apps/air-discount-scheme/backend/src/app/modules/nationalRegistry/nationalRegistry.types.ts
apps/air-discount-scheme/backend/src/app/modules/nationalRegistry/test/unit/nationalRegistry.service.spec.ts

Only fetch children for parents

---

apps/web/graphql/schema.ts
apps/web/screens/Home.tsx
libs/api/domains/cms/src/lib/services.ts

Addressing comments from this PR: https://github.com/island-is/island.is/pull/760

Fixes based off feedback from life events PR

---

libs/island-ui/core/src/lib/Checkbox/Checkbox.stories.tsx
libs/island-ui/core/src/lib/Checkbox/Checkbox.treat.ts
libs/island-ui/core/src/lib/Checkbox/Checkbox.tsx

Adds a large checkbox component

---

apps/api/codegen.yml
apps/web/graphql/client.ts
apps/web/graphql/fragmentTypes.json
apps/web/screens/AboutPage/AboutPage.tsx
apps/web/screens/Article.tsx
apps/web/screens/LandingPage/LandingPage.tsx
libs/api/domains/cms/src/lib/models/article.model.ts
workspace.json

Hey,
I tried it with this article (http://localhost:4200/grein/faedingarorlof-fyrir-foreldra-a-innlendum-vinnumarkadi) and without the cache policy and it was all good.
Can you make sure it fixes your issue?

chore: add introspectionQueryResultData

---

apps/web/components/SideMenu/SideMenu.tsx

Side menu - Add keys to mapped elements

island.is / Add keys to mapped elements

---

libs/island-ui/core/src/lib/Timeline/Event.treat.ts
libs/island-ui/core/src/lib/Timeline/Timeline.tsx
package.json
yarn.lock

Moving modal to portal so it will render outside of layout, and using popperjs to position it on the button

island.is / timeline modal overflow

---

apps/air-discount-scheme/README.md

This is just a rough description of the project, if you think there is something that can be clearer especially for developers outside islandis please do comment!

Adding readme that describes ads project

---

apps/web/components/Header/Header.tsx
apps/web/components/SideMenu/SideMenu.stories.tsx
apps/web/components/SideMenu/SideMenu.treat.ts
apps/web/components/SideMenu/SideMenu.tsx
apps/web/context/MenuTabsContext/MenuTabsContext.ts
apps/web/i18n/useRouteNames.tsx
apps/web/layouts/main.tsx
apps/web/pages/_app.tsx

Web menu content and transition tweaks

---

apps/judicial-system/api/src/app/modules/user/user.controller.spec.ts
apps/judicial-system/api/src/app/modules/user/user.service.ts
apps/judicial-system/web/src/api/index.ts
apps/judicial-system/web/src/main.tsx
apps/judicial-system/web/src/routes/CreateDetentionRequest/StepOne/StepOne.tsx
apps/judicial-system/web/src/routes/CreateDetentionRequest/StepTwo/StepTwo.tsx
apps/judicial-system/web/src/routes/CreateDetentionRequest/index.ts
apps/judicial-system/web/src/routes/DetentionRequests/DetentionRequests.tsx
apps/judicial-system/web/src/shared-components/FormFooter/FormFooter.tsx
apps/judicial-system/web/src/shared-components/FormFooter/index.ts
apps/judicial-system/web/src/types.ts
apps/judicial-system/web/src/utils/parsers.ts
apps/judicial-system/web/src/utils/stepHelper.ts
apps/judicial-system/web/src/utils/utils.spec.ts
apps/judicial-system/web/src/utils/validate.ts
libs/service-portal/applications/src/index.ts
libs/service-portal/core/src/lib/navigation/paths.ts

Second screen of the flow completed with auto save as you fill it out.

Judicial system/step two

---

apps/api/src/api.graphql
apps/web/components/SideMenu/SideMenu.tsx
apps/web/graphql/fragmentTypes.json
apps/web/graphql/schema.ts
apps/web/layouts/main.tsx
apps/web/screens/queries/AlertBanner.tsx
libs/api/domains/cms/src/lib/cms.resolver.ts
libs/api/domains/cms/src/lib/dto/getAlertBanner.input.ts
libs/api/domains/cms/src/lib/generated/contentfulTypes.d.ts
libs/api/domains/cms/src/lib/models/alertBanner.model.ts
libs/api/domains/cms/src/lib/services.ts
libs/api/schema/src/lib/schema.d.ts
libs/island-ui/core/src/index.ts
libs/island-ui/core/src/lib/AlertBanner/AlertBanner.tsx

island.is / connect alert banner to contentful

---

scripts/Dockerfile

Due to time pressure we are taking this _very_ temporary measure to make a delivery for a demo.

Run containers as root

---

libs/island-ui/core/src/lib/Checkbox/Checkbox.stories.tsx
libs/island-ui/core/src/lib/Checkbox/Checkbox.treat.ts
libs/island-ui/core/src/lib/Checkbox/Checkbox.tsx

Positions the tooltip in large checkbox containers to the right

---

libs/island-ui/core/src/lib/Typography/Typography.treat.ts
libs/island-ui/core/src/lib/Typography/Typography.tsx

Added font weights, if font weight is not defined use default variant font weight

Island-ui / Typography fontweights support

---

apps/api/src/api.graphql
apps/web/components/FrontpageTabs/FrontpageTabs.treat.ts
apps/web/components/FrontpageTabs/FrontpageTabs.tsx
apps/web/graphql/schema.ts
apps/web/screens/queries/FrontpageSlides.tsx
libs/api/domains/cms/src/lib/generated/contentfulTypes.d.ts
libs/api/domains/cms/src/lib/models/frontpageSlider.model.ts
libs/api/domains/cms/src/lib/models/frontpageSliderList.model.ts
libs/api/schema/src/lib/schema.d.ts
package.json
yarn.lock

Web frontpage tabs animation

---

libs/island-ui/core/src/lib/Button/Button.stories.tsx
libs/island-ui/core/src/lib/Button/Button.treat.ts
libs/island-ui/core/src/lib/Button/Button.tsx

Added a red variant of the ghost button

Added red ghost variant button

---

libs/island-ui/core/src/lib/Grid/Grid.stories.tsx
libs/island-ui/core/src/lib/Grid/GridColumn/GridColumn.treat.ts
libs/island-ui/core/src/lib/Grid/GridColumn/GridColumn.tsx

island-ui / responsive order to grid column

---

.github/workflows/build.yml

To be used when defining protection for branches

Adding a fixed "success" job

---

libs/island-ui/core/src/lib/DatePicker/DatePicker.tsx

Changes recently made to the datepicker broke is's functionality for me, see 👇 
How it should work 👇

Replace inputValue with value

---

README.md

And yes, this is also a POC for forked repos CI #805

Make header Ísland, not Island (eyja)

---

apps/web/components/AboutLatestNews/AboutLatestNews.tsx
apps/web/components/BulletList/BulletList.tsx
apps/web/components/Categories/Categories.tsx
apps/web/components/FrontpageTabs/FrontpageTabs.tsx
apps/web/components/LatestNewsSection/LatestNewsSection.tsx
apps/web/components/LifeEventsCardsSection/LifeEventsCardsSection.tsx
apps/web/components/NewsCard/NewsCard.tsx
apps/web/components/Sidebar/Sidebar.tsx
apps/web/components/SidebarNavigation/SidebarNavigation.tsx
apps/web/screens/Article.tsx
apps/web/screens/Category/Category.tsx
libs/island-ui/core/src/lib/AccordionItem/AccordionItem.tsx

Fix headings structure to validate accessibility standards

Accessibility headings

---

apps/web/screens/NewsList.tsx

[Changes to news page](https://app.asana.com/0/1183498341031105/1193519544461017/f)
When entering the news page we display all news but not only the ones from the year of the most current news article.

Fetching all news instead of the year of the latest news

---

apps/air-discount-scheme/README.md
apps/air-discount-scheme/api.graphql
apps/air-discount-scheme/api/jest.config.js
apps/air-discount-scheme/api/src/app/modules/auth/auth.service.spec.ts
apps/air-discount-scheme/api/src/app/modules/auth/auth.service.ts
apps/air-discount-scheme/api/src/app/modules/auth/auth.types.ts
apps/air-discount-scheme/api/src/environments/environment.prod.ts
apps/air-discount-scheme/api/src/environments/environment.ts
apps/air-discount-scheme/api/test/environment.jest.ts

Store it as StringList in AWS Parameter Store

Store developer/admin ssn in AWS Parameter store

---

apps/web/screens/Category/Category.tsx

- Don't render a heading for single articles without subgroup.
- Don't render a heading for custom sorted articles that don't belong to a subgroup.
- Comment Category code better.

Website/ Category subgroup heading rendering

---

apps/web/screens/Search/Search.tsx

[Ítra stiku á leitarniðurstöðusíðu og fleiri subtasks tengt því
](https://app.asana.com/0/1183498341031105/1189048494837089/f
)
*Fix grouping in sidebar accordion, merge 'Allir flokkar' and 'Sjá flokka' in one
* Fix search results count on search page to show total when no specific category is selected

UI Iterations On Search Page

---

apps/air-discount-scheme/web/components/KeyValue/KeyValue.tsx
apps/air-discount-scheme/web/components/KeyValue/index.ts
apps/air-discount-scheme/web/components/index.ts
apps/air-discount-scheme/web/screens/Admin/Admin.tsx
apps/air-discount-scheme/web/screens/Admin/components/KeyValues/KeyValues.tsx
apps/air-discount-scheme/web/screens/Admin/components/KeyValues/index.ts
apps/air-discount-scheme/web/screens/Admin/components/Panel/Panel.tsx
apps/air-discount-scheme/web/screens/Admin/components/Summary/Summary.tsx
apps/air-discount-scheme/web/screens/Admin/components/index.ts
apps/air-discount-scheme/web/screens/Admin/types.d.ts

Show discount price in the table and redesign Summary in Admin UI
Vegagerdin wants the discount price in the table. To focus more on that,
a redesign of the Summary component was needed.

Redesign summary and focus on airline filter for rendering

---

libs/api/domains/content-search/src/lib/contentSearch.service.ts

Make autocomplete suggest completions in requested language

Autocomplete language

---

.github/CODEOWNERS

My team needs approval from island-is/core to commit code to our own project
e.g. https://github.com/island-is/island.is/pull/909

fix incorrect paths in CODEOWNERS

---

libs/api/domains/cms/src/lib/search/importers/article.service.ts
libs/api/domains/cms/src/lib/search/importers/lifeEventsPage.service.ts
libs/api/domains/cms/src/lib/search/importers/news.service.ts
libs/api/domains/cms/src/lib/search/importers/utils.ts

Content is currently json and short texts
To provide a better set for matching search queries

Search extract text from objects

---

apps/web/pages/en/life-event/[slug]/index.tsx
libs/api/domains/cms/src/lib/models/lifeEventPage.model.ts

Display english life events page

Added english life events page

---

libs/api/content-search/src/services/elastic.service.ts
libs/api/domains/cms/src/lib/search/contentful.service.ts
package.json
yarn.lock

- Made indexer throttle requests to Contentful
- Made elasticsaerch bulk index wait for response before importing next chunks

Search throttle requests

---

apps/web/components/DrawerMenu/DrawerMenu.tsx
apps/web/screens/Article.tsx
libs/island-ui/contentful/src/lib/StaticHtml/StaticHtml.treat.ts

[Ítra á útliti skv. hönnun
](https://app.asana.com/0/1183498341031105/1194387442432387/f)
* Remove extra spacing between Article Title and content
* Add spacing between Baby Article Title and content
* Add styling to ordered lists in rich html text
Removing extra spacing, before&after:
Add spacing on baby articles, before&after:
Styling ordered list, before&after

Ui article iterations

---

apps/api/src/api.graphql
apps/web/screens/queries/FrontpageSlides.tsx
libs/api/domains/cms/src/lib/contentful.repository.ts
libs/api/domains/cms/src/lib/models/frontpageSlider.model.ts

Frontpage slider had unuseed fields

Removed unsued field

---

libs/island-ui/core/src/lib/Timeline/Timeline.tsx

labels and read more link

---

apps/web/screens/Article.tsx

Added missing imports

---

apps/service-portal/src/screens/Dashboard/Dashboard.tsx

Remove Hero from Dashboard

---

libs/island-ui/core/src/lib/Box/Box.tsx
libs/island-ui/core/src/lib/Box/useBoxStyles.ts
libs/island-ui/core/src/lib/Grid/GridColumn/GridColumn.tsx
libs/island-ui/core/src/lib/Hidden/Hidden.tsx

New Box changes weren't working as we thought. Restore it back to the previous version so I can take a closer look.

Restore Box/Hidden to fix layout

---

libs/island-ui/core/src/lib/Footer/Footer.tsx
libs/island-ui/core/src/lib/Link/ExternalLink/ExternalLink.tsx
libs/island-ui/core/src/lib/Link/Link.treat.ts
libs/island-ui/core/src/lib/Link/Link.tsx

https://app.asana.com/0/1183498341031105/1194742817343264
Implement new footer

island-ui/ Implement new footer design

---

apps/judicial-system/web/src/api/index.ts
apps/judicial-system/web/src/index.html
apps/judicial-system/web/src/main.tsx
apps/judicial-system/web/src/routes/CreateDetentionRequest/StepOne/StepOne.spec.tsx
apps/judicial-system/web/src/routes/CreateDetentionRequest/StepOne/StepOne.tsx
apps/judicial-system/web/src/routes/CreateDetentionRequest/StepTwo/StepTwo.tsx
apps/judicial-system/web/src/routes/DetentionRequests/DetentionRequests.tsx
apps/judicial-system/web/src/routes/Overview/Overview.treat.ts
apps/judicial-system/web/src/routes/Overview/Overview.tsx
apps/judicial-system/web/src/shared-components/FormFooter/FormFooter.tsx
apps/judicial-system/web/src/shared-components/Modal/Modal.treat.ts
apps/judicial-system/web/src/shared-components/Modal/Modal.tsx
apps/judicial-system/web/src/types.ts
apps/judicial-system/web/src/utils/constants.ts
apps/judicial-system/web/src/utils/formatters.ts
libs/island-ui/core/src/lib/Box/useBoxStyles.treat.ts

When a prosecutor goes from step one to step two of the form an heads up SMS should be sent to the judge on call. Also, when a prosecutor submits the claim, an SMS should be sent, notifying the judge.

Judicial system/modal pop

---

apps/air-discount-scheme/README.md
apps/air-discount-scheme/web/graphql/errorLink.ts
apps/air-discount-scheme/web/screens/Admin/Admin.tsx

Handle forbidden on component level
The component was already handling it and it was a bad UX to redirect the user to another 404 route.

Handle forbidden on component level

---

apps/web/screens/Home.tsx

Fix namespace object

---

README.md

Not sure if this is the right link but pretty sure that reddit.com is the wrong link 😅

Change Digital Iceland link 

---

.github/workflows/build.yml

Cache v1 is known to be slow. See https://github.com/actions/cache/issues/381
Faster build times
Build times are slow

Update cache actions to v2

---

apps/air-discount-scheme/web/components/Content/Content.tsx

Set default value for link list
Getting weird error on prod, this might fix it

Ads / links as default empty array

---

.github/workflows/build.yml

Login to ECR only when planning on publishing Docker images

---

apps/api/src/api.graphql
libs/api/domains/cms/src/lib/models/article.model.ts
libs/api/domains/cms/src/lib/models/subArticle.model.ts
libs/api/schema/src/lib/schema.d.ts

Empty articles are causing errors
Improve stability af api and web

Hide empty articles

---

apps/web/screens/Category/Category.tsx

Page did not return 404 error on category not found
404 is expected

Web category not found

---

apps/web/components/BackgroundImage/BackgroundImage.treat.ts
apps/web/components/BackgroundImage/BackgroundImage.tsx
apps/web/components/Card/Card.treat.ts
apps/web/components/Card/Card.tsx
apps/web/components/LifeEventsCardsSection/LifeEventsCardsSection.tsx
apps/web/screens/Category/Category.tsx
apps/web/screens/Search/Search.tsx
apps/web/screens/queries/Search.tsx
libs/island-ui/core/src/lib/AccordionItem/AccordionItem.treat.ts
libs/island-ui/core/src/lib/LinkCard/LinkCard.treat.ts
libs/island-ui/core/src/lib/LinkCard/LinkCard.tsx

- Added a hover color to the LinkCard.
- Tweak the Card when it has an image to look decent in all widths.
It had to be done!

More web fixes and tweaks

---

apps/web/components/FrontpageTabs/FrontpageTabs.tsx

https://app.asana.com/0/1183498341031105/1194989489699359

Website/ Allow news in frontpage slider

---

apps/web/screens/Home.tsx
libs/island-ui/core/src/lib/Tag/Tag.stories.tsx
libs/island-ui/core/src/lib/Tag/Tag.treat.ts
libs/island-ui/core/src/lib/Tag/Tag.tsx

https://app.asana.com/0/1183498341031105/1193519544461017
Give Tag boolean that renders a red dot above it, demanding attention.
We want to indicate what tag needs attention from the user.

island-ui/ Tag attention

---

apps/services/search-indexer/config/template-is.json
apps/services/search-indexer/src/migrate/aws.ts
apps/services/search-indexer/src/migrate/dictionary.ts
apps/services/search-indexer/src/migrate/elastic.ts

Added more logging to ES migrate
Don't fail if migrate cannot dissociate AWS ES package
fix typo
- Update ElasticSearch analyzers
- Fix issues in ES migration script and add more logging
- These ElasticSearch analyzers will improve search icelandic results
- Prevent issues with ElasticSearch configuration in the future.
- Improve logging for easier debugging of migrate script if other issues occur

Updated ES analyzers

---

apps/web/i18n/routeNames.tsx

Adding a route back to home page

---

apps/api/src/api.graphql
apps/web/graphql/fragmentTypes.json
apps/web/graphql/schema.ts
apps/web/hooks/useScrollSpy.ts
apps/web/screens/AboutPage/AboutPage.tsx
apps/web/screens/AboutPage/Sidebar.treat.ts
apps/web/screens/queries/AboutPage.ts
apps/web/screens/queries/fragments.ts
libs/api/domains/cms/src/lib/generated/contentfulTypes.d.ts
libs/api/domains/cms/src/lib/models/aboutPage.model.ts
libs/api/domains/cms/src/lib/models/pageHeader.model.ts
libs/api/domains/cms/src/lib/models/slice.model.ts
libs/api/schema/src/lib/schema.d.ts

* Change the "scroll-spy" to an updated implementation
* Remove "PageHeader" from the slice union type
* Old scroll-spy was slow and buggy
* PageHeader being a slice type was causing issues without any real benefit

Some updates/fixes to the about page

---

apps/web/components/LifeEventsCardsSection/LifeEventsCardsSection.tsx
apps/web/screens/Home.tsx

Fix regression after the svunta effect was removed.

Website/ Bring back Section bleed

---

apps/judicial-system/api/migrations/20200922125905-update-case.js
apps/judicial-system/api/src/app/modules/case/dto/updateCase.dto.ts
apps/judicial-system/api/src/app/modules/case/e2e/case.spec.ts
apps/judicial-system/api/src/app/modules/case/models/case.model.ts

See description
To be able to save a case with a court case number

Extend Case

---

apps/web/components/BulletList/BulletList.tsx
apps/web/components/DrawerMenu/DrawerMenu.tsx
apps/web/components/FixedNav/FixedNav.tsx
apps/web/components/SideMenu/SideMenu.treat.ts
apps/web/components/SideMenu/SideMenu.tsx
apps/web/screens/Article.tsx
apps/web/screens/Category/Category.tsx
libs/island-ui/core/src/lib/Input/Input.mixins.ts
libs/island-ui/core/src/lib/Typography/Typography.treat.ts

Multiple tweaks/fixes explained in each commit.
Many minor todos being completed at once.

Web many tweaks

---

apps/web/components/LatestNewsSection/LatestNewsSection.tsx
apps/web/screens/NewsItem.tsx

read more link on frontpage and breadcrumbs on detail news page

---

apps/web/screens/AboutPage/AboutPage.tsx

island.is / mobile drawer to about page

---

.github/workflows/build.yml
.gitignore
scripts/get-files-touched-by.sh
scripts/test.sh

Ignore generated files cache

---

apps/web/i18n/withLocale.tsx
apps/web/pages/_error.tsx

- Added empty path defaults
- To stabilize site

Empty path defaults

---

libs/island-ui/core/src/index.ts
libs/island-ui/core/src/lib/ProfileCard/ProfileCard.spec.tsx
libs/island-ui/core/src/lib/ProfileCard/ProfileCard.stories.tsx
libs/island-ui/core/src/lib/ProfileCard/ProfileCard.treat.ts
libs/island-ui/core/src/lib/ProfileCard/ProfileCard.tsx

related to this ticket https://app.asana.com/0/1183498341031105/1193953598815089
Profile card to display photo and basic info
To show persons profile

isalnd-ui / Profile card

---

apps/web/components/FrontpageTabs/FrontpageTabs.tsx

https://app.asana.com/0/1183498341031105/1194989489699359

Website/ Allow 'pages' in slider

---

apps/judicial-system/api/src/app/modules/user/user.service.ts

Judicial system/test users

---

apps/web/i18n/routeNames.tsx
apps/web/pages/en/organizations/um-island-is/[slug]/index.ts
apps/web/pages/en/organizations/um-island-is/index.ts
apps/web/pages/stofnanir/um-island-is/[slug]/index.ts
apps/web/pages/stofnanir/um-island-is/index.ts

Fixing link on home page

---

apps/judicial-system/web/src/routes/CreateDetentionRequest/StepTwo/StepTwo.tsx
apps/judicial-system/web/src/routes/DetentionRequests/DetentionRequests.tsx

Minor tweeks

---

libs/api/domains/content-search/src/lib/contentSearch.resolver.ts
libs/elastic-indexing/src/environments/environment.prod.ts
libs/elastic-indexing/src/environments/environment.ts
libs/elastic-indexing/src/lib/dto/syncInput.input.ts
libs/elastic-indexing/src/lib/indexing.controller.ts

- Made sync endpoints check tokens
- To remove attack vector

Token check in sync endpoints

---

apps/web/screens/Article.tsx
libs/api/domains/cms/src/lib/cms.contentful.service.ts

Add support for short version of article title
Article title is too long for the UI sometimes, in which case we use the short title if available and fallback to the original title

Article short title

---

apps/web/layouts/main.tsx
libs/island-ui/core/src/lib/Footer/Footer.tsx

#260  What
Missing translatable string
Was only in Icelandic

Add external title string prop to footer

---

libs/island-ui/core/src/lib/Select/Select.treat.ts

Adding a cursor to select icon and options in select box

---

apps/web/screens/AboutPage/AboutPage.treat.ts

https://app.asana.com/0/1183498341031105/1195074272494336
fix height for image

island.is / max height for tabs images

---

apps/web/components/FrontpageTabs/FrontpageTabs.tsx

Frontpage fix

---

libs/elastic-indexing/src/environments/environment.prod.ts
libs/elastic-indexing/src/environments/environment.ts

- Env file indexer fix
- Does not work as expected

Env file indexer fix

---

apps/web/hooks/useScrollSpy.ts

- useScrollSpy was causing errors on single articles

Use scrollspy fix

---

apps/web/screens/NewsList.tsx

Pagination on news page

---

libs/api/domains/cms/src/lib/cms.contentful.service.ts
libs/api/domains/cms/src/lib/models/organization.model.ts

Error on organization page

---

apps/web/screens/AboutPage/AboutPage.tsx
apps/web/screens/AboutPage/Sidebar.tsx

https://app.asana.com/0/1183498341031105/1193892556997269

Island.is / About sidebar cleanup

---

libs/island-ui/contentful/src/lib/TeamList/TeamList.tsx
libs/island-ui/core/src/lib/ProfileCard/ProfileCard.tsx

island.is / team equal height cards

---

libs/island-ui/contentful/src/lib/ProcessEntry/ProcessEntry.tsx

fix layout issue
looks ugly
before
after

bugfix for long process entry button text

---

apps/web/screens/AboutPage/RenderForm.tsx

Deal with error response strings arriving in icelandic from Mailchimp.
We need to catch them and return our own messages to the UI.

Website/ Mailchimp error translations

---

libs/island-ui/core/src/lib/Timeline/Timeline.tsx

island.is / add numbers back to timeline

---

apps/web/components/AboutLatestNews/AboutLatestNews.tsx
apps/web/screens/AboutPage/AboutPage.tsx
libs/island-ui/core/src/lib/Link/ArrowLink/ArrowLink.tsx

island.is / About news section

---

apps/web/components/FixedNav/FixedNav.tsx

Make logo in fixed nav focusable and clickable
Should have the same behaviour as the default header

Clickable logo in fixe nav

---

.github/.kodiak.toml

Prep work so we can continue with #938
Prepare for kodiakhq.com merge bot
Because we want merge bots

Add minimal config for Kodiak.

---

workspace.json

This reverts commit 1628d57a914d51d3c9309246ede1c34017ac08ac.

Revert "Fixed docker image key (#1061)"

---

libs/api/content-search/src/queries/search.ts

Added termPool field to search query + updated boosters.
More relevant search results

Search query fields and boosters updated

---

libs/island-ui/core/src/lib/RadioButton/RadioButton.stories.tsx
libs/island-ui/core/src/lib/RadioButton/RadioButton.treat.ts
libs/island-ui/core/src/lib/RadioButton/RadioButton.tsx

According to the design there should be variant sizes of radio buttons. This PR implements a large radio button
See ☝️
Regular ☝️
Large ☝️

Adds a large radio button

---

.github/actions/dist/index.js
.github/actions/main.ts

New build for codeowners check was being considered a last good build
and we could not retag any images.
TODO: Fail build if we can't retag images!

Fix CI due to new build

---

apps/judicial-system/api/src/app/modules/auth/auth.service.ts
apps/judicial-system/api/src/app/modules/case/case.controller.ts
apps/judicial-system/api/src/app/modules/case/case.service.ts
apps/judicial-system/api/src/app/modules/user/user.controller.ts
apps/judicial-system/api/src/app/modules/user/user.service.ts
apps/judicial-system/api/src/openapi.yaml

Adds a GET endpoint with limited access for testing purposes
We have no user management system and this will make testing easier

Judicial System: Adds a temporary endpoint to manage user roles

---

.github/workflows/build.yml

To support our release strategy

Adding hotfix branches to the list of builds

---

apps/web/screens/Category/Category.tsx

- Increase size in get articles query
- Articles are missing from groups due to article size limit

Category article size

---

workspace.json

Fix asset glob patterns.
To fix deployment of gjafakort and air-discount-scheme after nx upgrade.

Fix nx10 regression with asset glob patterns

---

apps/judicial-system/api/src/app/modules/case/case.controller.ts
apps/judicial-system/api/src/app/modules/case/case.service.ts
apps/judicial-system/api/src/app/modules/case/dto/transitionCase.dto.ts
apps/judicial-system/api/src/openapi.yaml
libs/judicial-system/types/src/lib/types.ts

Adds an endpoint for state transitions
To provide more granular control of state transitions

Judicial system/state transistions

---

libs/island-ui/theme/src/lib/theme.ts

island-ui / fallback fonts

---

apps/web/components/Timeline/Event.treat.ts
apps/web/components/Timeline/Timeline.tsx

https://app.asana.com/0/1181603131793397/1196335150068948/f

island.is / Timeline responsive modal

---

apps/judicial-system/web/src/routes/Prosecutor/Overview/Overview.tsx
apps/judicial-system/web/src/shared-components/FormFooter/FormFooter.tsx

https://app.asana.com/0/322488613152836/1196568599290502
https://app.asana.com/0/322488613152836/1196568599290500
- Add national id to the prosecutor overview screen and refactor so that I put localstorage data into component state.
- Remove the ability to add confirmation text under the "forward" button in form footer.
- Remove info on accused and court from modal.
To address issues from acceptance testing

Judicial system/att

---

apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepOne/StepOne.tsx
apps/judicial-system/web/src/utils/utils.spec.ts
apps/judicial-system/web/src/utils/validate.ts

https://app.asana.com/0/inbox/322488613152834/1196568599290505/1196648058205981
Adds input validation for police case number and national id.
For better usability

Judicial system/validation

---

apps/judicial-system/web/src/api/index.ts
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepOne/StepOne.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepTwo/StepTwo.tsx

When running the project without a user, it would crash. This would happen because sometimes cases in localstorage are not set and we need to make sure that that data is set if we want to work with it.

Better side effect handling

---

apps/judicial-system/web/src/routes/Judge/Confirmation/Confirmation.tsx
apps/judicial-system/web/src/routes/Judge/CourtRecord/CourtRecord.tsx
apps/judicial-system/web/src/routes/Judge/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Judge/Ruling/Ruling.tsx
apps/judicial-system/web/src/routes/Login/App.spec.tsx
apps/judicial-system/web/src/routes/Login/Login.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepOne/StepOne.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepTwo/StepTwo.tsx
apps/judicial-system/web/src/routes/Prosecutor/DetentionRequests/DetentionRequests.tsx
apps/judicial-system/web/src/routes/Prosecutor/Overview/Overview.tsx

https://app.asana.com/0/1189271618154957/1195315258966969
Set the following titles for screens 
**Login:** Réttarvörslugátt
**Dómari - staðfesta:** Staðfesting - Réttarvörslugátt
**Dómari - þingbók:** Þingbók - Réttarvörslugátt
**Dómari - yfirlit:** Yfirlit - Réttarvörslugátt
**Dómari - úrskurður:** Úrskurður - Réttarvörslugátt
**Dómari og ákærandi - yfirlit yfir kröfur:** Kröfur - Réttarvörslugátt
**Ákærandi - skref 1:** Grunnupplýsingar - Réttarvörslugátt
**Ákærandi - skref 2:** Málsatvik og lagarök - Réttarvörslugátt
**Ákærandi - yfirlit:** Yfirlit - Réttarvörslugátt
UX

Set page titles

---

.github/workflows/build.yml
libs/island-ui/core/src/lib/Text/Text.tsx
libs/service-portal/applications/src/components/ApplicationCard/ApplicationCard.tsx

Fix linting in CI

---

apps/judicial-system/web/src/routes/Judge/Confirmation/Confirmation.tsx
apps/judicial-system/web/src/routes/Judge/CourtRecord/CourtRecord.tsx
apps/judicial-system/web/src/routes/Judge/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Judge/Ruling/Ruling.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepOne/StepOne.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepTwo/StepTwo.tsx
apps/judicial-system/web/src/routes/Prosecutor/Overview/Overview.tsx
apps/judicial-system/web/src/utils/stepHelper.tsx

https://app.asana.com/0/1189271618154957/1196536229204556
See ☝️
It's a requirement

Add form stepper to flow

---

apps/web/components/SearchInput/SearchInput.tsx
apps/web/screens/Search/Search.tsx
libs/island-ui/core/src/lib/Accordion/AccordionItem/AccordionItem.tsx

* links in searchinput werer broken
* padding in sidebar was off

Fixing search input link bug and padding in sidebar

---

apps/judicial-system/web/src/routes/Judge/Overview/Overview.spec.tsx
apps/judicial-system/web/src/routes/Judge/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Prosecutor/Overview/Overview.spec.tsx
apps/judicial-system/web/src/routes/Prosecutor/Overview/Overview.tsx
libs/judicial-system/formatters/src/lib/formatters.ts

https://app.asana.com/0/1189271618154957/1197580479863577
See ☝️
It had not been in the design until now.

Judicial system/custody provisions in overview

---

apps/web/screens/Article.tsx

Fix tengt efni links

---

apps/web/components/FrontpageTabs/FrontpageTabs.tsx

Stop using makepath for page

---

libs/api/domains/cms/src/lib/models/featured.model.ts
libs/api/domains/cms/src/lib/models/homepage.model.ts

Links are empty in elnglish
- Filtered out empty links
- To hide empty links on english page

Addedfilter to tags for english

---

scripts/Dockerfile.proxy

Supports #1215 
Reflecting changes in the proxy in K8s
To make this work again.

Fix for ES proxy

---

libs/island-ui/core/src/lib/Accordion/Accordion.stories.mdx
libs/island-ui/core/src/lib/Box/Box.stories.mdx
libs/island-ui/core/src/lib/Divider/Divider.stories.mdx
libs/island-ui/core/src/lib/Divider/Divider.tsx
libs/island-ui/core/src/lib/FormStepper/FormStepper.stories.mdx
libs/island-ui/core/src/lib/Logo/Logo.stories.tsx
libs/island-ui/core/src/lib/NewsletterSignup/NewsletterSignup.stories.tsx
libs/island-ui/core/src/lib/Text/Text.stories.mdx
libs/island-ui/core/src/lib/Tooltip/Tooltip.stories.mdx
libs/island-ui/core/src/lib/Tooltip/Tooltip.tsx
libs/island-ui/storybook/config/preview.js

chore: fix deprecated stuff

---

libs/shared/form-fields/src/lib/RadioController/RadioController.tsx

Fix changes that were overwritten by the merge: 
https://github.com/island-is/island.is/pull/1269

Application System: Merge fix

---

apps/web/components/DrawerMenu/DrawerMenu.tsx
apps/web/components/SideMenu/SideMenu.treat.ts
apps/web/screens/NewsItem.tsx
libs/island-ui/core/src/lib/Breadcrumbs/Breadcrumbs.tsx

Use Typography in Breadcrumbs for now

---

apps/air-discount-scheme/web/screens/Admin/components/Summary/Summary.tsx
apps/air-discount-scheme/web/screens/Admin/types.d.ts

Show all states in summary
Admin users want to see the total sum of flight-legs booked with Loftbru.

Show all states in summary

---

apps/web/screens/Search/Search.tsx

Fix search count per category to display pagination and messages correctly

Fix total search count on search page

---

scripts/ci/Dockerfile

Fixing of Docker builds
We need those docker images

Fixing docker-static builds

---

apps/judicial-system/api/src/app/modules/case/e2e/case.spec.ts

Adds new case fields to tests.
Better test coverage.

Judicial System: Updates tests

---

libs/service-portal/graphql/src/lib/client.ts

We dont want to use the normal basepath while developing, this fixes that problem by checking location.
Fixing graphql fetch on localhost
Nothing is being fetched locally

Dev path for graphql in service portal

---

apps/judicial-system/web/src/routes/Judge/Confirmation/Confirmation.spec.tsx
apps/judicial-system/web/src/routes/Judge/Confirmation/Confirmation.tsx
apps/judicial-system/web/src/routes/Judge/Ruling/RulingStepTwo.tsx

https://app.asana.com/0/1197628843274291/1198214696234218
See up☝️
It's a bug

Judicial system/Announcement fixes

---

apps/judicial-system/api/seeders/20200927194724-user.js
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepOne/StepOne.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepTwo/StepTwo.spec.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepTwo/StepTwo.tsx
apps/judicial-system/web/src/types.ts
apps/judicial-system/web/src/utils/stepHelper.tsx
apps/judicial-system/web/src/utils/utils.spec.ts

A part of https://app.asana.com/0/1197628843274291/1198009073131848
See ☝️
UX

Judicial system/required pt2

---

apps/skilavottord/ws/.sequelizerc
apps/skilavottord/ws/bin/startup.sql
apps/skilavottord/ws/db/migrations/20201008200611-vehicle_owner.js
apps/skilavottord/ws/db/migrations/20201008210611-vehicle.js
apps/skilavottord/ws/db/migrations/20201008220611-recycling_request.js
apps/skilavottord/ws/db/migrations/20201008230611-gdpr.js
apps/skilavottord/ws/db/migrations/20201008240611-recycling-partners.js
apps/skilavottord/ws/db/seeders/20201010101010-seed-vehicleOwners.js
apps/skilavottord/ws/db/seeders/20201010101011-seed-vehicle.js
apps/skilavottord/ws/db/seeders/20201010111010-seed-gdpr.js
apps/skilavottord/ws/db/seeders/20201010111010-seed-recycling-request.js
apps/skilavottord/ws/db/seeders/20201010121010-seed-recycling-partner.js
apps/skilavottord/ws/sequelize.config.js
apps/skilavottord/ws/src/app/app.module.ts
apps/skilavottord/ws/src/app/modules/gdpr/gdpr.module.ts
apps/skilavottord/ws/src/app/modules/gdpr/gdpr.resolver.ts
apps/skilavottord/ws/src/app/modules/gdpr/index.ts
apps/skilavottord/ws/src/app/modules/gdpr/models/dto/gdpr.dto.ts
apps/skilavottord/ws/src/app/modules/gdpr/models/dto/index.ts
apps/skilavottord/ws/src/app/modules/gdpr/models/gdpr.model.ts
apps/skilavottord/ws/src/app/modules/gdpr/models/gdpr.service.ts
apps/skilavottord/ws/src/app/modules/gdpr/models/index.ts
apps/skilavottord/ws/src/app/modules/index.ts
apps/skilavottord/ws/src/app/sequelizeConfig.service.ts

gdpr graphql-db-module

---

apps/judicial-system/web/src/routes/Judge/Confirmation/Confirmation.tsx
apps/judicial-system/web/src/routes/Judge/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Judge/Ruling/RulingStepOne.tsx
apps/judicial-system/web/src/routes/Judge/Ruling/RulingStepTwo.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepOne/StepOne.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepTwo/StepTwo.tsx
apps/judicial-system/web/src/routes/Prosecutor/Overview/Overview.tsx
apps/judicial-system/web/src/types.ts

https://app.asana.com/0/1197628843274291/1196539929931215
Uses the designated prosecutor and judge when showing overviews.
This is required.

Judicial System: Prosecutor and judge in overviews

---

apps/judicial-system/web/src/routes/DetentionRequests/DetentionRequests.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepOne/StepOne.spec.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepOne/StepOne.tsx

When opening an existing request, you'd sometimes get wrong data in the fields.
It's a bug

Fix issue with localstorage

---

apps/skilavottord/ws/db/migrations/20201008210611-vehicle.js
apps/skilavottord/ws/src/app/app.module.ts
apps/skilavottord/ws/src/app/modules/models.ts
apps/skilavottord/ws/src/app/modules/vehicle/vehicle.module.ts
apps/skilavottord/ws/src/app/modules/vehicle/vehicle.resolver.ts
apps/skilavottord/ws/src/app/modules/vehicle/vehicle.service.ts

vehicle model added

---

apps/judicial-system/web/src/routes/DetentionRequests/DetentionRequests.tsx
apps/judicial-system/web/src/routes/Login/Login.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepOne/StepOne.tsx
apps/judicial-system/web/src/shared-components/AccordionListItem/AccordionListItem.tsx
apps/judicial-system/web/src/shared-components/CourtDocument/CourtDocument.tsx
apps/judicial-system/web/src/shared-components/Header/Header.tsx
apps/judicial-system/web/src/shared-components/Modal/Modal.tsx
apps/judicial-system/web/src/utils/stepHelper.tsx

See ☝️
The Typography component has been deprecated.

Replace all occurrences of Typography with Text

---

libs/island-ui/core/src/lib/Button/Button.treat.ts
libs/island-ui/core/src/lib/Button/Button.tsx
libs/island-ui/core/src/lib/IconRC/Icon.treat.ts
libs/island-ui/core/src/lib/IconRC/Icon.tsx

* Fluid button
* responsive button icon

island-ui / Fluid button and responsive button icon

---

libs/island-ui/core/src/lib/ActionCard/ActionCard.tsx
libs/island-ui/core/src/lib/TopicCard/TopicCard.stories.tsx

ActionCard: Make it look nice on mobile and use Button's icons correctly.
TopicCard: Fix story TS error and add accordion usage example to it.

island-ui/ Card tweaks

---

libs/auth-api-lib/migrations/20200819053200-create-resources.js
libs/auth-api-lib/migrations/20200828110359-create-clients.js
libs/auth-api-lib/seeders/20200819081415-identity-resources.js
libs/auth-api-lib/seeders/20200825111626-api-scopes.js
libs/auth-api-lib/seeders/20200825121317-api-resources.js
libs/auth-api-lib/seeders/20200831152526-clients.js
libs/auth-api-lib/src/lib/entities/dto/user-identity.dto.ts
libs/auth-api-lib/src/lib/entities/models/api-resource-scope.model.ts
libs/auth-api-lib/src/lib/entities/models/api-resource-secret.model.ts
libs/auth-api-lib/src/lib/entities/models/api-resource-user-claim.model.ts
libs/auth-api-lib/src/lib/entities/models/api-resource.model.ts
libs/auth-api-lib/src/lib/entities/models/api-scope-user-claim.model.ts
libs/auth-api-lib/src/lib/entities/models/api-scope.model.ts
libs/auth-api-lib/src/lib/entities/models/client.model.ts

Removed domain from db and models. Fixed active bug in dto.

---

libs/island-ui/core/src/lib/DatePicker/DatePicker.treat.ts
libs/island-ui/core/src/lib/DatePicker/DatePicker.tsx

Replace the deprecated Icon and Typography components with the new components.
To follow the design more closely.

Island ui/datepicker refactor

---

apps/application-system/form/src/routes/Application.tsx
libs/application/core/src/lib/formUtils.ts
libs/application/core/src/types/Form.ts
libs/application/templates/reference-template/src/forms/ExampleForm.ts
libs/application/templates/reference-template/src/forms/messages.ts

Use values in formatText function
To be able to use application context as values for localized strings

Values in format text

---

apps/application-system/form/webpack.config.js

Minify noice from split-chunks in webpack
To much noice in terminal 

Silence webpack output

---

apps/service-portal/src/components/Greeting/Greeting.tsx

use evening greeting between 18:00 and 3:00
Personalize the user experience more

Service Portal / Time based greeting

---

apps/api/src/app/app.module.ts
libs/api/domains/user-profile/src/lib/userProfile.module.ts

UserProfileService: Env service url variable for gql api

---

apps/judicial-system/web/src/routes/Judge/Ruling/RulingStepOne.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepOne/StepOne.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepTwo/StepTwo.tsx

https://app.asana.com/0/inbox/322488613152834/1198200136361895/1198902608987438
Save case when users change date fields, not just time fields like before.
It's a bug

Judicial-system/Save date changes

---

workspace.json

glob added to workspace json

---

apps/web/screens/AboutPage/RenderForm.tsx
libs/island-ui/core/src/lib/NewsletterSignup/NewsletterSignup.tsx

Adds onClick to handle formik submit on the button.
The new Button text variant is a span element so form submit was broken.

Add onClick to Newsletter form

---

workspace.json

Fixing sequalize init error on dev
Working services are good

Fix for services-user-profile assets

---

workspace.json

Adding migrations to assets
Needed for services-user-profile

Migrations added to assets

---

.github/workflows/push.yml

Avoid red builds on branch creation
This started happening after #1359 was merged

Avoid red builds on branch creation

---

workspace.json

Remove seeders

---

apps/skilavottord/ws/src/app/modules/gdpr/gdpr.resolver.ts
apps/skilavottord/ws/src/app/modules/gdpr/gdpr.service.ts
apps/skilavottord/ws/src/app/modules/recycling.partner/recycling.partner.resolver.ts
apps/skilavottord/ws/src/app/modules/recycling.partner/recycling.partner.service.ts
apps/skilavottord/ws/src/app/modules/recycling.request/recycling.request.resolver.ts
apps/skilavottord/ws/src/app/modules/vehicle.owner/vehicle.owner.resolver.ts
apps/skilavottord/ws/src/app/modules/vehicle.owner/vehicle.owner.service.ts
apps/skilavottord/ws/src/app/modules/vehicle/vehicle.resolver.ts
apps/skilavottord/ws/src/app/modules/vehicle/vehicle.service.ts

logging update debug to info

---

apps/skilavottord/ws/src/app/modules/vehicle.owner/vehicle.owner.resolver.ts

testing deployment

---

apps/judicial-system/api/src/app/modules/case/case.pdf.ts

https://app.asana.com/0/1197628843274291/1198562799851549
https://app.asana.com/0/1197628843274291/1198560357295548
☝️ 
This is required

Judicial System: Pdf updates

---

workspace.json

Api correctly serve env vars

---

libs/auth-api-lib/src/lib/auth/current-user.decorator.ts
libs/auth-api-lib/src/lib/auth/jwt.payload.ts
libs/auth-api-lib/src/lib/auth/jwt.strategy.ts
libs/auth-api-lib/src/lib/auth/user.ts

Return typed user from payload.

---

apps/judicial-system/api/src/app/modules/case/case.pdf.ts

https://app.asana.com/0/1197628843274291/1198899954964768
☝️ 
Feedback from users.
See attachments in issue ☝️

Judicial System: Updates ruling pdf for pilot

---

libs/island-ui/core/src/lib/Select/Select.treat.ts
libs/island-ui/core/src/lib/Select/Select.tsx

island-ui / Select - add required star

---

apps/web/components/Timeline/Timeline.treat.ts

island.is / Timeline Capitalization

---

libs/island-ui/core/src/lib/Button/Button.tsx

Revert unintended changes to Button

---

apps/service-portal/src/components/Header/Header.tsx
apps/service-portal/src/components/Notifications/NotificationMenuTrigger/NotificationMenuTrigger.tsx
apps/service-portal/src/components/UserMenu/UserMenu.tsx
libs/island-ui/core/src/lib/IconRC/iconMap.ts
libs/island-ui/core/src/lib/IconRC/icons/Notifications.tsx
libs/island-ui/core/src/lib/IconRC/icons/NotificationsOutline.tsx

Rework buttons in header to use new button component
Add Notifcations to icon set and replace icon in notification button
Bring header closer to design

Service portal/header buttons

---

apps/api/src/app/app.module.ts
apps/api/src/app/environments/environment.prod.ts
apps/api/src/app/environments/environment.ts
libs/api/domains/documents/src/lib/document.connection.ts
libs/api/domains/documents/src/lib/document.module.ts
libs/api/domains/documents/src/lib/document.resolver.ts
libs/api/domains/documents/src/lib/document.service.ts
libs/api/domains/documents/src/lib/dto/listDocumentsInput.ts

service-portal / guards and envs

---

libs/service-portal/applications/src/screens/ApplicationListWip/ApplicationListWip.tsx
libs/service-portal/applications/src/screens/ApplicationListWip/ApplicationlistWip.treat.ts
libs/service-portal/core/src/components/NavigationScreen/Card/Card.treat.ts
libs/service-portal/core/src/components/NavigationScreen/Card/Card.tsx
libs/service-portal/documents/src/screens/Overview/Overview.tsx
libs/service-portal/graphql/src/hooks/applications/useApplicantApplications.ts
libs/service-portal/graphql/src/hooks/applications/useAssigneeApplications.ts
libs/service-portal/graphql/src/hooks/documents/useListDocuments.ts
libs/service-portal/graphql/src/lib/queries/listDocuments.ts
libs/service-portal/settings/src/screens/DelegationGreeting/DelegationGreeting.treat.ts
libs/service-portal/settings/src/screens/DelegationGreeting/DelegationGreeting.tsx

opacity reduced and tag added to wip blur cards
Follow new implementation of design

WIP cards rework

---

apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepTwo/StepTwo.tsx

https://app.asana.com/0/1197628843274291/1198888041867395
Added a info bubble next to Greinargerð um málsatvik og lagarök title
For clarity

Judicial-system/Added a info bubble

---

libs/island-ui/core/src/lib/IconRC/iconMap.ts
libs/island-ui/core/src/lib/IconRC/icons/Download.tsx
libs/island-ui/core/src/lib/IconRC/icons/DownloadOutline.tsx
libs/service-portal/core/src/components/ActionCard/ActionCard.tsx

- Added Download Icon.
- Updated Document Card

New Download Icon

---

apps/services/user-profile/src/app/user-profile/verification.service.ts
apps/services/user-profile/src/environments/environment.prod.ts
apps/services/user-profile/src/environments/environment.ts

User profile change email

---

libs/service-portal/core/src/components/ActionCard/ActionCard.tsx

chore: updated actionCard iconType to outline

---

apps/services/user-profile/src/app/user-profile/verification.service.ts

Service Portal email fix href tag

---

apps/services/user-profile/src/app/user-profile/verification.service.ts

Service portal email a href fixed

---

apps/skilavottord/ws/src/app/modules/car/car.resolver.ts
apps/skilavottord/ws/src/app/modules/carowner/carowner.resolver.ts
apps/skilavottord/ws/src/app/modules/gdpr/gdpr.resolver.ts
apps/skilavottord/ws/src/app/modules/recycling.partner/recycling.partner.resolver.ts
apps/skilavottord/ws/src/app/modules/recycling.request/recycling.request.resolver.ts
apps/skilavottord/ws/src/app/modules/recyclingPartner/recyclingPartner.resolver.ts
apps/skilavottord/ws/src/app/modules/vehicle.owner/vehicle.owner.resolver.ts
apps/skilavottord/ws/src/app/modules/vehicle/vehicle.resolver.ts

update endpoint names

---

apps/skilavottord/ws/src/app/modules/recycling.partner/recycling.partner.resolver.ts
apps/skilavottord/ws/src/app/modules/samgongustofa/models/samgongustofa.model.ts

added recycling partner activate deactivate handling

---

apps/services/user-profile/src/app/user-profile/userProfile.controller.ts

If profile was updated and the current email was within the payload the email verifycation process was invoked.

Service Portal : Fix profile update email gets unverified

---

apps/skilavottord/ws/src/app/modules/samgongustofa/models/samgongustofa.service.ts

Docker-build-Return empty array when there is no vehicle

---

apps/skilavottord/ws/seeders/20201010111010-seed-recycling-request.js
apps/skilavottord/ws/src/app/modules/fjarsysla/models/fjarsysla.service.ts
apps/skilavottord/ws/src/app/modules/recycling.request/recycling.request.resolver.ts
apps/skilavottord/ws/src/app/modules/recycling.request/recycling.request.service.ts
apps/skilavottord/ws/src/app/modules/samgongustofa/models/samgongustofa.service.ts

Docker-build-Added skilavottordRecyclingRequests

---

apps/skilavottord/web/components/GDPR/GDPR.tsx
apps/skilavottord/web/graphql/queries/User.ts
apps/skilavottord/web/utils/filterData.ts

Added a missing return in the switch/case for case 'deregistered' cars
Because it didnt return any value otherwise and fell through to the default case.

Skilavottord - Minor fix in method that filters car

---

apps/skilavottord/ws/src/app/modules/user/models/user.model.ts
apps/skilavottord/ws/src/app/modules/user/user.resolver.ts

Feature user partnerid

---

apps/services/auth-api/src/app/app.module.ts

Issuer hardcoded

---

apps/services/auth-api/src/app/app.module.ts

Use internal address for jwks.

---

apps/skilavottord/ws/src/app/modules/fjarsysla/fjarsysla.resolver.ts
apps/skilavottord/ws/src/app/modules/fjarsysla/models/fjarsysla.service.ts
apps/skilavottord/ws/src/app/modules/recycling.request/recycling.request.resolver.ts
apps/skilavottord/ws/src/app/modules/recycling.request/recycling.request.service.ts
apps/skilavottord/ws/src/app/modules/samgongustofa/models/index.ts
apps/skilavottord/ws/src/app/modules/samgongustofa/models/samgongustofa.model.ts
apps/skilavottord/ws/src/app/modules/samgongustofa/models/samgongustofa.service.ts
apps/skilavottord/ws/src/app/modules/samgongustofa/samgongustofa.module.ts
apps/skilavottord/ws/src/app/modules/samgongustofa/samgongustofa.resolver.ts
apps/skilavottord/ws/src/environments/environment.ts

Docker-build-Refactor-and-Initialise-create-recycling-request

---

apps/service-portal/src/components/Header/Header.treat.ts
apps/service-portal/src/components/Header/Header.tsx
apps/service-portal/src/components/Layout/Layout.tsx
apps/service-portal/src/components/MobileMenu/MobileMenu.treat.ts
apps/service-portal/src/components/MobileMenu/MobileMenu.tsx
libs/service-portal/constants/src/lib/application.ts

Remove mobile toolbar from layout
Add menu button to header
Add button row to mobile menu
Update mobile menu styles
Update frontend to follow new design implementation

Service portal/mobile menu reworks

---

libs/application/ui-shell/src/components/ScreenFooter.tsx

Update the Button to the latest version.
Old Button was deprecated.

Switch to newer core/Button

---

apps/skilavottord/ws/src/app/modules/recycling.partner/recycling.partner.module.ts
apps/skilavottord/ws/src/app/modules/recycling.request/recycling.request.module.ts
apps/skilavottord/ws/src/app/modules/recycling.request/recycling.request.resolver.ts
apps/skilavottord/ws/src/app/modules/recycling.request/recycling.request.service.ts
apps/skilavottord/ws/src/app/modules/vehicle/vehicle.module.ts
apps/skilavottord/ws/src/app/modules/vehicle/vehicle.service.ts

Docker-build-Ready to test createSkilavottordRecyclingRequest

---

apps/judicial-system/backend/src/app/modules/case/pdf/case.pdf.ts

https://app.asana.com/0/1197628843274291/1199122923266479
☝️ 
Requested by users

Judicial System: Removes comma from signatures in pdf

---

apps/judicial-system/api/src/app/modules/case/dto/updateCase.input.ts
apps/judicial-system/api/src/app/modules/case/models/case.model.ts
apps/judicial-system/backend/migrations/20201106121834-update-case.js
apps/judicial-system/backend/src/app/modules/case/dto/createCase.dto.ts
apps/judicial-system/backend/src/app/modules/case/dto/updateCase.dto.ts
apps/judicial-system/backend/src/app/modules/case/e2e/case.spec.ts
apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
apps/judicial-system/web/src/graphql/sharedGql.ts
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepOne/StepOne.tsx
libs/judicial-system/types/src/lib/types.ts

https://app.asana.com/0/1197628843274291/1199120742190925
☝️ 
Required

Judicial System: Adds fields for requested defender

---

apps/skilavottord/ws/src/app/modules/samgongustofa/models/samgongustofa.model.ts
apps/skilavottord/ws/src/app/modules/samgongustofa/models/samgongustofa.service.ts

Docker-build-Added vinNumber

---

workspace.json

Adding docker tags to application-system projects
So that CI will build docker containers for the projects

Adding docker tags to application-system projects

---

apps/skilavottord/ws/src/app/modules/vehicle.owner/vehicle.owner.resolver.ts
apps/skilavottord/ws/src/app/modules/vehicle.owner/vehicle.owner.service.ts

Docker-build-Added create new vehicle owner

---

workspace.json

Include sequelize config and migrations for application system

---

apps/judicial-system/backend/src/app/modules/case/pdf/case.pdf.ts

Fixes a null pointer issue in pdf
Crash

Judicial System: Fixes a null pointer issue

---

apps/skilavottord/ws/seeders/20201010211010-seed-recycling-request.js
apps/skilavottord/ws/src/app/modules/recycling.request/recycling.request.resolver.ts
apps/skilavottord/ws/src/app/modules/recycling.request/recycling.request.service.ts

Docker-build-Bug fix recycling request

---

libs/service-portal/family/src/screens/UserInfo/UserInfo.tsx

update titles in user info links
Make it clearer that these are external links

Service Portal User Info Link Titles

---

apps/service-portal/src/components/Authenticator/AuthenticatorLoadingScreen.tsx

remove the text from authenticator loading screen
Improve UX

Service Portal Auth Loading Text

---

libs/service-portal/settings/src/components/Forms/LanguageForm.tsx
libs/service-portal/settings/src/components/UserOnboardingModal/UserOnboardingModal.tsx

icelandic set as a default language in the user onboarding modal
Improve UX

Service Portal Language Step Default Language

---

libs/service-portal/settings/src/components/UserOnboardingModal/Steps/IntroStep.tsx
libs/service-portal/settings/src/index.ts

render greeting based on gender in user onboarding modal
Improve UX

Service Portal Gender Based Greeting

---

libs/island-ui/core/src/lib/DatePicker/DatePicker.tsx

Add forwardref to input
Remove html selected from option

island-ui / datepicker fixes

---

apps/service-portal/src/components/ApplicationErrorBoundary/ApplicationErrorBoundary.tsx
apps/service-portal/src/screens/Dashboard/WidgetError/WidgetError.tsx
apps/service-portal/src/screens/Modules/ModuleErrorScreen.tsx

Dont report error to sentry on localhost
We dont benefit anything from logging the errors and it creates noise in sentry

Service portal ignore localhost sentry logging

---

libs/island-ui/core/src/lib/DatePicker/DatePicker.treat.ts

100% width on calendar container
react-datepicker generates inconsistent positions

island-ui / datepicker force consistent width

---

apps/skilavottord/ws/src/app/modules/recycling.request/recycling.request.service.ts

Docker-build-Added logs on Recycling request

---

apps/skilavottord/ws/src/app/modules/recycling.request/recycling.request.resolver.ts
apps/skilavottord/ws/src/app/modules/recycling.request/recycling.request.service.ts

Docker-build-Added skilavottordVehicleReadyToDeregistered

---

libs/api/domains/cms/src/lib/search/importers/news.service.ts

- Made data check is not circular
- Check should be not empty

Import check is not circular

---

libs/island-ui/core/src/lib/DatePicker/DatePicker.treat.ts

remove margin provided by react-datepicker

island-ui / datepicker remove margin

---

apps/service-portal/src/environments/environment.prod.ts

Remove the trailing slash
To fix the url

Service portal remove trailing slash on stage url

---

apps/skilavottord/ws/src/app/modules/fjarsysla/fjarsysla.resolver.ts
apps/skilavottord/ws/src/app/modules/gdpr/gdpr.resolver.ts
apps/skilavottord/ws/src/app/modules/recycling.request/recycling.request.resolver.ts
apps/skilavottord/ws/src/app/modules/samgongustofa/samgongustofa.resolver.ts
apps/skilavottord/ws/src/app/modules/vehicle.owner/vehicle.owner.resolver.ts
apps/skilavottord/ws/src/app/modules/vehicle/vehicle.resolver.ts

Feature add auth apis

---

apps/skilavottord/ws/src/app/modules/recycling.request/recycling.request.service.ts

Docker-build-Check requestType before continue

---

apps/skilavottord/ws/src/app/modules/vehicle/vehicle.resolver.ts

Docker-build-Added skilavottordVehicleById

---

apps/skilavottord/web/components/ErrorBoundary/ErrorBoundary.tsx
apps/skilavottord/web/components/FormStepper/FormStepperMobile.tsx
apps/skilavottord/web/screens/Confirm/Confirm.tsx
apps/skilavottord/web/screens/Handover/Handover.tsx
apps/skilavottord/web/screens/Handover/components/CompanyList.tsx
apps/skilavottord/web/screens/Overview/Overview.tsx
apps/skilavottord/web/screens/ReclingCompanies/RecyclingCompanies.tsx
apps/skilavottord/web/utils/dateUtils.ts
apps/skilavottord/web/utils/filterUtils.ts

- Timestamp is showing 24h instead of 12h
- Fetch user cars after userContext is loaded
- Refactor filtering of internalPartner
- Scroll to top when returning to home route
- Error message on /handover if permno in URL does not exist
Fixes issues that was showed during tests

Skilavottord/minor UI fixes 

---

apps/skilavottord/ws/src/app/modules/recycling.request/recycling.request.service.ts
apps/skilavottord/ws/src/app/modules/vehicle.owner/vehicle.owner.service.ts
apps/skilavottord/ws/src/app/modules/vehicle/vehicle.service.ts

Docker-build-Added few needed await

---

apps/judicial-system/web/src/routes/Judge/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Prosecutor/Overview/Overview.tsx
apps/judicial-system/web/src/shared-components/PoliceRequestAccordionItem/PoliceRequestAccordionItem.tsx

https://app.asana.com/0/1197628843274291/1198977286155087
Add the word "eftir" before the time when displaying the requested court date or actual court date.
Because the time selected in court date is not exact, but should be viewed as min time.

Judicial-system/Make clear that requested court date is after the given time

---

apps/judicial-system/web/src/routes/DetentionRequests/DetentionRequests.tsx
apps/judicial-system/web/src/routes/Judge/Ruling/StepOne/RulingStepOne.spec.tsx
apps/judicial-system/web/src/routes/Judge/Ruling/StepOne/RulingStepOne.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepOne/StepOne.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepTwo/StepTwo.tsx
apps/judicial-system/web/src/routes/Prosecutor/Overview/Overview.tsx
apps/judicial-system/web/src/shared-components/FormFooter/FormFooter.tsx
apps/judicial-system/web/src/shared-components/Modal/Modal.tsx
apps/judicial-system/web/src/utils/mocks.ts
libs/judicial-system/formatters/src/lib/formatters.ts

https://app.asana.com/0/1197628843274291/1199143603683037
See ☝️
It's a requirement from island-is. Also it's generally good practice.

Judicial-system/Strict TS setting pt2

---

apps/web/components/Adgerdir/AdgerdirArticles/AdgerdirArticles.tsx

Change number of results in adgerdir

---

apps/web/screens/Adgerdir/Article.tsx

Show disabled button if link does not exist

---

apps/skilavottord/web/components/FormStepper/FormStepper.tsx
apps/skilavottord/web/i18n/locales/en.json
apps/skilavottord/web/i18n/locales/is.json
apps/skilavottord/web/i18n/locales/translation.d.ts

Added icelandic translations that were missing
To complete the IS locale

Added more icelandic translations

---

.github/actions/branchWorkflows.json
.github/actions/detection.spec.ts
.github/actions/detection.ts
.github/actions/main.ts
.github/actions/mainWorkflows.json
.github/pull_request_template.md
.github/workflows/codeql-analysis.yml
.github/workflows/pullrequest.yml
.github/workflows/push.yml
nx.json
scripts/ci/00_prepare-base-tags.sh
scripts/ci/_nx-affected-targets.sh

There are still mentioning of "master" in the codebase but that is not reference to this repo. Those will be dealt on a case-by-case basis.
Supports island-is/infrastructure#275
Continue to be able to build Docker images and run PRs after we rename the branch

Changing references from "master" branch to "main"

---

apps/skilavottord/ws/src/app/modules/recycling.request/recycling.request.service.ts

Docker-build-Fixed checking isVehicle in database

---

apps/judicial-system/backend/README.md
apps/judicial-system/backend/migrations/20201107201756-update-notification.js
apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
apps/judicial-system/backend/src/app/formatters/formatters.ts
apps/judicial-system/backend/src/app/formatters/index.ts
apps/judicial-system/backend/src/app/modules/case/case.service.ts
apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
apps/judicial-system/backend/src/environments/environment.prod.ts
apps/judicial-system/backend/src/environments/environment.ts
apps/judicial-system/web/src/routes/Judge/HearingArrangements/HearingArrangements.tsx
libs/email-service/src/lib/email.service.ts
libs/judicial-system/types/src/lib/types.ts
scripts/schemas.js

https://app.asana.com/0/1197628843274291/1198563520384599
https://app.asana.com/0/1197628843274291/1198949971788358
Also adds the defender to the list of recipients of the signed ruling
https://app.asana.com/0/1197628843274291/1198949971788360
Also adds the defender to court date notifications to prosecutor and prison
https://app.asana.com/0/1197628843274291/1198987560584232
☝️ 
Required feature

Judicial System: Implements email court date notifiactions to prison

---

.github/actions/dist/index.js

rebuilding the GH action script to js

---

libs/island-ui/core/src/lib/DatePicker/DatePicker.stories.tsx
libs/island-ui/core/src/lib/DatePicker/DatePicker.treat.ts
libs/island-ui/core/src/lib/DatePicker/DatePicker.tsx

island-ui / Datepicker size and background props

---

libs/api/domains/cms/src/lib/search/cmsSync.service.ts

https://app.asana.com/0/1199123945323117/1199182577250261
Make importer have the correct context
Wrong context causes the importer to fail

Search indexer deployment fix

---

libs/application/templates/meta-application/src/forms/ApplicationForm.ts
libs/application/templates/meta-application/src/forms/Review.ts
libs/application/templates/meta-application/src/forms/messages.ts

Add submit field to main form. Add a final screen to review form, so we have a footer.
So we can submit the application.

Fix submission for meta application.

---

apps/skilavottord/ws/src/app/modules/vehicle/vehicle.service.ts

fixing deregestered

---

apps/skilavottord/ws/src/app/modules/recycling.request/recycling.request.service.ts

Docker-build-Skilavottord-Added debug

---

apps/skilavottord/ws/src/app/modules/recycling.request/recycling.request.service.ts

Docker-build-Skilavottord-change debug to info

---

apps/skilavottord/ws/src/app/modules/recycling.request/recycling.request.service.ts

Docker-build-Skilavottord-minor fixes

---

apps/judicial-system/api/src/app/modules/auth/auth.service.ts

Judicial System: Improves user validation

---

apps/skilavottord/ws/src/app/modules/recycling.request/recycling.request.service.ts

Feature skilavottord fix date format

---

apps/judicial-system/web/src/graphql/errorLink.ts
apps/judicial-system/web/src/routes/DetentionRequests/DetentionRequests.treat.ts
apps/judicial-system/web/src/routes/Judge/Confirmation/Confirmation.tsx
apps/judicial-system/web/src/routes/Judge/CourtRecord/CourtRecord.tsx
apps/judicial-system/web/src/routes/Judge/HearingArrangements/HearingArrangements.tsx
apps/judicial-system/web/src/routes/Judge/Ruling/StepOne/RulingStepOne.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepOne/StepOne.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepTwo/StepTwo.tsx
apps/judicial-system/web/src/services/api.spec.ts
apps/judicial-system/web/src/shared-components/Modal/Modal.tsx
apps/judicial-system/web/src/shared-components/PoliceRequestAccordionItem/PoliceRequestAccordionItem.tsx
apps/judicial-system/web/src/utils/cookies.ts
apps/judicial-system/web/src/utils/stepHelper.tsx
apps/judicial-system/web/src/utils/utils.spec.ts
apps/judicial-system/web/tsconfig.json
package.json
yarn.lock

https://app.asana.com/0/1197628843274291/1199143603683037
Everything, except the user management now uses strict TS.
Good practice

Judicial system/Strict TS pt4

---

apps/judicial-system/api/src/app/modules/auth/auth.service.ts
apps/judicial-system/api/src/app/modules/user/user.model.ts
apps/judicial-system/backend/migrations/20201113135409-update-user.js
apps/judicial-system/backend/migrations/20201114091445-remove-defaults.js
apps/judicial-system/backend/src/app/modules/user/e2e/user.spec.ts
apps/judicial-system/backend/src/app/modules/user/user.model.ts
apps/judicial-system/backend/test/setup.ts
libs/judicial-system/types/src/lib/types.ts

https://app.asana.com/0/1197628843274291/1198171573996202
https://app.asana.com/0/1197628843274291/1197258975286825
☝️
Prevents users with active flag set to false from logging in.
Currently, a logged in user can continue to work until the current login times out.
Also removes default values that are no longer needed from db columns.
We need a way to remove users.

Judicial System: Adds an active flag to users and removes default values from db columns

---

apps/skilavottord/ws/src/app/modules/samgongustofa/models/samgongustofa.service.ts

Docker-build-Skilavottord-Fix isRecyclale when has coOwner

---

.github/actions/dist/index.js
.github/actions/main.ts
.github/actions/package-lock.json
.github/workflows/push.yml

This closes island-is/infrastructure#287
Also package lock detection script and run push on release branch
creation like it was supposed to all the time.

Fix release branch good build detection

---

apps/judicial-system/web/src/routes/Judge/Confirmation/Confirmation.tsx

https://app.asana.com/0/1199153462262248/1199196328742109
The appeal announcements on the judges confirmation screen were not implemented according to the design.
Better UI

Judicial-system/Appeal announcement font fix

---

apps/judicial-system/backend/src/app/modules/case/case.service.ts

https://app.asana.com/0/1199153462262248/1199196775996701
☝️ Note that this PR does not handle errors received by the client.
If this is not handled then the server returns a 500 error when sending email fails.

Judicial System: Catches exceptions when sending signed ruling email

---

apps/skilavottord/web/screens/DeregisterVehicle/Confirm/Confirm.tsx

When fetching selected car to deregister from database it should show a loading icon.
Because it was showing the error message instead until it had fetched the vehicle. 

Skilavottord - Show loading icon during loading

---

apps/services/auth-api/src/app/app.module.ts
apps/services/auth-api/src/environments/environment.prod.ts
apps/services/auth-api/src/environments/environment.ts

Use environment files.

---

libs/api-catalogue/services/src/lib/provider.service.spec.ts
libs/api-catalogue/services/src/lib/provider.service.ts
libs/api-catalogue/services/src/lib/restmetadata.service.ts
libs/api-catalogue/types/src/lib/provider.model.ts
libs/api-catalogue/types/src/lib/xroadIdentifier.model.ts
libs/api/domains/api-catalogue/src/lib/models/xroadIdentifier.model.ts

#1453  What
Refactoring provider type to use xroadidentifier type
To make maintaing types easier

reworked providers to use xroad identifier type

---

libs/auth-api-lib/migrations/20201118143758-grant-sessionid-null.js
libs/auth-api-lib/src/lib/entities/dto/grant-dto.ts
libs/auth-api-lib/src/lib/entities/models/grants.model.ts

Allow null values for grant.session_id.

---

libs/api/domains/content-search/README.md
libs/api/domains/content-search/src/lib/contentSearch.service.ts
libs/api/domains/content-search/src/lib/models/searchResult.model.ts

https://app.asana.com/0/1199123945323117/1199220609580717
- Added readme for content search
- Added comments to code
- To make implementing content search easier

Api domains content search readme

---

libs/service-portal/documents/src/screens/Overview/Overview.tsx

chore: Documents overview input search icon

---

scripts/ci/_retag.sh

This closes island-is/infrastructure#304

Fail on retag failure

---

package.json

- Don't apply strict option on ts-node command

chore: strict false on schemas scripts

---

libs/application/ui-shell/src/components/ScreenFooter.tsx

When pressing tab in the application system, focus on Continue before back

---

apps/application-system/form/src/environments/environment.prod.ts
apps/application-system/form/src/environments/environment.ts
apps/application-system/form/src/main.tsx
libs/application/templates/parental-leave/src/fields/PaymentSchedule/PaymentsTable.tsx
libs/application/templates/parental-leave/src/fields/parentalLeaveUtils.ts
libs/application/ui-shell/src/components/ErrorBoundary.tsx
libs/application/ui-shell/src/lib/FormShell.tsx

Add sentry.io to application system
Add error boundary around the screen.
Fix parental leave application breaking.

Add sentry to application system

---

apps/judicial-system/backend/src/app/modules/case/case.service.ts

https://app.asana.com/0/1199153462262248/1199164386813746
☝️ 
To reduce the clutter in request overviews.

Judicial System: Does not return out dated requests

---

SUMMARY.md
handbook/technical-overview/adr/README.md
scripts/gitbook.js

Update links in gitbook to new ADR

---

handbook/technical-overview/monorepo.md

docs: import @eirikurn branching documentation PR here

---

libs/island-ui/core/src/lib/IconRC/iconMap.ts
libs/island-ui/core/src/lib/IconRC/icons/Reload.tsx
libs/island-ui/core/src/lib/IconRC/icons/ReloadOutline.tsx

Added Reload icon to Icon component

island-ui / Reload icon

---

apps/application-system/api/src/app/modules/application/e2e/application.spec.ts
apps/application-system/api/src/app/modules/application/utils/validationUtils.ts
apps/application-system/api/src/environments/environment.prod.ts
apps/application-system/api/src/environments/environment.ts
libs/api/domains/application/src/lib/application.service.ts

Fixing application readyForProduction check
I am creating a new env variable that we use that is directly tied to the name of our habitats
Because the readyForProduction check was erroring for dev, staging and production

Fixing application readyForProduction check

---

package.json
yarn.lock

See ☝️
Running security audit was failing and breaking the build.

Fix failing security audit

---

apps/skilavottord/ws/src/app/modules/gdpr/gdpr.service.ts
apps/skilavottord/ws/src/app/modules/recycling.partner/recycling.partner.service.ts
apps/skilavottord/ws/src/app/modules/vehicle.owner/vehicle.owner.service.ts
apps/skilavottord/ws/src/app/modules/vehicle/vehicle.service.ts

Adding error handling and logging

Feature bkend log

---

apps/judicial-system/backend/src/app/formatters/pdf.ts

https://app.asana.com/0/1199153462262248/1199372163065525
☝️ 
To fullfill reqs

Judicial System: Fixes pdf

---

apps/application-system/form/src/app/App.tsx
apps/application-system/form/src/components/Header.tsx
apps/application-system/form/src/utils/index.ts
libs/application/templates/parental-leave/src/fields/PaymentSchedule/PaymentSchedule.treat.ts
libs/application/templates/parental-leave/src/fields/PaymentSchedule/index.tsx
libs/application/templates/parental-leave/src/fields/Review/index.tsx
libs/application/templates/parental-leave/src/fields/components/Timeline/Timeline.treat.ts
libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
libs/application/ui-shell/src/components/FormMultiField.tsx
libs/application/ui-shell/src/components/Screen.treat.ts
libs/application/ui-shell/src/components/Screen.tsx
libs/application/ui-shell/src/components/ScreenFooter.treat.ts
libs/application/ui-shell/src/components/ScreenFooter.tsx
libs/application/ui-shell/src/components/Sidebar.tsx
libs/application/ui-shell/src/lib/FormShell.treat.ts
libs/application/ui-shell/src/lib/FormShell.tsx
libs/island-ui/core/src/lib/FormStepper/FormStepper.treat.ts
libs/island-ui/core/src/lib/FormStepper/FormStepperSection.treat.ts
libs/island-ui/core/src/lib/FormStepper/FormStepperSection.tsx

Various mobile refinements and fixes for the application system:
1. Fix cases where a horizontal scroll bar appears
2. Update Continue and Back buttons to match latest designs
3. Fix logo not appearing
4. Turn off auto focus fields
5. Scroll to top on question transition
6. Make the stepper sticky on mobile size
7. Make the stepper move to the active section on mobiles size
8. Wrap the the table with `overflowX: scroll` so that it doesn't create horizontal scroll bars for the main shell.
9. Start setting field types to more semantic attributes (for the relevant mobile keyboards).
Remaining (for next PR):
1. Make chapter images full width on mobile size
2. Add a sub-section progress bar, since the stepper only shows main sections on mobile size.
3. Continue investigating how to do …

Application system - mobile refinements 1

---

apps/skilavottord/ws/src/app/modules/recycling.request/recycling.request.service.ts

Build-docker-skilavottord-New rest body

---

libs/application/templates/document-provider-onboarding/src/fields/DocumentProvicerApplication/Review/index.tsx
libs/application/templates/document-provider-onboarding/src/fields/DocumentProvicerApplication/ThankYouScreen/index.tsx
libs/application/templates/document-provider-onboarding/src/forms/DocumentProviderApplication.ts
libs/application/templates/document-provider-onboarding/src/forms/ReviewApplication.ts
libs/application/templates/document-provider-onboarding/src/forms/messages.ts
libs/application/templates/document-provider-onboarding/src/lib/DocumentProviderOnboardingTemplate.ts

Removed chatbot and small style fixes 

remove chatbot and fix styles

---

libs/api-catalogue/elastic/src/lib/elastic.service.ts

Updating elasticsearch which fetches by id
Currently there is a bug stopping us from retreving items by id

updating id search for catalogue

---

libs/auth-api-lib/seeders/20201128073638-island-is-add-redirecturis.js
libs/auth-api-lib/seeders/20201128073659-island-is-add-cors-origins.js
libs/auth-api-lib/seeders/20201128073715-island-is-add-post-logout-uris.js

Seed data with uris (for silent renewal, cors and post logout) for service portal and applications.

Added seed data for uris on staging and prod

---

apps/judicial-system/api/src/environments/environment.prod.ts

https://app.asana.com/0/1199153462262248/1189677453581106
☝️ 
Needed for audit trail setup.

Judicial System: Modifies env vars for audit trail

---

libs/auth-api-lib/src/lib/entities/models/client.model.ts
libs/auth-api-lib/src/lib/services/clients.service.ts

Find each association separately instead of using sequelize include.

---

libs/island-ui/core/src/index.ts
libs/island-ui/core/src/lib/CategoryCard/CategoryCard.tsx

island-ui/ CategoryCard tag change and export

---

libs/auth-api-lib/src/lib/services/clients.service.ts

Deleteting Client for AdminUI
Associations must be deleted before deleting client

Delete client associations

---

apps/services/auth-admin-api/src/app/modules/users/user-identities.controller.ts
libs/auth-api-lib/src/lib/entities/models/user-identity.model.ts
libs/auth-api-lib/src/lib/services/user-identities.service.ts

#Find user identity by national registry id
Find user identity by national registry id

Find user identity by national registry id

---

libs/island-ui/core/src/lib/Checkbox/Checkbox.tsx

The `Checkbox` component was missing `checked={checked}` on the internal input component.
Resulting in the checked state not being updated correctly when the tracking property was
updated in the parent.
In the new `Filter` component being developed we are adding clear button to clear all
selected values. For the `Checkbox` to be able to track these changes correctly we need
to feed the `checked` property to the internal input field.

Add checked to the input used in Checkbox

---

libs/application/templates/parental-leave/src/constants.ts
libs/application/templates/parental-leave/src/fields/FirstPeriodStart/index.tsx
libs/application/templates/parental-leave/src/fields/Review/index.tsx
libs/application/templates/parental-leave/src/fields/Rights/GiveRights.tsx
libs/application/templates/parental-leave/src/fields/Rights/RequestRights.tsx
libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
libs/application/templates/parental-leave/src/lib/dataSchema.ts
libs/application/templates/parental-leave/src/lib/messages.ts
libs/shared/form-fields/src/lib/FieldDescription/FieldDescription.tsx

Remove blue boxed radio buttons in most cases (requested by designers).
Change wording related to transferring rights.
New personal allowance screen:
Blue radio buttons before:
And after:

Add personal allowance sub section to the flow.

---

scripts/ci/dockerfile-config/static-nginx.conf

turning off logs for health checks in static container type

---

apps/judicial-system/web/src/routes/Judge/CourtRecord/CourtRecord.spec.tsx
apps/judicial-system/web/src/routes/Judge/CourtRecord/CourtRecord.tsx
apps/judicial-system/web/src/routes/Judge/HearingArrangements/HearingArrangements.tsx
apps/judicial-system/web/src/routes/Judge/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Judge/Ruling/StepOne/RulingStepOne.spec.tsx
apps/judicial-system/web/src/routes/Judge/Ruling/StepOne/RulingStepOne.tsx
apps/judicial-system/web/src/routes/Judge/Ruling/StepTwo/RulingStepTwo.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepOne/StepOne.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepTwo/StepTwo.spec.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepTwo/StepTwo.tsx
apps/judicial-system/web/src/shared-components/TimeInputField/TimeInputField.tsx
apps/judicial-system/web/src/utils/formHelper.ts

Virkja Áfram-takka þegar svæði er orðið valid en ekki þegar það missir fókus https://app.asana.com/0/1199153462262248/1198887518721069 2085
Judicial system/form validation
 https://github.com/island-is/island.is/pull/2085 
22e74c1b8c7f70d42982b844b859d3e9ca4e8ee1
☝️ 
Get good at releasing

Judicial system/2020-12-07

---

libs/auth-api-lib/seeders/20201209073715-island-is-add-hms-data.js

Adding necessary data so that the client for HMS will work for them
So HMS can test working against the IDS4

Adding necessary data for hms client to work

---

apps/judicial-system/backend/seeders/20200927194724-user.js

Allows multiple sources when seeding the user table
We have reached a size limit that requires us to split up the seeding files.
We will address this properly soon by introducing a user management system.

Judicial System: Updates the user seeding process

---

apps/service-portal/src/hooks/useAuth/useAuth.ts

Manual refresh of site clears token
Fixing this with applying token to client.

Service Portal : Auth refresh bug fix

---

libs/application/core/src/lib/fieldBuilders.ts
libs/application/templates/parental-leave/src/fields/Duration/index.tsx
libs/application/templates/parental-leave/src/fields/FirstPeriodStart/index.tsx
libs/application/templates/parental-leave/src/fields/PeriodsRepeater/index.tsx
libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
libs/application/templates/parental-leave/src/lib/messages.ts

Stop hardcoding strings, have everything properly set up in the messages file. Added a new MessagesDir type to organize messages better.

Add Icelandic translations to most of the parental leave form.

---

apps/web/screens/AboutSubPage/AboutSubPage.tsx

https://app.asana.com/0/1199123945323117/1199587953442157
- Fix error in about sub page url resolution

Fixed get param causing error (#2203)

---

apps/web/components/ChatPanel/ChatPanel.tsx

https://app.asana.com/0/1199123945323117/1199585689963205
- Added a check for small screens
- Make chat bot less likely to open on mobile

Chatbot not open  in mobile

---

apps/web/components/Main/Main.tsx
apps/web/screens/Article.tsx
apps/web/screens/Layouts/SidebarLayout.tsx
libs/island-ui/core/src/lib/Navigation/Navigation.treat.ts
libs/island-ui/core/src/lib/Navigation/Navigation.tsx

- Table of content when relevant 
- New navigation dropdown in mobile
Updated design

Island.is/mobile article and toc

---

apps/judicial-system/backend/src/app/modules/notification/notification.controller.ts

https://app.asana.com/0/1199153462262248/1199572371900709
☝️ 

Judicial System: Fixes role permissions for judge notifications

---

libs/api/domains/cms/scripts/contentType.ts

https://app.asana.com/0/1199123945323117/1199608904951453
- Made type generator use correct codegen commands

Made generator use correct commands

---

libs/api/domains/cms/src/lib/models/organization.model.ts

https://app.asana.com/0/1199123945323117/1199608904951445
- Made api return organization logo
- To display in frontend

Logo to organization

---

apps/application-system/api/src/app/modules/application/application.controller.ts
apps/application-system/api/src/app/modules/application/e2e/application.spec.ts
apps/application-system/api/src/app/modules/application/tools/application.serializer.ts
apps/application-system/api/src/app/modules/application/tools/nationalId.decorator.ts
apps/application-system/api/src/app/modules/application/utils/tokenUtils.ts
apps/application-system/api/src/app/modules/application/utils/validationUtils.ts
libs/api/domains/application/src/lib/application.resolver.ts
libs/api/domains/application/src/lib/application.service.ts
libs/application/core/src/lib/ApplicationTemplateHelper.ts
libs/application/core/src/types/ApplicationTemplate.ts
libs/application/core/src/types/StateMachine.ts
libs/application/templates/document-provider-onboarding/src/lib/DocumentProviderOnboardingTemplate.ts
libs/application/templates/driving-lessons/src/lib/DrivingLessonsTemplate.ts
libs/application/templates/driving-license/src/lib/template.ts
libs/application/templates/health-insurance/src/lib/HealthInsuranceTemplate.ts
libs/application/templates/meta-application/src/lib/ApplicationTemplate.ts
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
libs/application/templates/passport/src/lib/PassportTemplate.ts
libs/application/templates/reference-template/src/lib/ReferenceApplicationTemplate.ts
libs/application/ui-shell/src/lib/ApplicationForm.tsx
libs/auth-nest-tools/src/lib/current-user.decorator.ts

This method is critical in making application answers and external data read/write-able across the system. I also changed the second parameter for the function so the whole application is accessible.

Finally use map user to role properly across the application system. 

---

apps/judicial-system/api/src/services/backend.ts

https://app.asana.com/0/1199153462262248/1199615548390637
☝️ 
This was a bug

Judicial System: Fixes auth header forwarding

---

apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepFour/StepFour.tsx

Asana task
https://app.asana.com/0/1199153462262248/1199608595413720/f
👆
Missing change from last text change batch

Updated message to court labels in UI

---

apps/judicial-system/api/src/services/backend.ts
apps/judicial-system/web/src/routes/Shared/DetentionRequests/DetentionRequests.tsx

https://app.asana.com/0/1199153462262248/1199596957713406
https://app.asana.com/0/1199153462262248/1199615548390637
☝️ 
Bug fixes

Judicial system/fixes for 5.2.0

---

libs/island-ui/core/src/index.ts

Forgot to add the `Filter` related component to the index list for island-ui
To use the `Filter` with the default import.

Adding Filter to index.ts for island-ui

---

apps/judicial-system/api/src/app/modules/user/user.model.ts
apps/judicial-system/backend/migrations/20201217120411-update-user.js
apps/judicial-system/backend/src/app/formatters/pdf.ts
apps/judicial-system/backend/src/app/modules/user/user.model.ts
libs/judicial-system/types/src/lib/types.ts

https://app.asana.com/0/1199153462262248/1199575542197596
☝️ 
Cleans up after adding user institution in latest release.

Judicial System: Cleans up user institution field

---

libs/application/templates/parental-leave/src/emailTemplateGenerators/assignParent.ts
libs/application/templates/parental-leave/src/emailTemplateGenerators/assignReviewer.ts

match email addresses to secrets

---

libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts

Fix undefined error

---

libs/application/templates/document-provider-onboarding/src/lib/DocumentProviderOnboardingTemplate.ts
libs/service-portal/document-provider/src/components/DocumentProviderBasicInfo/DocumentProviderBasicInfo.tsx
libs/service-portal/document-provider/src/screens/SingleDocumentProvider/SingleDocumentProvider.tsx

Added hardcoded id for reviews of applications. 
Refined some factors on single provider on service portal - not quite ready yet, but getting there.

added some logic for single provider and added reviewer on applicaiton

---

libs/application/templates/document-provider-onboarding/src/lib/DocumentProviderOnboardingTemplate.ts

added Id instred of hardcoded nationalID and a fix for dev users

fix for mapUserToRole

---

libs/auth-api-lib/src/lib/services/resources.service.ts

Include claims in getIdentityResourceByName

---

apps/services/auth-api/src/app/modules/clients/clients.module.ts
libs/auth-api-lib/src/lib/services/clients.service.ts

Fix import errors.

---

.github/CODEOWNERS

https://app.asana.com/0/1199123945323117/1199673033530053
Made Kosmos & kaos codeowner for gjafakort
Changes are needed to text see [#2350](https://github.com/island-is/island.is/pull/2350) and Vice versa are preoccupied

Change codeowners for gjafakort

---

apps/web/components/FrontpageTabs/illustrations/ChristmasTreeIllustration.tsx
apps/web/components/FrontpageTabs/illustrations/Illustration.tsx
apps/web/components/FrontpageTabs/illustrations/ManWithStrollerIllustration.tsx
apps/web/components/FrontpageTabs/illustrations/WomanFeedingBabyIllustration.tsx
apps/web/components/FrontpageTabs/illustrations/WomanOnBusIllustration.tsx
apps/web/components/FrontpageTabs/illustrations/WomanWithLaptopIllustration.tsx

Website: add new Christmas Tree illustration to front page slider

---

apps/gjafakort/web/i18n/locales/en.json
apps/gjafakort/web/i18n/locales/is.json

Ferðagjöf / text updates

---

libs/application/templates/parental-leave/src/fields/Review/index.tsx

Update expand/collapse button to match latest design
Looks like the rendering of the plus and minus icons is a bit off, we'll have to investigate this in ui/core.

Parental Leave - Update expand/collapse button

---

.github/CODEOWNERS
apps/gjafakort/web/i18n/locales/en.json
apps/gjafakort/web/i18n/locales/is.json

(cherry picked from commit 1fafef54e985b7c4b436b1b231be8968cd652c50)

expire date (#2350)

---

libs/island-ui/core/src/lib/Menu/Menu.treat.ts
libs/island-ui/core/src/lib/Menu/Menu.tsx
libs/island-ui/core/src/lib/ModalBase/ModalBase.treat.ts
libs/island-ui/core/src/lib/ModalBase/ModalBase.tsx

ios fix and additional breakpoints

island-ui / Menu improvements

---

libs/auth-api-lib/seeders/20201228140544-add-ids-admin.js

Added seed file for admin client and backend.

---

apps/services/auth-admin-api/src/app/modules/clients/clients.controller.ts
apps/services/auth-admin-api/src/app/modules/resources/resources.controller.ts
libs/auth-api-lib/migrations/20201229103556-add-archived-fields.js
libs/auth-api-lib/src/lib/entities/models/api-resource.model.ts
libs/auth-api-lib/src/lib/entities/models/api-scope.model.ts
libs/auth-api-lib/src/lib/entities/models/client.model.ts
libs/auth-api-lib/src/lib/entities/models/identity-resource.model.ts
libs/auth-api-lib/src/lib/services/clients.service.ts
libs/auth-api-lib/src/lib/services/resources.service.ts

Reverts island-is/island.is#2376

Revert "Feature/add archived functionality"

---

libs/auth-api-lib/seeders/20201231135419-update-ids-admin.js

Enable refresh tokens.

---

apps/web/screens/ApiCatalogue/ApiCatalogue.tsx
apps/web/screens/ServiceDetails/ServiceDetails.tsx

removing last part of breadcrumbs

---

apps/web/components/Timeline/Timeline.tsx
apps/web/screens/Search/Search.tsx

* adding spaces between strings in search results message
* checking for undefined on timeline for about page bug

Bug fixes, timeline and search results

---

libs/auth-api-lib/src/lib/entities/dto/api-resources.dto.ts
libs/auth-api-lib/src/lib/entities/dto/api-scopes.dto.ts
libs/auth-api-lib/src/lib/entities/dto/base/client-base.dto.ts
libs/auth-api-lib/src/lib/entities/dto/identity-resources.dto.ts

Remove archive from dtos

---

apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepTwo/StepTwo.spec.tsx
apps/judicial-system/web/src/routes/Shared/DetentionRequests/DetentionRequests.tsx
libs/auth-api-lib/seeders/20210104140855-auth-admin-api-add-user-claim.js

judicial-system/Fixed broken unit test

---

libs/auth-api-lib/src/lib/services/clients.service.ts

#Get Available scopes where archived is null

Get Available scopes where archived is null

---

apps/judicial-system/web/src/routes/Judge/Confirmation/Confirmation.spec.tsx
apps/judicial-system/web/src/routes/Judge/Confirmation/Confirmation.treat.ts
apps/judicial-system/web/src/routes/Judge/Confirmation/Confirmation.tsx
apps/judicial-system/web/src/routes/Judge/CourtRecord/CourtRecord.spec.tsx
apps/judicial-system/web/src/routes/Judge/CourtRecord/CourtRecord.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepOne/StepOne.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepTwo/StepTwo.spec.tsx
apps/judicial-system/web/src/routes/Shared/DetentionRequests/DetentionRequests.spec.tsx
apps/judicial-system/web/src/routes/Shared/DetentionRequests/DetentionRequests.treat.ts
apps/judicial-system/web/src/routes/Shared/DetentionRequests/DetentionRequests.tsx
apps/judicial-system/web/src/utils/mocks.ts
package.json
yarn.lock

https://app.asana.com/0/1199153462262248/1199353523039760
☝️ 
Minor release

Judicial System: Moved court end time to the confirmation screen (#2307)

---

apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
apps/judicial-system/backend/src/app/formatters/formatters.ts
apps/judicial-system/backend/src/app/formatters/pdf.ts
apps/judicial-system/web/src/routes/Judge/Ruling/StepOne/RulingStepOne.tsx
apps/judicial-system/web/src/routes/Judge/Ruling/StepTwo/RulingStepTwo.tsx
apps/judicial-system/web/src/shared-components/RulingAccordionItem/RulingAccordionItem.tsx

Ekki hafa tíma, einangrun og tilhögun þegar kröfu er hafnað
https://app.asana.com/0/1199153462262248/1199630011833605
☝️ 
The change makes rejected cases more clear to the user.
Ruling Step One no longer has custody end time and isolation when rejecting a case:
=======================
Ruling Step Two no longer has custody provisions and judge directions when rejecting a case:
=======================
Ruling pdf no longer has custody arrangements and judge directions for a rejected case:
=======================
Case status screen no longer has custody arrangements and judge directions for a rejected case:
=======================
Prison email notification no longer has custody arrangements for a rejected case:
=======================

Judicial System: Rejected Case Tweaks

---

apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
apps/judicial-system/backend/src/app/formatters/formatters.ts
apps/judicial-system/backend/src/app/formatters/pdf.ts
apps/judicial-system/web/src/shared-components/RulingAccordionItem/RulingAccordionItem.tsx

https://app.asana.com/0/1199153462262248/1199731615471349
☝️ 
Part of requirements.

Judicial System: Updates conclusion text for alternative travel ban ruling

---

apps/web/components/OpenApiView/OpenApiView.tsx

Centering loading icon.

---

apps/web/components/FrontpageSlider/LottiePlayer/LottieLoader.tsx
apps/web/components/FrontpageSlider/LottiePlayer/LottiePlayer.tsx
apps/web/components/FrontpageSlider/SlideBackgroundGrid.tsx
apps/web/libs/index.ts
apps/web/libs/react-lottie/types.ts
apps/web/libs/react-lottie/useLottie.tsx
package.json
yarn.lock

(cherry picked from commit 44ffdfb0a8a35f46148c4a5627d664917e802f9f)

Website/ Fix Lottie freezing (#2417)

---

apps/web/components/InstitutionPanel/InstitutionPanel.tsx
apps/web/components/LanguageToggler/LanguageToggler.tsx
apps/web/components/Menu/Menu.tsx
libs/island-ui/contentful/src/lib/ProcessEntry/ProcessEntry.tsx
libs/island-ui/core/src/lib/Menu/Menu.tsx
libs/island-ui/core/src/lib/Navigation/Navigation.tsx

- Image alt
- Language toggle duplicate id
- Remove h3 from process entry
- Use li inside ul

Island.is / Accessibility improvements

---

apps/application-system/README.md
libs/application/templates/reference-template/README.md

Adds extra steps when adding a new template to the Application System
Because the extra steps were missing

docs: Application System - adding a new template

---

.github/CODEOWNERS
libs/service-portal/driving-license/src/screens/DrivingLicense/DrivingLicense.tsx
libs/service-portal/driving-license/src/screens/DrivingLicense/components/Eligibility/Eligibility.tsx

I'll move this to the backend when we implement the business logic, where we'll query if the user can apply for these licenses.

Only 16 and above can apply for driving licenses

---

apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
apps/judicial-system/web/src/utils/mocks.ts

https://app.asana.com/0/1199153462262248/1199524739502330
👆 
Was a bug.

Judicial System: Stops displaying restrictions when ruling is alternative travel ban

---

apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx

https://app.asana.com/0/1199153462262248/1199524739502335
See 👆
When the decision is ACCEPTING_ALTERNATIVE_TRAVEL_BAN the form stepper should show "Farbann virkt", not "Gælsuvarðhald virkt"

Judicial-system/Add decision to PageLayout component

---

apps/services/auth-admin-api/src/app/modules/clients/clients.module.ts
apps/services/auth-admin-api/src/app/modules/clients/idp-restriction.controller.ts
libs/auth-api-lib/migrations/20210108120535-idp-restrictions.js
libs/auth-api-lib/seeders/20210108121154-idp-restrictions.js
libs/auth-api-lib/src/index.ts
libs/auth-api-lib/src/lib/entities/models/idp-restriction.model.ts
libs/auth-api-lib/src/lib/services/clients.service.ts

Ipd Restriction in db

---

apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepOne/StepOne.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepThree/StepThree.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepTwo/StepTwo.tsx
apps/judicial-system/web/src/shared-components/PageLayout/PageLayout.tsx

https://app.asana.com/0/1199153462262248/1199524097560303
☝️ 
Design changed.

Judicial system: Update Headings

---

apps/api/src/app/app.module.ts
apps/api/src/app/environments/environment.prod.ts
apps/api/src/app/environments/environment.ts
libs/api/domains/driving-license/README.md
libs/api/domains/driving-license/src/lib/client/drivingLicense.api.ts
libs/api/domains/driving-license/src/lib/client/index.ts
libs/api/domains/driving-license/src/lib/drivingLicense.module.ts
libs/api/domains/driving-license/src/lib/drivingLicense.service.ts

Connect driving license api domain to the driving license api at RLS through xroad
To get real data

Connecting driving license api domain to xroad driving license service

---

libs/application/templates/health-insurance/src/forms/HealthInsuranceForm.ts
libs/application/templates/health-insurance/src/forms/messages.ts

- Updated the copy
- Correct text added to the file-upload fields
Because the copy has been changed.

copy changes

---

apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepThree/StepThree.tsx

Fixed law info text
https://app.asana.com/0/inbox/1108390964729019/1199536784155389/1199539060836772

Judicial System / Fixed law info text

---

apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepTwo/StepTwo.tsx

Removed time error if there was no date.
https://app.asana.com/0/inbox/1108390964729019/1199524097560305/1199528869655352

Judicial System / Removed time error if there was no date.

---

apps/judicial-system/web/src/routes/Shared/DetentionRequests/DetentionRequests.tsx

https://app.asana.com/0/1199153462262248/1199530114077295
☝️ 
Bug

Judicial System: Fixes prosecutor lock when court in session

---

apps/judicial-system/web/src/routes/Judge/Ruling/StepOne/RulingStepOne.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepThree/StepThree.tsx
apps/judicial-system/web/src/utils/formHelper.ts

Custody date bug fixes
https://app.asana.com/0/1199153462262248/1199536784155400
Bug fixes
bugs bad

Judicial System / Custody date bug fixes

---

apps/judicial-system/web/src/shared-components/PageLayout/PageLayout.tsx

Tiny typo
https://app.asana.com/0/1108390964845040/1199547542824748

Judicial System / Tiny typo

---

apps/skilavottord/ws/src/app/modules/auth/auth.service.ts

adding users

---

apps/judicial-system/web/src/routes/Shared/DetentionRequests/DetentionRequests.tsx

https://app.asana.com/0/1199153462262248/1199530114077295
☝️ 
Bug

Judicial System: Fixes prosecutor lock

---

apps/skilavottord/ws/src/app/modules/user/user.resolver.ts

Feature hringras fix

---

libs/auth-api-lib/seeders/20210113122509-add-ids-admin-postlogouturl.js

Seed file with postlogouturl for ids-admin client.

---

apps/air-discount-scheme/backend/docker-compose.dev.yml
apps/air-discount-scheme/backend/src/app/modules/flight/flight.controller.ts
apps/air-discount-scheme/backend/src/app/modules/flight/flight.service.ts
apps/air-discount-scheme/backend/src/app/modules/flight/test/e2e/flight.spec.ts
apps/air-discount-scheme/backend/src/app/modules/flight/test/unit/flight.controller.spec.ts
apps/air-discount-scheme/backend/src/app/modules/flight/test/unit/flight.service.spec.ts
apps/air-discount-scheme/backend/src/app/modules/user/test/unit/user.service.spec.ts
apps/air-discount-scheme/backend/src/app/modules/user/user.service.ts

Should throw bad request if flight is booked in the past

Should throw bad request if flight is booked in the past

---

apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
apps/judicial-system/backend/src/app/formatters/formatters.ts
apps/judicial-system/web/src/utils/stepHelper.tsx
apps/judicial-system/web/src/utils/utils.spec.tsx

https://app.asana.com/0/1199153462262248/1199552077052389
Change conclusion if request is rejected.
It was a regression based on a misunderstanding in Figma.

Change conclution if request is rejected

---

libs/content-search-toolkit/src/services/kibana.service.ts

Log out the url used by the kibana service
I want to see the value used for the requests

Improving logging in kibana service

---

apps/auth-admin-web/.babelrc
apps/auth-admin-web/next.config.js
apps/auth-admin-web/pages/_app.tsx
apps/auth-admin-web/tsconfig.json

Add healthchecks to auth admin api

---

apps/web/screens/Search/Search.tsx
apps/web/utils/typenameResolver.ts

https://app.asana.com/0/1199123945323117/1199572510066419
Added a typename resolver
Names of content types are not consistent in Contentful and API

Resolved type for search result

---

libs/application/templates/children-domicile-transfer/src/dataProviders/ParentNationalRegistryProvider.ts
libs/application/templates/children-domicile-transfer/src/forms/ChildrenDomicileTransferForm.ts
libs/application/templates/children-domicile-transfer/src/lib/ChildrenDomicileTransferTemplate.ts

https://app.asana.com/0/1199733748699731/1199513406635470
- Displays a list of selected children and their current and future domicile
- Checkbox to confirm the information is correct
- We will need to create a custom component for this screen to display this data

Domicile transfer: Confirm domicile transfer information

---

libs/application/templates/driving-license/src/dataProviders/PenaltyPointsProvider.ts
libs/application/templates/driving-license/src/dataProviders/index.ts
libs/application/templates/driving-license/src/forms/application.ts

Create a dataprovider for penalty points
To ban people from requesting driving license that have too many penalty points

Adding penalty points data provider

---

apps/auth-admin-web/components/Layout/Header.tsx
apps/auth-admin-web/utils/auth.utils.ts

Util functions for session logic.

---

apps/judicial-system/web/src/routes/Judge/Confirmation/Confirmation.treat.ts
apps/judicial-system/web/src/routes/Judge/Confirmation/Confirmation.tsx
apps/judicial-system/web/src/routes/Judge/HearingArrangements/HearingArrangements.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepThree/StepThree.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepTwo/StepTwo.spec.tsx
apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
apps/judicial-system/web/src/shared-components/PdfButton/PdfButton.treat.ts
apps/judicial-system/web/src/shared-components/PdfButton/PdfButton.tsx

https://app.asana.com/0/1199153462262248/1199561133060542
See 👆
UX

Judicial-system/Add pdf button to signed verdict overview

---

libs/application/templates/children-domicile-transfer/src/forms/ChildrenDomicileTransferForm.ts

Uses mocked data for domicile transfer form. Extract data extraction into functions.

Refactoring children domicile application form

---

libs/application/templates/children-domicile-transfer/src/forms/ChildrenDomicileTransferForm.ts

Domicile transfer/application overview

---

apps/service-portal/src/environments/environment.prod.ts

Revert route changes
There are issues with changing the routes.

Service Portal/Reverting route changes

---

apps/services/search-indexer/config/kibana/visualization-articles-divided-by-language.json
apps/services/search-indexer/config/kibana/visualization-articles-with-process-entry.json
apps/services/search-indexer/config/kibana/visualization-english-articles.json
apps/services/search-indexer/config/kibana/visualization-icelandic-articles.json

Fixing search index pattern for kibana visualizations
It broke because of change in our index versioning

Fixing version pattern in kibana visualizations

---

apps/auth-admin-web/pages/api/auth/[...nextauth].js

Stop trying to refresh tokens when refresh token has expired.

---

apps/service-portal/src/environments/environment.prod.ts
apps/services/user-profile/src/app/user-profile/verification.service.ts

Changing auth and reset email urls
Current domain is incorrect

Service-portal/Changes to auth and reset email url

---

apps/auth-admin-web/components/Layout/Header.tsx
apps/auth-admin-web/components/Layout/Nav.tsx
apps/auth-admin-web/entities/common/SessionInfo.ts
apps/auth-admin-web/pages/index.tsx
apps/auth-admin-web/utils/auth.utils.ts

#Strongly typed session object

Strongly typed session object

---

apps/web/screens/Article.tsx
apps/web/screens/Search/Search.tsx

Truncate text in "Back" link on Articles
Use translation for Organizations label on Articles
Add space in search between "search results" - "in category"

Web bug fixes for release

---

libs/application/templates/driving-license/src/dataProviders/EntitlementTypesProvider.ts
libs/application/templates/driving-license/src/dataProviders/PenaltyPointsProvider.ts
libs/application/templates/driving-license/src/dataProviders/index.ts
libs/application/templates/driving-license/src/forms/application.tsx
libs/application/templates/driving-license/src/utils.ts

Mapping driving license entitlements to data from the dl api

Mapping entitlement types in dl application

---

apps/web/screens/GenericOverview/GenericOverview.tsx
libs/island-ui/core/src/lib/Link/Link.tsx

Use Link component to be able to open external links in new tab

Use link component to open external links in new tab

---

apps/services/auth-api/src/app/modules/case/e2e/auth-api.spec.ts
libs/auth-api-lib/seeders/20210118150729-add-island-is-uris.js

Seed file with uris for service portal on staging.

---

apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
apps/judicial-system/backend/src/app/formatters/formatters.ts
apps/judicial-system/web/src/utils/stepHelper.tsx

https://app.asana.com/0/1199153462262248/1199549768725005
☝️ 

Judicial System: Prosecutor Demands

---

apps/auth-admin-web/proxy.config.json
apps/services/auth-admin-api/src/app/modules/claims/claims.controller.ts
apps/services/auth-admin-api/src/app/modules/clients/client-allowed-scope.controller.ts
apps/services/auth-admin-api/src/app/modules/clients/client-claim.controller.ts
apps/services/auth-admin-api/src/app/modules/clients/client-grant-type.controller.ts
apps/services/auth-admin-api/src/app/modules/clients/client-post-logout-redirect-uri.controller.ts
apps/services/auth-admin-api/src/app/modules/clients/client-secret.controller.ts
apps/services/auth-admin-api/src/app/modules/clients/clients.controller.ts
apps/services/auth-admin-api/src/app/modules/clients/cors.controller.ts
apps/services/auth-admin-api/src/app/modules/clients/idp-restriction.controller.ts
apps/services/auth-admin-api/src/app/modules/clients/redirect-uri.controller.ts
apps/services/auth-admin-api/src/app/modules/grant-types/grant-types.controller.ts
apps/services/auth-admin-api/src/app/modules/resources/resources.controller.ts
apps/services/auth-admin-api/src/app/modules/users/user-identities.controller.ts

Adding backend string to the service-auth-admin-api calls
To make it work on dev environment, or test if that works

Adding backend string to service level and changing proxy.conf.json

---

apps/web/screens/LifeEvent/LifeEvent.tsx
apps/web/screens/NewsItem.tsx

Add rich text to news and life events

island-web / Add rich text to news and life events

---

apps/services/auth-admin-api/src/environments/environment.prod.ts

Added missing env vars to prod file.

---

apps/auth-admin-web/components/Resource/forms/ApiScopeCreateForm.tsx
apps/auth-admin-web/components/Resource/forms/IdentityResourceCreateForm.tsx
apps/auth-admin-web/services/ResourcesService.ts
apps/services/auth-admin-api/src/app/modules/resources/resources.controller.ts
libs/auth-api-lib/src/lib/services/resources.service.ts

Fix check if scope name is available

---

apps/auth-admin-web/components/Resource/forms/ApiScopeCreateForm.tsx
apps/auth-admin-web/components/Resource/forms/IdentityResourceCreateForm.tsx
apps/auth-admin-web/components/Resource/lists/ApiScopeList.tsx
apps/auth-admin-web/components/Resource/lists/IdentityResourcesList.tsx
apps/auth-admin-web/entities/dtos/api-scope-dto.ts
apps/auth-admin-web/entities/dtos/identity-resource.dto.ts
apps/auth-admin-web/pages/resource/api-scope/[edit].tsx
apps/auth-admin-web/pages/resource/api-scope/index.tsx
apps/auth-admin-web/pages/resource/identity-resource/[edit].tsx
apps/auth-admin-web/pages/resource/identity-resource/index.tsx
apps/auth-admin-web/services/ResourcesService.ts

#Refactor file name and class name of ApiScop and IdentitResource

Refactoring DTO file and class names

---

apps/judicial-system/web/src/routes/Judge/Ruling/StepTwo/RulingStepTwo.tsx

https://app.asana.com/0/1199153462262248/1199387306535850
See ☝️
Better UI

Judicial-system/Put custody restrictions in a blue box

---

apps/judicial-system/web/src/routes/Judge/Overview/Overview.treat.ts
apps/judicial-system/web/src/routes/Judge/Overview/Overview.tsx

https://app.asana.com/0/1199153462262248/1199512975001573
Add info card to judge overview page. Also replaced the accordion with text that's always showing.
UX
I removed the gender from the info box because it's being removed in #2592.

Judicial-system/Refactor judge overview page

---

apps/web/layouts/main.tsx

https://app.asana.com/0/1199123945323117/1199602958124172/f
Move cookie check to ssr

Island web / Alert banner dismissed

---

libs/auth-api-lib/seeders/20210121150729-service-portalbase-url-fix.js

Adding the seed file that fixes the redirect_urls

---

libs/application/templates/children-domicile-transfer/src/forms/ChildrenDomicileTransferForm.ts

https://app.asana.com/0/1199733748699731/1199584850352414
Change the order of the radio buttons
Since it does not matter in UI/UX perspective and would be more work to render the datepicker between the two radio inputs it was decided to change the order and display the datepicker below both radio inputs

Change order of radio buttons

---

libs/auth-api-lib/seeders/20210122152137-add-app-provider.js

Seed adding app provider to idp_restrictions table

---

apps/judicial-system/backend/src/app/formatters/pdf.ts
apps/judicial-system/web/src/routes/Judge/Confirmation/Confirmation.tsx
apps/judicial-system/web/src/routes/Judge/CourtRecord/CourtRecord.tsx
apps/judicial-system/web/src/routes/Judge/Ruling/StepTwo/RulingStepTwo.tsx
apps/judicial-system/web/src/shared-components/RulingAccordionItem/RulingAccordionItem.tsx
apps/judicial-system/web/src/utils/stepHelper.tsx

https://app.asana.com/0/1199153462262248/1199538599707354
Stop using the male version of "the accused" and start factoring in gender.
It's more inclusive.

Judicial system/Gender in static texts

---

apps/judicial-system/backend/src/app/formatters/pdf.ts
apps/judicial-system/web/src/routes/Judge/CourtRecord/CourtRecord.tsx
apps/judicial-system/web/src/shared-components/CourtDocuments/CourtDocuments.treat.ts
apps/judicial-system/web/src/shared-components/CourtDocuments/CourtDocuments.tsx
apps/judicial-system/web/src/shared-components/index.ts

https://app.asana.com/0/1199153462262248/1199174045356547
See ☝️
Better ui
https://user-images.githubusercontent.com/3789875/105684235-992ba800-5eec-11eb-9040-6131b2b16027.mov

Judicial-system/Move the add court document functionality to the top of the court documents component

---

apps/auth-admin-web/components/Client/form/ClientSecretForm.tsx
apps/auth-admin-web/pages/client-basic/index.tsx

#Native clients don't support secret
Native clients don't support secret

Add native to non secret

---

apps/gjafakort/application/migrations/20210125124052-darrikonn.js

Set new phone number for user

---

libs/api/domains/health-insurance/src/lib/healthInsurance.service.ts
libs/api/domains/health-insurance/src/lib/soap/healthInsuranceAPI.ts
libs/api/domains/health-insurance/src/lib/soap/soapClient.ts

health-insurance - Added logs

---

apps/api/src/app/environments/environment.ts
libs/api/domains/health-insurance/src/lib/soap/healthInsuranceAPI.ts

health-insurance - refactor and added environment values

---

apps/api/src/app/environments/environment.prod.ts
apps/api/src/app/environments/environment.ts

health-insurance - added environments values to prod

---

apps/judicial-system/backend/src/app/formatters/pdf.ts

https://app.asana.com/0/1199153462262248/1199538599707354
☝️ 
Important to use the correct gender.

Judicial System: Gender issues in ruling pdf

---

apps/judicial-system/web/src/routes/Judge/CourtRecord/CourtRecord.tsx
apps/judicial-system/web/src/routes/Judge/Ruling/StepOne/RulingStepOne.tsx
apps/judicial-system/web/src/routes/Judge/Ruling/StepTwo/RulingStepTwo.tsx
apps/judicial-system/web/src/shared-components/CourtRecordAccordionItem/CourtRecordAccordionItem.tsx
libs/judicial-system/formatters/src/lib/formatters.ts

https://app.asana.com/0/inbox/322488613152834/1199538599707354/1199656209051305
See ☝️
It's more inclusive

Judicial system/static text gender

---

apps/auth-admin-web/components/Client/form/ClientBasicCreateForm.tsx
apps/auth-admin-web/components/Client/form/ClientCreateForm.tsx
libs/auth-api-lib/sequelize.config.js

Adding client type texts

---

libs/application/ui-shell/src/components/FormMultiField.tsx

Fixes step layout bug in multi-fields.

Fix multi field padding

---

apps/auth-admin-web/components/Layout/Header.tsx
apps/auth-admin-web/pages/api/auth/[...nextauth].js
apps/auth-admin-web/utils/auth.utils.ts

Added log statements for debugging refresh tokens.

---

apps/judicial-system/web/src/shared-components/InfoCard/InfoCard.tsx

https://app.asana.com/0/1199153462262248/1199561133060544
☝️ 
Regerssion

Judicial System: Fixes regression in national id formatting

---

apps/auth-admin-web/components/common/HelpBox.tsx
apps/auth-admin-web/styles/_Base.scss

Hide helpbox on blur

---

apps/judicial-system/backend/src/app/modules/case/case.service.ts

https://app.asana.com/0/1199153462262248/1199613574461787
☝️ 

Return all cases that have not been revoked

---

apps/judicial-system/web/src/routes/Shared/DetentionRequests/DetentionRequests.treat.ts

https://app.asana.com/0/1199153462262248/1199656209051310
Hover and focus styles were off.
Better ui
https://user-images.githubusercontent.com/3789875/106004701-62e85700-60ab-11eb-8632-8350beb83aa3.mov

Judicial-system/Minor improvements to remove button style

---

libs/api/domains/health-insurance/src/lib/graphql/healthInsurance.resolver.ts
libs/api/domains/health-insurance/src/lib/graphql/models/faUmsoknSjukratrygging.model.ts
libs/api/domains/health-insurance/src/lib/graphql/models/index.ts
libs/api/domains/health-insurance/src/lib/healthInsurance.service.ts
libs/api/domains/health-insurance/src/lib/soap/dto/getFaUmsoknSjukratryggingType.dto.ts
libs/api/domains/health-insurance/src/lib/soap/dto/index.ts
libs/api/domains/health-insurance/src/lib/soap/healthInsuranceAPI.ts

health-insurance - new endpoint for get pending application status

---

libs/api/domains/health-insurance/src/lib/graphql/healthInsurance.resolver.ts

health-insurance - return boolean insteads of string

---

apps/service-portal/src/components/Authenticator/OidcSignIn.tsx

Redirecting from oidc resulted in a double root url /minarsidur/minarsidur with a 404 error

Service Portal: fix base url redirect from IDS.

---

apps/auth-admin-web/components/Client/lists/ClientsList.tsx
apps/auth-admin-web/components/Resource/lists/ApiResourcesList.tsx
apps/auth-admin-web/styles/Paginator.scss
apps/auth-admin-web/styles/_Base.scss
apps/auth-admin-web/styles/_ListLayout.scss

Fix export button look

---

libs/api/domains/national-registry/src/lib/nationalRegistry.service.ts

handle null value from maritalstatus as not married

Service Portal : handle null value from maritalstatus as not married

---

apps/judicial-system/web/src/routes/Shared/DetentionRequests/DetentionRequests.treat.ts
apps/judicial-system/web/src/routes/Shared/DetentionRequests/DetentionRequests.tsx
libs/island-ui/core/src/lib/Tag/Tag.treat.ts

https://app.asana.com/0/1199153462262248/1199656807371812
This PR does three things
1. Tags in custody table are now in line on smaller screens. This does however not mean that the table is fully responsive (far from it).
2. Removes a "div cannot be a descendant of p" console warning.
3. Remove background color change on disabled tags.
Better UI.

Judicial-system/Minor UI fixes

---

libs/island-ui/core/src/lib/Filter/Filter.stories.tsx
libs/island-ui/core/src/lib/Filter/Filter.tsx
libs/island-ui/core/src/lib/Filter/FilterMultiChoice/FilterMultiChoice.tsx

When isDialog  was added `Filter` I forgot to think about `FilterMultiChoice`.
By using `createContext` and creating `FilterContext` the user of the `Filter` component
only needs to apply the `isDialog` property on the main `Filter` component regardless
of which child components he will use.

Add isDialog to FilterMultiChoice

---

apps/auth-admin-web/pages/admin/index.tsx

Added links to datadog logs and dashboard.

---

apps/auth-admin-web/pages/_app.tsx

Stop using keepalive pings to refresh token.

---

apps/web/components/StoryList/StoryList.tsx

Link on about page "Sjá fleiri verkefnasögur" was incorrect

Link fix on story list

---

libs/application/templates/children-residence-change/README.md
libs/application/templates/children-residence-change/src/dataProviders/index.ts
libs/application/templates/children-residence-change/src/fields/ChangeInformation/index.tsx
libs/application/templates/children-residence-change/src/fields/Overview/index.tsx
libs/application/templates/children-residence-change/src/forms/ChildrenResidenceChangeForm.ts
libs/application/templates/children-residence-change/src/lib/utils.ts

https://app.asana.com/0/1199733748699731/1199599477069604
- Pull applicant data using the `NationalRegistryProvider`
- Display applicant data in relevant places in the application flow
- Added documentation on how to run the template locally. Needed because of additional setup for the `NationalRegistryProvider`
- To display real data

Residence change/nationalregistry data

---

.github/workflows/push.yml

we don't want something like this to be green: https://github.com/island-is/island.is/runs/1806040890?check_suite_focus=true

Do not post success if retag failed

---

apps/auth-admin-web/pages/_app.tsx
apps/auth-admin-web/pages/api/auth/[...nextauth].js
apps/auth-admin-web/utils/auth.utils.ts

Try to keep client side session updated and valid.

---

package.json
yarn.lock

Updating next auth package

---

apps/judicial-system/backend/src/app/modules/case/case.controller.ts

https://app.asana.com/0/1199153462262248/1199873953452236
☝️ 

Judicial System: Fixes judge assigment to case

---

apps/auth-admin-web/pages/api/auth/[...nextauth].js

Fixed sign for renewal window.

---

apps/air-discount-scheme/api/src/services/backend.ts

Disable cache

---

apps/judicial-system/backend/src/app/modules/case/case.controller.ts

https://app.asana.com/0/1199540339082445/1199649970684580
☝️ 

Fixes judge assigment to case (#2737)

---

libs/api/domains/health-insurance/src/lib/graphql/bucket.service.ts
libs/api/domains/health-insurance/src/lib/graphql/healthInsurance.resolver.ts
libs/api/domains/health-insurance/src/lib/healthInsurance.module.ts

s3 bucket testing

---

apps/auth-admin-web/components/Layout/Header.tsx

Removed log statements, trigger deployment.

---

.github/workflows/pullrequest-close.yml

Because feature creation feature name is lowercase

Coerce feature name to lowercase on close as well

---

apps/auth-admin-web/pages/admin/admin-user/[admin].tsx
apps/auth-admin-web/pages/admin/admin-user/index.tsx
apps/auth-admin-web/pages/admin/idp-provider/[idp].tsx
apps/auth-admin-web/pages/admin/idp-provider/index.tsx
apps/auth-admin-web/pages/admin/index.tsx
apps/auth-admin-web/pages/api/auth/[...nextauth].js
apps/auth-admin-web/pages/client-basic/index.tsx
apps/auth-admin-web/pages/client/[client].tsx
apps/auth-admin-web/pages/client/index.tsx
apps/auth-admin-web/pages/clients/index.tsx
apps/auth-admin-web/pages/resource/api-resource/[edit].tsx
apps/auth-admin-web/pages/resource/api-resource/index.tsx
apps/auth-admin-web/pages/resource/api-scope/[edit].tsx
apps/auth-admin-web/pages/resource/api-scope/index.tsx
apps/auth-admin-web/pages/resource/identity-resource/[edit].tsx
apps/auth-admin-web/pages/resource/identity-resource/index.tsx
apps/auth-admin-web/pages/resources/api-resources/index.tsx
apps/auth-admin-web/pages/resources/api-scopes/index.tsx
apps/auth-admin-web/pages/resources/identity-resources/index.tsx
apps/auth-admin-web/pages/users/index.tsx
apps/auth-admin-web/utils/auth.utils.ts

Cleanup unused session related code.

---

libs/api/domains/health-insurance/src/lib/graphql/bucket.service.ts
libs/api/domains/health-insurance/src/lib/graphql/healthInsurance.resolver.ts

Feature auth fix

---

apps/judicial-system/backend/src/app/modules/case/case.controller.ts

https://app.asana.com/0/1199153462262248/1199873823065181
☝️ 
All users should be able to see the ruling.

Judicial System: Unguards ruling pdf endpoint

---

apps/gjafakort/api/src/domains/auth/utils.ts
apps/gjafakort/api/src/environments/environment.prod.ts
apps/gjafakort/api/src/environments/environment.ts

https://github.com/island-is/helm/pull/281

Remove nationalIds

---

apps/service-portal/src/components/Greeting/Greeting.treat.ts
apps/service-portal/src/components/MobileMenu/figuresMapper.ts

Add minarsidur base to picture assets

refactor of code and adding minarsidur to base of asset (#2741)

---

apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepThree/StepThree.tsx
apps/judicial-system/web/src/routes/Prosecutor/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Shared/DetentionRequests/DetentionRequests.treat.ts
apps/judicial-system/web/src/routes/Shared/DetentionRequests/DetentionRequests.tsx
apps/judicial-system/web/src/shared-components/CourtDocuments/CourtDocuments.tsx
libs/judicial-system/formatters/src/lib/formatters.ts

https://app.asana.com/0/1199153462262248/1199623668402309
https://app.asana.com/0/1199153462262248/1199623668402311
- Fix typos.
- Prosecutors could continue without adding provisions.
- Minor table alignment issue fixed
UX

Judicial system/travel ban acceptance testing fixes

---

libs/application/templates/health-insurance/src/forms/HealthInsuranceForm.ts

Added a limit to how big the added attachment can be, 10MB

file size limit added

---

apps/services/documents/src/app/modules/document-provider/controllers/documentsInfra.controller.ts
apps/services/documents/src/app/modules/document-provider/document-provider.module.ts
apps/services/documents/src/app/modules/document-provider/dto/readinessDto.ts

Added readiness method for DocumentsService
Needed for kubernetes

added readiness method

---

apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx

https://app.asana.com/0/1199153462262248/1199637689946940
☝️ 
Should not be able to extend cases in certain situations.

Judicial System: Hide extend button

---

libs/auth-api-lib/seeders/20210208150729-prod-update.js

Adding necessary data for the prod environment through seed file

Prod data update

---

libs/auth-api-lib/seeders/20210208150729-prod-update.js

Adding necessary data to staging and prod

Prod data update (#2802)

---

.github/workflows/push.yml

This closes island-is/infrastructure#490

Don't allow underscore and have feature max length

---

libs/application/templates/health-insurance/src/forms/ConfirmationScreen.ts
libs/application/templates/health-insurance/src/lib/HealthInsuranceTemplate.ts

- Removed all connections to missing information part of form flow
- Added a confirmation screen the user is directed to on completing the form

Removing missing info and agent comment forms

---

libs/application/templates/health-insurance/src/constants.ts
libs/application/templates/health-insurance/src/fields/Review/StatusAndChildren.tsx
libs/application/templates/health-insurance/src/forms/HealthInsuranceForm.ts

Changed to using file upload controller instead of inputFileUpload component on status and children review page

using file upload controller

---

libs/api/domains/health-insurance/src/lib/bucket.service.spec.ts
libs/api/domains/health-insurance/src/lib/bucket.service.ts

added url-path to get file

---

libs/application/templates/health-insurance/src/forms/HealthInsuranceForm.ts
libs/application/templates/health-insurance/src/lib/HealthInsuranceTemplate.ts

Removing the nationality field form the confirm you contact page

removing nationality field from confirm your contact page

---

libs/api/domains/education/src/lib/client/mms.api.ts
libs/api/domains/education/src/lib/client/mms.type.ts
libs/api/domains/education/src/lib/education.service.ts
libs/api/domains/education/src/lib/education.type.ts
libs/api/domains/education/src/lib/graphql/license.model.ts
libs/api/domains/education/src/lib/graphql/main.resolver.ts
libs/api/domains/education/src/lib/graphql/sendLicense.input.ts
libs/api/domains/education/src/lib/graphql/sendLicense.model.ts
libs/api/domains/education/src/lib/graphql/teachingLicense.model.ts

Setting up mock data for teaching license resolver
To make it easier for the frontend to be developed and switch this later out with the real api

Creating graduation resolver

---

libs/application/templates/health-insurance/src/forms/HealthInsuranceForm.ts

Changing from `.postalCode` to `.address.postalCode` etc. to prefill with the actual data.

Fixing prefilling of data for address from nationalRegistry

---

libs/application/templates/health-insurance/src/dataProviders/ApplicationsProvider.ts
libs/application/templates/health-insurance/src/dataProviders/HealthInsuranceProvider.ts
libs/application/templates/health-insurance/src/dataProviders/OldPendingApplications.ts
libs/application/templates/health-insurance/src/forms/HealthInsuranceForm.ts

Added fields to print out why external data providers are failing as it is not showing in the network tab nor in datadog.
And is releated to dev environment so it can not be recreated on local.

Debug external data providers

---

apps/web/components/Organization/Slice/Districts/DistrictsSlice.treat.ts
apps/web/components/Organization/Slice/Districts/DistrictsSlice.tsx
apps/web/components/Organization/Slice/FeaturedArticles/FeaturedArticlesSlice.tsx
apps/web/components/Organization/Slice/Offices/OfficesSlice.tsx
apps/web/components/Organization/Slice/TwoColumnText/TwoColumnTextSlice.tsx
apps/web/components/Organization/Wrapper/OrganizationWrapper.treat.ts
apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/SidebarWrapper.tsx
apps/web/screens/Syslumenn/Home.tsx
apps/web/screens/Syslumenn/SubPage.tsx
apps/web/screens/queries/Organization.tsx

- Use organization subpage parentSubpage as fallback for navigation active url
- Fix data in TwoColumnnTextSlice
Deploy fixes to dev

Minor fixes for Sýslumenn

---

apps/web/components/Organization/Slice/Districts/DistrictsSlice.tsx
apps/web/components/Organization/Slice/FeaturedArticles/FeaturedArticlesSlice.tsx
apps/web/components/Organization/Wrapper/OrganizationFooter.tsx
apps/web/components/Organization/Wrapper/OrganizationWrapper.treat.ts
apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/pages/en/organizations/syslumenn/[slug]/index.ts
apps/web/pages/en/organizations/syslumenn/index.ts
apps/web/pages/en/organizations/syslumenn/services/index.ts
apps/web/screens/Syslumenn/Home.tsx
apps/web/screens/Syslumenn/Services.tsx
apps/web/screens/Syslumenn/SubPage.tsx

English version of sýslumenn pages. 
Fixes if organization data or logo is missing or has not been translated.
Part of migrating syslumenn.is to island.is

Sýslumenn - english version

---

.github/CODEOWNERS

add deloitte to codeowners for health-insurance

adding deloitte to codeowners for domains health-insurance

---

libs/island-ui/core/src/lib/DropdownMenu/DropdownMenu.stories.tsx
libs/island-ui/core/src/lib/DropdownMenu/DropdownMenu.treat.ts
libs/island-ui/core/src/lib/DropdownMenu/DropdownMenu.tsx
libs/island-ui/core/src/treat/global.treat.ts

Add custom render to dropdown menu
make it useable for more use cases

Island-ui / Add custom render to dropdown menu

---

libs/application/templates/reference-template/src/forms/ExampleForm.ts
libs/application/templates/reference-template/src/lib/ReferenceApplicationTemplate.ts

Be able to finish the review screen for ExampleForm template, currently it never sends the submission request since the data schema does not match what the review screen expects
To be able to finish the application

Fix reference template data schema and draft form

---

libs/island-ui/core/src/index.ts
libs/island-ui/core/src/lib/Table/Table.spec.tsx
libs/island-ui/core/src/lib/Table/Table.stories.tsx
libs/island-ui/core/src/lib/Table/Table.treat.ts
libs/island-ui/core/src/lib/Table/Table.tsx
libs/island-ui/core/src/lib/Table/index.tsx

Basic components to make a table using the island-ui theme
Core elements that can be used to make more complicated tables, and later on the basic theme could be updated and all tables would follow

island-ui / Basic table components

---

.github/CODEOWNERS

Make Stefna a code owner for `libs/api/domains/syslumenn`
We wrote this code.

Make Stefna code owner for Syslumenn API

---

apps/judicial-system/web/src/routes/Shared/UserForm/UserForm.tsx

Strips dash before saving national id and phone number.
Saving dashes causes problems.

Judicial System: Fixes user save

---

libs/auth-api-lib/seeders/20210216150729-hms-prod-update.js

Seed file prod update for hms

---

apps/web/screens/Article.tsx

Fix optional chaining bug

---

apps/skilavottord/README.md
apps/skilavottord/web-e2e/src/integration/app.spec.ts
apps/skilavottord/web/components/Layouts/AppLayout.tsx
apps/skilavottord/web/next.config.js
apps/skilavottord/web/proxy.conf.json
apps/skilavottord/ws/src/app/app.module.ts
libs/skilavottord/consts/src/lib/routes.ts

Updated tha basepath to be `/app/skilvottord` instead of only `/skilavottord` due to route conflict with island.is

Skilavottord - Update base path in frontend and api

---

libs/application/template-api-modules/src/lib/modules/templates/document-provider-onboarding/document-provider-onboarding.module.ts
libs/application/templates/document-provider-onboarding/src/lib/DocumentProviderOnboardingTemplate.ts

Added a new state to template so that emails get assigned. Some refactoring of the DocumentProviderOnboardingTemplate as well

Dpo.application assign email bug

---

scripts/ci/Dockerfile

adjusting nextjs docker build to use the new custom server

---

apps/judicial-system/backend/src/app/formatters/pdf.ts
apps/judicial-system/web/src/routes/Judge/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Prosecutor/Overview/Overview.tsx
apps/judicial-system/web/src/shared-components/PoliceRequestAccordionItem/PoliceRequestAccordionItem.tsx

https://app.asana.com/0/1199153462262248/1199900229987346
☝️ 

Judicial System: Fixes issues with the display of legal arguments

---

apps/web/screens/Category/Category.tsx

https://app.asana.com/0/1199123945323117/1199909137218773

Move placement of mobile nav on category page

---

apps/web/components/InstitutionsPanel/InstitutionsPanel.tsx

Link for institution panel is broken
- Replaced hardcoded value with a dynamic value
- Works better that way

Fixed institution link

---

apps/web/components/InstitutionsPanel/InstitutionsPanel.tsx

(cherry picked from commit 2aedc67fbabca0bd55c43f8821611ed4ef1afb71)

Fixed institution link (#2933)

---

libs/island-ui/contentful/src/lib/RichTextRC/defaultRenderNode.tsx

Merges https://github.com/island-is/island.is/pull/2937

Fix table of contents

---

apps/judicial-system/backend/src/app/formatters/pdf.ts

https://app.asana.com/0/1199153462262248/1199877418231402

Judicial system / Pdf titles

---

apps/web/screens/Category/Category.tsx

if hash is in url, scroll to that id

Scroll to category

---

apps/judicial-system/web/src/shared-components/UserProvider/UserProvider.tsx

https://app.asana.com/0/1199153462262248/1199894061387648
What the title says.
Otherwise, it is not possible to assign a prosecutor to a case.

Judicial System: Adds institution id to current user

---

apps/judicial-system/web/src/routes/Judge/CourtRecord/CourtRecord.spec.tsx
apps/judicial-system/web/src/routes/Judge/CourtRecord/CourtRecord.tsx

https://app.asana.com/0/1199153462262248/1199943123647013

Judicial System / Made accusedPleaAnnouncement optional

---

libs/application/templates/health-insurance/src/forms/messages.ts

Added the Icelandic copy for the select field

Icelandic copy for select field placeholder

---

apps/judicial-system/web/src/routes/Judge/Confirmation/Confirmation.tsx
apps/judicial-system/web/src/routes/Judge/CourtRecord/CourtRecord.spec.tsx
apps/judicial-system/web/src/routes/Judge/CourtRecord/CourtRecord.tsx
apps/judicial-system/web/src/routes/Judge/Overview/Overview.spec.tsx
apps/judicial-system/web/src/routes/Judge/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Prosecutor/Overview/Overview.tsx
apps/judicial-system/web/src/shared-components/PoliceRequestAccordionItem/PoliceRequestAccordionItem.tsx
apps/judicial-system/web/src/shared-components/RulingAccordionItem/RulingAccordionItem.tsx
libs/judicial-system/formatters/src/lib/formatters.spec.ts
libs/judicial-system/formatters/src/lib/formatters.ts

https://app.asana.com/0/1199153462262248/1199920099505656
☝️ 
Looks better

Judicial System: Format requested custody restrictions

---

apps/web/components/Organization/Slice/Districts/DistrictsSlice.tsx
apps/web/components/Organization/Slice/FeaturedArticles/FeaturedArticlesSlice.tsx
apps/web/components/Organization/Slice/Render/SliceDropdown.tsx
apps/web/components/Organization/Wrapper/OrganizationFooter.tsx
apps/web/components/Organization/Wrapper/OrganizationWrapper.treat.ts
apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/screens/Syslumenn/Auction.tsx
apps/web/screens/Syslumenn/Auctions.tsx
apps/web/screens/Syslumenn/Home.tsx
apps/web/screens/Syslumenn/Homestay.tsx
apps/web/screens/Syslumenn/Services.tsx
apps/web/screens/Syslumenn/SubPage.tsx
libs/api/domains/cms/src/lib/cms.contentful.service.ts

* Auctions loading icon, layout fixes and ordering
* Organization home link moved from navigation title to logo/title
* Footer style fixes
* Districts map on sýslumenn frontpage rendered with object to display xlink and hover effects for areas
* Fix linting and unique key warnings
Improve sýslumenn organization page after review

Sýslumenn improvements

---

libs/application/templates/health-insurance/src/forms/messages.ts

updated link to my pages

---

.github/CODEOWNERS

Fixing codeowners for content-search libs

Update codeowners for content search libs

---

apps/web/components/FrontpageSlider/FrontpageSlider.tsx
apps/web/screens/AboutSubPage/AboutSubPage.tsx
apps/web/screens/Error/Error.tsx
apps/web/screens/GenericOverview/GenericOverview.tsx
libs/island-ui/contentful/src/lib/RichTextRC/RichText.tsx
libs/island-ui/contentful/src/lib/SectionWithImage/SectionWithImage.tsx
libs/island-ui/contentful/src/lib/TellUsAStoryForm/TellUsAStoryForm.tsx

Using richText component everywhere instead of renderHtml

Rich text refactoring

---

apps/judicial-system/web/src/graphql/sharedGql.ts
apps/judicial-system/web/src/routes/Judge/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Prosecutor/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx

https://app.asana.com/0/1199153462262248/1199960043840160
☝️ 
Should use the prosecutor's institution.

Judicial System: Stops hardcoding prosecutor institution

---

apps/skilavottord/ws/src/app/modules/samgongustofa/models/samgongustofa.service.ts

changing isrecyclable

---

apps/skilavottord/ws/src/app/modules/auth/auth.service.ts
apps/skilavottord/ws/src/app/modules/user/user.resolver.ts

more users

---

scripts/ci/Dockerfile

memory options for node while building

---

package.json
yarn.lock

https://www.npmjs.com/advisories/1612

Fix security vulnerability with @graphql-tools/git-loader

---

apps/skilavottord/web/i18n/locales/is.json

spelling fix

---

libs/localization/scripts/formatter.js

- otherwise you don't get same id between local and graphql response

fix: don't strip out markdown from the id

---

libs/api/domains/document-provider/src/lib/document-provider.service.ts

Return errormessages that comes from Azure webservice.
For better UX

better error handling from azure webservice

---

apps/judicial-system/web/src/routes/Shared/UserForm/UserForm.tsx

Minor text tweek

---

libs/application/templates/health-insurance/src/fields/ConfirmationScreen/ConfirmationScreen.tsx
libs/application/templates/health-insurance/src/forms/messages.ts

Added the new copy to messages file
Updated  confirmation screen field to accommodate the copy changes

Health insurance copy changes

---

.github/workflows/push.yml

The builds have been timing out, so this is a temp solution. We will address this more appropriately [here](https://github.com/island-is/infrastructure/issues/542)

Longer timeouts for preparing step in GitHub CI

---

.github/workflows/push.yml

60 minutes seems is not enough. Going bigger.

we need more time

---

apps/skilavottord/ws/src/app/modules/auth/auth.service.spec.ts

remove nationalid and names

---

apps/skilavottord/README.md
apps/skilavottord/ws/src/environments/environment.prod.ts
apps/skilavottord/ws/src/environments/environment.ts

- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have rebased against main before asking for a review

Change name of env variable for user list

---

libs/api/domains/document-provider/src/lib/document-provider.resolver.ts
libs/api/domains/document-provider/src/lib/document-provider.service.ts

Added methods to add extra info to organisations
Need to be able to add extra info to organisations when inserted manually with no extra info

added methods to add extra info to organisation

---

libs/application/templates/health-insurance/src/lib/answerValidators.ts

File upload validation error moved inside the file upload component

---

package.json
yarn.lock

Running `yarn security-audit` results in an error, making PRs stop in the pipe.
It's blocking the CI pipe

fix(core): Fix security audit error

---

apps/services/search-indexer/src/migrate/lib/dictionary.ts
libs/content-search-index-manager/src/lib/index-templates/template-is.ts

We are having issues creating AWS ES xml packages.
Removing hyphen decompunder until issue is fixed
This issue is preventing all other projects from being deployed

Removed hyphenation decompounder

---

libs/application/templates/parental-leave/src/parentalLeaveUtils.ts

The getter for family was incorrectly referencing data from externalData.family
To be able to select spouse fetched from Þjóðskrá

fix(application-templates-parental-leave): Correctly reference family data

---

libs/application/templates/children-residence-change/src/lib/ChildrenResidenceChangeTemplate.ts

Adds the ability to go into parent b flow with own ssn if useMocks is set in application
Needed for development and QA

feat(children-residence-change):mock parent b flow

---

apps/application-system/api/src/app/modules/application/files/utils/childrenResidenceChange.ts
libs/application/templates/children-residence-change/src/fields/MockData/index.tsx

https://app.asana.com/0/1199733748699731/1200022261261311
When mock data is used we should display that data in the pdf

fix(children-residence-change): pdf mock data

---

apps/web/screens/ApiCatalogue/ApiCatalogue.tsx
apps/web/screens/ServiceDetails/ServiceDetails.tsx

Remove unused links from the navigation sidebar of the API catalogue and service details pages.
Links not needed.
N/A

removed efnisstefna link from navigation in api catalogue

---

libs/application/templates/children-residence-change/src/fields/Overview/index.tsx
libs/application/templates/children-residence-change/src/lib/messages/contract.ts

Updates data on confirmation screen to reflect which parent is in the flow

fix(children-residence-change): Overview screen data

---

libs/api/domains/health-insurance/src/lib/bucket.service.ts
libs/api/domains/health-insurance/src/lib/graphql/healthInsurance.resolver.ts
libs/application/template-api-modules/src/lib/modules/templates/health-insurance/health-insurance.service.ts
libs/application/template-api-modules/src/lib/modules/templates/health-insurance/health-insurance.utils.ts
libs/health-insurance/src/index.ts
libs/health-insurance/src/lib/bucket/bucket.service.ts
libs/health-insurance/src/lib/health-insurance.spec.ts
libs/health-insurance/src/lib/soap/dto/applyHealthInsuranceInputs.dto.ts
libs/health-insurance/src/lib/soap/dto/index.ts
libs/health-insurance/src/lib/soap/healthInsuranceAPI.ts

feature(health-insurance) - getting files from bucket

---

workspace.json

Adding docker-next for services-auth-admin-api

---

apps/services/documents/src/app/modules/document-provider/e2e/document-provider.spec.ts

Remove almost all tests since they are causing race-conditions in pull requests.
See above ;)
- [] I have performed a self-review of my own code

fix: Removed tests due to race-condition.. temporary fix

---

handbook/technical-overview/api-design-guide/README.md
handbook/technical-overview/api-design-guide/documentation.md
handbook/technical-overview/api-design-guide/errors.md
handbook/technical-overview/api-design-guide/methods.md
handbook/technical-overview/api-design-guide/once-only.md
handbook/technical-overview/api-design-guide/resource-oriented-design.md
handbook/technical-overview/api-design-guide/versioning.md

Review of the API Design Guide prior to API Catalogue realease.
Some things changed during development and the API Design Guide had to be reviewed and updated to reflect those changes.
N/A

Api design guide review

---

apps/judicial-system/web/next-modules/withHealthcheckConfig.js
apps/judicial-system/web/next.config.js

https://app.asana.com/0/1199153462262248/1200017647359051
See ☝️
The CI expects this to be implemented and fails if it's not.

(feat)Judicial-system/Added withHealthcheckConfig

---

apps/skilavottord/ws/src/app/modules/auth/auth.service.spec.ts
apps/skilavottord/ws/src/app/modules/auth/auth.service.ts
apps/skilavottord/ws/src/app/modules/user/user.resolver.ts
apps/skilavottord/ws/src/environments/environment.ts

Feature usertoenv

---

apps/judicial-system/web/units/Healthchecks/withHealthchecks.tsx
apps/judicial-system/web/units/errors.ts

https://app.asana.com/0/322488613152836/1200017647359051

(feat)Judicial-system/Add health check

---

.github/workflows/pullrequest.yml
apps/air-discount-scheme/api/src/main.ts
apps/air-discount-scheme/backend/src/main.ts
apps/api/src/main.ts
apps/application-system/api/src/main.ts
apps/judicial-system/backend/src/main.ts
apps/reference-backend/src/main.ts
apps/services/auth-admin-api/src/main.ts
apps/services/auth-api/src/main.ts
apps/services/documents/src/main.ts
apps/services/search-indexer/src/main.ts
apps/services/user-profile/src/main.ts
libs/infra-nest-server/src/lib/bootstrap.ts
libs/infra-next-server/src/lib/bootstrap.ts

Adding APM support for the NextJS services as well

Moving DataDog tracing to a central location

---

workspace.json

Now building docker image for services-auth-admin-api
Creating a target for the service to signal we need a docker image for it
We like docker images

build(services-auth-admin-api): docker target location

---

apps/skilavottord/ws/src/app/modules/auth/auth.service.ts
apps/skilavottord/ws/src/app/modules/auth/jwt.strategy.ts
apps/skilavottord/ws/src/app/modules/samgongustofa/models/samgongustofa.service.ts

log change

---

libs/application/templates/health-insurance/src/lib/HealthInsuranceTemplate.ts
libs/application/templates/health-insurance/src/types.ts

Fixing the validation of the file upload on review page when use selects additional info

fix(health-insurance): Removing validation of file upload on review page for additional information

---

libs/auth-api-lib/migrations/20210303105229-client-delegations-non-nullable.js
package.json

Don't try to enforce null constraints yet.

---

apps/judicial-system/api/src/app/modules/case/dto/createCase.input.ts
apps/judicial-system/api/src/app/modules/case/dto/updateCase.input.ts
apps/judicial-system/api/src/app/modules/case/interceptors/case.transformer.spec.ts
apps/judicial-system/api/src/app/modules/case/interceptors/case.transformer.ts
apps/judicial-system/api/src/app/modules/case/models/case.model.ts
apps/judicial-system/backend/migrations/20210309120814-update-case.js
apps/judicial-system/backend/src/app/modules/case/case.controller.ts
apps/judicial-system/backend/src/app/modules/case/dto/createCase.dto.ts
apps/judicial-system/backend/src/app/modules/case/dto/updateCase.dto.ts
apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
apps/judicial-system/backend/test/e2e.spec.ts
apps/judicial-system/web/graphql/sharedGql.ts
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepOne/StepOne.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepOne/StepOneForm.tsx
apps/judicial-system/web/src/routes/Shared/UserForm/UserForm.tsx
apps/judicial-system/web/src/utils/mutations.ts
apps/judicial-system/web/src/utils/useFormHelper.ts
libs/judicial-system/types/src/lib/types.ts

https://app.asana.com/0/1199153462262248/1199979427153778
☝️ 
Requirement

feature(judicial-system): Optionally send request to defender

---

libs/auth-api-lib/migrations/20210303105229-client-delegations-non-nullable.js
package.json

* Don't try to enforce null constraints yet.
* upgrading vulnerable package
Co-authored-by: Petar Shomov <petar@andes.is>
The build system got a bit confused about the success tasks, so need to force merge this to main

Don't try to enforce null constraints yet. (#3164)

---

apps/judicial-system/web/next.config.js

https://app.asana.com/0/1199153462262248/1200017647359051
Remove unused config.
It's redundant and I want to see if this is resolves the issue we're having with deploying.

fix(judicial-system)/Simplify nextjs config

---

apps/web/components/Card/Card.tsx
apps/web/components/CardsSlider/CardsSlider.treat.ts
apps/web/components/CardsSlider/CardsSlider.tsx

https://app.asana.com/0/inbox/1183506890377448/1199678316578918/1200030077265362
Fix the spacing and breakpoints of carousel
Wasn't looking like the design

Tweak life event carousel

---

libs/application/core/src/lib/formBuilders.ts
libs/application/core/src/types/Form.ts
libs/application/templates/children-residence-change/src/forms/ChildrenResidenceChangeForm.ts
libs/application/templates/children-residence-change/src/lib/messages/externalData.ts
libs/application/ui-shell/src/components/FormExternalDataProvider.tsx

https://app.asana.com/0/1199733748699731/1200032250261873
Added an optional `description` prop to the `FormExternalDataProvider`
To be able to display a more detailed text on why this exernal data is being fetched.

feat(application-system): external data description

---

apps/auth-admin-web/pages/api/auth/[...nextauth].js

fix(auth-admin-web): Get idtoken from account.

---

apps/web/components/Card/Card.tsx
apps/web/components/CardsSlider/CardsSlider.treat.ts
apps/web/components/CardsSlider/CardsSlider.tsx
apps/web/screens/GenericOverview/GenericOverview.tsx
apps/web/screens/queries/fragments.ts
libs/api/domains/cms/src/lib/models/questionAndAnswer.model.ts
libs/island-ui/contentful/src/lib/FaqList/FaqList.tsx

https://github.com/island-is/island.is/pull/3220
https://github.com/island-is/island.is/pull/3216
https://github.com/island-is/island.is/pull/3163

hotfix(web): Faq file fix and other minor issues

---

libs/application/templates/health-insurance/src/fields/Review/ContactInfo.tsx
libs/health-insurance/src/lib/bucket/bucket.service.ts

fix(health-insurance):Minor refactor

---

libs/application/templates/data-protection-complaint/src/fields/CommissionFieldRepeater/CommissionFieldRepeater.tsx
libs/application/templates/data-protection-complaint/src/fields/ComplaineeRepeater/ComplaineeTable.tsx
libs/application/templates/data-protection-complaint/src/fields/ComplaintOverview/ComplaintOverview.tsx
libs/application/templates/data-protection-complaint/src/fields/ComplaintOverview/Sections.tsx
libs/application/templates/data-protection-complaint/src/fields/ComplaintOverview/Shared.tsx
libs/application/templates/data-protection-complaint/src/fields/ComplaintOverview/index.ts
libs/application/templates/data-protection-complaint/src/forms/ComplaintForm.ts
libs/application/templates/data-protection-complaint/src/lib/dataSchema.ts
libs/application/templates/data-protection-complaint/src/lib/messages/info.ts
libs/application/templates/data-protection-complaint/src/lib/messages/overview.ts
libs/application/templates/data-protection-complaint/src/shared/constants.ts

Set up overview screen in DPAC
Continue development of template

feat(data-protection-complaint): Add Overview Screen

---

apps/api/src/app/app.module.ts
apps/api/src/app/environments/environment.prod.ts
apps/api/src/app/environments/environment.ts
libs/api/domains/education/src/lib/client/mms.api.ts
libs/api/domains/education/src/lib/education.module.ts

Connect to xroad to get MMS data

fix(education-domain): stop faking data and connect to xroad

---

apps/judicial-system/web/src/routes/Judge/Confirmation/Confirmation.tsx
apps/judicial-system/web/src/routes/Judge/Ruling/StepOne/RulingStepOne.spec.tsx
apps/judicial-system/web/src/routes/Judge/Ruling/StepOne/RulingStepOne.tsx
apps/judicial-system/web/src/routes/Prosecutor/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Shared/DetentionRequests/DetentionRequests.tsx
apps/judicial-system/web/src/shared-components/RulingAccordionItem/RulingAccordionItem.tsx

https://app.asana.com/0/1199153462262248/1200017038310544
https://app.asana.com/0/1199153462262248/1200017038310540
https://app.asana.com/0/1199153462262248/1199999639914935

Fix(Judicial-System): Few minor fixes.

---

libs/application/templates/health-insurance/src/forms/messages.ts

changing to new Icelandic submission title

fix(sjukratryggingar): changing to new icelandic submission title

---

.github/CODEOWNERS

- Update shared/form-fields codeowner

chore: update codeowner on form-fields lib

---

libs/application/templates/health-insurance/src/dataProviders/ApplicationsProvider.ts
libs/application/templates/health-insurance/src/dataProviders/HealthInsuranceProvider.ts
libs/application/templates/health-insurance/src/dataProviders/PendingApplications.ts
libs/application/templates/health-insurance/src/healthInsuranceUtils.ts
libs/application/templates/health-insurance/src/lib/HealthInsuranceTemplate.ts

- Fix logic to check if existing drafts
- Refactor types in providers
- Refactor unused variable
- Crashed frontend because filter was applied on an object

fix(health-insurance): Fix blank page

---

SUMMARY.md
jest.config.js
libs/clients/mms/.eslintrc.json
libs/clients/mms/README.md
libs/clients/mms/jest.config.js
libs/clients/mms/src/index.ts
libs/clients/mms/src/lib/clients-mms.spec.ts
libs/clients/mms/src/lib/clients-mms.ts
libs/clients/mms/tsconfig.json
libs/clients/mms/tsconfig.lib.json
libs/clients/mms/tsconfig.spec.json
nx.json
tsconfig.base.json
workspace.json

Just an empty mms client library.

feat(education): Initialize mms clients lib

---

apps/auth-admin-web/components/Admin/lists/TranslationList.tsx
apps/auth-admin-web/services/TranslationService.ts

feat(admin-auth-web): Fix delete translation

---

libs/auth-api-lib/seeders/20210322163513-applications-resources.js

chore(auth-api-lib): Seed resource data for application system.

---

apps/application-system/form/src/index.html

fix: remove TODO for now

---

apps/application-system/form/src/index.html

chore: add description for umsoknir

---

libs/application/ui-shell/src/components/Screen.tsx

Disable submit button while a submit is in progress
So that you do not call it more than once

chore(application-system-form): Disable submit button while submitting

---

apps/web/components/LifeEventsCardsSection/LifeEventsCardsSection.tsx
apps/web/components/SearchInput/SearchInput.tsx
apps/web/screens/Home.tsx
apps/web/screens/Search/Search.tsx

Minor tweaks for web https://github.com/island-is/island.is/pull/3336

fix: Added language string and skip untranslated life event cards (#3336)

---

libs/auth-api-lib/seeders/20210324144627-applications-resources2.js

chore(auth-api): Seed resources for application system, attempt2 (#3344)

---

apps/application-system/form/src/components/Header.tsx
apps/application-system/form/src/routes/SignIn.tsx

* fix: redirect
* fix: url check

fix(application-system): paths fixes (#3351)

---

libs/application/templates/document-provider-onboarding/src/lib/DocumentProviderOnboardingTemplate.ts

Added readyForProduction flag to the document-provider-onboarding application
To get the application to production

fix: added readyForProduction flag (#3347)

---

libs/auth-api-lib/migrations/20210326092429-create-delegations.js

chore(auth-api): Create tables for delegations.

---

libs/api/domains/education/src/lib/education.service.ts
libs/api/domains/education/src/lib/education.type.ts
libs/api/domains/education/src/lib/graphql/grade/englishGrade.model.ts
libs/api/domains/education/src/lib/graphql/grade/examResult.model.ts
libs/api/domains/education/src/lib/graphql/grade/gradeResult.model.ts
libs/api/domains/education/src/lib/graphql/grade/icelandicGrade.model.ts
libs/api/domains/education/src/lib/graphql/main.resolver.ts

Adding full name of user to exam result
Because the new design uses a name

feat(domains/education): adding name to exam results

---

apps/auth-admin-web/components/Client/form/ClientCreateForm.tsx

#fix validation for baseurl when editing

feat(auth-admin-api): fix validation for baseurl when editing

---

README.md

docs: Add mention of `direnv` being prerequisite

---

libs/auth-api-lib/src/lib/services/translation.service.ts

feat(auth-admin-web): remove tolowercase

---

libs/service-portal/education-license/src/screens/EducationLicense/components/LicenseCards/LicenseCards.tsx

feat(license): disable button while loading

---

libs/api/domains/education/src/lib/education.service.ts
libs/clients/mms/src/lib/mms.type.ts

The UI probably needs an update since the `issuer` might always be `Menntamálastofnun`.
Then it doesn't make sense to clutter the UI with the MMS logo.

feat(license): rename school to issuer

---

apps/services/auth-api/src/app/modules/translation/translation.controller.ts

fix(auth-api): Fix url for translations.

---

apps/air-discount-scheme/backend/src/app/modules/flight/flight.service.ts
apps/air-discount-scheme/backend/src/app/modules/flight/test/e2e/flight.spec.ts
apps/air-discount-scheme/backend/src/app/modules/flight/test/integration/flight.service.spec.ts
apps/air-discount-scheme/backend/src/app/modules/flight/test/unit/flight.controller.spec.ts

Akureyri had an incorrect flightcode
- [ X ] I have performed a self-review of my own code
- [ X ] My changes generate no new warnings
- [ X ] Formatting passes locally with my changes
- [ X ] I have rebased against main before asking for a review

fix(air-discount-scheme): Wrong flightcode for Akureyri

---

libs/auth-api-lib/migrations/20210326112344-delegation-fix.js

fix(auth-api): Fix valid_count column type.

---

.github/CODEOWNERS
libs/api/domains/education/src/lib/education.service.ts
libs/api/domains/education/src/lib/education.type.ts
libs/api/domains/education/src/lib/graphql/grade/mathGrade.model.ts
libs/clients/mms/src/lib/mms.type.ts

Need to add numbercomprehension
We show that field for 4th and 7th grade

feat(education): Adding number comprehension to exam results

---

libs/service-portal/core/src/lib/navigation/masterNavigation.ts
libs/service-portal/education-career/src/screens/EducationCareer/EducationCareer.tsx
libs/service-portal/education-degree/src/screens/EducationDegree/EducationDegree.tsx
libs/service-portal/education-license/src/screens/EducationLicense/EducationLicense.tsx
libs/service-portal/education-student-assessment/src/screens/EducationStudentAssessment/EducationStudentAssessment.tsx
libs/service-portal/education-student-assessment/src/screens/EducationStudentAssessment/components/StudentAssessmentTable/StudentAssessmentTable.tsx
libs/service-portal/education/src/screens/EducationOverview/EducationOverview.tsx

Filter empty grades from StudentAssessmentTable
Remove link to old grades
Trying relative paths for images

feat(service-portal): Filter empty grades

---

libs/auth-api-lib/migrations/20210331081545-remove-delegation-scope-fk.js

fix(auth-api): Remove foreign key to api_scope.

---

libs/service-portal/education-license/src/screens/EducationLicense/components/LicenseCards/LicenseCards.tsx

feat(license): loading indicator while sealing

---

libs/service-portal/education-student-assessment/src/screens/EducationStudentAssessment/components/StudentAssessmentTable/StudentAssessmentTable.tsx

Added number comprehension to student assessment table

feat(service-portal): Education Number Comprehension

---

libs/application/templates/health-insurance/src/forms/HealthInsuranceForm.ts
libs/application/templates/health-insurance/src/forms/messages.ts
libs/application/templates/health-insurance/src/lib/HealthInsuranceTemplate.ts

- Fix misspellings
- Added copy to clarify the flow for users
- Changed the application title shown in action card from english to icelandic
- Minor refactor of states and events

fix(health-insurance): Fix misspellings and copy updates

---

apps/services/auth-api/src/app/app.module.ts
apps/services/auth-api/src/app/modules/permissions/permissions.controller.ts
apps/services/auth-api/src/app/modules/permissions/permissions.module.ts
libs/auth-api-lib/src/lib/services/access.service.ts

feat(auth-api): Endpoint with permitted scopes.

---

.github/workflows/push.yml
scripts/ci/_retag.sh
scripts/ci/retag-unaffected.sh

This is the [new?] recommended way to retag images in ecr

ci(ecr): Simplify retagging

---

.github/workflows/pullrequest-lint.yml

validateSingleCommit was added in v3.4.0

ci(pr): Update semantic pull request action

---

apps/service-portal/src/store/modules.ts
libs/service-portal/core/src/lib/navigation/masterNavigation.ts
libs/service-portal/education/src/screens/EducationOverview/EducationOverview.tsx

Remove education degree page
Education degree page is not production ready

feat(service-portal): Remove education degree page

---

apps/judicial-system/web/src/routes/Shared/DetentionRequests/ActiveDetentionRequests.tsx
apps/judicial-system/web/src/routes/Shared/DetentionRequests/PastDetentionRequests.tsx
apps/judicial-system/web/src/utils/mutations.ts

https://app.asana.com/0/1199153462262248/1199877900959589
Ensure consistent kt formatting between active and past detention request tables and handle undefined value in custodyFrom. 
Fixes ui bugs

fix(judicial-system): Detention request table fixes

---

apps/judicial-system/backend/src/app/modules/case/case.service.ts

https://app.asana.com/0/1199153462262248/1200089982514643
☝️ 
By request from users.

fix(judicial-system): Improves signature text

---

apps/judicial-system/web/src/routes/Judge/CourtRecord/CourtRecord.tsx

https://app.asana.com/0/1199153462262248/1200047583274093
☝️ 
This was a bug.

fix(judicial-system): Adds Other Demands to Police Demands

---

apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepFive/StepFiveForm.tsx
apps/judicial-system/web/src/utils/useS3Upload.ts
libs/island-ui/core/src/lib/InputFileUpload/InputFileUpload.tsx

https://app.asana.com/0/1199153462262248/1200123118127366
If an upload fails for some reason, the user should be able to retry.
UX
https://user-images.githubusercontent.com/3789875/114197347-c4e1fa00-9941-11eb-84a9-1e9a5b950263.mov

feat(judicial-system): Retry upload on fail

---

libs/application/templates/children-residence-change/src/fields/SelectChildren/index.tsx

https://app.asana.com/0/1199733748699731/1200169200696766
Disabled child selection if the applicant and the other parent live together
If the applicant and the other parent live together it should not be possible to request a transfer for the children

feat(crc): disable child selection if parents live together

---

libs/application/template-api-modules/src/lib/modules/templates/children-residence-change/emailGenerators/applicationSubmitted.ts

Updates content of email for crc

chore(crc): email content

---

apps/auth-admin-web/components/Admin/nav/AdminTabNav.tsx
libs/auth-api-lib/src/lib/services/translation.service.ts

#Translation count not working correctly. Tab fix

feat('auth-admin-web'): Translation count not working correctly. Tab fix

---

apps/judicial-system/web/src/routes/Judge/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Prosecutor/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.spec.tsx
apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
apps/judicial-system/web/src/shared-components/CaseFile/CaseFile.tsx
apps/judicial-system/web/src/shared-components/CaseFileList/CaseFileList.tsx
apps/judicial-system/web/src/utils/mocks.ts

https://app.asana.com/0/1199153462262248/1200174330230901
Add case file overview to signed verdict overview

feat(judicial-system): Case files in signed verdict overview

---

.github/CODEOWNERS

build(all): Removing team from codeowners since it is no longer part of SÍ

---

libs/application/templates/children-residence-change/src/fields/Reason/index.tsx
libs/application/templates/children-residence-change/src/lib/messages/reason.ts

https://app.asana.com/0/1199733748699731/1200184411501108
Adding a description and changing screen according to new design

feat(crc): reason description and minor fixes

---

package.json
yarn.lock

fix: ssri version update

---

apps/application-system/api/src/environments/environment.interface.ts
apps/application-system/api/src/environments/environment.prod.ts
apps/application-system/api/src/environments/environment.ts
libs/application/template-api-modules/src/lib/modules/templates/children-residence-change/children-residence-change.module.ts
libs/application/template-api-modules/src/lib/modules/templates/children-residence-change/children-residence-change.service.ts
libs/application/template-api-modules/src/lib/types/index.ts

Sends sms to parent b when parent a submits application if parent b phone number is registered.
TODO: Update copy of sms text (yet to be designed) and add variables to helm.

feat(crc): Sends sms to counterparty on parent a submission

---

apps/auth-admin-web/utils/validation.utils.ts

#Temporary fix url validation
The validation fails with legit url. 

feat('auth-admin-web'): Temporary fix url validation

---

libs/application/templates/children-residence-change/src/fields/Overview/Overview.treat.ts
libs/application/templates/children-residence-change/src/fields/Overview/index.tsx
libs/application/templates/children-residence-change/src/lib/messages/contract.ts

https://app.asana.com/0/1199733748699731/1200184411501103
- Updated overview screen and translations
- Pushed translations to Contentful
New design

feat(crc): update overview screen according to new design

---

apps/services/auth-admin-api/src/app/modules/access/scope.constants.ts
apps/services/auth-admin-api/src/app/modules/grant-types/grant-types.controller.ts

feat(auth-admin-api): Try using scope guard in grant-types controller.

---

apps/web/components/NewsCard/NewsCard.tsx
apps/web/components/Organization/Slice/AccordionSlice/AccordionSlice.tsx
apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/hooks/useLinkResolver/useLinkResolver.tsx
apps/web/screens/Organization/Home.tsx
apps/web/screens/Organization/NewsItem.tsx
apps/web/screens/Organization/NewsList.tsx
apps/web/screens/Organization/Services.tsx
apps/web/screens/Organization/Syslumenn/Auction.tsx
apps/web/screens/Organization/Syslumenn/Auctions.tsx
package.json
yarn.lock

This includes some small fixes for the Syslumenn web that went live a few days ago.
This includes a few commits cherry picked from main.

fix(web): Hotfix/8.0.0 syslumenn

---

apps/auth-admin-web/components/Layout/Nav.tsx
apps/auth-admin-web/pages/admin/index.tsx
apps/auth-admin-web/pages/api/auth/[...nextauth].js
apps/auth-admin-web/utils/role.utils.ts

#RoleUtils - Check if user is admin

feat('auth-admin-web'): RoleUtils

---

apps/auth-admin-web/pages/api/auth/[...nextauth].js
apps/auth-admin-web/services/TokenService.ts
apps/auth-admin-web/utils/ids.constants.ts

feat(auth-admin-web): IDS constants in code.

---

apps/judicial-system/api/src/app/modules/audit/audit.service.ts
apps/judicial-system/api/src/app/modules/case/interceptors/case.transformer.ts
apps/judicial-system/api/src/app/modules/file/models/signedUrl.model.ts
apps/judicial-system/backend/src/app/modules/case/case.controller.ts
apps/judicial-system/backend/src/app/modules/file/awsS3.service.ts
apps/judicial-system/backend/src/app/modules/file/file.spec.ts
apps/judicial-system/web/src/routes/Judge/Overview/Overview.spec.tsx
apps/judicial-system/web/src/routes/Judge/Overview/Overview.tsx
apps/judicial-system/web/src/services/api.ts
apps/judicial-system/web/src/services/notification.ts
apps/judicial-system/web/src/shared-components/CaseFileList/CaseFileList.tsx
apps/judicial-system/web/src/shared-components/Table/Table.tsx
apps/judicial-system/web/src/types/react-table-config.d.ts
libs/judicial-system/auth/src/lib/auth.module.ts
libs/judicial-system/formatters/src/lib/formatters.ts
libs/judicial-system/types/src/lib/types.ts
libs/nova-sms/src/lib/sms.service.ts

style(judicial-system): Resolves Linting Issues

---

apps/auth-admin-web-e2e/src/integration/app.spec.ts
apps/auth-admin-web/next.config.js
apps/auth-admin-web/pages/_app.tsx
apps/auth-admin-web/pages/api/auth/logout.js
apps/auth-admin-web/services/TokenService.ts
apps/services/auth-admin-api/src/environments/environment.ts

fix(auth-admin-web): Attempt base url fixes.

---

apps/auth-admin-web/next.config.js
apps/auth-admin-web/pages/_app.tsx

fix(auth-admin-web): Handle different basepath.

---

handbook/repository/aws-secrets.md
libs/application/templates/children-residence-change/README.md
libs/application/templates/health-insurance/README.md
libs/application/templates/party-letter/README.md

- Merged AWS secrets docs and saw afterward some duplicates old docs

docs: clean up AWS docs after merge

---

libs/api/domains/cms/src/lib/models/frontpageSlider.model.ts
libs/api/domains/cms/tsconfig.lib.json

Tsconfig.lib.json was overriding strict to false by mistake
Strict errors went unreported until tests, with strict enabled, hit upon it.
A strict error had been introduced. The strict error for the domains/cms was resolved.

fix(api-domains-cms): Strict override fix

---

scripts/ci/90_docker-cypress.sh
scripts/ci/90_docker-express.sh
scripts/ci/90_docker-next.sh
scripts/ci/90_docker-static.sh
scripts/ci/Dockerfile
scripts/ci/Dockerfile.cypress
scripts/ci/_docker.sh

resolves: https://github.com/island-is/infrastructure/issues/659
[https://eu-west-1.console.aws.amazon.com/ecr/repositories/private/821090935708/system-e2e/image/sha256:6da1b88b9413ad479f63504c3c463f1d41d92a057e460731b8ec0307d4c76bba/details/?region=eu-west-1](https://eu-west-1.console.aws.amazon.com/ecr/repositories/private/821090935708/system-e2e/image/sha256:6da1b88b9413ad479f63504c3c463f1d41d92a057e460731b8ec0307d4c76bba/details/?region=eu-west-1)
Fixing vulnerabilities in system-e2e docker image.
Because reasons

fix(system-e2e): Fixing vulnerabilities in cypress docker image

---

apps/judicial-system/backend/migrations/20210416154909-update-case.js
apps/judicial-system/backend/test/e2e.spec.ts

☝️ 
The default value is no longer needed and may hide errors

chore(judicial-system): Removes default case type

---

package.json
yarn.lock

Running `yarn run security-audit` on main results in an error.
No new PR's can go through the pipe while this happens.

fix(core): Fixes security audit

---

apps/auth-admin-web/pages/api/auth/[...nextauth].js

fix(auth-admin-web): Use pkce instead of state.

---

apps/web/components/Organization/Slice/LogoList/LogoList.tsx
apps/web/components/Organization/Slice/StorySlice/StorySlice.tsx
apps/web/components/Organization/Slice/TimelineSlice/TimelineSlice.tsx

Changed the year/month labels on the timeline. Added correct color scheme to logo list and story slice.

fix(web): Minor DI slice changes

---

apps/auth-admin-web/utils/auth.utils.ts

fix(auth-admin-web): Add basepath to logout url.

---

apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepTwo/StepTwo.tsx
apps/judicial-system/web/src/routes/Prosecutor/Overview/Overview.tsx

https://app.asana.com/0/1199153462262248/1200184411501126
☝️ 
It is now possible to update requests until a ruling has been signed. This could lead to excessive sms notifications. The current change leads to fewer and more controlled sms notifications.

feat(judicial-system): Notification Improvements

---

apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/AppealSection/AppealSection.tsx
apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx

https://app.asana.com/0/1199153462262248/1200032250261895
☝️ Fixes issues found during testing

fix(judicial-system): Fixes to Postponed Appeal

---

libs/service-portal/education-license/src/screens/EducationLicense/components/LicenseCards/LicenseCards.tsx

feat(education-license): Use skeletonloader while loading

---

libs/application/templates/children-residence-change/src/fields/Overview/index.tsx
libs/application/templates/children-residence-change/src/lib/messages/contract.ts

https://app.asana.com/0/1199733748699731/1200221568911079
- Changed string to markdown
- Changed string variable name
- Use `DescriptionText` instead of `Text` on overview screen

chore(crc): update child benefit overview string

---

libs/auth-api-lib/migrations/20210421114039-change-admin-access-pk.js

fix(auth-admin-api): Enable access with many scopes

---

apps/api/src/app/app.module.ts
apps/icelandic-names-registry/backend/sequelize.config.d.ts
apps/icelandic-names-registry/backend/sequelize.config.js
workspace.json

fix(icelandic-names-registry): Add to apps api and make seeder only seed each seed once

---

apps/icelandic-names-registry/backend/src/environments/environment.prod.ts

Fix prod/dev env name mismatch

fix(icelandic-names-registry): Fix env mismatch

---

apps/icelandic-names-registry/backend/src/environments/environment.interface.ts
apps/icelandic-names-registry/backend/src/environments/environment.prod.ts
apps/icelandic-names-registry/backend/src/environments/environment.ts

Should hopefully finally fix this build error
https://github.com/island-is/island.is/runs/2418725464#step:10:1357

fix(icelandic-name-registry): interface for environment

---

apps/icelandic-names-registry/backend/src/environments/environment.prod.ts
apps/icelandic-names-registry/backend/src/environments/environment.ts

again, hopefully a final fix
simply return empty string as fallback
https://github.com/island-is/island.is/runs/2419387239#step:10:1289

fix(icelandic-names-registry): default to string for auth values

---

libs/service-portal/document-provider/src/screens/SingleDocumentProvider/DocumentProviderOrganisationForm.tsx

Fixing broken build. Somehow an error got through.
Fix broken build

fix(dpo): fixing broken build

---

.github/CODEOWNERS

chore(core): add codeowner for api-domains-translations

---

libs/auth-api-lib/seeders/20210426083138-add-admin-uris.js

fix(auth-admin-web): Add new redirecturis for staging and prod.

---

libs/auth-api-lib/seeders/20210425152526-app-client.js

fix(app-client): Adding app client to staging and prod through seed file

---

apps/web/screens/IcelandicNames.tsx

Should fix this, not sure how to reproduce locally to be sure
https://github.com/island-is/island.is/runs/2438384256#step:10:1301

fix(web): Fix build error

---

apps/web/components/IcelandicNamesSearcher/IcelandicNamesSearcher.tsx
apps/web/screens/IcelandicNames.tsx

Still having this error
https://github.com/island-is/island.is/runs/2438666343#step:10:1494
Now I am importing the Table without renaming it and destructuring the components from it

fix(web): Fix build error again

---

libs/application/templates/children-residence-change/src/fields/ContactInfo/index.tsx
libs/application/templates/children-residence-change/src/lib/ChildrenResidenceChangeTemplate.ts

- Bugfix for contact info screen
- Mark application as ready for production

fix(crc): mark ready for production and minor fix

---

libs/auth-api-lib/seeders/20210426152142-update-admin-scopes.js

fix(auth-admin-api): Set scopes access controlled. (#3609)

---

libs/auth-nest-tools/src/lib/current-user.decorator.ts

To be consistent with CurrentUser. This fixes a regression that affects all graphql external data in the application system.

fix(application-system): hotfix make sure CurrentRestUser includes authorization header

---

libs/application/templates/children-residence-change/src/forms/ChildrenResidenceChangeForm.ts
libs/application/templates/children-residence-change/src/lib/messages/externalData.ts

Cherry picking commit from main
- Merges #3606 to release

fix(crc): Removes otherparent from data gathering screen (#3606)

---

apps/endorsement-system/seeders/20210325171826-development.js
apps/endorsement-system/src/app/modules/endorsementValidator/endorsementValidator.decorator.ts
apps/endorsement-system/src/app/modules/endorsementValidator/endorsementValidator.module.ts
apps/endorsement-system/src/app/modules/endorsementValidator/endorsementValidator.service.ts
apps/endorsement-system/src/app/modules/endorsementValidator/validators/minAge/minAgeValidator.service.spec.ts
apps/endorsement-system/src/app/modules/endorsementValidator/validators/minAge/minAgeValidator.service.ts
apps/endorsement-system/src/app/modules/endorsementValidator/validators/minAgeByDate/minAgeByDateValidator.service.spec.ts
apps/endorsement-system/src/app/modules/endorsementValidator/validators/uniqueWithinTags/uniqueWithinTagsValidator.service.spec.ts

We need to validate if endorser is of age when endorsing
- We want to set a min age for validating
- Added tests
- Fixed test names

feat(endorsement-system): Min age validation

---

apps/application-system/api/src/app/modules/application/files/utils/pdf.ts

https://app.asana.com/0/1199733748699731/1200252846943288

fix(crc): fix character encoding

---

apps/endorsement-system/src/app/modules/endorsement/e2e/endorsement.spec.ts
apps/endorsement-system/src/app/modules/endorsement/endorsement.controller.ts
apps/endorsement-system/src/app/modules/endorsement/endorsement.service.ts
apps/endorsement-system/src/app/modules/endorsementList/endorsementList.controller.ts
libs/api/domains/endorsement-system/src/lib/endorsementSystem.resolver.ts
libs/api/domains/endorsement-system/src/lib/endorsementSystem.service.ts

We are currently not able to get a list of endorsements.
- Added a list endpoint
- Updated test

fix(endorsement-system): Get endorsements list

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx

Was mistaking string for boolean, making chatbot always hidden as `'false'` is not `false`

fix(web): Fix if condition for hiding chatbot

---

libs/application/templates/institution-collaboration/src/lib/template.ts

Set ready for application flag as true

fix: set readyForProduction flag on collaboration application

---

libs/auth-api-lib/migrations/20210428122216-api_scope_user_rename_updated_column.js

feat('auth-api-lib): Renane updated column

---

apps/air-discount-scheme/backend/migrations/20210428140700-fix-customer-record.js

An airline company inserted wrong departure dates on a specific entry.
An airline company, using Loftbru, had a bug which they have now fixed. The entry within this migration is being amended so that the customer gets their connecting flight codes

fix(air-discount-scheme): Fix specific customer record

---

apps/auth-admin-web/services/TranslationService.ts

feat('auth-admin-web'): Encode Uri for translations

---

apps/application-system/api/src/app/modules/application/files/file.service.ts

fix(crc): Awaits uploading file to s3

---

libs/application/template-api-modules/src/lib/modules/templates/children-residence-change/children-residence-change.service.ts
libs/application/template-api-modules/src/lib/modules/templates/children-residence-change/emailGenerators/index.ts
libs/application/template-api-modules/src/lib/modules/templates/children-residence-change/emailGenerators/syslumennNotification.ts
libs/application/template-api-modules/src/lib/modules/templates/children-residence-change/utils.spec.ts
libs/application/template-api-modules/src/lib/modules/templates/children-residence-change/utils.ts

Sends email to syslumenn when uploading to starfskerfi fails.

feat(crc): Sends email to syslumenn on upload failure

---

apps/judicial-system/backend/src/app/modules/case/case.service.ts
apps/judicial-system/backend/src/app/modules/notification/notification.service.ts

https://app.asana.com/0/1199153462262248/1200214145052890
Example filename before change: **R-666/2021** changed to  **Þingbók og úrskurður R-666/2021** and **007-2021-666** changed to **Krafa um gæsluvarðhald 007-2021-666" / "Krafa um farbann 007-2021-666**.
The new names are more clear.

feat(judicial-system): Changed the filenames for attachments

---

apps/judicial-system/web/src/routes/Judge/Overview/Overview.treat.ts
apps/judicial-system/web/src/routes/Judge/Overview/Overview.tsx
apps/judicial-system/web/src/utils/hooks/useCase.tsx

https://app.asana.com/0/1199153462262248/1200258760543527
Always allow manual court case creation.
https://user-images.githubusercontent.com/3789875/116562527-c3797100-a8f2-11eb-8ee9-821315cfa7f2.mov

feat(judicial-system): Always allow manual court case creation

---

apps/judicial-system/backend/src/app/modules/notification/notification.service.ts

https://app.asana.com/0/1199153462262248/1200089982514663
Send a copy of prison email to prosecutors
This is something that prosecutors are asking a lot for.

feat(judicial-system): Send a copy of prison email to prosecutors

---

apps/judicial-system/backend/src/app/modules/file/awsS3.service.ts
apps/judicial-system/backend/src/app/modules/file/file.service.ts
apps/judicial-system/backend/src/app/modules/file/file.spec.ts
apps/judicial-system/web/src/routes/Prosecutor/Overview/Overview.tsx
apps/judicial-system/web/src/shared-components/CaseFileList/CaseFileList.tsx
apps/judicial-system/web/src/shared-components/Modal/Modal.tsx
apps/judicial-system/web/src/utils/hooks/useFileList.tsx

https://app.asana.com/0/322488613152836/1200181907151990
Display a modal that tells the user that a file is no longer available if the file is no longer in S3 for any reason. 
Better UX
https://user-images.githubusercontent.com/3789875/116530872-0c6afe80-a8ce-11eb-8fef-ea8096b47122.mov

feat(judicial-system): Case file not found

---

apps/judicial-system/web/src/routes/Judge/Ruling/StepOne/RulingStepOne.tsx

https://app.asana.com/0/1199153462262248/1200221198057870
Added a CaseFileList accordion item to the ruling page

feat(judicial-system): Added a CaseFileList accordion item to the ruling page

---

libs/application/templates/party-letter/src/fields/EndorsementList/EndorsementTable.tsx
libs/application/templates/party-letter/src/fields/EndorsementList/index.tsx
libs/application/templates/party-letter/src/types.ts

Check if application includes endorsement id
if so: query endorsement list
otherwise: make a connection to endorsement system, update the application answers and query endoresement list

feat(applications-party-letter): Connect party letter application to endorsement system

---

apps/judicial-system/web/src/routes/Judge/CourtRecord/CourtRecord.spec.tsx
apps/judicial-system/web/src/routes/Judge/CourtRecord/CourtRecord.tsx

https://app.asana.com/0/1199153462262248/1200270543199436
Fix litigation presentations formatting
There was a weird, invisible formatting on the text I copied.

fix(judicial-system): Fix litigation presentations formatting

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/screens/Organization/Home.tsx
apps/web/screens/Organization/NewsItem.tsx
apps/web/screens/Organization/NewsList.tsx
apps/web/screens/Organization/Services.tsx
apps/web/screens/Organization/SubPage.tsx
apps/web/screens/Organization/Syslumenn/Auction.tsx
apps/web/screens/Organization/Syslumenn/Auctions.tsx
apps/web/screens/Organization/Syslumenn/Homestay.tsx

* Remove breadcrumbs from organization frontpage
* Remove _Stofnanir_ / _Organizations_ breadcrumb from organization subpage breadcrumbs list
Requested by the Digital Iceland team.

feat(web): Organization breadcrumbs

---

apps/services/auth-api/src/app/modules/permissions/permissions.controller.ts

fix(auth-api): Use correct guards.

---

.github/CODEOWNERS
libs/application/template-api-modules/src/lib/modules/template-api.service.ts
libs/application/template-api-modules/src/lib/modules/templates/index.ts
libs/application/template-api-modules/src/lib/modules/templates/party-letter/party-letter.module.ts
libs/application/template-api-modules/src/lib/modules/templates/party-letter/party-letter.service.ts
libs/application/templates/party-letter/src/constants.ts
libs/application/templates/party-letter/src/dataProviders/CurrentUserCompanies.ts
libs/application/templates/party-letter/src/fields/EndorsementDisclaimer/index.tsx
libs/application/templates/party-letter/src/fields/EndorsementList/EndorsementTable.tsx
libs/application/templates/party-letter/src/fields/EndorsementList/index.tsx
libs/application/templates/party-letter/src/fields/PartyLetterApplicationReview/index.tsx
libs/application/templates/party-letter/src/fields/Review/index.tsx
libs/application/templates/party-letter/src/forms/LetterApplicationForm.ts
libs/application/templates/party-letter/src/lib/PartyLetterApplicationTemplate.ts
libs/application/templates/party-letter/src/lib/dataSchema.ts
libs/application/templates/party-letter/src/lib/messages.ts
libs/application/templates/party-letter/src/types.ts
workspace.json

Currently endorsement list is being created with a client side call, this is exposes it to manipulation.
- Created api endpoint to create list
- Made frontend get endorsement list id from external data
- Fixed minor inconsistencies in variable names
- Flattened answer variable list
- Fixed address type
- Added variables to list count message
- Fixed synced messages with Contentful errors
- Added create endorsement call to api on collect endorsements step entry
- Further improve integration of endorsement system

feat(application-template-party-letter): Endorsement system creation to API

---

apps/judicial-system/web/.eslintrc.json
apps/judicial-system/web/pages/_document.tsx
apps/judicial-system/web/src/shared-components/Header/Header.tsx
apps/judicial-system/web/src/shared-components/SkipToContent/SkipToContent.treat.ts
apps/judicial-system/web/src/shared-components/SkipToContent/SkipToContent.tsx
apps/judicial-system/web/src/shared-components/index.ts

https://app.asana.com/0/1199153462262248/1200279054978684
Use a11y eslint rules
To make sure we are following best practices in accessibility

feat(judicial-system): Use a11y eslint rules

---

apps/judicial-system/api/src/app/modules/case/interceptors/case.transformer.spec.ts
apps/judicial-system/api/src/app/modules/case/interceptors/case.transformer.ts

https://app.asana.com/0/1199153462262248/1200283778906204
Increase time where a case is appealable from three to seven days
We got feedback that three days was too short

fix(judicial-system): Increase time where a case is appealable from three to seven days

---

apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepThree/StepThree.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepThree/StepThreeForm.tsx

https://app.asana.com/0/1199153462262248/1200289738477335
Splitting StepThree into a data layer and presentation layer
Better code readability

refactor(judicial-system): Refactor step three

---

apps/services/endorsements/api/src/app/app.module.ts
apps/services/endorsements/api/src/app/modules/endorsement/endorsement.controller.ts
apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.controller.ts
apps/services/endorsements/api/src/environments/environment.prod.ts
apps/services/endorsements/api/src/environments/environment.ts

Added audits for all user interactions with the endorsements system.
- Added calls to audit logs

feat(services-endorsements-api): User audit

---

package.json
yarn.lock

Fix failing security audit
It's blocking new pr builds from passing.

fix(core): Fix failing security audit

---

libs/application/template-api-modules/src/lib/modules/templates/children-residence-change/children-residence-change.service.ts
libs/application/template-api-modules/src/lib/modules/templates/children-residence-change/emailGenerators/applicationSubmitted.ts

feat(crc): Case number in email

---

.github/actions/package.json
.github/actions/yarn.lock

https://github.com/island-is/island.is/security/dependabot/.github/actions/yarn.lock/hosted-git-info/open

chore(build): upgrading vulnerable package

---

libs/auth-api-lib/src/lib/services/delegations.service.ts

fix(auth-api): Fix rsk error logging.

---

libs/application/ui-shell/src/components/FormExternalDataProvider.tsx

Updates icon to tray icon on external data provider screen. Tray icon is correct according to application system design system.

chore(as): External data icon

---

apps/services/endorsements/api/src/app/app.module.ts

Environment file is swapped for prod environment file causing type issues

fix(services-endorsements-api): Added fix for environment config

---

libs/application/templates/funding-government-projects/src/lib/messages/definitionOfApplicant.ts
libs/application/templates/funding-government-projects/src/lib/messages/overview.ts

https://app.clickup.com/t/jk371k
Fixing translation ids
To translate values for the application.

fix: Application for funding government projects translation id fixes

---

apps/web/screens/Organization/NewsItem.tsx
apps/web/screens/Organization/NewsList.tsx

Add [#3786](https://github.com/island-is/island.is/pull/3786) on top of relase 8.2.0

fix(web): Organization news

---

libs/application/templates/login-service/src/lib/messages/applicant.ts
libs/application/templates/login-service/src/lib/messages/application.ts
libs/application/templates/login-service/src/lib/messages/errors.ts
libs/application/templates/login-service/src/lib/messages/overview.ts
libs/application/templates/login-service/src/lib/messages/submitted.ts
libs/application/templates/login-service/src/lib/messages/technicalContact.ts
libs/application/templates/login-service/src/lib/messages/technicalInfo.ts
libs/application/templates/login-service/src/lib/messages/terms.ts

https://app.clickup.com/t/j37dwv
Add correct link to agreement terms.
Vital for application

fix(login-service-application): agreement terms url fixed

---

libs/application/templates/data-protection-complaint/src/forms/ComplaintForm.ts

https://app.clickup.com/t/h35384
Remove disabled on fields that are not supposed to be disabled.
User needs to be able to change relevant fields.

fix(data-protection-complaint): remove disabled on fields that should not be disabled.

---

apps/web/components/ChatPanel/ChatPanel.treat.ts
apps/web/components/ChatPanel/ChatPanel.tsx
apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Sticky/Sticky.tsx
apps/web/screens/Article.tsx

This PR includes three cherry-picked commits that we need to deploy before launching the syslumenn web.
By request of Digital Iceland / Syslumenn

fix(web): Cherry-picked commits for syslumenn web

---

libs/application/templates/institution-collaboration/src/lib/template.ts

Add ready for prod flag back in to collaboration application 
To enable collaboration application on prod.

fix(collaboration-application): add readyforprodflag

---

.github/CODEOWNERS
libs/application/templates/funding-government-projects/src/lib/FundingGovernmentProjectsTemplate.ts
libs/application/templates/institution-collaboration/src/lib/template.ts

Set readyForProduction flag for two applications on main.
They are supposed to be ready for prod

fix(aafgp and ic): set ready for prod on main

---

apps/web/components/Organization/Wrapper/Themes/SyslumennTheme/SyslumennHeader.treat.ts
apps/web/screens/queries/Organization.tsx

fix(web): Fix image in syslumenn header

---

libs/application/templates/family-matters/children-residence-change/src/fields/ChangeInformation/index.tsx
libs/application/templates/family-matters/children-residence-change/src/fields/Overview/index.tsx
libs/application/templates/family-matters/children-residence-change/src/fields/Terms/index.tsx
libs/application/templates/family-matters/children-residence-change/src/forms/ChildrenResidenceChangeForm.ts
libs/application/templates/family-matters/children-residence-change/src/forms/ParentBForm.ts
libs/application/templates/family-matters/children-residence-change/src/lib/dataSchema.ts
libs/application/templates/family-matters/children-residence-change/src/lib/messages/contract.ts
libs/application/templates/family-matters/children-residence-change/src/lib/messages/newResidence.ts
libs/application/templates/family-matters/children-residence-change/src/lib/messages/terms.ts
libs/application/templates/family-matters/core/src/utils/dataSchema.ts
libs/application/templates/family-matters/joint-custody-agreement/src/lib/dataSchema.ts

https://app.asana.com/0/1199733748699731/1200321465204794
- Removed checkbox from "Hvert á að flytja" screen
- Reduced the terms checkboxes to just one checkbox
- Added a checkbox to the overview/contract screen so the user agrees to sign the contract
- `validateTerms` now defaults to 1 term
I will push strings to contentful when this gets merged

feat(crc): contract checkbox

---

libs/auth-api-lib/migrations/20210519134445-api-scope-groups.js

fix(auth-api-lib): Fix error in foreign key in migration

---

apps/auth-admin-web/components/Client/form/ClientCreateForm.tsx
apps/auth-admin-web/components/Layout/StatusBar.tsx

#Fix bug that selects different values than in db

feat('auth-admin-web'): feature/client edit fix

---

apps/services/auth-api/src/app/modules/resources/resources.controller.ts
libs/auth-api-lib/src/lib/services/resources.service.ts

feat(auth-api): Add endpoint for actor scopes

---

libs/application/templates/family-matters/children-residence-change/src/fields/Overview/index.tsx

https://app.asana.com/0/1199733748699731/1200378473129915

fix(crc): parent B signature not working

---

.github/workflows/pullrequest.yml
.github/workflows/push.yml

build: reverting fully the self-hosted runners

---

workspace.json

Get the public-api service to have docker container images built

build(auth-public-api): Creating docker image for service

---

apps/judicial-system/web/src/routes/Judge/Confirmation/Confirmation.spec.tsx
apps/judicial-system/web/src/routes/Judge/Confirmation/Confirmation.treat.ts
apps/judicial-system/web/src/routes/Judge/Confirmation/Confirmation.tsx
apps/judicial-system/web/src/routes/Judge/CourtRecord/CourtRecord.spec.tsx
apps/judicial-system/web/src/routes/Judge/HearingArrangements/HearingArrangements.spec.tsx
apps/judicial-system/web/src/routes/Judge/Ruling/StepOne/RulingStepOne.spec.tsx
apps/judicial-system/web/src/routes/Judge/Ruling/StepTwo/RulingStepTwo.spec.tsx
apps/judicial-system/web/src/routes/Judge/Ruling/StepTwo/RulingStepTwo.treat.ts
apps/judicial-system/web/src/routes/Judge/Ruling/StepTwo/RulingStepTwo.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepFour/StepFour.spec.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepThree/StepThree.spec.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepTwo/StepTwo.spec.tsx
apps/judicial-system/web/src/utils/mocks.ts
workspace.json

Færa "þinghaldi lauk" á skjáinn á undan
☝️ 
This prevents a raise condition.

fix(judicial-system): Moves court end time to the previous screen

---

libs/application/templates/family-matters/children-residence-change/src/fields/components/ContractOverview.tsx
libs/application/templates/family-matters/children-residence-change/src/lib/messages/contract.ts

https://app.asana.com/0/1199733748699731/1200378473129907

fix(crc): duration text label when permanent

---

libs/application/templates/family-matters/core/src/components/ErrorModal/ErrorModal.tsx

https://app.asana.com/0/1199733748699731/1200366363488802

fix(crc): left align link in modal

---

libs/island-ui/core/src/lib/Header/UserDropdown/UserDropdown.tsx
libs/island-ui/core/src/lib/ModalBase/ModalBase.tsx

https://github.com/island-is/island.is/pull/3981

fix(island-ui): avoid jump from scrollbar width changes (#3981)

---

libs/application/templates/parental-leave/src/forms/EmployerApproval.ts
libs/application/templates/parental-leave/src/forms/OtherParentApproval.ts

I messed up the buttons orders, mb

fix(parental-leave): buttons orders

---

apps/services/auth-admin-api/src/app/modules/resources/resources.module.ts
apps/services/auth-api/src/app/modules/permissions/permissions.module.ts
apps/services/auth-api/src/app/modules/resources/resources.module.ts
libs/auth-api-lib/migrations/20210528141848-create-domain.js
libs/auth-api-lib/src/index.ts
libs/auth-api-lib/src/lib/entities/dto/domain.dto.ts
libs/auth-api-lib/src/lib/entities/models/domain.model.ts
libs/auth-api-lib/src/lib/services/resources.service.ts

#Adding Domain to db and auth-lib

feat(auth-api-lib): Adding Domain to db and auth-lib

---

apps/auth-admin-web/entities/dtos/api-scope-group.dto.ts
apps/auth-admin-web/entities/models/api-scope-group.model.ts
libs/auth-api-lib/migrations/20210531095547-alter-domain.js
libs/auth-api-lib/src/lib/entities/dto/api-scope-group.dto.ts
libs/auth-api-lib/src/lib/entities/models/api-scope-group.model.ts

#Alter apiScopeGroup. Set domain as non nullable

feat(auth-api-lib): Alter apiScopeGroup. Set domain as non nullable

---

apps/judicial-system/backend/src/app/formatters/rulingPdf.ts

https://app.asana.com/0/1199153462262248/1200352906978927

fix(judicial-system): Replace 'Krafa lögreglu' with 'Krafa'

---

apps/api/src/app/environments/environment.prod.ts

fix(api): Use XROAD_BASE_PATH_WITH_ENV instead of XROAD_BASE_PATH

---

apps/gjafakort/api/src/environments/environment.ts
apps/gjafakort/api/src/services/versionConfiguration.ts

Removing configcat configuration and environment flag check for the new giftcard, making the new one the default

chore(gjafakort): Removing configcat configuration

---

apps/application-system/api/esbuild.json
apps/judicial-system/backend/esbuild.json

Should fix runtime of judicial-system-backend and application-system-api

fix(bundler): Add pdfkit and color* to externals

---

package.json
yarn.lock

Should fix the security audit error

fix(core): resolve ws dependency to a newer version

---

workspace.json

Fix glob match in workspace.json
gjafakort-application migrations are failing

fix(gjafakort-application): Add sequelize assets

---

apps/api/src/app/environments/environment.ts

fix(api): use XROAD_CLIENT_ID for national registry

---

libs/application/templates/parental-leave/src/lib/dataSchema.ts
libs/application/templates/parental-leave/src/lib/messages.ts

Validate that bank account is of length 4 (bank) + 2 (ledger) + 6 (number) = 12

chore(application-templates-parental-leave): Validate bank account length

---

libs/auth-api-lib/migrations/20210602131057-modify_delegations.js
libs/auth-api-lib/src/lib/entities/dto/delegation-scope.dto.ts
libs/auth-api-lib/src/lib/entities/dto/delegation.dto.ts
libs/auth-api-lib/src/lib/entities/models/delegation-scope.model.ts
libs/auth-api-lib/src/lib/entities/models/delegation.model.ts
libs/auth-api-lib/src/lib/services/delegation-scope.service.ts
libs/auth-api-lib/src/lib/services/delegations.service.ts

feat(auth-public-api): delegation modifications

---

handbook/technical-overview/adr/README.md

- Fixes https://github.com/island-is/island.is/issues/3955

fix(docs): link to ADR 13

---

libs/auth-api-lib/src/lib/services/delegations.service.ts

#Fix delegation find valid custom to

feat(auth-api-lib): Fix delegation find valid custom to

---

.github/CODEOWNERS

Update codeowners
Changed ownership of project.
N/A

chore(codeowners): hugsmidjan for service-portal

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/applicationApprovedByEmployer.ts
libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/index.ts
libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts

- Update copy in email to not make it look like it was approved by Fæðingarorlofssjóður
- Only send if applicant is not self employed

chore(application-templates-parental-leave): Update copy in email when application is approved by employer

---

apps/api/src/app/environments/environment.ts

Add global prefix to authPublicApi url for local development.
To fix local development.

fix(api): add prefix to authPublicApi url

---

apps/web/components/Organization/Slice/Render/SliceDropdown.tsx
apps/web/screens/Organization/SubPage.tsx
apps/web/screens/Organization/Syslumenn/Auctions.tsx
libs/api/domains/cms/src/lib/cms.contentful.service.ts
package.json
yarn.lock

Cherry-picked #3845 by request from Syslumenn.
Also fixes a grid offset issue with subpage dropdowns (see screenshot) - not yet merged on main
This has been fixed.

fix(web): Organization web hot-fixes

---

libs/application/templates/parental-leave/src/forms/Prerequisites.ts
libs/application/templates/parental-leave/src/lib/messages.ts

- https://app.asana.com/0/1182378413629561/1200408166368980

feat(parental-leave): new checkbox label message

---

apps/judicial-system/web/src/routes/Judge/Confirmation/Confirmation.spec.tsx
apps/judicial-system/web/src/routes/Judge/Overview/Overview.spec.tsx
apps/judicial-system/web/src/routes/Shared/DetentionRequests/DetentionRequests.spec.tsx
apps/judicial-system/web/src/routes/Shared/Login/Login.spec.tsx
apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.spec.tsx
apps/judicial-system/web/src/shared-components/Logo/Logo.spec.tsx
apps/judicial-system/web/src/shared-components/UserProvider/UserProvider.spec.tsx
apps/judicial-system/web/src/shared-components/UserProvider/UserProvider.tsx

https://app.asana.com/0/1199153462262248/1200403423569989
☝️ 

fix(judicial-sytem): Stop current user spam

---

apps/judicial-system/api/esbuild.json

fix(judicial-system): Adds islandis-login refereence to esbuild

---

apps/services/auth-public-api/src/app/modules/delegations/delegations.controller.ts
apps/services/auth-public-api/src/app/modules/resources/api-scope.controller.ts
apps/services/auth-public-api/src/app/modules/translation/translation.controller.ts
apps/services/auth-public-api/src/main.ts

feat(auth-public-api): Feature/fix endpoints

---

apps/services/auth-public-api/src/environments/environment.ts

fix(auth-public-api): Fix audience

---

libs/localization/README.md

docs: Explain the `extract-strings` script, improve examples

---

workspace.json

Schema generation is failing on main for application system api.
- Fixed output patch from schema generation
- Removed duplicates
- Removed redundant output path

fix(application-templates-party-application): Schema generation

---

package.json
yarn.lock

Fixes security audit errors
It's blocking the pipe

fix(core): Fixes security audit errors

---

.github/dependabot.yml

This might be too much. Objections to trying it out?

chore(deps): Enable dependabot pull requests

---

.github/CODEOWNERS

chore(parental-leave): fix codeowner on vmst api domain

---

apps/skilavottord/ws/esbuild.json

Fix skilavottord login process

chore(skilavottord): Adding dependency that cannot be js-bundled

---

yarn.lock

I pulled main and ran `yarn` and that resulted in this change in yarn.lock. I believe someone didn't check in this change and pushed to main.

chore(core): Yarn lock updated

---

apps/application-system/api/src/app/modules/application/files/pdfGenerators/residenceChange.ts

https://app.asana.com/0/1199733748699731/1200446273231576

chore(crc): change heading text

---

libs/application/templates/family-matters/core/src/fields/SelectChildren/index.tsx
libs/application/templates/family-matters/core/src/utils/index.ts

https://app.asana.com/0/1199733748699731/1200403547319706

fix(crc): children order

---

apps/services/auth-api/src/app/modules/delegations/delegations.controller.ts
apps/services/auth-api/src/app/modules/delegations/delegations.module.ts
apps/services/auth-api/tsconfig.json
apps/services/auth-public-api/src/app/modules/delegations/delegations.module.ts
libs/auth-api-lib/src/lib/entities/models/delegation-scope.model.ts
libs/auth-api-lib/src/lib/services/delegation-scope.service.ts

feat(auth-api-lib): Get delegated scopes

---

apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/HearingArrangements/HearingArrangements.tsx
apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepTwo/StepTwo.tsx
apps/judicial-system/web/src/utils/hooks/useCase.tsx

https://app.asana.com/0/1199153462262248/1200164237014735
☝️ This PR fixes some issues that came up during implementation of the above story.
Transitions were broken

fix(judicial-system): Fixes transitions

---

libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts

chore(parental-leave): Enabling template for production

---

apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/Overview/Overview.tsx

https://app.asana.com/0/1199153462262248/1200164237014735/f
☝️ Fixes a bug.found during testing
Bug

feat(judicial-system): Fixes error introduced by transition refactoring

---

apps/application-system/api/src/environments/environment.ts
libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/assignOtherParentEmail.ts
libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/otherParentRejectedEmail.ts
libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.spec.ts
libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.ts
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.spec.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

Merging #4220 into the release branch
* Move getOtherParentId to parentalLeaveUtils
* Use getOtherParentId when assigning other parent to application
* Fix url in other parent emails
* Refactor period percentage calculation

chore(parental-leave): Fix other parent issues (#4220)

---

apps/auth-admin-web/components/Admin/form/DomainCreateForm.tsx
apps/auth-admin-web/components/Admin/form/GrantTypeCreateForm.tsx
apps/auth-admin-web/components/Admin/form/IdpProviderCreateForm.tsx
apps/auth-admin-web/components/Admin/form/LanguageCreateForm.tsx
apps/auth-admin-web/components/Admin/form/TranslationCreateForm.tsx
apps/auth-admin-web/components/Client/form/ClientBasicCreateForm.tsx
apps/auth-admin-web/components/Client/form/ClientCreateForm.tsx
apps/auth-admin-web/components/Resource/forms/ApiResourceCreateForm.tsx
apps/auth-admin-web/components/Resource/forms/ApiScopeCreateForm.tsx
apps/auth-admin-web/components/Resource/forms/IdentityResourceCreateForm.tsx
apps/auth-admin-web/components/common/HintBox.tsx
apps/auth-admin-web/i18n/locales/en.json
apps/auth-admin-web/styles/HintBox.scss
apps/auth-admin-web/styles/_FormLayout.scss
apps/auth-admin-web/utils/validation.utils.ts

* Add DelegationScope and Delegation to Resources.Module
* Client validation and api scope fix
* Adding domain validation
* Not validating identifiers when editing. Change validators for identityresource name and apiresource name
* Add to language file
* Hint box for Api Resource
* Adjusting text. Fixing functions.. adding hint boxes
* adding id
* Adding id2
* Remove console log

fix(auth-admin-web): validations and hint boxes (#4240)

---

apps/auth-admin-web/components/Client/form/ClientAllowedScopesForm.tsx
apps/auth-admin-web/components/Resource/forms/ApiResourceScopeForm.tsx
apps/auth-admin-web/utils/validation.utils.ts

fix(auth-admin-web): Validation fixes

---

apps/auth-admin-web/components/Client/form/ClientAllowedScopesForm.tsx
apps/auth-admin-web/components/Resource/forms/ApiResourceScopeForm.tsx
apps/auth-admin-web/utils/validation.utils.ts

fix(auth-admin-web): Validation fixes (#4249)

---

apps/judicial-system/backend/migrations/20210608081018-update-case.js

https://app.asana.com/0/1199153462262248/1200414912242011/f
☝️ fixes a db migration for the above task - the migration was failing on staging
Must fix to be able to release

fix(judicial-system): Fixes demands migration

---

apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepFour/StepFour.tsx

https://app.asana.com/0/1199153462262248/1200414912242011/f
☝️ improves the above by making the field required
Requirement

fix(judicial-system): Makes demands required for custody and travel ban

---

apps/auth-admin-web/components/Admin/form/GrantTypeCreateForm.tsx
apps/auth-admin-web/i18n/locales/en.json
apps/auth-admin-web/utils/validation.utils.ts

feat(auth-admin-web): Fix validation for Grant Type. Add Hint box for Grant Type

---

libs/auth-api-lib/migrations/20210621120546-create_indexes.js
libs/auth-api-lib/migrations/20210621121659-modify_translation.js

feat(auth-api-lib): Alter translation table & Create indexes

---

libs/auth-api-lib/src/lib/services/grants.service.ts

feat(auth-api-lib): Create if grant does not exist in update command

---

apps/judicial-system/web/messages/policeDemandsForm.ts
apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/PoliceDemands/PoliceDemandsForm.tsx

https://app.asana.com/0/1199153462262248/1200474750183719
- Added a tooltip and translation string
- To display more information for the user

feat(judicial-system): add tooltip to request to date field

---

libs/application/templates/institution-collaboration/src/lib/messages.ts
libs/application/templates/institution-collaboration/src/lib/template.ts

add message descriptor for application name
More descriptive

feat(ia): add message descriptor for application name

---

scripts/create-secret.sh

You've got a problem. You decide to use regex. Now you've got two problems.

fix: Fix length check in create secret
