island-is/island.is

libs/island-ui/core/src/lib/Alert/Alert.stories.tsx
libs/island-ui/core/src/lib/Alert/Alert.treat.ts
libs/island-ui/core/src/lib/Alert/Alert.tsx

The alert component can either be of type Info or Error. It has fluid width, meaning you'll have to wrap it in a container to control it's width.

Added an Alert component

---

apps/services/search-indexer/src/app/indexing.service.ts

Prevent undefined field becoming part of 'reducedContent' for ES document

Fix for "undefined" in search results

---

apps/services/search-indexer/src/app/indexing.service.ts
libs/api/content-search/src/services/elastic.service.ts

The indexer goes down when trying to map articles that have unpublished content.
Added this as a quick fix, this will be handled properly when we tackle indexing of multiple content types
- Made indexer not go down due to unpublished content

Mapper not handling unpublished content fix

---

apps/services/search-indexer/src/app/indexing.service.ts
apps/services/search-indexer/src/contentful/syncer.ts
apps/services/search-indexer/src/environments/environment.prod.ts
apps/services/search-indexer/src/environments/environment.ts
libs/api/content-search/src/services/elastic.service.ts

The `sync` was not deleting entries when doing normal sync.
Parameters passes to contentful sync caused `deletedEntries` to be allways empty.
We have an upcoming task to expand the sync to support locale and multiple content type search from contentful,
we will fix ts types and optimize during that process
- `sync` now deletes entries from the ES index
- Made sync mapping not fail when encountering nested relatedArticles
- `content_type` argument caused sync endpoint to not return deleted entries
- Added `deleteByIds`
- Added comments
- Added TODO comments as reminders

Contentful sync

---

apps/web/components/SideMenu/SideMenu.treat.ts
apps/web/components/SideMenu/SideMenu.tsx
apps/web/components/SideMenu/components/LinkBox/LinkBox.treat.ts
apps/web/components/SideMenu/components/LinkBox/LinkBox.tsx

- Fix scrollbar being visible on desktop. Content does not scroll on desktop, users should scroll the whole page.
- Allow vertical scrolling inside content on mobile.
- Don't close the SideMenu on `click outside` as users will accidentally close it when using the main scrollbar.

Fix further outstanding issues with SideMenu

---

libs/island-ui/core/src/lib/Input/Input.stories.tsx
libs/island-ui/core/src/lib/Input/Input.treat.ts
libs/island-ui/core/src/lib/Input/Input.tsx

If the `required` prop is set on input fields, a red star is added to the label. It doesn't add any kind of validation, that's still the consumers job.

Added a required prop to input

---

apps/web/components/FrontpageTabs/FrontpageTabs.treat.ts
apps/web/components/FrontpageTabs/FrontpageTabs.tsx
apps/web/screens/Home.tsx
libs/island-ui/core/src/lib/Button/Button.tsx

This was made with a tabs functionality in mind and these arrows (prev/next) only act as moving to previous or next tab and are automatically giving the selected tab focus.

Added prev/next arrow buttons to frontpage tabs

---

apps/web/components/SideMenu/SideMenu.treat.ts

Fix Hero's arrow buttons having higher zIndex than SideMenu

fix: SideMenu zIndex issue

---

apps/air-discount-scheme/web/components/Content/Content.tsx

First solution was based on this comment https://github.com/contentful/rich-text/issues/96#issuecomment-511100434
React should be able to render arrays if you provide all elements with keys, so there should be no need to flatten the array

Ads - using map instead of flatMap

---

apps/judicial-system/api/src/app/modules/auth/jwt.strategy.ts
apps/judicial-system/web/src/api/index.ts
apps/judicial-system/web/src/routes/Login/Login.treat.ts
apps/judicial-system/web/src/routes/Login/Login.tsx
apps/judicial-system/web/src/utils/cookies.ts

Reads csrfToken from cookie sent from server and uses that as an authentication agains API. If the API is called without this token, it returns 401 and you are redirected to the login page with an error message saying that the login is no longer valid.

Adds authorisation header to api calls

---

apps/web/components/SideMenu/SideMenu.treat.ts

Initial tab focus:
Inactive tab focus:

Solve SideMenu active-tab focus indicator issue

---

libs/island-ui/core/src/lib/Input/Input.mixins.ts
libs/island-ui/core/src/lib/Input/Input.stories.tsx
libs/island-ui/core/src/lib/Input/Input.treat.ts
libs/island-ui/core/src/lib/Input/Input.tsx

resolves #764
Use native textarea behavior and lock resize to only work vertically, component width should be block (100%) and controlled by parent, so there should be no need to resize horizontally

island-ui - Textarea support for inputs

---

apps/judicial-system/api/README.md
apps/judicial-system/api/src/app/modules/auth/auth.controller.ts
apps/judicial-system/api/src/app/modules/auth/auth.guard.ts
apps/judicial-system/api/src/app/modules/auth/auth.service.spec.ts
apps/judicial-system/api/src/app/modules/auth/auth.service.ts
apps/judicial-system/api/src/app/modules/auth/jwt.strategy.ts
apps/judicial-system/api/src/app/modules/case/case.controller.ts
apps/judicial-system/api/src/app/modules/case/case.model.ts
apps/judicial-system/api/src/app/modules/case/e2e/case.spec.ts
apps/judicial-system/api/src/app/modules/user/user.controller.spec.ts
apps/judicial-system/api/src/app/modules/user/user.controller.ts
apps/judicial-system/api/src/app/modules/user/user.module.ts
apps/judicial-system/api/src/app/modules/user/user.service.spec.ts
apps/judicial-system/api/src/app/modules/user/user.service.ts
apps/judicial-system/api/src/app/modules/user/user.types.ts
apps/judicial-system/api/src/openapi.yaml
apps/judicial-system/api/test/setup.ts
apps/judicial-system/web/src/routes/Login/Login.tsx

Adds an api endpoint to get the current user.
Makes it possible to skip island.is authentication during local development (see Readme).

Judicial system user endpoint

---

libs/island-ui/contentful/src/lib/Image/Image.treat.ts
libs/island-ui/contentful/src/lib/Image/Image.tsx

* Remove grey background color
* Set opacity to 0 on blurred thumbnail after image has been loaded
Before:
After:

Setting opacity to 0 on blurred thumbnail after image has been loaded

---

libs/api/domains/cms/src/lib/models/article.model.ts
libs/api/domains/cms/src/lib/models/html.model.ts
libs/api/domains/cms/src/lib/models/landingPage.model.ts
libs/api/domains/cms/src/lib/models/lifeEventPage.model.ts
libs/api/domains/cms/src/lib/models/processEntry.model.ts
libs/api/domains/cms/src/lib/models/questionAndAnswer.model.ts
libs/api/domains/cms/src/lib/models/sectionWithImage.model.ts
libs/api/domains/cms/src/lib/models/slice.model.ts
libs/api/domains/cms/src/lib/models/subArticle.model.ts

apollo in-memory-cache needs the [__typename, id] combination to be
unique for each slice. It the id is not unique, the cache might
return incorrect data, resulting in incorrect content to be shown
to the user

fix bug in apps/web graphql stack

---

libs/api/domains/documents/src/lib/document.connection.ts

Adding a check here, so when we run the API and we don't have the credentials we don't get an error

fix: add check for credentials

---

apps/judicial-system/web/src/routes/CreateDetentionRequest/StepTwo/StepTwo.tsx
apps/judicial-system/web/src/routes/DetentionRequests/DetentionRequests.tsx
apps/judicial-system/web/src/types.ts

This PR sets a case as SUBMITTED when you enter the second step of the flow. Ideally this would happen when you actually submit the case but that PR is still being worked on and we will move the code to its right place when it's merged(#875). If you now login with my ssn (1112902539) You'll only see the cases marked as SUBMITTED.

User role judge can see submitted cases

---

libs/island-ui/core/src/lib/Timeline/Timeline.tsx

Fix typo variant, allow only showing one number

Island.is/timeline improvements

---

.github/CODEOWNERS

Changed the core maintainer rule to only focus on root files and the .github directory.
Will re-enable the fallback rule when we've found a way to remove codegen schemas from git. 
This is to unblock the web team while they're working on the island.is launch.
Any change that touches the graphql schema causes changes in multiple generated schema files. This unneccessarily triggers code reviews for multiple codeowners, which slows down development.

Temporarily remove fallback codeowners rule

---

.github/workflows/build.yml

Maybe this allows us to trigger builds that for some reason are not
running (see discussions on #804)
We want to be able to run CI manually
https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

Add workflow dispatch trigger in CI

---

apps/web/components/LifeEventsCardsSection/LifeEventsCardsSection.tsx

Hide empty life events on frontpage
Contentful returns all published content even if it is empty we have to filter out the empty content

Removed empty life events

---

apps/web/screens/Article.tsx

article call to action button is back

---

apps/air-discount-scheme/api.graphql
apps/air-discount-scheme/api/src/app/modules/flightLeg/dto/flightLeg.input.ts
apps/air-discount-scheme/api/src/app/modules/flightLeg/flightLeg.model.ts
apps/air-discount-scheme/backend/migrations/20200921084928-store-cooperation.js
apps/air-discount-scheme/backend/src/app/modules/flight/dto/body.dto.ts
apps/air-discount-scheme/backend/src/app/modules/flight/flight.model.ts
apps/air-discount-scheme/backend/src/app/modules/flight/flight.service.ts
apps/air-discount-scheme/backend/src/app/modules/flight/test/integration/flight.service.spec.ts
apps/air-discount-scheme/web/graphql/possibleTypes.json
apps/air-discount-scheme/web/graphql/schema.tsx
apps/air-discount-scheme/web/screens/Admin/Admin.tsx
apps/air-discount-scheme/web/screens/Admin/components/Panel/Panel.tsx
apps/air-discount-scheme/web/screens/Admin/components/Summary/Summary.tsx

Store cooperation in flight_leg and show in Admin UI.
Before, the cooperation was overwriting the airline column in the flight_leg table,
which is incorrect. By moving it to the cooperation column, we can better explain
the airlines relationships in the Admin UI

Store cooperation for airlines

---

apps/web/components/LatestNewsSection/LatestNewsSection.tsx
apps/web/pages/en/news/index.tsx
apps/web/screens/Home.tsx
libs/api/domains/cms/src/lib/cms.contentful.service.ts
libs/api/domains/cms/src/lib/models/image.model.ts
libs/api/domains/cms/src/lib/models/news.model.ts

Made a quick fix for the english news on the frontpage.
Will itterate by mergeing the latest news endpoint into the getNews endpoint
- Made news qeujry use locale
- Made news mapper handle empty news items
- Added empty condition to api

Made frontpage news on english frontpage be in english

---

libs/api/domains/cms/src/lib/models/aboutPage.model.ts
libs/api/domains/cms/src/lib/models/slice.model.ts

New slice types are causing issues on live and dev sites in development
- Made slice types not in mapping logic be ignored
- To make environments more stable

Safe slice types

---

apps/air-discount-scheme/backend/src/app/modules/flight/dto/body.dto.ts
apps/air-discount-scheme/backend/src/app/modules/flight/flight.service.ts
apps/air-discount-scheme/backend/src/app/modules/flight/test/integration/flight.service.spec.ts
apps/air-discount-scheme/backend/src/app/modules/flight/test/unit/flight.controller.spec.ts

Adding cooperation parameter to createFlight body and save it with the flightleg
So Icelandair can inform whether the flightleg includes a flight from norlandair

Ads/adding cooperation paramter in creatFlight body

---

scripts/dockerfile-config/static-nginx.conf

Fixes #962 
See issue
The React-based static apps don't work.

Always serve index.html as fallback content

---

apps/api/src/api.graphql
apps/web/graphql/schema.ts
apps/web/screens/Article.tsx
apps/web/screens/queries/Article.tsx
libs/api/domains/cms/src/lib/cms.elasticsearch.service.ts
libs/api/domains/cms/src/lib/cms.resolver.ts
libs/api/domains/cms/src/lib/dto/getSingleArticle.input.ts
libs/api/domains/cms/src/lib/models/bulletListSlice.model.ts
libs/api/domains/cms/src/lib/models/embeddedVideo.model.ts
libs/api/domains/cms/src/lib/models/faqList.model.ts
libs/api/domains/cms/src/lib/models/headingSlice.model.ts
libs/api/domains/cms/src/lib/models/html.model.ts
libs/api/domains/cms/src/lib/models/image.model.ts
libs/api/domains/cms/src/lib/models/latestNewsSlice.model.ts
libs/api/domains/cms/src/lib/models/linkCardSlice.model.ts
libs/api/domains/cms/src/lib/models/logoListSlice.model.ts
libs/api/domains/cms/src/lib/models/mailingListSignupSlice.model.ts
libs/api/domains/cms/src/lib/models/pageHeaderSlice.model.ts
libs/api/domains/cms/src/lib/models/processEntry.model.ts
libs/api/domains/cms/src/lib/models/sectionWithImage.model.ts
libs/api/domains/cms/src/lib/models/slice.model.ts
libs/api/domains/cms/src/lib/models/statistics.model.ts
libs/api/domains/cms/src/lib/models/storySlice.model.ts
libs/api/domains/cms/src/lib/models/timelineSlice.model.ts
libs/api/schema/src/lib/schema.d.ts

To reduce risk of article being found in search engine and not accessible through contentful we are using the search engine to display the article. 
- Got source data from elastic instead of Contentful
- Added type resolvers to mapping logic
- Increase stability of website
- To keep search results and content in sync

Article source elasticsearch

---

libs/island-ui/core/src/lib/Link/Link.tsx

Only enabling default prefetching of JS bundles, when the target bundle is known (when the 'as' prop is set on the Link component)
Note: This (along with most Link references) will have to updated anyways after next >= 9.5.3
Changes the NextLink generic component in the ui-core (which is probably not the right place for the component in the first place)
The console spits out a bunch of 404 not founds for links defined using <Link>, but without specifying an 'as' prop (to know what kind of component it is supposed to link to)
N/A

Web: Only enable default prefetching for links with 'as'

---

libs/island-ui/core/src/lib/Swiper/Swiper.tsx

For whatever reason that I could not fix, useMeasure was not returning the width of the ref element in iOS. I replaced it with a manual check for offsetWidth on the ref.
To make Swiper work correctly for iOS (or at least some versions of iOS, was happening in Chrome/Safari).

Fix Swiper for iOS

---

apps/web/components/FrontpageTabs/FrontpageTabs.treat.ts
apps/web/components/FrontpageTabs/FrontpageTabs.tsx
apps/web/screens/Home.tsx

Better transitions without destroying and reloading animations, now they fade into each other and each animation restarts.
Also fixed padding to be correct according to design for blue search container.
Looks better according to the designer.

Tweaks to frontpage slider

---

apps/web/screens/NewsList.tsx

https://app.asana.com/0/1183498341031105/1195074272522333/f
Make it so the news list page is in english as well
So non-native speakers can understand it

Making the news list in next.js be translatable

---

apps/services/search-indexer/config/template-is.json
apps/services/search-indexer/src/migrate/dictionary.ts

Removed hypen from ES analyzers name
This was causing issues in AWS ES migrate script
Our elasticsearch dictionaries are in a separate repo, because of that changes to references of dictionary items can issues if/while the dictionaries are out of sync

Removed hypen from ES analyzers name

---

apps/web/screens/Category/Category.tsx
apps/web/screens/Category/LifeEventInCategory.tsx
apps/web/screens/LifeEvent/LifeEvent.tsx

https://app.asana.com/0/1183498341031105/1195074272522333/f
Translating more UI elements
So non-native speakers can understand
Because of contentful rate limiting, i was never able to see this change

Added translatable strings in category and life events

---

libs/api/domains/cms/src/lib/models/article.model.ts

- Added default value to subgroup
- Make site more fault tolerant

Default value to subgroup

---

.github/CODEOWNERS
libs/dokobit-signing/.eslintrc
libs/dokobit-signing/README.md
libs/dokobit-signing/jest.config.js
libs/dokobit-signing/src/index.ts
libs/dokobit-signing/src/lib/signing.service.spec.ts
libs/dokobit-signing/src/lib/signing.service.ts
libs/dokobit-signing/tsconfig.json
libs/dokobit-signing/tsconfig.lib.json
libs/dokobit-signing/tsconfig.spec.json
libs/nova-sms/README.md
libs/nova-sms/src/lib/sms.service.spec.ts
libs/nova-sms/src/lib/sms.service.ts
nx.json
package.json
tsconfig.json
workspace.json
yarn.lock

A service for signing PDF documents using Dokobit's API. The service can be extended later to include other types of documents and/or other capabilities supported by Dokobit's API.
This service will first be used to sign verdicts in detention request cases.

Adds integration with document signing service from dokobit

---

apps/web/screens/Category/Category.tsx

Always sort 'other' subgroup key to bottom.

Website/ Always sort 'other' subgroup key to bottom.

---

apps/services/search-indexer/config/template-is.json
libs/api/content-search/src/queries/search.ts

- Vastly improve the quality of search results
- Added stopwords filter for autocomplete
Removed hyphenation compound filter from content field in ES.
Because hyphenation compound filter does not produce good results against a large body of text
Prevent non relevant search results being displayed to the user

Improve the quality of search results

---

apps/api/src/api.graphql
apps/web/graphql/fragmentTypes.json
apps/web/graphql/schema.ts
apps/web/screens/queries/fragments.ts
libs/api/domains/cms/src/lib/models/asset.model.ts
libs/api/domains/cms/src/lib/models/slice.model.ts
libs/api/schema/src/lib/schema.d.ts
libs/island-ui/contentful/src/lib/AssetLink/AssetLink.tsx
libs/island-ui/contentful/src/lib/FaqList/FaqList.tsx
libs/island-ui/contentful/src/lib/richTextRendering.tsx
libs/island-ui/core/src/lib/LinkCard/LinkCard.tsx

support embedding non-image assets in contentful which was broken before
So content editors can embed e.g. pdf files in contentful editor

handle embedded non-image assets in contentful editor

---

apps/web/screens/LifeEvent/LifeEvent.tsx

#Lif Event Header Image
Life event header image should span all gridcontainer
Follow design
Before:
After:

Make life event header image span all container

---

apps/web/components/FrontpageTabs/FrontpageTabs.tsx

Links in frontpage sliders disappeared in some merge, bringing them back

Bring back page links in front page sliders

---

apps/api/src/api.graphql
apps/web/components/SearchInput/SearchInput.tsx
apps/web/graphql/schema.ts
apps/web/screens/queries/Search.tsx
libs/api/domains/cms/src/lib/generated/contentfulTypes.d.ts
libs/api/domains/cms/src/lib/models/lifeEventPage.model.ts
libs/api/schema/src/lib/schema.d.ts

Show the intro text/description if it exists, on search result cards...
It was missing.

Show intro text (description) on search results

---

libs/island-ui/core/src/lib/Input/Input.mixins.ts

The design specifies that the Input component should have the following font sizes and line heights
- On mobile 👉  font-size: 20px | line-height: 24px
- On desktop 👉  font-size: 24px | line-height: 36px
This PR implements that.
Mobile ☝️
Desktop ☝️

Change input font-size and line-height according to design

---

libs/island-ui/core/src/lib/Tag/Tag.stories.tsx
libs/island-ui/core/src/lib/Tag/Tag.treat.ts
libs/island-ui/core/src/lib/Tag/Tag.tsx

Added a rose variant to tags
This is needed in the skilavottord project

Added rose colored variant to tag

---

apps/air-discount-scheme/backend/src/app/modules/discount/discount.service.ts

Removing zero and O from discount code
Because users tend to mix them up

Ads/removing zero and O from discount code because users tend to mix them up

---

apps/web/components/Header/Header.tsx
apps/web/components/SideMenu/SideMenu.tsx

**Tighten up**
Before:
After:
**Fix mobile SideMenu colorscheme bug.**
Before:
After:

Website / Tighten SideMenu layout on mobile

---

apps/web/components/AboutLatestNews/AboutLatestNews.tsx
apps/web/components/Timeline/Timeline.tsx
apps/web/screens/AboutPage/AboutPage.tsx
libs/island-ui/core/src/lib/Timeline/Timeline.treat.ts
libs/island-ui/core/src/lib/Typography/Typography.treat.ts
libs/island-ui/core/src/lib/Typography/Typography.tsx

https://app.asana.com/0/1183498341031105/1195547281923255
- AboutPage mobile spacing tweaks
- Make Timeline escape grid on mobile 
- Give eyebrow bigger line-height on mobile.
- General improvements
Before:
After:
Before:
After:
Etc...

Website / About page spacing tweaks for mobile

---

apps/judicial-system/web/src/api/index.ts
apps/judicial-system/web/src/routes/CourtRecord/CourtRecord.tsx
apps/judicial-system/web/src/routes/DetentionRequests/DetentionRequests.spec.tsx
apps/judicial-system/web/src/routes/Judge/Overview.spec.tsx
apps/judicial-system/web/src/routes/Judge/Overview.tsx
apps/judicial-system/web/src/routes/Overview/Overview.tsx
apps/judicial-system/web/src/utils/stepHelper.ts
apps/judicial-system/web/src/utils/utils.spec.ts

https://app.asana.com/0/1189271618154957/1195315258966996
If there are custody restrictions then they should be listed in a comma separated list (B - Einangrun, E - Fjölmiðlabann). If there are no custody restrictions then "Lausagæsla" should be displayed.

Display "Lausagæsla" in overview if there are no custody restrictions

---

.github/workflows/build.yml

Currently, success is skipped if previous checks don't run. This will
allow developers to merge red pull requests.
This closes #1070

Make success check run always

---

apps/web/components/FrontpageTabs/FrontpageTabs.tsx

* Remove swiping effect in frontpage tabs
* They were causing bug in mobile, unable to click button
* Swiping was not working nicely
* Should do this more elegantly

Remove swiping and fix mobile button

---

libs/infra-express-server/src/lib/infra-express-server.ts
libs/infra-express-server/tsconfig.json
libs/message-queue/src/lib/channel.ts
libs/message-queue/tsconfig.json

Reduces work on: #253
This PR fixes typescript errors in:
* message-queue
* infra-next-server
Kill all typescript errors that come due to strict setting being enabled
So all code in monorepo can be strict

Fixing typescript errors in message-queue and infra-express-server libs

---

apps/skilavottord/web/next-modules/withHealthcheckConfig.js
apps/skilavottord/web/next.config.js
apps/skilavottord/web/pages/_app.tsx
apps/skilavottord/web/units/Healthchecks/withHealthchecks.tsx
apps/skilavottord/web/units/errors.ts

Listen to /liveness and /readiness
Because we want to conform to standards

Add readiness/liveness probes to skilavottord-web

---

apps/web/components/RichText/RichText.tsx
libs/island-ui/contentful/src/lib/ProcessEntry/ProcessEntry.tsx

Fix minor layout on articles
Videos and images were not showing in less than XL screen sizes
Process entry button section was wrapping too soon
Before: 
After:

Fix layout issues on articles

---

package.json
yarn.lock

The version of node-forge we were using was breaking our build due to a security vuln.

Resolve node-forge to 0.10.0 due to security vulnerability

---

.github/workflows/build.yml

Builds failing on master for docker-static(dummy) with the error: `Cache not found for input keys: Linux--generated-files`
So master can be green again :)

Dont use generated files when building for dummy

---

apps/judicial-system/web/src/utils/formatters.ts
apps/judicial-system/web/src/utils/utils.spec.ts

User JSON.stringify to format values
Otherwise, strings cannot include special characters in api calls

Judicial-system: Fixes formatting of values

---

apps/web/screens/Article.tsx

Fix spacing in article rich text

---

.github/workflows/build.yml

We still need the PUBLISH flag low in the stack... We should try to limit the usage of random environment variables in scripts.

Fix builds after attempted PUBLISH removal

---

libs/island-ui/core/src/lib/FormStepper/FormStepper.tsx
libs/island-ui/core/src/lib/FormStepper/FormStepperSection.tsx
libs/island-ui/core/src/lib/FormStepper/shared/SubSectionItem/SubSectionItem.tsx
libs/island-ui/core/src/lib/Typography/Typography.treat.ts

Refactor FormStepper to use new Text component.
Typography is now deprecated.

Refactor FormStepper Typography to Text

---

apps/skilavottord/web/screens/Overview/components/ActionCard/ActionCard.tsx
libs/island-ui/core/src/lib/Tooltip/Tooltip.stories.mdx
libs/island-ui/core/src/lib/Tooltip/Tooltip.treat.ts
libs/island-ui/core/src/lib/Tooltip/Tooltip.tsx
libs/shared/form-fields/src/lib/CheckboxController/CheckboxController.tsx
libs/shared/form-fields/src/lib/RadioController/RadioController.tsx

Changed the background colour of the tooltip popover from white to blue100. Also changed the default colour of the icon to dark200 and to blue400 on hover and a few other minor style changes.
According to the design, the tooltip icon should be grey by default, and blue on hover. The tooltip popover should always have a light blue background.

island-ui/Tooltip style changes

---

libs/application/templates/parental-leave/src/fields/Usage/index.tsx
libs/application/templates/parental-leave/src/fields/components/Slider/index.tsx
libs/application/ui-fields/src/lib/CheckboxFormField.tsx
libs/application/ui-fields/src/lib/DividerFormField.tsx
libs/application/ui-fields/src/lib/FileUploadFormField/index.tsx
libs/application/ui-fields/src/lib/IntroductionFormField.tsx
libs/application/ui-fields/src/lib/RadioFormField.tsx
libs/application/ui-fields/src/lib/ReviewFormField.tsx
libs/application/ui-fields/src/lib/components/Description.tsx
libs/application/ui-shell/src/components/FormMultiField.tsx
libs/application/ui-shell/src/components/Screen.tsx
libs/application/ui-shell/src/types.ts

Typography component is deprecated

Replace Typography with Text component

---

.prettierrc
nx.json
package.json
scripts/prettier-plugins/sort-projects.js
tsconfig.base.json
workspace.json

Make sure nx project lists are always sorted (in workspace.json, nx.json and tsconfig.base.json).
This is implemented as a prettier plugin, so it is applied every time we run `yarn format`. `yarn generate` also runs prettier on all added/updated files. "Just Works ™️ "
To reduce the chance of conflicts when teams are generating nx apps and libs.

Prettier plugin to sort nx project lists

---

scripts/generate-schemas.js

Make sure we always have all of the schemas. 
"Affected" logic does not make sense for code generation unless we have all of the schemas in the beginning and always run `generate` with the correct HEAD/BASE as we pull more code. This is tricky for CI. Even more so for developers.
For new developers, the `schemas` command is failing, since there is no HEAD/BASE variables, and there's no affected projects, so it doesn't generate any schemas.
This is a quick fix until most of this logic is replaced in #1225.

Generate all schemas

---

.github/workflows/push.yml

This was expected since we are now building all apps of the same type at the same time. With 20 min start time parallelism doesn't work that well for less than 10 builds. I say we increase the docker build timeout for now. And then look into faster build times now that test and lint times are down.

Give docker build more time

---

.github/workflows/push.yml

Create builds for release trains
We need them right away before pushing to them

Adding support for release-train builds (and hotfixes)

---

.github/workflows/pullrequest.yml
nx.json
workspace.json

After #1315 was merged, running lint gave the following error 
Turns out, NX requires us to create a project for the fonts, so that's what I did.
It's a bug

Added a fonts project to workspace.json and nx.json

---

scripts/ci/get-files-touched-by.sh

Fix generate schemas. Change how we detect the root folder.
It stopped working when we moved the script that detects changed files down one level.

Fix generate schemas

---

workspace.json

Add projectType field required to run nx commands.

fix: missing projectType

---

apps/judicial-system/web/src/shared-components/Modal/Modal.tsx

Remove deprecated Icon component
Icon has been deprecated

Remove deprecated Icon component

---

apps/judicial-system/web/src/routes/Judge/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepTwo/StepTwo.tsx
apps/judicial-system/web/src/routes/Prosecutor/Overview/Overview.tsx
libs/island-ui/core/src/lib/Tooltip/Tooltip.treat.ts
libs/island-ui/core/src/lib/Tooltip/Tooltip.tsx

This PR addresses two issues, one in the judicial-system project and the other in island-ui. These issues are 
- The comments to judge section needs to be separated from the request for detention.
- The tooltip becomes misplaced with a bigger font-size.
Regarding the tooltip:
When using the Text component with a variant that has a bigger font-size than the default, say h3 f.x., the tooltip is misplaced. The examples below have a font-size of 30px.
**Before**
**After**
Improvements.

Judicial-system: Added a heading for the 'comments to judge section'

---

package.json
yarn.lock

The build is failing on `yarn run security-audit` because of a vulnerability in obejct-path that is resolved in this version.
To fix the build

Resolve object-path to v.0.11.5

---

libs/island-ui/core/src/lib/Text/Text.treat.ts

Increase default text size to 16 from 15.
A designer noticed it was 15 but should be 16.

Change default text font size from 15 to 16 in sm breakpoint

---

apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepOne/StepOne.spec.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepOne/StepOne.tsx
apps/judicial-system/web/src/types.ts

https://app.asana.com/0/1197628843274291/1197773320394651
See ☝️
If the name of the accused is entered first, then police case number and national id, the name would not be saved with the case.

Judicial-system/Save case fix

---

apps/web/components/Section/Section.tsx

Don't use background bleed styles if bleed amount is not specified. Styles were being used and had 'undefinedpx' as values.

Don't use background bleed styles if bleed amount is not specified

---

libs/island-ui/core/src/lib/Text/Text.tsx

Breadcrumbs Next.js links not working on production.
Seemed to work locally and serving production locally but not on live production web for some reason. I have a theory it is because of the `child?.type?.name === 'Link'` check. It is not really needed anyway so removing it and hoping it fixes the issue.

Breadcrumbs/Text next.js links (build) fix

---

libs/api/domains/cms/src/lib/models/slice.model.ts
libs/api/domains/cms/src/lib/search/importers/aboutPage.service.ts
libs/api/domains/cms/src/lib/search/importers/article.service.ts
libs/api/domains/cms/src/lib/search/importers/articleCategory.service.ts
libs/api/domains/cms/src/lib/search/importers/lifeEventsPage.service.ts
libs/api/domains/cms/src/lib/search/importers/news.service.ts

This will patch empty imports, this patch will probably be reworked when we iterate migration
https://app.asana.com/0/1183498341031105/1198954651970197
- Make importer not import entries we consider empty
- Change log level from error to warn
- Changed error logging messages
- Importer is importing empty entries due to them being published in another language
- Error level in logs is considered critical failure and sets of alarms
- Logging the whole error object is causing noise in logs

Skip empty types on import

---

libs/api/domains/cms/src/lib/search/importers/article.service.ts

Quick fix for a minor bug: Articles are not being mapped before checking for title.

Fix articles are not being mapped

---

apps/service-portal/src/components/UserMenu/UserMenu.tsx
libs/service-portal/applications/src/index.ts
libs/service-portal/documents/src/screens/Overview/Overview.tsx
libs/service-portal/documents/src/widgets/documentList.tsx

Effort to fix type errors in Fuse.js for service portal documents
Remove Fuse as a dependancy from documents for now
Version mismatch has been causing builds to break on type errors randomly
@storybook/ui@6.0.26 depends on fuse.js "^3.6.1"
The currently installed version of fuse is locked as "fuse.js": "6.4.2"
Building the project on other branches has been causing a type error in documents Overview.tsx where fuse.search is interpreted as returning Document[] instead of FuseResult<Document[]>
**This needs to be addressed later**

Service Portal Documents Fuse Type Fix

---

apps/judicial-system/web/src/routes/DetentionRequests/DetentionRequests.spec.tsx
apps/judicial-system/web/src/routes/DetentionRequests/DetentionRequests.tsx
apps/judicial-system/web/src/utils/formatters.ts
apps/judicial-system/web/src/utils/utils.spec.ts

https://app.asana.com/0/322488613152836/1189677453581096
- Remove time from Gæsluvarðhald til section of detention request table
- Rename the table head column from "Gæsluvarðhaldstími" to "Gæsluvarðhald til"
- Prevent "Opna kröfu" button from wrapping
- Make sure all national ids have a hyphen.
The table does now scale well, even on large screens.

Judicial-system/Detention request table scales a little better now

---

libs/island-ui/core/src/lib/Input/Input.mixins.ts

Textarea font weight set to light.
It's according to design

island-ui/Textarea font weight set to light

---

libs/application/templates/parental-leave/src/fields/PeriodsSectionImage/PeriodsSectionImage.tsx
libs/application/ui-shell/src/components/ScreenFooter.tsx

Small margin adjustment on form footer
Set image size so match design for now.
- [ x] I have performed a self-review of my own code

Parental leave cosmetic fixes

---

libs/api/domains/cms/src/lib/search/cmsSync.service.ts

https://app.asana.com/0/1183498341031105/1199101557028143
Made folder hash algorithm not calculate hash for node_modules
node_modules calculating a hash for node_modlues depletes the container resources causing it to crash

Fix for hash memory problem

---

libs/api/domains/cms/src/lib/search/cmsSync.service.ts
libs/api/domains/cms/src/lib/search/contentful.service.ts

Changed warning to warn
warning is not a valid function on logger to log warnings

Search indexer fixed warning error

---

SCHEMAS.md
apps/air-discount-scheme/backend/src/app/modules/cache/cache.module.ts
apps/application-system/api/docker-compose.base.yml
apps/application-system/api/docker-compose.dev.yml
apps/application-system/api/src/app/modules/application/application.module.ts
apps/application-system/api/src/environments/environment.prod.ts
apps/application-system/api/src/environments/environment.ts
apps/application-system/api/src/environments/index.ts
libs/cache/src/lib/cache.ts

Use a redis cluster in the application system api project.
Because our AWS environment uses a redis cluster but not a redis instance.

Using redis cluster instead of redis instance in applicaiton system api

---

apps/skilavottord/web/screens/DeregisterVehicle/Confirm/Confirm.tsx

- Changed requestType to `deregistered` not `deregister`
- The correct type is `deregistered`

Changed requestType to deregistered

---

apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepOne/StepOne.spec.tsx
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepOne/StepOne.treat.ts
apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepOne/StepOne.tsx
apps/judicial-system/web/src/utils/mocks.ts

https://app.asana.com/0/1197628843274291/1197851580977337
Added radio buttons for gender on the first screen of the prosecutor flow.
Because when we start sending notifications to prisons, they want to know the gender of people being sent to them.

Judicial-system/Added gender to step one screen

---

libs/island-ui/core/src/lib/FormStepper/SectionNumber/SectionNumber.treat.ts
libs/island-ui/core/src/lib/FormStepper/SectionNumber/SectionNumber.tsx
libs/island-ui/core/src/lib/IconRC/iconMap.ts
libs/island-ui/core/src/lib/IconRC/icons/Checkmark.tsx
libs/island-ui/core/src/lib/IconRC/icons/Ellipse.tsx
libs/island-ui/core/src/lib/IconRC/icons/EllipseOutline.tsx

Update the FormStepper to use the newer Icon component.
The old Icon component is deprecated.

Replace Icon with IconRC

---

apps/application-system/api/src/app/modules/application/application.module.ts

Only create a one redis connection not three as it was before.
I recently introduced this bug in #1787 
Because one is quite enough

Prevent multiple redis connections in application system

---

libs/cache/src/lib/cache.ts

Increasing the refresh slots timeout value
Because refresh slots in application-system have been timing out

Adding refresh-slots-timeout to redis config

---

libs/island-ui/core/src/lib/Button/Button.treat.ts
libs/island-ui/core/src/lib/Button/Button.tsx

Add loading state to button
improve icon sizes and alignments
use min height for some cases to ensure consistent button heights
some ex.

island-ui / Button loading, and icon improvements

---

apps/web/screens/Adgerdir/Article.tsx

Add button to the bottom of adgerdir article page
Fix bug with button that has no buttontext

Adgerdir add button to bottom of article

---

libs/service-portal/documents/src/components/DocumentCard/DocumentCard.tsx

Live data shows inconsistency in casing, some documents would not be treated as pdf documents because the filetype did not match.

hotfix: Live data shows tha fileType can be both upper- and lowercase

---

libs/island-ui/core/src/lib/Button/Button.tsx

Button add missing selector for color scheme
Button selector for color scheme was accidentally removed

island-ui / Button add missing selector for color scheme

---

libs/island-ui/core/src/lib/Button/Button.treat.ts
libs/island-ui/core/src/lib/DatePicker/DatePicker.tsx
libs/island-ui/core/src/lib/Grid/GridRow/GridRow.treat.ts
libs/island-ui/core/src/lib/Header/Header.treat.ts
libs/island-ui/core/src/lib/InputFileUpload/InputFileUpload.tsx
libs/island-ui/core/src/lib/NewsletterSignup/NewsletterSignup.tsx
libs/island-ui/core/src/lib/ProfileCard/ProfileCard.treat.ts
libs/island-ui/core/src/lib/Select/Select.tsx
libs/island-ui/core/src/lib/Swiper/Swiper.treat.ts
libs/island-ui/core/src/lib/Toast/Toast.treat.ts
libs/island-ui/core/tsconfig.json
libs/island-ui/core/tsconfig.lib.json

Remove "strict": false from tsconfig in island-ui core. Fix some of the warnings, still multiple left that can be fixed later.

Island-ui-core is now typescript strict.

---

apps/skilavottord/web/screens/DeregisterVehicle/Confirm/Confirm.tsx

- Because the error from backend is returned differently, this fix will catch the error accordingly
- With this fix the app will be able to catch the error, otherwise it will pass as successful in the UI

Skilavottord / Fix error handling in deregister vehicle

---

apps/judicial-system/web/src/utils/utils.spec.ts
apps/judicial-system/web/src/utils/validate.ts

The email-format regex had a unnecessary escape character that caused a lint warning. I'm removing it.
Dev experience

Judicial-system/Fix lint warning

---

apps/skilavottord/web/screens/Confirm/Confirm.tsx
apps/skilavottord/web/screens/Overview/components/ActionCard/ActionCard.tsx

This fixes the displaying of a car being co-owned to look better in tablet view and smaller browser windows.
This fixes an issue that squeezed the text between button and car registration number
Result:

Skilavottord - Fix tablet view on action card

---

apps/web/components/FrontpageTabs/FrontpageTabs.tsx
apps/web/components/FrontpageTabs/illustrations/Illustration.tsx

- Change slide content's spacing from padding to margin since it was causing the wrong height to be reported.
- Preload one extra illustration to remove flicker.
- Display the illustrations on `md` breakpoint as well.
-
-

Website/ Frontpage illustration tweaks

---

apps/web/components/Adgerdir/AdgerdirArticles/AdgerdirArticles.tsx

- Selected filters now narrow cards down better.
- Filters that aren't used on any page are now hidden.

Change filters on covid page

---

libs/island-ui/core/src/lib/DatePicker/DatePicker.treat.ts

ios adds padding to select which causes the text to overflow

island-ui / datepicker remove default padding from ios

---

apps/judicial-system/api/src/types/entropy-string.d.ts
apps/judicial-system/api/tsconfig.json

Extends the typescript declaration for Entropy Class to get rid of "any" inference.
Without this, building GraphQL schemas for the judicial system api fails.

Judicial System: Improves typescript declaration for entropy class

---

apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepOne/StepOne.spec.tsx

https://islandis.slack.com/archives/C01BQD2F1AP/p1606299160058700
See ☝️
Tomorrow is November 26th. Since the datepicker shows the trail of last month the number 26 appears twice in the date picker. We were choosing tomorrow in this test and it chose the "wrong" 26, i.e. October 26th instead of November 26th 🙈 The 15th will never appear twice in the date picker.

Judicial-system/Choose 15th instead of tomorrow in stepone test

---

libs/api-catalogue/services/src/lib/restmetadata.service.ts

Updating the way we create IDs for services from xroad, so the URLs stay the same after night schedule run
Create a single reusable id for each service
So that URLs can be reused

updating the method used to create ids for services

---

libs/island-ui/core/src/lib/DialogPrompt/DialogPrompt.treat.ts
libs/island-ui/core/src/lib/DialogPrompt/DialogPrompt.tsx

In mobile the dialog looked like it was escaping the screen to the right
(see screenshots below)
Before:
After:

Fix modal dialog margins

---

apps/judicial-system/web/src/routes/Judge/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Prosecutor/Overview/Overview.tsx
apps/judicial-system/web/src/shared-components/PoliceRequestAccordionItem/PoliceRequestAccordionItem.tsx
apps/judicial-system/web/src/utils/stepHelper.tsx
apps/judicial-system/web/src/utils/utils.spec.tsx

https://app.asana.com/0/inbox/322488613152834/1199370521770163/1199370521770162
A judge can see drafts now when the first notification has been sent. This means that a judge can see a case where the requestedCustodyEnd date has not been set and would see a lot of undefined values 👇
If this ever happens, we now display a custom message instead of undefined values
It's a bug

Judicial-system/Handle undefined values in police demands

---

libs/island-ui/core/src/lib/Tag/Tag.stories.tsx
libs/island-ui/core/src/lib/Tag/Tag.treat.ts

Added a rose variant to the outlined tag.
In Skilavottord project, the design is to use a rose colored tag so I hope it's ok to add this variant to the lib as well.

Island-ui: Rose variant for outlined tag

---

apps/judicial-system/api/src/environments/environment.prod.ts

HOSTNAMEs are unique and ideal for distinguishing between pods.
We need to use separate streams for pods to avoid conflicts.

Judicial System: Uses hostname in audit trail stream name

---

apps/judicial-system/api/src/environments/environment.prod.ts

Treats boolean environment variables as strings
Otherwise, 'false' is interpreted as true.

Judicial System: Boolean env handling

---

libs/api-catalogue/services/src/lib/provider.service.spec.ts
libs/api-catalogue/services/src/lib/provider.service.ts
libs/api-catalogue/services/src/lib/restmetadata.service.ts
libs/api-catalogue/types/src/lib/provider.model.ts

Updating the service registration to use the org name available from x-road
So that the org name is tied to x-road and prevent users from setting multiple org names by accident

Update providers to include the org name from xroad

---

libs/auth-api-lib/src/lib/auth/current-user.decorator.ts
libs/auth-api-lib/src/lib/auth/jwt.strategy.ts
libs/auth-api-lib/src/lib/auth/user.ts

Make access token available in the User object returned by the @CurrentUser decorator.
So that GraphQL resolvers can use it for authorization when they call REST APIs.
- [x ] I have performed a self-review of my own code
- [ x] My changes generate no new warnings
- [x ] Formatting passes locally with my changes
- [ x] I have rebased against main before asking for a review

Added accessToken property to User.

---

apps/web/screens/Home.tsx

(cherry picked from commit f97d4f513f65e7f5800e2142cead6ff225554ac2)
- Fix for tabs under search input on frontpage
- Currently we are not able to link to nested pages such as `/covid-adgerdir`

Use new routes for tags and next links (#2082)

---

README.md

Make the design system easier to find by linking to it from the root README

docs/ Link to UI library from the main README

---

SUMMARY.md
libs/island-ui/README.md

docs: rename island ui lib

---

apps/services/search-indexer/config/kibana/dashboard-articles.json
apps/services/search-indexer/config/kibana/index-pattern-island.json
apps/services/search-indexer/config/kibana/visualization-articles-contain-multiple-process-entries.json
apps/services/search-indexer/config/kibana/visualization-articles-with-process-entry.json
apps/services/search-indexer/config/template-en.json
apps/services/search-indexer/config/template-is.json
libs/api/domains/cms/src/lib/search/importers/aboutPage.service.ts
libs/api/domains/cms/src/lib/search/importers/adgerdirPage.ts
libs/api/domains/cms/src/lib/search/importers/article.service.ts
libs/api/domains/cms/src/lib/search/importers/utils.ts
libs/content-search-indexer/types/src/index.ts

Datatable that shows all articles that have more than 1 process entry

Showing articles that have more than one process entry in a data table

---

apps/web/screens/AboutSubPage/AboutSubPage.tsx

https://app.asana.com/0/1199123945323117/1199587953442157
- Remove everything after the symbol "?" in as path
- Get query params are causing errors when getting page content

Fixed get param causing error

---

apps/web/screens/Search/Search.tsx

https://app.asana.com/0/1199123945323117/1199585689963197
- Removed Covid operations from other search results box
- Made covid operations appear in search results
- Added Covid operations tag to covid operations search results
- Covid operations were to hidden in other search results, better UX

Covid operations in search results

---

libs/content-search-toolkit/src/services/elastic.service.ts

https://app.asana.com/0/1199123945323117/1199597433453861
Checking for `AWS_SECRET_ACCESS_KEY` causes issues when going from `ES proxy` to `ES locally`.
Just checking for `AWS_WEB_IDENTITY_TOKEN_FILE ` should suffice 
- Changed AWS check so it does not conflict with proxy
- Previous check fails in our environments

Changed aws check

---

apps/web/components/FrontpageTabs/FrontpageTabs.tsx

https://app.asana.com/0/1199123945323117/1199600556560461
- Made frontpage slider correctly resolve covid frontpage url
- Currently url is resolved to frontpage

Made frontpage slider resolve covid page url correctly

---

libs/service-portal/settings/src/components/Forms/LanguageForm.tsx
libs/service-portal/settings/src/components/UserOnboardingModal/Steps/LanguageStep.tsx

Switch the current language as soon as the user selects it in the onboarding modal
Improve onboarding UX

Service Portal - Set Onboarding Language on Change

---

libs/application/templates/parental-leave/src/fields/Review/index.tsx

Set the accordion to be expanded by default, and the user will collapse the items as they review them.
Requested
1. Add optional buttons ("collapse/expand all") - needs design.

Parental leave - expand review accordion by default

---

libs/api/domains/document-provider/src/lib/document-provider.service.ts

Use mock data for document-provider api
So frontend developers can test the application without create provider on test environment on the old mailbox

use mock data

---

apps/web/screens/AboutPage/AboutPage.tsx

Remove page navigation from about page navbar

Remove about page jumper from navbar

---

libs/island-ui/core/src/lib/Accordion/Accordion.stories.mdx
libs/island-ui/core/src/lib/Accordion/AccordionItem/AccordionItem.tsx

Adding `labelColor` prop so the color of the label on `AccordionItem` can be controlled.
The `Filter` component is using this to change the color of the label to blue when there is 
a selected value for a specific group.

Adding labelColor to control the color for the AccordionItem

---

apps/web/screens/ApiCatalogue/ApiCatalogue.tsx
apps/web/screens/ServiceDetails/ServiceDetails.tsx

Adding the Navigation component to two pages in the Api Catalogue 
Design Desktop:
- *Service list* : https://www.figma.com/file/IQ006wy2vR1jIWJ6Uqwis5/Viskuausan?node-id=570%3A1713
- *Service details* : https://www.figma.com/file/IQ006wy2vR1jIWJ6Uqwis5/Viskuausan?node-id=361%3A1
Design Mobile:
- *Service list* : https://www.figma.com/file/IQ006wy2vR1jIWJ6Uqwis5/Viskuausan?node-id=364%3A36
- *Service details* : https://www.figma.com/file/IQ006wy2vR1jIWJ6Uqwis5/Viskuausan?node-id=500%3A1692
Adding navigation to the upper left corner on the two pages (screens) ApiCatalogue and ServiceDetails
For easy navigation for user
**Desktop**
**Mobile**
**Desktop**
**Mobile**

Adding Navigation to ApiCatalogue

---

.github/CODEOWNERS

(cherry picked from commit debbdb10e0116a5ac5b9e8094265dbaadf25e709)

Made Kosmos & kaos codeowner for gjafakort (#2357)

---

apps/web/components/FrontpageTabs/FrontpageTabs.tsx

Remove hardcoded string and use translated stiring insteda

Use global namespace in frontpage tabs

---

.github/workflows/push.yml

Make sure we fail the workflow if we don't want to run it so the build doesn't count as a good build

Skip failure notification if we're skipping workflow

---

apps/web/components/ServiceList/ServiceList.tsx

Enabling truncate flag on CategoryCard used in the ServiceList.
For some screen widths the service title can be come to long for the card so we need to truncate it.

Enabling truncate flag on CategoryCard use in ServiceList

---

apps/web/screens/Article.tsx

Optional title will always have empty string as default value so we use logical OR instead of nullish coalescing operator so empty strings will return false

island.is / Navigation title

---

apps/judicial-system/web/src/routes/Shared/DetentionRequests/DetentionRequests.treat.ts
apps/judicial-system/web/src/routes/Shared/DetentionRequests/DetentionRequests.tsx
libs/island-ui/core/src/lib/IconRC/iconMap.ts
libs/island-ui/core/src/lib/IconRC/icons/CaretUp.tsx
libs/island-ui/core/src/lib/IconRC/icons/CaretUpOutline.tsx

https://app.asana.com/0/1199153462262248/1199597549258731
It's unclear that users can sort the detention request table because the sort arrows are currently not visible by default. In this PR, we make the arrows visible by default, although slightly transparent to indicate that the table can be sorted.
UX
https://user-images.githubusercontent.com/3789875/103631284-b0edbd00-4f3a-11eb-833f-40049adeaf89.mov

Judicial-system/Sort arrow tweeks

---

libs/island-ui/core/src/lib/Button/Button.stories.tsx
libs/island-ui/core/src/lib/Button/Button.tsx

island-ui/ Allow 'title' prop on Button

---

apps/web/components/OpenApiDocumentation/OpenApiDocumentation.tsx

Links to a service with two versions
dev: https://beta.dev01.devland.is/throun/vefthjonustur/vorulisti/SVMtREVWX0NPTV8xMDAwMl9Pcmlnby1Qcm90ZWN0ZWRfcGV0c3RvcmU
local: http://localhost:4200/throun/vefthjonustur/vorulisti/SVMtREVWX0NPTV8xMDAwMl9Pcmlnby1Qcm90ZWN0ZWRfcGV0c3RvcmU
When there are two or more versions of a service, lower select options are un-clickable (fall behind the redoc element).  So we will need to set it's z-index to 0 after it has been created.
Because redoc is an external javascript module

nLoad setting redoc div z-index to 0 -attempt2

---

apps/web/components/OpenApiDocumentation/OpenApiDocumentation.tsx

The fix did not work after merge, so removing it again
The redoc reqest sample window (gray one to the right) dissapears, so removing the fix
I was trying to fix that the select options are not clickable when versions are more than one
You can see the problem in this pull-reqest: https://github.com/island-is/island.is/pull/2393

Removing version select options fix

---

apps/web/components/OpenApiView/OpenApiView.treat.ts
apps/web/components/OpenApiView/OpenApiView.tsx

Links to a service with two versions
dev: https://beta.dev01.devland.is/throun/vefthjonustur/vorulisti/SVMtREVWX0NPTV8xMDAwMl9Pcmlnby1Qcm90ZWN0ZWRfcGV0c3RvcmU
local: http://localhost:4200/throun/vefthjonustur/vorulisti/SVMtREVWX0NPTV8xMDAwMl9Pcmlnby1Qcm90ZWN0ZWRfcGV0c3RvcmU
When there are two or more versions of a service, lower select options are un-clickable (fall behind the redoc element).  So we will need to set the z-index to 2  on the column containing the select component because one of the redoc items is set to z-index: 1
Because redoc is an external javascript module
The problem being fixed:

Service version options in front of redoc

---

package.json
yarn.lock

Upgrading `quicktype` to version 15.0.258
`quicktype` depends on `urijs` which has vulnerability which has been fixed 
and `quicktype` has upgraded to safe version (v 1.19.4 of `urijs`)

Upgrade quicktype due to vulnerability.

---

.github/CODEOWNERS
.github/workflows/codeowners.yml

Kolibri now has two teams. These are the OGs.

Update codeowners to reflect team name change

---

libs/application/templates/health-insurance/src/forms/HealthInsuranceForm.ts
libs/application/templates/health-insurance/src/forms/messages.ts
libs/application/templates/health-insurance/src/lib/HealthInsuranceTemplate.ts

- Confirmation of residency page for applicants moving from Greenland or Faroe Islands. 
- Also added UserProfile provider for prefilled form fields under Contact information section
If users move from Greenland or Faroe Islands the user needs to upload additional documents. This page allows the user to provide the details.

Confirmation of Residency page

---

apps/web/components/OpenApiDocumentation/OpenApiDocumentation.tsx
apps/web/components/OpenApiView/OpenApiView.treat.ts
apps/web/components/OpenApiView/OpenApiView.tsx
apps/web/components/ServiceInformation/ServiceInformation.tsx
apps/web/screens/ServiceDetails/ServiceDetails.tsx

Needed to move fetching of links from component OpenApiDocumentation to OpenApiView
Displaying links in the header
Change of design.
see: https://www.figma.com/file/IQ006wy2vR1jIWJ6Uqwis5/Viskuausan
No current service in X-Road has these links yet, but if you want to view them you can hardcode them by change the **useEffect** hook like so
```
useEffect(() => {
const onCompleted = (data) => {
//const converted = YamlParser.safeLoad(data.getOpenApi.spec)
let converted = YamlParser.safeLoad(data.getOpenApi.spec) as any
converted.info['x-links'] = {
documentation:
'https://github.com/guttih/voffcon/blob/master/README.md',
responsibleParty: 'https://guttih.com/contact',
bugReport:
'https://github.com/guttih/voffcon/issues/new?assignees=&labels=&template=bug_report.md&title=',
featureRequest: …
```

moving OpenApi links to OpenApiView

---

libs/application/templates/health-insurance/src/forms/MissingInfoForm.ts
libs/application/templates/health-insurance/src/lib/HealthInsuranceTemplate.ts

- Changed so that the checkbox is not filled upon arrival at missing information page

Checkbox on missing information page

---

apps/web/screens/Article.tsx
libs/island-ui/core/src/lib/Tag/Tag.tsx

If article is connected to a organization we display tag in mobile
Based on design

Island.is / Organization mobile tag

---

libs/island-ui/contentful/src/lib/RichTextRC/RichText.treat.ts
libs/island-ui/contentful/src/lib/RichTextRC/defaultRenderNode.tsx

Consistent spacing around lists inside rich text, moving form mobile paragraph style to fixed 16px
Based on design

Island.is / rich text list spacing

---

libs/application/core/src/lib/fieldBuilders.ts
libs/application/core/src/types/Fields.ts
libs/application/ui-fields/src/lib/FileUploadFormField/index.tsx

Add missing props to FileUploadFormField:
1. `maxSize`
2. Forward `uploadMultiple` and `uploadAccept` to the core component in the field.
Ex: 
```
buildFileUploadField({
id: 'uploadFiles',
title: 'Upload files',
introduction: 'Please upload your important files (PDF, Text)',
uploadDescription: 'Documents accepted with extension: .pdf, .docx. With a maximum size of 1kb.',
maxSize: 1000,
}),
```

Add props to FileUploadFormField

---

apps/judicial-system/web/src/routes/Shared/DetentionRequests/DetentionRequests.treat.ts
apps/judicial-system/web/src/routes/Shared/DetentionRequests/DetentionRequests.tsx

https://app.asana.com/0/1199153462262248/1199716090325395
Make name column in detention requests table bigger so that longer names don't wrap. Really long names get cut off with an "..." at the end.
Better UI

Judicial-system/Make name column in detention requests table bigger

---

apps/services/user-profile/src/app/user-profile/verification.service.ts

Reset emails were ending up in the promotions tab in Gmail.  By removing the email from the body it delivers in the main gmail tab

Service portal: Prevent emails from landing in the promotions tab

---

libs/shared/babel/README.md
scripts/ci/Dockerfile

Make sure production builds use production babel configuration.
Also, add more documentation about deep imports.
To pick up our production optimizations in `libs/shared/babel/web`, which configures `babel-plugin-transform-imports` with `exportFinder`.

Set NODE_ENV when building production builds

---

libs/island-ui/core/src/lib/Footer/Footer.tsx

Add hyphen to footer top links
Some links have a long name that breaks the layout

island-ui / Footer top links hyphen

---

apps/judicial-system/web/src/routes/Prosecutor/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
apps/judicial-system/web/src/shared-components/InfoCard/InfoCard.tsx

https://app.asana.com/0/1199153462262248/1199716090325397
Name and national id are now both bold and national id has a hyphen and "kt." preceding it. Removed gender.
Better readability.

Judicial-system/Format nationalID and remove gender from info card

---

libs/application/templates/driving-license/src/forms/application.tsx

After changing the national registry api to accept null on address fields it will break if we don't have optional chaining

Add optional chaining to possibly null field

---

libs/island-ui/core/package.json

Fix global styles in legacy projects by marking island-ui/core/src/index.ts as having sideEffects (global styles).
This is a regression from the performance work in #2530. New projects should start using `shared/babel/web` and explicitly import and run `globalStyles()`.

Fix global styles in island-ui

---

apps/web/components/Sticky/Sticky.tsx
apps/web/screens/Article.tsx
apps/web/screens/Category/Category.tsx

Reusing the Sticky component for article and category sidebars. Also fixed where it did not update correctly on resize.
Detects if the screen is not tall enough for the whole sidebar to be visible and if so it will remove position = sticky.
On smaller screens (or lower resolutions) the bottom half of the sidebar (if it was a tall one) was not visible until you scrolled all the way down.

Use the dynamic sticky for left sidebar

---

scripts/build-graphql-schema.ts

In `build-graphql-schema` the [yargs.argv._](https://github.com/yargs/yargs/blob/169b815df7ae190965f04030f28adc3ab92bb4b5/docs/api.md/#argv) 
parameters can be both string and numbers.
But `require( )` only accepts strings, so using `yargs.string(key)` to make them only strings.
Fix build error in `build-graphql-schema`
To enable generation of graphql schemas.
Script failing for the command:  `yarn nx run judicial-system-api:schemas/build-graphql-schema --skip-nx-cache
`
with the following stack trace:
```
> nx run judicial-system-api:schemas/build-graphql-schema
$ cross-env ts-node -r tsconfig-paths/register -O '{\"module\":\"commonjs\",\"esModuleInterop\":true}' -P apps/judicial-system/api/tsconfig.json scripts/build-graphql-schema.ts apps/judicial-system/api/src/app/app.module …
```

Fix build issue in build-graphql-schema

---

.github/CODEOWNERS

API catalogue was removed in #2498 but not from [codeowners](https://github.com/island-is/island.is/blob/main/.github/CODEOWNERS#L79).
This breaks all PRs since linting of codeowners complains about it not existing in the project anymore.

Remove api-catalogue from codeowners

---

libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts

Show the "Share info with other parent" section only if they chose confirm the other parent.

Parental Leave - Share info with other parent as conditional

---

apps/web/screens/Home.tsx
apps/web/screens/NewsItem.tsx

Remove sleeve all together from home screen
Fix tag link in newsitem breadcrumbs

Remove sleeve from home screen and fix breadcrumb tag on news item

---

apps/judicial-system/web/src/utils/utils.spec.tsx

https://app.asana.com/0/1199153462262248/1199683723918407
Refactor utils test so that they use `screen.getByText` instead of `const { getByText } = ...`.
According to [this blog post](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#not-using-screen), this is best practice. I'm also hoping it fixes broken tests on another PR #2570.

Judicial-system/Refactor util tests

---

libs/island-ui/theme/src/lib/theme.ts

Add paragraph spacings to theme, as defined in figma
Figma has defined paragraph spacings for breaks in text that are not defined in our spacing scheme

island-ui / Paragraph spacings

---

libs/island-ui/core/src/lib/Accordion/Accordion.stories.mdx
libs/island-ui/core/src/lib/ActionCard/ActionCard.stories.tsx
libs/island-ui/core/src/lib/AlertBanner/AlertBanner.stories.tsx
libs/island-ui/core/src/lib/AlertMessage/AlertMessage.stories.tsx
libs/island-ui/core/src/lib/AsyncSearch/AsyncSearch.stories.tsx
libs/island-ui/core/src/lib/Breadcrumbs/Breadcrumbs.stories.tsx
libs/island-ui/core/src/lib/Button/Button.stories.tsx
libs/island-ui/core/src/lib/CategoryCard/CategoryCard.stories.tsx
libs/island-ui/core/src/lib/Checkbox/Checkbox.stories.tsx
libs/island-ui/core/src/lib/DatePicker/DatePicker.stories.tsx
libs/island-ui/core/src/lib/DialogPrompt/DialogPrompt.stories.tsx
libs/island-ui/core/src/lib/Footer/Footer.stories.tsx
libs/island-ui/core/src/lib/FormStepper/FormStepper.stories.mdx
libs/island-ui/core/src/lib/Input/Input.stories.tsx
libs/island-ui/core/src/lib/InputFileUpload/InputFileUpload.stories.tsx
libs/island-ui/core/src/lib/Link/Link.stories.mdx
libs/island-ui/core/src/lib/Menu/Menu.stories.tsx
libs/island-ui/core/src/lib/Navigation/Navigation.stories.tsx
libs/island-ui/core/src/lib/Pagination/Pagination.stories.tsx
libs/island-ui/core/src/lib/RadioButton/RadioButton.stories.tsx
libs/island-ui/core/src/lib/Select/Select.stories.tsx
libs/island-ui/core/src/lib/Tabs/Tabs.stories.tsx
libs/island-ui/core/src/lib/Tag/Tag.stories.tsx
libs/island-ui/core/src/lib/Toast/Toast.stories.tsx
libs/island-ui/core/src/lib/Tooltip/Tooltip.stories.mdx
libs/island-ui/core/src/utils/withFigma.tsx

Current Figma links are private. There's no way to directly link to pages using Figma communities. This PR updates the stories to point to our community space.

island-ui / Update Figma links to point to our community space.

---

libs/api/domains/cms/src/lib/cms.contentful.service.ts

Some of the functions in the contentful service declared a parameter object whereas other did not.
I standardized the contentful service to parameter object declaration instead of constructing it in the function call itself
consistency

Standardized the parameter format in the contentful service

---

libs/api/domains/cms/src/lib/cms.contentful.service.ts

Changed variable names to be consistent

Standardized result variables: 'r' -> 'result'

---

libs/api/domains/cms/src/lib/dto/getSingleNews.input.ts

Added a default value to the DTO for SingleNews
Defend against errors
lang is an optional input in the input DTO but it is passed directly down to getElasticsearchIndex() which doesn't have precautions against that

Added a default value to the DTO for SingleNews

---

apps/judicial-system/web/src/routes/Shared/DetentionRequests/DetentionRequests.spec.tsx
apps/judicial-system/web/src/routes/Shared/DetentionRequests/DetentionRequests.treat.ts
apps/judicial-system/web/src/routes/Shared/DetentionRequests/DetentionRequests.tsx
apps/judicial-system/web/src/utils/mutations.ts

https://app.asana.com/0/1199153462262248/1199612302735343
Add text that indicates whether or not a case is an extension in the list of cases.
Otherwise, two rows look exactly alike in the table of requests when one is the original request and the other is an extension.

Judicial-system/Extension indicator

---

libs/application/templates/health-insurance/src/fields/ChildrenInfoMessage/ChildrenInfoMessage.treat.ts
libs/application/templates/health-insurance/src/fields/Review/ContactInfo.tsx
libs/application/templates/health-insurance/src/fields/Review/StatusAndChildren.tsx

- Changing the margin top of the ChildrenInfoMessage component to look like design
- Removing the nationality field from the review page

InfoMessage margin top fix, removing nationality field from review page

---

libs/island-ui/core/.eslintrc
libs/island-ui/core/src/lib/Checkbox/Checkbox.tsx
libs/island-ui/core/src/lib/RadioButton/RadioButton.tsx

- Fix absolute imports within `island-ui/core` to be relative
- Force this convention by adding an eslint rule
Absolute imports are breaking CI in other PRs

Fix: Refactor absolute imports to be relative inside island-ui/core

---

libs/api/domains/cms/src/lib/environments/environment.ts

Grouped menu is not correctly updated when a nested menu updates
- Added menu as a nested content type
- This will trigger an update on grouped menu on menu updates

Added menu as nested for grouped menu

---

libs/island-ui/core/src/lib/Button/Button.treat.ts
libs/island-ui/core/src/lib/Button/Button.tsx

It might make more sense to make all buttons inline-flex. But since we don't want to make a global change that might have some unseen consequences and buttons are working in general we will add the option for inline buttons
Inline buttons will listen to text style properties like `align-text`, in some cases that will make them easier handle and it will be closer to the default button display `inline-block` property

Island-ui / Add inline to button

---

apps/judicial-system/web/src/shared-components/CourtRecordAccordionItem/CourtRecordAccordionItem.tsx

https://app.asana.com/0/322488613152836/1199925504424433
Accused plea announcement should not be bold in court record accordion item
Better UI

Judicial-system/Accused plea announcement should not be bold in court record accordion item

---

libs/vmst-client/src/lib/vmst-client.module.ts

Temporarily logging all network activity that goes through the VMST client to find the cause of X-Road requests not getting through.
To be able to make X-Road requests to VMST

Temporarily log all network activity in the VMST client

---

libs/api/domains/directorate-of-labour/src/lib/directorate-of-labour.module.ts
libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.module.ts
libs/vmst-client/src/lib/vmst-client.module.ts

XROAD_CLIENT_ID can now be used by everyone making requests on behalf of digital iceland so no need to have it namespaced to VMST
So VMST client requests work since they are now missing the client id header

Correctly reference x road client id

---

libs/island-ui/contentful/src/lib/RichTextRC/RichText.tsx

Rich text currently does not render newlines within paragraphs. This PR makes the renderer replace `\n` with `<br>`.
This hello world text block would previously have rendered in a single line.
- [   I have added tests that prove my fix is effective or that my feature works

Make rich text render newlines within paragraphs

---

libs/api/domains/cms/src/lib/environments/environment.ts

This makes articles in ES update when a subgroup that is referenced in them changes. 
When a subgroup is renamed the change should appear on the website without requiring a full resync.

Add articleSubgroup to nested content types

---

workspace.json

- Allow Docker to find the required outputPath

fix: missing outputPath for Dockerfile

---

handbook/technical-overview/devops/next-server.md
workspace.json

Configure outputPath on next build targets.
To fix the CI build, which depends on this property being around.

Add outputPath to next build targets

---

libs/island-ui/core/src/lib/ModalBase/ModalBase.stories.tsx
libs/island-ui/core/src/lib/ModalBase/ModalBase.tsx

Make it possible to toggle visibility with state,
Make it optional to remove modal after it's closed
>Make it possible to toggle visibility with state
It's not always possible to wrap the modal using disclosure, e.g. when modal is triggered as a response of some event
>Make it optional to remove modal after it's closed
Less clutter in the DOM when rendering list of items that can trigger modals, if modals are the same it will remove problems like duplicate id's

Island-ui / Base modal visibility

---

libs/island-ui/contentful/src/lib/RichTextRC/defaultRenderNode.tsx

Table of contents is not working on life events page
- Fixed broken id for header elements

Added fix for life event ids

---

apps/web/components/CardsSlider/CardsSlider.tsx
apps/web/screens/LifeEvent/LifeEvent.tsx

To show more content on life event screen
To show more of the card on the screen

Remove extra padding on mobile

---

package.json
yarn.lock

- `yarn run security-audit` repors high vulnerabilities regarding immer.
- We have warnings for two packages, storybook and slate/* both have open issues https://github.com/storybookjs/storybook/issues/13961 and https://github.com/ianstormtaylor/slate/pull/4050, it should be a matter of time a patch version is published, using resolutions shouldn't impact the usage of these two packages

fix: update immer for security report

---

scripts/e2e-ci.js

In CI pipeline e2e step succeeds even test specs fails.
To stop build wrongly passing on e2e failure.

Fix e2e false success

---

libs/api/domains/national-registry/src/lib/graphql/models/address.model.ts

Make last update date nullable.
Data from national registry api returns null even if users have correctly registered addresses. It is possibly that the data in the dev env is not complete. But this fix will prevent queries to fail.

Fix: Make address update date nullable

---

apps/services/search-indexer/src/migrate/aws.ts

https://app.asana.com/0/1199123945323117/1199979538876695
Logs are flagging "Associating package with AWS ES domain" as not allowed.
Most likely it's the attempt to disassociate the package that is causing the error.
- Fixed logs
- To make it clear where not allowed error originates
- Fix copy/paste error

Fixed log message

---

.github/workflows/push.yml

Build on main is failing due to timeout - https://github.com/island-is/island.is/runs/1970331826

More time to build node modules cache

---

apps/web/components/ServiceInformation/ServiceInformation.tsx

Disabling the environment select box.
There is always one environment here for now, so we want it un-selectable, until there will be more environments to choose from.

Locking environment checkbox

---

libs/application/templates/health-insurance/src/fields/Review/StatusAndChildren.tsx
libs/application/templates/health-insurance/src/forms/messages.ts

Fixed markdown on link in already insured modal
Translation fix on status and children review

fix (Health insurance): Already insured modal link, translation on status and children review

---

apps/service-portal/src/hooks/useModules/useModules.ts
libs/feature-flags/README.md
libs/feature-flags/src/lib/configcat.ts
libs/feature-flags/src/lib/types.ts

NationalId should be included in configcat request
So we will be able to use user segments for special users until we get the delegation system

fix(service-portal): nationalId should be included in ff request

---

apps/judicial-system/backend/src/app/formatters/pdf.ts

https://app.asana.com/0/1199153462262248/1199999639914930
If accousedPleaAnnouncement was left empty,  the PDF would display null instead of an empty string
It's a bug.

fix(judicial-system): Null guard accusedPleaAnnounement in PDF

---

libs/application/templates/health-insurance/src/fields/ErrorModal/ErrorModal.tsx

Disabled hide on click outside for error modal

feature(health-insurance): Disabled hide on click outside for error modal

---

apps/judicial-system/web/src/routes/Shared/DetentionRequests/DetentionRequests.tsx

https://app.asana.com/0/1199153462262248/1200032250261907
See ☝️
The tag used to be "Krafa send" for both prosecutors and judges which doesn't make sense for judges.

feat(judicial-system):Submitted claims now have a Ny Krafa tag for judges

---

libs/island-ui/core/src/lib/Grid/Grid.stories.tsx
libs/island-ui/core/src/lib/Grid/GridColumn/GridColumn.treat.ts

Adding '0' to columns to fix offset reset for breakpoints
When offset was set to '0' in breakpoints above mobile it was not reset

fix(island-ui): Reset grid offset

---

apps/web/layouts/main.tsx
apps/web/screens/queries/AlertBanner.tsx
libs/api/domains/cms/src/lib/generated/contentfulTypes.d.ts
libs/api/domains/cms/src/lib/models/alertBanner.model.ts
libs/api/mocks/src/domains/cms/factories.ts

- If there is no link (and link title) provided it will simply not appear in the AlertBanner.
- Made the link use the LinkResolver
AlertBanner was broken when there was no link (or there was a link but the reference to it was removed).

fix(web): AlertBanner link not required and uses LinkResolver

---

apps/application-system/api/src/app/modules/application/application.controller.ts
apps/application-system/api/src/app/modules/application/dto/createApplication.dto.ts
apps/application-system/api/src/app/modules/application/e2e/application.spec.ts
apps/application-system/form/src/routes/Applications.tsx
libs/api/domains/application/src/lib/dto/createApplication.input.ts

Refactor createApplication to only accept `typeId`
So it is not possible to construct applications in some desired states.

chore(application-system-api): Only accept typeId when creating applications

---

libs/application/templates/health-insurance/jest.config.js
libs/application/templates/health-insurance/src/healthInsuranceUtils.spec.ts

Added additional test for the draft util to check that:
- error modal about active draft doesn't show if the user already is on the oldest draft
- function is returning the oldest draft id

test(health-insurance): add test to check draft util

---

apps/web/components/LifeEventsCardsSection/LifeEventsCardsSection.tsx
apps/web/components/SearchInput/SearchInput.tsx
apps/web/screens/Home.tsx
apps/web/screens/Search/Search.tsx

- Life event cards on front page slider are shown even if there is no content. Only showing if it has title and slug for link.
- Added language string that was missing in search results dropdown.

fix(web): Add language string and skip untranslated life event cards

---

libs/api/domains/education/src/lib/s3.service.ts

Presign using a promise
> GetPresignedUrl: You must ensure that you have static or previously resolved credentials if you call this method synchronously (with no callback), otherwise it may not properly sign the request. If you cannot guarantee this (you are using an asynchronous credential provider, i.e., EC2 IAM roles), you should always call this method with an asynchronous callback.
So using a promise instead.

fix(license): presign using a promise

---

libs/application/templates/children-residence-change/src/fields/Duration/index.tsx

Adds locale to datepicker
So it is in correct format

fix(crc): Locale in datepicker

---

README.md
apps/web/README.md
handbook/technical-overview/feature-flags.md

docs: Mention need for `export ` prefix for variables in `.env.secret`

---

libs/island-ui/core/src/lib/DatePicker/DatePicker.stories.tsx

The `DatePicker` storybook is crashing becuse of an error:
```
TypeError: Cannot read property 'locale' of undefined
```
- Removed the `pl` example

fix(ui-island): datepicker storybook

---

.github/.kodiak.toml

See title
To get consistent git history. The default configuration is "github_default", which sometimes uses PR title and sometimes the commit title, depending on how many commits there are. Instead we always want the conventional commit validated PR title.

chore(core): configure kodiak to always use PR title

---

apps/judicial-system/web/src/routes/Shared/DetentionRequests/PastDetentionRequests.tsx

https://app.asana.com/0/1199153462262248/1199877900959589
Fix "Extension" label formatting in PastDetentionRequests table
The pervious label was not formatted correctly.

fix(judicial-system): Detention requests table fixes

---

libs/application/templates/children-residence-change/src/fields/Overview/index.tsx

The ternarny operator is uses the same value two times and crashes on this screen since the answer is undefined for parentB in the step.

fix(crc): Fixes localization key

---

libs/application/templates/children-residence-change/src/fields/Overview/SignatureModal/ModalConditionalContent.tsx
libs/application/templates/children-residence-change/src/fields/Overview/SignatureModal/index.tsx
libs/application/templates/children-residence-change/src/fields/Overview/index.tsx

Changes type we send to signature modal to skip null checking all over the place.

fix(crc): Refactor types in signature modal

---

apps/reference-backend/sequelize.config.d.ts
apps/reference-backend/src/app/modules/resource/dto/resource.dto.ts
apps/reference-backend/src/app/modules/resource/resource.controller.ts
apps/reference-backend/src/app/modules/resource/resource.model.ts
apps/reference-backend/src/app/modules/resource/resource.service.ts
apps/reference-backend/tsconfig.json
apps/reference-backend/webpack.config.js
workspace.json

Swagger plugin seems to not be working as intended.
- Added fix for Swagger plugin
- Removed decorators handled by default in Swagger plugin
- Made TS strict
- TS strict seems like the agreed default

fix(reference-backend): Swagger plugin webpack fix

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/screens/Organization/NewsItem.tsx
apps/web/screens/Organization/NewsList.tsx
apps/web/screens/Organization/Services.tsx
apps/web/screens/Organization/SubPage.tsx
apps/web/screens/queries/Organization.tsx
libs/api/domains/cms/src/lib/generated/contentfulTypes.d.ts
libs/api/domains/cms/src/lib/models/organizationPage.model.ts

Adds option for secondary purple menu on organization pages. Also fixes header color scheme for subpages.
This is according to design.

feat(web): Add organization secondary menu

---

libs/api/domains/cms/src/lib/cms.resolver.ts
libs/api/domains/cms/tsconfig.json
libs/api/domains/cms/tsconfig.lib.json

Forgot to enable strict in the tsConfig. Fixed an error introduced since first error pruning.

fix(api-domains-cms): Enabled strict and fixed a remaining typescript error

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/screens/Organization/NewsItem.tsx
apps/web/screens/Organization/NewsList.tsx
apps/web/screens/Organization/Syslumenn/Auction.tsx

Organization title used as meta title suffix on organization subpages. 
Example: _Fréttir og tilkynningar | Sýslumenn_
Keep consistancy on meta title usages. On single article it is _Article name | Ísland.is_

feat(web): Organization meta title

---

apps/judicial-system/web/src/routes/Judge/Overview/Overview.spec.tsx
apps/judicial-system/web/src/routes/Judge/Overview/Overview.tsx
apps/judicial-system/web/src/utils/mocks.ts

https://app.asana.com/0/1199153462262248/1199986469006836
Remove 'Open' button from judge files overview if the currently logged in judge is not the assigned judge on that case
Only the judge assigned to a case should be able to see case files for that case.
TODO: div decendant in p

fix(judicial-system): Judge overview file fix

---

apps/service-portal/src/store/modules.ts
libs/service-portal/core/src/lib/navigation/masterNavigation.ts
libs/service-portal/education/src/screens/EducationOverview/EducationOverview.tsx

We want to remove the education degree page from the service portal, and remove it from the latest section.
This is a cherry-pick of #3431 on top of release 8.0.0
Education degree page is not production ready

feat(service-portal): hotfix removal of education degree page from service-portal

---

apps/judicial-system/api/src/app/modules/feature/feature.controller.ts

☝️ 
Feature hiding should always be available

fix(judicial-system): Removes auth guard from feature hiding

---

libs/island-ui/core/src/lib/Checkbox/Checkbox.treat.ts

Align the input box with the visual box
After setting alignSelf to center the input box and the visual checkbox did not align anymore. 
Before:
After:

fix(island-ui): Align input box with visual box

---

libs/application/core/src/lib/formUtils.ts
libs/application/templates/parental-leave/src/config.ts
libs/application/templates/parental-leave/src/lib/answerValidators.spec.ts
libs/application/templates/parental-leave/src/lib/answerValidators.ts

This PR fixes 2 issues and updates 1 value:
1. Allow the user to move the duration slider beyond 6 months
2. Resolve an error if the user refreshes while on the duration slider screen.
3. Change the maxMonths value to 24
Notes:
On the duration slider screen, we can't determine if the user will spread their leave beyond 6 months with a percent ratio lower than 100. So we will take out the check `"if the endDate is inside the allowed range of days/months"` for now.

fix(parental-leave): Fixes to duration slider screen

---

apps/web/screens/queries/Organization.tsx

This fixes images and attachments not appearing on the subpages.

fix(web): Fix organization subpage query to fetch assets

---

libs/island-ui/contentful/src/lib/ContactUs/ContactUs.tsx
libs/island-ui/core/src/lib/Checkbox/Checkbox.tsx
libs/island-ui/core/src/lib/IconRC/Icon.tsx
libs/island-ui/core/src/lib/Input/Input.tsx
libs/island-ui/core/src/lib/RadioButton/RadioButton.tsx
libs/island-ui/core/src/lib/Select/Select.tsx

- Added `aria-live="assertive"` to form errors for screen readers to immediately notify the user of any error
- Made input fields have `aria-describedby` with the id of the displayed error
- Set `aria-hidden="true"` for asterisks (*) in required field labels
- Added `ariaHidden` as an optional prop for Icon component and set it to true in the Input/Select where it displays an alert icon

fix(island-ui): Tweak aria errors for form fields

---

scripts/ci/Dockerfile.cypress

Fix broken build
Because developers are usually not happy with broken build

fix(system-e2e): Wrong target name on cypress dockerfile

---

apps/judicial-system/web/src/routes/Shared/DetentionRequests/PastDetentionRequests.tsx

https://app.asana.com/0/1199153462262248/1200214145052850
Remove custody time boundaries if past case was rejected
It doesn't make sense to show to and from dates for rejected custody requests

fix(judicial-system): Remove custody time boundaries if past case was rejected

---

libs/api/domains/document-provider/src/lib/models/organisation.model.ts

Make Organisation api model fields nullable where nullable
To display manually inserted objects

fix(dpo): Make Organisation api model fields nullable where nullable

---

apps/judicial-system/web/src/routes/Judge/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Prosecutor/Overview/Overview.tsx

https://app.asana.com/0/1199153462262248/1200195763827515
Add case file comments to overview screen for judges and fix typo on overview page for prosecutors where "Athugasemdir vegna málsmeðferðar" was the title for both comments and caseFileComments
Case file comments should be visible to the judge.

feat(judicial-system): Add case file comments to overview screen for judges

---

apps/endorsement-system/seeders/20210325171826-development.js
apps/endorsement-system/src/app/modules/endorsement/e2e/endorsement.spec.ts
apps/endorsement-system/src/app/modules/endorsement/endorsement.service.ts
apps/endorsement-system/src/app/modules/endorsementList/e2e/endorsementList.spec.ts
apps/endorsement-system/src/app/modules/endorsementList/endorsementList.model.ts
apps/endorsement-system/src/app/modules/endorsementMetadata/endorsementMetadata.module.ts
apps/endorsement-system/src/app/modules/endorsementMetadata/endorsementMetadata.service.ts
apps/endorsement-system/src/app/modules/endorsementMetadata/providers/endorsementSystemSignedLists.service.ts
apps/endorsement-system/src/app/modules/endorsementMetadata/providers/nationalRegistryUser.service.ts
apps/endorsement-system/src/app/modules/endorsementValidator/endorsementValidator.decorator.ts
apps/endorsement-system/src/app/modules/endorsementValidator/endorsementValidator.module.ts
apps/endorsement-system/src/app/modules/endorsementValidator/endorsementValidator.service.ts
apps/endorsement-system/src/app/modules/endorsementValidator/validators/uniqueWithinTags/uniqueWithinTagsValidator.service.spec.ts
apps/endorsement-system/src/app/modules/endorsementValidator/validators/uniqueWithinTags/uniqueWithinTagsValidator.service.ts

We need to be a ble to ensure the endorsement is unique within a set scope of endorsmentList types
- Added way for validations to request metadata
- Updated tags to be unique for this election
- Updated seeders to match updated data
- Added check to make sure nationalId is a person
- Updated e2e tests
- Added unit tests
- Added tag unique within list validator

feat(endorsement-system): Endorsement unique within list tag validation

---

apps/web/hooks/useNamespace.ts

Adds a crucial bit to `useNamespaceStrict()`'s `RetVal` typing that didn't make it over from the feature-branch from which this feature was cherry picked.
(Test/spec file compilation only succeeded because Jest runs in non-strict mode. We **MUST** fix this issue.)

fix: Add missing `useNamespaceStrict()` `RetVal` typing action

---

libs/application/template-api-modules/src/lib/modules/templates/institution-collaboration/institution-collaboration.service.ts
libs/application/templates/institution-collaboration/src/forms/application.ts
libs/file-storage/src/lib/file-storage.service.ts

Ic Using asynchronous method instead of synchronous
##What
Changed s3.getSignedUrl method, using asynchronous overload instead of synchronous.
Attempting to fix issues when generating signedUrl on staging.

fix: Release/8.1 ic application s3 fix

---

libs/application/template-api-modules/src/lib/modules/templates/children-residence-change/emailGenerators/applicationSubmitted.ts
libs/application/template-api-modules/src/lib/modules/templates/children-residence-change/emailGenerators/transferRequested.ts
libs/application/template-api-modules/src/lib/modules/templates/document-provider-onboarding/emailGenerators/applicationApproved.ts
libs/application/template-api-modules/src/lib/modules/templates/document-provider-onboarding/emailGenerators/applicationRejected.ts
libs/application/template-api-modules/src/lib/modules/templates/document-provider-onboarding/emailGenerators/assignReviewerEmail.ts
libs/application/templates/children-residence-change/src/forms/ChildrenResidenceChangeForm.ts

Currently emails are not sending because `development@island.is` was hardcoded as a sender.
Fixing this issue for applications that are already in production.
We have a better solution for this that we will implement and release later.
- Emails are failing on production

fix(application-system): use env variables when sending emails

---

libs/application/templates/parental-leave/src/fields/Review/index.tsx
libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts

Temporarily comment out sharing leave information with other parent. 
We will work on this post v1 launch.
We have not built the functionality to combine to the information points (your leaves and the other parent)

chore(parental-leave): Temporarily remove sharing leave information with other parent

---

apps/application-system/api/src/environments/environment.prod.ts
apps/application-system/api/src/environments/environment.ts
libs/application/template-api-modules/src/lib/modules/shared/shared.service.ts
libs/application/template-api-modules/src/lib/modules/templates/children-residence-change/emailGenerators/applicationSubmitted.ts
libs/application/template-api-modules/src/lib/modules/templates/children-residence-change/emailGenerators/transferRequested.ts
libs/application/template-api-modules/src/lib/modules/templates/document-provider-onboarding/emailGenerators/applicationApproved.ts
libs/application/template-api-modules/src/lib/modules/templates/document-provider-onboarding/emailGenerators/applicationRejected.ts
libs/application/template-api-modules/src/lib/modules/templates/document-provider-onboarding/emailGenerators/assignReviewerEmail.ts
libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/applicationApproved.ts
libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/assignEmployerEmail.ts
libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/assignOtherParentEmail.ts
libs/application/template-api-modules/src/lib/modules/templates/reference-template/emailGenerators/applicationApproved.ts
libs/application/template-api-modules/src/lib/types/index.ts

Reads email sender name and email address from environment variables instead of hard coding them.
There is a different value white listed for sending email's on production then on dev and staging. This means that the current implementation with hard coding the email address would always be blocked on production.

fix(as): Reads email from env values

---

libs/island-ui/core/src/lib/ActionCard/ActionCard.stories.tsx
libs/island-ui/core/src/lib/ActionCard/ActionCard.tsx
libs/island-ui/core/src/lib/IconRC/iconMap.ts
libs/island-ui/core/src/lib/IconRC/icons/Document.tsx
libs/island-ui/core/src/lib/IconRC/icons/DocumentOutline.tsx

This adds the option for a secondary CTA on Action Cards.
We need something like this for a list of applications that have both a digital version (primary) and a PDF (secondary).
Designers think this should be a part of the core library.

feat(island-ui): Add secondary CTA option to Action Card

---

apps/judicial-system/web/src/routes/Judge/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Prosecutor/Overview/Overview.tsx

https://app.asana.com/0/1199153462262248/1200221197332081
Style changes to comments
Instead of having two accordion items for comments, combine them into one which makes the UI cleaner.

feat(judicial-system): Style changes to comments

---

apps/endorsement-system/seeders/20210325171826-development.js
apps/endorsement-system/src/app/modules/endorsement/e2e/endorsement.spec.ts
apps/endorsement-system/src/app/modules/endorsement/endorsement.service.ts

Actions should be limited on closed lists
- Made user unable to endorse closed lists
- Made user unable to remove endorsements from closed lists
- Made owner unable to bulk create endorsements on closed lists
- Updated test to reflect changes
- We consider closed lists to be locked in time

feat(endorsement-system): Closed lists

---

apps/services/endorsements/api/src/app/modules/endorsementMetadata/endorsementMetadata.module.ts

Environment dev file getting swapped out for environment prod file is breaking the build.
- Added `as NationalRegistryConfig`
- To suppress type issue

fix(services-endorsement-api): Fix for national registry environment

---

apps/endorsement-system/seeders/20210325171826-development.js
apps/endorsement-system/src/app/modules/endorsement/e2e/endorsement.spec.ts
apps/endorsement-system/src/app/modules/endorsement/endorsement.controller.ts
apps/endorsement-system/src/app/modules/endorsement/endorsement.service.ts
apps/endorsement-system/src/app/modules/endorsementList/e2e/endorsementList.spec.ts

Bulk endorsement should invalidate any existing endorsements when bulk importing endorsements.
- Added invalidate endorsements on bulk import
- Added tests for this case

feat(endorsement-system): bulk import conflict handling

---

libs/application/templates/children-residence-change/src/fields/Overview/index.tsx
libs/application/templates/children-residence-change/src/lib/messages/contract.ts

https://app.asana.com/0/1199733748699731/1200270543199448
- Render different string for parent A and parent B
- We want to be able to display different text for depending on which parent is viewing the application

fix(crc): overview description

---

apps/judicial-system/web/src/routes/Judge/Overview/Components/ConclusionDraft.tsx
apps/judicial-system/web/src/shared-components/Modal/Modal.treat.ts
apps/judicial-system/web/src/shared-components/RulingInput/RulingInput.tsx

https://app.asana.com/0/1199153462262248/1200162824002549
Layout changes to the conclusion modal
We want to do everything we can to prevent users to have to scroll the modal window.

fix(judicial-system): Layout changes to the conclusion modal

---

apps/web/layouts/main.tsx

Preload fonts, trying to reduce largest contentful paint
Trying to improve the lighthouse score

chore(web): font preloading

---

libs/island-ui/core/src/lib/ProfileCard/ProfileCard.tsx

- Change border style from shadow to solid
- Add option for link at bottom of card
- Add option for making the content smaller
We need this to implement a new design.
This is done in cooperation with Helgi Páll from K&K.

feat(island-ui): Add properties to Profile Card and change card border

---

apps/web/screens/Adgerdir/Article.tsx
apps/web/screens/Adgerdir/Home.tsx

Removes the chatbot on the covid pages. It is about to be taken down so it would no longer be functional on the page. Requested by Fríða from Stafrænt Ísland.

chore(web): Remove chatbot from covid pages

---

apps/download-service/src/app/modules/documents/document.controller.ts
apps/download-service/src/app/modules/documents/dto/getDocument.dto.ts
libs/clients/documents/src/lib/documentClient.ts
libs/clients/documents/src/lib/documents.module.ts

Increasing the timeout to 30s , added exeption handling on the document client.
Body token was incorrect in controller after auth changes from [#3149](https://github.com/island-is/island.is/pull/3419)
Some document requests are taking longer than 10s to respond and thus returning an unhandled error which was causing problems for the app. 

fix(download-service): hotfix-download service auth and timeout extend

---

libs/application/templates/funding-government-projects/src/lib/FundingGovernmentProjectsTemplate.ts

Application for funding government projects is missing the ready for production flag.
Also translation added for application name.

fix: Aafgp - set ready for prod flag

---

libs/application/core/README.md

I didn't add documentation after implementing the new translation service. Here we go

docs: add documentation for AS translations

---

libs/application/templates/parental-leave/src/dataProviders/Children/Children.ts

Skipping all requests in data provider if mocking data
Some of them may fail because you are not expecting a baby so that the data provider will not return mocked data

chore(application-templates-parental-leave): Skip requests in Children data provider if mocking data

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/screens/Article.tsx

Articles can have multiple organizations attached to it. This PR makes articles use the footer of the first organization in the array that has a configured footer.
Some articles were not displaying the Syslumenn header because another organization was element zero in the array.

feat(web): Select article footer and chat panel from array of organizations

---

apps/web/screens/queries/fragments.ts
libs/api/domains/cms/src/lib/generated/contentfulTypes.d.ts
libs/api/domains/cms/src/lib/models/mailingListSignupSlice.model.ts

Add a new field `signupUrl` to Contentful type `MailingListSignup`.
So that Contentful types reflect the corresponding content model in Contentful. The corresponding content model in Contentful is named `Email Signup`. In an upcoming Pull Request, we'll use this new field to set mailing list signup URLs via Contentful.

feat(web): Add new field signupUrl to Email Signup Contentful model

---

package.json
yarn.lock

This should get rid of the build error but I don't know if it will impact `webpack-dev-server` in any apps or libraries. I have only verified that the `application-system` works fine.
https://github.com/webpack/webpack-dev-server/issues/3340#issuecomment-847659624
Fix security issues with `multicast-dns`

fix(core): security audit multicast-dns and browserslist

---

libs/auth-nest-tools/src/lib/current-user.decorator.ts
libs/auth-nest-tools/src/lib/getRequest.ts

Use graphql context where appropriate
This would result in loosing the GraphQL context for nested resolvers,
meaning that this would not work:
```typescript
@ResolveField('address')
resolveAddress(@CurrentUser() user: User) {
// throws an error due to the @CurrentUser decorator
}
```

fix(core): Use graphql context where appropriate

---

apps/application-system/form/src/routes/Applications.tsx
libs/application/core/src/lib/messages.ts

Currently we are displaying different text in the application list buttons
- Added new translation strings
- Updated the application list component to display the same text as in Mínar síður
- I will push translations to Contentful once this gets merged to `main`
- We want to have this unified

fix(application-system): update button text in application list

---

apps/web/screens/AboutPage/RenderForm.tsx
libs/island-ui/core/src/lib/NewsletterSignup/NewsletterSignup.stories.tsx
libs/island-ui/core/src/lib/NewsletterSignup/NewsletterSignup.treat.ts
libs/island-ui/core/src/lib/NewsletterSignup/NewsletterSignup.tsx

Add message and styling for the state `success` of `NewsletterSignup`.
Implemented by design from Helgi at K&K.
Previous version of `NewsletterSignup` did not have any handling implemented for the success state.

feat(island-ui): NewsletterSignup - Add message and styling for success state

---

apps/web/components/Organization/Wrapper/Themes/UtlendingastofnunTheme/UtlendingastofnunHeader.treat.ts

This makes the Utl. header a bit darker.
Designers want to try this.

feat(web): Change header background for Utlendingastofnun

---

apps/air-discount-scheme/backend/esbuild.json

Add missing external dependencies
To make air-discount-scheme-backend run

fix(ads-backend): Add missing color* externals

---

libs/api/domains/national-registry-x-road/src/lib/nationalRegistryXRoad.service.ts
libs/application/templates/family-matters/children-residence-change/src/dataProviders/MockNationalRegistryProvider.ts

We now use the `fjolskylda` endpoint to determine if children live with the applicant, parentB or both.

fix(crc): children legal residence check

---

scripts/e2e-ci.js
scripts/schemas.js
scripts/static-serve.js
scripts/utils.js

Improving e2e-ci by using only spawn for child process, and piping otput to stdout for better debugging in CI.
e2e test are sometimes flaky and recently we saw e2e test for `web` hanging for 25min without any useful logs.
To be able to debug flaky e2e tests in CI with more output logs.

chore(core): Improving e2e in CI

---

apps/judicial-system/web/src/shared-components/DropdownMenu/DropdownMenu.tsx
libs/island-ui/core/src/lib/Box/useBoxStyles.treat.ts
libs/island-ui/core/src/lib/Box/useBoxStyles.ts

Add the ability to use zIndex: 1 in useBoxStyles

feat(island-ui): Add zIndex to useBoxStyles

---

libs/application/core/src/lib/formBuilders.ts
libs/application/templates/parental-leave/src/forms/DraftRequiresAction.ts
libs/application/templates/parental-leave/src/forms/EditOrAddPeriods.ts
libs/application/templates/parental-leave/src/forms/EditsInReview.ts
libs/application/templates/parental-leave/src/forms/EditsRequireAction.ts
libs/application/templates/parental-leave/src/forms/EmployerApproval.ts
libs/application/templates/parental-leave/src/forms/InReview.ts
libs/application/templates/parental-leave/src/forms/OtherParentApproval.ts
libs/application/templates/parental-leave/src/forms/Prerequisites.ts

- https://app.asana.com/0/1182378413629561/1200409061590810
- So we have nice titles in the browser tabs while the step is active

fix(parental-leave): missing tiles and wrong ids

---

README.md
scripts/ci/Dockerfile.cypress
scripts/ci/Dockerfile.test

Update node versions from 14.16 to 14.17
Breaking CI since it is the new [minimum version](https://github.com/island-is/island.is/blob/main/package.json#L6).

chore(core): Update dockerfile node versions from 14.16 to 14.17

---

apps/web/pages/stofnanir/[slug]/[subSlug]/index.tsx

Redirect all organization subpages from `/stofnanir/[slug]/[subslug]` to `/s/[slug]/[subslug]`.

fix(web): Add redirect for organization subpages

---

libs/feature-flags/src/lib/context.tsx

Use nationalId as a user identifier in configcat.
This makes feature flags simpler, and allows us to do percentage based
feature rollouts more reliably.
It also fixes a delegation feature flag which the service portal is sharing with the identity server.

fix(feature-flags): Use nationalId as a user identifier

---

libs/application/templates/parental-leave/src/fields/Duration/index.tsx
libs/application/templates/parental-leave/src/fields/components/Slider/index.tsx

Fixes the duration slider so that it calculates the percentage when the track is clicked and when the keyboard arrow keys are used.
The bug:

fix(parental-leave): Fixes duration slider events not called

---

libs/application/template-api-modules/src/lib/modules/templates/party-application/emailGenerators/assignSupremeCourtEmail.ts
libs/application/template-api-modules/src/lib/modules/templates/party-letter/emailGenerators/assignToMinistryOfJustice.ts

Currently emails are hardcoded and can't be properly tested in deployment environments
- Made emails use environment variables
- Allow for testing in dev and staging

feat(application-templates-party-application): Move emails to environment variables

---

libs/application/templates/parental-leave/src/fields/Duration/index.tsx
libs/application/templates/parental-leave/src/fields/components/Slider/index.tsx

Merging #4233 into the release branch
* Fixes the duration slider so that it calculates the percentage when the track is clicked and when the keyboard arrow keys are used.
* Removes Slider tooltip for this release

fix(parental-leave): Fixes duration slider events not called (#4233)

---

apps/api/src/app/app.module.ts
apps/api/src/app/environments/environment.ts
libs/api/domains/license-service/src/lib/client/driving-license-client/drivingLicenseService.api.ts
libs/api/domains/license-service/src/lib/licenseService.module.ts

Move xroad path for RLS driving license service into env var `DRIVING_LICENSE_XROAD_PATH`.
Path was mistakenly left hard-coded in first version.

fix(api): move driving license xroad path into env

---

libs/api/domains/document-provider/src/lib/document-provider.resolver.ts
libs/api/domains/document-provider/src/lib/document-provider.service.ts

Failed to load statistics for single provider. The reason was that the authentication token was not forwarded to the services-layer.
Bugfix

fix(dpo): fix single provider statistics - unauthorized

---

apps/services/endorsements/api/src/app/modules/endorsementMetadata/endorsementMetadata.model.ts
apps/services/endorsements/api/src/app/modules/endorsementMetadata/providers/temporaryVoterRegistry/temporaryVoterRegistry.service.ts
libs/api/domains/endorsement-system/src/lib/models/endorsementMetadata.model.ts

Voter region metadata field is not being exported properly from the endorsement system and domain
- Added `voterRegion` to exported metadata field types
- To make the field accessible via the graphql api

fix(services-endorsements-api): Metadata type

---

apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/Defendant/DefendantForm.tsx

https://app.asana.com/0/1199153462262248/1200474750183715
- Fixes a missing placeholder for R Cases select dropdown
- Bug

fix(judicial-system): only display default value if there is a workingCase

---

apps/air-discount-scheme/backend/docker-compose.dev.yml
apps/application-system/api/docker-compose.dev.yml
apps/gjafakort/application/docker-compose.dev.yml

The one on public ecr doesn't seem to be compatible with the one we
were using. No need to change them since this is not running in ci.

fix(dev): Revert docker image for redis cluster

---

.eslintrc.json
.github/workflows/pullrequest.yml
apps/api/src/app/app.module.ts
apps/api/src/app/environments/environment.ts
libs/api/domains/document-provider/src/lib/document-provider.resolver.ts
libs/api/domains/documents/src/lib/document.resolver.ts
libs/api/domains/driving-license/src/lib/graphql/main.resolver.ts
libs/api/domains/education/src/lib/graphql/main.resolver.ts
libs/api/domains/health-insurance/src/lib/graphql/healthInsurance.resolver.ts
libs/api/domains/national-registry-x-road/src/lib/nationalRegistryXRoad.resolver.ts
libs/api/domains/national-registry/src/lib/graphql/familyMember.resolver.ts
libs/api/domains/national-registry/src/lib/graphql/user.resolver.ts
libs/api/domains/rsk/src/lib/api-domains-rsk.resolver.ts

As part of the authentication and delegation system we are adding audit logs to our services and
our GQL api domains that read sensitive data from 3rd party service providers.
To audit which user is reading what data.

feat(api): Add audit logs to domains consuming 3rd party services

---

apps/air-discount-scheme/web-e2e/cypress.json
apps/application-system/form-e2e/cypress.json
apps/auth-admin-web-e2e/cypress.json
apps/gjafakort/web-e2e/cypress.json
apps/judicial-system/web-e2e/cypress.json
apps/service-portal-e2e/cypress.json
apps/skilavottord/web-e2e/cypress.json
apps/system-e2e/cypress.json
apps/web-e2e/cypress.json

It seems that the Cypress video record processing can make our e2e test hang.
https://github.com/cypress-io/cypress/issues/6695#issuecomment-852811773
Test if the video recording process is making our e2e test able to hang.
To improve developer experince with the CI pipeline.

ci(core): Disable Cypress video recording

---

apps/judicial-system/web/messages/caseFiles.ts
apps/judicial-system/web/messages/index.ts
apps/judicial-system/web/messages/requestCourtDate.ts
apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/CaseFiles/CaseFilesForm.tsx
apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepFive/StepFiveForm.tsx
apps/judicial-system/web/src/shared-components/MarkdownWrapper/MarkdownWrapper.treat.ts
apps/judicial-system/web/src/shared-components/MarkdownWrapper/MarkdownWrapper.tsx

https://app.asana.com/0/1199153462262248/1200501166205913
- Added strings for case files
- Added an initial MarkdownWrapper component
https://docs.devland.is/libs/localization#markdown-support
- We want to be able to control strings through Contentful

feat(judicial-system): case files strings to contentful

---

apps/application-system/api/infra/application-system-api.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

API ENV calls these like this:
```
callbackAdditionUrl: process.env.PAYMENT_ADDITION_CALLBACK_URL,
callbackBaseUrl: `process.env.PAYMENT_BASE_CALLBACK_URL
```
application-system-api calls them like this:
```
callbackBaseUrl: process.env.PAYMENT_BASE_CALLBACK_URL,
callbackAdditionUrl: process.env.PAYMENT_ADDITION_CALLBACK_URL,
```

fix(charts): wrong env link to chart

---

libs/auth/react/src/lib/Authenticator/Authenticator.spec.tsx
libs/auth/react/src/lib/Authenticator/Authenticator.treat.ts
libs/auth/react/src/lib/Authenticator/Authenticator.tsx
libs/auth/react/src/lib/Authenticator/AuthenticatorErrorScreen.tsx
libs/auth/react/src/lib/Authenticator/AuthenticatorLoadingScreen.tsx
libs/auth/react/src/lib/Authenticator/OidcSignIn.tsx

* Render an error screen if the OIDC callback has an error from the IDS.
* Avoid race conditions in redirects during error callbacks.
* Never pass the OIDC callback url as a return url for IDS.
Better error handling. Spotted when an IDS regression caused strange client behaviour.
In case of an error during IDS login:

fix(auth): Improve signin error handling

---

apps/judicial-system/web/messages/reportForm.ts
apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/PoliceReport/PoliceReportForm.tsx

https://app.asana.com/0/1199153462262248/1200530258163038
- Changed the defaultMessage
- Fixed dependency array in useEffect
- Bug

fix(judicial-system): wrong defaultMessage in translation string

---

.github/workflows/push.yml

Feature deployments should not send a message about failed builds to slack

fix(ci): Avoid sending message on feature deploy

---

apps/services/endorsements/api/infra/endorsement-system-api.ts
apps/services/party-letter-registry-api/infra/party-letter-registry-api.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

Fix we already applied on release/9.2.0

fix: infrastructure settings missing for cross-namespace comms

---

apps/api/src/app/app.module.ts
apps/service-portal/src/components/UserDelegations/UserDelegations.tsx
libs/api/domains/auth/src/lib/auth.module.ts
libs/api/domains/auth/src/lib/models/delegation.model.ts
libs/api/domains/auth/src/lib/resolvers/delegation.resolver.ts
libs/api/domains/identity/src/index.ts
libs/api/domains/identity/src/lib/identity.module.ts
libs/api/domains/identity/src/lib/identity.resolver.ts
libs/api/domains/identity/src/lib/identity.service.ts
libs/island-ui/core/src/lib/Input/Input.tsx
libs/island-ui/core/src/lib/Input/types.ts
libs/service-portal/graphql/src/lib/queries/getActorDelegations.ts
libs/service-portal/settings/access-control/src/screens/Access/Access.tsx
libs/service-portal/settings/access-control/src/screens/AccessControl/components/Accesses/Accesses.tsx
libs/service-portal/settings/access-control/src/screens/GrantAccess/GrantAccess.tsx
libs/shared/form-fields/src/lib/InputController/InputController.tsx

Use Identity type instead of from / to for delegations
From* and To* name should be readonly and should just come from rsk or national-registry

feat(access-control): use identity for delegations

---

nx.json
package.json
yarn.lock

* Adding resolution for dicer to version 0.3.0, solving the deprecated buffer warning.
* Adding resolutions to nx.json to trigger affacted change.

chore(core): Adding resolution for dicer to version 0.3.0 (#4403)

---

apps/application-system/api/webpack.config.js
apps/application-system/form/webpack.config.js
apps/service-portal/webpack.config.js

- Not working when using `NODE_ENV=development`, I believe it can be safely removed

chore(application-system,service-portal): remove non used dev config

---

libs/application/templates/family-matters/children-residence-change/src/forms/ChildrenResidenceChangeForm.ts

Hotfix hiding mock data section so we don't display the `Continue` and `Back` buttons in places where they shouldn't be present.

fix(crc): hide mock data section

---

apps/web/screens/Project/Project.tsx
apps/web/screens/queries/Project.tsx
libs/api/domains/cms/src/lib/generated/contentfulTypes.d.ts
libs/api/domains/cms/src/lib/models/projectPage.model.ts

Add OG image and description to project pages for sharing on social media.
People want to use it for island.is/entry

fix(web): Add OG image and description to project pages

---

apps/service-portal/src/components/UserDelegations/UserDelegations.tsx

Hide loading indicator if delegation request fails.
The loading indicator would be forever visible if the request fails.

fix(auth): hide loading indicator if delegation request fails

---

apps/web/components/Organization/Slice/EventSlice/EventSlice.treat.ts

The event slice doesn't get the right padding when client side rendered as the CSS is ordered differently. Very annoying.
Should not look like this.

fix(web): Fix padding on event slice with client-side render

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.ts
libs/clients/vmst/src/clientConfig.yaml

The API only supports `dateOfBirth` when children have been born. We do not have this data at the moment and will revist when we do.
Will revisit this field in another PR where integrating custody API from Þjóðskrá as well as connecting estimated dates of birth to national registry ids of born children.
So that we do not get an error when sending applications for unborn children.

fix(parental-leave): Send an empty true date of birth

---

apps/api/src/app/app.module.ts
libs/api/domains/auth/src/lib/resolvers/delegation.resolver.ts
libs/api/domains/identity/src/lib/identity.module.ts
libs/api/domains/identity/src/lib/identity.resolver.ts
libs/api/domains/identity/src/lib/identity.service.ts
libs/api/domains/national-registry-x-road/src/index.ts
libs/api/domains/national-registry-x-road/src/lib/nationalRegistryXRoad.module.ts

Move identity domain to use the new national registry service over x-road. 
This is to embrace the future and provide consistent delegations in all our environments.
Delegation API requests would call both the old Natreg API and the new Natreg API (in different layers). But the two api's have quite different data on dev, causing a lot of issues.

feat(api): Use natreg over x-road in identity domain

---

nx.json
scripts/schemas.js
workspace.json

Fixes #4533 
Schema generation was sometimes failing unpredictably which I think was a combination of two things which are fixed with this PR:
* Default NX cache is stored under `node_modules/.cache` which gets stored in the GitHub Actions cache as part of the node_modules cache we create
* The flag `--skip-nx-cache` was not propagated in nested `nx run ...` executions
I suspect these two things in combination created situations where parts of the schema were retrieved from a cache where they should have been generated.
Consistent, clean schema generation.

fix: Schema generation more reliable

---

apps/web/hooks/useLinkResolver/useLinkResolver.ts

The contact link on the frontpage got its resolved slug as `/stafraent-island/hafa-samband` from the linkResolver's `aboutPage` rule. A 404 redirect can't be written for `/stafraent-island/hafa-samband` in contentful since the page type is `aboutPage` and resolves back to itself.

fix: Updated the LinkResolver to prepend '/s' to the aboutPage type

---

libs/application/templates/complaints-to-althingi-ombudsman/src/fields/ComplaintOverview/ComplainedFor.tsx
libs/application/templates/complaints-to-althingi-ombudsman/src/fields/ComplaintOverview/Complainee.tsx
libs/application/templates/complaints-to-althingi-ombudsman/src/fields/ComplaintOverview/ComplaintOverview.tsx
libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanApplication.ts
libs/application/templates/complaints-to-althingi-ombudsman/src/lib/dataSchema.ts
libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/overview.ts

https://app.clickup.com/t/nbduny
Show attachments in overview plus minor mobile overview adjustments
So that the user can see what documents are attached to the application

feat(ctao): Attachments in overview

---

apps/services/endorsements/api/src/app/modules/endorsementList/e2e/openEndorsementList/openEndorsementList.spec.ts
apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.controller.ts

Fix for Ministry of justice can't open list
- Removed owner validation for open
- Allow Ministry of justice to open list

fix(services-endorsements-api): Removed owner validation

---

apps/web/screens/Organization/Services.tsx

The services screen was missing implementation of children links in nav list.
Requested by Sýslumenn webmaster

feat(web): Add missing children links to services screen nav list

---

apps/web/components/Organization/Slice/EventSlice/EventSlice.treat.ts
apps/web/components/Organization/Slice/EventSlice/EventSlice.tsx

Fixing CSS styles for the event slice.
The event slice does not render properly currently.
This was hot-fixed to the last release, but did not end up in the main branch, so we need to hot-fix again.

fix(web): Fix event slice styles

---

libs/content-search-toolkit/src/services/elastic.service.ts

Bulk import is failing due to large payload size
- Reduce chunk size to a value that is unlikely to cause further issues
- Allow search indexer to continue to work normally

fix(services-search-indexer): Reduce bulk import chunk size

---

libs/application/templates/driving-assessment-approval/src/fields/StudentLookupField.tsx

When the teacher hasn't filled out a student nationalId, the lookup will crash and burn. This should address and fix that issue.

fix(application-template-driving-assessment): fixing an undefined value in the student lookup

---

apps/judicial-system/web/messages/Core/signedVerdictOverview.ts
apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/AppealSection/AppealSection.spec.tsx
apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/AppealSection/AppealSection.treat.ts
apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/AppealSection/AppealSection.tsx
apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverviewForm.tsx

https://app.asana.com/0/1199153462262248/1200339992478442
Inform court if case is appealed in court on signed verdict overview page
We inform the court if a case is appealed after a verdict so it makes sense to do so also if the case is appealed in court.

feat(judicial-system): Inform court if case is appealed in court on signed verdict overview page

---

apps/service-portal/src/components/ContentBreadcrumbs/ContentBreadcrumbs.tsx
libs/service-portal/core/src/lib/messages.ts
libs/service-portal/core/src/lib/navigation/masterNavigation.ts
libs/service-portal/core/src/lib/navigation/paths.ts
libs/service-portal/settings/access-control/src/index.ts
libs/service-portal/settings/access-control/src/screens/AccessControl/AccessControl.tsx
libs/service-portal/settings/access-control/src/screens/GrantAccess/GrantAccess.tsx

https://www.notion.so/Unable-to-select-from-bread-crumbs-e87205e51edd4aa8b92f8d967309caca
* Fix breadcrumbs in general to support route params
* Add breadcrumbs for child routes of access-control
* Service portal didn't support route params before, and was leaving out breadcrumbs for those routes.

feat(delegation): fix breadcrumbs

---

.github/workflows/pullrequest.yml

It is very noisy and we cannot suppress individual packages 
Get rid of it being in the critical path to delivery in favour of dependabot which is much more fine grained and is not blocking delivery pipelines.
Predictability

chore(ci): Disabling `npm audit` since it is hard to manage and not that helpful

---

libs/island-ui/core/src/lib/Checkbox/Checkbox.treat.ts
libs/island-ui/core/src/lib/Checkbox/Checkbox.tsx
libs/shared/form-fields/src/lib/CheckboxController/CheckboxController.spec.tsx

Fixes: https://github.com/island-is/island.is/issues/4027
Implements: https://www.notion.so/Please-go-over-UI-of-scope-selection-e5ee740a78944dd0b6d97eb162ac0ea6
Make semibold text occupy space in order to avoid content jumps

fix(ui): fix content jumps for checkbox toggle

---

libs/service-portal/settings/access-control/src/screens/GrantAccess/GrantAccess.treat.ts
libs/service-portal/settings/access-control/src/screens/GrantAccess/GrantAccess.tsx
libs/shared/form-fields/src/lib/InputController/InputController.tsx

https://www.notion.so/No-action-when-kennitala-is-wrong-5a15ea7d34924bb6aa48fb8a5a7762ee
https://www.notion.so/A-gangshafi-field-seems-to-be-editable-0e7780b0bbe34fc5949674ab449c10f5
* Better error handling for incorrect nationalId
* Fix UX when fetching and displaying user's name based on nationalId

feat(delegation): ux fix for nationalId input in grant access

---

libs/api/domains/education/src/lib/education.service.ts

fix(service-porta-education): preventing siblings from being able to see each others' grades

---

libs/file-storage/src/lib/file-storage.service.ts

Fixing an error where the filename is formatted so that the file extension is removed causing all files to become binary files.
Its breaking the application for sjukratryggingar
Before:
After:

fix(file-uploade): Fix file upload so that the file extension isnt removed on filename formatting.

---

libs/application/templates/party-application/src/fields/SupremeCourtOverview/index.tsx
libs/application/templates/party-application/src/lib/PartyApplicationTemplate.ts

Currently admins of the party application don't see the party name and get wrong info in exports.
- Made admin page use external data fields
- Fixed constituency validation logic

fix(application-templates-party-application): Fix admin overview

---

apps/services/endorsements/api/src/app/modules/endorsementValidator/validators/minAgeByDate/minAgeByDateValidator.service.ts

Currently we remove one year if birthday is before event date, this should happen if birthday is after event date.
- Turned the check arrow around
- Updated comments to reflect this
- This is the intended behaviour

fix(services-endorsements-api): Fix minAgeAtDate age check

---

libs/service-portal/family/src/components/FamilyMemberCard/FamilyMemberCard.tsx

Remove family relation display on family member cards
Occasionally the user will get an incorrect family relation displayed.

fix(service-portal): remove labels on family member cards

---

libs/application/templates/party-application/src/fields/EndorsementListSubmission/index.tsx
libs/application/templates/party-application/src/lib/PartyApplicationTemplate.ts

Currently the system assigns a new endorsement list to the application when a list is rejected.
- Made the reject action point to the rejected state
- Made table update when data is refreshed

fix(application-templates-party-application): Fix rejected state

---

libs/application/templates/party-application/src/lib/PartyApplicationTemplate.ts

People can't endorse lists once they have been rejected
- Allowed people to endorse rejected lists
- Made application not clear assignees when leaving states
- Clearing assignees prevents admins from accessing list

fix(application-templates-party-application-api): Party application accepted screen

---

apps/services/endorsements/api/infra/endorsement-system-scripts-update-metadata.ts
apps/services/endorsements/api/migrations/20210909175011-arnorhs.js
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

Updating meta data only for the temporary voter registry

fix(endorsement-system-api): limiting queries to national registry

---

apps/web/screens/Organization/Syslumenn/Auctions.tsx

- Show real estate respondents and petitioners in UI
- Add filter for auction type "Sale closed".
- Update filter "All open auctions" to hide auctions of type "Sale closed".
- Show timestamp when data was fetched.
- Remove office location Bolungarvik
For improved UI/UX.

feat(web): Syslumenn auctions - Improved filters and UI

---

libs/island-ui/core/src/lib/RadioButton/RadioButton.treat.ts
libs/island-ui/core/src/lib/RadioButton/RadioButton.tsx

Removed `RadioButton` error style that was left behind after changes in this PR https://github.com/island-is/island.is/pull/4625
The class was setting `padding-bottom: 0` on the label when it had an error, when the padding should just stay the same.
QA

fix(island-ui): RadioButton error state

---

libs/application/templates/data-protection-complaint/src/fields/ComplaineeRepeater/ComplaineeRepeaterItem.tsx
libs/application/templates/data-protection-complaint/src/forms/ComplaintForm.ts
libs/application/templates/data-protection-complaint/src/lib/dataSchema.ts
libs/application/templates/data-protection-complaint/src/lib/messages/error.ts

https://app.clickup.com/t/1e0y6wq
- Added border-radius to custom component in company info repeater
- Added `defaultValue=""` to input controllers so that correct error message is shown
- Added special error message for nationalId format
- Changed all usages of `.nonempty()` in data-schema to `.refine()`, so that correct error message is shown.
QA / Design requirement

fix(dpac): Tweaks to data schema and company info screen

---

libs/service-portal/assets/src/screens/AssetsVehicles/AssetsVehicles.tsx
libs/service-portal/wip/src/screens/FinanceWIP/FinanceWIP.tsx
libs/service-portal/wip/src/screens/SettingsWIP/SettingsWIP.tsx

Change the namespaces of a couple of translation strings.
Unable to properly change the translation strings because of misplaces namespaces. It would result in deprecating some strings I would rather not deprecate.

fix(service-portal): use proper translation namespaces for wip section

---

libs/api/domains/license-service/src/lib/client/driving-license-client/drivingLicenseService.api.ts
libs/api/domains/license-service/src/lib/client/driving-license-client/genericDrivingLicense.type.ts
libs/api/domains/license-service/src/lib/licenceService.type.ts

* feat(license-service): map status code from verifyPkpass API result to client
* feat(license-service): skip logging if 400 error with status in message
* Update libs/api/domains/license-service/src/lib/licenceService.type.ts
Co-authored-by: Már Örlygsson <mar.nospam@anomy.net>
* Update libs/api/domains/license-service/src/lib/licenceService.type.ts
Co-authored-by: Már Örlygsson <mar.nospam@anomy.net>
* Update libs/api/domains/license-service/src/lib/licenceService.type.ts
Co-authored-by: Már Örlygsson <mar.nospam@anomy.net>
* Update libs/api/domains/license-service/src/lib/licenceService.type.ts
Co-authored-by: Már Örlygsson <mar.nospam@anomy.net>
* Update libs/api/domains/license-service/src/lib/client/driving-license-client/drivingLicenseService.api.ts
Co-authored-by: Már Örlygsson …

feat(license-service): map status code from verifyPkpass API (#5010)

---

libs/application/templates/driving-assessment-approval/src/fields/Congratulations.tsx
libs/application/templates/driving-assessment-approval/src/lib/DrivingAssessmentApprovalTemplate.ts
libs/application/templates/driving-assessment-approval/src/lib/messages.ts

updating translation string keys for Contentful and adding a description to the confirmation box

feat(application-templates-driving-assessment-approval): updating translations

---

libs/island-ui/core/src/lib/InputFileUpload/InputFileUpload.tsx

Add prop `hideIcons` to `InputFileUpload` component that controls whether or not icons, such as `remove file` or `retry upload` should appear. This prop is set to false by default so this change has no effect where this component is currently being used.
You should be able to upload files without these controls if you want.

feat(island-ui): Add the ability to hide icons in InputFileUpload component

---

libs/application/templates/parental-leave/src/fields/Rights/RequestRightsRadio.tsx

Initialize requestDays with existing answer.
Add error to the field if either radio option is not selected.
If applicant left the application and returned later. Navigated to previous steps and back again through RequestRights, without changing it value, it resulted in the error state `requestDays: 0, isRequesting: "yes"`.
If the applicant was going through new application and no value is selected in RequestRights and he clicked "Áfram" nothing happened and no error was shown. Now the forms highlights the fields with error message.

fix(parental-leave): Request rights were missing proper initialization

---

libs/application/templates/driving-license/src/dataProviders/EligibilityProvider.ts
libs/application/templates/driving-license/src/dataProviders/QualityPhotoProvider.ts
libs/application/templates/driving-license/src/fields/QualityPhoto/QualityPhoto.tsx
libs/application/templates/driving-license/src/forms/application.tsx
libs/application/templates/driving-license/src/lib/constants.ts
libs/application/templates/driving-license/src/lib/messages.ts

Mock data for driving license application itself.

feat(application-templates-driving-license): Enable fake data at the beginning of the application flow

---

apps/judicial-system/backend/src/app/formatters/rulingPdf.ts

https://app.asana.com/0/1199153462262248/1200879471149033
Fix to☝️ 
Bug

fix(judicial-system): Ignores white-spaces in empty attendees field

---

libs/service-portal/core/src/lib/navigation/masterNavigation.ts
libs/service-portal/core/src/lib/navigation/paths.ts
libs/service-portal/finance/src/index.ts
libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx
libs/service-portal/wip/src/index.ts

Hotfix for: https://github.com/island-is/island.is/pull/5108
* Add an empty state for the user when there are no "Status transactions"
* Fix breadcrumbs on the finance module
* Empty state on status transactions is now totally empty
* The finance breadcrumbs are a little bit wonky because of the WIP finance that users who are not within the feature flag see. Changed the setup a bit.

feat(service-portal): Hotfix. Empty state for status transactions.

---

libs/application/core/src/types/Fields.ts
libs/application/ui-fields/src/lib/RadioFormField/RadioFormField.tsx
libs/shared/form-fields/src/lib/RadioController/RadioController.tsx

- Added the option to disable a single radio option. You can still disable the whole thing as before as well.
- Added the missing prop `backgroundColor` to `RadioController` inside `RadioFormField`
Needed to be able to set a single radio option as disabled. Also could not set the background white since the prop was missing in `RadioFormField`

feat(application-core/ui-fields): add props to buildRadioField

---

apps/air-discount-scheme/backend/esbuild.json

Reverting #5135 
Adding swagger distribution files instead to work with `fastify-swagger`
Top: feature-deploy of this PR
Bottom: current main with #5135
This PR on dev via feature-deploy

fix(air-discount-scheme): Included swagger distribution files in esbuild

---

apps/financial-aid/api/src/app/modules/application/application.resolver.ts
apps/financial-aid/api/src/app/modules/application/dto/allApplications.input.ts
apps/financial-aid/api/src/app/modules/application/dto/applications.input.ts
apps/financial-aid/api/src/app/modules/application/dto/index.ts
apps/financial-aid/api/src/services/backend.ts
apps/financial-aid/backend/src/app/modules/application/application.controller.ts
apps/financial-aid/backend/src/app/modules/application/application.service.ts
apps/financial-aid/web-veita/graphql/sharedGql.ts
apps/financial-aid/web-veita/src/routes/ApplicationsOverview/applicationsOverview.tsx
apps/financial-aid/web-veita/src/utils/navigation.ts
libs/financial-aid/shared/src/lib/enums.ts
libs/financial-aid/shared/src/lib/formatters.ts

https://app.asana.com/0/1201017282841966/1201079906615276
Added a enum ApplicationStateUrl 
When getting all applications, takes input that is ApplicationStateUrl 
Filters in backend instead of client 
When routing between tables, we get the newest
Put the filter rather on the backend than in client

fix(financial-aid): Moving filtering of applications from client to backend

---

apps/application-system/api/docker-compose.base.yml
apps/application-system/api/docker-compose.ci.yml
apps/application-system/api/docker-compose.dev.yml
apps/application-system/api/src/environments/environment.ts

Adding `redis_cluster` to the `docker-compose` setup for `application-system-api`.
In the upgraded Nx repo [branch](https://github.com/island-is/island.is/tree/core/upgrade-nx) it breaks the test that the app is unable to connect to the redis cluster.

chore(application-system-api): Enabling redis cluster in CI for application-system-api

---

apps/web/pages/_error.tsx
apps/web/screens/queries/Url.tsx
libs/cms/src/lib/generated/contentfulTypes.d.ts
libs/cms/src/lib/models/url.model.ts

Allowing a fallback redirect with the `explicitRedirect` on 404redirects (url) in contentful.
We're refactoring our content models. In that effort we wish to remove `aboutSubPage` but it is still being used for 404redirects. The superseding `organizationSubPage` does not store slugs in the same way as `aboutSubPage`.
One solution is to simply allow explicit redirects as a fallback if `page` is not provided.

feat(web): Ability to have explicit redirect links

---

apps/judicial-system/backend/src/app/formatters/rulingPdf.ts

https://app.asana.com/0/1199153462262248/1201061586055548/f
Use 'Kærði/a' instead of 'Varnaraðili' in restriction cases PDF

fix(judicial-system): Use 'Kærði/a' instead of 'Varnaraðili' in restriction cases PDF

---

libs/application/templates/parental-leave/src/fields/PeriodPercentage/PeriodPercentage.tsx

When creating the first period the user is asked to select when it should start, on:
- Estimated date of birth
- Real date of birth
- Specific date
For all other periods they can only start on specific dates.
This PR makes sure that all of the periods created after the first period get a default value for `firstPeriodStart` to equal `specificDate`
If the user deletes the first period they may get a validation error that the first period is missing a value for `firstPeriodStart`. By having a default value on all periods we will not run into this situation.

chore(parental-leave): Make sure all periods have a default value for firstPeriodStart

---

workspace.json

Updating port for e2e baseUrl in `application-system-form-e2e`
`e2e` task is failing because ` application-system-form` starts on port 4242 but e2e was expecting 4200

test(application-system-form): Configure port on baseUrl for e2e test.

---

libs/application/templates/driving-license/src/dataProviders/FeeInfoProvider.ts

returning message descriptor on fee info provider when there's an error - right now the application gets destroyed if there's an error in FJS

fix(application-template-driving-license): returning message descriptor on error

---

apps/services/auth-public-api/src/app/modules/delegations/delegations.controller.ts
apps/services/auth-public-api/src/app/modules/delegations/test/integration/delegations.controller.spec.ts
apps/services/auth-public-api/src/app/modules/resources/api-scope.controller.ts
apps/services/auth-public-api/src/app/modules/resources/identity-resources.controller.ts
apps/services/auth-public-api/src/app/modules/translation/translation.controller.ts
apps/services/auth-public-api/src/openApi.ts

Removing `/public` from controllers paths in `auth-public-api`.
Adding server option to the OpenAPI document.
To open for the Swagger UI and OpenAPI document for auth-public-api.
First attempt of testing the Ingress rewrite-target rule, which will be configured manually against the dev kubernetes cluster before configuring the Helm charts.
https://github.com/kubernetes/ingress-nginx/blob/main/docs/examples/rewrite/README.md#rewrite-target

feat(auth-public-api): Removing /public for service to let ingress configure

---

apps/judicial-system/backend/src/app/formatters/requestPdf.ts
apps/judicial-system/backend/src/app/messages/requestPdf.ts
apps/judicial-system/web/src/utils/useFormHelper.ts

https://app.asana.com/0/1199153462262248/1201261137719276/f
- Remove defender section if no defender chosen
- Move all strings in requestPdf to Contentful
- Minor string changes
- Minor bug fix where isValid export was missing from useFormHelper
Iteration on request Pdf

chore(judicial-system): Iterate request pdf

---

libs/application/templates/accident-notification/src/utils/hasMissingDocuments.ts

Only check police report when accident was fatal
Current implementation results in a bug.

fix(accident-notification): Fix edge case for when accident wasnt fatal

---

yarn.lock

This fixes security vulnerability:
https://github.com/island-is/island.is/security/dependabot/yarn.lock/is-svg/open

chore(core): Upgrade postcss-svgo to remove is-svg dependency

---

apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepThree/StepThreeForm.tsx

https://app.asana.com/0/1199153462262248/1201371123228010/f
Only display isolation demand for custody cases
Fix, isolation demand does not apply for travel ban case type
Before:
After:

fix(judicial-system): Only display isolation demand for custody cases

---

libs/island-ui/core/src/lib/Grid/GridColumn/GridColumn.css.ts

Remove object from gridcolumn classname on order class.
When developing locally, `[object_Object]` will be added to the order classname in gridColumn.
As a result of the `orderRange` "object from the const `order`. Thus you can not really use the order property while developing on localhost.
I did not see any reason for the order object to be placed as a part of the `order_` class.

fix(island-ui): gridcolumn classname

---

apps/judicial-system/backend/src/app/formatters/rulingPdf.ts
apps/judicial-system/backend/src/app/messages/rulingPdf.ts

https://app.asana.com/0/1199153462262248/1201386801040005/f
* Remove police case number from ruling pdf
* Add case number string to Contentful
Before:
After:

chore(judicial-system): Remove police case number from ruling pdf

---

libs/service-portal/endorsements/src/lib/messages.ts
libs/service-portal/endorsements/src/screens/PetitionsAdmin/PetitionsAdmin.tsx
libs/service-portal/endorsements/src/screens/PetitionsTable/PetitionsTable.tsx
libs/service-portal/endorsements/src/screens/queries.ts

Admin now has overview over what lists have been locked by admin. And CSV downloads all petitions belonging a given list not just currently paginated endorsements.

fix(service-portal): General petition admin overview of locked lists and csv fix

---

apps/web/components/Regulations/useRegulationIndexer.ts

Some Regulation text-bodies trigger a bug in the TOC/index generator, resulting in a wall of titles.
This affects at least two very recent regulations.

fix(regulations/web): HOTFIX)Prevent over-extending index titles

---

apps/judicial-system/web/src/routes/Court/InvestigationRequest/CourtRecord/CourtRecordForm.tsx
apps/judicial-system/web/src/routes/Court/InvestigationRequest/Ruling/StepOne/RulingStepOneForm.tsx
apps/judicial-system/web/src/utils/validate.ts

Fixes a bug where prosecutorDemands were not being validated on rulingStepOne screen. This is a regression from https://app.asana.com/0/1199153462262248/1201312869487978/f. We forgot to move the validations in investigation cases
It's a bug
https://user-images.githubusercontent.com/3789875/143410680-fae2ec60-f5ae-444c-acee-78b8e8613b5e.mov
https://user-images.githubusercontent.com/3789875/143410532-4f103869-66d7-44e9-8954-a00ba3607a3b.mov

fix(judicial-system): prosecutorDemands not being validated on rulingStepOne screen

---

libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.service.ts

re-adding the return statement I idiotically removed when trying to fix the consistency of the action

fix(template-api-modules-driving-license): re-adding the return statement

---

apps/judicial-system/web/src/components/PageLayout/PageLayout.tsx
apps/judicial-system/web/src/components/PageLayout/utils/index.ts
apps/judicial-system/web/src/routes/Shared/Requests/Requests.tsx
apps/judicial-system/web/src/utils/sections.ts

https://app.asana.com/0/1199153462262248/1201408210753231/f
Fix: validate that court(judge or registrar) has permission to open on valid court steps
For security reasons court (judge or registrar) needs permission to open a case

fix(judicial-system): Fix: Add court permission to step validation

---

apps/web/components/Organization/Slice/TimelineSlice/TimelineSlice.tsx

The English website for `/en/o/digital-iceland` is throwing 500 errors
https://island.is/en/o/digital-iceland
When getting months for future, it cannot find anything in this future. Fallback of index `0` given but then the filter filters out with `>0`, sometimes giving it nothing to return

fix(web): Timeline with no future causes errors

---

libs/api/domains/national-registry-x-road/src/lib/nationalRegistryXRoad.module.ts

Extends timeout for national registry api since it is timing out on prod

fix(national-registry): Extends timout period

---

libs/island-ui/core/src/lib/Navigation/Navigation.tsx

https://island.is/s/stafraent-island is showing two footers for whatever reason. I'm not sure what the cause is but it seems to have something to do with `reakit/MenuButton` and nesting another button there within causing strange things to happen. For now this seems to "fix" it...

fix(web): fix double footer

---

apps/judicial-system/backend/src/app/modules/notification/notification.service.ts

https://app.asana.com/0/1199153462262248/1201437594297195/f
- Sends email to prison when custody cases are accepted partially.
This was a bug.

fix(judicial-system): Fixes prison email in partially accepted custody cases

---

libs/api/domains/national-registry-x-road/src/lib/nationalRegistryXRoad.module.ts

Extending timeout for national registry api.
Api is timing out on prod when it needs a cold start.

fix(national-registry): Extends timout period (#5777)

---

libs/api/domains/education/src/lib/s3.service.ts
libs/service-portal/education-license/src/index.ts
libs/service-portal/education-license/src/screens/EducationLicense/components/LicenseCards/LicenseCards.css.ts
libs/service-portal/education-license/src/screens/EducationLicense/components/LicenseCards/LicenseCards.tsx

Use two step process for downloading, i.e.
1. first request an e-sealed documentation
2. download it
The previous implementation violates the Content Security Policy directive: "connect-src 'self'" which was newly set and started to break the downloads.

fix(license): Use two step method for downloading to bypass Chrome security standards

---

.github/actions/unit-test/action.yml
.github/workflows/config-values.yaml
.github/workflows/pullrequest.yml
.github/workflows/push.yml

To maybe get rid of API rate limiting... This should be temporary until either https://github.com/actions/toolkit/pull/947 or https://github.com/actions/cache/pull/679 are accepted and released

fix(ci): Use temporary published version of island-is/cache

---

libs/clients/regulations/src/lib/regulations.ts

Graphql caching is behaving strangely, these requests are being cached in too many places.
Regulation data and search results are getting cached for days on end, resulting in badly outdated information.
FWIW, The up-stream API sets nicely behaved HTTP Cache-Control headers.

fix(regulations/web): remove cacheOptions from RegulationsService

---

libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

☝️ 
So that it works for users that fetched data before the new data provider arrived

fix(parental-leave): Fetch spouse from deprecated provider if not found in person provider

---

libs/island-ui/core/src/lib/Select/Components/index.tsx
libs/island-ui/core/src/lib/Select/Select.css.ts
libs/island-ui/core/src/lib/Select/Select.tsx

Add a createable ReactSelect component into island-ui. 
To create a createable ReactSelect component, you'd pass down a `isCreateable` prop (default set to false) to the existing Select component and it will render a creatable version of that component. I also added a fix for a minor bug where we were rotating the icon, no matter what the icon was. I think it only makes sense to rotate the icon if it's set to chevronDown (default).
The judicial-system project needs a createable ReactSelect component.
https://user-images.githubusercontent.com/3789875/144438203-5b5cf3f0-1fe3-43f8-82f2-f6b5ecfca3cd.mov

feat(island-ui): Add a createable ReactSelect component

---

.github/CODEOWNERS
libs/api/domains/assets/src/lib/api-domains-assets.service.ts
libs/service-portal/assets/src/screens/RealEstateAssetDetail/RealEstateAssetDetail.tsx

Missing data in detail view of properties: Staðfang & Sveitafélag
Bonus: Adding hugsmidjan as codeowners for the assets service.
Bugfixing

fix(service-portal): missing data in detail view properties

---

workspace.json

See title.
This test is super flaky, not providing value at the moment and not much activity in creating this type of e2e tests.
We need to have a less flaky CI, at least for this release cycle. Would be great to revert this when we start creating this type of e2e tests and have a way to fix the actual issue (`nx run application-system-form:build:production` exiting with status code 1 and no logs).

chore(ci): Skip flaky application-system-form-e2e test

---

SUMMARY.md
jest.config.js
libs/feature-flags/README.md
libs/feature-flags/src/lib/configcat.ts
libs/feature-flags/src/lib/types.ts
libs/infra-nest-server/src/lib/buildOpenApi.ts
libs/nest/feature-flags/.eslintrc.json
libs/nest/feature-flags/README.md
libs/nest/feature-flags/jest.config.js
libs/nest/feature-flags/src/index.ts
libs/nest/feature-flags/src/lib/feature-flag.client.ts
libs/nest/feature-flags/src/lib/feature-flag.config.ts
libs/nest/feature-flags/src/lib/feature-flag.decorator.ts
libs/nest/feature-flags/src/lib/feature-flag.guard.spec.ts
libs/nest/feature-flags/src/lib/feature-flag.guard.ts
libs/nest/feature-flags/src/lib/feature-flag.module.ts
libs/nest/feature-flags/src/lib/feature-flag.service.ts
libs/nest/feature-flags/tsconfig.json
libs/nest/feature-flags/tsconfig.lib.json
libs/nest/feature-flags/tsconfig.spec.json
libs/react/feature-flags/src/lib/context.tsx
nx.json
tsconfig.base.json
workspace.json

A feature flag library for our APIs. Wraps the low level API to provide support for our user objects, consistent with the `@island.is/react/feature-flags` library.
Also includes a NestJS guard to wrap entire endpoints and resolvers behind feature flags.
[Readme](https://github.com/island-is/island.is/blob/nest-feature-flag/libs/nest/feature-flags/README.md)
To make it easier to use feature flags in our APIs.

feat(core): Feature flag library for Nest APIs

---

libs/api/domains/auth/src/lib/resolvers/delegation.resolver.ts
libs/api/domains/identity/src/lib/identity.service.ts

When person is not found in Þjóðskrá the person is null which causes a error. This returns null instead.
The validTo date can be null from the OpenAPI spec so checking for falsy value and returning undefined if it is.
To avoid the errors otherwise caused.

fix(api): Fixing possbile null and undefined values in auth and identity domains

---

apps/application-system/form/src/auth.ts
apps/service-portal/src/auth.ts
libs/auth/scopes/src/index.ts
libs/auth/scopes/src/lib/api.scope.ts

Add new scopes to our clients.
To minimize disruption during the next release. This way, signed in users will already have access tokens with the scopes they need when we deploy new UIs and APIs which check for those scopes.

chore(auth): Add new scopes to our clients

---

libs/api/domains/auth/src/lib/resolvers/delegation.resolver.ts

Fields can be null if no result is found in NationalRegistry, or the service is offline.
Missing nullable config for GQL schema.

fix(api): Adding nullable true for resolve fields in auth domain.

---

libs/service-portal/settings/access-control/src/screens/Access/Access.tsx
libs/service-portal/settings/access-control/src/screens/AccessControl/components/Accesses/Accesses.tsx
libs/service-portal/settings/access-control/src/screens/GrantAccess/GrantAccess.tsx
libs/shared/components/src/auth/UserMenu/UserDelegations.tsx

When no identity is found the GQL returns null object so adding handling for `onComplete` if `identity` was not found to display the toast error message.
Fixing typescript compile errors when `to` and `from` fields on `delegation` are missing due to errors in `identity` service.
Fixing the regression when returning null instead of throwing error when identity was not found in the identity service.

fix(service-portal): Fixing toast error handling in GrantAccess and typescript issues for delegations

---

apps/services/endorsements/api/src/environments/environment.ts

The National registry soap config was set to the dev config, causing errors on dev and staging.
This mistake was made in this pr https://github.com/island-is/island.is/pull/5752/
Errors:
https://app.datadoghq.eu/logs?query=service%3Aendorsement-system-api%20env%3Astaging%20-status%3A%28warn%20OR%20info%29&cols=host%2Cservice&event=AQAAAX2aKzhFL6ZXRQAAAABBWDJhSzBtT0FBQi11MGZyeUZzRkl3QVc&index=%2A&messageDisplay=inline&stream_sort=desc&from_ts=1638809302375&to_ts=1638982102375&live=true

fix(endorsement-system-api): National registry soap prod config

---

apps/judicial-system/web/src/components/RulingInput/RulingInput.tsx

https://app.asana.com/0/1199153462262248/1201423192590376/f
Only autofill ruling on initial render. We were autofilling every time workingCase changed, making it impossible to edit the autofilled ruling
This is a bug. This fixes a broken e2e test.
https://user-images.githubusercontent.com/3789875/145368031-5a5ffcb0-aab5-4c4a-a511-168d1d0060a2.mov
https://user-images.githubusercontent.com/3789875/145367691-1072e3bb-3536-4898-be25-d39e0984f0a5.mov

fix(judicial-system): Only autofill ruling on initial render

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/screens/Organization/Home.tsx

We've been asked to show this message to users via an alert on all Syslumenn pages, implemented as a quick fix, in order to get this live ASAP. The message disappears after December 13th. Then we will simply revert this PR to get rid of this quick fix in future releases.
Syslumenn offices will be closed on Monday December 13th.

feat(web): Syslumenn / Alert quick fix

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/screens/Organization/Home.tsx

Cherry picked the merge commit for #5942 from `main`.
We've been asked to show this message to users via an alert on all Syslumenn pages, implemented as a quick fix, in order to get this live ASAP. The message disappears after December 13th. Then we will simply revert this PR to get rid of this quick fix in future releases.
Syslumenn offices will be closed on Monday December 13th.

feat(web): Hotfix - Syslumenn / Alert quick fix

---

apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/CaseFiles/CaseFilesForm.tsx
apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepFive/StepFiveForm.tsx
apps/judicial-system/web/src/utils/hooks/useS3Upload.ts

https://app.asana.com/0/1199153462262248/1201423192590376/f
Update state with new case files when uploading case files
In the new setup where we use the FormProvider to fetch cases and not on every page, there is a regression. The regression is that when we upload case files, we are not setting the state with the uploaded case file. This means that the case files are not visible in the client until you refresh. 
https://user-images.githubusercontent.com/3789875/145425549-289341e3-391e-4beb-b606-b723b99703d7.mov
https://user-images.githubusercontent.com/3789875/145425365-e70d3577-fca2-4129-84ca-26bce7c1ce98.mov

fix(judicial-system): Update state with new case files when uploading case files

---

apps/services/endorsements/api/src/app/modules/endorsement/e2e/bulkCreateEndorsement/bulkCreateEndorsement.spec.ts
apps/services/endorsements/api/src/app/modules/endorsement/e2e/createEndorsement/createEndorsement.spec.ts
apps/services/endorsements/api/src/app/modules/endorsement/endorsement.controller.ts
apps/services/endorsements/api/src/app/modules/endorsement/endorsement.service.ts
apps/services/endorsements/api/test/testHelpers.ts

Use national Registry v1 since xroad connection is causing errors

fix(endorsement-system-api): create endorsement on list gets fullName from national registry v1 and skips metadata steps

---

apps/judicial-system/web/messages/InvestigationCases/Court/rulingStepTwo.ts
apps/judicial-system/web/messages/RestrictionCases/Court/hearingArrangements.ts

https://app.asana.com/0/1199153462262248/1201452292299288/f
Fix Contentful strings ids
There were duplicate strings and they where in the wrong namespace

fix(judicial-system): Fix Contentful strings ids

---

apps/air-discount-scheme/web/components/AppLayout/AppLayout.tsx

Remove no longer used props from `Footer`

fix(air-discount-scheme-web): remove no longer used props from Footer

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/screens/queries/Organization.tsx
libs/cms/src/lib/generated/contentfulTypes.d.ts
libs/cms/src/lib/models/organizationPage.model.ts

We've added a new field in Contentful to store links to external systems for Organizations, This PR updates the Contentful types accordingly and renders these links on the Organization home page.
Sjúkratryggingar provide information portals for users to use (Réttindagátt and Gagnagátt) and we need to show links to those on the Organization home page.

feat(web): Organizations / Render new Contentful field External Links for Organization Page

---

libs/financial-aid/shared/src/lib/formatters.ts

https://app.asana.com/0/1201498198362488/1201405795061494
Displays month name instead of number in spouse email
Clearer copy

fix(fa): Spouse email - name instead of number

---

apps/services/user-notification/infra/user-notification.ts
charts/islandis/values.dev.yaml
charts/islandis/values.staging.yaml

grant ingress internal namespace
So the service can be reached through the internal ingress

chore(services-user-notification): grant namespaces

---

libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.service.ts
libs/application/templates/driving-license/src/dataProviders/CurrentLicenseProvider.ts
libs/application/templates/driving-license/src/forms/application.ts

when license selection is available, allow both types depending on the current license
tiny typing cleanup in submission step
To allow full-license application flow, when testing the new license flow

fix(application-templates-driving-license): fix license selection

---

.github/actions/cache/action.yml
.github/workflows/pullrequest.yml
.github/workflows/push.yml

island-is/infrastructure#1017
Bake in retry mechanism for the cache actions in our CI
It's not ideal that we need a second step after the cache action to check if it failed or not but composite actions do not yet support continue-on-error.
Because our cache action was failing with 500 every now and then.

ci: Retry if cache fails

---

apps/services/user-notification/src/main.ts

The openapi json schema path is generated by adding '-json' to the
swagger path. By having the swagger path on the root the openapi schema
is hosted on /-json which doesn't make any sense

fix(user-notification): Change to default swagger path

---

apps/skilavottord/ws/src/app/modules/auth/auth.guard.ts

Use request.auth instead of cookies
The cookies differ from prod to localhost

fix(skilavottord): use request.auth instead of cookies

---

.github/workflows/push.yml

push-success step was not checking if the tests failed or not

ci: Push workflow should fail if tests fail

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/screens/Organization/Home.tsx

Removing an alert message that was temporarily added last month (see PR #5942), where Syslumenn needed to show a certain message on their Organization page to Users, with short notice. This message is now outdated and therefor we're removing it.
Note: Ideally the merge commit of the before mentioned PR should simply have been reverted, but there were some conflicts when doing the revert. Since these are only a handful of lines in only two files, I manually removed the lines added in the original PR.
This code we're removing here was added with that in mind to simply remove it once the message was outdated.
For screenshots of the alter message begin removed, see screenshots in PR #5942 where this alert message was added.

feat(web): Syslumenn / Remove outdated temporary alert

---

apps/skilavottord/web/components/Header/Header.tsx
apps/skilavottord/ws/src/app/modules/auth/auth.guard.ts
apps/skilavottord/ws/src/environments/environment.ts

Use cookies to get user info from session token
The access token doesn't include user information (other than nationalId)

fix(skilavottord): use cookies to get user info from session token

---

apps/air-discount-scheme/backend/docker-compose.yml
apps/application-system/api/docker-compose.yml
apps/financial-aid/backend/docker-compose.yml
apps/gjafakort/application/docker-compose.yml
apps/icelandic-names-registry/backend/docker-compose.yml
apps/judicial-system/backend/docker-compose.yml
apps/reference-backend/docker-compose.yml
apps/services/auth-api/docker-compose.yml
apps/services/documents/docker-compose.yml
apps/services/endorsements/api/docker-compose.yml
apps/services/user-profile/docker-compose.yml
apps/skilavottord/ws/docker-compose.yml
libs/testing/containers/src/lib/testing-containers.ts

Change postgres docker image to one that supports ARM 64
So developers using apples new M1 chip are able to run tests

fix(infra): Change the postgres image for the m1 chip

---

.github/CODEOWNERS
libs/clients/syslumenn/README.md

Adding @island-is/kosmos-kaos and @island-is/stefna as code owners of recently refactored Syslumenn Client.
In PR #5973 the Syslumenn Client was refactored and moved from `/libs/api/domains/syslumenn/` to `/libs/clients/syslumenn/`, but the CodeOwners definition was not updated accordingly.

chore(syslumenn-api): CodeOwners / Add CodeOwners of refactored Syslumenn Client

---

apps/web/components/Organization/SearchBox/SearchBox.tsx

* Enable keyboard navigation via the searchbox on organization home pages (arrow keys, enter and tab)
* Before this change you could not press enter to search
* Before this change you could not use the arrow keys to cycle through search results
* Before this change you could not click on the magnifying glass to search
Here we see the searchbox on island.is/s/syslumenn right now (the search icon does not work):
https://user-images.githubusercontent.com/43557895/148384421-2ea5d148-fa7d-4386-a72d-27f71f9ca647.mp4
Here's what this change looks like, now you can click the search icon, use the arrow keys and enter to navigate:
https://user-images.githubusercontent.com/43557895/148385068-54a1f68c-f2b8-41f5-ac63-0d673d5a74cb.mp4

feat(web): Organization searchbox, show loading icon while typing, enabled english search and improved keyboard navigation

---

libs/island-ui/core/src/lib/DatePicker/DatePicker.css.ts
libs/island-ui/core/src/lib/DatePicker/DatePicker.stories.tsx
libs/island-ui/core/src/lib/DatePicker/DatePicker.tsx

[@island.is/island-ui: Datepicker needs to check if label is in order to place popper](https://github.com/island-is/island.is/issues/5226)
Refactor datepicker popper to use className instead of globalStyles and fix datepicker without label, it shouldn't happen, but it is possible to add empty string as a label.
Because it breaks datepicker when there is no label for it

fix(island-ui): fix datepicker without label

---

apps/services/user-notification/infra/user-notification.ts
charts/islandis/values.dev.yaml
charts/islandis/values.staging.yaml

Removing the health checks for the notification worker
Because the worker service doesn't require it and is getting shut down over and over

chore(user-notification): removing worker health check

---

libs/nest/audit/src/lib/audit.interceptor.spec.ts
libs/nest/audit/src/lib/audit.interceptor.ts
libs/nest/audit/src/lib/audit.service.spec.ts
libs/nest/audit/src/lib/audit.service.ts

When machine clients calls an API they by default don't have `nationalId` claim. This allows for audit logging also for machine clients without nationalId.
To support audit logging for machine clients.

feat(audit): Updating audit to support auditing from auth object without nationalId.

---

libs/cms/src/lib/environments/environment.ts

* If an organization slug changes then articles that are referencing that organization still point to the old slug
* This fixes the problem regarding no articles showing up on the organization services page due to a change of organization slug (since articles will then keep pointing to the old slug)

fix(web): Article organization slug not changing on sync

---

.github/CODEOWNERS

Simplify codeowners for aranja-related projects.
* Disconnect the application system from Aranja. Core will handle code reviews until a new code owner is found.
* Remove aranja codeownership from some other libs which we're not maintaining anymore.
* Aranja owns authentication folders and some parental leave folders (until another team takes over).
* Simplify to a single Aranja team to match internal structure.
To clean up github org.

chore(codeowners): Simplify aranja teams

---

apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
apps/judicial-system/backend/src/app/formatters/formatters.ts

https://app.asana.com/0/1199153462262248/1201514576356827/f
Use Sækjandi instead of Ákærandi in SMS notifications

chore(judicial-system): Use Sækjandi instead of Ákærandi in SMS notifications

---

libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/emailGenerators/drivingLicenseSubmittedEmail.spec.ts
libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/emailGenerators/drivingLicenseSubmittedEmail.ts

A few sanity fixes and addressing the issue where an applicant does not have an email set
To make it more clear that we need to add an email option into the application if we want people to receive emails

refactor(application-templates-driving-license): address & type fixes in email generator

---

apps/judicial-system/web/src/components/PageLayout/utils/index.ts
apps/judicial-system/web/src/utils/mocks.ts
apps/judicial-system/web/src/utils/sections.ts

https://app.asana.com/0/1199153462262248/1201634243867910/f
In extended investigation cases, the form stepper would use travel ban urls. 
It's a bug
https://user-images.githubusercontent.com/3789875/149126571-e5923234-f73d-4ab5-9f66-be077906f301.mov

fix(judicial-system): Fix form stepper navigation

---

apps/web/screens/Organization/NewsItem.tsx

Adds a link back to news overview in breadcrumbs.
Requested: https://app.asana.com/0/1199123945323117/1201539837995036

chore(web): add breadcrumb tag link back to news overview

---

apps/web/screens/Organization/Syslumenn/Auctions.tsx
apps/web/screens/queries/Organization.tsx
libs/api/domains/syslumenn/src/lib/models/syslumennAuction.ts
libs/clients/syslumenn/src/lib/syslumennClient.types.ts
libs/clients/syslumenn/src/lib/syslumennClient.utils.ts

* Respondents and petitioners were only showing up for real estate auctions
* Show where the auction takes place if that data is available
* We want to show the respondents and petitioners for both ships and real estates
* Recently, a new field `uppbodStadur` was added to Syslumenn API, to contain information about where the auction takes place. This field is currently always empty, but soon it will be fully implemented in the Syslumenn API. Therefore, in this PR, we are rendering this field in the view if it has a value.

feat(web): Syslumenn auctions, show respondents and petitioners for ships and real estate

---

apps/web/screens/Search/Search.tsx
apps/web/screens/ServiceWeb/Search/ServiceSearch.tsx

Forgot to normalize queries.
Some might say it would prove insightful to see when search queries are angry but data becomes that much more organized when standardized :stuck_out_tongue_closed_eyes:

fix(plausible): Normalize queries with lowercase

---

libs/application/templates/driving-license/src/fields/PaymentPending/PaymentPending.tsx
libs/application/templates/driving-license/src/fields/PaymentPending/hooks/useSubmitApplication.ts

zendesk issue: 15293 -- regression introduced in #6117
fixing event sent for aborting the payment flow
so people without a payment url are not redirected as if the application was sent successfully

fix(application-template-driving-license): fixing event sent for aborting the payment flow

---

apps/web/screens/Project/Project.tsx

* When you refresh the page then the browser will always select the first tab on a project subpage.
* This change makes it so that the selected tab is stored in the url, meaning that when you refresh the page now the tab you had selected stays selected.
* We want to fix this so that users can share links to a selected tab and also so that you don't lose the selected tab on refresh
Previously if you would refresh the page while on this tab, then the first tab would get selected

feat(web): Project subpage, same tab selected on refresh

---

.github/CODEOWNERS
libs/application/template-api-modules/src/lib/modules/templates/p-sign-submission/p-sign-submission.service.ts

Base 64 prefix was missing and adding codeowners.

fix(p-sign-application): Adding prefix to base64 string 

---

apps/service-portal/src/components/Sidebar/Sidebar.tsx

* fix: logo not visible in sidebar
* fix: remove clutter
HOTFIX 🔥  - No logo displayed in Service Portal in Safari

fix(service-portal): logo not visible in sidebar on safari (#6316)

---

libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
libs/api/domains/driving-license/src/lib/drivingLicense.spec.ts
libs/api/domains/driving-license/src/lib/drivingLicense.type.ts
libs/application/templates/driving-license/src/fields/EligibilitySummary/extractReasons.ts
libs/application/templates/driving-license/src/lib/messages.ts
libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
libs/clients/driving-license/src/lib/drivingLicenseApi.types.ts

This adds a reason for why RLS will not let people move forward in the application
People who are applying and get the generic notice that people need to contact Syslumenn, will now get a user-friendly message indicating what the error may be.

feat(api-domains-driving-license): adding the reason for rejection from RLS

---

apps/judicial-system/web/src/components/AccordionItems/PoliceRequestAccordionItem/PoliceRequestAccordionItem.tsx
apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/Defendant/Defendant.tsx

https://app.asana.com/0/1199153462262248/1201256841519082/f
Use correct route when leaving the defendant screen in investigation cases
It's a bug

fix(judicial-system): Use correct route when leaving the defendant screen in investigation cases

---

apps/judicial-system/backend/src/app/formatters/requestPdf.ts

https://app.asana.com/0/0/1201706705525298/f
- Uses plural heading when more than one defendant.
Bug

fix(judicial-system): Fixes defendant heading in request pdf

---

apps/judicial-system/web/src/components/SigningModal/SigningModal.tsx
apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/Accused/AccusedAppealDatePicker.tsx

https://app.asana.com/0/1199153462262248/1201514576356808/f
Route judges to signed verdict overview instead of the list of requests after signing a verdict
Better UX
https://user-images.githubusercontent.com/3789875/150959729-c6446f84-2fbb-4c7b-94cd-84fdb756ad77.mov

feat(judicial-system): Route judges to signed verdict overview instead of the list of requests after signing a verdict

---

apps/judicial-system/backend/src/app/formatters/requestPdf.ts
apps/judicial-system/backend/src/app/messages/requestPdf.ts

https://app.asana.com/0/1199153462262248/1201614149125822/f
Only show description in requestPDF if the description has been set and does not contain only spaces.
This field is optional.

chore(judicial-system): Description in requestPDF

---

libs/application/templates/data-protection-complaint/src/fields/ComplaintConfirmation/ComplaintConfirmation.css.ts
libs/application/templates/data-protection-complaint/src/fields/ComplaintConfirmation/ComplaintConfirmation.tsx
libs/application/templates/data-protection-complaint/src/lib/messages/confirmation.ts

[1w50rgz](https://app.clickup.com/t/1w50rgz)
Change text and added link
Because stakeholder wanted this change.

fix(dpac): changing confirmation screen

---

libs/application/templates/data-protection-complaint/src/fields/AgreementDescription.tsx
libs/application/templates/data-protection-complaint/src/forms/ComplaintForm.ts
libs/application/templates/data-protection-complaint/src/lib/messages/delimitation.ts
libs/application/templates/data-protection-complaint/src/lib/messages/error.ts

[1w505z7](https://app.clickup.com/t/1w505z7)
* Added more bullets to agreements part.
* Took away defaultMessage in sections (I don't know why it was like that..)
* Fixed error message.
Request from stakeholders

fix(dpac): changes to text

---

apps/web/screens/Organization/Syslumenn/Auctions.tsx

* Currently the datepicker on the Syslumenn auctions page isn't filtering the auctions by date
* We want to fix this since the live version makes all auctions dissapear when you change the date filter

fix(web): Syslumenn auctions, now you can filter by date, instead of everything dissapearing when you use the datepicker

---

infra/src/dsl/feature-values.spec.ts
infra/src/dsl/serialize-to-yaml.ts
infra/src/feature-env.ts

Feature service exclude was not working because they were excluded before the dependent services were calculated

fix(infra): Exclude user-notification try 2

---

libs/api/domains/user-profile/src/lib/userProfile.service.ts

Only create islykill settings if `email` OR `mobile` is in input
IF islykill fails when creating a user with only `locale` or `documentNotifications` an error will be thrown. And that error will not have any relevance for a user with only `locale` or `documentNotifications` in the input

fix(user-profile): Only create islykill settings if email OR tel is in input

---

libs/content-search-toolkit/src/queries/rankEvaluation.ts
libs/content-search-toolkit/src/queries/search.ts

Ranking metrics should not receive aggregations.
Was causing errors when accidentally introduced to aggregates.
More aggregations have been introduced and they're simply hitting the ranking evaluations by default.
Simple solution: flag for aggregations.

fix(content-search-toolkit): Aggregations removed from ranking metrics

---

apps/judicial-system/api/src/services/backend.ts

https://app.asana.com/0/1199153462262248/1201663486234663/f
Fix to ☝️ 
Bug

fix(judicial-system): Adds missing content type header to backend calls

---

apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverviewForm.tsx

https://app.asana.com/0/1199153462262248/1201777996978512/f
Switch registrar with type in last line of info card
Better readability

chore(judicial-system): Switch registrar with type in last line of info card

---

apps/financial-aid/web-veita/src/components/Profile/MunicipalityProfile.tsx
libs/financial-aid/shared/src/lib/enums.ts

https://app.asana.com/0/1201849781730850/1201814168458678
Add the missing aid row in the aid overview in Veita. Also fix some typos.
So the Admin can see all the aid types.
Before: 
After:

fix(fa): Add missing aid

---

libs/auth/react/src/lib/Authenticator/OidcSignIn.tsx

https://islandis.slack.com/archives/C01C7C3M2J3/p1645446634932849
Don't create a navigation entry in the browser history on the oidc-signin callback page. This page is just to handle arguments from the IDP. It is single use and should not be visited again.
So user's don't accidentally end up on an error page when navigating back and forth.

fix(react-auth): Use history.replace in oidc-signin callback page

---

apps/financial-aid/web-veita/src/components/NewUserModal/NewUserModal.tsx

https://app.asana.com/0/1201849781730850/1201814168458673
Check if the national id is already in use and display error message about that.
So the user know what the error is about.

fix(fa): Add error message when national id is already in use

---

libs/application/templates/financial-aid/src/fields/SummaryForm/SummaryForm.tsx
libs/application/templates/financial-aid/src/forms/Application.ts
libs/application/templates/financial-aid/src/forms/Spouse.ts
libs/application/templates/financial-aid/src/forms/Submitted.ts
libs/application/templates/financial-aid/src/forms/WaitingForSpouse.ts
libs/application/templates/financial-aid/src/lib/FinancialAidTemplate.ts
libs/application/templates/financial-aid/src/lib/constants.ts
libs/application/templates/financial-aid/src/lib/messages/summaryForm.ts
libs/application/templates/financial-aid/src/lib/utils.ts

##
https://app.asana.com/0/1201849781730850/1201645065535623
https://app.asana.com/0/1201849781730850/1201645065535613
- Renames routes to Routes
- Changes state of application on submission. Changes it to spouse if there is a spouse otherwise change it to submitted
- Adds blank spouse form
- Adds blank waiting for spouse form
- Adds blank submitted form
- Maps user to role for applicant and spouse
- Assigns application to spouse when application enters spouse state
- For naming convention
- We need it to handle different states in application
- Needed for spouse state
- Needed for applicant when application is in spouse state
- Needed for status page
- Access control for the application
- So spouse has access to application

feat(fa): State changes in AS on submission

---

apps/services/user-notification/infra/user-notification.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

Fix Hnipp not sending notifications
Contentful was throwing "Invalid Access Token" errors. Through debugging, it was realized that the cms service was sending production access key to `preview.contentful.com` instead of `cdn.contentful.com`. This PR adds the correct contentful hosts in dev, staging, and prod.

fix(cms): Add CONTENTFUL_HOST values to CMS env

---

apps/services/user-notification/src/app/modules/notifications/notifications.module.ts

Requests from user-notification worker to user-profile service are super
slow and are triggering the fetch-client circuit breaker, so we're
disabling it (for now) while debugging

chore(user-notification): disable fetch client circuit breaker

---

apps/judicial-system/backend/src/app/messages/notifications.ts
apps/judicial-system/backend/src/app/modules/case/case.service.ts

https://app.asana.com/0/1199153462262248/1201835567438802/f
👆 
Increased security.

chore(judicial-system): Stop sending signed ruling to court if it is already in S3

---

libs/api/domains/auth/src/lib/models/delegation.model.ts

Adds type for Personal Representative delegations.
Adds exhaustive type checking to ensure user get build errors when
adding new types to delegationType enum without adding new type.
New PersonalRepresentative delegation did not work with GraphQL since it was missing type.
This adds a new type.
In addition a exhaustive check was added do ensure this issue does not repeat.

fix(API): Fix missing graphql type for delegations

---

apps/judicial-system/backend/src/app/modules/case/case.service.ts

https://app.asana.com/0/1199153462262248/1201899370258140/f
Add noNationalId to extended case's defendants
It's a bug

fix(judicial-system): Add noNationalId to extended case's defendants

---

apps/judicial-system/backend/src/app/messages/notifications.ts
apps/judicial-system/backend/src/app/modules/case/case.service.ts

https://app.asana.com/0/1199153462262248/1201835567438802/f
- Fixes reference to the Contentful string for the email body.
- Only sends the signed ruling as an attachment if it was not uploaded to S3.
Bug

fix(judicial-system): Fixes court fallback email

---

apps/judicial-system/web/src/routes/Court/InvestigationRequest/CourtRecord/CourtRecord.tsx
apps/judicial-system/web/src/routes/Court/InvestigationRequest/Ruling/Ruling.tsx

https://app.asana.com/0/1199153462262248/1201835567438764/f
Autofill prosecutorDemands on ruling screen for court users
This was still being done on the courtRecord screen in investigation cases and that was a bug.

fix(judicial-system): Autofill prosecutorDemands on ruling screen for court users

---

apps/judicial-system/web/messages/InvestigationCases/Court/courtRecordForm.ts
apps/judicial-system/web/messages/RestrictionCases/Court/courtRecordForm.ts

Session bookings autofill is now markdown
These strings have newlines in them but they are not showing in CF. By marking them as #markdown, content editors have more control over their format in CF.

chore(judicial-system): Session bookings autofill is now markdown

---

apps/api/README.md
apps/services/endorsements/api/README.md
apps/services/search-indexer/README.md
apps/web/README.md
handbook/misc/application-payment-guide.md
libs/application/templates/driving-license/src/forms/prerequisites/sectionFakeData.ts
libs/application/templates/general-petition/README.md
libs/clients/driving-license/README.md
libs/clients/syslumenn/README.md
libs/cms/README.md

Rename all mentions of Kosmos & Kaos to Júní.
Kosmos & Kaos is now named Júní after merger

chore(READMEs): Normalize Júní code ownership naming

---

libs/logging/src/lib/logging.ts
scripts/ci/_retag.sh

fix(ci): docker image re-tagging should work when re-running the CI jobs

---

libs/api/domains/license-service/src/lib/client/driving-license-client/pkpass.client.ts
libs/api/domains/license-service/src/lib/graphql/genericLicense.model.ts
libs/api/domains/license-service/src/lib/graphql/main.resolver.ts
libs/api/domains/license-service/src/lib/licenseService.service.ts
libs/service-portal/graphql/src/lib/mutations/createPkPass.ts
libs/service-portal/licenses/src/components/QRCodeModal/QRCodeModal.tsx

SEE: #6852 
Race condition was made by fetching pkpass two times in a row. 
Either pkpass url or qrcode was expired.
BUG 🐛 

fix(api): race condition when fetching url or qrcode (#6852)

---

apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/courtRecord.spec.ts
apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/courtRecord.spec.ts
apps/judicial-system/web/messages/InvestigationCases/Court/courtRecordForm.ts
apps/judicial-system/web/messages/RestrictionCases/Court/courtRecordForm.ts
apps/judicial-system/web/src/routes/Court/InvestigationRequest/CourtRecord/CourtRecordForm.tsx
apps/judicial-system/web/src/routes/Court/InvestigationRequest/Ruling/RulingForm.tsx
apps/judicial-system/web/src/routes/Court/RestrictionRequest/CourtRecord/CourtRecord.tsx
apps/judicial-system/web/src/routes/Court/RestrictionRequest/Ruling/Ruling.tsx
apps/judicial-system/web/src/utils/validate.ts

https://app.asana.com/0/1199153462262248/1201935511632243/f
Validate conclusion and decision on courtRecord screen instead of ruling
Users want to be able to start working on the court record before making these decisions.

chore(judicial-system): Validate conclusion and decision on courtRecord screen instead of ruling

---

apps/services/user-notification/src/app/modules/notifications/notificationDispatch.service.ts

Fix error detection from firebase-admin
Firebase error documentation is rather poor.
When firebase returns an error on sending a push notification we must decide based on the response if the error is caused by an issue with the push token or not.
If we decide incorrectly that the issue is not with the token when it actually is the tokens fault, the message will end up in the sqs dead-letter-queue, which we'd rather avoid.
This change is based on errors we're seeing in datadog.

chore(user-notification): Fix error detection from firebase-admin

---

apps/judicial-system/web/src/components/CaseInfo/CaseInfo.tsx

https://app.asana.com/0/1199153462262248/1201927207988736/f
- Fixes case info display for registrars.
Bug

fix(judicial-system): Fix Case Info For Registrars

---

apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepTwo/StepTwoForm.tsx

https://app.asana.com/0/1199153462262248/1201927207988736/f
- Fixes case info for prosecutors on the hearing arrangements screen in restriction cases.
Bug

fix(judicial-system): Fixes case info on hearing arrangements screen in restriction cases

---

apps/air-discount-scheme/backend/src/environments/environment.ts
libs/clients/national-registry/v2/src/lib/nationalRegistryClient.config.ts

Disable token exchange for ADS. It is currently 100% redundant since the client already has the scope required to talk to National Registry. It may be causing problems due to clock drift and NBF validation.
Also add a configuration to increase logging of national registry errors.
To figure out why ADS has been broken all day.

fix(ads): ADS national registry hotfix and logging

---

apps/financial-aid/api/src/app/modules/municipalityNationalRegistryModule/municipalityNationalRegistry.resolver.ts

- Get spouse is throwing 500 error when it should be throwing 404 if person doesn't have a spouse 
- If error than spouse is undefined
- Desperate times

fix(fa): Temporary fix for national registry 

---

libs/nest/config/README.md
libs/nest/config/src/lib/ConfigurationLoader.ts
libs/nest/config/src/lib/InvalidConfiguration.ts
libs/nest/config/src/lib/defineConfig.ts
libs/nest/config/src/lib/e2e/config.module.spec.ts
libs/nest/config/src/lib/types.ts

This adds support for optional configs. So module can register config type to be optional, and handle it using the `isConfigured` property.
This was inspired when I was going to add token exchange for the `NationalRegistryClientModule` but other apps like Air Discount Scheme so changing the `NationalRegistryClientModule`  to require client credentials in config would have broken ADS. 

feat(nest-config): Add support for optional configs

---

apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/Overview/Overview.tsx

https://app.asana.com/0/1199153462262248/1201337986358791/f
Only create resentExplanation if the case is received
You can only write a resent explanation if the case is received but we were creating one either way.

fix(judicial-system): Only create resentExplanation if the case is received

---

libs/island-ui/contentful/src/lib/AssetLink/AssetLink.tsx

* Added a https prefix to asset links
* We can't link to a .docx file since the browser blocks unsecure connections
* It was weird for people to open a pdf file which would open up as an http link

feat(web): Asset link https prefix

---

apps/web/screens/ServiceWeb/SubPage/SubPage.tsx
apps/web/screens/queries/ServiceWeb.ts
libs/cms/src/lib/generated/contentfulTypes.d.ts
libs/cms/src/lib/models/supportQNA.model.ts

* Added a Contact link for the organization contact banner on the service web
* Previously it was hardcoded in

feat(web): Contact link for the organization contact banner on the service web

---

libs/auth-api-lib/src/lib/entities/dto/delegation-scope.dto.ts
libs/auth-api-lib/src/lib/entities/dto/delegation.dto.ts

Fixing a validTo regression as I removed nullable: true from swagger decorator.
This cause the GQL api to use default date value as 01-01-1970.

fix(auth-public-api): Fix validTo to allow null in swagger.

---

apps/financial-aid/api/src/app/modules/municipalityNationalRegistryModule/municipalityNationalRegistry.resolver.ts
apps/financial-aid/api/src/app/modules/municipalityNationalRegistryModule/municipalityNationalRegistry.service.ts
apps/financial-aid/api/src/app/modules/municipalityNationalRegistryModule/municipalityNationalRegistryModule.module.ts

Adding service class that uses the `NationalRegistryClientModule` in financial-aid instead of using the `api/domains/nationalRegistryXroadModule`. 
After the `api/domains/nationalRegistryXroadModule` was refactored to use token exchange or client credentials to communicate with Þjóðskrá, it broke the Financial Aid GraphQL communications with Þjóðskrá.

fix(fa): Adding service to decouple the dependency on api-domains for National Registry

---

.github/workflows/pullrequest.yml
apps/web/components/Project/Header/DefaultProjectHeader.css.ts
apps/web/components/Project/Header/DefaultProjectHeader.tsx
apps/web/screens/Project/Project.tsx
apps/web/screens/queries/Project.tsx
libs/cms/src/lib/generated/contentfulTypes.d.ts
libs/cms/src/lib/models/projectPage.model.ts

* Added 2 new fields to Project pages in Contentful (default header image and background color)
* Rendered these fields when the default theme is selected for a given Project Page 
* We want to be able to change how the default header looks in Contentful
New look:
New look (mobile):

feat(web): Project page default header image and text background

---

libs/application/templates/driving-license/src/dataProviders/TeachersProvider.ts
libs/application/templates/driving-license/src/forms/draft/subSectionSummary.ts
libs/application/templates/driving-license/src/forms/draft/subSectionTempInfo.ts

B-temp applications have do not require driving assessment so instructor name needed to be the name from the drivingInstructor answers 
The driving instructor was also being saved as name and submitted instead of as the national id of the instructor.

fix(driving-license-application): Driving instructor name from answers for B-temp

---

libs/application/templates/parental-leave/src/fields/Review/Review.css.ts
libs/application/templates/parental-leave/src/fields/Review/Review.tsx

Option to print parental leave form overview.

feat(parental-leave): add button to print overview

---

apps/web/screens/ServiceWeb/SubPage/SubPage.tsx

* Changed how the related links on the service web look
* For consistency
Previous look
Current look
The new look is more similar to the sidebar on Articles

feat(web): Service web related links visual update

---

apps/service-portal/src/auth.ts
libs/api/domains/license-service/src/lib/graphql/main.resolver.ts
libs/auth/scopes/src/lib/api.scope.ts

Creating a `@island.is/licenses:verify` scope on the verify endpoint in the GQL api.
To grant external clients access to the licenses verify endpoint. The scanner apps needs this to verify driver licenses and we don't won't to grant the client the internal scope.

refactor(api): Adding license:verify scope for verify endpoint.

---

libs/service-portal/documents/src/screens/Overview/Overview.tsx

Set default filter of inbox to 3 months in future
Users cannot see documents when they are sent with a date that surpasses today's date.

feat(service-portal): Set default filter of inbox to 3 months in future

---

apps/auth-admin-web/components/Resource/forms/ApiScopePersonalRepresentativePermissionsForm.tsx
apps/auth-admin-web/entities/models/personal-representative-scope-permission.model.ts
apps/auth-admin-web/styles/_FormLayout.scss
libs/auth-api-lib/src/lib/personal-representative/services/personal-representative-scope-permission.service.ts

When connecting scope to right type in personal representative permission in the IDS Admin the description for the permission type was not shown. It is now shown both for selected type and for active scope permissions (see screenshot)

feat(personal-rep-ids-admin): Add permission type to scope connector

---

apps/financial-aid/web-osk/graphql/sharedGql.ts
apps/financial-aid/web-osk/src/components/Estimation/Estimation.tsx

https://app.asana.com/0/1202024607727436/1201995298577458
- When applicant is married the aid amount calculated differently from veita to osk 
- We were using national registry, which we dont retrieve when logged into status page osk 
- Added family status to my application to use to decide between individual or cohabitation 
- Necessary that osk and veita provide the same information

fix(fa): Status page aid amount calculation

---

apps/services/auth-api/src/app/modules/user-profile/user-profile.controller.spec.ts
libs/auth-api-lib/src/lib/services/user-profile.service.ts

Revert user profile integration in auth-api.
Because it doesn't work on staging/prod and sometimes slows down auth by around 3 seconds.

fix(ids): HOTFIX Revert user profile integration

---

libs/financial-aid/shared/src/lib/formatters.ts

https://app.asana.com/0/1202037685216853/1202037685216830
Add to text to email formtatter.
More info for user.

fix(fa): Add text to rejected email

---

apps/web/components/Project/Header/DefaultProjectHeader.tsx
apps/web/screens/Project/Project.tsx
apps/web/screens/queries/Project.tsx
libs/cms/src/lib/generated/contentfulTypes.d.ts
libs/cms/src/lib/models/projectPage.model.ts

* Added a new field in Contentful that allows you to edit what text gets shown when you share a link to Project page
* Added a fail-safe to the project subpage mapping
* We want to be able to customize the text shown when you share a link to a project page (without using the intro text)
* If you delete a project subpage in Contentful and forget to remove the reference in the Project page then you would get a 500 error

feat(web): Project page featured description

---

libs/infra-nest-server/src/lib/infra/apm.interceptor.ts
libs/infra-nest-server/src/lib/infra/infra.module.ts

NestJS interceptor which adds DataDog APM spans for NestJS request handlers and resolvers.
To have more visibility into which NestJS handlers are running and when.

feat(infra): NestJS interceptor for DataDog APM

---

.github/CODEOWNERS
apps/services/auth-api/src/app/modules/user-profile/user-profile.controller.spec.ts
apps/services/auth-api/src/app/modules/user-profile/user-profile.controller.ts
apps/services/auth-api/test/setup.ts
libs/auth-api-lib/src/lib/entities/dto/user-profile.dto.ts
libs/auth-api-lib/src/lib/services/user-profile.service.ts
libs/clients/national-registry/v2/src/index.ts
libs/clients/national-registry/v2/src/lib/nationalRegistryClient.module.ts
libs/clients/national-registry/v2/src/lib/nationalRegistryClient.service.ts
libs/clients/national-registry/v2/src/lib/types/address.dto.ts
libs/clients/national-registry/v2/src/lib/types/individual.dto.ts

Handle error responses better in the new IDS / Auth API integrations.
* Handle 404 responses from Company Registry, National Registry and User Profile Service.
* Handle empty National Registry 204 responses with new shared code and client service.
So we can add more user claims in IDS.

fix(auth-api): Handle integration errors better

---

apps/financial-aid/backend/migrations/20220406124843-update-applications-comments.js
apps/financial-aid/backend/src/app/modules/application/models/application.model.ts

https://app.asana.com/0/1202037685216853/1202055368844795
Change comment fields type from STRING to TEXT.
So the user can have long long texts.

fix(fa): Allow longer text on comments

---

apps/financial-aid/api/src/app/modules/municipality/models/municipality.model.ts
apps/financial-aid/api/src/app/modules/municipality/municipality.resolver.ts
apps/financial-aid/api/src/services/backend.ts
apps/financial-aid/backend/src/app/modules/staff/staff.controller.ts
apps/financial-aid/backend/src/app/modules/staff/staff.service.ts
apps/financial-aid/web-veita/graphql/sharedGql.ts
apps/financial-aid/web-veita/src/components/MultiSelection/MultiSelection.css.ts
apps/financial-aid/web-veita/src/components/MultiSelection/MultiSelectionAdmins.tsx
apps/financial-aid/web-veita/src/components/MultiSelection/MultiSelectionMunicipality.tsx
apps/financial-aid/web-veita/src/components/NewUserModal/NewUserModal.tsx
apps/financial-aid/web-veita/src/components/Profile/EmployeeProfile.tsx
apps/financial-aid/web-veita/src/components/Profile/MunicipalityProfile.tsx
apps/financial-aid/web-veita/src/components/index.ts
libs/financial-aid/shared/src/lib/interfaces.ts

https://app.asana.com/0/1202037685216853/1202025307775315
- Created new endpoint where getting all admins that are not in municipality 
- Added select option where you can pick admin that are not in municipality 
- Needed feature for super admin and convenient

feat(fa): Super admin can make existing user as admin

---

apps/financial-aid/api/src/app/modules/municipality/dto/createMunicipality.input.ts
apps/financial-aid/api/src/app/modules/municipality/municipality.resolver.ts
apps/financial-aid/api/src/app/modules/staff/staff.resolver.ts
apps/financial-aid/api/src/services/backend.ts
apps/financial-aid/backend/src/app/modules/municipality/municipality.controller.ts
apps/financial-aid/backend/src/app/modules/municipality/municipality.service.ts
apps/financial-aid/backend/src/app/modules/staff/staff.controller.ts
apps/financial-aid/backend/src/app/modules/staff/staff.service.ts
apps/financial-aid/backend/src/app/modules/staff/test/numberOfUsersForMunicipality.spec.ts
apps/financial-aid/web-veita/graphql/sharedGql.ts
apps/financial-aid/web-veita/src/components/NewMunicipalityModal/NewMunicipalityModal.tsx
apps/financial-aid/web-veita/src/routes/Municipalities/municipalities.tsx

https://app.asana.com/0/1202037685216853/1202025307775313
- Making create admin when creating muni optional 
- Adding to new muni modal the option of picking out an existing admin
- If selected existing admin, after creating muni update admin 
- When getting number of users only admin user
- Because we want to be able to update admin instead of creating 
- Requested

feat(fa): When creating municipality being able to use existing admin

---

apps/financial-aid/web-veita/src/components/MultiSelection/MultiSelection.tsx
apps/financial-aid/web-veita/src/utils/formHelper.ts

https://app.asana.com/0/1202037685216853/1202088096213725
- Checks if admin has access to one muni 
- if so then add municipality ids to the one 
- moved mapping function to component
- select with one selection is just wrong

feat(fa): When access to one municipality default will select one  

---

libs/island-ui/core/src/lib/Input/Input.css.ts
libs/island-ui/core/src/lib/Input/Input.tsx
libs/island-ui/core/src/lib/Input/types.ts
libs/shared/form-fields/src/lib/InputController/InputController.tsx

Show loading indicator inside input field for better async UX
Async actions based on input have no standard loading indicator like buttons, this should allow for a more consistent UX

feat: Loading Input

---

apps/web/pages/s/syslumenn/utgefid-efni/index.ts
apps/web/screens/Organization/SubPage.tsx

* Sýslumenn already have an organization subpage that uses the same slug as the generic published material page, meaning that the new generic published material page appears instead of the old page, which is not ideal.
* So the change was to specifically check if the user was on the syslumenn utgefid-efni page and override the generic published material page with the syslumenn published material page
* This will be removed in the future if syslumenn want to utilize the new generic published material page instead
Here we can see the new generic published material page that appears instead of the old syslumenn org page since they share the same slug
Here is the page we want to see

feat(web): Sýslumenn published material page override

---

libs/service-portal/documents/src/utils/getOrganizationLogoUrl.ts

Remove prepending https 
Because it was done in another file (see https://github.com/island-is/island.is/pull/7100) 

fix(service-portal): remove prepended https

---

apps/judicial-system/backend/migrations/20220419164419-update-institution.js
apps/judicial-system/backend/test/e2e.spec.ts

https://app.asana.com/0/1199153462262248/1202148289367382/f
- Activates Héraðsdómur Norðurlands eystra.
- Creates Lögreglustjórinn á Norðurlandi eystra.
Necessary preparation for go live.

feat(j-s): Prepares Norðurland eystra for Go Live

---

apps/web/components/Regulations/DiffModeToggle.tsx
apps/web/components/Regulations/HistoryStepper.tsx
apps/web/components/Regulations/RegulationChangelog.tsx
package.json
yarn.lock

Incomplete impacts were missing from regulation timeline
Timeline needs to show all impacts to display the real status of a regulation

feat(regulations): show all impacts in history list

---

apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
apps/judicial-system/backend/src/app/formatters/formatters.ts
apps/judicial-system/backend/src/app/messages/notifications.ts

[Asana](https://app.asana.com/0/1199153462262248/1202148289367437/f)
- Fix wrong format of date and time 
- It was defaulting to english for some unknown reason

fix(j-s): fix date and time format in notifications

---

apps/web/components/Regulations/RegulationStatus.tsx

When viewing original version of a regulation and the regulation had history, the date range was showing wrong final date

fix: show correct final date when viewing original version

---

apps/web/components/Regulations/RegulationStatus.tsx

Edge case where regulation status would not display correct status text

fix(regulations): issue with status order

---

apps/judicial-system/backend/src/app/messages/notifications.ts
apps/judicial-system/backend/src/app/messages/pdfCustodyNotice.ts
apps/judicial-system/web/messages/Core/index.ts
apps/judicial-system/web/messages/Core/restrictions.ts
apps/judicial-system/web/messages/Core/sections.ts
apps/judicial-system/web/messages/Core/signedVerdictOverview.ts
apps/judicial-system/web/messages/RestrictionCases/Court/courtRecordForm.ts
apps/judicial-system/web/messages/RestrictionCases/Court/overview.ts
apps/judicial-system/web/messages/RestrictionCases/Court/ruling.ts
apps/judicial-system/web/messages/RestrictionCases/Prosecutor/accusedForm.ts
apps/judicial-system/web/messages/RestrictionCases/Prosecutor/demandsForm.ts
apps/judicial-system/web/messages/RestrictionCases/Prosecutor/overview.ts
apps/judicial-system/web/messages/RestrictionCases/Prosecutor/reportForm.ts
apps/judicial-system/web/messages/RestrictionCases/Prosecutor/requestedHearingArrangementsForm.ts

[Asana](https://app.asana.com/0/0/1202188672896414/f)
- Remove template string being used for contentful strings
- They are not supported and result in empty translations when uploading to contentful

fix(j-s): remove template strings from contentful strings

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx

* Previously the english page version of Organization pages did not show the corresponding footers
* We want the footer to be shown on multiple locales

feat(web): Organization page english footers

---

libs/application/templates/parental-leave/src/fields/Review/Review.tsx
libs/application/templates/parental-leave/src/fields/UsePrivatePensionFund/index.tsx
libs/application/templates/parental-leave/src/lib/answerValidators.spec.ts
libs/application/templates/parental-leave/src/lib/answerValidators.ts
libs/application/templates/parental-leave/src/types.ts

Adding answer validation for privatePensionFund and privatePensionFundPercentage, both on the Payment Information page and on the Review page (see images)
Doing this to avoid issues with users not filling in these fields.

fix(parental-leave): answer validation for privatePensionFund and privatePensionFundPercentage

---

apps/service-portal/src/auth.ts
libs/service-portal/graphql/src/lib/fragments/application.ts

Add delete button to applications component in Service portal
So users can delete their drafted applications in the service portal.
https://user-images.githubusercontent.com/2643113/165759979-a267dd6f-dbe4-4bc9-b2b8-dad5508a44c0.png)

feat(service-portal): Add delete functionality on applications

---

apps/application-system/form/src/app/App.tsx
apps/application-system/form/src/routes/Applications.tsx
apps/service-portal/src/app/App.tsx
libs/application/ui-shell/src/lib/ApplicationForm.tsx
libs/service-portal/graphql/src/lib/client.ts
libs/shared/components/src/auth/UserMenu/UserProfileLocale.tsx
libs/shared/components/src/auth/UserMenu/userProfile.graphql.ts
libs/shared/components/src/index.ts

Use UserProfileLocale from service-portal in application and place that component into the shared react components.
Persisting locale through refreshes and between browsers.
Shared component used to avoid duplication of code.

fix(application-system): Reintroduce userprofile locale logic

---

apps/judicial-system/web/messages/Core/signedVerdictOverview.ts
apps/judicial-system/web/messages/RestrictionCases/Prosecutor/accusedForm.ts
apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx

[Asana](https://app.asana.com/0/0/1202188672896410/f)
- Support Admission cases in modal when extending custody/admission

fix(j-s): support admission case in extend custody modal

---

apps/web/components/Organization/Slice/OneColumnText/OneColumnTextSlice.tsx

* Replaced '#' with the actual link url
* We want to be able to use the link, the # link is a leftover

feat(web): OneColumnText Slice link url

---

libs/cms/src/lib/search/importers/article.service.ts

* Pruned entry hyperlinks from related articles and subarticles when saving data in elasticsearch
* Added the entry id to the exception log since this issue was hard to debug without knowing the id's
* This was causing an issue where articles were not showing up on the web due to circularity caused by entry hyperlinks in subarticles or related articles

fix(web): Pruned entry hyperlinks from related articles and subarticles

---

apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/receptionAndAssignment.spec.ts
apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/receptionAndAssignment.spec.ts
apps/judicial-system/web/src/utils/validate.ts

[Asana](https://app.asana.com/0/1199153462262248/1202216317858343/f)
- Disable the continue button when the court case number is invalid

fix(j-s): disable continue btn if court-case-number is invalid

---

libs/application/templates/parental-leave/src/lib/answerValidators.ts

Fixing issue where answer validation for privatepensionfund and privatePensionFundPercentage would fail on the review page if the submit failed.
Make sure that this issue does not occur if the submit fails.

fix(parental-leave): privatepensionfund and percentage validation fix on failed submit

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/Themes/UtlendingastofnunTheme/UtlendingastofnunHeader.css.ts
apps/web/components/Organization/Wrapper/Themes/UtlendingastofnunTheme/UtlendingastofnunHeader.tsx

* Changed the header image for Útlendingastofnun

feat(web): Útlendingastofnun header change

---

libs/service-portal/family/src/components/ChildView/ChildView.tsx

Show parents if there is a parent response
Parents response can be in some extremely rare cases.

fix(service-portal): Show parents if there is a parent response

---

apps/judicial-system/backend/src/app/formatters/custodyNoticePdf.ts
apps/judicial-system/backend/src/app/formatters/rulingPdf.ts
apps/judicial-system/web/messages/Core/signedVerdictOverview.ts
apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/AppealSection/AppealSection.spec.tsx
apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/AppealSection/AppealSection.tsx

[Asana](https://app.asana.com/0/1199153462262248/1202246183652724/f)
Use court end time instead of ruling date where relevant
It doesn't matter when a judge signs a verdict, what matters is when the court proceedings finish.

fix(j-s): Use court end time instead of ruling date where relevant

---

apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/overview.spec.ts
apps/judicial-system/web/messages/RestrictionCases/Prosecutor/accusedForm.ts
apps/judicial-system/web/messages/RestrictionCases/Prosecutor/overview.ts
apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/Overview.css.ts
apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/index.ts
apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepOne/StepOneForm.tsx

[Asana](https://app.asana.com/0/1199153462262248/1202086011710963/f)
Move info panel about how to resend a case to the overview step
It used to be on the first step of the flow. Now, when you open a sent case you automatically go to the last step and therefore it makes sense to have this info panel there.

chore(j-s): Move info panel about how to resend a case to the overview step

---

apps/web/layouts/main.tsx
libs/island-ui/core/src/lib/Footer/Footer.tsx

* Web footer links to support page now
* Changed the layout for the bottom left links
* Put the support page link behind a feature flag

feat(web): Web footer links to support page

---

libs/application/templates/parental-leave/src/lib/answerValidators.ts

Fix issue when refreshing the page would cause the validation of privatePensionFundPercentage to fail

fix(parental leave): submit failure on page refresh

---

apps/service-portal/src/components/Layout/Layout.css.ts
apps/service-portal/src/components/Layout/Layout.tsx

Add padding to gridcontainer in mobile
It was removed from the ui library. We need it for the service-portal.

fix(service-portal): Add padding to grid layout container

---

apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepThree/StepThreeForm.spec.tsx
apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepThree/StepThreeForm.tsx
apps/judicial-system/web/src/utils/formHelper.spec.ts
apps/judicial-system/web/src/utils/formHelper.ts

- fix(j-s): fix toggleInArray not handling empty state
- fix(j-s): pass in changing demands prop to demands autofill
Asana[https://app.asana.com/0/1199153462262248/1202188672896423/f]
- Fix the isolation radio button
- Make sure changed demands are passed into demands autofill function
- Isolation radio button was not able to be toggled
- Changing type to admission to the facility had no changes to the text of the demands on next page

fix(j-s): fix demands for restriction cases

---

libs/application/templates/financial-aid/src/fields/Status/ApplicantStatus.tsx
libs/application/templates/financial-aid/src/lib/utils.ts

https://app.asana.com/0/1202167941440767/1202167941440798
Fix checks on when applicant is waiting for spouse, because new state ApplicationStates.PREREQUISITESSPOUSE has been added.

fix(fa): Fix check when waiting for spouse

---

apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/hearingArrangements.spec.ts
apps/judicial-system/web-e2e/src/utils/index.ts
apps/judicial-system/web/src/routes/Court/InvestigationCase/HearingArrangements/HearingArrangements.tsx
apps/judicial-system/web/src/routes/Court/InvestigationCase/HearingArrangements/HearingArrangementsForm.tsx

[Asana](https://app.asana.com/0/1199153462262248/1202086011710880/f)
remove autofill of courtDate with requestedCourtDate
test if court date is autofilled and confirmed correctly
Court date should only be confirmed when user presses the continue button

fix(j-s): fix court date being confirmed automatically

---

apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/overview.spec.ts

- Remove it.only mark on tests
- So it is not only test run in this test module

test(j-s): remove it.only mark for e2e test

---

apps/web/components/HeadWithSocialSharing/HeadWithSocialSharing.tsx
apps/web/components/ServiceWeb/Wrapper/Wrapper.tsx
apps/web/screens/ServiceWeb/Home/Home.tsx

* Added a prop to the service web wrapper component that allows you to turn the search engine indexing on or off
* Also fixed an issue regarding image urls that already start with https by simply not prefixing the url with https if it does not start with '//'
* We want the mannaudstorg service web to be indexed by search engines

feat(web): Service web, optional search indexing

---

apps/web/screens/Organizations/Organizations.tsx
apps/web/screens/queries/Organization.tsx
libs/cms/src/lib/generated/contentfulTypes.d.ts
libs/cms/src/lib/models/organization.model.ts

* Added a new field to the Organization model that allows you to set whether or not that organization gets shown on the organizations page
* We want to be able to change in the CMS what organizations are shown on the organizations page https://island.is/s

feat(web): Organizations page - CMS can change what organizations are shown

---

libs/application/templates/parental-leave/src/fields/SpouseUseAsMuchAsPossible/index.tsx
libs/application/templates/parental-leave/src/fields/personalUseAsMuchAsPossible/index.tsx
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.spec.ts
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts

Remove personalAllowance if usePersonalAllowance is set to NO and personalAllowance exists
Remove personalAllowanceFromSpouse if usePersonalAllowanceFromSpouse is set to NO and personalAllowanceFromSpouse exists

fix(parental leave): remove personalAllowance(FromSpouse) if the user does not want to use it

---

apps/web/components/ChatPanel/BoostChatPanel/BoostChatPanel.tsx
apps/web/components/ChatPanel/ChatBubble/ChatBubble.tsx

* Relocated the chat bubble in the mobile view
* So the chat bubble doesn't cover the application button in the mobile view

feat(web): Pushed the Chat bubble up in the mobile view

---

apps/web/components/ChatPanel/ChatBubble/ChatBubble.tsx
apps/web/components/ChatPanel/WatsonChatPanel/WatsonChatPanel.tsx
apps/web/components/ChatPanel/types.ts
apps/web/screens/Article/components/ArticleChatPanel/ArticleChatPanel.tsx

* As of right now the ChatBubble is always moved up when island.is enters the mobile width, this change only relocates the chat bubble when a process entry banner appears on an article
https://user-images.githubusercontent.com/43557895/170684337-1f2bfe07-de76-4ced-a665-919c1c987f87.mp4

feat(web): Only relocate ChatBubble when an article that contains a process entry is viewed in mobile

---

libs/auth/react/src/lib/AuthSettings.spec.ts
libs/auth/react/src/lib/AuthSettings.ts

As we do not use reference access tokens, we should not be calling revocation on the access tokens, only refresh tokens.
This results in 404 errors in auth-api when trying to look for access_token as reference token on revocation.

fix(auth-react): Remove access_token revocation token type

---

libs/auth/react/src/lib/AuthSettings.spec.ts
libs/auth/react/src/lib/AuthSettings.ts

HOTFIX PR #7537 
As we do not use reference access tokens, we should not be calling revocation on the access tokens, only refresh tokens.
This results in 404 errors in auth-api when trying to look for access_token as reference token on revocation.

fix(auth-react): HOTFIX Remove access_token recovationTokenType

---

libs/service-portal/core/src/lib/messages.ts
libs/service-portal/information/src/lib/messages.ts
libs/service-portal/vehicles/src/lib/messages.ts
libs/service-portal/vehicles/src/screens/VehicleDetail/VehicleDetail.tsx

* Remove vehicle detail subtitle
* Update few default strings
* No subtitle should be displayed on the vehicle detail page.

chore(service-portal): Remove vehicle detail title. Update some default strings

---

apps/judicial-system/web/src/routes/Court/InvestigationCase/CourtRecord/CourtRecord.tsx

[Asana - Rannsóknarheimild/Þingbók - Mættir eru syncast ekki í bakenda](https://app.asana.com/0/1199153462262248/1202360581950488/f)
- Remove force autofill for fields `courtStartDate, courtAttendees, courtLocation`
- So that fields are not overwritten if users change them and hits refresh or navigates to the next page

fix(j-s): remove force autofill

---

libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts

fix error of periods and other db values being restored/deleted after spouse approval
https://dit-iceland.atlassian.net/jira/software/projects/UUFV/boards/71?selectedIssue=UUFV-85&text=85

fix(parental-leave): db intact on spouse approval

---

apps/judicial-system/backend/src/app/modules/case/case.service.ts

[Asana - Passa að villutölvupóstur fari ekki út við successfull leiðréttingu](https://app.asana.com/0/0/1202362015988803/f)
- Don't check if court record fails to upload when modifying ruling
- Court record is not uploaded when modifying ruling

fix(j-s): only check failed courtRecord upload when not modifying ruling

---

apps/web/components/ChatPanel/WatsonChatPanel/WatsonChatPanel.tsx

* Now the chat bubble for the watson chat bot won't appear when locale is not 'is'
* The chat bot is only in Icelandic right now so we want to not show it when the locale is set to english

feat(web): Hide the Watson chat bot launcher if the locale is not 'is'

---

libs/auth/react/src/lib/AuthSettings.spec.ts
libs/auth/react/src/lib/AuthSettings.ts

The `oidc-client-ts` automatically updates the access token before it expires. This causes the IDS user session to slide, creating infinite user session.
To fix the regression the `oidc-client-ts` library introduced.

fix(auth-react): Disabling automatic access token refresh

---

apps/judicial-system/web/src/routes/Court/InvestigationCase/Ruling/Ruling.tsx

[Asana](https://app.asana.com/0/1199153462262248/1202413161940505/f)
When you click the Back button in the footer of the Ruling page in investigation cases, you are routed to the prosecutor flow, i.e. to "/krafa/rannsoknarheimild/fyrirtaka" (should be "/domur/rannsoknarheimild/fyrirtaka")
It's a bug

fix(j-s): Fix a broken back link on ruling page

---

apps/air-discount-scheme/web/screens/Subsidy/components/Benefits/Benefits.tsx

Users poll the graphql api every 10 seconds once on Air Discount Scheme.
Reduce request load by sixfold.
Some users may figure out that they either have to wait or manually refresh themselves in the case where they are trying to use multiple discount codes in quick succession.

feat(ads): Polling every minute instead of every ten seconds

---

apps/auth-admin-web/infra/auth-admin-web.ts
charts/identity-server/values.staging.yaml

Remove enable-global-auth for staging
This was causing CSP violations, and wasn't set in the original Helm setup.

fix(infra): Remove enable-global-auth for auth-admin-web staging

---

apps/web/components/Organization/Wrapper/Themes/FiskistofaTheme/FiskistofaFooter.css.ts
apps/web/components/Organization/Wrapper/Themes/FiskistofaTheme/FiskistofaFooter.tsx

There were small style inconsistencies in the Fiskistofa footer.

fix(web): Fix styles for Fiskistofa footer

---

apps/services/user-profile/src/app/user-profile/e2e/userProfile.spec.ts

Update the test for non-matching mobile numbers
The test was wrong. It was not checking for the mismatching emails. Only if the response was good, which is done in a different test.

fix(service-portal): Update sms code test for mismatching numbers

---

libs/application/core/src/types/Form.ts
libs/application/templates/announcement-of-death/src/forms/done.ts
libs/application/templates/announcement-of-death/src/forms/draft/subSectionInheritance.ts
libs/application/ui-components/src/components/Markdown/Markdown.css.ts
libs/application/ui-components/src/components/Markdown/Markdown.tsx
libs/application/ui-components/src/components/Markdown/markdownOptions.tsx
libs/application/ui-components/src/index.ts
libs/application/ui-shell/src/components/FormMultiField.tsx
libs/shared/form-fields/src/lib/FieldDescription/FieldDescription.tsx
package.json
yarn.lock

Adding styled markdown to the application system UI components.
Currently only supporting h1, bullet lists, and anchors
This will make rich text areas easier to work with

feat(application-system): Default markdown styles

---

libs/application/templates/parental-leave/src/fields/Review/Review.tsx

Edit button doesn't respond when clicked on in review page
Didn't work after other parent structure changed

fix(parental-leave): edit other parent on review page

---

libs/auth-api-lib/src/lib/config/DelegationConfig.ts

Updating the default config list for scopes that should only be returned in the scope list for companies to grant access using custom delegations.
To hide these scopes when individuals are giving custom delegations.

chore(auth-public-api): Adding company only scopes for custom delegations

---

libs/application/data-providers/src/providers/UserProfileProvider.ts
libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.spec.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

remove country code (+354) from function that prefills user tel number in application
Otherwise 1234567 will be shown as 3541234

feat(parental-leave): remove country code from prefilled tel number

---

apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
apps/judicial-system/backend/src/app/formatters/formatters.ts
apps/judicial-system/backend/src/app/modules/notification/notification.service.ts

[Asana](https://app.asana.com/0/1199153462262248/1202438223074125/f)
Don't send courtDateLinkEmail if sendRequestToDefender is not set
It's a bug

fix(j-s): Don't send courtDateLinkEmail if sendRequestToDefender is not set

---

libs/service-portal/core/src/lib/navigation/masterNavigation.ts
libs/service-portal/vehicles/src/index.ts
libs/service-portal/vehicles/src/lib/messages.ts
libs/service-portal/vehicles/src/screens/Overview/Overview.tsx
libs/service-portal/vehicles/src/screens/VehicleHistory/VehicleHistory.tsx

Hide vehicle lookup as Samgöngutstofa is not ready with authentication service.
Bonus (the bigger the better right?):
* Text and spacing changes
* Display empty state if array from resolver is empty
* Display empty text if filtered vehicles is empty
* Add "Skilavottorð" button above search in vehicles overview

fix(service-portal): hide vehicle lookup

---

apps/web/components/MobileAppBanner/MobileAppBanner.tsx

Hide the mobile app banner if links are not specified in UI configuration.
The mobile app banner may need to be disabled sometimes.

fix(web): Add a way to hide mobile banner

---

libs/service-portal/documents/src/index.ts
libs/service-portal/documents/src/screens/AccessDeniedLegal/AccessDenied.css.ts
libs/service-portal/documents/src/screens/AccessDeniedLegal/AccessDeniedLegal.tsx

New screen for when Documents are blocked because of actor is legal guardian and the child is 15+ years old.
Explanation of why only documents are blocked.

feat(service-portal): Documents - Block screen

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/assignEmployerEmail.ts
libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/assignOtherParentEmail.ts
libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts

Make sure the links in the sms and email being sent to spouse/employer is the same and no additional token is generated.
https://dit-iceland.atlassian.net/jira/software/projects/UUFV/boards/71?selectedIssue=UUFV-104

fix(parental-leave): sms token same as email

---

libs/application/templates/announcement-of-death/src/fields/FilesRecipientCard/FilesRecipientCard.tsx

If applicant is a part of Estates then they were added twice to FileRecipients.

fix(announcement-of-death): Fixed duplication issue for filerecipients regarding applicant

---

libs/shared/components/src/auth/UserMenu/UserDropdown.tsx

Use the initals of the current actor as the initials in the avatar.
Is now:
Becomes:

fix(service-portal): Use current username in avatar

---

libs/api/domains/license-service/src/lib/client/adr-license-client/adrLicenseService.api.ts
libs/api/domains/license-service/src/lib/client/machine-license-client/machineLicenseService.api.ts
libs/api/domains/license-service/src/lib/graphql/main.resolver.ts

fix(service-portal): default drivers license when querying all licenses without input.

---

libs/application/ui-components/src/components/CompanySearchController/CompanySearchItem.tsx

Fix bug causing the company search info field to break
When trying to search for * \ or any character used in reg exp you would break the company search info field. Fixed by escaping characters that would cause the crash.

fix(application-system): Fix bug causing the company search info field to break

---

libs/service-portal/information/src/screens/UserInfoOverview/UserInfoOverview.tsx

* All viewable children should come from the get my children api

fix(service-portal): Remove children on same family number for all users

---

libs/auth/react/src/lib/Authenticator/CheckIdpSession.tsx

Update `CheckIdpSession` to use `expiresIn` instead of `expiresUtc` to control when to check again for expired session.
Using `expiresUtc` causes problems when users change their clock without using time zones.

fix(auth-react): Hotfix-Service Portal CheckIdpSession Update

---

apps/judicial-system/message-handler/infra/judicial-system-message-handler.ts
charts/judicial-system/values.dev.yaml

[Vista gögn sjálfkrafa í Auði eftir afgreiðslu ef þau hafa ekki verið vistuð](https://app.asana.com/0/1199153462262248/1201777996978577/f)
- Adds a service account to the message handler.
The service account was missing from the helm charts.

fix(j-s): Message Handler Service Account

---

apps/service-portal/src/components/ContentBreadcrumbs/ContentBreadcrumbs.tsx
libs/service-portal/core/src/lib/messages.ts
libs/service-portal/core/src/lib/navigation/masterNavigation.ts

Refactoring `ContentBreadcrumbs` in Service Portal.
To resolve some issues that the current implementation has:
* Fixes breadcrumb duplication if found multiple times in the navigation definition.
* Resolves route params.
* Allows for having a breadcrumb name defined as the route param value (see screenshot).
* Adds Spouse and Child breadcrumb in when viewing in Family.
* Removes the last item to be rendered as a tag.
Old duplicated breadcrumbs:
New not duplicated breadcrumbs:
No breadcrumb for route param:
Route param breadcrumb title:
Spouse and Child breadcrumb:

refactor(service-portal): Refactor ContentBreadcrumbs

---

apps/judicial-system/web/src/utils/hooks/useSections/index.ts

- Prevents prosecutors from navigating to the case files page (and beyond) until the case facts and legal arguments have been filled in.
Bug.

fix(j-s): Prosecutor Navigation

---

apps/application-system/api/src/app/modules/application/e2e/application.spec.ts
apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/CaseFiles/CaseFiles.tsx
apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepFive/StepFive.tsx
apps/judicial-system/web/src/utils/hooks/useCourtUpload/index.ts
apps/judicial-system/web/src/utils/hooks/useFileList/index.ts
apps/services/auth-public-api/src/app/modules/delegations/actorDelegations.controller.spec.ts
apps/services/auth-public-api/src/app/modules/delegations/meDelegations.controller.spec.ts
apps/services/auth-public-api/src/app/modules/resources/scopes.controller.spec.ts
handbook/reference/problems/README.md
libs/nest/problem/src/lib/ProblemError.ts
libs/nest/problem/src/lib/apolloError.filter.spec.ts
libs/nest/problem/src/lib/apolloError.filter.ts
libs/nest/problem/src/lib/httpException.filter.spec.ts
libs/nest/problem/src/lib/httpException.filter.ts
libs/shared/problem/src/ProblemType.ts

Hotfix httpstatuses url from #8002 
To stop reference .com which redirects to another domain.

refactor(nest-problem): Update httpstatuses reference to .org instead of .com (#8002)

---

infra/scripts/helm-diff.sh

fixes: https://github.com/island-is/infrastructure/issues/1292
This script will diff between two chosen releases by entering the version version. 
`./helm-diff.sh 16.1.0 16.2.0`
This will output in `less` a side by side diff comparison between kubernetes manifests of the two releases. 
Requires you to have the tool ydiff installed
https://github.com/ymattw/ydiff
To do smoke tests on missing environment variables before release.

feat(infra): Script to diff manifest between releases

---

libs/auth-api-lib/src/lib/config/DelegationConfig.ts
libs/auth-api-lib/src/lib/services/delegations.service.ts

Adding filter in scope check to compare against custom scope rules.
When scope was once allowed for delegation, but is then later changed by using the custom scope rules, i.e. to allow only for companies (ProcurationHolder), the Access Control UI was still displaying the scope tag due to the public api still returning the scope as part of the delegation. This PR filters these scopes out of the scope list.
Before:
After:

fix(auth-public-api): Add filter for custom scope rules in checkIfScopeAllowed.

---

apps/web/components/Organization/Slice/Districts/DistrictsSlice.tsx
apps/web/components/Organization/Slice/OrganizationSlice.tsx
apps/web/screens/Organization/Home.tsx
apps/web/screens/Organization/SubPage.tsx

* Add more spacing below the last slice

feat(web): Added margin bottom prop to organization slices

---

libs/cms/src/lib/models/link.model.ts

* Removed leading and trailing whitespace from link url
* We ran into an issue where a link url had a trailing whitespace in the CMS which resulted in a sidebar menu not highlighting it since the code was checking for an exact match

fix(web): Trim leading and trailing whitespace from link url

---

apps/web/types.tsx

* The import path for NextPageContext is outdated and was messing up with type hints
* Changing the import path fixed this issue
Here's a screenshot of code taken before this change:
Here's a screenshot of code taken after this change (no more type errors since things are correctly typed now):

fix(web): Change type import for NextPageContext

---

apps/web/components/Organization/Wrapper/Themes/DigitalIcelandTheme/DigitalIcelandHeader.css.ts

* The title on the Stafrænt Ísland organization page was not rendered in some versions of Safari

fix(web): Gradient text not showing up in Safari

---

apps/web/screens/Category/Category/Category.tsx
apps/web/screens/queries/Category.tsx

Articles can be shown in more than one group by adding to the `otherCategory` and `otherGroup` fields. Currently, this only works when an article's main category is different from the other category.
This PR fixes it so that articles can appear in the main group and also other groups on the same category page.

fix(web): Fix category page when article belongs to multiple groups

---

apps/web/components/Organization/Slice/OverviewLinks/OverviewLinks.tsx
apps/web/screens/queries/fragments.ts
libs/cms/src/lib/generated/contentfulTypes.d.ts
libs/cms/src/lib/models/introLinkImage.model.ts

Currently, all links on overview slices open in a new tab (for example on https://island.is/s/stafraent-island/thjonustur). This PR adds a boolean in Contentful to change this.
The default is still to open in a new tab.

feat(web): Add option for whether overview links should open in a new tab

---

apps/web/components/Organization/Slice/AccordionSlice/AccordionSlice.tsx
apps/web/components/Organization/Slice/BulletList/BulletList.tsx
apps/web/components/Organization/Slice/Districts/DistrictsSlice.tsx
apps/web/components/Organization/Slice/EventSlice/EventSlice.tsx
apps/web/components/Organization/Slice/FeaturedArticles/FeaturedArticlesSlice.tsx
apps/web/components/Organization/Slice/Heading/HeadingSlice.tsx
apps/web/components/Organization/Slice/LogoList/LogoList.tsx
apps/web/components/Organization/Slice/MailingListSignupSlice/MailingListSignupSlice.tsx
apps/web/components/Organization/Slice/MultipleStatistics/MultipleStatistics.tsx
apps/web/components/Organization/Slice/OneColumnText/OneColumnTextSlice.tsx
apps/web/components/Organization/Slice/OverviewLinks/OverviewLinks.tsx
apps/web/components/Organization/Slice/StorySlice/StorySlice.tsx
apps/web/components/Organization/Slice/TabSection/TabSection.tsx
apps/web/components/Organization/Slice/TimelineSlice/TimelineSlice.tsx
apps/web/components/Organization/Slice/TwoColumnText/TwoColumnTextSlice.tsx
apps/web/screens/Organization/SubPage.tsx
apps/web/screens/queries/Organization.tsx
libs/cms/src/lib/generated/contentfulTypes.d.ts
libs/cms/src/lib/models/organizationSubpage.model.ts

This makes it possible to add TOC to organization subpages. All slices that have titles appear in the TOC.

feat(web): Add optional table of contents for organization subpages

---

apps/web/layouts/main.tsx
apps/web/screens/Organization/Home/Home.tsx
apps/web/screens/Organization/Home/index.ts
apps/web/screens/Organization/Home/utils.ts

* Sjúkratryggingar have a status page (https://status.sjukra.is) which indicates the status of their web services. Now their organization page will automatically show an alert banner if an incident or a scheduled maintenance is shown on the status page.
* To be able to do this I added a prop to the Layout component which can be used to add alert banners to the top of the page

feat(web): Add support for custom alert banners in layout

---

apps/web/screens/Adgerdir/Article.tsx
apps/web/screens/Article/Article.tsx
apps/web/screens/queries/Adgerdir.tsx
apps/web/screens/queries/Article.ts
apps/web/screens/queries/fragments.ts
libs/cms/src/lib/generated/contentfulTypes.d.ts
libs/cms/src/lib/models/processEntry.model.ts
libs/island-ui/contentful/src/lib/ProcessEntry/ProcessEntry.tsx

* Now users can select an asset in Contentful instead of having to use a url
* Removed the type field from Process Entry since it's no longer used
* Only render a process entry if there is a process link provided, since the field is no longer required in Contentful and we don't want to show a process entry if there is no link
(Now there's a new field in Contentful for an asset)

feat(web): Allow Process entry asset reference instead of url

---

apps/web/components/Stepper/Stepper/Stepper.tsx
apps/web/components/Stepper/utils.ts
apps/web/screens/Article/Article.tsx
apps/web/screens/queries/fragments.ts
libs/cms/src/lib/environments/environment.ts
libs/cms/src/lib/models/stepper.model.ts
libs/cms/src/lib/models/subArticle.model.ts
libs/cms/src/lib/unions/slice.union.ts

* Instead of having the stepper process entry always at the top you can now place it where you want (in between text for example)
* Made the step option value for the select component actually reference the same memory address as exists in the list of options, meaning that when you now open the select box you'll actually see the selected value highlighted instead of just the top one in the list
* 
* Before this change a stepper process entry would only be at the top of the page, we want to be able to choose where it appears
(Highlight was off due to the way the Select component compares values)
(Highlight is correct now)

feat(web): Add a way to embed stepper in article body

---

apps/financial-aid/backend/src/app/modules/municipality/municipality.service.ts

https://app.asana.com/0/1202167941440767/1202721143583930
When decrypting the navPassword field of a municipality, we need to add a check wether the municipality is empty. This happens when a user starts the application but his municipality is currently not registered in our system.
So users without registered municipality can continue the application.

fix(fa): Add nullish check for missing municipalities

---

libs/application/templates/financial-aid/src/lib/utils.ts

To determine wether a municipality is registered we need to both check if it exists and if it is active. The latter check was added.
So non-active municipalities are also considered as unregistered.

fix(fa): Add check if municipality is active

---

apps/web/components/Organization/Slice/FeaturedArticles/FeaturedArticlesSlice.tsx

The slice should be displayed if there are articles OR resolved articles.

fix(web): Fix FeaturedArticles display condition for resolved articles

---

libs/api/domains/national-registry-x-road/src/lib/nationalRegistryXRoad.service.ts

There is a mismatch between the error codes that Þjóðskrá is returning from their dev and staging/prod environments. When retrieving a spouse from Þjóðskrá and the spouse does not exist, Þjóðskrá will return 400 on dev but 404 on staging/prod. 
This hotfix makes sure we handle both cases.
A conversation with Þjóðskrá about their error codes is ongoing.

fix(fa): Hotfix for thjodskra spouse error 
