libs/api/domains/national-registry-x-road/src/lib/nationalRegistryXRoad.service.ts

There is a mismatch between the error codes that Þjóðskrá is returning from their dev and staging/prod environments. When retrieving a spouse from Þjóðskrá and the spouse does not exist, Þjóðskrá will return 400 on dev but 404 on staging/prod. 
This hotfix makes sure we handle both cases.
A conversation with Þjóðskrá about their error codes is ongoing.
This change was also made as a hotfix for release 17.0.0: https://github.com/island-is/island.is/pull/8126

fix(fa): Fix thjodskra spouse error

---

apps/services/user-profile/src/app/user-profile/verification.service.ts

Add english text to confirmation code email along with the Icelandic text.
Support both languages. `EN` + `IS`

feat(user-profile): Add english translations to confirmation code email

---

apps/air-discount-scheme/backend/src/app/modules/nationalRegistry/nationalRegistry.service.ts
apps/air-discount-scheme/backend/src/app/modules/user/user.service.ts

Need more explicit logs for when national registry is being contacted

fix(ads): temporary heightened logging

---

apps/application-system/api/docker-compose.yml
apps/github-actions-cache/docker-compose.yml

Remove a little used and unnecessary setting in `docker-compose.yml`, i.e. `net.core.somaxconn=511`.
Running `docker-compose up` on my machine (linux using podman-compose) causes an error, and this seems to be unnecessary for local development.
Not sure how to test that this doesn't break for someone else.

chore(docker-compose): Remove obsolete somaxconn sysctl

---

apps/air-discount-scheme/backend/src/app/modules/nationalRegistry/nationalRegistry.service.ts

Custody endpoint was operating on a faulty premise.
Custody endpoint returns other parent, if applicable, not the callee parent.

fix(ads): Ensure callee parent is included in custodians

---

package.json
scripts/ci/Dockerfile
scripts/local-e2e.sh
yarn.lock

Bump cypress v10.2.0 to v10.6.0
Highlights concerning our scenario:
- Updated cross-origin cookie handling to align with browser behavior. This fixed various issues with cookies when testing across multiple origins.
- Corrected the Typescript types to include baseUrl as a valid test config override option
- Fixed an issue where the Proxy-Authorization header included capitalization that would fail with certain proxies. 
- Fixed issues with document.cookie when testing multiple origins
- Upgraded electron from 18.3.0 to 19.0.8
- Upgraded bundled Chromium version from 100.0.4896.75 to 102.0.5005.148
- Fixes issue where cookies were not handled within cy.origin for requests other than the AUT page request
- Fixed an issue that could lead to infinite recursion and thus a crash when running …

chore: bump cypress version from v10.2.0 to v10.6.0, improved local-e2e

---

libs/application/templates/financial-aid/src/fields/Files/Files.tsx
libs/application/templates/financial-aid/src/lib/constants.ts
libs/application/templates/financial-aid/src/lib/hooks/useFileUpload.ts
libs/application/templates/financial-aid/src/lib/messages/application.ts

https://app.asana.com/0/1202167941440767/1202882546493116
- Add constants to restrict the size and types of attachments
- Handle when too big files are uploaded and add error message for that
So users can not send problematic file types or really big files to the database.
This problem was spotted after a security review.

fix(fa): Add size and type restriction to upload files

---

libs/cache/src/lib/cache.ts
package.json
yarn.lock

After bumping ioredis from v4 to v5, `application-system-api` pods are crashing because of missing `lodash.flatten`, although its installed as peer dep in several packages.
```bash
│ _modules/bull/node_modules/ioredis/built/redis/index.js","/webapp/node_modules/bull/node_modules/ioredis/built/index.js","/webapp/node_modules/bull/lib/queue.js","/webapp/node_modules/bull/index.js","/webapp/ │
│ main.js"]},"exception":true,"level":"error","message":"unhandledRejection: Cannot find module 'lodash.flatten'\nRequire stack:\n- /webapp/node_modules/bull/node_modules/ioredis/built/utils/lodash.js\n- /webap │
```
```bash
> yarn why lodash.flatten
=> Found "lodash.flatten@4.4.0"
info Reasons this module exists
- "apollo-server-cache-redis#ioredis" depends on it
- Hoisted from …
```

revert(dependency): downgrade ioredis from v5 to v4

---

libs/application/templates/p-sign/src/forms/applicationSections/sectionInformation.ts
libs/application/templates/p-sign/src/forms/applicationSections/sectionInformationActor.ts
libs/application/templates/p-sign/src/forms/applicationSections/sectionOverview.ts

Showing email and phone from userprofile for applicant in info section and from answers in overview.

fix(p-sign-application): Email and phone from user profile and answers

---

libs/cms/src/lib/models/organizationPage.model.ts
libs/cms/src/lib/models/organizationSubpage.model.ts
libs/cms/src/lib/models/projectPage.model.ts
libs/cms/src/lib/models/projectSubpage.model.ts

* We recently had an incident where a slice list in contentful had one item in draft and that caused an entire organization page to down due to a 500 error (The error was that slices can't contain a null value).
* This fix addresses the issue since now we filter out the slices that aren't successfully mapped
* We don't want something in Contentful to cause a 500 error on the web

fix(web): Filter out slices that failed mapping

---

libs/service-portal/information/src/screens/UserInfo/UserInfo.tsx

Hotfix: https://github.com/island-is/island.is/pull/8322
Don't show individuals on same family number when in delegation mode.

fix(service-portal): hotfix - No showing family members in delegation

---

apps/web/screens/Category/Category/Category.tsx

* We've reached the currently set limit of articles fetched for some categories (meaning that new articles will not appear on the category page)
* I set the limit to be a 1000 (which is the same number used for the island.is/s page)
* We want to be able to see new articles on category pages even though there are more than 150 articles

chore(web): Increase number of articles fetched on category page

---

libs/service-portal/core/src/components/ExpandableTable/Row.tsx
libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx
libs/service-portal/finance/src/screens/FinanceStatus/Table.css.ts

Add print styles for detail table on finance status screen.
Details will be cut off with current styling when printing.

feat(service-portal): Print finance details

---

apps/judicial-system/web-e2e/src/integration/Prosecutor/Indictments/defendant.spec.ts
apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationCases/defendant.spec.ts
apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/defendant.spec.ts
apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/PoliceCaseNumbers/PoliceCaseNumbers.tsx

[Asana ](https://app.asana.com/0/1199153462262248/1202891259672359/f)
- Fix validation for police case numbers input
- Fix the flashing error message when entering in first police case number

fix(j-s): fix validation for police case numbers input

---

apps/financial-aid/api/project.json

The financial-aid apps (Veita and Ósk) are not working on DEV and it looks like they are having trouble with the financial-aid-api. A change was made to the build method of financial-aid-api by the core team that effected the build: https://github.com/island-is/island.is/pull/8192/files#diff-6dcba6421dee2c251e7211c916a97e452585a09dabca450615b2bd69fd728779.
The local build was fixed with this PR: https://github.com/island-is/island.is/pull/8317, but the DEV is still broken.
This change to revert is not certain to fix the problem on DEV but is safe to do after talking to the core team.

fix(fa): Use another build executor

---

apps/web/screens/Project/Project.tsx

* I recently moved the breadcrumbs to the wrapper but forget to remove them from subpage's, resulting in double breadcrumbs
* This change fixes that issue

fix(web): Project subpage double breadcrumbs

---

apps/service-portal/src/components/Greeting/Greeting.tsx
apps/service-portal/src/screens/Dashboard/Dashboard.css.ts
apps/service-portal/src/screens/Dashboard/Dashboard.tsx

Revert image on dashboard going under the cards
Make name heading smaller to match design
Comments from PO
Before:
After:

revert(service-portal): image going under cards

---

apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
apps/judicial-system/backend/src/app/formatters/formatters.ts
apps/judicial-system/backend/src/app/messages/notifications.ts

[Asana](https://app.asana.com/0/1199153462262248/1202861834321035/f)
An SMS that gets sent to prosecutors when a court has received their case currently says 
```
Héraðsdómur Reykjavíkur hefur móttekið kröfu um **fjárdráttur** sem þú sendir..
```
With this PR it changes this to 
```
Héraðsdómur Reykjavíkur hefur móttekið kröfu um **ákæru** sem þú sendir..
```
We're also changing the text in an email that is sent to prosecutors when they are invited to the court hearings. It currently says 
```
Subject: 
Fyrirtaka í máli S-4444/2022
Body: 
Héraðsdómur Reykjavíkur hefur staðfest fyrirtökutíma fyrir kröfu um gæsluvarðhald.
Fyrirtaka fer fram 14. september 2022, kl. 12:00.
Dómsalur: 201.
Dómari: Amy Madison Gray.
```
With this PR it changes to
```
Subject: 
Þingfesting í máli S-4444/2022 …
```

fix(j-s): Fix text in notifications in indictments

---

libs/api/domains/national-registry/src/lib/nationalRegistry.service.ts

From the Einstaklingar endpoint on gender code
```
{
"kodi": "7",
"lysing": "Kynsegin/annað fullorðinn"
}
```

fix(national-registry): Transgender adults can be parents

---

apps/web/screens/Category/Category/Category.tsx

* Currently articles aren't appearing on the category pages due to a limit of how many are fetched
* This fixes that issue
* There are 176 articles on a particular category page and only 150 of them are appearing

chore(web): Hotfix - Increase number of articles fetched on category page (#8362)

---

libs/application/templates/financial-statements-inao/src/lib/messages.ts

a few duplicate id-s for messages

fix(financial-statement-inao): rename message duplicate

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx

* The hsn slug was missing from the list and that means that the larger island.is footer is below the hsn footer, we want to change that.

chore(web): Add hsn slug to footerEnabled list

---

apps/air-discount-scheme/backend/src/app/modules/nationalRegistry/nationalRegistry.service.ts

Re-introduces code that anticipates null names from the national registry.
Some users only have null values associated with their names except in their fullName field.
This, unfortunately, has to be taken into account.

fix(ads): Anticipate null names from NREG

---

apps/air-discount-scheme/backend/src/app/modules/nationalRegistry/nationalRegistry.service.ts

Need to reconsider how names are introduced but a fix(revert) is needed for now
Right now the cache will be invalid for any user who logs on

fix(ads): Revert to old name functionality in ADS for now

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx

* Hotfix PR, here's the PR that got merged to main: https://github.com/island-is/island.is/pull/8475)
* We want to have the correct footers on the hsn organization page

feat(web): Hotfix - add hsn slug to footer enabled list (#8475)

---

apps/web/hooks/useLinkResolver/useLinkResolver.ts

* There's an accidental 'o' in the english projectnews link that should be a 'p'

fix(web): Wrong english project news link

---

apps/judicial-system/backend/src/app/modules/case/filters/case.filters.spec.ts
apps/judicial-system/backend/src/app/modules/case/filters/case.filters.ts

[Asana - Snúa við blocking logic í controller guards](https://app.asana.com/0/1199153462262248/1202974314193379/f)
- Default to block access to cases with a given role or institution in a given state 
- More secure if we add new institution types, user roles and case states

chore(j-s): default to block access too new states

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/Themes/RikislogmadurTheme/RikislogmadurFooter.css.ts
apps/web/components/Organization/Wrapper/Themes/RikislogmadurTheme/RikislogmadurFooter.tsx
apps/web/components/Organization/Wrapper/Themes/RikislogmadurTheme/RikislogmadurHeader.css.ts
apps/web/components/Organization/Wrapper/Themes/RikislogmadurTheme/RikislogmadurHeader.tsx

* Added a header and footer component for the Ríkislögmaður organization page
* (I noticed that all organization headers and footers aren't dynamically imported which I believe is increasing the bundle size for no reason, I'll have to address that in another PR (if you were wondering))

feat(web): Add header and footer for Ríkislögmaður's organization page

---

apps/web/screens/Search/Search.tsx
apps/web/screens/queries/Search.tsx
libs/api/domains/content-search/src/lib/enums/searchableContentTypes.ts
libs/cms/src/lib/generated/contentfulTypes.d.ts
libs/cms/src/lib/models/lifeEventPage.model.ts
libs/cms/src/lib/search/importers/lifeEventsPage.service.ts

* We recently reused the life event pages to write about the Digital Iceland services but we forgot to tweak the search results page (as of right now you see "Innskráning fyrir alla" tagged as a life event, which isn't quite right)
* We want to remove the tag from life event pages that are used as a Digital Iceland service since it's wrong to talk about the services as life events

fix(web): Remove life event tag from Digital Iceland services in search results

---

apps/web/screens/Search/Search.tsx
apps/web/screens/queries/Search.tsx
libs/api/domains/content-search/src/lib/enums/searchableContentTypes.ts
libs/cms/src/lib/generated/contentfulTypes.d.ts
libs/cms/src/lib/models/lifeEventPage.model.ts
libs/cms/src/lib/search/importers/lifeEventsPage.service.ts

original PR can be seen here: https://github.com/island-is/island.is/pull/8524

feat(web): Hotfix - life event tag removed for digital iceland service in search results

---

.github/CODEOWNERS

* Stefna is very frequently working on content models and contentful related things so it's about time we are codeowners :)

chore(web): Add stefna as codeowner of libs/cms

---

apps/web/screens/Project/utils.tsx

* We want to render the smaller version of the island.is footer if there already is a project page footer present

feat(web): Change what footer gets rendered depending on theme on Project pages

---

apps/web/screens/Project/utils.tsx

Hotfix PR (see PR merged to main here: #8548

feat(web): Hotfix - show small island is footer if project footer present

---

apps/web/screens/Search/Search.tsx

* Added an enum instead of "hardcoding" the pageType string check
* Removed images for Digital Iceland Service Anchor page type in search results

feat(web): Remove digital iceland service images in search results

---

.github/CODEOWNERS

chore(codeowners): remove vice versa as codeowners

---

apps/services/search-indexer/infra/search-indexer-service.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
libs/cms/src/lib/search/contentful.service.ts

* The search-indexer is calling Contentful but getting back a "Response too big" response
* Changing the chunk size of the fetch locally helped with indexing so having an env variable to change in the deployed environment might not be such a bad idea

feat(search-indexer): Add env variable for chunk size of contentful fetch

---

.github/CODEOWNERS

* Stefna recently became a codeowner of web and libs/cms and since we are expecting to hotfix a few things before the next release we'd like to also change the codeowners on the release branch

chore(web): Change codeowners due to hotfixes before next release

---

libs/application/templates/institution-collaboration/src/lib/messages.ts

Namespace had been changed to ia.application.service: which wasnt configured in appicationtypes and resulted in contentful not finding the strings.
Translations couldnt be updated.

chore(ia): Fix application namespace translation

---

apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunNordurlandsTheme/HeilbrigdisstofnunNordurlandsFooter.tsx
apps/web/components/Organization/Wrapper/Themes/LandkjorstjornTheme/LandkjorstjornFooter.tsx
apps/web/components/Organization/Wrapper/Themes/LandlaeknirTheme/LandlaeknirFooter.tsx

* If a footer item has a link it doesn't appear on the web
* We want footer item titles to render as links the CMS entry has a link attribute

feat(web): Render footer item links if they are present

---

libs/api/domains/license-service/src/lib/client/driving-license-client/drivingLicenseService.api.ts

Took a change from this PR
* https://github.com/island-is/island.is/pull/8606
The drivers license service seems to return 400 when a user has an expired/invalid license. This isn't an error and thus shouldn't be thrown!

feat(service-portal): Hotfix - drivers license error spam

---

libs/cms/src/lib/search/contentful.service.ts

* Remove nested entries from search-indexer
* This is causing an issue regarding syncing content on the web

feat(search-indexer): Remove nested entries from search-indexer

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
libs/application/template-api-modules/src/lib/modules/templates/parental-leave/smsGenerators/assignOtherParentSms.ts

fixing issue where the sms to otherparent would not have the link in it.

fix(parental-leave): fix assign other parent sms not containing link

---

libs/service-portal/information/src/components/ChildView/ChildView.tsx

Somehow this went past me in the code-review in a [recent code change of this file](https://github.com/island-is/island.is/commit/c04ddb880b6cb1b2adfdf1d9c19ba9f83e4b7e78). This was accidentally reversed. Reverting the reverse to set it back to normal 🤝

fix(service-portal): Revert reverse child modal enabling

---

libs/auth-api-lib/src/lib/delegations/delegationScope.service.ts

After removing identity resources from delegation scopes we need to set ApiScopes to be required in `findAllValidCustomScopesTo`.
To prevent errors when scopes are no longer supports delegations or are expired.

fix(auth-api): Set ApiScope include to be required in findAllValidCustomScopesTo

---

apps/web/components/ServiceWeb/SearchInput/SearchInput.tsx
apps/web/screens/ServiceWeb/Search/ServiceSearch.tsx
libs/cms/src/lib/models/supportCategory.model.ts

* There was a bug regarding service web search when the url was /adstod/leit
* This change addresses that issue

fix(web): Search route for service web

---

apps/web/components/ServiceWeb/SearchInput/SearchInput.tsx
apps/web/screens/ServiceWeb/Search/ServiceSearch.tsx
libs/cms/src/lib/models/supportCategory.model.ts

* After adding english support for the service web the search input was acting off when the path was /adstod/leit or /en/help/search
* This change fixes that issue

fix(web): Search route fix for service web

---

libs/service-portal/finance/src/screens/FinanceTransactions/FinanceTransactions.tsx

preselect finance filter for transactions
Screen can become empty to start with unless pre-selected.

fix(service-portal): Preselect finance filter for transactions

---

apps/web/screens/queries/fragments.ts

* Images were not appearing on the web when they were inside a slice, this change adds that feature
* Content on the web already presumed that this would work, we want to add this feature because it isn't uncommon to want to add an image inside a rich text field

feat(web): Add ImageFields to GraphQL query for slices

---

apps/web/components/Organization/Slice/AccordionSlice/AccordionSlice.tsx
apps/web/components/Organization/Slice/Districts/DistrictsSlice.tsx
apps/web/components/Organization/Slice/FeaturedArticles/FeaturedArticlesSlice.tsx
apps/web/components/Organization/Slice/MultipleStatistics/MultipleStatistics.tsx
apps/web/components/Organization/Slice/OverviewLinks/OverviewLinks.tsx
apps/web/screens/queries/Article.ts
apps/web/screens/queries/Organization.tsx
apps/web/screens/queries/Project.tsx
apps/web/screens/queries/fragments.ts
libs/cms/src/lib/generated/contentfulTypes.d.ts
libs/cms/src/lib/models/accordionSlice.model.ts
libs/cms/src/lib/models/districts.model.ts
libs/cms/src/lib/models/featuredArticles.model.ts
libs/cms/src/lib/models/multipleStatistics.model.ts
libs/cms/src/lib/models/overviewLinks.model.ts

* If someone adds a faqlist inside a onecolumn text it won't appear on the web due to a graphql query, this change tweaks graphql richtext queries to support nested slices
* Add a way to optionally render a border above each slice
* Removed powerbislice related fields from contentful types since it was causing an error due to the slicetype not being in the code (that's because the powerbi slice is still in the works so it's safe to remove the type)

feat(web): Change graphql queries to support nested slices and add optional border above accordion slice

---

libs/shared/connected/src/utils/sortAlpha.ts

* ð was missing from the alphabet, so I added it

feat(web): Add ð to alphabetical sorting

---

apps/judicial-system/web/src/components/CaseInfo/CaseInfo.tsx

[Asana - LÖKE nr tögg, bæta við bili fyrir neðan](https://app.asana.com/0/1199153462262248/1202972048201126/f)
- Add margin bottom under police case number tags
- Looks better
| Before | After |
| - | - |
| ![Screenshot 2022-10-14 at 15 15 38](https://user-images.githubusercontent.com/5700902/195882245-06670b19-a2c7-4f82-9286-823fd26d5678.png) | ![Screenshot 2022-10-14 at 15 15 28](https://user-images.githubusercontent.com/5700902/195882465-edc63a50-3d24-484b-aabd-01f6037b3013.png) |

feat(j-s): add more margin under police case number tags

---

apps/judicial-system/web/src/routes/Prosecutor/Indictments/PoliceCaseFiles/PoliceCaseFilesRoute.tsx
apps/judicial-system/web/src/utils/hooks/useS3UploadV2/useS3UploadV2.ts

[Asana - Málsgögn - upload-skjár fyrir gagnapakka](https://app.asana.com/0/1199153462262248/1203046355378025/f)
- Fix files being displayed stuck in progress state after upload
- Send both the previous id and new id to the `setSingleFile` to be able to find the file
| Before | After |
| - | - |
| ![Screenshot 2022-10-17 at 15 48 40](https://user-images.githubusercontent.com/5700902/196223689-103d858c-cd82-4ded-9527-54a1fe78eccd.png) | ![Screenshot 2022-10-17 at 15 48 22](https://user-images.githubusercontent.com/5700902/196223694-dae6ee8e-a2e3-4171-ba71-e6b648b5dd12.png) |

fix(j-s): fix files being displayed in progress state

---

apps/api/esbuild.json

* It seems that api project is crashlooping due to this package missing

fix(api): Add duplexer3 to esbuild.json

---

apps/web/components/NewsList/NewsList.tsx

* The NewsList link is wrong on the english page due to a missing locale for the linkResolver
* This change fixes that issue

fix(web): Add locale to linkResolver for newslist

---

apps/web/screens/Organization/Syslumenn/Auctions.tsx
apps/web/screens/queries/Organization.tsx
libs/api/domains/syslumenn/src/lib/models/syslumennAuction.ts
libs/clients/syslumenn/src/lib/__mock-data__/responses.ts
libs/clients/syslumenn/src/lib/syslumennClient.types.ts
libs/clients/syslumenn/src/lib/syslumennClient.utils.ts

Show the new field `auglysingatexti` in the Auctions listing.
Syslumenn have added a new field for showing information specific for a given Auction. They've requested that this field value is shown in the Auctions listing.

feat(web): Syslumenn / Auction publish text

---

apps/service-portal/src/index.html
libs/localization/src/lib/LocaleContext.tsx

Update `lang` attribute to account for the current language.
Even though we do not need to account for SEO in the service portal..
We have some comments regarding the `<html lang="">` tag on the service-portal. It can be confusing for some assisted technologies like screen readers to go to a page in one language when the lang attr is showing a different language.
Details here: https://accessibility.psu.edu/foreignlanguages/langtaghtml/

fix(service-portal): Update html lang

---

apps/web/screens/Article/Article.tsx
apps/web/screens/Organization/SubPage.tsx
apps/web/screens/Project/Project.tsx

* Now you can embed an accordion slice inside of richtext for the following content types
* Article
* Baby Article
* Project Page
* Project subpage
* Organization subpage

feat(web): Add AccordionSlice to rich text embed on articles, organization and project pages

---

apps/web/components/Organization/Slice/LifeEventPageListSlice/LifeEventPageListSlice.tsx

* Clicking on a card will be the same as clicking on the cards link
https://user-images.githubusercontent.com/43557895/197505788-e286d5bd-182c-44b5-a862-37be94d63203.mov

feat(web): Digital Iceland Service Card acts as a link

---

apps/web/screens/Organizations/Organizations.tsx
apps/web/utils/sortAlpha.ts

* On the /s page we were sorting with the localeCompare function but that doesn't correctly sort the items in an alphabetical order
* So instead I used the sortAlpha utility function which handles alphabetical sorting

fix(web): Correctly sort organizations by title

---

libs/cms/src/lib/search/importers/supportQNA.service.ts

* We recently wanted to ignore relatedLinks field in the circularity check for the SupportQNA content type but I forgot to add the "fields" field before so the last fix didn't work.
* See last PR https://github.com/island-is/island.is/pull/8693

fix(web): SupportQNA circularity check

---

libs/application/templates/parental-leave/src/fields/PeriodsSectionImage/ConclusionImageScreen.tsx

If applicant is receiving benefits then we don't want to show the text about employers on the final screen.

fix(parental leave): Don't show employer text for beneficiaries in final screen

---

apps/web/screens/LifeEvent/LifeEvent.tsx
libs/cms/src/lib/models/sectionWithImage.model.ts

* The code isn't robust enough so when fields were missing from Contentful the user would see a 500 page on the web
* This change addresses that issue

chore(web): Make sectionwithimage text optional as well as life event page image

---

libs/cms/src/lib/models/supportQNA.model.ts

* There was a missing slash so all related links of a supportqna lead to the wrong place
* This change adds that missing slash

fix(web): SupportQNA link

---

libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx

Fixing button with long title doubling. Button container made wider.
. 

fix(service-portal): button doubling on smaller screens

---

apps/judicial-system/api/src/app/modules/feature/feature.controller.ts
libs/judicial-system/formatters/src/lib/formatters.spec.ts
libs/judicial-system/formatters/src/lib/formatters.ts

- More graceful handling for string split
- Handles strings like:
- `feature1, otherFeature`
- `feature1,otherFeature`
- `feature1 otherFeature`
- `feature1 otherFeature `

fix(j-s): fix hiddenFeatures split

---

libs/auth-api-lib/src/lib/delegations/DelegationConfig.ts

See subject.
To make 1-level deep delegations work consistently.

fix(auth): Allow granting company and finance scopes 1-level deep

---

apps/web/components/Organization/Slice/OverviewLinks/OverviewLinks.tsx
libs/cms/src/lib/models/introLinkImage.model.ts

* Contentful allows you to publish content even though required fields are missing (on other locales than the default one)
* This allows Contentful users to cause 500 errors on english pages because the code expects fields to be there when they are not
* This change addresses that issue for the IntroLinkImage content type (but there are probably more content types which are like this)

chore(web): Make fields IntroLinkImage fields optional to prevent graphql errors on english pages

---

libs/cms/src/lib/models/html.model.ts
libs/cms/src/lib/search/importers/utils.ts
libs/island-ui/contentful/src/lib/RichTextRC/defaultRenderNode.tsx

* We've seen that entry-hyperlinks can contain circular data (since we are referencing an entry which might reference an entry that references the original entry and so forth) which has been causing some issues when extracting strings from the object (since if the data is circular then that string extraction function will never end)
* This change removes all fields from entry-hyperlinks except for what's important (the actual values that make up the url)
* By doing this we no longer have to worry about making entry-hyperlinks in Contentful since we cut off everything that isn't necessary to make up the urls in the code
* While I was at it I also noticed some of the urls were wrong when the locale wasn't set to Icelandic so I fixed that as well

fix(web): Removed entry hyperlink fields that might cause circularity when mapping html

---

apps/web/components/Organization/Slice/LifeEventPageListSlice/LifeEventPageListSlice.tsx

feat(web): Show title above Life event page list slice if it's present

---

apps/web/components/Organization/Slice/LifeEventPageListSlice/LifeEventPageListSlice.tsx

This is a cherry-picked commit that we'd like to hotfix

feat(web): Hotfix - Show title above Life event page list slice if it's present (#8803)

---

libs/service-portal/settings/access-control/src/screens/AccessControl/AccessControl.tsx

Apollo seams to be caching authDelegtions query in delegation access control screen and because of that No data screen is displayed when you add delegation for the first time
Needs fixing on dev and prod

fix(service-portal):  Apollo caching delegations

---

apps/web/components/Organization/Slice/SliceMachine.tsx
apps/web/screens/Organization/Home/Home.tsx

* We were asked to move the content up a bit (no need to have padding top for the top slice)

feat(web): Remove paddingTop from first slice on Organization page if there is no description 

---

apps/web/components/Organization/Slice/SliceMachine.tsx
apps/web/screens/Organization/Home/Home.tsx

This is a cherry-pick commit that we'd like to hotfix in since the layout change was requested by Digital Iceland

feat(web): Hotfix - Remove paddingTop from first slice on Organization page if there is no description  (#8818)

---

apps/web/screens/Category/Category/Category.tsx

* Articles weren't sorted correctly in an alphabetical order on the categories screen (/flokkur)
*This code change addresses that issue

chore(web): Sort articles on categories screen alphabetically

---

apps/web/components/Organization/Slice/AccordionSlice/AccordionSlice.tsx
libs/island-ui/contentful/src/lib/RichTextRC/defaultRenderNode.tsx

This is a cherry-picked commit that we'd like to hotfix

feat(web): Hotfix - Allow for nested accordion slices (#8779)

---

apps/web/components/Organization/Slice/AccordionSlice/AccordionSlice.tsx
apps/web/screens/queries/fragments.ts
libs/cms/src/lib/generated/contentfulTypes.d.ts
libs/cms/src/lib/models/accordionSlice.model.ts

* Add boolean field to Accordion Slice in Contentful called showTitle
* Add dropdown field to Accordion Slice in Contentful so we can choose what kind of heading element the title (and child titles) will be rendered as
* It's sometimes useful to be able to hide the accordion slice title
* We want to be able to change the semantics of the page so that it's more accessible

feat(web): Optionally render Accordion Slice title

---

apps/services/auth/public-api/src/app/modules/delegations/actorDelegations.controller.spec.ts
libs/auth-api-lib/src/lib/delegations/delegations.service.ts

Fix bug.
The logic incorrectly handled company and person delegations.

fix(auth): Fix issue where delegations are assumed deceased

---

apps/web/components/NewsItems/Item.tsx
apps/web/components/NewsItems/NewsItems.tsx
apps/web/components/Organization/Slice/LatestNewsSlice/LatestNewsSlice.tsx
apps/web/components/Organization/Slice/OneColumnText/OneColumnTextSlice.tsx
apps/web/components/Organization/Slice/SliceMachine.tsx
apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/screens/Organization/Home/Home.tsx
apps/web/screens/Organization/Home/LandingPageFooter/LandingPageFooter.css.ts
apps/web/screens/Organization/Home/LandingPageFooter/LandingPageFooter.tsx
apps/web/screens/Organization/Home/LandingPageFooter/index.ts
apps/web/screens/Organization/SubPage.tsx
apps/web/screens/queries/Organization.tsx
apps/web/screens/queries/fragments.ts
libs/cms/src/lib/generated/contentfulTypes.d.ts
libs/cms/src/lib/models/organizationPage.model.ts

* I added a new theme to organization pages called "landing_page"
* So we can make cards on island.is/s link to a landing page for an organization on the island.is web
https://user-images.githubusercontent.com/43557895/199037034-de72b2cb-9ef5-473d-8d3f-3e996547dc35.mov

feat(web): Add landing page theme to Organization pages

---

apps/judicial-system/web/src/components/AccordionItems/IndictmentsCaseFilesAccordionItem/IndictmentsCaseFilesAccordionItem.tsx

[Asana](https://app.asana.com/0/1199153462262248/1203046355378049/f)
Reset chapter and orderWithinChapter if ordered not in a chapter
Bug

fix(j-s): Reset chapter and orderWithinChapter if ordered not in a chapter

---

apps/services/auth/delegation-api/src/app/delegations/test/meDelegations.access.spec.ts
apps/services/auth/delegation-api/src/app/delegations/test/meDelegations.auth.spec.ts
apps/services/auth/delegation-api/src/app/delegations/test/meDelegations.filters.spec.ts
apps/services/auth/delegation-api/src/app/delegations/test/test-data.ts
apps/services/auth/delegation-api/src/app/delegations/test/utils.ts
apps/services/auth/delegation-api/src/app/domains/test/domains.controller.spec.ts
apps/services/auth/delegation-api/test/access-test-cases.ts
apps/services/auth/delegation-api/test/fixtures/fixture-factory.ts
apps/services/auth/delegation-api/test/fixtures/types.ts
apps/services/auth/delegation-api/test/setup.ts
apps/services/auth/public-api/src/app/modules/delegations/actorDelegations.controller.spec.ts
apps/services/auth/public-api/src/app/modules/delegations/meDelegations.controller.spec.ts
apps/services/auth/public-api/test/utils.ts
libs/auth-api-lib/src/lib/delegations/delegations-outgoing.service.ts
libs/auth-api-lib/src/lib/delegations/models/delegation.model.ts
libs/services/auth/testing/src/index.ts
libs/services/auth/testing/src/utils/delegations.ts
libs/services/auth/testing/tsconfig.json
libs/services/auth/testing/tsconfig.spec.json

Filter delegation endpoints so they match which scopes the user can manage delegations for.
Includes an API test suite for this.
This is needed for DelegationsV2

feat(auth): Filter delegations based on user access

---

libs/application/templates/parental-leave/src/fields/Review/Review.tsx

Not show employer email and phone number if receiving benefits in review screen
before:
after:

fix(parental leave): not show employer email and phone number if receiving benefits

---

apps/judicial-system/web/src/components/AccordionItems/IndictmentsCaseFilesAccordionItem/IndictmentsCaseFilesAccordionItem.tsx

[Asana](https://app.asana.com/0/1199153462262248/1203284582867790/f)
Use maxWidth instead of width for case file names
Otherwise, the file names are centered instead of left aligned, which is weird

fix(j-s): Use maxWidth instead of width for case file names

---

apps/judicial-system/backend/src/app/formatters/pdf.ts

[Laga overflow í efnisyfirliti málaskrár pdf](https://app.asana.com/0/1199153462262248/1203265017403973/f)
Only adds "..." to text that is cut off.
Bug

fix(j-s): PDF Max Length

---

apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/Defendant.tsx
apps/judicial-system/web/src/routes/Prosecutor/components/DefendantInfo/DefendantInfo.tsx
apps/judicial-system/web/src/utils/hooks/useDefendants/index.ts

[Asana](https://app.asana.com/0/1199153462262248/1203337457990688/f)
Fix a bug where users are unable to change defendant after entering a ssn while creating an indictment

fix(j-s): Wrap updateDefendantState in useCallback

---

apps/web/components/Organization/Slice/EmailSignup/EmailSignup.tsx
apps/web/screens/queries/fragments.ts
libs/api/domains/mailchimp/src/lib/dto/emailSignup.input.ts
libs/api/domains/mailchimp/src/lib/emailSignup.resolver.spec.ts
libs/api/domains/mailchimp/src/lib/emailSignup.resolver.ts

* I forgot to use the email config field when mapping checkboxes to query parameter strings when sending the signup request to mailchimp, resulting in the checkbox fields not working :) 
* This change addresses that issue and will correctly map the checkbox values to mailchimp values

fix(web): Email Signup config

---

libs/application/template-api-modules/src/lib/modules/templates/financial-statements-inao/financial-statements-inao.service.ts

values is undefinef when novaluestatement is false should be the opposite

fix(financial-statement-inao):  values only undefined when novaluestatement is false

---

libs/content-search-toolkit/src/services/elastic.service.ts

Big objects are being logged, resulting in end-of-json. This should improve the filtering of objects being logged.
In my testing, full articles are getting logged, resulting in >44000 character long strings

fix(search-indexer): Fix filtering of logged objects

---

apps/services/auth/delegation-api/src/app/domains/domains.controller.ts
apps/services/auth/delegation-api/src/app/domains/test/domains.controller.spec.ts
apps/services/auth/delegation-api/test/access-test-cases.ts
libs/api/domains/auth/src/lib/dto/apiScopes.input.ts
libs/api/domains/auth/src/lib/dto/domainDirection.ts
libs/api/domains/auth/src/lib/dto/domains.input.ts
libs/api/domains/auth/src/lib/services-v1/meDelegations.service.ts
libs/api/domains/auth/src/lib/services-v2/apiScope.service.ts
libs/api/domains/auth/src/lib/services-v2/meDelegations.service.ts
libs/api/domains/auth/src/lib/services/actorDelegations.service.ts
libs/api/domains/auth/src/lib/services/domain.service.ts
libs/api/domains/auth/src/lib/services/types.ts
libs/auth-api-lib/src/lib/delegations/delegations-outgoing.service.ts
libs/auth-api-lib/src/lib/resources/delegation-resources.service.ts
libs/clients/auth/delegation-api/project.json
libs/clients/auth/public-api/project.json
libs/service-portal/access-control/delegations/src/components/access/AccessForm.tsx
libs/service-portal/access-control/delegations/src/hooks/useDomains.ts

[Extend scopes API to support incoming delegations UI](https://www.notion.so/Extend-scopes-API-to-support-incoming-delegations-UI-c8ab6d2436df4543ad26d03e948706e4)
[Extend domains API to support incoming delegations UI](https://www.notion.so/Extend-domains-API-to-support-incoming-delegations-UI-f0e87875e03f4234a5abc54a80e5869b)
Adding `direction` query parameter to `/domains`, `/ domains/:domainId/scope-tree` and `/domains/:domainId/scopes` endpoints.
To change default case to return all domains and all scopes in domain when not filtered by direction. Then support `direction=outgoing` to filter the list to filtered scopes for only allowed for outgoing delegations.
N/A

feat(delegation-api): Add domains and scope direction support for filtering

---

apps/system-e2e/src/tests/web/smoke/homepage.spec.ts

Since we are visiting a lot of web pages in homepage tests, those can take a while to finish. In some cases, they need just a tad over the 90 seconds limit. So marking those as slow should actually prevent them from failing and shorten the runtime all around.

chore(qa): Do not fail homepage tests due to a long list of pages to visit

---

apps/web/layouts/main.tsx
apps/web/pages/_error.tsx

* An error was occurring on the error page which meant the layout wasn't loading)
* Also I moved the console.error to the catch block instead of having it run each time the error page gets loaded (even though everything got loaded succesfully it would still log an error)

fix(web): Fix error that was appearing on the layout load of the error page (404 and 500)

---

libs/application/template-api-modules/src/lib/modules/templates/financial-statements-inao/financial-statements-inao.service.ts

Added extra try-catch around post for personal election in submitApplication
Trying to find out why the postFinancialStatementForPersonalElection is not found

feat(financial-statements-inao): Extra try-catch around post for personal election in submitApplication

---

apps/service-portal/src/components/MobileMenu/MobileMenu.css.ts
apps/service-portal/src/components/MobileMenu/MobileMenu.tsx

Postholf is disappearing under mobile header in mobile menu
when adding position param for alert banners, it was overwriting position already defined in css file. 

fix(service-portal): postholf disappearing in mobile menu

---

libs/service-portal/access-control/delegations/src/screens/GrantAccess/GrantAccess.tsx

Domain name was not updating in session storage when creating new delegation.

fix(service-portal): Fixes domain name update to keep in sync

---

apps/web/components/Organization/Slice/PowerBiSlice/PowerBiSlice.tsx
apps/web/components/connected/fiskistofa/SidebarShipSearchInput/SidebarShipSearchInput.tsx
libs/api/domains/powerbi/README.md

* When changing values in a powerbi dropdown the query params were out of date due to me presuming that the router.query object would update on shallow router.push, but it turns out it doesn't change
* This change fixes that issue
* (I also updated the README for the powerbi api domain)

fix(web): Power Bi Slice - Query params changing back to old values

---

apps/web/components/ServiceWeb/Forms/StandardForm/StandardForm.tsx
apps/web/screens/Organization/Services.tsx

* Fix suggestion links on service web (they weren't sending you to the question you clicked on but rather the category that question belonged to)
* Exclude mannaudstorg questions from the suggestions if we are not on their web
* Make services page more robust by not directly accessing the article group slug (we saw an issue regarding this and this change fixes that issue)

fix(web): Various fixes for the web project

---

apps/web/components/ServiceWeb/Forms/StandardForm/StandardForm.tsx
apps/web/screens/Organization/Services.tsx

* Make services code a bit more robust if there is a missing group
* Fix supportqna link for suggestions
* Exclude mannaudstorg from suggestions (unless we are on their web)
* Make services page more robust by not directly accessing the article group slug (we saw an issue regarding this and this change fixes that issue)

fix(web): Various fixes for the web project (#9201)

---

apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
apps/judicial-system/backend/src/app/formatters/formatters.ts
apps/judicial-system/backend/src/app/messages/notifications.ts
apps/judicial-system/backend/src/app/modules/notification/notification.service.ts

[Asana](https://app.asana.com/0/1199153462262248/1203046355378001/f)
Add defender revoked emails for indictments
Defenders need to know if their cases are revoked.
The email is 
```
Ákæra sem taka átti fyrir hjá Héraðsdómi Reykjavíkur fimmtudaginn 1. desember 2022, kl. 12:32, hefur verið afturkölluð.
Sakborningur: Bragagata 2, fd. 12.12.2000.
Dómstóllinn hafði skráð þig sem verjanda í málinu.
```

chore(j-s): Add defender revoked emails for indictments

---

apps/judicial-system/web/src/routes/Prosecutor/components/ProsecutorSection/ProsecutorSection.tsx
apps/judicial-system/web/src/routes/Prosecutor/components/ProsecutorSection/ProsecutorSectionHeading.strings.ts
apps/judicial-system/web/src/routes/Prosecutor/components/ProsecutorSection/ProsecutorSectionHeading.tsx

[Asana](https://app.asana.com/0/1199153462262248/1203176015076412/f)
Change tooltip for prosecutor section in indictments
The old text only applies to R-cases

chore(j-s): Change tooltip for prosecutor section in indictments

---

apps/web/components/SearchSection/SearchSection.tsx
libs/island-ui/core/src/lib/Box/Box.tsx
libs/island-ui/core/src/lib/Box/types.ts

- Add `data-testid` to the shared `Box` component
- Move `data-testid` on homepage image to container instead of graphic

fix(e2e): Fix brittle homepage test

---

libs/api/domains/assets/src/models/propertyDetail.model.spec.ts
libs/api/domains/assets/src/models/propertyDetail.model.ts

Fix asset filterfields for property owner.
It's wrong. And has already been hotfixed on prod.

fix(service-portal): assets filter fix

---

apps/web/components/connected/fiskistofa/SidebarShipSearchInput/SidebarShipSearchInput.tsx
apps/web/components/connected/fiskistofa/calculators/StraddlingStockCalculator/machine.ts
libs/cms/src/lib/environments/environment.ts

* As of right now if there isn't pre-existing information for a ship you won't be able to add categories and calculate values in the StraddlingStockCalculator
* I also added footerItem as a nested contentful type since I noticed it wasn't listed
* This feature was requested by the directorate of fisheries

fix(web): Straddling Stock calculator - Allow users to still calculate values even though server returns 404

---

apps/web/screens/Organization/Home/Home.tsx
apps/web/screens/Organization/OrganizationNewsArticle.tsx
apps/web/screens/Organization/OrganizationNewsList.tsx
apps/web/screens/Organization/PublishedMaterial/PublishedMaterial.tsx
apps/web/screens/Organization/Services.tsx
apps/web/screens/Organization/StafraentIsland/ApiCatalogue.tsx
apps/web/screens/Organization/StafraentIsland/ApiDetails.tsx
apps/web/screens/Organization/SubPage.tsx
apps/web/screens/Organization/Syslumenn/Auctions.tsx
apps/web/screens/Organization/Syslumenn/Homestay.tsx
apps/web/screens/Organization/Syslumenn/OperatingLicenses.tsx
apps/web/screens/Project/ProjectNewsArticle.tsx
apps/web/screens/Project/ProjectNewsList.tsx
apps/web/screens/Project/utils.tsx

* We noticed that if a user doesn't provide a primary link to a link group the web displays a 500 error, this change addresses that issue
* A contentful user should not be able to cause 500 errors on the web,

fix(web): Add fail safe to link group's primarylink field since it's been causing 500 errors

---

apps/web/components/connected/fiskistofa/SidebarShipSearchInput/SidebarShipSearchInput.tsx
apps/web/components/connected/fiskistofa/calculators/StraddlingStockCalculator/machine.ts
libs/cms/src/lib/environments/environment.ts

This PR contains a cherry picked commit that got merged to main (#9220)
We want to hotfix this change to prod since this was requested by the directorate of fisheries (Fiskistofa)

feat(web): Hotfix - Straddling Stock calculator - Allow users to still calculate values even though server returns 404

---

apps/web/components/Organization/OrganizationIslandFooter/OrganizationIslandFooter.css.ts
apps/web/components/Organization/OrganizationIslandFooter/OrganizationIslandFooter.tsx
apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/screens/Organization/Home/LandingPage/LandingPage.tsx

* When on small screens the links went outside of the viewport, so this change wraps the links
* Show the smalller version of the Ísland.is footer when on an organization landing page
* There was a missing key in a translation namespace so I added a key
https://user-images.githubusercontent.com/43557895/205031067-d475fb60-2262-4c56-a428-d646221d64a6.mov

feat(web): Organization footer UI improvements

---

apps/web/components/connected/electronicRegistrationStatistics/MonthlyStatistics/MonthlyStatistics.css.ts
apps/web/components/connected/electronicRegistrationStatistics/MonthlyStatistics/MonthlyStatistics.tsx

This PR contains a cherry picked commit that got merged to main (https://github.com/island-is/island.is/pull/9234)
We want to hotfix this change to prod since the statistics UI on prod is displaying incorrect data

fix(web): Hotfix - Electronic registration statistics UI not showing correct values via filter

---

apps/web/components/AnchorNavigation/AnchorNavigation.tsx
apps/web/components/NewsList/NewsList.tsx
apps/web/components/Organization/NewsArticle/NewsArticle.tsx
apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/screens/Category/Category/Category.tsx
apps/web/screens/LifeEvent/LifeEvent.tsx
apps/web/screens/News.tsx
apps/web/screens/Organization/OrganizationNewsArticle.tsx
apps/web/screens/Organization/OrganizationNewsList.tsx
apps/web/screens/Organization/PublishedMaterial/PublishedMaterial.tsx
apps/web/screens/Organization/Services.tsx
apps/web/screens/Organization/StafraentIsland/ApiCatalogue.tsx
apps/web/screens/Organization/StafraentIsland/ApiDetails.tsx
apps/web/screens/Organization/SubPage.tsx
apps/web/screens/Organization/Syslumenn/Auctions.tsx
apps/web/screens/Organization/Syslumenn/Homestay.tsx
apps/web/screens/Organization/Syslumenn/OperatingLicenses.tsx
apps/web/screens/Project/Project.tsx

* Webreader component added to organization pages (behind a feature flag)
* Web reader component added to life event pages (behind a feature flag)
* Web reader component added to news (behind a feature flag)
* Web reader component added to project pages (behind a feature flag)
* Fixed bug where category screen would jump to the top of the page on accordion close
* Add identifier to url on life event pages when a user click on an anchor link

feat(web): Add Webreader to more pages and tweak url hash for categories and life event pages

---

apps/web/components/connected/electronicRegistrationStatistics/MonthlyStatistics/MonthlyStatistics.tsx

* The registration type dropdown would default to "Allt" if the user changed what year was selected
* This change keeps the same registration type selected if the type exists for the newly selected year
https://user-images.githubusercontent.com/43557895/205661328-c6dcce34-a128-4923-8cd5-f1c845a12daf.mov
https://user-images.githubusercontent.com/43557895/205661103-fa04e14a-c4bf-481e-a725-637b7a8414e9.mov

feat(web): Electronic registration statistics - Keep registration type selection between years if possible

---

apps/web/components/AnchorNavigation/AnchorNavigation.tsx
apps/web/components/NewsList/NewsList.tsx
apps/web/components/Organization/NewsArticle/NewsArticle.tsx
apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/screens/Category/Category/Category.tsx
apps/web/screens/LifeEvent/LifeEvent.tsx
apps/web/screens/News.tsx
apps/web/screens/Organization/OrganizationNewsArticle.tsx
apps/web/screens/Organization/OrganizationNewsList.tsx
apps/web/screens/Organization/PublishedMaterial/PublishedMaterial.tsx
apps/web/screens/Organization/Services.tsx
apps/web/screens/Organization/StafraentIsland/ApiCatalogue.tsx
apps/web/screens/Organization/StafraentIsland/ApiDetails.tsx
apps/web/screens/Organization/SubPage.tsx
apps/web/screens/Organization/Syslumenn/Auctions.tsx
apps/web/screens/Organization/Syslumenn/Homestay.tsx
apps/web/screens/Organization/Syslumenn/OperatingLicenses.tsx
apps/web/screens/Project/Project.tsx

This PR contains a cherry picked commit that got merged to main (https://github.com/island-is/island.is/pull/9252)
* Add Webreader to more pages and tweak url hash for categories and life event pages
* Move readspeaker below title of organization pages
* Add webreader to news
* Use different feature flag for webreader news feature
* Add webreader to project pages
* Add comment

feat(web): Hotfix - Add Webreader to more pages and tweak url hash for categories and life event pages (#9252)

---

libs/clients/smartsolutions/src/lib/smartSolutions.api.ts
libs/clients/smartsolutions/src/lib/smartSolutions.types.ts

More robust logging for PkPass functionality
The service doesn't log errors in creation, only service errors.

feat(service-portal): improved logging for smart solutions

---

apps/services/auth/delegation-api/infra/delegation-api.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml

Fix the redis connection in this new auth service.
It needs a different URL since it's running in the IDS AWS account.

fix(auth): HOTFIX Redis url for services-auth-delegation-api in production

---

apps/services/auth/delegation-api/infra/delegation-api.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml

Fix the redis connection in this new auth service.
It needs a different URL since it's running in the IDS AWS account.

fix(auth): Redis url for services-auth-delegation-api in production

---

apps/services/auth/delegation-api/src/app/delegations/me-delegations.controller.ts
apps/services/auth/delegation-api/src/app/domains/domains.controller.ts
libs/auth-api-lib/seeders/data/scope-delegation-admin.ts
libs/auth/scopes/src/lib/admin-portal.scope.ts
libs/auth/scopes/src/lib/auth.scope.ts
libs/portals/shared-modules/delegations/src/module.ts

Add new scope for admin portal delegations.
So users can give access to delegations both in My Pages or in the Admin Portal.

feat(ap): New delegation scope for admin portal

---

libs/clients/middlewares/src/lib/createEnhancedFetch.spec.ts
libs/clients/middlewares/src/lib/createEnhancedFetch.ts
libs/clients/middlewares/src/lib/withErrorLog.ts

This is to make devops life easier. Error responses should generally
not include user PII and we already filter out national ids and more
from our logs.
We can always toggle this off on case-by-case basis.

feat(fetch): HOTFIX Default to log error response bodies

---

apps/web/components/NewsCard/NewsCard.tsx

fix(web): News Cards should display image if width of container is more than 600 px

---

apps/web/components/connected/fiskistofa/ShipSearch/ShipSearch.tsx
apps/web/components/connected/fiskistofa/SidebarShipSearchInput/SidebarShipSearchInput.tsx

This PR contains cherry picked commits from the PR #9335 which got merged to main, we'd like to hotfix this change in since fiskistofa.is needs this functionality since they're redirecting fiskistofa.is to island.is/s/fiskistofa

feat(web): Fiskistofa ship search query param names can be changed in cms (#9335)

---

apps/web/screens/Search/Search.tsx

* If a search result does not have a url or slug field it'll cause the web to show a 500 error
* This change addresses that issue

fix(web): Add fail-safe to slug field in search results

---

apps/web/screens/Search/Search.tsx

fix(web): Hotfix - Add fail-safe to slug field in search results (#9354)

---

apps/web/screens/queries/fragments.ts
libs/cms/src/lib/search/importers/organizationSubpage.service.ts

* Placing a faqlist or accordion inside a onecolumn text didn't work since we didn't query for them
* This change tweaks the query to support nested fields inside onecolumn text
* While I was at it I noticed a max call stack error if an accordion referenced a onecolumn text that referenced that accordion (causing a circularity which the extractStrings function would recurse infinitely on)

feat(web): Fetch nested fields in one column text

---

apps/web/screens/Organization/PublishedMaterial/PublishedMaterial.tsx
apps/web/screens/Organization/PublishedMaterial/components/PublishedMaterialItem/PublishedMaterialItem.tsx
apps/web/screens/Organization/Services.tsx
apps/web/screens/queries/Organization.tsx

This PR contains 2 cherry picked commits from commits that are on main 
* https://github.com/island-is/island.is/pull/9326
* https://github.com/island-is/island.is/pull/9363

fix(web): Hotfix - allow for different org page and org slug on published material page

---

libs/portals/shared-modules/delegations/src/constants/domain.ts
libs/portals/shared-modules/delegations/src/hooks/useDomains/useDomains.ts

Delegations is used both in service-portal and admin-portal. Queries must set the right default options to domain options.
This introduces default options by portal type

fix(portals-delegations): Portal specific default domain option

---

apps/web/components/connected/fiskistofa/ShipSearch/ShipSearch.tsx

* The url creation logic appended the query params twice since the entire url was used as the pathname instead of it just being the pathname
Example: 
`https://gamli.fiskistofa.is/veidar/aflastada/einstokskip?timabil=2223`
would become 
`https://gamli.fiskistofa.is/veidar/aflastada/einstokskip?timabil=2223?timabil=2223`

fix(web): Fiskistofa ship search - duplicated query param

---

apps/portals/admin/src/components/Header/Header.tsx
libs/shared/components/src/auth/UserMenu/UserButton.tsx
libs/shared/components/src/auth/UserMenu/UserDropdown.tsx
libs/shared/components/src/auth/UserMenu/UserMenu.spec.tsx
libs/shared/components/src/auth/UserMenu/UserMenu.tsx

Added support for some variations of the user menu.
- iconOnlyMobile prop to hide name in button.
- display people icon if user is logged in delegation.
- showLanguageSwitcher prop to show and hide language picker. Defaults to true
As per design.

fix(admin-poral): UserMenu updates

---

libs/application/templates/parental-leave/src/lib/messages.ts

Change text in generic file upload to ask two mothers to upload file from Livio if they have undergone artificial insemination
To try to get this documentation handed in with first upload of application and to try to avoid VMST having to go back and ask the applicants for this information after the application has been submitted.

fix(parental-leave): Change text in generic file upload

---

apps/judicial-system/web/src/components/ProsecutorSelection/ProsecutorSelection.tsx

[Takmarka val sækjanda við embætti notanda í nýju máli sem stonfað er úr LÖKE](https://app.asana.com/0/1199153462262248/1203447613452322/f)
- Limits the prosecutors available for case assignment to the user's prosecutors office when no creating prosecutor has been set.
- If a prosecutor from another prosecutors office is selected, then the user looses access to the case.

fix(j-s): Limit Prosecutor Selection

---

apps/judicial-system/backend/src/app/modules/case/case.service.ts
apps/judicial-system/backend/src/app/modules/file/file.service.ts

[Breyta stöðu case files úr STORED_IN_COURT í STORED_IN_RVG ef málsnúmer dómstóls breytist](https://app.asana.com/0/1199153462262248/1203447613452318/f)
- Resets case file states to STORED_IN_RVG when court case number is changed or removed.
- Otherwise, case files will. not be uploaded to court when a new court case number is assigned.

fix(j-s): Case File State

---

apps/web/components/Organization/Slice/AccordionSlice/AccordionSlice.tsx
apps/web/components/Organization/Slice/FeaturedArticles/FeaturedArticlesSlice.tsx
libs/island-ui/contentful/src/lib/EmbeddedVideo/EmbeddedVideo.tsx

* It was weird that featured articles would open in a new window
* The youtube regex match doesn't support video urls of the format: https://youtu.be/hX9Bnmn8fv8

fix(web): Open featured articles in same window and change youtube embed regex

---

apps/web/utils/richText.tsx
libs/island-ui/contentful/src/lib/RichTextRC/defaultRenderNode.tsx

* If an asset gets embedded inside some kind of nested structure (like inside of an unordered list item) it simply won't appear, this change addresses that issue
* I also added the TwoColumnText option to the richText function in the web project so if someone embeds a TwoColumnText inside of a rich text field it'll appear on the web

chore(web): Render nested embedded asset fields

---

apps/judicial-system/web/src/components/InfoCard/InfoCard.spec.tsx
apps/judicial-system/web/src/components/InfoCard/InfoCard.tsx
apps/judicial-system/web/src/components/InfoCard/InfoCardClosedIndictment.tsx
apps/judicial-system/web/src/routes/Court/InvestigationCase/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Court/RestrictionCase/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx

[Asana](https://app.asana.com/0/1199153462262248/1203335296623515/f)
Show defenders on closed indictment info card. If there are two defendants with defenders that have the same email address, we only show that defender once (because then they have the same defender.)
For clarity

chore(j-s): Show defenders on closed indictment info card

---

apps/judicial-system/web/src/routes/Court/InvestigationCase/CourtRecord/CourtRecord.tsx
apps/judicial-system/web/src/routes/Court/InvestigationCase/Ruling/Ruling.tsx
apps/judicial-system/web/src/routes/Court/RestrictionCase/CourtRecord/CourtRecord.tsx
apps/judicial-system/web/src/routes/Court/RestrictionCase/Ruling/Ruling.tsx
apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/PoliceDemands/PoliceDemands.tsx
apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/PoliceReport/PoliceReport.tsx
apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepFour/StepFour.tsx
apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepThree/StepThree.tsx
apps/judicial-system/web/src/utils/hooks/useDeb/index.tsx

[Asana](https://app.asana.com/0/1199153462262248/1203621685545197/f)
Refactor useDep hook to accept list of workingCase keys
By not accepting a list of keys, if there were multiple values that needed debouncing you'd have to call the hook multiple times i.e.
_old_
`useDep(workingCase, 'valueA')`
`useDep(workingCase, 'valueB')`
_new_
`useDep(workingCase, ['valueA',  'valueB'])`
You can also use a keyof workingCase for single values i.e.
`useDep(workingCase, 'valueB')`
https://user-images.githubusercontent.com/3789875/210052712-04089236-d2a4-48a9-976d-b7a49c4ed8e4.mov

chore(j-s): Refactor useDep hook

---

apps/services/auth/delegation-api/src/environments/environment.ts

As the delegation system is used both in service portal and admin portal, the api needs to support both `island.is` and `@admin.island.is` audience.
To authorize api requests from the admin porta.
N/A

fix(delegation-api): Add admin audience

---

apps/web/components/ChatPanel/WatsonChatPanel/WatsonChatPanel.tsx

* Now there's a close button in the watson chat panel (previously there was only a minimize button)

feat(web): Add close button to watson chat panel

---

libs/api/domains/vehicles/src/lib/api-domains-vehicles.type.ts
libs/api/domains/vehicles/src/models/usersVehicles.model.ts

Fix date type error after auto generating client config in another PR 
See #9488

fix(service-portal): HOTFIX - vehicle history type error (#9488)

---

libs/clients/transport-authority/vehicle-owner-change/src/lib/vehicleOwnerChangeClient.service.ts

Fetch the correct errorNo for vehicle locks when validating vehicle for ownerchange
To be able to translate the error message (using text from contentful)

fix(transport-authority-transfer-of-vehicle-ownership): Use correct errorNo for vehicle locks

---

apps/air-discount-scheme/backend/src/app/modules/discount/discount.controller.ts
libs/air-discount-scheme/types/src/lib/user.ts

From our air discount codes, airline companies are using the user info value for their frontends. The legacy value for genderqueer shall be presented externally until all parties are ready to switch.
Since a database migration has already taken place for user data I'd recommend overwriting the response upon retrieval but leave everything else as is.

fix(air-discount-scheme): Return legacy gender value for external contacts

---

libs/content-search-toolkit/README.md
libs/content-search-toolkit/src/services/elastic.service.ts
libs/content-search-toolkit/src/services/utils/index.ts
libs/content-search-toolkit/src/services/utils/utils.spec.ts

Production web content isn't being updated due to circular error objects being processed by a function that can't handle circular data. This change (containing a cherry-pick commit from main) addresses that issue
* Add first draft of a circular fail safe implementation
* Call correct function and type function in a generic manner
* Move function to utils.ts
* Renamed param
* Add unit test and refactor code
* Combine tests into one single test
* Add seperate circularity check
* Update README

fix(search-indexer): Hotfix - Add circularity fail-safe to error filtering (#9337)

---

apps/air-discount-scheme/backend/seeders/20211108100835-development.js

Make testing easier.
Gervimaður Færeyjar has a child '2222222229' so we ensure that they both are inserted upon generating noisy random data.

fix(ads): More test data on local development

---

apps/judicial-system/web/src/utils/formHelper.ts

[Retry virkar ekki eftir að ekki tekst að hlaða upp skrá](https://app.asana.com/0/1199153462262248/1203374349779618/f)
- Ignores case files that are attached to a police case when displaying "Önnur gögn" on the screen "Dómskjöl".

fix(j-s): Other Case Files

---

apps/tools/contentful-role-permissions/constants/index.ts
apps/tools/contentful-role-permissions/utils/index.ts

* The dropdown was missing a few content types since we've surpassed a 100 in Contentful (and the api only returns a 100 at a time)
* Also since the mailingListSignupSlice content type will be deleted soon I added it's replacement as a default option
* We need to see all content types in the dropdown to be able to set correct permissions for users

fix(contentful-role-permissions): Load all content types, not just the first 100 in Contentful dev tool

---

apps/portals/admin/src/components/ModuleSwitcher/ModuleSwitcher.tsx
apps/portals/admin/src/components/ModuleSwitcher/ModuleSwitcherDesktop.css.ts
apps/portals/admin/src/components/ModuleSwitcher/ModuleSwitcherDesktop.tsx
apps/portals/admin/src/components/ModuleSwitcher/ModuleSwitcherHeader.tsx
apps/portals/admin/src/components/ModuleSwitcher/ModuleSwitcherMobile.tsx
apps/portals/admin/src/screens/Dashboard/Dashboard.tsx
libs/portals/core/src/hooks/useSingleNavigationItem.spec.tsx
libs/portals/core/src/hooks/useSingleNavigationItem.ts
libs/portals/core/test/useSingleNavigationItem-test-cases.ts

Few updates to the module switcher:
- Removing right border and displaying only "Stjórnborð" when navigating to access denied modules when static.
- Remove completely if user doesn't have any access to any module.
To fix awkward module switcher for those cases.

refactor(portals-admin): Update static module switcher when outside active module

---

apps/services/auth/delegation-api/src/app/delegations/test/me-delegations.filters.spec.ts
libs/auth-api-lib/src/lib/delegations/delegations-outgoing.service.ts

Stop actor from being able to find delegation to self with the `otherUser` filter.
To stop the user from going into the delegation detail view to modify delegation for self.
N/A

fix(delegation-api): Stop actor from being able to find delegations to self with otherUser filter.

---

libs/portals/admin/regulations-admin/src/components/EditBasics.tsx
libs/portals/admin/regulations-admin/src/lib/messages.ts
libs/portals/admin/regulations-admin/src/screens/Edit.tsx
libs/portals/admin/regulations-admin/src/screens/Home.css.ts
libs/portals/admin/regulations-admin/src/screens/Home.tsx
libs/portals/admin/regulations-admin/src/state/useDraftingState.ts
libs/portals/admin/regulations-admin/src/utils/dataHooks.ts

* Add dropdown for creating new regulations
There can be more than one type of regulation created. Selection in the first step.

feat(regulations-admin): Update create regulation selection button

---

libs/auth-api-lib/seeders/data/helpers/createScope.ts

Would be nice to include #9638 in the release so the IDS scope seeding migrations are more complete. Otherwise they require more manual work before the admin portal starts working.

feat(auth): Create ApiScopeUserClaim models in scope migrations. (#9638) HOTFIX

---

apps/web/components/Organization/Slice/SliceMachine.tsx
apps/web/components/connected/fiskistofa/ShipSearchBoxedInput/ShipSearchBoxedInput.tsx
apps/web/components/connected/fiskistofa/index.ts
apps/web/utils/richText.tsx
libs/cms/src/lib/generated/contentfulTypes.d.ts

* Add connected component for the Directorate of fisheries organization page
* This was a requested by the Directorate of fisheries
* The search input used to be in the sidebar but that wasn't an obvious enough spot for the users so this was deemed a better solution

feat(web): Ship search component for directorate of fisheries organization pages

---

apps/air-discount-scheme/backend/infra/backend.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

Give our graphql api access to the air-discount-scheme-backend.
To enable the new ADS UIs on island.is.

infra: Grant graphql api access to air-discount-scheme-backend

---

apps/air-discount-scheme/web/infra/web.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

Add ingress external namespace to enable internet traffic.
#9672 added islandis namespace to the backend which is applied to the whole air-discount-scheme namespace so `nginx-ingress-external` needs to be added explicitly to the web app.

fix(ads): Add nginx-ingress-external to air discount scheme web.

---

apps/web/screens/Article/Article.tsx
apps/web/screens/Organization/Home/Home.tsx
apps/web/screens/Organization/Home/LandingPage/LandingPageFooter.tsx

* Now forms can be embedded inside the rich text field of articles
* The organization logo was missing from organization pages that had the landing page theme

feat(web): Add form to articles, show organization logo for landing pages

---

libs/application/templates/accident-notification/src/forms/AccidentNotificationForm/aboutTheAccidentSection.ts

https://app.clickup.com/t/326kt3k
Make fields required
They were supposed to be required but weren't

fix(applications): Accident notification required fields are now actually required

---

apps/application-system/form/src/routes/Applications.tsx

https://app.clickup.com/t/2ymbcry
Display error screen for unknown application
It is the expected behaviour

fix(applications): Improved routing for applications to display error on unknown application

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.spec.ts
libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts

Start date was missing returning constants if the applicant chose to start on actual birth date/expected birth date if the period was all personal and trasferred rights.

fix(parental-leave): start date missing constant return (#9746)

---

libs/content-search-toolkit/src/services/elastic.service.ts
libs/content-search-toolkit/src/services/utils/index.ts
libs/content-search-toolkit/src/services/utils/utils.spec.ts

* I noticed that ElasticSearch has been throwing an IllegalArgumentException and I believe it might be due to the request chunk size being invalid 
Here below we can see the bulkBody of the error and the first element in the list is a document (it should be an operation like update, delete or something of the sort https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#bulk-api-request-body)
Since the delete operation is only a single line and all other operations (as far as I can tell) are 2 lines then the code that was there previously was incorrect since it relied on an even numbered chunk size.
So I added a variant chunk size depending on the data we have at hand.

fix(search-indexer): Invalid ElasticSearch bulk request chunk size

---

libs/content-search-toolkit/src/services/elastic.service.ts
libs/content-search-toolkit/src/services/utils/index.ts
libs/content-search-toolkit/src/services/utils/utils.spec.ts

* Use correct number of operations instead of relying on an even number since delete is single line
* Change logic for request chunk function
This PR contains a cherry picked commit from main https://github.com/island-is/island.is/pull/9755

fix(search-indexer):  Hotfix - use correcly sized request bulk chunk size in ElasticSearch

---

libs/application/ui-shell/src/components/DelegationsScreen.tsx
libs/auth/react/src/lib/Authenticator/AuthContext.tsx
libs/auth/react/src/lib/Authenticator/Authenticator.tsx

Adding correct url parameter to delegation checked application
In the new react router package when calling
useNavigation
and instantly
useLocation
the useNavigation is not fast enough to update itself so the uselocation gets the old value.
Fixed by sending the value itself into the function from parent.

fix(applications): Url parameter for delegation

---

apps/web/components/ServiceWeb/Footer/Footer.tsx

* When a user presses the online chat link then the chat window is supposed to open up and connect you to an agent, but since the link prefetches data and doesn't fully reload the page then the watson chat bot doesn't recognize the link change. So we use the window.open() function instead to make sure that the watson chat bot loads correctly and recognized the query param in the route that triggers the agent chat to commence.
* This was a requested feature by Digital Iceland

feat(web): Reload page on online chat link click

---

libs/api/domains/vehicles/src/lib/api-domains-vehicles.resolver.ts

Add the scope internalProcuring to the VehiclesDetail endpoint
So it is possible to get information about the vehicle when using delegation

feat(transport authority applications): Add internalProcuring to VehiclesDetail

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/Themes/FiskistofaTheme/FiskistofaFooter.tsx
apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsFooter.css.ts
apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsFooter.tsx
apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsHeader.tsx
apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunNordurlandsTheme/HeilbrigdisstofnunNordurlandsFooter.tsx
apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunSudurlandsTheme/HeilbrigdisstofnunSudurlandsFooter.tsx
apps/web/components/Organization/Wrapper/Themes/LandkjorstjornTheme/LandkjorstjornFooter.tsx
apps/web/components/Organization/Wrapper/Themes/LandlaeknirTheme/LandlaeknirFooter.tsx
apps/web/components/Organization/Wrapper/Themes/SjukratryggingarTheme/SjukratryggingarFooter.tsx
apps/web/components/Organization/Wrapper/Themes/SyslumennTheme/SyslumennFooter.tsx

* Instead of having hardcoded values inside the code we'd like to have the option to change images without it requiring a code change

feat(web): Read organization footer image urls from cms

---

apps/judicial-system/web/src/components/DefenderInfo/DefenderInfo.tsx

[Texti i info bubblu er rangur á skjánum varnaraðili - verjandi varnaraðila.](https://app.asana.com/0/1199153462262248/1203865140441049/f)
- Fixes a tooltip in the defender section for investigation cases.

fix(j-s): Defender Tooltip

---

libs/application/templates/marriage-conditions/src/forms/sharedSections/dataCollection.ts

Duplicate userprofile text removed

fix(marriage-conditions): remove duplicate data provider text

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts

We where sending in the wrong right code if the applicants where not in registered cohabitation. 
If no spouse found we didn't not fill in fullname and gendercode of the person. Therefor we were sending in FO rights code instead of F.

fix(parental-leave): right code fix

---

apps/services/sessions/sequelize.config.js
libs/api/domains/auth/src/lib/auth.module.ts
libs/api/domains/auth/src/lib/loaders/client.loader.ts
libs/api/domains/auth/src/lib/models/client.model.ts
libs/api/domains/auth/src/lib/services/clients.service.ts
libs/api/domains/auth/src/lib/services/types.ts
libs/clients/auth/delegation-api/src/lib/apis.ts

Finish implementation of `ClientLoader` to load client to resolve `clientName` and resolve domain to get logo for display.
To use client name and logo in session history UI.
N/A

feat(api-sessions): Use data loader to load client name and logo

---

libs/application/templates/financial-statements-inao/src/forms/application/shared/about/clientInfoSection.ts
libs/application/templates/financial-statements-inao/src/forms/application/shared/keyNumbers/capitalNumbers.ts

operating year which is fetched dynamically had to be refetched each time entering the application

fix(financial-statement-inao): operating year not persisting 

---

.github/workflows/push.yml

Map GH Actions secret to step env variable for geoip update script.
docker build is failing due to the env variable missing in the step.

fix(sessions): Add env variable to docker-build step for geoip udpate

---

libs/application/ui-components/src/components/ApplicationList/ApplicationList.tsx
libs/island-ui/core/src/lib/ActionCard/ActionCard.tsx

Revert ui component
Was bugged for many applications

fix(applications): Revert draft status bar to original design

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/assignEmployerEmail.ts

Get applicant name to send in the email to employer not all external dat
Was returning [object Object] instead og applicant name

fix(parental-leave): get applicant name not all external data

---

libs/service-portal/air-discount/src/module.ts

* Hide air discount when logged in as a company
Hotfix: https://github.com/island-is/island.is/pull/10065

fix(service-portal): Hotfix - hide air-discount when logged in as a company in serviceportal

---

apps/web/components/Form/Form.tsx

* I noticed that the padding was way too much on mobile screen sizes so I decreased it for better usability

fix(web): Change padding on web form depending on screen size

---

apps/judicial-system/backend/src/app/modules/police/police.service.ts

[Taka bandstrik af kennitölu áður en hún er send í LÖKE.](https://app.asana.com/0/1199153462262248/1203984021474236/f)
Remove dash from national IDs before sending update request to police service
To avoid getting an error that comes when a national ID is sent with an update request

fix(j-s): Remove dash from National IDs

---

libs/application/templates/driving-instructor-registrations/src/fields/StudentsOverview/index.tsx
libs/application/templates/driving-instructor-registrations/src/fields/ViewStudent/index.tsx

Driving License book api now returns completed hours with 2 decimal points. It was blowing up the number field and had to be rounded down so adding that in.

fix(instructor-registration): format completed hours

---

apps/judicial-system/web/src/components/IndictmentCaseFilesList/IndictmentCaseFilesList.tsx
apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFiles/CaseFiles.strings.ts

[Umferðarlagabrot - Birta ákæru á yfirliti sækjanda og dómaramegin](https://app.asana.com/0/1199153462262248/1203966413719356/f)
Display link to auto generated indictment for traffic violation cases
Because it is not uploaded by the user in these cases so in order for them to be displayed on the overview screen we must instead link to the auto generated file

feat(j-s): Display auto generated indictment pdf

---

apps/judicial-system/backend/src/app/messages/courtUpload.ts
apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts

Remove modified text and change namespace as ruling_v2 already existed in Contentful
So that the name is displayed correctly in Auður

fix(j-s): Remove modified text and change namespace

---

apps/services/license-api/src/app/modules/license/clients/firearmLicense/firearmLicenseApiClient.service.ts

Pick out individual properties for the verification function.
Too many props makes the service go sour.

fix(license-api): Pick out properties for verify

---

package.json
yarn.lock

A recent dependency broke our (buggy) esbuild dep handling. Then we need to manually tweak our dependencies to get our builds to work.
To fix the prod builds

chore(deps): Deduplicate deep-equal and color

---

apps/services/auth/admin-api/infra/auth-admin-api.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml

Fix regression in #10291 as the library depends on the `IDENTITY_SERVER_ISSUER_URL` to be present for the `DelegationConfig`.
To unblock auth-admin-api to be able to start.
N/A

fix(services-auth-admin-api): Add issuer url env variable

---

apps/web/components/Stepper/utils.ts
apps/web/screens/queries/Article.ts

* Previously if users would place an accordion or an faq list inside a step subtitle field it wouldn't be displayed
* While I was at it I improved the stepContainsQuestion function by making it check whether the step was indeed a question to begin with
* We want to allow such embeds inside the rich text fields of steps
*

feat(web): Allow faqlists inside stepper subtitles

---

apps/services/search-indexer/infra/search-indexer-service.ts
apps/web/components/PageLoader/PageLoader.tsx
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
libs/cms/src/lib/environments/environment.ts
libs/cms/src/lib/search/cmsSync.service.ts
libs/cms/src/lib/search/contentful.service.ts
libs/cms/src/lib/search/importers/utils.ts
libs/content-search-indexer/src/environments/environment.ts
libs/content-search-indexer/src/lib/indexing.controller.ts
libs/content-search-indexer/src/lib/indexing.service.ts
libs/content-search-toolkit/src/services/elastic.service.ts

This reverts commit 79456e434f3e438c4f421375d28b714b14540439.
* The search-indexer on dev is running out of heap memory while re-syncing on dev.
* So we don't ship something which might be causing memory errors to production, we decided to revert this change for now

fix(search-indexer): Revert "fix(search-indexer): Increase performance of search-indexer (#9892)"

---

libs/clients/driving-license-book/src/clientConfig.json
libs/clients/driving-license-book/src/lib/drivingLicenseBookClient.service.ts
libs/clients/driving-license-book/src/utils/mappers.ts

Get student returns active book with optional request parameter so simplifying the function.

fix(driving-license-book-api): Simplify get student

---

apps/services/search-indexer/infra/search-indexer-service.ts
apps/web/components/PageLoader/PageLoader.tsx
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
libs/cms/src/lib/environments/environment.ts
libs/cms/src/lib/search/cmsSync.service.ts
libs/cms/src/lib/search/contentful.service.ts
libs/cms/src/lib/search/importers/utils.ts
libs/content-search-indexer/src/environments/environment.ts
libs/content-search-indexer/src/lib/indexing.controller.ts
libs/content-search-indexer/src/lib/indexing.service.ts
libs/content-search-toolkit/src/services/elastic.service.ts

This reverts commit 2a04937cddb9695d50d476975e794dd930c5f940.
* Turns out that the issue regarding the indexer running out of memory wasn't due to the code per say so we'd like to re-introduce the changes since they are beneficial for performance reasons as well as stability reasons
* The previous issue that caused us to go for the initial revert was due to Contentful data being too large to fit inside our heap memory allocations so we'll also include some node option changes in this PR

fix(search-indexer): Revert "fix(search-indexer): Revert "fix(search-indexer): Increase performance of search-indexer (#9892)" (#10394)"

---

apps/services/auth/admin-api/infra/auth-admin-api.ts
apps/services/auth/admin-api/src/main.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml

Use NestJS global prefix instead of ingress rewrite to add the `/backend` prefix for auth-admin-api.
Ingress rewrite decodes url parameters without encoding them back causing issues in auth-admin-api, as our resource IDs contains url-unsafe characters.

fix(auth-admin-api): Use nestjs global prefix instead of ingress rewrite.

---

libs/auth-api-lib/src/lib/clients/clients.service.ts

Reverting removal of `raw: true` for clients.
To fix regression in IDS.

fix(services-auth-ids-api): Revert removing of raw: true for clients

---

apps/system-e2e/src/tests/islandis/service-portal/smoke/access-control.spec.ts
apps/system-e2e/src/tests/islandis/service-portal/smoke/company-delegation.spec.ts

Hide onboarding modal in service portal e2e tests.
Because it breaks most tests.
Would be nice to abstract this in service-portal tests somehow so it is hidden automatically in all tests.

fix(e2e): Hide onboarding in service portal tests

---

package.json
yarn.lock

Upgrade dd-trace to latest.
The version we were using has a known memory leak which might explain some of our memory issues in production.
The [2->3 migration](https://github.com/DataDog/dd-trace-js/blob/master/MIGRATING.md) should be safe.

chore(deps): Upgrade dd-trace

---

apps/web/layouts/main.tsx

* In a recent PR I accidentally removed the filter function call for the alert banners resulting in unwanted banners appearing on dev

fix(web): Filter out alert banners that should not be shown

---

apps/consultation-portal/components/CaseTimeline/CaseTimeline.tsx
apps/consultation-portal/components/ReviewCard/ReviewCard.tsx
apps/consultation-portal/screens/Case/Case.tsx
apps/consultation-portal/types/interfaces.ts
apps/consultation-portal/utils/helpers/dateFormatter.ts

Remove front 0 in day and month
fix timeline dates so it shows a period in 1 state, shows "from ... " in 2 state and "date" in last state 

fix: remove 0, fix dates in timeline

---

libs/application/templates/financial-statements-inao/src/fields/CemetryCaretaker/index.tsx
libs/application/templates/financial-statements-inao/src/forms/application/cemetry/sectionCemetryCaretaker.ts
libs/application/templates/financial-statements-inao/src/lib/constants.ts

- removed extra object on cemetryCaretaker object
- caretaking property is unused
- changed cemeterycaretaker  section id in case of conflict with cemeterycaretaker custom field
The `.caretakers` created an extra object on cemetryCaretaker object and hence failed validation.

fix(financial-statement-inao):  validation error caretaker screen

---

libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

Fix selected child index for adoption / foster care / other so that child in list for "normal" application isn't pre selected

fix(parental-leave): selected child index for adoption / foster care / other

---

libs/application/core/src/lib/fieldBuilders.ts
libs/application/types/src/lib/Fields.ts
libs/application/ui-fields/src/lib/PhoneFormField/PhoneFormField.tsx
libs/application/ui-forms/src/lib/applicantInformationMultiField/applicantInformationSchema.ts
libs/island-ui/core/src/lib/PhoneInput/CountryCodeSelect/Components/index.tsx
libs/island-ui/core/src/lib/PhoneInput/CountryCodeSelect/CountryCodeSelect.css.ts
libs/island-ui/core/src/lib/PhoneInput/PhoneInput.tsx
libs/shared/form-fields/src/lib/PhoneInputController/PhoneInputController.tsx

Feature flag now disables the country code dropdown instead of rendering a normal text input.
It was causing major problems because of zod schema validation between the two different inputs.
The PhoneInput prefixes the value with a country code, so it needs a different validation than a normal text input, and using a feature-flag to differentiate between two zod-schemas seems impossible
Also, adding the option to disable the dropdown with a prop e.g. 
```ts
buildPhoneField({
id: 'applicant.phoneNumber',
title: "Phone",
disableDropdown: true,
}),
```
https://user-images.githubusercontent.com/16031201/226647386-d57f61c7-08c2-4cb9-aed3-6fbf301e726d.mp4

fix(phone-input): Hotfix: change feature flag functionality

---

libs/portals/shared-modules/delegations/src/screens/GrantAccess/GrantAccess.tsx

It did not work to change domains on the grant access screen. The form would be silently invalid with an empty national id after reseting the form.
This is another RHF regression. :(
So we can launch.

fix(delegations): Fix regression when switching domains

---

libs/application/templates/document-provider-onboarding/project.json
libs/application/templates/document-provider-onboarding/src/forms/messages.ts

Extract strings script was outdated and some messages had non-unique ID's
QA

fix(dpo): Fix extract-strings script and unique message id's

---

apps/judicial-system/web/src/components/IndictmentCaseFilesList/IndictmentCaseFilesList.tsx
apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFiles/CaseFiles.tsx
apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Prosecutor/Indictments/Processing/Processing.tsx
apps/judicial-system/web/src/utils/hooks/useCase/updateCaseGql.ts
apps/judicial-system/web/src/utils/hooks/useSections/index.ts
apps/judicial-system/web/src/utils/stepHelper.ts

[Asana](https://app.asana.com/0/1199153462262248/1204272649743961)
Move all logic to one function and hide traffic violation indictment step if user has already uploaded an indictment file in the old flow
Because with the old functionality we could create a confusing situation where a user might have began working on a case within the old user flow but is forced in to the new one.

fix(j-s): Fix traffic violation feature hiding

---

apps/judicial-system/web/src/routes/Court/Indictments/CourtRecord/CourtRecord.tsx

[Asana](https://app.asana.com/0/1199153462262248/1203966424106781/f)
Only accept .pdf files for court record and ruling in indictments
We want to limit the use of other file extensions being uploaded to RVG. Most of these files are written as Word documents and can easily be exported as pdfs.

chore(j-s): Only accept .pdf files for court record and ruling in indictments

---

infra/src/dsl/output-generators/map-to-helm-values.ts

HPA config is not coordinated with the desired replica count and is overriding it. Fixing that so now mountebank is just 1 instance.

fix(system-e2e): Stop K8s HPA from scaling mountebank service

---

libs/island-ui/core/src/lib/Input/Input.mixins.ts

The background color from Input.mixins.ts was overwriting the Box's background color. Now, the container only uses the box's background color.

fix(island-ui): Background-color specificity.

---

libs/island-ui/core/src/lib/Input/Input.tsx

The regular input styles with media queries had higher specificity than the textarea styles. Now the input styles are not applied if the component is a textarea.
This is a fix for a bug that was introduced in #10656 .

fix(island-ui): Textarea font size.

---

apps/contentful-apps/pages/fields/subarticle-url-field.tsx
libs/cms/src/lib/environments/environment.ts

* overViewLinks and introLinkImage are both nested content types which when changed didn't cause the Elastic search index to update for the page the the content was nested within. This is fixed by adding these two types as nestedContentTypes

feat(web): Re-index pages into ElasticSearch when nested content changes

---

libs/cms/src/lib/models/menuLinkWithChildren.model.ts

* We want to add a fail-safe to the menu since we recently noticed that if there is a missing link then the web displays a 500 error due to a graphql validation failure since the link is required
* We want to prevent errors in the future

fix(web): Main menu graphql errors due to missing content in CMS

---

libs/service-portal/sessions/src/screens/Sessions/Sessions.tsx

The search field now handles loosely formatted national IDs, such as those with a trailing space or with a dash in the middle.
UX

feat(sessions): Allow different formatted National IDs in the filter.

---

apps/contentful-apps/components/MideindTranslationSidebar/api/index.tsx
apps/contentful-apps/next.config.js
apps/contentful-apps/pages/fields/subarticle-url-field.tsx

* Previously there was a public runtime config setup to expose variables within the Next.js project used to host Contentful apps. It turns out that due to the static generation the variables weren't exposed to the browser. So the only way to use runtime configs would be to render the pages at request time which is not something we want to do due to the performance loss and all of the variables are only used in the browser so until we have something that should only be setup server side we'd like to use environment variables instead.

chore(contentful-apps): Use environment variables instead of runtime config for Contentful Apps

---

libs/portals/admin/ids-admin/src/components/TenantsList/TenantsList.tsx

The tenant list is now a bit narrower. It has the same width as the dashboard.
More consistent with other islands.is pages.

feat(ids-admin): Tenant list grid width 

---

libs/island-ui/core/src/lib/Input/Input.css.ts
libs/island-ui/core/src/lib/Input/Input.stories.tsx
libs/island-ui/core/src/lib/Input/types.ts

This PR does two things to increase the UX of the <Input /> component. 
1. Hides the spin buttons on input[type='number']. They are never used.
2. Add support for the `inputmode` ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode)) on inputs. This allows us to control what kind of keyboard is displayed on mobile devices.
Before removing the spin buttons:
After:
With `inputMode="numeric"`:
Without:

feat(island-ui): Hide spin buttons and add inputmode

---

libs/island-ui/core/src/lib/ToggleSwitch/ToggleSwitch.css.ts
libs/island-ui/core/src/lib/ToggleSwitch/ToggleSwitch.stories.mdx

This implements the new design for the toggle switch. Now the unchecked state is grey to distinguish the states better.
Figma: https://www.figma.com/file/pDczqgdlWxgn3YugWZfe1v/UI-Library-%E2%80%93-%F0%9F%96%A5%EF%B8%8F-Desktop?node-id=1444-25&t=YrgEtvksjtSq7rTc-4

feat(island-ui): ToggleSwitch color changes

---

libs/application/template-api-modules/src/lib/modules/templates/general-fishing-license/general-fishing-license.service.ts
libs/application/templates/general-fishing-license/src/fields/Overview/index.tsx

Strandveiðileyfi has two charge codes, it is the only one that has more than one, so special case was created around that functionality. If we need this to be more robust for the future, if more licenses requires more than one type, then we need to get them grouped in some way from the fishing license api in order to avoid hard coding values on our end.

fix(applications): GFL, Strandveiðileyfi has two chargecodes

---

libs/island-ui/core/src/lib/Accordion/Accordion.stories.mdx
libs/island-ui/core/src/lib/Accordion/AccordionItem/AccordionItem.css.ts
libs/island-ui/core/src/lib/Accordion/AccordionItem/AccordionItem.tsx

The PR adds an optional color variant prop to the <AccordionCard />. 
Figma design:
https://www.figma.com/file/pDczqgdlWxgn3YugWZfe1v/UI-Library-%E2%80%93-%F0%9F%96%A5%EF%B8%8F-Desktop?node-id=96-654&t=qjjZIxsQvSAPq3tp-4

feat(island-ui): Color variants on AccordionCard

---

libs/portals/admin/ids-admin/src/components/Client/AdvancedSettings.tsx
libs/portals/admin/ids-admin/src/components/Client/Delegation.tsx
libs/portals/admin/ids-admin/src/shared/components/ConditionalWrapper.tsx
libs/portals/admin/ids-admin/src/shared/components/ContentCard.css.ts
libs/portals/admin/ids-admin/src/shared/components/ContentCard.tsx

Add an additional prop that wraps the childrent of the <ContentCard /> in an Accordion. Also minor styling fixes.

feat(ids-admin): Collapsable ContentCard

---

apps/web/components/Organization/Slice/Render/SliceDropdown.tsx
apps/web/screens/queries/fragments.ts
apps/web/utils/richText.tsx
libs/cms/src/lib/environments/environment.ts
libs/cms/src/lib/generated/contentfulTypes.d.ts
libs/cms/src/lib/models/sliceDropdown.model.ts
libs/cms/src/lib/unions/slice.union.ts

* We have a slice dropdown functionality for Organization subpages (where you pick an option from the dropdown and that selection will be displayed below the dropdown) but we want this feature for articles and other pages on the web as well
Simple test scheenshots:

feat(web): Added SliceDropdown content type

---

libs/portals/shared-modules/delegations/src/components/Modal/Modal.tsx

For some reason, the modal had a prop that allowed the body to scroll underneath the modal. This 🌭 removes this functionality. Modals should always block the body scroll. 
I tested all uses of this modal.
The scroll bar is only shown here to illustrate the problem.

fix(portals-shared-modules-delegations): Modal body scroll

---

apps/judicial-system/web/src/utils/mutations.ts

Add rulingDate to CaseList Query 
Verified bug
To fix filtering of cases that broke when rulingDate stopped being returned by the CaseList Query

fix(j-s): Add rulingDate to CaseList Query

---

libs/api/domains/communications/src/lib/emailTemplates/serviceWebForms.ts

* This was requested by Sjúkratryggingar
- Note: The email config for which email a service web form gets sent to is in the codebase but it'd be ideal to move that to a CMS at some point

feat(web): Send to different emails depending on selected category on service web

---

apps/consultation-portal/components/HeroBanner/HeroBanner.css.ts
apps/consultation-portal/components/HeroBanner/HeroBanner.tsx

https://veflausnir.atlassian.net/browse/KAM-1195
remove padding in hero banner

fix(consultation-portal): remove padding in hero banner

---

.github/actions/unit-test/action.yml

Increase runner node memory limits to 8GiB when running tests
application-system-api tests are running out of memory.

chore(ci): Increase node memory limits

---

libs/service-portal/settings/personal-information/src/utils/showUserOnboardingModal.ts

* When `hide_onboarding_modal` query param is visible, add to session storage.
* For testing, disable once then the whole session is disabled, avoiding the popup if user is redirected.

fix(service-portal): Add session storage hide modal on param

---

apps/service-portal/src/components/Layout/Layout.tsx
libs/api/domains/finance/src/lib/models/customerRecords.model.ts
libs/service-portal/air-discount/src/screens/AirDiscountOverview/AirDiscountOverview.tsx
libs/service-portal/core/src/components/IntroHeader/IntroHeader.tsx

* Nullable customer records
* Move alert banner section from intro header to layout
* customer records can be empty
* Intro header is not always rendered

fix(service-portal): Nullable customer records

---

apps/services/auth/delegation-api/src/app/clients/clients.controller.ts
libs/auth-api-lib/src/lib/clients/clients.service.ts

Read the domain name from the client model and fallback to try to parse it from the client ID if not configured.
We recently added the domainName field to the client model and this uses that to read the domain name. It can be missing so we continue to fallback to the client id.
N/A

fix(delegation-api): Read domainName from client and fallback to parse from clientId.

---

apps/web/components/NewsList/NewsList.tsx
apps/web/components/Organization/NewsArticle/NewsArticle.tsx
apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/screens/LifeEvent/LifeEvent.tsx
apps/web/screens/News.tsx
apps/web/screens/Organization/PublishedMaterial/PublishedMaterial.tsx
apps/web/screens/Organization/Services.tsx
apps/web/screens/Organization/StafraentIsland/ApiCatalogue.tsx
apps/web/screens/Organization/SubPage.tsx
apps/web/screens/Organization/Syslumenn/Auctions.tsx
apps/web/screens/Organization/Syslumenn/Homestay.tsx
apps/web/screens/Organization/Syslumenn/OperatingLicenses.tsx

* These web reader feature flags have been set to true on prod for a few months now so it's safe to simply remove them from the code

chore(web): Remove web reader feature flags that are set to true on prod

---

apps/web/components/ServiceWeb/Forms/StandardForm/StandardForm.tsx

* The ordering wasn't correct since it didn't order icelandic characters correctly (that's what this change addresses)

feat(web): Fix ordering for support categories in service web contact form dropdown

---

libs/service-portal/health/src/lib/navigation.ts

fix(service-portal): wrong id in navigation message

---

apps/judicial-system/web/src/components/Table/Table.tsx
apps/judicial-system/web/src/routes/CourtOfAppeal/Cases/Cases.tsx
apps/judicial-system/web/src/routes/Shared/Cases/PastCases.tsx

[Málalisti Landsréttur - Röðun í síu falin](https://app.asana.com/0/1199153462262248/1204559062187683)
- disabling rows to not be sortable
- rows should not be sortable

fix(j-s): Disabling rows in case list in court of appeal

---

apps/judicial-system/backend/src/app/modules/case/state/case.state.spec.ts
apps/judicial-system/backend/src/app/modules/case/state/case.state.ts

[Landsréttur - ráða við að leiðrétta mál sem eru í kæruferli](https://app.asana.com/0/1199153462262248/1204723926688693/f)
- Allows the district court to modify the case after it has been appealed.
- This should be possible.

fix(j-s): Enables Case Correction After Appeal

---

apps/web/screens/queries/Search.tsx

* If you open up island.is right now (when this PR was created) and search for an org subpage then if you click on a suggested search result you'll always see a 404 since there is missing data required to form the link

fix(web): Add org page to query for org subpage in search

---

apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacanciesList.tsx
apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacancyDetails.tsx

A new page displaying a list of vacancies is gonna go live in the next release and we want to have a way to manually start displaying the page

chore(web): Add namespace feature flag for vacancies list page

---

libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/getApproveAnswers.ts

Seller's co-owner is not able to approve if one other seller's co-owner has already approved (then approved=false, but the check for whether we should save the approved answer only continues if approved=undefined)

fix(transfer of vehicle ownership): error if more than one co-owner

---

apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudies.css.ts
apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudiesHeader.tsx

* Here's an attempt to improve the scaling for the university studies header for larger screens
https://github.com/island-is/island.is/assets/43557895/e0de7565-835b-45e0-ac6b-39c85f08bd12

chore(web): Change width of University studies header for larger screens

---

apps/judicial-system/web/src/routes/Defender/Cases/Cases.tsx
apps/judicial-system/web/src/routes/Defender/Cases/DefenderCasesTable.tsx

[Hopp við load - meðan síðan lódast er hausinn neðarlega og hoppar svo upp](https://app.asana.com/0/1203322535526396/1204778264928402/f)
Display loading table when page is fetching case list data
Better user experience

fix(j-s): Display loading table for defender cases

---

libs/application/templates/driving-learners-permit/src/fields/LookupStudent/index.tsx

fix(driving-learners-permit): Hook up error messages to descriptors

---

apps/system-e2e/src/tests/islandis/web/smoke/endorsements.spec.ts

The test expects to be logged in, but was missing `authUrl`, since `/homeUrl` is public.

test(system-e2e): Fix delegation test failure

---

apps/contentful-apps/pages/sidebars/preview-link.tsx

* A recent [PR](https://github.com/island-is/island.is/pull/11456) introduces caching for the public web but we still want content editors to be able to bypass it to see their changes on the dev web.

feat(contentful-apps): Bypass cache for preview links

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/IcelandicNaturalDisasterInsuranceFooter.css.ts
apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/IcelandicNaturalDisasterInsuranceFooter.tsx
apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/IcelandicNaturalDisasterInsuranceHeader.css.ts
apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/IcelandicNaturalDisasterInsuranceHeader.tsx
apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/index.ts

feat(web): Add header and footer for NTÍ organization

---

apps/consultation-portal/screens/Case/components/CaseOverview/CaseOverview.tsx

https://veflausnir.atlassian.net/browse/KAM-1366
- Text in detailed descripion comes with \n, should show breaks in frontend

fix(consultation-portal): text should have breaks

---

apps/contentful-apps/pages/fields/vacancy-contacts-field.tsx

To not have to create a new content type I added a json field for the vacancy contacts. Here I am adding a contentful app that renders that json field in a more user friendly manner. Allowing users to press buttons to add or delete contacts from the list

feat(contentful-apps): Vacancy contacts custom contentful app field

---

scripts/clean.sh

The clean.sh script has been updated to support both bash and zsh, as well as older bash <4 shells, broadening the compatibility and usability of the script across different environments.
This change ensures that users running different shells can use the clean.sh script without any shell-specific issues. Previously, the script was only compatible with bash which could lead to potential issues for zsh users. By enabling support for zsh, I removed this limitation and increased the script's utility.

fix(scripts): Adding zsh support for the clean script

---

libs/application/templates/driving-license-duplicate/src/forms/applicationSections/sectionDelivery.ts

I don't know what to say. Very small changes.
Removing text from one place.
Key is reused.
Removed an unused import while I'm at it.
As small as these get.

fix(application-driving-license-duplicate): Too many strings, removing title

---

libs/cms/src/lib/unions/slice.union.ts

* It turns out that a user can in fact embed an empty asset in the CMS causing the code that maps the asset to fail, this is something we want to be fixed

fix(web): Add fail-safe when mapping assets from CMS

---

libs/cms/src/lib/environments/environment.ts

* The elastic search mapper keeps track of what content types are nested so we can update the corresponding document in ElasticSearch when a change happens in the CMS
* The SupportCategory and SupportSubCategory content types weren't tagged as being nested which resulted in ElasticSearch documents not being updated when the category name would be changed

chore(search-indexer): Add support categories as nested types

---

libs/application/templates/driving-license-duplicate/src/lib/messages.ts

One field requires markdown for styling purposes

fix(application-driving-license-duplicate): Add markdown to description field

---

libs/cms/src/lib/search/importers/utils.ts

* Since creating a new URL object doesn't work without it have a base url I simply provided it since it's only used here to count how many process entry links are external or not and since a relative link is basically an island.is link then it's appropriate that island.is would be it's base url.

chore(web): Allow process entry links to be relative

---

apps/contentful-apps/pages/sidebars/preview-link.tsx

Allow users in the CMS to open up a preview for the vacancy content type

feat(contentful-apps): Add preview link for vacancy content type

---

libs/cms/src/lib/models/link.model.ts
libs/cms/src/lib/models/processEntry.model.ts
libs/cms/src/lib/models/referenceLink.model.ts
libs/cms/src/lib/models/utils.ts

For E2E tests to not leave the environment they are testing once they navigate using a link, this was deemed the best approach. Instead of relying on CMS users to create relative links we can instead handle it so if they create an absolute link to prod then we'll automatically make that link relative

feat(web): Add relative url mapping so CMS links can point to prod and code makes them relative

---

apps/contentful-apps/pages/fields/publish-date-field.tsx

* If a user publishes an entry in the CMS then the publish date field receives a value (the initial publish date timestamp) but since the entry just got published without the publish date being populated we need to publish the entry again to store this value with the published entry.

fix(contentful-apps): Publish date field should publish entry again to store it's value

---

apps/consultation-portal/screens/Case/components/CaseDocuments/CaseDocuments.tsx
apps/consultation-portal/screens/Case/components/DocFileName/DocFileName.tsx
apps/consultation-portal/utils/helpers/sortLocale.ts

https://veflausnir.atlassian.net/browse/KAM-1412
- If link had no description the site crashed
- documentsBox is now sorted

fix(consultation-portal): bug fixed and added sort

---

apps/web/components/connected/DrivingInstructorList/DrivingInstructorList.tsx
apps/web/components/connected/DrivingInstructorList/index.ts
apps/web/components/connected/index.ts
apps/web/screens/queries/DrivingInstructors.ts
apps/web/utils/richText.tsx
libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
libs/api/domains/driving-license/src/lib/graphql/main.resolver.ts
libs/api/domains/driving-license/src/lib/graphql/models/teacher.model.ts
libs/application/template-api-modules/src/lib/modules/shared/api/driving-license/driving-license.service.ts
libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
libs/clients/driving-license/src/lib/drivingLicenseApi.types.ts

* Add an embeddable component in richtext for the CMS that displays a table containing driving instructors

feat(web): Driving instructors on public web

---

apps/web/screens/Organization/PublishedMaterial/PublishedMaterial.tsx

* To be able to link a filtered search result page we'd like to store the selected filters in query params of the url
* Also in case the user refreshes the page his selected filters won't clear out anymore
* It's often handy to be able to link to specific types of documents and this change allows CMS users to do just that :)
(Look at the url)

feat(web): Store search filters in url for published material pages

---

apps/services/search-indexer/infra/search-indexer-service.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
libs/cms/src/lib/search/contentful.service.ts

https://islandis.slack.com/archives/C01J3ANCF55/p1689177698836069
* The nested logic is getting out of hand due to too many linked entry references in the CMS and our 3 year old indexing code can't deal with it anymore.

feat(search-indexer-service): Add env variable for disabling nested resolution of entries from CMS

---

apps/contentful-apps/pages/fields/subarticle-url-field.tsx

* The url field of a baby article in the cms consists of the parent article's slug and the baby article's slug seperated by a slash. 
`${parentArticle.slug}/${babyArticle.slug}`.
When a baby article is created it doesn't have any parent assigned to it so fetch the parent's slug doesn't work since there is none. But once there is a parent set, then we'd like to refetch it to be able to form the url field of the baby article (which is what this PR is for).

feat(contentful-apps): Refetch parent on sys change for Baby Article url field extension

---

apps/services/license-api/src/app/modules/license/clients/drivingLicense/drivingLicenseApiClient.service.ts

Return error if a user's driving license doesn't contain a photo
Prod licenses must contain a photo

fix(license-api): re-enable the photo check

---

libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanApplication.ts
libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanSubmitted.ts
libs/application/templates/complaints-to-althingi-ombudsman/src/lib/dataSchema.ts
libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/complainee.ts
libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/complaintDescription.ts
libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/complaintInformation.ts
libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/confirmation.ts
libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/preexistingComplaint.ts
libs/application/ui-forms/src/lib/formConclusionSection/formConclusionSection.ts

Text updated in multiple locations.
Conclusion section title is now overridable.
Power of attorney file upload is now optional.
Appeals moved from subsection to its own section.
Alternative alert message for preexistingComplaints.
Feedback from QA
Appeals section:
Conclusion section title override:
Alternative alertMessage:

fix(application-system): Complaints to althingi ombudsman QA fixes 

---

apps/services/search-indexer/infra/search-indexer-service.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
libs/cms/src/lib/search/contentful.service.ts

* An environment variable was added recently so we can turn on/off the nested entry fetching logic that the search-indexer goes through to figure out whether for example: an article needs to be re-indexed since an accordion that it points to got updated
* It's time we turn it on so we can start getting nested delta updates in again

chore(search-indexer): Re-enable nested fetching for search indexer entries

---

apps/contentful-apps/pages/fields/article-subarticles-field.tsx

https://github.com/island-is/island.is/assets/43557895/b00da7a2-0208-4c2e-aae9-379ee7701c37
https://github.com/island-is/island.is/assets/43557895/740f5b70-8c08-47f3-8c45-f05322f252ea

fix(contentful-apps): Adjust subarticles field height depending on item count

---

apps/services/search-indexer/infra/search-indexer-service.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

* Recently a lot of entries that had many entries were linking to were published in the CMS, causing the indexing process to halt. That's when this env variable was introduced but we'd like to toggle the nested functionality back on again (meaning that if someone updates an accordion then the article it's on will be updated).

chore(search-indexer): Allow fetching entries that link to nested entries again

---

package.json
yarn.lock

A vulnerability was found in the [import-in-the-middle](https://www.npmjs.com/package/import-in-the-middle) package, a Datadog-maintained module used by our Node.js tracing library package, [dd-trace](https://www.npmjs.com/package/dd-trace). This should not affect us since we are not using ESM or any of these libraries: 
*    --loader=import-in-the-middle/hook.mjs
*    –-loader=dd-trace/loader-hook.mjs
*    --loader import-in-the-middle/hook.mjs
*    –-loader dd-trace/loader-hook.mjs
But to be safe I think it is better to upgrade.
Upgrade dd-trace to 3.32.1.
To avoid possible vulnerability in the future.

chore: upgrade dd-trace

---

scripts/ci/Dockerfile

yarn set version fails on playwright since it always fetches the latest instead of using the version we have in the repo
copying yarn files instead of using yarn set version

fix: do not use yarn set version

---

apps/contentful-apps/pages/fields/subarticle-url-field.tsx

* If the url field was left empty for other locales than the default one then the entry could not be published since the code used a / value instead of allowing the field being empty and since the url value needs to be unique then the validation kicked in and prevented us from publishing, this is solved by simply allowing an empty value

fix(contentful-apps): Subarticle url field validation

---

apps/judicial-system/api/esbuild.json
apps/judicial-system/backend/esbuild.json
apps/services/user-notification/esbuild.json

Adding `@nestjs/axios` as `externalDependencies` in `esbuild.json` for
* `judicial-system-api`
* `judicial-system-backend`
* `user-notification` which applies also for the worker.
These services are using `cms-translations` library that uses the `CmsModule` which includes `HttpHealthIndocator` from `@nestjs/axios`. Needed to fix regression from the monorepo upgrade.
N/A

fix(core): Add @nestjs/axios in esbuild.json externalDependencies.

---

apps/web/graphql/client.ts
apps/web/graphql/options.ts
apps/web/graphql/withApollo.tsx

* Content writers need to be able to preview what they are writing on the dev environment quickly so we've got a way to bypass the cache. But it stopped working due to an update resulting in the initApollo function not receiving the page context parameter, I simply added it and now the bypass works again 🙌

fix(web): Allow bypassing cache for web

---

libs/cms/src/lib/models/utils.ts

* Previously only the pathname was returned but that cut off the query params and hash value in the url, which is something we want to keep, so that's what this PR is for :)

fix(cms): Include query params in relative url mapping

---

apps/web/components/IcelandicNamesSearcher/IcelandicNamesSearcher.tsx
apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/hooks/useContentfulId.ts
apps/web/hooks/usePlausible.ts
apps/web/hooks/useViewport.ts
apps/web/screens/AboutPage/Sidebar.tsx
apps/web/screens/Adgerdir/components/AdgerdirArticles/AdgerdirArticles.tsx
apps/web/screens/Adgerdir/components/CardsSlider/CardsSlider.tsx
apps/web/screens/Organization/StafraentIsland/ApiCatalogue.tsx
apps/web/screens/Organizations/Organizations.tsx
apps/web/screens/Search/Search.tsx

* I noticed errors on route changes (clicking a link) for some pages and it turns out it's due to values being returned in useEffect, see more here: https://stackoverflow.com/questions/72306420/typeerror-destroy-is-not-a-function-nextjs

fix(web): useEffect returned values are causing errors on route change

---

apps/application-system/form/src/routes/Applications.tsx
libs/application/ui-shell/src/lib/ApplicationForm.tsx

React 18 `StrictMode` exposed a bug (local development only) in the applications screen where the delegations check gets stuck because we were  setting a `delegationCheck` by toggling it on/off instead of directly setting it to true. Because of the double render of StrictMode in development mode this check was always being toggled twice and therefore never changed to the correct value.
Fixes regression after big NX update 

fix(application-system): Delegations screen stuck in loading state

---

apps/services/search-indexer/dev-services/docker-compose.yml
apps/services/search-indexer/dev-services/elasticsearch/Dockerfile

* I've been struggling with running `yarn dev-services services-search-indexer` after I recently updated Docker Desktop on an intel mac. The changes in this PR fixed that issue

fix(search-indexer): Update docker files for local development

---

libs/application/templates/driving-instructor-registrations/src/fields/ViewStudent/index.tsx

Previously all test restuls were being treated as passed.
We simply filter them now
Visual aid for 010130-2129, a test student who has test results but has not passed the exam.
Notice bottom right for `Skriflegm prófum lokið`

fix(application-dir): Exams passed filter

---

apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacanciesList.tsx
libs/cms/src/lib/cms.elasticsearch.service.ts
libs/cms/src/lib/search/importers/news.service.ts

* Since there was max size parameter defined in the Elasticsearch query there seemed to be a cut off, meaning that not all vacancies got returned.
* This PR adds the max size limit to be a 1000 (since we need to set some number and 1000 is also used for the /s page it was deemed feasible, however it's not likely that vacancies entered in the CMS will ever be more than a 100 but it's best to be safe by setting it to a 1000).
Once the vacancies endpoint in xroad becomes paginated this code will also be updated so it allows for pagination but until that happens, this change is truly needed
* I also added a fail-safe for news that haven't been published yet (by setting the releaseDate field that gets stored in ES to null if the initialPublishDate is an empty string)
* And I noticed that the …

fix(web): Vacancies added in CMS not showing up on overview page

---

libs/application/templates/p-sign/src/lib/messages.ts

Want string extraction to not fail.

fix(application-p-sign): Fix duplicate message id

---

apps/web/screens/Organization/PublishedMaterial/PublishedMaterial.tsx

* The published material page (utgefid-efni) was being infinitely re-rendered due to props being refetched when the url got updated

fix(web): Published material page prop refetching loop

---

apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacanciesList.tsx
libs/cms/src/lib/cms.elasticsearch.service.ts
libs/cms/src/lib/search/importers/news.service.ts

fix(web): Hotfix - Vacancies added in CMS not showing up on overview page (#11870)

---

.github/CODEOWNERS

Removing `/handbook/` path from `CODEOWNERS` file as it doesn't exist any more.
To unblock CI.

fix(core): Remove handbook from codeowners

---

libs/api/domains/vehicles/src/models/getVehicleSearch.model.ts

Update the date field in search model to represent it's true value.
Otherwise it will be converted to a timestamp string, and therefore be different to other dates in the model.

fix(service-portal): Update first reg date in get veichle search model

---

apps/web/components/NewsItems/NewsItems.tsx
apps/web/screens/queries/fragments.ts

* We don't want the "Forsíðufréttir" news tag to be visible on news cards (since it's an internal functionality to make news appear on the frontpage)

chore(web): Hide frontpage news tag on latest news card

---

libs/api/domains/icelandic-government-institution-vacancies/src/lib/icelandic-government-institution-vacancies.resolver.ts
libs/api/domains/icelandic-government-institution-vacancies/src/lib/utils.ts

* The "stofnunNr" field coming from the vacancies endpoint is sometimes a string and other times a number so to have it behave correctly we convert it to a string
* I edited the types that the vacancies endpoint returns to correctly indicate what is returned
* It was previously indicated that the "stofnunNr" endpoint would always be a string (through email communication since there isn't an openapi definition for the web service that returns the vacancies) but it turns out not to be the case so that's why this change is necessary

fix(web): Convert numeric "stofnunNr" field to string for vacancy institutions

---

libs/api/domains/icelandic-government-institution-vacancies/src/lib/icelandic-government-institution-vacancies.resolver.ts

* A set was being checked for values instead of a map which resulted in logos from external service being displayed instead of logos from the cms

fix(web): Vacancy institution logo matching

---

README.md

Fix broken links in root README
Links to the handbook are broken after we removed the handbook from the repo.
N/A

chore(core): Fix broken links in root README

---

apps/judicial-system/web/src/utils/hooks/useSections/index.ts

[Asana](https://app.asana.com/0/1199153462262248/1205315341984017/f)
Don't allow clicking on current step of form stepper
If the current step has a modal when you leave it, the modal is shown when you click on the current step in the form stepper.

chore(j-s): Don't allow clicking on current step of form stepper

---

apps/judicial-system/web/src/utils/mutations.ts
libs/api/domains/rights-portal/src/lib/rightsPortal.service.ts

So that the duration field in the case list table for appealed cases works correctly.
[Landsréttur málalisti - undefined í gildistíma](https://app.asana.com/0/1199153462262248/1205336076594260/f)
Added missing fields from appealed case list query
So we can display the duration period of a case in the appealed cases table

fix(j-s): Add required fields to appealed cases CaseList query

---

apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/IcelandicNaturalDisasterInsuranceHeader.css.ts
apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/IcelandicNaturalDisasterInsuranceHeader.tsx

* The title was overflowing above the background image

fix(web): Change styling for NTí header

---

apps/application-system/api/project.json

Removing the xroad-proxy script from `application-system-api` dev target
The `application-system-api` starts the `services-user-profile` which starts xroad-proxy, so this is race condition and one will fail.
N/A

chore(application-system-api): Remove xroad-proxy as explicit dependency in dev target

---

apps/download-service/infra/download-service.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

Add missing education xroad config to download service
Broke

fix(service-portal): add xroad config to education

---

apps/judicial-system/web/src/utils/hooks/useS3Upload/useS3Upload.ts

[LÖKE gögn sem er búið að hlaða upp birtast samt aftur sem val á refresh](https://app.asana.com/0/1199153462262248/1205424566603439/f)
- Fixes the saving of police file ids.

fix(j-s): Police File Id

---

libs/service-portal/information/src/screens/Child/Child.tsx

Only return error / not found screen if there's no cached data
The graphql error trumps all other data

fix(service-portal): user information child

---

apps/web/utils/safelyExtractPathnameFromUrl.ts

* req.url string can be /next/data/.../something.json if a user requests a page client side by clicking a link. We don't want that to affect how we are extracting the url pathname so the fix here is to trim .json away from the url
* This is causing a 500 error when clicking links for pages that rely on the pathname to specifically not end in .json

fix(web): Trim .json from pathname extraction function

---

apps/web/utils/safelyExtractPathnameFromUrl.ts

fix(web): Hotfix - Trim .json from pathname extraction function (#12085)

---

apps/judicial-system/backend/src/app/modules/case/case.service.ts
apps/judicial-system/backend/src/app/modules/case/test/caseController/getCourtRecordSignatureConfirmation.spec.ts

[Ef ekki tekst að vista undirritaða þingbók í S3 þá á undirritun ekki að heppnast](https://app.asana.com/0/1199153462262248/1205393867190019/f)
- Fails a court record signature if the signed court record cannot be uploaded to S3.
- If the upload fails, then the signed court record cannot be accessed.

fix(j-s): Court Record Signature Failure

---

libs/auth-api-lib/src/lib/resources/admin/admin-scope.service.ts
libs/auth/shared/src/index.ts
libs/auth/shared/src/lib/utils/validateClientId.spec.ts
libs/auth/shared/src/lib/utils/validateIdMockData.ts
libs/auth/shared/src/lib/utils/validatePermissionId.spec.ts
libs/auth/shared/src/lib/utils/validatePermissionId.ts
libs/portals/admin/ids-admin/src/lib/messages.ts
libs/portals/admin/ids-admin/src/screens/Permission/CreatePermission/CreatePermission.action.ts

Allow colon in the permission id
To create a permission/scope with id format "@test.island.is/test:test"
Updated error message
Newly created permission

feat(auth-admin): Allow colon in permission ID

---

apps/download-service/src/app/modules/occupational-licenses/education-license.controller.ts
libs/api/domains/occupational-licenses/src/lib/occupationalLicenses.resolver.ts
libs/service-portal/occupational-licenses/src/screens/EducationalDetail/EducationalDetail.tsx
libs/service-portal/occupational-licenses/src/screens/HealthDirectorateDetail/HealthDirectorateDetail.tsx
libs/service-portal/occupational-licenses/src/screens/OccupationalLicensesOverview/OccupationalLicensesOverview.tsx

Fixed download service controller so that now it receives the parameter from the URL. Fixed incorrect date format displayed in the occupation license UI
For teacher to see correct dates and be able to download their license from the web.

fix(service-portal): Occupational license fix download service and date format

---

apps/services/search-indexer/infra/search-indexer-service.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
libs/cms/src/lib/search/cmsSync.module.ts
libs/cms/src/lib/search/contentful.service.ts
libs/feature-flags/src/lib/features.ts

* We are storing CMS data in Elasticsearch so we can search through it and provide a backup in case the CMS goes down.
* The CMS calls an endpoint on the search-indexer service when content changes but when something nested gets changed (like an accordion) then we need to traverse up the tree to find the page (indexable entry) that we need to re-index so the update is displayed on the web. But this process is especially slow if something nested gets updated with a lot of backlinks then (with the current implementation) it takes a long time and can even make the search-indexer run out of memory. So when something like that happens it's good to be able to turn off the nested resolution so new content actually starts appearing on the web again

feat(search-indexer): Use feature flag instead of env variable for turning nested entry resolving on or off

---

apps/services/auth/ids-api/src/app/user-profile/user-profile.controller.spec.ts
apps/services/auth/ids-api/test/setup.ts
libs/services/auth/testing/src/fixtures/apiScope.fixture.ts
libs/testing/fixtures/src/index.ts
libs/testing/fixtures/src/utils/createUniqueWords.ts
libs/testing/nest/src/lib/testServer.ts

Attempt to fix flaky test in ids-api. Most likely the reason for this flaky test is that faker will not generate unique scope names. At least that is my presumption.
This PR will ensure that those names are unique since they are used as primary keys in the scope model
Our CI has some flaky tests, i.e. https://github.com/island-is/island.is/actions/runs/5761331315/job/15619298536

fix(ids-api): Fix flaky test in ids-api

---

scripts/_run-aws-eks-commands.js

Removes the removed method `onFinishCommand` in-favour of promise
`yargs` dependency was updated yesterday, which broke the db-proxy script. They removed `onFinishCommand` from the package.
[issue](https://github.com/yargs/yargs/issues/1947)

fix(chore): Fix db-proxy scripts after yargs update

---

apps/system-e2e/src/playwright.config.ts

Retries are causing up to 90 minute CI runs. This is unacceptable.
Initially retries were added to catch flaky tests. It's debatable which is better. For now, test failures due to flaky test is better than ridiculous test times.

chore(system-e2e): Disable retries in CI

---

apps/api/infra/api.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

Turn off failsafe for licenses resolver.
To stop the failsafe being default ON in deployments and re-enable hotfixes.
N/A

fix(api-infra): Remove default licenses failsafe ON in api infra.

---

libs/cms/src/lib/search/contentful.service.ts

* I removed code that was stripping away fields to save up memory but since the deletedEntries don't have a fields property there is very little gain in having that code there and it even had a typo in it which was indexing the wrong array to begin with
* This fixes the `Importer failed Cannot read properties of undefined (reading 'id')` error we've been seeing in logs

fix(search-indexer): Imports failing due to missing deleted entry ids

---

apps/web/components/Project/Header/DefaultProjectHeader.css.ts
apps/web/screens/Project/utils.tsx
apps/web/screens/queries/Project.tsx
libs/cms/src/lib/generated/contentfulTypes.d.ts
libs/cms/src/lib/models/projectPage.model.ts

* Add an option to display a secondary sidebar for project pages (similar to what organization pages can do today)
* Remove css forcing header to have a minimum height to prevent whitespace in case header content is smaller than that
Desktop
Mobile

feat(web): Project page secondary sidebar option

---

libs/service-portal/vehicles/src/screens/DrivingLessonsBook/DrivingLessonsBook.tsx

Only show driving schools with status of `2` in driving lesson school table
Comment from Samgöngustofa:
> Ámínum síðum fyrir Ökunámið undir Ökuskóla er ekki verið að athuga stöðuna á Ökuskólanum. (þ.e. hann getur verið hætt við eða útrunninn)
Þannig undir drivingSchoolExams í GetStudentOverview ætti bara að birta ökuskóla sem eru "status": 2

fix(service-portal): Only show driving school exam with status 2

---

apps/judicial-system/web/src/routes/Shared/Cases/ActiveCases.tsx
apps/judicial-system/web/src/utils/hooks/useSort/useSortAppealCases.ts
apps/judicial-system/web/src/utils/hooks/useSort/useSortCases.ts

[Laga stafrófsröð í málalistum vegna Chrome](https://app.asana.com/0/1199153462262248/1205417850909473/f)
Change how we sort lists 
Because sorting by Icelandic letters doesn't work in Chrome as is

fix(j-s): Use compare locale IS for alphabetized sorting

---

libs/service-portal/information/src/screens/Child/Child.tsx
libs/service-portal/information/src/screens/UserInfo/UserInfo.graphql
libs/service-portal/information/src/screens/UserInfo/UserInfo.tsx

Add back tooltip split name
It's not active after service change as the data has been updated.

fix(service-portal): Add back tooltip split name

---

apps/web/screens/ServiceWeb/Home/Home.tsx

fix(web): Use correct slug when querying service web slices

---

apps/web/screens/queries/LifeEvents.tsx

* The life event pages aren't able to display nested accordions since it's missing from the query

feat(web): Query nested fields for life event pages

---

apps/web/screens/Project/Project.tsx
apps/web/screens/Project/ProjectTableOfContents.tsx
apps/web/screens/queries/Project.tsx
libs/cms/src/lib/generated/contentfulTypes.d.ts
libs/cms/src/lib/models/projectSubpage.model.ts

* Add a boolean field to the project subpage content type which displays a table of contents component if toggled on
* This feature is already present on organization subpages and is needed for project subpages as well

feat(web): Add table of contents to project subpage

---

apps/web/i18n/I18n.tsx
apps/web/pages/api/rss/index.ts

* We no longer rely on a specific tag per news item but instead there is now an organization field that news can have. We need to start utilizing that field in the rss feed so we can fetch all news that a specific organization owns (previously this was done using a tag but that isn't necessarily the case anymore since you could skip having tags and only filling out the organization field in the cms for news)
* Add types for api route since previously there was a ts-ignore comment

feat(web): Filter rss feed by organization

---

.github/workflows/pullrequest.yml
.github/workflows/push.yml
libs/cms/src/lib/models/powerBiSlice.model.ts

- We are running NX parallel=3 for tests in PRs but parallel=1 on push.
- PR checks are green and therefore are merged
- Tests running after merged are failing due to timeouts
This sets the same parallelism on PRs and merge (push) workflows

ci: increase nx parallel 1 -> 3 for tests in push workflow

---

libs/cms/src/lib/search/importers/utils.ts

* We are trimming away too much data from entry-hyperlinks, we'd like to keep fields like the title of an entry and so forth
* This change stops removing everything other than slug and url named fields and instead removes all object fields
* This'll address an issue on the web where links appear without a title

fix(search-indexer): Remove non primitive fields instead of everything except slug and url

---

libs/auth-api-lib/src/lib/delegations/DelegationConfig.ts

Adding delegation custom scope rule for `@island.is/fishing-license` to have it only enabled for companies in the delegation system.
So individuals can't grant delegations with the fishing license scope.
N/A

feat(auth-api-lib): Add delegation custom scope rule for @island.is/fishing-license scope.

---

apps/web/components/connected/HousingBenefitCalculator/HousingBenefitCalculator.tsx
apps/web/screens/queries/HousingBenefitCalculator.ts
libs/api/domains/housing-benefit-calculator/src/lib/models/calculation.model.ts
libs/clients/housing-benefit-calculator/src/lib/housing-benefit-calculator.service.ts

fix(web): Hotfix - Change what reductions field is displayed in housing benefit calculator (#12238)

---

libs/cms/src/lib/search/importers/utils.ts

fix(search-indexer): Hotfix - Remove non primitive fields instead of everything except slug and url (#12243)

---

apps/judicial-system/api/src/app/modules/auth/auth.controller.ts

Redirect defendant to case list if no redirect link is sent with login request
So that defendants can log in through the main page

fix(j-s): Log in defender fix

---

apps/consultation-portal/screens/Case/components/BlowoutList/BlowoutList.tsx

https://veflausnir.atlassian.net/browse/KAM-1666
- There was extra margin in the box when there where no stakeholders

feat(consultation-portal): fix extra margin shown

---

apps/judicial-system/web/src/routes/Defender/CaseOverview.strings.ts
apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx

[Breyta birtingu á óútfylltum svæðum í info card](https://app.asana.com/0/1199153462262248/1205537726590934/f)
Hide judge field if empty and show default text if there is no court case number on case
To make the overview more clear

fix(j-s): Hide judge and default string for court case number if empty

---

libs/api/domains/communications/src/lib/communications.service.ts

* After a bit of debugging I figured out that the content type header is being set automatically by axios and that's why sometimes it was incorrect and other times it was application/json and got a successful response
* By setting it explicitly I'm hoping we can stop seeing form submit fails on prod like we've been seeing for the past couple of days
* Also we've now stopped logging the entire error object and have now moved back to logging just the message

fix(web): HSN web form - Set "Content-Type" header to "application/json"

---

libs/api/domains/communications/src/lib/communications.service.ts

fix(web): Hotfix - Explicitly set HSN form response header (#12287)

---

libs/application/template-api-modules/src/lib/modules/shared/api/driving-license/driving-license.service.ts

After changes in API version, the license is now under "nr" field and not "name" field

fix(digital tachograph): Fix shared template api currentLicense when using validCategories param

---

apps/web/components/Footer/Footer.tsx
apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx

* By default there is now no logo displayed and the footer title is an h3 visually but always an h2 element

feat(web): Remove org logo from default footer

---

libs/application/ui-components/src/components/ApplicationCard/utils/history.tsx
libs/portals/admin/application-system/src/components/ApplicationDetails/ApplicationDetails.tsx

Stop using the date today as the date value for pending action. It should be the last history message date.
Users would probably get confused by the always changing date, thinking that the application is getting updated daily.

fix(history-application-system): Using the last history message as the date for the pending action

---

libs/service-portal/documents/src/screens/Overview/Overview.tsx

Hide docline list when active doc mobile
It should not be shown when a document is active.

fix(service-portal): Hide shown document list mobile

---

apps/system-e2e/entrypoint.sh
apps/system-e2e/src/notifications/notify.ts

In #12328 I tried setting the project which failed in the Slack message. I incorrectly assumed that `TEST_PROJECT` was the project which failed, but didn't check what the actual value was. Trying again with this PR, basing on the reality.
From CI logs:
```
Current test environment: dev
Playwright args: judicial-system/smoke
Playwright project: everything
```

chore(system-tests): Show which project failed

---

libs/cms/src/lib/search/importers/utils.spec.ts
libs/cms/src/lib/search/importers/utils.ts

* Continuation for PR -> https://github.com/island-is/island.is/pull/12363
* If there was more than one way to make a circular loop in an entry-hyperlink node the code wouldn't index pages that had that state
* Add edge case test and fix for when there's more than one way to "close the circle"
PR 12363 basically just removed the line on the left

fix(search-indexer): Prune entry hyperlink node fields that are not primitive

---

apps/web/screens/queries/Article.ts

* We noticed that the new default footer didn't have the correct color on the article page and it turns out it's because we weren't even querying for the footerConfig

fix(web): Add footerConfig to article query

---

apps/judicial-system/backend/src/app/modules/file/file.controller.ts
apps/judicial-system/backend/src/app/modules/file/guards/viewCaseFile.guard.ts
apps/judicial-system/backend/src/app/modules/file/test/fileController/getCaseFileSignedUrlRolesRules.spec.ts

Allow prison system staff to open COA results
Because they should see it

fix(j-s): Allow prison system user COA result access

---

apps/system-e2e/src/tests/islandis/service-portal/smoke/work-license.spec.ts

Fix e2e test work license
Response + path changed

fix(system-e2e): Test work license path and name

---

apps/web/components/Form/Form.tsx

* I recently changed the form component a bit but forgot to add a space between the sender's name and his email

fix(web): Add missing whitespace in form message

---

libs/service-portal/documents/src/components/DocumentRenderer/PdfDocument.tsx

Use pagination instead of displaying all documents at once
Instead of displaying all pages at once.

chore(service-portal): Use pagination instead of displaying all documents inbox

---

apps/consultation-portal/screens/Case/utils/getStakeholdersList.ts

https://veflausnir.atlassian.net/browse/KAM-1796
- If extraStakeholderList is an empty string, it should not render the empty string in the stakeholder list

fix(consultation-portal): Boð um þátttöku has empty string

---

apps/services/sessions/project.json

After #12152 the build target changed as it was simplified. This broke the `yarn start` command for the service.
To fix the start command for the service.
N/A

fix(services-sessions): Fix serve buildTarget to fix yarn start for the service.

---

charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
charts/judicial-system/values.dev.yaml
charts/judicial-system/values.prod.yaml
charts/judicial-system/values.staging.yaml
infra/src/dsl/basic.spec.ts
infra/src/dsl/feature-values.spec.ts
infra/src/dsl/ingress.spec.ts
infra/src/dsl/output-generators/map-to-helm-values.ts
infra/src/dsl/types/input-types.ts

We have been seeing timeouts for scale down events and when we roll over to a new release due to nginx sending requests to pods that have already been set to a terminating state.
This can cause the user to hang for a while and then see a 504 timeout from nginx with no obvious error message

fix: set default service upstream to true for fully zero downtime deployments

---

libs/application/ui-components/src/components/PaymentPending/hooks/usePaymentStatus.ts

Changed the fetch policy for `getstatus` to `network-only`
Using the default fetchPolicy `cache-first` will cache the paymentUrl that results in an error from ARK when a payment is requested for a deleted charge.

fix(application-system): Get status fetchpolicy

---

libs/island-ui/core/src/lib/Text/Text.css.ts

There are global styles in the core Text component that force an SVG's path to a specific color when rendered inside an anchor tag in specific contexts.
The SVG path should instead only inherit `currentColor` and be controlled by the DOM parent tree. This affects SVGs that may not intend on having a path rendered (for example, the Arrow icons).

fix(web): remove svg path styles

---

libs/api/domains/rights-portal/src/lib/healthCenter/healthCenter.service.ts

Adding can register property to the response
So that users can change their health center registration

fix(service-portal): Adding property to response

---

libs/application/template-api-modules/src/lib/modules/shared/api/driving-license/driving-license.service.ts

Mistakenly removed legacy params when refactoring.
The function, albeit called legacy, only consists of v4/v5 endpoints. There are some special cases being handled in there and need to be addressed at a later refactor. Hence we re-introduce the legacy pathway here.

fix(application): Driving License Client needs to listen to legacy params

---

apps/judicial-system/backend/src/app/modules/case/interceptors/case.interceptor.ts

[Sía FMST starfsmenn út úr virkni sem merkir hvort fangelsi hafi opnað úrskurð Landsréttar](https://app.asana.com/0/1199153462262248/1205805678997183)
Only log "prison system staff" roles that are in institution type "prison"
Because other prison staff having opened the appeal result isn't relevant to our use case

fix(j-s): Only add prison system staff in Prison institutions to event log

---

libs/api/domains/license-service/src/lib/licenseService.service.ts
libs/clients/license-client/src/lib/clients/adr-license-client/adrLicenseClient.service.ts
libs/clients/license-client/src/lib/clients/disability-license-client/services/disabilityLicenseClient.service.ts
libs/clients/license-client/src/lib/clients/driving-license-client/services/drivingLicenseClient.service.ts
libs/clients/license-client/src/lib/clients/firearm-license-client/services/firearmLicenseClient.service.ts
libs/clients/license-client/src/lib/clients/machine-license-client/machineLicenseClient.service.ts
libs/clients/license-client/src/lib/licenseClient.type.ts

Have the pkpass functionality in the license client optional
Makes it more usable for non-pkpass licenses

feat(license-client): make the license client more generic

---

libs/application/utils/src/lib/builders/paymentStateBuilder.ts

Remove  `shouldDeleteChargeIfPaymentFulfilled: true,`  to be default
Was causing problems with a Driving licence application where the application could not advance due to an error from an on entry api but the application was still being sent. Then the  user deleted the application within the payment state and got refunded.

fix(application-system): remove payment defaults

---

libs/application/utils/src/lib/builders/paymentStateBuilder.ts

Remove  `shouldDeleteChargeIfPaymentFulfilled: true,`  to be default
Was causing problems with a Driving licence application where the application could not advance due to an error from an on entry api but the application was still being sent. Then the  user deleted the application within the payment state and got refunded.

fix(application-system): Remove default delete from payment state builder

---

libs/application/templates/announcement-of-death/src/lib/dataSchema.ts
libs/clients/syslumenn/src/lib/syslumennClient.utils.ts

Aggressive regex was filtering out legitimate properties, coming in as 6 or 7 digits (missing `F` prefix).
This is causing properties present in the District Commissioner's database to be lost when transitioting to our application system.
Note, that it may look strange to test the data coming from DC but since we're injecting them into the application's answers (for convenience) we validate data the same way we would in the application frontend with our dataschema.

fix(application-estate): Property mapping fixes

---

apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx

[Verjandi getur ekki sent inn greinargerð eftir að greinargerðarfrestur er liðinn](https://app.asana.com/0/1199153462262248/1205833684526261/f)
- When the statement deadline was expired the defender was routed to the appeal brief page rather than the appeal satement page. This has been fixed.

fix(j-s): Defender Appeal Statement

---

apps/service-portal/src/components/ContentBreadcrumbs/ContentBreadcrumbs.tsx

* Only display go back with arrow on mobile
* Use all ancestors to determine if an item in breadcrumbs has a parameter name
* Go back could be displayed in the middle of crumbs if middle item has breadCrumbsHidden=true
* Ancestors with param name will display the string, example 
`Yfirlit | id | Nánar` instead of `Yfirlit | 123 | Nánar`.
Was 😞 
Becomes 😃

fix(service-portal): Update breadcrumbs

---

libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.service.ts

A plaster to ensure that applications calculated for B-full will have phone numbers included, but this was causing the license creation to fail.
After this plaster has launched we need to make sure the driving license application calculates phone numbers or accesses it in another way before submission.

fix(application-driving-license): Plaster for miscalculated phone

---

apps/service-portal/src/components/Layout/FullWidthLayout.tsx
apps/service-portal/src/components/TabNavigation/SubTabItem.tsx
apps/service-portal/src/components/TabNavigation/TabNavigation.css.ts
apps/service-portal/src/components/TabNavigation/TabNavigation.tsx

Add tab navigation as button navigation
Add subnav support for tabnav
There is no support in the <Tabs /> component to support nested navigation.
And this approach is more natural for a nav + screen rendering instead of using the <Tabs />

chore(service-portal): Add tab navigation as button navigation

---

apps/judicial-system/backend/src/app/modules/notification/guards/rolesRules.ts

[Aðstoðarmaður Landsréttar og dómarar LR fá tölvupóst þegar þeir eru skráðir á málið af Landsrétti ](https://app.asana.com/0/1199153462262248/1205681517617898/f)
- Allows judge assistants to send role assignment notifications at the appeals court.

fix(j-s): Notification Permissions

---

apps/consultation-portal/hooks/api/useFetchEmail.ts
apps/consultation-portal/screens/Subscriptions/components/EmailBox/EmailBox.tsx
apps/consultation-portal/screens/Subscriptions/components/SubscriptionsSkeleton/SubscriptionsSkeleton.tsx

https://veflausnir.atlassian.net/browse/KAM-1847
User can only view subscription options once his email has been verified

fix: KAM-1847: Subscription option should not show up until verified email

---

apps/air-discount-scheme/api/infra/api.ts
apps/air-discount-scheme/backend/infra/backend.ts
apps/api/infra/api.ts
apps/application-system/api/infra/application-system-api.ts
apps/icelandic-names-registry/backend/infra/icelandic-names-registry-backend.ts
apps/judicial-system/backend/infra/judicial-system-backend.ts
apps/services/auth/ids-api/infra/identity-server.ts
apps/services/documents/infra/documents-service.ts
apps/services/endorsements/api/infra/endorsement-system-api.ts
apps/services/sessions/infra/sessions.ts
apps/services/user-profile/infra/service-portal-api.ts
apps/skilavottord/web/infra/web.ts
apps/skilavottord/ws/infra/ws.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
charts/judicial-system/values.dev.yaml
charts/judicial-system/values.prod.yaml
charts/judicial-system/values.staging.yaml
infra/src/dsl/dsl.ts
infra/src/environments.ts

PR #12323 didn't suffice to turn off the npm notice logs in datadog due to most of the apps infra files are explicitly settings the `envs` property with the old npm config which override the common dsl config. 
This PR simplifies this by adding the new `NPM_CONFIG_UPDATE_NOTIFIER=false` env variable to the global env variables in `infra/src/environments.ts`, then removes all usage of the old `NO_UPDATE_NOTIFIER=true` config.
To reduce noice in DataDog due to this redundant logging.
N/A

chore(core): Simplify infra config to add NPM_CONFIG_UPDATE_NOTIFIER=false to turn of npm notice logs

---

apps/web/layouts/main.tsx
apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacanciesList.tsx
apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacancyDetails.tsx
libs/api/domains/icelandic-government-institution-vacancies/src/lib/icelandic-government-institution-vacancies.resolver.ts

* Orri (the system used to apply for jobs and post jobs) will be down due to maintenance in the upcoming days.
* This PR adds an option to display an alert banner and also we now catch the error if the xroad vacancies endpoint fails and simply return no jobs if that is the case
* This was requested by Fjársýslan

feat(web): Add alert banner option to /starfatorg

---

libs/service-portal/finance/src/components/FinanceStatusDetailTable/FinanceStatusDetailTable.tsx
libs/service-portal/finance/src/components/FinanceStatusTableRow/FinanceStatusTableRow.tsx

Incorrect chargeType name was being displayed in Finance status when exporting
To get correct data

fix(service-portal): display correct chargeType in xls/csv export

---

apps/web/components/Webreader/Webreader.tsx
apps/web/components/Webreader/index.ts

* We are missing an id for the readspeaker script which is a likely cause for it sometimes not loading correctly
https://wrdev.readspeaker.com/index.php/get-started/implementation/dynamic-loading
* This PR adds that id as well as dynamically importing the webreader on the server side

fix(web): Webreader not loading correctly

---

apps/consultation-portal/screens/Case/Case.json

https://veflausnir.atlassian.net/browse/KAM-1860
https://github.com/island-is/island.is/pull/12667
Change wording for hiding advice

fix(consultation-portal): KAM-1860: fix wording (#12667)

---

apps/consultation-portal/lib/shared.json
apps/consultation-portal/screens/Case/Case.json
apps/consultation-portal/screens/Case/components/AdviceForm/AdviceForm.tsx
apps/consultation-portal/screens/Case/components/AdviceList/AdviceList.tsx
apps/consultation-portal/screens/Case/components/CaseStatusBox/CaseStatusBox.tsx
apps/consultation-portal/screens/Case/components/CaseStatusText/CaseStatusText.tsx
apps/consultation-portal/screens/Case/components/index.ts

* KAM-1857: fix wording in statuses
* retComp as const
---------
https://veflausnir.atlassian.net/browse/KAM-1857
https://github.com/island-is/island.is/pull/12662
- Change wording in status box
- CaseStatusText returns an array so that we can get formatting on the link

fix(consultation-portal): KAM-1857: fix wording in statuses (#12662)

---

apps/web/components/Organization/Wrapper/Themes/DefaultTheme/index.ts
apps/web/components/Organization/Wrapper/Themes/DigitalIcelandTheme/index.ts
apps/web/components/Organization/Wrapper/Themes/FiskistofaTheme/index.ts
apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/index.ts
apps/web/components/Organization/Wrapper/Themes/GevTheme/index.ts
apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunAusturlandsTheme/index.ts
apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunNordurlandsTheme/index.ts
apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunSudurlandsTheme/index.ts
apps/web/components/Organization/Wrapper/Themes/HmsTheme/index.ts
apps/web/components/Organization/Wrapper/Themes/HveTheme/index.ts
apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/index.ts
apps/web/components/Organization/Wrapper/Themes/IcelandicRadiationSafetyAuthority/index.ts
apps/web/components/Organization/Wrapper/Themes/LandkjorstjornTheme/index.ts
apps/web/components/Organization/Wrapper/Themes/LandlaeknirTheme/index.ts
apps/web/components/Organization/Wrapper/Themes/RettindagaeslaFatladsFolksTheme/index.ts
apps/web/components/Organization/Wrapper/Themes/RikislogmadurTheme/index.ts
apps/web/components/Organization/Wrapper/Themes/RikissaksoknariTheme/index.ts
apps/web/components/Organization/Wrapper/Themes/SAkTheme/index.ts
apps/web/components/Organization/Wrapper/Themes/SHHTheme/index.ts
apps/web/components/Organization/Wrapper/Themes/SjukratryggingarTheme/index.ts
apps/web/components/Organization/Wrapper/Themes/SyslumennTheme/index.ts
apps/web/components/Organization/Wrapper/Themes/TryggingastofnunTheme/index.ts
apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/index.ts
apps/web/components/Organization/Wrapper/Themes/UtlendingastofnunTheme/index.ts
apps/web/layouts/main.tsx
libs/cms/src/lib/cms.resolver.ts

* Dynamically imported headers via SSR are not working well with alert banners since that causes them to "bug out" (see video below)
* To prevent layout shift and headers bugging out if there is an alert banner above them
https://github.com/island-is/island.is/assets/43557895/2ca6d1ee-a34b-49cc-9b26-062159c9fec0

fix(web): Remove dynamic imports for headers

---

apps/services/user-profile/src/app/user-profile/e2e/userProfile.spec.ts
apps/services/user-profile/src/app/user-profile/verification.service.ts
apps/services/user-profile/src/app/v2/user-profile.service.ts

Revert using formatted phone number in sms verification as Nova SMS service throws and error on the formatted number.
To fix error in sending sms with Nova.
N/A

fix(user-profile): Reverting using formatted phone number in sms verification

---

apps/services/user-profile/src/app/user-profile/verification.service.ts
apps/services/user-profile/src/app/v2/test/me-user-profile.controller.spec.ts

Continue fix in #12693 that the phonenumber  needs to be parsed in confirmSMS
So confirmSMS finds the match and succeeds to confirm the sms code.
N/A

fix(user-profile): Parse phone number to find match in confirmSMS

---

apps/web/components/Organization/Slice/Render/SliceDropdown.tsx

fix(web): Add spacing between slice dropdown and first element

---

apps/consultation-portal/screens/Case/utils/shouldShowStakeholdersBox.ts

https://veflausnir.atlassian.net/browse/KAM-1865
https://github.com/island-is/island.is/pull/12691
Change date in date check for shouldShowStakeholdersBox to 10th
Change comparison of dates to getTime()

fix(consultation-portal): KAM-1865: changed launch date (#12691)

---

apps/consultation-portal/components/DebouncedSearch/DebouncedSearch.tsx
apps/consultation-portal/components/Layout/Layout.tsx
apps/consultation-portal/hooks/useFrontPageFilters.ts
apps/consultation-portal/screens/Home/Home.tsx
apps/consultation-portal/screens/Home/components/SearchAndFilter/SearchAndFilter.tsx

https://veflausnir.atlassian.net/browse/KAM-1866
On initial rendering, let search box wait for filters to load until populating the field
Removing dynamic for specific components

fix(consultation-portal): KAM-1866: Search getting filter value once filters are loaded

---

libs/application/templates/parental-leave/src/forms/AdditionalDocumentsRequired.ts
libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
libs/application/templates/parental-leave/src/forms/ResidenceGrant.ts
libs/application/templates/parental-leave/src/lib/messages.ts

change descriptions for uploads
default text was all endings but we just allow .pdf

fix(parental-leave): change descriptions for uploads

---

apps/consultation-portal/screens/Case/utils/shouldShowStakeholdersBox.ts

https://veflausnir.atlassian.net/browse/KAM-1868
Only show stakeholders box if case has been added on and after 13th November

fix(consultation-portal): KAM-1868: Change launch date to 13th of Nov

---

apps/services/auth/delegation-api/infra/delegation-api.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml

Increase memory of delgationapi to request 256m and limit 512m to make it more stable while we debug.
The delegation api is being restarted multiple times a day, so trying to increase the memory to make it more stable.
The usage of the delegation system has increased but there might also be some expensive methods in the application code that can be improved.
This hopefully makes the api more stable while we work on fixes.
N/A

chore(delegation-api): Increase memory of delgation api

---

.github/CODEOWNERS
libs/portals/admin/icelandic-names-registry/src/components/Editor/Editor.tsx

Add #12706 to release to fix icelandic names registry admin module.
It's currently broken as employees of Þjóðskrá cannot edit names to add link to a ruling.
N/A

fix(portals-admin-icelandic-names-registry): Fix name update mutation

---

libs/service-portal/assets/src/screens/AssetsOverview/AssetsOverview.tsx
libs/service-portal/assets/src/screens/Overview/Overview.tsx
libs/service-portal/assets/src/screens/WorkMachinesDetail/WorkMachinesDetail.tsx
libs/service-portal/core/src/components/LinkButton/LinkButton.tsx
libs/service-portal/core/src/screens/NoDataScreen/NoDataScreen.tsx
libs/service-portal/documents/src/components/DocumentActionBar/DocumentActionBar.tsx
libs/service-portal/documents/src/components/DocumentRenderer/UrlDocment.tsx
libs/service-portal/education/src/screens/DrivingLessonsBook/DrivingLessonsBook.tsx
libs/service-portal/health/src/screens/HealthOverview/HealthOverview.tsx
libs/service-portal/information/src/components/PersonalInformation/Forms/ProfileForm/components/FormButton.tsx
libs/service-portal/licenses/src/screens/LicenseDetail/LicenseDetail.tsx

Render <Button> component as span when inside links
<button> inside link is not valid

fix(service-portal): Don't render button element inside anchors

---

libs/service-portal/assets/src/screens/AssetsOverview/AssetsOverview.tsx
libs/service-portal/assets/src/screens/Overview/Overview.tsx
libs/service-portal/core/src/components/GoBack/GoBack.tsx
libs/service-portal/core/src/components/LinkButton/LinkButton.tsx
libs/service-portal/core/src/screens/NoDataScreen/NoDataScreen.tsx
libs/service-portal/documents/src/components/DocumentActionBar/DocumentActionBar.tsx
libs/service-portal/education/src/screens/DrivingLessonsBook/DrivingLessonsBook.tsx
libs/service-portal/finance/src/screens/FinanceSchedule/FinanceSchedule.tsx
libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx
libs/service-portal/health/src/screens/HealthOverview/HealthOverview.tsx
libs/service-portal/health/src/screens/Medicine/MedicinePurchase.tsx
libs/service-portal/health/src/screens/Payments/wrapper/PaymentsWrapper.tsx
libs/service-portal/licenses/src/screens/LicenseDetail/LicenseDetail.tsx
libs/service-portal/licenses/src/screens/PassportDetail/PassportDetail.tsx

Button component always has tabindex=0 for some reason, need to take  that off when rendered as span inside link
To avoid doubple tabbing inside links

fix(service-portal): avoid double tabbing on button links

---

apps/web/screens/Project/utils.tsx

So the buttons in the header have the correct color theme

fix(web): Use light theme for grindavik project page header

---

apps/consultation-portal/components/Layout/components/Menu/Menu.tsx
apps/consultation-portal/components/Layout/components/Menu/components/MenuModal/MenuModal.tsx

https://veflausnir.atlassian.net/browse/KAM-1894
https://veflausnir.atlassian.net/browse/KAM-1894
Large logo has 160x28 size and small logo has 28x28 size
Small logo should always be on mobile applications

fix(consultation-portal): logo with same size as island.is (#12801)

---

libs/application/templates/passport/src/lib/PassportTemplate.ts

Removed `shouldDeleteChargeIfPaymentFulfilled: true` for all states exluding `ParentB`.
Payments were being refunded when the payment had been fulfilled and the passport had been processed

fix(passport): Passport lifecycle fix

---

libs/application/templates/passport/src/lib/PassportTemplate.ts

Removed `shouldDeleteChargeIfPaymentFulfilled: true` for all states exluding `ParentB`.
Payments were being refunded when the payment had been fulfilled and the passport had been processed

fix(passport-application): Lifecycle fix

---

libs/service-portal/documents/src/screens/Overview/Overview.css.ts
libs/service-portal/documents/src/screens/Overview/Overview.tsx

Replace button as h1, with text as h1.
The button takes on a button role even though it is set `as=h1`.
We are using this as a heading but it is seen by the user as part of the breadcrumbs.

fix(service-portal): Heading as text

---

libs/api/domains/rights-portal/src/lib/drug/models/drugCertificate.model.ts
libs/clients/icelandic-health-insurance/rights-portal/src/clientConfig.json
libs/service-portal/health/src/lib/messages.ts
libs/service-portal/health/src/screens/Medicine/Medicine.graphql
libs/service-portal/health/src/screens/Medicine/MedicineLicense.tsx
libs/service-portal/health/src/screens/MedicineCertificate/MedicineCertificate.graphql
libs/service-portal/health/src/screens/MedicineCertificate/MedicineCertificate.tsx

Display more detailed medicine certificate status
TO show correct certificate status

fix(service-portal): add correct statuses to medicine certificates

---

apps/judicial-system/web/src/routes/CourtOfAppeal/components/CaseFilesOverview/CaseFilesOverview.tsx

[Asana](https://app.asana.com/0/1199153462262248/1205950041984082/f)
Fix spacing in CaseFilesOverview component

chore(j-s): Fix spacing in CaseFilesOverview component

---

libs/judicial-system/formatters/src/lib/formatters.spec.ts
libs/judicial-system/formatters/src/lib/formatters.ts

[Asana](https://app.asana.com/0/1199153462262248/1206046984488078/f)
We have a `sanitize` function that replaces all instances of `"` with an empty string. There was a minor issue with our implementation in that we were only targeting the first instance.
This is both incorrectly implemented and is showing up in island.is code scanning tool.

chore(j-s): Fix sanitize function

---

libs/application/templates/estate/src/forms/Forms.ts
libs/application/templates/estate/src/forms/OverviewSections/assetsAndDebts.ts
libs/application/templates/estate/src/lib/messages.ts

https://app.asana.com/0/1204431115744096/1205939903295179
Adds a total value field below each `Card` section
Requested in a task

feat(estate): add sum fields in estate overview

---

libs/service-portal/health/src/screens/HealthOverview/HealthOverview.tsx
libs/service-portal/health/src/screens/Medicine/wrapper/MedicineWrapper.tsx
libs/service-portal/health/src/screens/Payments/wrapper/PaymentsWrapper.tsx

Make sure user has insurance before displaying insurance status
So people without insurance don't get confused

fix: check if isInsured is false for determining insurance status

---

libs/service-portal/information/src/components/PersonalInformation/Forms/ProfileForm/ProfileForm.tsx

fix(service-portal): User settings adds encoding to returnUrl

---

libs/service-portal/assets/src/screens/VehicleDetail/VehicleDetail.tsx
libs/service-portal/assets/src/screens/VehicleMileage/VehicleMileage.tsx
libs/service-portal/core/src/components/LinkButton/LinkButton.css.ts
libs/service-portal/core/src/components/LinkButton/LinkButton.tsx
libs/service-portal/core/src/components/LinkResolver/LinkResolver.tsx
libs/service-portal/core/src/components/UserInfoLine/UserInfoLine.tsx
libs/service-portal/health/src/components/FootNote/helper.tsx
libs/service-portal/licenses/src/utils/dataMapper.tsx

Add a shared service-portal component that can be displayed as a button or text, and will resolve to react-router link or external link all on its own.
We've had to do this same thing too many times.

chore(service-portal): Update link button service portal component

---

apps/api/esbuild.json
apps/application-system/api/esbuild.json
apps/financial-aid/backend/esbuild.json
apps/judicial-system/backend/esbuild.json
apps/services/endorsements/api/esbuild.json
apps/services/user-profile/esbuild.json

Due to recent upgrade of the glob package `path-scurry` package depends on a newer `lru-cache` version then most of our other package dependencies. Hence there is a version mismatch and `path-scurry` needs to be added as external dependency in esbuild for APIs using the `emailService`.
* judicial-system-backend
* api
* application-system-api
* financial-aid-backend
* services-endorsement-api
* services-user-profile
So APIs can start up again.
N/A

fix(core): Add esbuild.json external to fix glob update regression

---

libs/service-portal/core/src/components/IntroHeader/IntroHeader.tsx

No logo when no provider provided
There should be no logo displayed when no provider is provided to the introheader component.

fix(service-portal): No logo when no provider provided

---

apps/judicial-system/web/src/components/CourtDocuments/CourtDocuments.tsx
apps/judicial-system/web/src/types/index.ts

[Asana](https://app.asana.com/0/1199153462262248/1205991136769086/f)
In the CourtDocuments component, you could not delete items with the same name. Now you can. Also, imporved the loading indication when deleting documents.
https://github.com/island-is/island.is/assets/3789875/6044d866-4320-4e99-a137-e71d5a2f287b

fix(j-s): Handle court documents with the same name

---

libs/api/domains/communications/src/lib/environments/environment.ts

* When testing out emails locally it's convenient to be able to set an environment variable whether or not we want emails to be sent to the "Nodemailer App" for us to be able to preview them

chore(communications): Add useNodemailerApp to communications domain options

---

libs/api/domains/communications/src/lib/emailTemplates/serviceWebForms.ts

feat(web): Hotfix - Change what email Grindavík service web form gets sent to depending on categories (#13009)

---

apps/web/screens/Project/components/ProjectFooter/ProjectFooter.tsx

* Default header image field on Project pages should not be shown in the footer

fix(web): Remove image from project page footers using default variant footer

---

apps/web/components/ChatPanel/WatsonChatPanel/WatsonChatPanel.tsx
apps/web/components/ChatPanel/WatsonChatPanel/utils.ts
apps/web/components/ChatPanel/types.ts
apps/web/components/Organization/Wrapper/config.ts
apps/web/components/ServiceWeb/config.ts
apps/web/screens/Article/components/ArticleChatPanel/config.ts
apps/web/screens/Project/components/ProjectChatPanel/config.ts

* Stop using 2 seperate instances for both locales for directorate of immigration chat (just use one)
* Stop displaying a pop up window for Samgöngustofa web chat where users have to type in their email and name

feat(web): Change config for directorate of immigration chat

---

apps/contentful-apps/pages/fields/organization-subpage-slug-field.tsx

* We don't want contentful users to be able to create organization subpages with other organization subpage slugs
* Organization subpage links are: `/s/${page.slug}/${subpage.slug}` so that's why we need an app since we want the slug to be unique given the parent page (we will allow /s/syslumenn/eitthvad and /s/vinnueftirlitid/eitthvad)
https://github.com/island-is/island.is/assets/43557895/789e47c3-2c4f-4283-8150-a35b8d407772

feat(contentful-apps): Organization subpage slug contentful app

---

libs/service-portal/core/src/components/TabNavigation/TabNavigation.tsx

Only show subnav items on tabnav when more than 1 is available.
No need for a single subnav button that does nothing.
This is how it is today:

fix(service-portal): Only show subnav items on tabnav when more than 1

---

.github/CODEOWNERS

Removing Júní and Aranja from codeowners for loftbrú
Júní is no longer maintaining Loftbrú, Hugsmiðjan is the sole maintainer.
Talking to Aranja devs, they see no reason to be codeowners.

chore(ads): Remove juni and aranja from codeowners on ads

---

libs/service-portal/finance/src/lib/messages.ts
libs/service-portal/finance/src/screens/FinanceLoans/FinanceLoans.tsx

* Remove duplicates
* Add specific no content string for loans
* NO DUPLICATES ALLOWED
* No content for loans is not the same as other finance pages.

fix(service-portal): Update finance messages

---

libs/service-portal/health/src/lib/navigation.ts
libs/service-portal/information/src/lib/navigation.ts

* Update health path parents so they represent the correct path
* Bonus: Also happening on my-information. 
It was set to a sibling of the other children
So this (see sidenav):
Becomes this:

fix(service-portal): Health path parents

---

libs/portals/admin/ids-admin/src/hooks/useLooseSearch.tsx
libs/portals/admin/ids-admin/src/screens/Permissions/Permissions.tsx

Fix the search logic for permissions.
There was an issue in the search logic where a permission with the permissionID `@island.is/healt/health-care` was not in the filteredList when searching for `health-care` but was in the list when `healthcare` was in the list
So permissions that include `-` can be filtered correctly

fix(auth-admin): Permissions search

---

apps/system-e2e/src/support/api-tools.ts
apps/system-e2e/src/tests/judicial-system/smoke/custody-court.ts
apps/system-e2e/src/tests/judicial-system/smoke/custody-tests.spec.ts

Waiting for update responses before continuing in our court e2e test
If there's a delay in response time then some steps prematurely fire and create a race condition, often breaking the test when run on dev

fix(j-s): E2E, Verify update requests completion before continuing

---

apps/contentful-apps/pages/fields/organization-subpage-slug-field.tsx

So that opening an entry doesn't accidentally change the slug

fix(contentful-apps): Skip generating organization subpage slug from title on initial render

---

libs/application/templates/parental-leave/src/fields/UnEmploymentBenefits/index.tsx
libs/application/templates/parental-leave/src/lib/messages.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

Add alert message for the time being because applicant can't register employee if he is receiving unemployment benefits.
Two different period length calculation that was causing validation error.

fix(parental-leave): alert message and period length fix

---

libs/application/templates/parental-leave/src/fields/UnEmploymentBenefits/index.tsx
libs/application/templates/parental-leave/src/lib/messages.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

Add alert message for the time being because applicant can't register employee if he is receiving unemployment benefits.
Two different period length calculation that was causing validation error.

fix(parental-leave): alert message and period length fix (#13136)

---

libs/service-portal/health/src/lib/messages.ts
libs/service-portal/health/src/screens/HealthCenter/HealthCenter.tsx

Update the health center front end:
* No table when empty
* Add fallback string to no center registration
Request from Sjúkra.

fix(service-portal): Health fallback string and table empty

---

apps/air-discount-scheme/backend/src/app/modules/discount/discount.service.ts
apps/air-discount-scheme/backend/src/app/modules/discount/dto/params.dto.ts
libs/api/domains/air-discount-scheme/src/lib/discount-admin/dto/createExplicitDiscountCode.input.ts
libs/portals/admin/air-discount-scheme/src/screens/CreateDiscount/CreateDiscount.tsx
libs/portals/admin/air-discount-scheme/src/screens/SuperDiscount/SuperDiscount.tsx

We dont want anymore to use two flightlegs.
Because using two codes is more expensive than using one code to order two flights with.

chore(ads): removing many flights option

---

apps/web/components/DefaultHeader/DefaultHeader.tsx
apps/web/components/Organization/Wrapper/Themes/HljodbokasafnIslandsTheme/HljodbokasafnIslandsHeader.tsx

feat(web): Add undertitle prop to Default Header component

---

apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacancyDetails.tsx

Change fallback image when svg image is used for social sharing viewed item in starfatorg
So the fallback image is starfatorg icon not island.is default image

fix(web): Change social sharing image fallback when svg image is used

---

apps/web/components/ServiceWeb/Background/Background.tsx
apps/web/components/ServiceWeb/Background/Variations/TransportAuthority/TransportAuthority.css.ts
apps/web/components/ServiceWeb/Background/Variations/TransportAuthority/TransportAuthority.tsx
apps/web/components/ServiceWeb/config.ts

feat(web): Add header for transport authority service web

---

apps/web/components/ServiceWeb/SearchInput/SearchInput.tsx

After a monorepo package upgrade the suggested search results stopped appearing. This is due to the code relying on a data property being up to date when it's not.
https://github.com/island-is/island.is/assets/43557895/a3008de8-be65-4afd-b28b-7b3c23a6daf4
https://github.com/island-is/island.is/assets/43557895/77cdbdfc-ff76-4a8a-bed3-0c451b5a17ad

fix(web): Service web suggested search not displaying results

---

libs/service-portal/assets/src/screens/VehicleMileage/VehicleMileage.tsx
libs/service-portal/assets/src/utils/readDate.ts

Update validation rule for mileage input
If we're in editing mode, we want to find the highest confirmed registered number, ignoring all Island.is registrations from today.
API was updated to add new transactions instead of updating the current one, so we need to make changes in the UI to reflect that.

fix(service-portal): Update validation rule for mileage input

---

libs/cms/src/lib/search/importers/adgerdirPage.ts
libs/cms/src/lib/search/importers/anchorPage.service.ts
libs/cms/src/lib/search/importers/article.service.ts
libs/cms/src/lib/search/importers/articleCategory.service.ts
libs/cms/src/lib/search/importers/enhancedAsset.service.ts
libs/cms/src/lib/search/importers/event.service.ts
libs/cms/src/lib/search/importers/frontpage.service.ts
libs/cms/src/lib/search/importers/groupedMenu.service.ts
libs/cms/src/lib/search/importers/link.service.ts
libs/cms/src/lib/search/importers/manual.service.ts
libs/cms/src/lib/search/importers/manualChapterItem.service.ts
libs/cms/src/lib/search/importers/menu.service.ts
libs/cms/src/lib/search/importers/news.service.ts
libs/cms/src/lib/search/importers/organizationPage.service.ts
libs/cms/src/lib/search/importers/organizationSubpage.service.ts
libs/cms/src/lib/search/importers/projectPage.service.ts
libs/cms/src/lib/search/importers/serviceWebPage.service.ts
libs/cms/src/lib/search/importers/subArticle.service.ts
libs/cms/src/lib/search/importers/supportQNA.service.ts

* We want to skip logging in case there are no entries being mapped to reduce the amount of logs
* Remove "Processing sync data for ..." logs since they are not present for all types and after the paginated sync update they don't provide as much value

chore(search-indexer): Skip logging if no entries are being mapped

---

libs/application/template-api-modules/src/lib/modules/templates/social-insurance-administration/social-insurance-administration-utils.ts
libs/application/template-api-modules/src/lib/modules/templates/social-insurance-administration/social-insurance-administration.service.ts
libs/application/templates/social-insurance-administration/pension-supplement/src/forms/PensionSupplementForm.ts
libs/application/templates/social-insurance-administration/pension-supplement/src/lib/answerValidationSections/fileUploadValidationSection.ts
libs/application/templates/social-insurance-administration/pension-supplement/src/lib/constants.ts
libs/application/templates/social-insurance-administration/pension-supplement/src/lib/dataSchema.ts
libs/application/templates/social-insurance-administration/pension-supplement/src/lib/pensionSupplementUtils.ts
libs/clients/social-insurance-administration/src/clientConfig.yaml

feat(pension-supplement): Send application

---

libs/service-portal/documents/src/components/DocumentRenderer/DocumentRenderer.tsx

Use overview url as fallback for detail-url
We have seen instances of documents not containing a url in detail, when there is in fact a url in overview.

fix(service-portal): Use overview url as fallback for detailurl

---

libs/cms/src/lib/search/importers/lifeEventPage.service.ts

This fixes the typename for life events
Mapping of Life Events has incorrect typename.

fix(web): life events indexer missing typename

---

.github/workflows/config-values.yaml

Sometimes checkout is not run and the step fails. This makes sure that it is always run and only one step can be true.

ci: make checkout on helm always happen

---

apps/services/auth/ids-api/infra/ids-api.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml

User profile client scope needs to be a valid json string
So the service can load the variable using json loader.
N/A

fix(auth-ids-api): String needs to be json string for user profile client scope.

---

libs/content-search-indexer/src/lib/cache-invalidation.service.ts
libs/content-search-indexer/src/lib/indexing.service.ts

* For a better debugging experience I've added logs and increased the wait time until we start cache invalidating
* This is a new feature that's currently being tested on dev and this PR would help regarding seeing the cache invalidation progress

chore(search-indexer): Log what endpoints are being cache invalidated

---

libs/content-search-indexer/src/lib/indexing.service.ts
libs/content-search-toolkit/src/services/elastic.service.ts

* We are trying to invalidate cached data when it gets re-indexed

fix(search-indexer): Set refresh to true when bulk indexing

---

libs/api/domains/content-search/src/lib/contentSearch.resolver.ts
libs/cms/src/lib/cms.resolver.ts

* Continuation of https://github.com/island-is/island.is/pull/13259
* 'icelandic-health-insurance' is now 'iceland-health' so this PR reverts the failsafe code added for the migration

chore(web): Revert iceland-health slug fail-safe

---

apps/web/screens/Organization/Home/LandingPage/LandingPage.tsx
apps/web/screens/Organization/Home/LandingPage/LandingPageFooter.tsx

* Often english fields in the cms are not populated so we want to prevent an empty footer from being shown
* I also fixed the spacing between the content and the footer

fix(web): Make sure only footer items with values are shown for organization landing page footer

---

apps/web/components/Organization/Slice/SliceMachine.tsx
apps/web/utils/richText.tsx

fix(web): Fix content width for SectionWithImage content type

---

libs/content-search-indexer/src/lib/cache-invalidation.service.ts

chore(search-indexer): Wrap cache invalidation log in an object

---

apps/judicial-system/web/src/routes/Shared/AppealToCourtOfAppeals/AppealToCourtOfAppeals.strings.ts
apps/judicial-system/web/src/routes/Shared/Statement/Statement.strings.ts

[Asana](https://app.asana.com/0/1199153462262248/1206408738524084/f)
There were three contentful strings with the same ID, which gives the following error when trying to publish them

fix(j-s): Fix duplicate CF string id

---

apps/services/user-notification/src/app/modules/notifications/messageProcessor.service.spec.ts
apps/services/user-notification/src/app/modules/notifications/messageProcessor.service.ts

User notification service uses in-memory cache to cache Contenful Hnipp templates. After PR #13013 the template object wasn't shallowed copied making the service write to the cached object values of a notification.
To fix the notification service.
N/A

fix(user-notification): Shallow copy template object to avoid cache tampering.

---

apps/services/search-indexer/infra/search-indexer-service.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

Since the previous change seemed to be blocking all external calls to the service

fix(search-indexer): Allow external calls to search-indexer

---

apps/services/search-indexer/infra/search-indexer-service.ts
apps/web/infra/web.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

search-indexer service needs to be able to call web so we can invalidate the redis cache for web graphql queries

feat(web): Allow search-indexer to call web

---

apps/web/components/Organization/Wrapper/Themes/SAkTheme/SAkHeader.css.ts

* I saw a warning in the terminal when running web locally

fix(web): Use flex-end instead of end for SAk header css

---

libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts

A whoopsie. Need to find by estateInfoSelection. Was just selecting the first one since the find was evaluating `Boolean(estate.caseNumber)`.

fix(application-estate): Comparison for finding correct estate on submit

---

apps/web/components/Charts/v2/hooks/data.ts
apps/web/components/Charts/v2/renderers/ChartComponentRenderer.tsx
apps/web/components/Charts/v2/renderers/ChartNumberBox/ChartNumberBox.css.ts
apps/web/components/Charts/v2/renderers/ChartNumberBox/ChartNumberBox.tsx
apps/web/components/Charts/v2/renderers/ChartRenderer.tsx
apps/web/components/Charts/v2/utils/format.ts
libs/clients/statistics/src/lib/statistics.utils.ts

Chart Number Box:
- Fixing floating point rendering issue (28.9999997% vs 29%)
- Reducing font size for main value on small devices
- Fixed error in YoY / MoM calculation
Pie chart:
- Increasing chart size
- Improving labels
General:
- Improving formatting for number and percentages displayed in charts
- Made it possible to use the `sourceData` field to use custom data (JSON blob) rather than the statistic data source
- Connected the interval field to result filtering so it is now possible to skip every n-th entry in the results
- _For example if you want to get 36 months of data but only show every 12th month to show difference between years_
Left for later:
- Refactor the `interval` property that is now located on `Chart Component` contentful model up and into the `Chart` model to …

feat(web): Chart improvements and fixes

---

apps/web/pages/_error.tsx

* https://island.is/grindavik redirects to https://island.is/v/fyrir-grindavik
* https://island.is/grindavik?fbclid=123 doesn't get redirected and displays a 404 page
https://islandis.slack.com/archives/C01C7C3M2J3/p1706530493554269

fix(web): Ignore query params when redirecting

---

apps/consultation-portal/pages/mal/[slug].tsx

https://veflausnir.atlassian.net/browse/KAM-2095
https://github.com/island-is/island.is/pull/13631
Sometimes when serversideprops is fetching data, the ctx.query.slug is null, so we will try to await the ctx.query.slug
We will also console.error the id just in case

fix(consultation-portal): KAM-2095: await ctx (#13631)

---

apps/air-discount-scheme/backend/docker-compose.yml
apps/application-system/api/docker-compose.yml
apps/financial-aid/backend/docker-compose.yml
apps/icelandic-names-registry/backend/docker-compose.yml
apps/reference-backend/docker-compose.yml
apps/services/auth/ids-api/docker-compose.yml
apps/services/documents/docker-compose.yml
apps/services/endorsements/api/docker-compose.yml
apps/services/regulations-admin-backend/docker-compose.yml
apps/services/sessions/docker-compose.yml
apps/services/university-gateway/docker-compose.yml
apps/services/user-notification/docker-compose.yml
apps/services/user-profile/docker-compose.yml
apps/skilavottord/ws/docker-compose.yml
libs/testing/containers/src/lib/testing-containers.ts

Upgrade version of PostgreSQL used ƒor local development and CI.
This is the first step in our [upgrade plan](https://www.notion.so/Upgrade-Postgres-to-15-3-c5913fb32aa44e119608ce09c5b3b842?pvs=4).
Because we're 3 majors out of date and version 11 is not supported anymore (since Nov 9, 2023).
See the [upgrade plan](https://www.notion.so/Upgrade-Postgres-to-15-3-c5913fb32aa44e119608ce09c5b3b842?pvs=4) for next steps.

chore(core): Upgrade PostgreSQL from 11.14 to 15.3

---

.github/CODEOWNERS

Removing the Core team as Codeowner of `**/infra` changes
Those always require devops review due to changed charts so unnecessary to require Core as well.

chore(Codeowners): Remove Core as Codeowner of **/infra changes

---

apps/api/infra/api.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
libs/clients/statistics/src/lib/fetchConfig.ts

Make stale-while-revalidate valid for 2 weeks so if the site receives a visit once every 2 weeks we should have data in cache.
Remove enhanced fetch debug log env variable.
To configure caching for prod.
Debugging is done so turnoff to remove log noice.

fix(clients-statistics): Update stale-while-revalidate lifetime to 14 days so we can use cache.

---

apps/web/components/connected/HousingBenefitCalculator/SpecificHousingBenefitSupportCalculator.tsx

https://github.com/island-is/island.is/pull/13674

feat(web): Hotfix - Specific housing benefit calculator - display "5" and "6 or more" options for household member radio buttons

---

.yarn/patches/@nestjs-terminus-npm-10.2.0-9e24c129e0.patch
package.json
yarn.lock

* Update @nestjs/sequelize package to mach NestJS major version.
* Yarn patch @nestjs/terminus package to remove `checkDependantPackages` check which is failing for `SequelizeHealthIndicator` due to the nestjs/sequelize and sequelize packages being bundled in main.js.
To fix bundled production builds.
N/A

fix(core): Update @nestjs/sequelize to v10 to match our major NestJS version. Patch nestjs/terminus.

---

.yarn/patches/@nestjs-terminus-npm-10.2.0-9e24c129e0.patch
apps/services/auth/admin-api/infra/auth-admin-api.ts
apps/services/auth/delegation-api/infra/delegation-api.ts
apps/services/auth/ids-api/infra/ids-api.ts
apps/services/auth/personal-representative-public/infra/personal-representative-public.ts
apps/services/auth/personal-representative/infra/personal-representative.ts
apps/services/auth/public-api/infra/auth-public-api.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml
yarn.lock

* Remove `checkDependentPackages` also called during runtime in `pingCheck` and crashed the apis due to it not finding packages and aggressively calling process.exit(1).
* Add `/health/check` route as the readiness probe for all the Auth APIs.
To test if propper readiness indicator indicating that the services can query the db helps stabalizing APIs during auto scaling.
N/A

chore(auth-apis): Auth APIs readiness health check

---

apps/judicial-system/web/src/routes/Court/components/ReceptionAndAssignment/ReceptionAndAssignment.tsx

[Asana](https://app.asana.com/0/1199153462262248/1206362125834834/f)
Remove defendant plea alert box from all case types but indictments
This only applies to indictments

fix(j-s): Remove defendant plea alert box from all case types but indictments

---

apps/web/screens/Organization/Syslumenn/Auctions.tsx

* Tiny visual fix that was overlooked when the bottom text was added to the card

fix(web): Auction card see more link visual fix

---

libs/island-ui/contentful/src/lib/RichTextRC/defaultRenderNode.tsx

* Otherwise the link ends up being /[slug]/something/something-else

fix(web): Make sure that subarticle entry hyperlink href starts with a slash

---

libs/service-portal/core/src/components/InstitutionPanel/InstitutionPanel.tsx
libs/service-portal/education-student-assessment/src/screens/EducationStudentAssessment/components/StudentAssessmentTable/StudentAssessmentTable.tsx

* Add education detail tooltip
* Update introheader logo display
Tiny little bugfix 🐛 
Goes from 😿 
To ✨

fix(service-portal): Education. Update icon. Add tooltip

---

charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
charts/judicial-system/values.dev.yaml
charts/judicial-system/values.prod.yaml
charts/judicial-system/values.staging.yaml
infra/src/dsl/output-generators/map-to-helm-values.ts
infra/src/dsl/pdb.spec.ts

MaxUnavailable: 0 cause clusters to become too rigid during node autoscaling not allowing any pod evictions, changing it to 1 will allow autoscaling

chore(infra): Tune down PDB strictness

---

apps/web/screens/Organization/Syslumenn/Auctions.tsx

* The auctions page must not be cached in any way

chore(web): Add no-cache as fetchPolicy when fetching auctions

---

apps/web/screens/queries/fragments.ts
libs/cms/src/lib/generated/contentfulTypes.d.ts
libs/cms/src/lib/models/chart.model.ts

To allow content editors to flip the x and y-axis when displaying charts
- This PR is only adding it to the search indexer mapping and page querying the actual implementation will be in another PR
To match what is in the design system

feat(web): Add optional flipAxis field to Chart content model

---

libs/portals/shared-modules/delegations/src/components/delegations/DelegationsEmptyState.tsx
libs/portals/shared-modules/delegations/src/components/delegations/incoming/DelegationsIncoming.tsx
libs/portals/shared-modules/delegations/src/components/delegations/outgoing/DelegationsOutgoing.tsx
libs/portals/shared-modules/delegations/src/lib/messages.ts

Fix wrong empty state message for incoming delegations.
To show clearer message to user.

fix(service-portal): empty state message for incoming deligations

---

apps/web/screens/Organization/Syslumenn/Auctions.tsx

chore(web): Hotfix - Add no-cache as fetchPolicy when fetching auctions (#13777)

---

libs/cms/src/lib/models/organizationPage.model.ts

* It's always bothered me that we have an organizationPage.slug and an organization.slug that often are the same but when they are not weird things might happen
* This PR suggests that we fallback to using the organization.slug
* So that newer organization pages don't need to define a slug and will derive it from the organization content type

feat(search-indexer): Fallback to using organization.slug for organizationPage.slug

---

apps/services/sessions/migrations/20240216101538-change-user-agent-column-datatype.js
apps/services/sessions/src/app/sessions/constants.ts
apps/services/sessions/src/app/sessions/session.model.ts
apps/services/sessions/src/app/sessions/sessions.service.spec.ts
apps/services/sessions/src/app/sessions/sessions.service.ts

DataDog is reporting errors about a field being to long for database column.
So we migrate the user agent column to be TEXT so it allows Postgres unlimited varchar column.
We then take the first 1024 chars from the user agent string.
To fix error and lost session tracking due to these failures.
N/A

fix(services-sessions): Fix sessions column too large value

---

.eslintrc.json

Add eslint warning to encourage a shared function syntax.
https://www.notion.so/Code-standard-Function-syntax-86d5c6d562dd4ca88ea3a2ea7eecd80b?pvs=4 
func-style: 720 warnings
prefer-arrow-callback: 39 warnings

chore(core): Add lint warnings for preferred function style

---

apps/system-e2e/src/tests/judicial-system/smoke/custody-tests.spec.ts
apps/system-e2e/src/tests/judicial-system/utils/helpers.ts

[Laga E2E test](Laga E2E test)
- Waits for case acceptance in judge flow to make sure the request leaves the server before the test quits.
- Waits for file selection in file picker.
- Sometimes the test quits before the request to accept the case leaves the server.
- We tried removing the file picker dealy, but that caused file picking to fail in some cases. Further investigation needed.
The following screen shot indicates that the "prosecutor should appeal case" test failed but the real failure is in "court should submit decision in case":

fix(j-s): Wait for Accept Test

---

charts/identity-server/values.dev.yaml
charts/islandis/values.dev.yaml
charts/judicial-system/values.dev.yaml
infra/src/environments.ts

DSL had hardcoded RDS read replicas url for dev, should point to a dns record so it can be updated internally.

fix: set internal dns record for postgres read replicas

---

libs/auth-api-lib/src/lib/delegations/delegations-outgoing.service.ts
libs/auth-api-lib/src/lib/resources/delegation-resources.service.ts

Hotfix of #13821
These queries are super slow in production because they have a LEFT OUTER JOIN against all delegations in the system containing the respective api scopes.
The original goal is to filter api scopes based on custom delegations which the authenticated user has against the current subject. So this PR changes removes the offending joins and instead conditionally queries the list of custom delegation scopes before the main query, which can then match against them with a simple IN filter.

fix(auth): Speed up delegation queries HOTFIX

---

apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculator.tsx

* When the locale is set to something other than english we want to make sure the first letter of a month is lowercase when used in a sentence (janúar instead of Janúar)

chore(web): Pension Calculator - Lowercase first letter for month when used in sentence

---

.github/CODEOWNERS

@island-is/core needlessly has ownership of `.githooks/`, because of defaulting.
Here, I'm taking ownership for @island-is/devops to increase speeeeeed and lessen the burden on @island-is/core

chore(CODEOWNERS): Take ownership of `.githooks/`

---

apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculatorResults.css.ts
apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculatorResults.tsx
apps/web/screens/Organization/SocialInsuranceAdministration/translationStrings.ts
apps/web/screens/queries/PensionCalculator.ts
libs/api/domains/social-insurance/src/lib/models/pensionCalculation.model.ts
libs/api/domains/social-insurance/src/lib/socialInsurance.service.ts
libs/api/domains/social-insurance/src/lib/utils.ts

The social insurance administration backend is now returning id's instead of Icelandic text
This PR
* Uses those id's to fetch translation strings
* Now also displays the total payment after tax at the top of the results page
* Minor visual changes regarding heading levels and button placements

feat(web): Pension Calculator - Fix translation strings and change UI according to new design

---

apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculator.tsx
apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculatorResults.css.ts
apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculatorResults.tsx
apps/web/screens/Organization/SocialInsuranceAdministration/translationStrings.ts

* Change default values for pension calculation form
* Skip sending fields to backend that aren't used in calculation depending on what pension type was selected
* Fix visuals

feat(web): Pension Calculator - Change default values and tweak visuals

---

libs/auth-api-lib/src/lib/delegations/delegations-index.service.ts

Indexing all delegations doesn't happen right after db write, so there is no need to use master database when indexing.

fix(delegation-index): stop using master db when indexing all delegations

---

libs/clients/syslumenn/src/lib/syslumennClient.utils.spec.ts
libs/clients/syslumenn/src/lib/syslumennClient.utils.ts

Invalid data was reaching the pre-filled state of the application due to `50,02` being cast into string in the DC's respsonse instead of passing `50.02` as float.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1206670473640411

fix(application-estate): Share-parsing function for icelandic commas

---

libs/api/domains/university-gateway/src/lib/graphql/main.resolver.ts
libs/api/domains/university-gateway/src/lib/graphql/models/program.model.ts
libs/api/domains/university-gateway/src/lib/graphql/models/programFilter.model.ts
libs/api/domains/university-gateway/src/lib/graphql/university.resolver.ts
libs/nest/pagination/src/lib/graphql/paginated.response.ts

* Add caching support to the university gateway graphql endpoints
* Add caching support to the PaginatedResponse model
* island.is/haskolanam/leit is really slow since the graphql calls aren't cached

chore(university-gateway): Cache graphql calls

---

libs/application/template-api-modules/src/lib/modules/templates/grindavik-housing-buyout/grindavik-housing-buyout.service.ts
libs/application/templates/grindavik-housing-buyout/src/forms/GrindavikHousingBuyoutForm.ts
libs/application/templates/grindavik-housing-buyout/src/lib/dataSchema.ts
libs/application/templates/grindavik-housing-buyout/src/lib/messages/application.ts
libs/application/templates/grindavik-housing-buyout/src/lib/messages/errors.ts
libs/application/templates/grindavik-housing-buyout/src/utils/loan.ts

- Remove checkbox on user statement screen
- Add a checkbox on loan providers screen that confirms if user has no loans on the property

fix(ghb): Remove statement checkbox and add loan providers check

---

apps/services/user-notification/src/app/modules/notifications/notificationsWorker.service.ts

The template was being rewritten according to arguments and therefore the in-memory representation of the object would have its template string overwritten. This would/could result in the template being written to cache with argument replacements already in place.

fix(user-notifications): In memory cache fix

---

libs/auth-api-lib/migrations/20240227133212-migrate-application-admin-scope.js

Add `;` in the lates migration script in auth api lib.  
It is causing syntax error and failure in initContainer migrations. 

fix(auth-api-lib): Fix syntax error

---

apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculator.tsx

* Users can no longer enter that they want to use more than 100% tax card ratio
* Users can no longer enter that they lived abroad for more than 52 years between the age of 16-67
* This was requested by the social insurance administration
https://github.com/island-is/island.is/assets/43557895/4c44c7f2-c473-43e5-9d8f-c7e12d61b005

feat(web): Pension Calculator - client side input validation

---

libs/react-spa/shared/src/components/problems/Problem.tsx

* Updated `<Problem>` size defaults
The alert for third party service errors should be small by default

feat(react-spa-shared): make third party default small

---

libs/cms/src/lib/models/linkGroup.model.ts
libs/cms/src/lib/models/projectPage.model.ts

* Fail safe added in case fields are missing
* Because this was causing a 500 error on english versions of project pages that had missing link group references in the cms

fix(web): Add failsafe for when mapping project pages

---

libs/application/ui-shell/src/components/Screen.tsx

Move scroll-to-top logic to a separate `useEffect`
When submitting a screen and getting an error, specifically the data-providers screen, you could reduce the screen down to mobile size and submit again, and it would let you through even though there were errors from data-provdider

fix(application-system): Fix submit callback bug

---

apps/services/user-profile/migrations/20240313114633-next-nudge.js
apps/services/user-profile/src/app/types/nudge-type.ts
apps/services/user-profile/src/app/user-profile/userProfile.model.ts
apps/services/user-profile/src/app/v2/dto/post-nudge.dto.ts
apps/services/user-profile/src/app/v2/me-user-profile.controller.ts
apps/services/user-profile/src/app/v2/test/me-user-profile.controller.spec.ts
apps/services/user-profile/src/app/v2/user-profile.service.ts
apps/services/user-profile/test/fixture-factory.ts

* nudge update with nextNudge
* next nudge tests and needsNudge changes
* wip interval to update and nudge
* refactor for nudge
* Move nudge skipField param to be a post body payload and rename to nudgeFrom.
* Remove import that was refactored.
* Fix tests
* minor bug fux for confirmNudge
* Rename NudgeFrom enum to NudgeType
* Add happy path test for status updates on nudge
* Add tests to verify that emailStatus and mobileStatus are not changed to empty in other states.
* Use ApiPropertyOptional for optional properties on user profile model. Rename variable in userprofile service v2 for readability. Use SKIP_INTERVAL and NUDGE_INTERVAL in user profile spec file.
* Undo api property decorator fixes due to too big impact.
---------
Attach a link …

feat(user-profile): Next-nudge interval (#14136)

---

infra/src/cli/render-secrets.ts
infra/src/common.ts
scripts/get-secrets.sh

`yarn get-secrets my-project` was broken. Here we fix it.
The logger updates made all `console.log` use `logger.debug`. Now the logger uses `console.error` for all logs to send them all stderr, and the secrets rendering uses `console.log` (stdout) so we can redirect to the secrets file.

fix(scripts): Get secrets only "working" when debugging

---

infra/scripts/container-scripts/create-db.sh

* fix: create-db.sh feature deploy script now supports readonly users
* fix: shellcheck
* chore: fix shellcheck errors
---------

fix: create-db.sh feature deploy script now supports readonly users (#14195)

---

apps/web/components/Organization/Slice/BulletList/BulletList.tsx

* After the spacing update we did a few weeks ago there's no need for components to have their own margin or padding around themselves

fix(web): Remove paddingBottom from BulletList component

---

apps/contentful-apps/pages/fields/link-group-link-field.tsx

A link group is most often used to create a sidebar menu for organization pages or project pages. The newly created contentful app logic relies on the fact that a link group is referenced by either of those content types. However if a link group gets created and isn't being referenced it'll be stuck in a "loading state". In this PR we are fixing that issue.
https://github.com/island-is/island.is/assets/43557895/692e3955-0988-4d91-856e-c7663bfc259b
https://github.com/island-is/island.is/assets/43557895/e5c6341d-2d8e-4699-a34e-16c66306c717

fix(contentful-apps): Handle case when link group is created separately

---

apps/web/components/Footer/Footer.tsx

* Changed initial page render to be a non mobile screen width for the footer
https://github.com/island-is/island.is/assets/43557895/dc7082b6-4935-4b6e-91b9-7690eee5ddbd
https://github.com/island-is/island.is/assets/43557895/c1881d01-f316-4594-a284-bb7fd379cdcf

fix(web): Default footer causes layout shift on desktop screens

---

apps/api/infra/api.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

Reverting redis hostnames that was done in https://github.com/island-is/island.is/commit/281152231de0b8e60f146de771a6fd7397128705#diff-9ddea0806b954676f87cdf26cdb742bd08615a75225b8bca20d256ccd826abf5L226
GQL api seems to be unable to use the new hostname.

fix(clients-rsk-relationships): Revert redis cluster hostname for rsk procuring client

---

apps/native/app/src/ui/lib/scan-result-card/scan-result-card.tsx

Update scanner app to show correct background, title and logo for scanning Veiðikort
Not launch blocking, scanning works without it but only shows the result (Í gildi/ekki í gildi) on a pink background with no title.
Before and after:
<div><img height = "800" src="https://github.com/island-is/island.is/assets/19665778/31fe6731-29fe-4a45-b17f-dc208b905f77">

feat(native-app): add scan result background in scanner for Veiðikort

---

apps/web/components/DefaultHeader/DefaultHeader.tsx
apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/Themes/HljodbokasafnIslandsTheme/HljodbokasafnIslandsHeader.tsx
apps/web/components/Organization/Wrapper/Themes/VinnueftirlitidTheme/VinnueftirlitidHeader.tsx
apps/web/screens/Project/components/ProjectHeader/ProjectHeader.tsx
libs/cms/src/lib/models/organizationTheme.model.ts

feat(web): Default header - text offset and have the option to set different background on mobile screens

---

libs/application/templates/passport/src/fields/PassportSelection/index.tsx
libs/application/templates/passport/src/forms/overviewSection/personalOverview.ts

A domicile check was hanging around in the frontend (after DataProviders).
Also fixed a small bug where a message was being rendered as [object Object].

fix(application-passport): Domicile requirements change followup

---

libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

Hotfix #14304
Older applications created in 2022 don't have the commonFiles or fileUpload.file array when no attachment.

fix(parental-leave): Fix getAttachments for old applications

---

libs/cms/src/lib/environments/environment.ts

* When syncing updates from the cms to elasticsearch we need to know if each content type is nested or not to decide if we need to go up a level to find what to re-index

chore(cms): Mark big bullet list and related content types as nested

---

apps/contentful-apps/pages/fields/link-group-link-field.tsx

* The link group contentful app only allows users to create links but not add existing ones
* We want to be able to reuse links between locales in the cms

chore(contentful-apps): Link group - Allow using pre existing links

---

apps/web/pages/_error.tsx
apps/web/utils/fetch404RedirectUrl.ts
apps/web/utils/getServerSidePropsWrapper.ts

fix(web): Hotfix - Fix redirect functionality by also redirecting if there is not a CustomNextError thrown (#14377)

---

libs/content-search-toolkit/src/queries/search.ts

feat(web): Hotfix - Finetune search results when typing "Tryggingastofnun" keywords (#14400)

---

apps/services/user-profile/infra/service-portal-api.ts
apps/services/user-profile/src/app/worker/worker.service.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

Fixing 'Invalid date' error when processing user profiles with nextNudge = `null` since `addMonths(nudgeLastAsked, 6)` results in `Invalid date` which cannot be set to `nextNudge` so it fails on the upsert.
To finish running the user-profile-worker without errors

fix(user-profile-worker): Set nextNudge to null when nudgeLastAsked has no value and remove islykill cert as dependency

---

libs/auth-nest-tools/src/lib/jwt.strategy.ts

Add #14603 
Test to see if server timeskew can be causing 401 between IDS and service portal api (user profile api)
N/A

fix(auth-nest-tools): Fix add nestjs jwt clocktolorance

---

apps/web/components/Organization/Wrapper/Themes/FiskistofaTheme/index.ts

* When client side routing, the footer styles get messed up (also see PR: https://github.com/island-is/island.is/pull/14634)
* Disabling SSR when dynamically importing fixes the isssue

fix(web): Disable SSR for Directorate of Fisheries footer

---

libs/api/domains/social-insurance/src/lib/utils.ts

fix(web): Hotfix - Pension calculator, add one to month offset so it matches the frontend #14771

---

apps/web/public/.well-known/assetlinks.json

See title
Apparently this might be needed to share sign-in credentials between the website and app. The goal is to register and use island.is passkeys in the app. Android needs to validate that the domain allows this.

chore(web): Add handle_all_urls to assetlinks [HOTFIX]

---

libs/cache/src/lib/cache.ts

fix: increase timeout

---

apps/web/components/connected/HousingBenefitCalculator/HousingBenefitCalculator.tsx

fix(web): Hotfix - Housing benefit calculator - Display "4 or more" instead of "4" if only 4 options are displayed #15043

---

apps/application-system/form/src/routes/AssignApplication.tsx
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts

add abort option when prev state is `employerWaitingToAssignForEdits` and change to useEffectOnce when assigning application to the employer. Locally it called it twice so the state history was wrong.

fix(parental-leave): useEffectOnce when assigning application to employer and add another abort option to a state

---

libs/application/ui-shell/src/components/FormExternalDataProvider.tsx

Hotfix for bug that allows users to bypass the data-provider checks if the application has a screen before data-provider
Steps to reproduce:
Open up an application that has a screen before the dataprovider step
Click the checkbox to approve data collection
A dataprovider fails
Use the backbutton of your mouse or the browser to statelessly go back one screen
Then you can "Halda áfram" twice to bypass the dataproviders.

fix(application-system): Data provider bug hotfix

---

libs/application/ui-shell/src/components/FormStepper.tsx

Don't render out formStepper states if the title is empty
Have the same behaviour as the discontinued core formStepper
Previously:
Now:

fix(application-system): formstepper empty state

---

apps/web/components/DefaultHeader/DefaultHeader.tsx
apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx

(The title color used to "dark400")

feat(web): Social Insurance Administration - header title color change

---

libs/clients/social-insurance-administration/src/lib/apiProvider.ts
libs/clients/social-insurance-administration/src/lib/configFactory.ts

fix(web): Hotfix - Remove autoAuth for PensionCalculatorApi due to 500 error when calculating pension #15211

---

apps/service-portal/src/components/Notifications/NotificationButton.tsx
apps/service-portal/src/components/Notifications/NotificationLine.tsx
apps/service-portal/src/components/Notifications/Notifications.css.ts
libs/api/domains/documents/src/lib/documentV2.service.ts
libs/api/domains/notifications/src/lib/notifications.resolver.ts
libs/api/domains/notifications/src/lib/notificationsList.resolver.ts
libs/api/domains/notifications/src/utils/helpers.ts
libs/service-portal/core/src/components/ActionCard/ActionCard.css.ts
libs/service-portal/documents/src/components/DocumentLine/AvatarImage.tsx
libs/service-portal/information/src/screens/Notifications/Notifications.graphql
libs/service-portal/information/src/screens/Notifications/Notifications.tsx

hotfix: #15194 & #15239 & #15219

fix(service-portal): Documents dl url & notifications api - hotfix

---

libs/application/templates/new-primary-school/src/fields/FriggOptionsAsyncSelectField/index.tsx
libs/application/templates/new-primary-school/src/fields/Review/review-groups/AllergiesAndIntolerances.tsx
libs/application/templates/new-primary-school/src/fields/index.ts
libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/differentNeedsSection/allergiesAndIntolerancesSubSection.ts
libs/application/templates/new-primary-school/src/hooks/useFriggOptions.ts
libs/application/templates/new-primary-school/src/lib/constants.ts
libs/application/templates/new-primary-school/src/lib/dataSchema.ts
libs/application/templates/new-primary-school/src/lib/messages.ts
libs/application/templates/new-primary-school/src/lib/newPrimarySchoolUtils.ts
libs/application/templates/new-primary-school/src/types.ts

[[TS-806] Implement Allergies and intolerances page](https://dit-iceland.atlassian.net/jira/software/c/projects/TS/boards/82?issueParent=59643&selectedIssue=TS-806)

feat(new-primary-school): Allergies and intolerances - Data implementation

---

apps/api/dist/.nx-results
apps/application-system/form/dist/.nx-results
apps/financial-aid/web-osk/dist/.nx-results
apps/financial-aid/web-veita/dist/.nx-results
apps/judicial-system/web/dist/.nx-results

I found while working on `clean.mjs` (see https://github.com/island-is/island.is/pull/15337) that we have some `.nx-results` files in `dist/` folders. This suggests they are generated and not needed in our git repo.

chore: Remove generated `dist/` files

---

libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
libs/api/domains/driving-license/src/lib/drivingLicense.type.ts
libs/application/core/src/lib/messages.ts
libs/application/template-api-modules/src/lib/modules/templates/driving-license-duplicate/driving-license-duplicate.service.ts
libs/application/templates/driving-license-duplicate/src/dataProviders/index.ts
libs/application/templates/driving-license-duplicate/src/forms/applicationSections/sectionDataProviders.ts
libs/application/templates/driving-license-duplicate/src/lib/drivingLicenseDuplicateTemplate.ts
libs/clients/driving-license/src/lib/drivingLicenseApi.types.ts
libs/clients/driving-license/src/v4/clientConfig.json
libs/clients/driving-license/src/v5/clientConfig.json

fix(application-dld): Entry requirements in DP

---

apps/web/screens/Search/Search.tsx

* Digital Iceland community pages were linking to a 404 page due to the search link resolution code not handling all anchor page types

fix(web): Broken anchor page links in search

---

apps/contentful-apps/components/translation-namespace/utils/deserialize.ts

Cherrypicked from PR: https://github.com/island-is/island.is/pull/15618

fix(contentful-apps): Hotfix - Translation namespace app - trim whitespace when considering if a node is empty

---

libs/auth-api-lib/src/lib/clients/admin/admin-clients.service.ts
libs/auth-api-lib/src/lib/resources/admin/admin-scope.service.ts
libs/portals/admin/ids-admin/src/screens/Client/components/Delegation.tsx
libs/portals/admin/ids-admin/src/screens/Permission/components/PermissionDelegations.tsx

Only allow Super admins to make changes to PersonalRepresentative changes in the new IDS

hotfix(auth-admin): SuperAdmin block PersonalRepresentative changes in IDS

---

libs/application/templates/social-insurance-administration/income-plan/src/forms/IncomePlanForm.ts
libs/application/types/src/lib/Fields.ts
libs/application/ui-fields/src/lib/TableRepeaterFormField/TableRepeaterFormField.tsx

[[TS-839] Calculate income per year](https://dit-iceland.atlassian.net/jira/software/c/projects/TS/boards/82?issueParent=60310&selectedIssue=TS-839)

feat(income-plan): Calculate income per year

---

.github/CODEOWNERS
apps/web/public/.well-known/apple-app-site-association

This allows us to deep link specific URLs with the island.is app.

feat: Configure universal links for the test app HOTFIX

---

apps/services/auth/admin-api/src/app/v2/clients/me-clients.controller.ts
apps/services/auth/admin-api/src/openApi.ts
libs/api/domains/auth/src/lib/models/delegation.model.ts
libs/auth-api-lib/src/lib/delegations/admin/delegation-admin-custom.service.ts
libs/auth-api-lib/src/lib/delegations/constants/zendesk.ts
libs/clients/zendesk/src/lib/zendesk.service.ts
libs/portals/admin/delegation-admin/src/components/DelegationList.tsx
libs/portals/admin/delegation-admin/src/screens/DelegationAdminDetails/DelegationAdmin.graphql
libs/portals/shared-modules/delegations/src/components/access/AccessCard.tsx
libs/portals/shared-modules/delegations/src/components/delegations/incoming/DelegationsIncoming.tsx
libs/portals/shared-modules/delegations/src/components/delegations/outgoing/DelegationsOutgoing.tsx

Add delete button to Delegation Access card, call delete mutation
Allow users to delete paper delegations

feat(auth-admin): Delete delegation UI

---

libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
libs/api/domains/driving-license/src/lib/drivingLicense.type.ts
libs/application/templates/driving-license/src/fields/EligibilitySummary/extractReasons.ts
libs/application/templates/driving-license/src/fields/EligibilitySummary/useEligibility.ts
libs/application/templates/driving-license/src/forms/prerequisites/sectionApplicationFor.ts
libs/application/templates/driving-license/src/lib/constants.ts
libs/application/templates/driving-license/src/lib/messages.ts
libs/application/templates/driving-license/src/lib/types.ts
libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
libs/clients/driving-license/src/v5/clientConfig.json

* check if 65 renewal is possible
* remove console log
* cleanup
* coderabbit tweaks
* coderabbit changes
* quick fix
* add type?
---------

feat(driving-license): check if 65+ renewal is possible (#16292)

---

apps/contentful-apps/pages/fields/project-subpage-slug-field.tsx

feat(contentful-apps): Hotfix - Allow two project subpages to have same slug (#16412)

---

apps/services/auth/admin-api/src/app/v2/delegations/delegation-admin.controller.ts
apps/services/auth/admin-api/src/app/v2/delegations/test/delegation-admin.auth.spec.ts
apps/services/auth/delegation-api/src/app/delegations/delegation-index.controller.ts
libs/auth-api-lib/src/lib/delegations/admin/delegation-admin-custom.service.ts
libs/auth-api-lib/src/lib/delegations/delegations-index.service.ts
libs/portals/shared-modules/delegations/src/components/delegations/DelegationViewModal.tsx
libs/portals/shared-modules/delegations/src/components/delegations/outgoing/DelegationsOutgoing.tsx

fix(auth-admin): Hotfix: Auditlog for webhook and minor UI fixes

---

apps/service-portal/src/lib/masterNavigation.ts
libs/api/domains/signature-collection/src/lib/signatureCollection.resolver.ts
libs/api/domains/signature-collection/src/lib/signatureCollection.service.ts
libs/api/domains/signature-collection/src/lib/signatureCollectionAdmin.resolver.ts
libs/api/domains/signature-collection/src/lib/signatureCollectionAdmin.service.ts
libs/application/templates/signature-collection/parliamentary-list-creation/src/fields/CopyLink/index.tsx
libs/application/templates/signature-collection/parliamentary-list-creation/src/forms/Draft.ts
libs/clients/signature-collection/src/lib/signature-collection-shared.service.ts
libs/clients/signature-collection/src/lib/signature-collection.service.ts
libs/portals/admin/signature-collection/src/lib/messages.ts
libs/portals/admin/signature-collection/src/screens-parliamentary/DownloadReports/MyPdfDocument/index.tsx
libs/portals/admin/signature-collection/src/screens-parliamentary/List/paperSignees/identityAndCanSignLookup.graphql
libs/portals/admin/signature-collection/src/screens-parliamentary/List/paperSignees/index.tsx
libs/portals/admin/signature-collection/src/shared-components/completeReview/lockList/index.tsx
libs/service-portal/core/src/lib/messages.ts
libs/service-portal/information/src/lib/navigation.ts
libs/service-portal/signature-collection/src/index.ts
libs/service-portal/signature-collection/src/lib/messages.ts
libs/service-portal/signature-collection/src/lib/navigation.ts
libs/service-portal/signature-collection/src/lib/paths.ts
libs/service-portal/signature-collection/src/module.tsx
libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/ViewList/Signees/PaperSignees.tsx
libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/ViewList/index.tsx
libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/index.tsx
libs/service-portal/signature-collection/src/screens/Parliamentary/index.tsx
libs/service-portal/signature-collection/src/screens/shared/SigneeView/index.tsx

The parliamentary elections are on route for tomorrow at 13:00.
A cavalcade of commits follows:
* 166f7d69076df5bea8e22109147a308f17e4bf4a (company route signature collections)
* 3e13affcb623a99fa420c268b2b8d46154efd20b (sp list submitted)
* df6c638eccef02e78e6475ee184031358d262ad3 (adding report date)
* 1d5a051b5af5ff14c60196eee4acf8638283a3a7 (tweaks 15.10)
* 330e4c1c39e09a3b2c0747aed21a32bf8a5be0a4 (ongoing fixes) 
* c21a58fae5d9f3d22b7de337a47afbd5ffd5cc20 (tweaks for parliamentary collection)
* 420313dd427e7ad50f2ab8c3c7e03eff86f7d4df (fix paper signatures for candidacy)

fix(signature-collection): A litany of fixes

---

libs/application/template-api-modules/src/lib/modules/templates/signature-collection/parliamentary-list-creation/parliamentary-list-creation.service.ts
libs/application/templates/signature-collection/parliamentary-list-creation/src/dataProviders/index.ts
libs/application/templates/signature-collection/parliamentary-list-creation/src/forms/Draft.ts
libs/application/templates/signature-collection/parliamentary-list-creation/src/forms/Prerequisites.ts
libs/application/templates/signature-collection/parliamentary-list-creation/src/lib/errors.ts
libs/application/templates/signature-collection/parliamentary-list-creation/src/lib/messages.ts
libs/application/templates/signature-collection/parliamentary-list-signing/src/lib/errors.ts
libs/application/types/src/lib/Fields.ts
libs/clients/signature-collection/src/lib/signature-collection.service.ts
libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/index.tsx
libs/service-portal/signature-collection/src/screens/shared/SignedList/index.tsx
libs/service-portal/signature-collection/src/screens/shared/SigneeView/index.tsx
libs/service-portal/signature-collection/src/skeletons.tsx

Albinagu:
7b3c0cd9e0619a9a450f24f75e5d56f232a29e0e (fixes 16.10)
d356a2fc1b2baa9f2fd47bbbe3b821184840a0a1 (sc fixes 16.10)
AlexDiljar:
4a5ebba34e11b54355282b33450d169686dc8bfc (remove candidate ef all lists removed)
525e166654034a22df1aace47440e26521ee5212 (allow manager on paper upload)

fix(application-plc): Various fixes 16.10

---

libs/api/domains/signature-collection/src/lib/signatureCollection.service.ts
libs/application/core/src/lib/fieldBuilders.ts
libs/application/template-api-modules/src/lib/modules/templates/signature-collection/parliamentary-list-creation/parliamentary-list-creation.service.ts
libs/application/template-api-modules/src/lib/modules/templates/signature-collection/parliamentary-list-signing/parliamentary-list-signing.service.ts
libs/application/templates/signature-collection/parliamentary-list-creation/src/dataProviders/index.ts
libs/application/templates/signature-collection/parliamentary-list-creation/src/forms/Done.ts
libs/application/templates/signature-collection/parliamentary-list-creation/src/forms/Prerequisites.ts
libs/application/templates/signature-collection/parliamentary-list-creation/src/lib/createCollectionTemplate.ts
libs/application/templates/signature-collection/parliamentary-list-creation/src/lib/messages.ts
libs/application/templates/signature-collection/parliamentary-list-signing/src/lib/errors.ts
libs/clients/signature-collection/src/lib/signature-collection.service.ts
libs/service-portal/signature-collection/src/hooks/index.ts
libs/service-portal/signature-collection/src/lib/messages.ts
libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/index.tsx
libs/service-portal/signature-collection/src/screens/Parliamentary/index.tsx
libs/service-portal/signature-collection/src/screens/shared/SignedList/index.tsx
libs/service-portal/signature-collection/src/screens/shared/SigneeView/index.tsx

d25d4e97d45e374eeef14f47ff8e55a50c3b60d7 (detect user delegation type)
8b46f97e1ade6d715e0e0bb4b365393771810640 (user not found handling)
695edeea45f656d8f30fb6af8ddf7eabc12eb067 (refetch is owner 16.10)

fix(application-plc): Fixes 16.10 batch 2

---

libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
libs/api/domains/driving-license/src/lib/drivingLicense.type.ts
libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.service.ts
libs/application/templates/driving-license/src/forms/draft/subSectionDelivery.ts
libs/application/templates/driving-license/src/forms/draft/subSectionSummary.ts
libs/application/templates/driving-license/src/lib/constants.ts
libs/application/templates/driving-license/src/lib/dataSchema.ts
libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts
libs/application/templates/driving-license/src/lib/types.ts
libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
libs/clients/driving-license/src/v5/clientConfig.json

feat(driving-license): add pickup option to submit data for 65+

---

libs/application/templates/financial-aid/src/components/Logo/Logo.tsx

Fix error in dynamic log when prereq fails

fix(financial-aid): dynamic logo

---

apps/application-system/api/migrations/20241022145836-payment-alter-column-definition-text.js

This PR introduces a migration to update the `definition` column in the `payment` table from `STRING` to `TEXT`. This change is necessary to accommodate larger JSON schema data that exceeds the previous character limit imposed by the `STRING` type.
- **Migration**: 
- Altered the `definition` column type from `Sequelize.STRING` to `Sequelize.TEXT` in the `payment` table.
- the `up` method to change the column type to `TEXT`.
- the `down` method to revert the column type back to `STRING` if needed.
- **Increased Capacity**: The `TEXT` type allows for storing larger strings, which is essential for handling JSON data that can exceed the default `STRING` length limit.
- **Seamless Integration**: The change is expected to be seamless in PostgreSQL, with no significant side effects on storage …

fix(applicaiton-system): Payment migration for definition to text from string

---

libs/application/template-api-modules/src/lib/modules/templates/financial-aid/financial-aid.service.ts

Use bankNumber and ledger when sending bank info
bank info was returning as accountNumber-acountNumber-acountNumber but should be bankNumber-ledger-accountNumer

fix(financial-aid): use bankNumber and ledger

---

libs/island-ui/core/src/lib/Button/Button.tsx

Render button children in span
Hotfix #16515

fix(ui-core): Render button string children in span (hotfix)

---

apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculatorResults.tsx

fix(web): Hotfix - pension calculator result preview only for current year (#16751)

---

libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

https://github.com/island-is/island.is/pull/16756
When the start day is 17 and end month has 31 days it was giving wrong endDate
Co-authored-by: Ylfa <55542991+ylfahfa@users.noreply.github.com>

fix(parental-leave): Correct endDate for month slider

---

apps/judicial-system/web/src/components/InfoCard/DefendantInfo/DefendantInfo.strings.ts
apps/judicial-system/web/src/routes/Shared/IndictmentOverview/IndictmentOverview.tsx

[Asana](https://app.asana.com/0/1199153462262248/1208595674703393/f)
This PR addresses issues from https://github.com/island-is/island.is/pull/16709. 
1. Fixes typo -- `Birting skal dómfellda dóminn` ➡️ `Birta skal dómfellda dóminn`
2. Display verdict view date for defenders in their info cards. 
These are bugs

fix(j-s): Display verdict view date for defenders

---

apps/services/user-notification/infra/user-notification.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
charts/services/user-notification-cleanup-worker/values.dev.yaml
charts/services/user-notification-cleanup-worker/values.prod.yaml
charts/services/user-notification-cleanup-worker/values.staging.yaml
charts/services/user-notification-worker/values.dev.yaml
charts/services/user-notification-worker/values.prod.yaml
charts/services/user-notification-worker/values.staging.yaml
charts/services/user-notification/values.dev.yaml
charts/services/user-notification/values.prod.yaml
charts/services/user-notification/values.staging.yaml

Add application-system grant to user-notification
So application-system users can get their notifications

fix(application-system): Add application-system grant to user-notification

---

libs/portals/admin/delegation-admin/src/screens/CreateDelegation/CreateDelegation.tsx
libs/portals/admin/delegation-admin/src/screens/DelegationAdminDetails/DelegationAdmin.tsx
libs/portals/admin/delegation-admin/src/screens/Root.tsx
libs/portals/shared-modules/delegations/src/components/delegations/DelegationViewModal.tsx

Broke current auth logic for some screens

fix(admin-portal): Fix bff hooks to not use old auth hooks (#17018)

---

.dockerignore

This reverts commit ede53ec81c26abb87c4b0352912652dc694e9ec0.
This is breaking docker builds due to our GtiHub cache project being ignored

revert: "chore(infra): Improve `.dockerignore` (#17048)"

---

apps/api/infra/api.ts
apps/services/bff/infra/admin-portal.infra.ts
apps/services/bff/infra/my-pages-portal.infra.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
charts/services/api/values.dev.yaml
charts/services/api/values.prod.yaml
charts/services/api/values.staging.yaml
charts/services/services-bff-portals-admin/values.dev.yaml
charts/services/services-bff-portals-admin/values.prod.yaml
charts/services/services-bff-portals-admin/values.staging.yaml
charts/services/services-bff-portals-my-pages/values.dev.yaml
charts/services/services-bff-portals-my-pages/values.prod.yaml
charts/services/services-bff-portals-my-pages/values.staging.yaml

fix(services-bff): Fix ingress for portals

---

apps/api/infra/api.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
charts/services/api/values.dev.yaml
charts/services/api/values.prod.yaml
charts/services/api/values.staging.yaml

API needs a grant to allow bff communications for the service portal

fix: add missing ns grant to api for bff

---

libs/api/domains/documents/src/lib/documentV2.service.ts
libs/api/domains/documents/src/lib/dto/getDocumentListInput.ts
libs/api/domains/documents/src/lib/models/v2/documents.input.ts
libs/clients/documents-v2/src/lib/dto/listDocuments.input.ts
libs/clients/documents/src/lib/documentClient.ts
libs/clients/documents/src/lib/models/DocumentInput.ts

Sort by publication in documents v1 and v2 by default
After client config update in october, `Publication` has been added. UI already sorts by publication, so the service should sort by publication by default.

fix(documents): Sort by publication v1 and v2 by default

---

apps/services/bff/src/app/modules/user/user.controller.spec.ts
apps/services/bff/src/app/modules/user/user.service.ts

[Pull request on main](https://github.com/island-is/island.is/pull/17247)

fix(services-bff): Add missing exp check on the user endpoint

---

libs/content-search-toolkit/src/queries/search.ts

feat(web): Hotfix - Global search alias for 'Vinnumálastofnun' (#17204)

---

apps/web/components/ChatPanel/BoostChatPanel/BoostChatPanel.tsx

fix(web): Hotfix - Boost chat panel,  use pushUp prop #17271

---

apps/contentful-apps/pages/fields/admin-only-boolean-field.tsx
apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/screens/queries/Organization.tsx
libs/cms/src/lib/generated/contentfulTypes.d.ts
libs/cms/src/lib/models/organizationPage.model.ts
libs/cms/src/lib/search/importers/organizationPage.service.ts
libs/cms/src/lib/search/importers/organizationSubpage.service.ts

feat(web): Hotfix - Organization pages, boolean in CMS that'll hide pages from search engines (#17283)

---

libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils/mappers.ts
libs/application/templates/inheritance-report/src/lib/dataSchema.ts

fix(inheritance-report): bugfixing 20.12

---

apps/judicial-system/web/src/components/InfoCard/InfoCardClosedIndictment.tsx
apps/judicial-system/web/src/components/InfoCard/useInfoCardItems.tsx

- [Asana task](https://app.asana.com/0/1199153462262248/1208837484868039)
- Removing rendering an empty date field when prosecutor is reviewing a case
- Don't want to render labels with `undefined` value
- First time a prosecutor is reviewing
- After review we see the date 👍 

fix(j-s): hide review date field when review date is falsy

---

apps/web/components/ChatPanel/BoostChatPanel/BoostChatPanel.tsx

feat(web): Boost.ai - Set language depending on activeLocale

---

libs/clients/documents-v2/src/lib/dto/document.dto.ts
libs/clients/documents-v2/src/utils/htmlConfig.ts

fix(documents): Don't force lowercase attribute names (hotfix)

---

libs/island-ui/core/src/lib/Footer/Footer.css.ts
libs/island-ui/core/src/lib/Footer/Footer.tsx

fix(web): Global footer - Do not wrap privacy policy title below icon

---

apps/web/components/Webreader/Webreader.tsx

fix(web): Hotfix - Readspeaker href gets opened by Plausible outbound link tracking script (#17981)

---

apps/web/components/Form/Form.tsx
libs/api/domains/communications/src/lib/communications.service.ts
libs/api/domains/communications/src/lib/dto/genericForm.input.ts

fix(web): Hotfix - Form, English locale with different options doesn't load email config correctly (#18015)

---

.github/workflows/deploy-argocd.yml
scripts/ci/docker/generate-tag.mjs
scripts/ci/docker/get-data.mjs

fix: apply on mq

---

.markdownlint.yml
.vscode/extensions.json

Stop those annoying "line too long" warnings in my editor. Also, suggest a plugin (and add config), so more will follow its style guide.

chore: Add config for `markdownlint`

---

package.json
yarn.lock

Version 3 of kennitala has stricter national id validation, making sure that they reflect valid dates. However, there are a few national ids from February of 1969 which do not have valid dates. This update has a fix which considers these valid.

fix: Hotfix - Update kennitala package to fix edge cases (#18332)

---

libs/application/templates/rental-agreement/src/forms/draft/rentalHousing/rentalHousingSpecialProvisions.ts
libs/application/templates/rental-agreement/src/lib/dataSchema.ts

fix(rental-agreement): validate descriptionInput set when required

---

apps/web/screens/Article/Article.tsx
apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculatorWrapper.tsx

fix(web): Hotfix - Wrap div around header and footer so they don't shrink #18632

---

libs/cms/src/lib/cms.elasticsearch.service.ts

fix(web): Hotfix, Team list member order - Only order by score if there is a text input

---

libs/application/template-api-modules/src/lib/modules/templates/hms/fire-compensation-appraisal/fire-compensation-appraisal.service.ts
libs/application/templates/hms/fire-compensation-appraisal/src/forms/mainForm/photoSection.ts

fix submit of fire compensation appraisal application, application should be submitted and then photos.
fix real estate data provider. An endpoint should get the real estate id only as a string of numbers but no "F" prefix
So that the application works

fix(hms-fca): hms fire comp appraisal submit

---

libs/application/templates/hms/fire-compensation-appraisal/src/forms/mainForm/photoSection.ts
libs/application/templates/hms/fire-compensation-appraisal/src/forms/mainForm/realEstateSection.ts
libs/application/templates/hms/fire-compensation-appraisal/src/lib/dataSchema.ts
libs/application/templates/hms/fire-compensation-appraisal/src/lib/messages/photoMessages.ts

Add custom error message that gives better guidance to the user if he doesn't upload enough photos
Add fasteignaId to the real estate select field to distinguish properties with the same house and street number

fix(hms-fca): hms file upload message hotfix

---

libs/application/template-api-modules/src/lib/modules/templates/hms/fire-compensation-appraisal/utils.ts

Fasteignanumer has an F appended to it that needs to be removed when the application is sent in
So that the application is correctly created in the HMS system

fix(hms-fca): filter char from fasteignanr

---

libs/island-ui/contentful/src/lib/TeamList/TeamList.tsx

fix(web): Hotfix, Team List - Pass prefixes prop down to rendered component (#19612)
