apps/web/screens/Article/components/ArticleChatPanel/config.ts

* Remove watson bot from evrópska sjúkratryggingakortið article
* This was requested by Stafrænt Ísland

feat(web): Remove watson bot from article

---

libs/application/template-api-modules/src/lib/modules/templates/institution-collaboration/emailGenerators/applicationConfirmationEmail.ts
libs/application/template-api-modules/src/lib/modules/templates/institution-collaboration/emailGenerators/applicationOverviewTemplate.ts
libs/application/templates/institution-collaboration/src/lib/messages.ts

feat(institution-collaboration): Changes to text in email confirmation

---

apps/judicial-system/backend/src/app/modules/case/guards/test/limitedAccessCaseExistsGuard.spec.ts
apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts

[Aðgangur verjanda að S-máli](https://app.asana.com/0/1199153462262248/1202978837143953/f)
- Allows no case files in defender access.
Bug

fix(j-s): No Case Files

---

libs/service-portal/vehicles/src/screens/VehicleDetail/VehicleDetail.tsx

Hotfix to display "Ferilsskýrsla" on prod
See #8512 
Don't need feature flag anymore, but the other functionality this feature flag holds is still needed. 
Note to self: Make two seperate feature flags next time 👍 

chore(service-portal): remove feature flag for ferilsskyrsla (#8512) hotfix

---

apps/services/search-indexer/infra/search-indexer-service.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
libs/cms/src/lib/search/contentful.service.ts

https://github.com/island-is/island.is/pull/8566

fix(search-indexer): Hotfix - Add env variable for chunk size of contentful fetch

---

libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
libs/application/templates/parental-leave/src/lib/answerValidators.ts

feat(parental-leave): fix formatting error when adding new period

---

apps/web/screens/Search/Search.tsx

This is a hotfix PR requested by digital iceland.
Main merged PR: https://github.com/island-is/island.is/pull/8553

feat(web): Hotfix - remove digital iceland service images from search results

---

apps/web/screens/Article/components/ArticleChatPanel/config.ts

* This is a hotfix PR requested by Stafrænt Ísland, here's the PR that got merged to main: https://github.com/island-is/island.is/pull/8557

feat(web): Hotfix - remove chat bot from article

---

libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts

feat(parental-leave): Add VMST nationalId to states

---

libs/application/templates/institution-collaboration/src/lib/messages.ts

application namespace fix translation strings
Not configured correctly resulting in contentful strings being lost and not being able to update through contentful.

fix(ia): IA application namespace fix translation strings

---

apps/judicial-system/backend/src/app/modules/case/case.service.ts
apps/judicial-system/backend/src/app/modules/case/guards/test/caseExistsGuard.spec.ts
apps/judicial-system/backend/src/app/modules/case/test/caseController/create.spec.ts
apps/judicial-system/backend/src/app/modules/case/test/caseController/createCourtCase.spec.ts
apps/judicial-system/backend/src/app/modules/case/test/caseController/extend.spec.ts
apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/archive.spec.ts
apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/create.spec.ts

[Aðgangur verjanda að S-máli](https://app.asana.com/0/1199153462262248/1202978837143953/f}
- Fixes case files query for non-defenders.
Non-defenders were shown deleted case files.

fix(j-s): Case File Query

---

apps/web/components/ServiceWeb/Background/Variations/Mannaudstorg/Mannaudstorg.css.ts
apps/web/components/ServiceWeb/Background/Variations/Mannaudstorg/Mannaudstorg.tsx
apps/web/components/ServiceWeb/SearchSection/SearchSection.tsx
apps/web/screens/ServiceWeb/Home/Home.tsx
apps/web/screens/ServiceWeb/SubPage/SubPage.tsx

https://user-images.githubusercontent.com/43557895/193828855-0154005e-4f2d-4440-8f2c-ded137c43eb7.mov

feat(web): Add new header for Mannauðstorg service web page

---

libs/application/templates/parental-leave/src/dataProviders/Children/Children.ts

feat(parental-leave): Update when otherParent could start application

---

libs/application/templates/parental-leave/src/fields/InReviewSteps/index.tsx
libs/application/templates/parental-leave/src/forms/EditsInReview.ts
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
libs/application/templates/parental-leave/src/lib/answerValidator-utils.ts

feat(parental-leave): Applicant could edit application whenever he wants

---

libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

feat(parental leave): start date checking

---

libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

fix(parental-leave): Add check on NavId to prevent too many Put request

---

apps/web/components/ServiceWeb/Background/Variations/Mannaudstorg/Mannaudstorg.css.ts
apps/web/components/ServiceWeb/Background/Variations/Mannaudstorg/Mannaudstorg.tsx
apps/web/components/ServiceWeb/Forms/StandardForm/StandardForm.tsx
apps/web/components/ServiceWeb/SearchSection/SearchSection.tsx
apps/web/screens/ServiceWeb/Forms/Forms.tsx
apps/web/screens/ServiceWeb/Home/Home.tsx
apps/web/screens/ServiceWeb/SubPage/SubPage.tsx

Cherrypicked PR's that got merged to main:
* https://github.com/island-is/island.is/pull/8591
* https://github.com/island-is/island.is/pull/8581

feat(web): Hotfix - service web form for mannaudstorg 

---

libs/application/template-api-modules/src/lib/modules/templates/institution-collaboration/emailGenerators/applicationConfirmationEmail.ts
libs/application/template-api-modules/src/lib/modules/templates/institution-collaboration/emailGenerators/applicationOverviewTemplate.ts
libs/application/templates/institution-collaboration/src/lib/messages.ts

chore(ia): text changes to email template

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/constants.ts
libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
libs/application/templates/parental-leave/src/fields/SelfEmployed/index.tsx
libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
libs/application/templates/parental-leave/src/lib/answerValidators.ts
libs/application/templates/parental-leave/src/lib/messages.ts

Creating separate fileuploadfields for different conditions, e.g. selfEmployedFile, student etc

feat(parental-leave): creating separate fileUploadFields

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/constants.ts
libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts

feat(parental-leave): Add '_months' to 'from' variable when applicant chooses useLength in months 

---

libs/application/templates/parental-leave/src/forms/EditOrAddPeriods.ts
libs/application/templates/parental-leave/src/forms/InReview.ts
libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
libs/application/templates/parental-leave/src/lib/answerValidators.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

fix(parental-leave): fix validation for managed periods

---

libs/cms/src/lib/search/contentful.service.ts

fix(search-indexer): Hotfix - Remove nested entries from search-indexer (#8629)

---

apps/web/components/ChatPanel/WatsonChatPanel/WatsonChatPanel.tsx
apps/web/components/ChatPanel/types.ts
apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/config.ts
apps/web/screens/Article/components/ArticleChatPanel/ArticleChatPanel.tsx
apps/web/screens/Article/components/ArticleChatPanel/config.ts
apps/web/screens/Home/Home.tsx
apps/web/screens/Home/config.ts

*. Chat bot is only on Icelandic pages, and since the answers and UI have been updated we want to put the chatbot on english pages

feat(web): Add english chat bot to articles

---

libs/application/templates/marriage-conditions/src/fields/ApplicationOverview/ApplicationOverview.tsx
libs/application/templates/marriage-conditions/src/forms/spouseConfirmation.ts
libs/application/templates/marriage-conditions/src/lib/MarriageConditionsTemplate.ts

fix(marriage-conditions): Minor fixes for spouse 2

---

apps/auth-admin-web/components/Resource/forms/IdentityResourceCreateForm.tsx
libs/auth-api-lib/src/lib/delegations/delegationScope.service.ts

Fixing regression introduced in #8542 where the IdentityResources need to be applied automatically for delegations.
To fix regression when using delegations.

fix(auth-api): Enable identity resources for automatic scopes in delegations.

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/applicationApprovedByEmployerToEmployer.ts

fix(parental-leave): check for null in email to employer

---

libs/api/domains/license-service/src/lib/licenseService.service.ts

* date-fns is complaining about a misformatted date. This fixes that.
* Cherry-picked from https://github.com/island-is/island.is/pull/8659

fix(license-service): fix date string

---

libs/api/domains/directorate-of-labour/src/index.ts
libs/api/domains/directorate-of-labour/src/lib/directorate-of-labour.repository.ts
libs/api/domains/directorate-of-labour/src/lib/directorate-of-labour.resolver.ts
libs/api/domains/directorate-of-labour/src/lib/directorate-of-labour.service.ts
libs/api/domains/directorate-of-labour/src/models/applicationInformation.model.ts
libs/api/domains/directorate-of-labour/src/models/applicationInformationChildren.model.ts
libs/api/domains/directorate-of-labour/src/models/applicationInformationEmployer.model.ts
libs/api/domains/directorate-of-labour/src/models/applicationRights.model.ts
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
libs/clients/vmst/src/clientConfig.yaml
libs/clients/vmst/src/lib/vmst.module.ts

feat(parental-leave): Add getApplicationInformation endpoint

---

apps/system-e2e/src/tests/web/smoke/homepage.spec.ts

chore(system-e2e): Homepage tests for both english and icelandic

---

libs/application/templates/parental-leave/src/forms/EditOrAddPeriods.ts
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts

feat(parental-leave): add final in closed state

---

libs/service-portal/applications/src/screens/Overview.tsx
libs/service-portal/assets/src/screens/AssetsOverview/AssetsOverview.tsx
libs/service-portal/core/src/lib/messages.ts
libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
libs/service-portal/finance/src/components/DocumentScreen/DocumentScreen.tsx
libs/service-portal/finance/src/screens/FinanceSchedule/FinanceSchedule.tsx
libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx
libs/service-portal/finance/src/screens/FinanceTransactions/FinanceTransactions.tsx
libs/service-portal/licenses/src/screens/LicensesOverview/LicensesOverview.tsx
libs/service-portal/vehicles/src/screens/Lookup/Lookup.tsx
libs/service-portal/vehicles/src/screens/Overview/Overview.tsx
libs/service-portal/vehicles/src/screens/VehicleDetail/VehicleDetail.tsx
libs/service-portal/vehicles/src/screens/VehicleHistory/VehicleHistory.tsx

Hotfix:
https://github.com/island-is/island.is/pull/8663
https://github.com/island-is/island.is/pull/8672
https://github.com/island-is/island.is/pull/8667

fix(service-portal): hotfix for finance filter + docline disappear

---

libs/cms/src/lib/search/contentful.service.ts

* Add more robust code that uses chunk size for nested entries
* Wrap the sync api call into a function to reduce the amount of memory we need
This is a cherry-picked hotfix PR, here's the PR that got merged to main: #8675

fix(search-indexer): Add chunk size to linked entry fetch (#8675)

---

libs/cms/src/lib/search/contentful.service.ts

feat(search-indexer): Half chunk size if Contentful limit is reached for response size

---

libs/cms/src/lib/search/contentful.service.ts

feat(search-indexer): Half chunk size if Contentful limit is reached for response size (#8688)

---

apps/system-e2e/src/notifications/notify.ts

test(system-e2e): Better failure notification

---

apps/system-e2e/src/support/utils.ts
apps/system-e2e/src/tests/web/smoke/homepage.spec.ts
apps/system-e2e/src/tests/web/smoke/search.spec.ts

fix(qa): removing explicit timeouts and fixing Staging urls

---

libs/api/domains/license-service/src/lib/client/adr-license-client/adrLicense.spec.ts
libs/api/domains/license-service/src/lib/client/adr-license-client/adrLicenseService.api.ts
libs/api/domains/license-service/src/lib/client/driving-license-client/drivingLicenseMappers.ts
libs/api/domains/license-service/src/lib/client/firearm-license-client/firearmLicense.spec.ts
libs/api/domains/license-service/src/lib/client/firearm-license-client/firearmLicenseMapper.ts
libs/api/domains/license-service/src/lib/client/firearm-license-client/firearmLicenseService.api.ts
libs/service-portal/licenses/src/screens/LicenseDetail/LicenseDetail.tsx

Cherry picked from PR: https://github.com/island-is/island.is/pull/8671

feat(service-portal): Add pkpass eligibility validation for firearm/adr license

---

apps/services/auth/api/infra/identity-server.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml
infra/src/dsl/types/input-types.ts

https://github.com/island-is/infrastructure/issues/1313
Make a volume for IDS
So IDS can persist and rotate its own certs

chore(infra): Add volume for IDS certs, Give example input to volume

---

apps/api/esbuild.json

chore(api): Add p-cancellable to API esbuild packages

---

apps/api/esbuild.json

fix(api): Spelling mistake in package

---

apps/github-actions-cache/src/app/health.ts

fix(actions-cache): liveness conditional

---

libs/api/domains/driving-license/src/lib/util/hasResidenceHistory.ts
libs/application/templates/driving-license/src/forms/draft/subSectionSummary.ts
libs/application/templates/driving-license/src/lib/dataSchema.ts
libs/application/templates/operating-license/src/lib/utils.ts

fix(driving-license-application): mapping instructor name and minor fixes

---

apps/api/esbuild.json

fix(api): Add missing dependencies

---

libs/application/templates/financial-statements-inao/src/fields/CemetryEquities/index.tsx
libs/application/templates/financial-statements-inao/src/fields/ElectionEquties/index.tsx
libs/application/templates/financial-statements-inao/src/fields/KeyNumbers/Total.tsx

add currency suffix and format to all input fields
easier to read

feat(financial-statement-inao): always show currency suffix

---

libs/api/domains/directorate-of-labour/src/models/applicationInformation.model.ts
libs/api/domains/directorate-of-labour/src/models/applicationInformationPeriod.model.ts
libs/application/templates/parental-leave/src/fields/FirstPeriodStart/index.tsx
libs/application/templates/parental-leave/src/fields/InReviewSteps/index.tsx
libs/application/templates/parental-leave/src/fields/PeriodsRepeater/index.tsx
libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
libs/application/templates/parental-leave/src/graphql/queries.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
libs/application/templates/parental-leave/src/types.ts
libs/clients/vmst/src/clientConfig.yaml

feat(parental-leave): Add sync VMST periods

---

apps/services/auth/public-api/src/app/modules/delegations/meDelegations.controller.spec.ts
libs/auth-api-lib/src/lib/delegations/delegations.service.ts

Fixing bug when updating delegations.
To fix a security bug in auth public api.

fix(aut-public-api): Fix security bug in update delegations.

---

apps/services/auth/public-api/src/app/modules/delegations/meDelegations.controller.spec.ts
libs/auth-api-lib/src/lib/delegations/delegations.service.ts

Hotfix #8750 into release.
To fix in production.

fix(auth-public-api): Hotfix bug in update delegations. (#8750)

---

apps/services/user-notification/esbuild.json

fix(user-notification): Add jwa package for user-notification

---

apps/judicial-system/backend/project.json

[Auður - dev umhverfi. EKki hægt að stofna mál eða vista gögn. ](https://app.asana.com/0/1199153462262248/1203200599843615/f)
- Disables experimental fetch in the backend.
The experimental fetch was interfering with court system calls via xRoad.

fix(j-s): Block Experimental Fetch

---

apps/judicial-system/backend/src/app/modules/case/case.module.ts

[InternalCaseService initialization er brotin í hosting umhverfum](https://app.asana.com/0/1199153462262248/1203201763720712/f)
Changes the order of CaseService and InternalCaseService as providers and CaseController and InternalCaseController as controllers. This seems to affect the initialisation order and fix an injection error that caused some injected services to be undefined in InternalCaseService. The change has already been tested on dev and seems to do the trick.
Verified bug.

fix(j-s): Injection Fix

---

libs/application/templates/parental-leave/src/lib/answerValidators.ts

fix(parental-leave): Add check for private pension fund

---

apps/web/components/Organization/Slice/SliceMachine.tsx
apps/web/components/Organization/Slice/TimelineSlice/TimelineSlice.css.ts
apps/web/components/Organization/Slice/TimelineSlice/TimelineSlice.tsx

https://user-images.githubusercontent.com/43557895/197332413-6a9342b8-f018-4c47-9102-fd8706ff51fc.mov

feat(web): Add a way to drag the timeline slice

---

scripts/ci/Dockerfile

Add --no-experimental-fetch in entrypoints for runners
The global node fetch API doesn't have the same functionality as the fetch packages we use in different projects

fix(infra): Add --no-experimental-fetch in entrypoints for runners

---

scripts/ci/Dockerfile

This reverts commit 83d8d6fd76ba6857bc34330d6a1264c48ac7145c.

fix(infra): Revert "fix(infra): Add --no-experimental-fetch in entrypoints for runners (#8770)"

---

scripts/ci/Dockerfile

This reverts commit 8eda8c34173c90ee3dc404d866a127ec30bd3f11.
Some confusion led me to think this was the cause of an issue we were facing with spinnaker, by coincidence another issue was causing problems at the same time the original was merged.

fix(infra): Revert Revert "fix(infra): Add --no-experimental-fetch in entrypoints for runners"

---

libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

fix(parental leave): fix for old applications

---

apps/api/infra/api.ts
apps/github-actions-cache/infra/github-actions-cache.ts
apps/judicial-system/message-handler/infra/judicial-system-message-handler.ts
apps/judicial-system/scheduler/infra/judicial-system-scheduler.ts
apps/services/endorsements/api/infra/endorsement-system-api.ts
apps/services/user-notification/infra/user-notification.ts
apps/services/xroad-collector/infra/xroad-collector.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
charts/judicial-system/values.dev.yaml
charts/judicial-system/values.prod.yaml
charts/judicial-system/values.staging.yaml

Fix issue where apps were using the node global fetch API
Fix issues with various apps.

fix(node): Add --no-experimental-fetch to .args where used

---

libs/api/domains/directorate-of-labour/src/lib/directorate-of-labour.resolver.ts
libs/application/templates/parental-leave/src/fields/PeriodsRepeater/index.tsx
libs/application/templates/parental-leave/src/graphql/queries.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

fix(parental-leave): remove error message when employer approves application

fix(parental-leave): remove error message when employer approves application

---

libs/api/domains/directorate-of-labour/src/lib/directorate-of-labour.resolver.ts
libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.ts
libs/application/templates/parental-leave/src/fields/Duration/Duration.tsx
libs/application/templates/parental-leave/src/fields/FirstPeriodStart/index.tsx
libs/application/templates/parental-leave/src/fields/PeriodPercentage/PeriodPercentage.tsx
libs/application/templates/parental-leave/src/fields/PeriodsRepeater/index.tsx
libs/application/templates/parental-leave/src/fields/components/Timeline/Chart.tsx
libs/application/templates/parental-leave/src/fields/components/Timeline/Panel.tsx
libs/application/templates/parental-leave/src/forms/EditOrAddPeriods.ts
libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
libs/application/templates/parental-leave/src/graphql/queries.ts
libs/application/templates/parental-leave/src/lib/answerValidators.ts
libs/application/templates/parental-leave/src/lib/messages.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

fix(parental leave): fix bugs on new applications

---

libs/application/templates/financial-statements-inao/src/lib/financialStatementsInao.ts

feat(financial-statement-inao): add users name to application title when available

---

libs/auth-api-lib/migrations/20221012094608-add-personal-representative-inactive.js

Fix column name in migration.
Migrations need to have snake_case even though code uses camelCase.

fix(auth): Fix column name in personal-representative migration

---

libs/application/templates/parental-leave/src/fields/HasMultipleBirths/index.tsx
libs/application/templates/parental-leave/src/forms/Prerequisites.ts
libs/application/templates/parental-leave/src/lib/answerValidators.ts
libs/application/templates/parental-leave/src/lib/dataSchema.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
libs/application/templates/parental-leave/src/types.ts

feat(parental-leave): Add validated for multiple births inputs

---

libs/application/templates/parental-leave/src/config.ts
libs/application/templates/parental-leave/src/fields/Rights/GiveDaysSlider.tsx
libs/application/templates/parental-leave/src/fields/Rights/RequestDaysSlider.tsx
libs/application/templates/parental-leave/src/fields/Rights/TransferRights.tsx
libs/application/templates/parental-leave/src/fields/components/BoxChart/BoxChart.css.ts
libs/application/templates/parental-leave/src/fields/components/BoxChart/index.tsx
libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
libs/application/templates/parental-leave/src/forms/Prerequisites.ts
libs/application/templates/parental-leave/src/lib/answerValidators.ts
libs/application/templates/parental-leave/src/lib/messages.ts

feat(parental-leave): multiple births change flow

---

apps/judicial-system/backend/src/app/modules/case/case.service.ts

[Smíða einn PDF gagnapakka úr málsgögnum](https://app.asana.com/0/1199153462262248/1203046355378049/f)
- Fixes case file exclusion from PDF.
Verified bug.

fix(j-s): Case File Exclusion

---

apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/courtRecord.spec.ts

Skip a failing e2e test that is stopping unrelated PRs from being merged

fix(j-s): Skip a failing e2e test

---

libs/application/template-api-modules/src/lib/modules/templates/marriage-conditions-submission/marriage-conditions-submission.service.ts
libs/application/template-api-modules/src/lib/modules/templates/marriage-conditions-submission/types.ts
libs/application/templates/marriage-conditions/src/fields/ApplicationOverview/ApplicationOverview.tsx
libs/application/templates/marriage-conditions/src/forms/application.ts
libs/application/templates/marriage-conditions/src/forms/spouseConfirmation.ts
libs/application/templates/marriage-conditions/src/lib/constants.ts
libs/application/templates/marriage-conditions/src/lib/dataSchema.ts
libs/application/templates/marriage-conditions/src/lib/messages.ts
libs/application/templates/marriage-conditions/src/types.ts

fix(marriage-conditions): cleanup of previous marriage and text tweak

---

libs/content-search-toolkit/src/queries/search.ts

support * wildcard for internal users

feat(content-search-toolkit): Support wildcard

---

libs/api/domains/directorate-of-labour/src/lib/directorate-of-labour.resolver.ts
libs/application/templates/parental-leave/src/fields/PeriodsRepeater/index.tsx
libs/application/templates/parental-leave/src/fields/Review/Review.tsx
libs/application/templates/parental-leave/src/forms/EmployerApproval.ts
libs/application/templates/parental-leave/src/forms/EmployerApproveEdits.ts
libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
libs/application/templates/parental-leave/src/graphql/queries.ts
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

* fix(parental-leave): fix employer could not approve edited periods
* fix(parental-leave): fix employer could not approve edited application

fix(parental leave): fix employer could not approve edited app (#8855)

---

libs/application/templates/parental-leave/src/fields/Rights/GiveDaysSlider.tsx
libs/application/templates/parental-leave/src/fields/Rights/RequestDaysSlider.tsx
libs/application/templates/parental-leave/src/fields/Rights/TransferRights.tsx
libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts

feat(parental-leave): revert PR #8849

---

libs/application/templates/marriage-conditions/src/fields/ApplicationOverview/ApplicationOverview.tsx
libs/application/templates/marriage-conditions/src/forms/application.ts
libs/application/templates/marriage-conditions/src/forms/spouseDone.ts
libs/application/templates/marriage-conditions/src/lib/messages.ts

fix(marriage-conditions): overview tweak

---

libs/application/templates/parental-leave/src/config.ts
libs/application/templates/parental-leave/src/fields/Rights/RequestMultipleBirthsDaysSlider.tsx
libs/application/templates/parental-leave/src/fields/Rights/TransferRights.tsx
libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
libs/application/templates/parental-leave/src/types.ts

feat(parental-leave): change flow 1.0

---

libs/application/templates/parental-leave/src/fields/Rights/RequestDaysSlider.tsx
libs/application/templates/parental-leave/src/fields/Rights/RequestMultipleBirthsDaysSlider.tsx
libs/application/templates/parental-leave/src/fields/Rights/TransferRights.tsx
libs/application/templates/parental-leave/src/fields/components/BoxChart/index.tsx
libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
libs/application/templates/parental-leave/src/lib/messages.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

feat(parental-leave): change flow for requested days

---

apps/judicial-system/backend/src/app/modules/case/case.service.ts

[Reyna aftur að vista úrskurð/þingbók í Auði ef villa kemur upp í vistun](https://app.asana.com/0/1199153462262248/1202978837144083/f)
- Stops uploading court record and ruling to court for indictment cases.
These documents come from the court system and should not be uploaded

fix(j-s): No Court Record and Ruling for Indictment Cases

---

libs/application/templates/parental-leave/src/fields/Rights/RequestMultipleBirthsDaysSlider.tsx
libs/application/templates/parental-leave/src/fields/components/Slider/index.tsx
libs/application/templates/parental-leave/src/lib/messages.ts

Change and translate text for multiple birth application

feat(parental-leave): parental leave multiple births text

---

libs/application/templates/parental-leave/src/fields/Rights/RequestDaysSlider.tsx
libs/application/templates/parental-leave/src/fields/Rights/RequestMultipleBirthsDaysSlider.tsx
libs/application/templates/parental-leave/src/fields/Rights/TransferRights.tsx
libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
libs/application/templates/parental-leave/src/lib/answerValidators.ts
libs/application/templates/parental-leave/src/lib/messages.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
libs/application/templates/parental-leave/src/types.ts

feat(parental-leave): multiple births change flow 3.0

---

apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFiles/CaseFiles.tsx

[Asana](https://app.asana.com/0/1199153462262248/1203292133988705/f)
Remove required star from upload fields on CaseFile screen
These fields are not required and should not be marked as such.

chore(j-s): Remove required star from upload fields on CaseFile screen

---

libs/clients/vmst/src/lib/utils.ts

chore(vmst_logging): Improved error logging for vmst utils

---

libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

feat(parental-leave): Change flow after get confirmation from VMST

---

libs/application/ui-forms/src/lib/applicantInformationSection/applicantInformationMultiField.ts
libs/application/ui-forms/src/lib/applicantInformationSection/types.ts

Create a type manually for form-ui multifield
Type safety

fix(applications): incorrect type was used for application

---

libs/application/templates/data-protection-complaint/src/forms/ComplaintForm.ts

fix(dpc-application): Fix initial render bug

---

libs/api/domains/auth/src/lib/services-v2/meDelegations.service.ts

fix(auth): Handle missing delegations

---

libs/auth-api-lib/src/lib/resources/resources.service.ts

Fixing bug in domain validation when adding scope to group.
To unblock IDS Admin to be able to add scope to groups.
N/A

fix(auth-api-lib): Fix bug in domain validation when adding scope to group

---

libs/service-portal/settings/access-control/src/components/Accesses/Accesses.tsx
libs/service-portal/settings/access-control/src/screens/Access/Access.tsx
libs/service-portal/settings/access-control/src/screens/GrantAccess/GrantAccess.tsx

fix(auth): delegations v1 queries fix

---

libs/content-search-toolkit/src/queries/rankEvaluation.ts
libs/content-search-toolkit/src/queries/search.ts
libs/content-search-toolkit/src/services/elastic.service.ts

fixes conflict with ratings query

feat(content-search-toolkit): Defaults for highlights

---

libs/application/template-api-modules/src/lib/modules/templates/health-insurance/health-insurance.utils.ts

Null check
So things can be null

fix(application): Hotfix health insurance application null check

---

libs/api/domains/directorate-of-labour/src/lib/directorate-of-labour.resolver.ts
libs/application/templates/parental-leave/src/fields/PeriodsRepeater/index.tsx
libs/application/templates/parental-leave/src/fields/Review/Review.tsx
libs/application/templates/parental-leave/src/graphql/queries.ts
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
libs/application/templates/parental-leave/src/lib/answerValidators.ts

fix(parental leave): Fix employer errors

---

apps/service-portal/src/store/modules.ts

Allow companies to use new delegations module (still hidden behind feature flag).

fix(auth): Enable new delegations module for companies

---

libs/application/templates/health-insurance/src/forms/HealthInsuranceForm.ts
libs/application/templates/health-insurance/src/lib/dataSchema.ts

Not use shared form ui libary any more
This application has custom logic

fix(applications): Revert health insurance changes from form ui libary

---

libs/service-portal/core/src/lib/navigation/masterNavigation.ts

Cherry pick for release the fix of access control v2 menu item.
To fix for release
N/A

fix(service-portal): Cherry pick access control v2 menu fix

---

libs/application/templates/parental-leave/src/fields/PeriodsRepeater/index.tsx
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts

1. fix otherParent permission
2. fix sync startDate from VMST

fix(parental leave): other parent permission

---

charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
charts/judicial-system/values.dev.yaml
charts/judicial-system/values.prod.yaml
charts/judicial-system/values.staging.yaml
infra/src/environments.ts

fix(infra): reduce update notice spam in datadog

---

apps/service-portal/src/store/modules.ts

Apply hotfix on pre-release.
To fix for release

fix(auth): Enable new delegations module for companies (#8961)

---

.yarnrc.yml

Decrease in node_module size from 3.5G -> 2.2G

chore(yarn): Use hard-linking for duplicate packages

---

libs/application/templates/financial-statements-inao/src/fields/ElectionStatement/index.tsx
libs/application/templates/financial-statements-inao/src/fields/Overview/index.tsx
libs/application/templates/financial-statements-inao/src/fields/PartyOverview/index.tsx

incorrect name for upload sceen whan navigating back

fix(financial-statement-inao): fix upload screen naming

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/constants.ts
libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

feat(parental-leave): add rightCodePeriod for multiple births

---

libs/api/domains/auth/src/lib/services-v2/meDelegations.service.ts
libs/service-portal/access-control/delegations/src/components/access/AccessForm.tsx
libs/service-portal/access-control/delegations/src/components/access/AccessItem.css.ts
libs/service-portal/access-control/delegations/src/components/access/AccessItem.tsx
libs/service-portal/access-control/delegations/src/components/access/access.utils.ts
libs/service-portal/access-control/delegations/src/components/delegations/DelegationsFromMe.tsx

- Fixes sorting delegation by name in access control view.
- Sorts out expired delegations on the API GraphQL client
- Removes background colour on row list in scope rights.
- Disables confirm button if no delegations have been selected

fix(service-portal): Delegation UI V2 fixes

---

libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts

fix(parental-leave): Add check before adding VMST_ID

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
libs/application/templates/parental-leave/src/dataProviders/Children/Children-utils.ts
libs/application/templates/parental-leave/src/fields/Rights/RequestMultipleBirthsDaysSlider.tsx
libs/application/templates/parental-leave/src/fields/Rights/TransferRights.tsx
libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

fix(parental-leave): refactor multipleBirthsRequestsDays

---

libs/application/templates/parental-leave/src/lib/answerValidators.ts

fix(parental-leave): fix give-right and request-rights validation

---

libs/api/domains/directorate-of-labour/src/models/parentalLeave.model.ts
libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.ts
libs/clients/vmst/src/clientConfig.yaml

feat(parental-leave): Update API call for multiple births

---

libs/service-portal/core/src/components/ActionCard/ActionCard.tsx
libs/service-portal/core/src/components/IntroHeader/IntroHeader.tsx
libs/service-portal/core/src/components/LinkResolver/LinkResolver.css.ts
libs/service-portal/core/src/components/LinkResolver/LinkResolver.tsx

fix(service-portal): image positioning, icons and plausible

---

libs/application/templates/financial-statements-inao/src/fields/ElectionStatement/index.tsx

Don't need a specific approval when returning statement

fix(financial-statement-inao): Remove approve requirement for election statment

---

apps/web/components/ServiceWeb/Forms/StandardForm/StandardForm.tsx

Hotfix, cherry picked from #9006

fix(service-web): Modifier disabled in favor of functionality

---

libs/application/ui-shell/src/lib/ApplicationForm.tsx

fix(application-system): Reintroduce shell

---

libs/application/templates/parental-leave/src/fields/Rights/RequestDaysSlider.tsx
libs/application/templates/parental-leave/src/fields/Rights/RequestMultipleBirthsDaysSlider.tsx
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.spec.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

feat(parental-leave): refactor and add unitest for multiple births

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/constants.ts
libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts

fix(parental-leave): fix rightCodes for multiple births

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.ts

fix(parental-leave): Remove noOfChildren if not multipleBirths

---

libs/application/templates/financial-statements-inao/src/forms/application/individual/individualKeyNumbers.ts
libs/application/templates/financial-statements-inao/src/forms/application/party/partyKeyNumbers.ts

wrong properties from messages in a few places being used

fix(financial-statement-inao):  adjust text for keynumbers

---

apps/web/next.config.js
apps/web/pages/api/rss/opinbernyskopun.ts
apps/web/screens/queries/Project.tsx
apps/web/screens/queries/fragments.ts
libs/cms/src/lib/generated/contentfulTypes.d.ts
libs/cms/src/lib/models/questionAndAnswer.model.ts
package.json
yarn.lock

* Added an rss feed for the question and answer items for the project subpage /v/opinbernyskopun/askoranir-opinberra-adila
* Added a read only field for question and answer content type so we can correctly state the publish date of each item (the field is autofilled via a Contentful app / UI extension)
* Added a dependency so I can parse the rich text content into an html string to place in the RSS feed
* It was requested that we add this feature so the Opinber Nýsköpun team can send out emails each time a new challenge gets published

feat(web): RSS feed for /v/opinbernyskopun/askoranir-opinberra-adila

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/screens/Organization/SubPage.tsx

* Digital Iceland wants the external links of Sjúkratryggingar to have more of an emphasis on the web so we changed the look of the buttons
* This was requested by Digital Iceland (Stafrænt Ísland)

feat(web): Add custom styles to external links of /s/sjukratryggingar

---

libs/application/template-api-modules/src/lib/modules/templates/health-insurance/health-insurance.service.ts

Adding error to error logging in sjukratryggingar

fix(health-insurance): Add error logging back into service

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsHeader.css.ts
apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsHeader.tsx
apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/index.ts

https://user-images.githubusercontent.com/43557895/202196706-4332d8b4-8bf6-4810-862d-cd8caf0f8d31.mov

feat(web): Add header for Fjársýsla ríkisins

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsFooter.css.ts
apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsFooter.tsx
apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsHeader.css.ts
apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsHeader.tsx
apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/index.ts

Cherrypicked commits from two different PR's that got merged with main:
https://github.com/island-is/island.is/pull/9050
https://github.com/island-is/island.is/pull/9020

feat(web): Hotfix - Fjársýsla ríkisins, header and footer

---

libs/application/templates/financial-statements-inao/src/fields/CemetryEquities/index.tsx
libs/application/templates/financial-statements-inao/src/fields/CemetryOperation/cemetryIncome.tsx
libs/application/templates/financial-statements-inao/src/fields/PowerOfAttorneyFields/index.tsx
libs/application/templates/financial-statements-inao/src/fields/Shared/CapitalNumberOverview.tsx

various small fixes for fsi application

fix(financial-statement-inao): fsi few minor fixes

---

libs/service-portal/access-control/delegations/src/components/access/AccessCard.tsx
libs/service-portal/access-control/delegations/src/screens/GrantAccess/GrantAccess.tsx
libs/service-portal/core/src/lib/messages.ts

fix(auth): Fix access control translations

---

apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsHeader.css.ts

feat(web): Decrease header height for fjarsyslan

---

apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsHeader.css.ts

feat(web): Decrease header height

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsFooter.tsx
apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsHeader.css.ts
libs/application/types/src/lib/InstitutionTypes.ts

* Rename slug for fjarsyslan since it got changed in Contentful

fix(web): Rename slug for fjarsyslan

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsFooter.tsx
apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsHeader.css.ts
libs/application/types/src/lib/InstitutionTypes.ts

* The slug got changed in Contentful so we need to also change it in the code

feat(web): fjarsyslan slug change

---

apps/services/auth/ids-api/src/app/users/user-identities.controller.ts
libs/auth-api-lib/src/lib/user-identities/user-identities.service.ts

* Add endpoint for updating claims.
* Read claims from master.
* Move useMaster to options object.
Co-authored-by: Valur Einarsson <valure@live.com>
Co-authored-by: Eiríkur Heiðar Nilsson <eirikur@nilsson.is>

feat(auth-api): Add endpoint for updating claims. (#8973)

---

apps/services/auth/ids-api/infra/identity-server.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml

chore(auth): Increasing resources since this seems to be important for Redis performance

---

apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx

[Opna fyrir Norðurland Eystra á S mál.](https://app.asana.com/0/1199153462262248/1203364239710972/f)
Gives the police in north Iceland access to indictments.
Part of pilot program.

chore(j-s): Indictment North Iceland

---

apps/services/auth/ids-api/infra/identity-server.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml

* Increasing resources since this seems to be important for Redis performance
* fixing the generation

chore(auth): Increasing resources since this seems to be important for Redis performance (#9069)

---

infra/src/uber-charts/islandis.ts

chore(infra): disabling search-indexer-service from getting deployed in feature deployments

---

apps/web/utils/richText.tsx
libs/api/domains/mailchimp/src/lib/emailSignup.resolver.ts

chore(web): Encode the URI when subscribing to mailchimp newsletter

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/screens/Organization/SubPage.tsx

This is a cherry-picked commit PR that I got the request to hotfix in. #9035

feat(web): Hotfix - Add custom styles to external links of /s/sjukratryggingar (#9035)

---

libs/application/templates/parental-leave/src/fields/FirstPeriodStart/index.tsx
libs/application/templates/parental-leave/src/forms/EditOrAddPeriods.ts
libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
libs/application/templates/parental-leave/src/lib/answerValidators.ts

* fix(parental-leave): fix validation for periods
* fix(parental-leave): remoe Single parent while it's not out

fix(parental-leave): fix validation for periods (#9085)

---

libs/api/domains/driving-license-book/src/drivingLicenseBook.resolver.ts
libs/api/domains/driving-license-book/src/guards/drivingInstructor.guard.ts
libs/api/domains/driving-license-book/src/guards/drivingSchoolEmployee.guard.ts
libs/application/templates/driving-instructor-registrations/src/fields/FindStudentModal/index.tsx
libs/application/templates/driving-instructor-registrations/src/fields/ViewStudent/index.tsx
libs/application/templates/driving-instructor-registrations/src/graphql/queries.ts
libs/application/templates/driving-instructor-registrations/src/lib/messages.ts
libs/clients/driving-license-book/src/lib/drivingLicenseBookClient.service.ts

fix(driving-license-book): split employee and instructor get and find students for debug purpose

---

libs/application/templates/financial-statements-inao/src/fields/CemetryOverview/index.tsx
libs/application/templates/financial-statements-inao/src/fields/ElectionStatement/index.tsx
libs/application/templates/financial-statements-inao/src/forms/application/application.ts
libs/application/templates/financial-statements-inao/src/forms/application/cemetry/sectionCemetryCaretaker.ts
libs/application/templates/financial-statements-inao/src/lib/messages.ts

alert box before submitting application that signature via email will be required

feat(financial-statement-inao): Add alert info box for signarture

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
libs/application/templates/parental-leave/src/fields/OtherParent/index.tsx
libs/application/templates/parental-leave/src/lib/messages.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

fix(parental-leave): small fixes

---

apps/api/infra/api.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
libs/clients/electronic-registration-statistics/project.json
libs/clients/electronic-registration-statistics/src/clientConfig.json
libs/clients/electronic-registration-statistics/src/lib/electronicRegistrations.config.ts

* The urls for the electronic registration statistics api have changed so we need to update them

chore(web): Change electronic registration statistics api urls 

---

libs/clients/driving-license-book/src/clientConfig.json
libs/clients/driving-license-book/src/lib/drivingLicenseBookClient.service.ts

Filter out students that have expired to fix error on prod.

fix(driving-license-book): filter parameters for expired students

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

fix(parental-leave): fix multiple Births periods rights

---

apps/application-system/api/src/app/modules/application/tools/applicationAccess.service.ts
libs/clients/driving-license-book/src/clientConfig.json
libs/clients/driving-license-book/src/lib/drivingLicenseBookClient.service.ts

Two cherry picks:
- Access for roles to applications
- driving license book update client config and filter parameters for expired students

fix(application-system): Acess for roles and filter parameter in driving license book

---

libs/application/template-api-modules/src/lib/modules/templates/financial-statements-inao/financial-statements-inao.service.ts

Added more logging
Error on dev but not local

feat(financial-statements-inao): Added more logging

---

libs/service-portal/access-control/delegations/src/components/delegations/DelegationsFormFooter.css.ts

fix(service-portal): fix sticky footer shadow in delegations

---

libs/service-portal/access-control/delegations/src/components/delegations/DelegationsFormFooter.tsx
libs/service-portal/access-control/delegations/src/screens/GrantAccess/GrantAccess.tsx

fix(service-portal): Grant access view form footer shadow fix

---

apps/service-portal/src/components/MobileMenu/MobileMenu.css.ts
apps/service-portal/src/components/MobileMenu/MobileMenu.tsx

fix(service-portal): postholf disappearing in mobile menu (#9159)

---

apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFiles/CaseFiles.tsx

[Skjöl sem tilheyra LÖKE númeri birtast á skjánum Dómskjöl undir Önnur gögn](https://app.asana.com/0/1199153462262248/1203362097756767/f)
- Filters case files connected to a police case from other case files.
Verified bug

fix(j-s): Filter Case Files

---

libs/service-portal/vehicles/src/screens/VehicleDetail/VehicleDetail.tsx

Missing link in registration number for vehicle detail

fix(service-portal): empty link

---

libs/application/templates/financial-statements-inao/src/lib/utils/dataSchema.ts

Trying to test signing fsi-application with gervmenn's phonenumbers on dev

fix(financial-statement-inao):  fsi ignore phone validation on dev

---

libs/application/template-api-modules/src/lib/modules/templates/financial-aid/financial-aid.service.ts
libs/application/templates/financial-aid/src/lib/FinancialAidTemplate.ts

Edit "write" permissions in FinancialAidTemplate
Add user type to direct tax payments when creating application

fix(fa): Fix error on submit

---

apps/application-system/api/src/app/modules/application/application.controller.ts
apps/application-system/api/src/app/modules/application/e2e/application.spec.ts

fix(application-system): revert strict mode

---

infra/scripts/Dockerfile

fix(infra): frozen lock typo

---

infra/scripts/Dockerfile
infra/yarn.lock

fix(infra): Upgrade infra scripts yarn to berry

---

infra/package.json
infra/yarn.lock

fix(infra): Updated deprecated typescript in infra

---

apps/judicial-system/web/src/routes/Court/Indictments/CourtRecord/CourtRecord.tsx

[Asana](https://app.asana.com/0/1199153462262248/1203432668699958/f)
Route to closedIndictment route instead of cases route when an indictment is closed
That's what we do in R-cases

chore(j-s): Change routing when an indictment is closed

---

libs/application/templates/parental-leave/src/lib/answerValidators.ts

fix(parental-leave): add more check for request rights

---

libs/application/templates/parental-leave/src/dataProviders/Children/Children-utils.spec.ts
libs/application/templates/parental-leave/src/fields/FirstPeriodStart/index.tsx
libs/application/templates/parental-leave/src/fields/Review/Review.tsx
libs/application/templates/parental-leave/src/forms/EditOrAddPeriods.ts
libs/application/templates/parental-leave/src/forms/EmployerApproval.ts
libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
libs/application/templates/parental-leave/src/lib/answerValidators.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

fix(parental leave): request rights and start date

---

libs/api/domains/assets/src/models/propertyDetail.model.spec.ts
libs/api/domains/assets/src/models/propertyDetail.model.ts

hotfix: https://github.com/island-is/island.is/pull/9213

fix(service-portal): Hotfix - update filter asseets detail model (#9213)

---

apps/web/components/Organization/Slice/PowerBiSlice/PowerBiSlice.tsx
apps/web/components/connected/fiskistofa/SidebarShipSearchInput/SidebarShipSearchInput.tsx
apps/web/screens/ServiceWeb/Home/Home.tsx

This is PR contains a cherry picked commit from PR #9209 that's been merged to main

fix(web): Hotfix - Add fail safe to service web and fix initial powerbislice state (#9209)

---

libs/api/domains/assets/src/models/propertyDetail.model.spec.ts
libs/api/domains/assets/src/models/propertyDetail.model.ts

hotfix: https://github.com/island-is/island.is/pull/9213

fix(service-portal): hotfix - assets filter fix

---

.github/CODEOWNERS

Update path of delegations module in codeowners.
We refactored the module and moved it to new location so the path has updated.

fix(core): Update delegations module codeowner

---

apps/judicial-system/backend/src/app/modules/case/case.controller.ts
apps/judicial-system/backend/src/app/modules/case/case.service.ts
apps/judicial-system/backend/src/app/modules/case/test/caseController/create.spec.ts
apps/judicial-system/backend/src/app/modules/case/test/caseController/createCourtCase.spec.ts
apps/judicial-system/backend/src/app/modules/case/test/caseController/getCourtRecordSignatureConfirmation.spec.ts
apps/judicial-system/backend/src/app/modules/case/test/caseController/getRulingSignatureConfirmation.spec.ts
apps/judicial-system/backend/src/app/modules/case/test/caseController/transition.spec.ts
apps/judicial-system/backend/src/app/modules/case/test/caseController/update.spec.ts
apps/judicial-system/backend/src/app/modules/court/test/createCourtCase.spec.ts
apps/judicial-system/backend/src/app/modules/file/file.service.ts

[Eyða og breyta gögnum þegar LÖKE nr er eytt](https://app.asana.com/0/1199153462262248/1203372256206928/f)
- Updates police case numbers of case files when a police case number is modified.
- Delete case files when a police case number is removed.
- Better usability.

feat(j-s): Police Case Number Updates

---

apps/judicial-system/backend/src/app/modules/event/event.service.ts

[Asana](https://app.asana.com/0/1199153462262248/1203434593461517/f)
Show indictment subtype on Slack feed
Provides clarity for the team

chore(j-s): Show indictment subtype on Slack feed

---

apps/judicial-system/web/src/components/InfoCard/InfoCard.css.ts
apps/judicial-system/web/src/components/InfoCard/InfoCard.tsx
apps/judicial-system/web/src/components/InfoCard/InfoCardClosedIndictment.tsx

[Asana](https://app.asana.com/0/1199153462262248/1203457980631344/f)
Use css grid in InfoCard instead of flexbox.
Css grid gives us a better way of controlling the gap between rows and columns

chore(j-s): InfoCard grid

---

libs/application/templates/financial-statements-inao/src/fields/Shared/CapitalNumberOverview.tsx

remove "Lykiltölur" from overview section heading

fix(financial-statement-inao): fsi overview headings

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.spec.ts
libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.spec.ts
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts

fix(parental-leave): sync rightCodePeriod from VMST to island.is

---

libs/application/templates/driving-school-confirmation/src/fields/ConfirmationDate/index.tsx

- Set default date in date picker to today
- Set default date to yesterday if filling out it the morning

fix(driving-licence): Set default date

---

apps/application-system/form/infra/application-system-form.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

fix(parental-leave): Move VMST_ID from secrets to env

---

apps/web/components/ChatPanel/WatsonChatPanel/WatsonChatPanel.tsx
apps/web/components/ChatPanel/types.ts

This PR contains a cherry picked commit that got merged to main (https://github.com/island-is/island.is/pull/9279)

feat(web):  Hotfix - allow cms to change chat panel css variables

---

apps/application-system/api/src/app/modules/application/e2e/applicationAccess.spec.ts
apps/application-system/api/src/app/modules/application/tools/applicationAccess.service.ts

Cant use array.some() this way asynchronously switched to a simple for loop. Added some tests for this.

fix(application-system): Feature flag delegation async fix 

---

apps/auth-admin-web/utils/validation.utils.ts

Make prefix validation regexes more consistent.
We need to create a new domain in staging/prod before the release tomorrow which includes new client and scope migrations which depend on these domains.

fix(auth): HOTFIX Allow subdomains in domain names (#9255)

---

infra/src/feature-env.ts

fix(mocks): no-mocks by default in feature-envs

---

libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
libs/service-portal/documents/src/screens/Overview/Overview.tsx

fix(service-portal): hotfix - document line flash (#9322)

---

libs/portals/shared-modules/delegations/src/components/delegations/outgoing/DelegationsOutgoing.tsx

fix(portals-delegations): Fix unnecessary fetches loading flickering

---

libs/auth-api-lib/seeders/data/scope-ads-admin.ts

The dev machine client breaks migrations in staging and production as it is only defined in dev.
To unblock the migration.

fix(auth-lib): Remove dev machine client for ADS scope definition.

---

libs/auth-api-lib/seeders/data/scope-ads-admin.ts

Applying hotfix #9340 to release
To fix startup when dev client does not exist.

fix(auth-lib): Fix auth ADS scope seed

---

libs/service-portal/graphql/src/hooks/passport/useChildrenPassport.ts
libs/service-portal/graphql/src/hooks/passport/usePassport.ts
libs/service-portal/licenses/src/screens/LicensesOverview/index.tsx
libs/service-portal/licenses/src/screens/PassportDetail/PassportDetail.tsx

fix(service-portal): change ff for passport (#9341)

---

libs/application/templates/parental-leave/src/fields/SelfEmployed/index.tsx

Fix self employed validation
Error message didn't show when applicant tried to go forward without answering isSelfEmployed question

fix(parental leave): fix self employed validation

---

apps/system-e2e/global.d.ts
infra/package.json
infra/src/cli/render-secrets.ts
infra/src/cli/render-urls.ts
infra/src/dsl/egress.spec.ts
infra/src/dsl/exports/helm.ts
infra/src/dsl/kubernetes-runtime.ts
infra/src/dsl/types/output-types.ts
infra/src/dsl/value-files-generators/local-setup.spec.ts
infra/src/dsl/value-files-generators/local-setup.ts
infra/src/dsl/xroad.ts
infra/src/feature-env.ts
infra/src/secrets.ts
package.json

Making feature deployments with mocks an explicit option. Massaging the local environment generation.

chore: Making feature-deployment with mocks an explicit decision

---

apps/web/components/SearchInput/SearchInput.tsx

fix(web): Hotfix - prevent 500 error if search result does not contain slug field

---

libs/application/templates/parental-leave/src/fields/SelfEmployed/index.tsx
libs/application/templates/parental-leave/src/hooks/useLazyQuery.ts
libs/application/templates/parental-leave/src/lib/dataSchema.ts

Fix verification for the national id of the employer
Add a validation for an employer national id and make sure it is a valid company.
Because only valid companies should be able to approve as an employer.

fix(parental leave): verification for the national id of the employer

---

apps/judicial-system/web/src/components/Logo/Logo.css.ts
apps/judicial-system/web/src/components/Logo/Logo.tsx
apps/judicial-system/web/src/routes/Shared/Cases/ActiveCases.tsx
apps/judicial-system/web/src/routes/Shared/Cases/Cases.css.ts
apps/judicial-system/web/src/routes/Shared/Cases/Cases.strings.ts
apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx
apps/judicial-system/web/src/routes/Shared/Cases/useFilter.spec.tsx
apps/judicial-system/web/src/routes/Shared/Cases/useFilter.strings.ts
apps/judicial-system/web/src/routes/Shared/Cases/useFilter.tsx
apps/judicial-system/web/src/utils/mutations.ts

[Asana - Filtering á R-mál eða S-mál eingöngu](https://app.asana.com/0/1199153462262248/1202978837144066/f)
- Add filter select option for Cases screen
- Filter syncs with `localstorage`
- Refactor `CreateCaseButton` to its own component
- Added state to conditionally render the `Confirm delete` button because otherwise, it shows when applying filters

feat(j-s): filter-cases

---

apps/web/screens/queries/fragments.ts
libs/cms/src/lib/search/importers/organizationSubpage.service.ts

feat(web): Hotfix - fetch nested fields inside one column text (#9366)

---

apps/service-portal/src/app/App.tsx

fix(service-portal): Fix module provider error

---

libs/portals/core/src/screens/Modules.tsx

feat(admin-portal): Show access denied if user has no modules

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsHeader.css.ts
apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsHeader.tsx

* This was requested by Fjársýslan
https://user-images.githubusercontent.com/43557895/208642792-90e774ad-a867-42e7-afb4-8404fa2f929d.mov

feat(web): Change header image for /s/fjarsyslan

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsHeader.css.ts
apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsHeader.tsx

feat(web): Hotfix - Change header image for /s/fjarsyslan (#9389)

---

libs/application/template-api-modules/src/lib/modules/templates/financial-statements-inao/financial-statements-inao.service.ts

Update actors name
Was using clients name

feat(financial-statements-inao): Update actors name

---

libs/application/templates/parental-leave/src/fields/PeriodsRepeater/index.tsx
libs/application/templates/parental-leave/src/lib/answerValidator-utils.ts

* fix(parental-leave): fix rights calculator
* fix(parental-leave): fix firstPeriodStart value

fix(parental-leave): hotfix rights calculator (#9397)

---

libs/plausible/src/lib/servicePortalEvents.ts

https://github.com/island-is/island.is/pull/9379

fix(service-portal): Update param for outbound service-portal link

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsHeader.css.ts
apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsHeader.tsx

* The header seems to get pushed down during a route change so this change will make it stick in the right place

fix(web): Add Gridcontainer to header of Fjársýslan

---

apps/judicial-system/backend/src/app/modules/defendant/defendant.service.ts
apps/judicial-system/backend/src/app/modules/defendant/test/internalDefendantController/deliverDefendantToCourt.spec.ts

[Skila gögnum um varnaraðila við móttöku máls í Auði](https://app.asana.com/0/1199153462262248/1203337868753454/f)
- Blocks email to court when defendant cannot be updated.
- The court is not ready to receive the email.

fix(j-s): Block Update Failed Email to Court

---

apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsHeader.css.ts
apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsHeader.tsx

(#9407)
This PR contains a cherry picked commit from main we'd like to hotfix in since the issue is still on the prod web.

fix(web): Remove Box component from Fjársýslan header  (#9407)

---

libs/service-portal/graphql/src/hooks/passport/useChildrenPassport.ts
libs/service-portal/licenses/src/components/LicenseCards/LicenseCards.tsx
libs/service-portal/licenses/src/screens/LicensesOverview/ChildrenLicenses.tsx
libs/service-portal/licenses/src/screens/PassportDetail/PassportDetail.tsx
libs/service-portal/licenses/src/utils/capitalize.ts

* Update name display for passports
* Improve user friendliness

feat(service-portal): Update passport name display

---

libs/api/domains/passport/src/lib/models/identityDocumentModelChild.model.ts
libs/api/domains/passport/src/lib/passport.service.ts
libs/clients/passports/src/clientConfig.yaml
libs/service-portal/graphql/src/hooks/passport/useChildrenPassport.ts
libs/service-portal/licenses/src/components/LicenseCards/LicenseCards.tsx
libs/service-portal/licenses/src/components/SingleLicenseCard/SingleLicenseCard.tsx
libs/service-portal/licenses/src/index.ts
libs/service-portal/licenses/src/lib/constants.ts
libs/service-portal/licenses/src/lib/messages.ts
libs/service-portal/licenses/src/screens/LicensesOverview/ChildrenLicenses.tsx
libs/service-portal/licenses/src/screens/LicensesOverview/UserLicenses.tsx
libs/service-portal/licenses/src/screens/LicensesOverview/index.tsx
libs/service-portal/licenses/src/screens/PassportDetail/PassportDetail.tsx
libs/service-portal/licenses/src/utils/capitalize.ts

Hotfix:
https://github.com/island-is/island.is/pull/9355
https://github.com/island-is/island.is/pull/9416
.. Plus add child name. Has been [added to main](https://github.com/island-is/island.is/pull/9261/files#diff-886143833ef4812d02fab37d26fffeaf0c7866c374fddf21f4f6bb5eff81464cR139) along with multiple other changes to the passport service. I only [selected](https://github.com/island-is/island.is/pull/9418/commits/5345d7dacd003fd610aef6685452bed7c4b4ac58) the `childName` change for this hotfix.

fix(service-portal): hotfix - passport view fixes and minor additions

---

libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

fix(parental-leave): could not delete period in start in next month

---

libs/application/templates/estate/src/forms/EstateWithNoProperty/externalDataFields/estateMembersFields.ts
libs/application/templates/estate/src/forms/EstateWithNoProperty/externalDataFields/propertiesFields.ts
libs/application/templates/estate/src/forms/EstateWithNoProperty/form.ts
libs/application/templates/estate/src/lib/dataSchema.ts
libs/application/templates/estate/src/lib/messages.ts

fix(estate): nonempty checkbox for accepting debts

---

libs/application/templates/passport/src/forms/ParentB.ts
libs/application/templates/passport/src/lib/PassportTemplate.ts

fix(passport-application): Remove mock provider for identityDocument

---

apps/air-discount-scheme/backend/docker-compose.yml
apps/application-system/api/docker-compose.yml
apps/github-actions-cache/docker-compose.yml

chore(infra): update deprecated redis docker manifests

---

apps/application-system/api/infra/application-system-api.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

fix(infra): fixed missing values in charts

---

apps/application-system/api/infra/application-system-api.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

fix(infra): add more missing envs to application system api

---

libs/service-portal/licenses/src/index.ts
libs/service-portal/licenses/src/screens/PassportDetail/PassportDetail.tsx

https://github.com/island-is/island.is/pull/9443

fix(service-portal): hotfix - Update feature flag passport detail

---

apps/api/esbuild.json

* The deployment pipeline for both dev and staging have stopped working due to this issue
* Context: https://islandis.slack.com/archives/C019LNRM6LE/p1672156295238449

fix(api): Update esbuild.json so it includes pdfkit 

---

apps/judicial-system/web/src/components/FormProvider/FormProvider.tsx

[Asana](https://app.asana.com/0/1199153462262248/1203532045215680/f)
Fix a console warning about an uncontrolled input being changed to a controlled input when "noNationalId" checkbox was checked.
Better DX

chore(j-s): Fix console warning

---

apps/services/auth/delegation-api/src/environments/environment.ts

Add missing @ symbol in `@island.is` audience.
To unblock service portal.

fix(delegation-api): Fix audience regression

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.spec.ts
libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
libs/application/templates/parental-leave/src/index.ts

* fix(parental-leave): Percentage vs endDate issue
* fix(parental-leave): Using D{days} everywhere which ratio is not 100 percent
* fix(parental-leave): fix unitest
Fix percentage and endDate issue which are not comparable calculated with VMST

fix(parental leave): percentage end date issue (#9469)

---

handbook/technical-overview/technical-direction.md
libs/financial-aid/shared/src/lib/taxCalculator.spec.ts
libs/financial-aid/shared/src/lib/taxCalculator.ts

- New year needs to update tax percentage and tax allowance
- Updated test from new years tax allowance 
- added new year for the future, better to change number than

fix(fa): Updating personal tax allowance

---

libs/financial-aid/shared/src/lib/taxCalculator.spec.ts
libs/financial-aid/shared/src/lib/taxCalculator.ts

Hotfix cherry picked from: https://github.com/island-is/island.is/pull/9479

fix(financial-aid): Hotfix tax calculation

---

apps/air-discount-scheme/backend/src/app/modules/discount/discount.controller.ts
libs/air-discount-scheme/types/src/lib/user.ts

fix(ads): Hotfix ads legacy gender

---

libs/application/templates/driving-instructor-registrations/src/fields/FindStudentModal/index.tsx
libs/application/templates/driving-instructor-registrations/src/fields/StudentsOverview/Skeleton.tsx
libs/application/templates/driving-instructor-registrations/src/fields/StudentsOverview/index.tsx
libs/application/templates/driving-instructor-registrations/src/fields/ViewStudent/Skeleton.tsx
libs/application/templates/driving-instructor-registrations/src/fields/ViewStudent/index.tsx
libs/application/templates/driving-instructor-registrations/src/fields/style.css.ts
libs/application/templates/driving-instructor-registrations/src/lib/messages.ts
libs/application/templates/marriage-conditions/src/dataProviders/NationalRegistryMaritalStatusProvider.ts

fix(marriage-conditions-template): Driving registration and marriage conditions

---

apps/service-portal/src/lib/modules.ts

fix(service-portal): Delegations module was missing in modules

---

libs/application/templates/marriage-conditions/src/dataProviders/NationalRegistryMaritalStatusProvider.ts

fix(marriage-conditions): for testing (#9535)

---

libs/application/data-providers/src/providers/UserProfileProvider.ts
libs/application/templates/public-debt-payment-plan/src/dataProviders/paymentPlanPrerequisites.ts
libs/application/templates/public-debt-payment-plan/src/forms/PrerequisitesForm.ts
libs/clients/payment-schedule/src/lib/payment-schedule-client.module.ts

chore(pdpp): Remove area code from phone number and CIT-return condtion

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts

Prevent sending SMS to none GSM phoneNumber

fix(parental-leave): prevent sending sms to non GSM phoneNumber

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts

Prevent sending SMS to none GSM phoneNumber
Keep application in correct state even sending SMS got error

fix(parental leave): sms issues

---

apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFiles/CaseFiles.tsx

[Taka út þingbók tekur líka út dóm](https://app.asana.com/0/1199153462262248/1203669009319256/f)
Only remove the case file that was deleted.
The bug made it seem as if multiple files were being deleted, but only one was truly being deleted. 
https://user-images.githubusercontent.com/4820859/211867147-96431f8c-9a83-4c02-947c-bccd2456831e.mov
https://user-images.githubusercontent.com/4820859/211863633-396a3228-2c4d-4d3c-854d-1fca28ee9fe8.mov

fix(j-s): Remove case files

---

apps/application-system/api/src/app/modules/application/tools/application.serializer.ts
libs/application/templates/reference-template/src/lib/ReferenceApplicationTemplate.ts
libs/application/templates/reference-template/src/lib/messages.ts
libs/application/types/src/lib/ApplicationTemplate.ts

Made it so you can add value to your message in template name field.
So that you can have value in a translatable text.

feat(application-system): Update template name

---

apps/services/auth/ids-api/src/app/delegations/delegations.controller.ts
apps/services/auth/public-api/src/app/modules/delegations/actorDelegations.controller.ts
libs/auth-api-lib/src/lib/delegations/delegations-incoming.service.ts

Add an optional parameter with requested scopes to get available delegations.
So we can show only those delegations that are available to the client.

feat(auth): Enable filtering delegations with requested scopes

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.ts

feat(parental-leave): Add sendAdditionalDocuments function and refactor

---

apps/judicial-system/web/src/routes/Court/Indictments/CourtRecord/CourtRecord.tsx

Fixed in one place but overlooked another place where the same bug was located
Fix bug for file deletion
Bugfix

fix(j-s): Remove case files again

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
libs/application/templates/parental-leave/src/constants.ts
libs/application/templates/parental-leave/src/forms/UploadAdditionalFiles.ts
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
libs/application/templates/parental-leave/src/lib/messages.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
libs/application/templates/parental-leave/src/types.ts

Added screen for upload

---

apps/system-e2e/src/support/login.ts

fix(system-e2e): number of national IDs for admin mage

---

libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.spec.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

- [  ] I have made corresponding changes to the documentation
- [  ] I have rebased against main before asking for a review

fix(parental-leave): Fixed unittest and allowOtherParentToUsePersonalAllowance

---

libs/infra-nest-server/src/lib/bootstrap.ts
libs/infra-nest-server/src/lib/testServer.ts
libs/testing/nest/src/lib/testServer.ts

fix(core): HOTFIX Revert forbidUnknownValues

---

apps/judicial-system/backend/src/app/modules/case/case.service.ts

[Málsgögnum hlaðið oft í Auði](https://app.asana.com/0/1199153462262248/1203754459187640/f)
- Fixes case file reset on court case number change.
- Case files where uploaded multiple times to court.

fix(j-s): Case File Reset

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/Themes/LandlaeknirTheme/LandlaeknirFooter.css.ts
apps/web/components/Organization/Wrapper/Themes/LandlaeknirTheme/LandlaeknirFooter.tsx
apps/web/components/Organization/Wrapper/Themes/LandlaeknirTheme/LandlaeknirHeader.css.ts
apps/web/components/Organization/Wrapper/Themes/LandlaeknirTheme/LandlaeknirHeader.tsx

This is a PR containing a cherry picked commit from main
* Change header
* Change footer
* Use constants for image urls
* Close unclosed string

feat(web): Change header and footer for Directorate of Health (#9604)

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts

feat(parental-leave): Refactor sendApplication

---

libs/application/templates/reference-template/src/dataProviders/index.ts
libs/application/templates/reference-template/src/forms/Prerequisites.ts
libs/application/templates/reference-template/src/lib/ReferenceApplicationTemplate.ts
libs/application/types/src/lib/template-api/TemplateApi.ts

Configure uses cloning.
Configure was configuring the instance in place. Was causing problems.

fix(application-system): clone object during configure

---

libs/application/templates/public-debt-payment-plan/src/fields/Overview/Overview.tsx

change reference to identity for overview
names where not appearing in overview

fix(pdpp): change reference to identity for overview

---

libs/application/templates/transport-authority/digital-tachograph-drivers-card/src/lib/messages/applicant.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/ApplicationStatus/StatusStep/index.tsx
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/ApplicationStatus/index.tsx
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/index.tsx
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/sections/BuyerSection.tsx
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/sections/InsuranceSection.tsx
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/VehiclesField/VehicleRadioField.tsx
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/VehiclesField/VehicleSelectField.tsx
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/messages/error.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/types/index.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/getApproveAnswers.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/getReviewSteps.ts

Same as this --> https://github.com/island-is/island.is/pull/9653

fix(transfer of vehicle ownership): hotfix

---

apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Defendant/Defendant.tsx

[Asana](https://app.asana.com/0/1199153462262248/1203702889407350/f)
Allow defender registration on case type ELECTRONIC_DATA_DISCOVERY_INVESTIGATION
This is from feedback from our users

feat: ELECTRONIC_DATA_DISCOVERY_INVESTIGATION defender registration

---

apps/air-discount-scheme/backend/infra/backend.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

infra: Grant graphql api access to air-discount-scheme-backend (#9669)

---

libs/application/templates/parental-leave/src/fields/Duration/Duration.tsx
libs/application/templates/parental-leave/src/fields/FirstPeriodStart/index.tsx
libs/application/templates/parental-leave/src/fields/PeriodPercentage/PeriodPercentage.tsx
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

StartDate should be in the beginning of month of expected date of birth

fix(parental-leave): Fix StartDate for Parental Grant

---

libs/application/template-api-modules/src/lib/modules/templates/public-debt-payment-plan/paymentPlanPrerequisites.service.ts

fix(pdpp): Fallback to nodebts error

---

apps/web/components/ServiceWeb/Background/Background.tsx
apps/web/components/ServiceWeb/Background/Variations/Mannaudstorg/Mannaudstorg.css.ts
apps/web/components/ServiceWeb/Background/Variations/Mannaudstorg/Mannaudstorg.tsx
apps/web/components/ServiceWeb/Background/Variations/Sjukratryggingar/Sjukratryggingar.css.ts
apps/web/components/ServiceWeb/Background/Variations/Sjukratryggingar/Sjukratryggingar.tsx
apps/web/components/ServiceWeb/Header/Header.tsx
apps/web/components/ServiceWeb/SearchSection/SearchSection.tsx
apps/web/components/ServiceWeb/Wrapper/Wrapper.tsx
apps/web/components/ServiceWeb/config.ts
apps/web/components/ServiceWeb/types.ts
apps/web/screens/ServiceWeb/Home/Home.tsx
apps/web/screens/ServiceWeb/SubPage/SubPage.tsx

* Enable service web for Icelandic Health Insurance organization
* Add header image and change color scheme for the service web

feat(web): Icelandic Health Insurance - service web

---

libs/application/core/src/lib/messages.ts
libs/application/template-api-modules/src/lib/modules/shared/api/identity/identity.service.ts
libs/application/template-api-modules/src/lib/modules/shared/api/national-registry/national-registry.service.ts
libs/application/template-api-modules/src/lib/modules/templates/general-fishing-license/general-fishing-license.service.ts
libs/application/templates/general-fishing-license/src/index.ts
libs/application/templates/general-fishing-license/src/lib/messages/error.ts

Stop application process if data is missing for nationalid and the get ships providers.

fix(application-system): Application Barriers if data is null

---

libs/application/core/src/lib/messages.ts
libs/application/template-api-modules/src/lib/modules/shared/api/identity/identity.service.ts
libs/application/template-api-modules/src/lib/modules/shared/api/national-registry/national-registry.service.ts
libs/application/template-api-modules/src/lib/modules/templates/general-fishing-license/general-fishing-license.service.ts
libs/application/templates/general-fishing-license/src/index.ts
libs/application/templates/general-fishing-license/src/lib/messages/error.ts

Stop application process if data is missing for national registry and the get ships providers.

fix(application-system): Error reasons for national registry and get ships

---

apps/air-discount-scheme/web/infra/web.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

Hotfix release with #9685 
To fix ADS web

fix(ads): Add nginx-ingress-external to air discount scheme web.

---

apps/air-discount-scheme/backend/infra/backend.ts
apps/air-discount-scheme/web/infra/web.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

Hotfix #9690 
Release hotfix for #9690

fix(ads): ADS infra udpate to add islandis

---

apps/web/components/Organization/Slice/SliceMachine.tsx
apps/web/components/connected/fiskistofa/ShipSearchBoxedInput/ShipSearchBoxedInput.tsx
apps/web/components/connected/fiskistofa/index.ts
apps/web/utils/richText.tsx
libs/cms/src/lib/generated/contentfulTypes.d.ts

This PR contains a cherry picked commit from main
* Add new component
* Style search input

feat(web): Hotfix - Ship search component for directorate of fisheries organization pages (#9671)

---

libs/application/template-api-modules/src/lib/modules/templates/european-health-insurance-card/dto/european-health-insurance-card.dtos.ts
libs/application/template-api-modules/src/lib/modules/templates/european-health-insurance-card/european-health-insurance-card.service.ts
libs/application/templates/european-health-insurance-card/src/dataProviders/index.ts

feat(ehic-ds): Add dummy service

---

libs/application/templates/driving-license/src/dataProviders/index.ts
libs/application/templates/driving-license/src/forms/prerequisites/sectionExternalData.ts
libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts

fix(driving-license-application): Payment provider

---

libs/application/templates/parental-leave/src/lib/dataSchema.ts

Validate phone numbers when applicant is putting in the numbers to only be GSM numbers not landline numbers. 

fix(parental-leave): Validate phone numbers

---

apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx

[Opna ákærur fyrir LRH og Héraðsdóm í Reykjavík](https://app.asana.com/0/1199153462262248/1203751921773235/f)
- Gives the Reykjavik police access to indictments.
- They will take part in a pilot.

feat(j-s): Indictments for Reykjavik

---

libs/portals/shared-modules/delegations/src/components/delegations/outgoing/DelegationsOutgoing.tsx

fix(portals): Hot fix for outgoing delegations rendering

---

libs/application/templates/european-health-insurance-card/src/fields/Applicants/Applicants.tsx
libs/application/templates/european-health-insurance-card/src/fields/Temp/Temp.tsx
libs/application/templates/european-health-insurance-card/src/fields/externalDataSection.ts
libs/application/templates/european-health-insurance-card/src/forms/european-health-insurance-card.tsx
libs/application/templates/european-health-insurance-card/src/lib/types/index.ts

steps update

---

package.json
yarn.lock

* deploy feature trigger
* Revert "deploy feature trigger"
This reverts commit e29cb2d8a2510a238482e750c549d9fdbc9246b7.
* added lodash
* added lodash
* installed lodash
* added firebase dep
* added firebase dep
* added lodash.includes
* cleanup
* cleanup
* fixed latest firebase
* removing lodash as it is included in latest firebase
* yarn install

fix(user-notifications): Add missing dep to esbuild (#9722)

---

libs/application/template-api-modules/src/lib/modules/templates/operating-license/operatingLicense.service.ts
libs/application/template-api-modules/src/lib/modules/templates/operating-license/types/attachments.ts

fix(operating-license): Criminal record validate and submit (#9727)

---

apps/judicial-system/backend/src/app/modules/case/case.service.ts
apps/judicial-system/backend/src/app/modules/case/test/caseController/getRulingSignatureConfirmation.spec.ts

[Ekki uppfæra framlengd mál í LÖKE](https://app.asana.com/0/1199153462262248/1203770935391899/f)
- No longer attempts to update extended LÖKE cases as the extended case does not exist in LOKE.
- Extended cases cannot be updated in LÖKE.

fix(j-s): Extended LOKE Cases

---

libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.spec.ts
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts

fix(parental-leave): clean up VMST ID on un-nessary states

---

libs/application/templates/parental-leave/src/lib/messages.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.spec.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

Fixing question for no primary parent in iceland application.

fix(parenteal-leave): no primary parent questions fixes

---

apps/application-system/api/src/app/modules/application/application.controller.ts
libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification.service.ts
libs/application/template-api-modules/src/lib/modules/templates/complaints-to-althingi-ombudsman/complaints-to-althingi-ombudsman.service.ts
libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/data-protection-complaint.service.ts
libs/application/template-api-modules/src/lib/modules/templates/health-insurance/bucket/bucket.service.ts
libs/application/template-api-modules/src/lib/modules/templates/health-insurance/health-insurance.utils.ts

Remove redundant error logging 
Was causing some noise in the logs. All errors from the template apis are being caught. Some of these errors are being logged multiple times.

chore(application-system): Cleaning up error logging noise

---

apps/judicial-system/backend/src/app/modules/case/internalCase.controller.ts
apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverCaseFilesRecordToCourtGuards.spec.ts
apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverCaseToPoliceGuards.spec.ts
apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverCourtRecordToCourtGuards.spec.ts
apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverRequestToCourtGuards.spec.ts
apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverSignedRulingToCourtGuards.spec.ts
apps/judicial-system/backend/src/app/modules/court/court.service.ts
apps/judicial-system/backend/src/app/modules/file/file.module.ts
apps/judicial-system/backend/src/app/modules/file/internalFile.controller.ts
apps/judicial-system/backend/src/app/modules/file/test/internalFileController/deliverCaseFileToCourtGuards.spec.ts
apps/judicial-system/backend/src/app/modules/notification/internalNotification.controller.ts
apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/internalNotificationControllerGuards.spec.ts
apps/judicial-system/backend/src/app/modules/police/police.service.ts

[Setja MODIFIED tilkynningar á biðröð](https://app.asana.com/0/1199153462262248/1203640056170090/f)
- Adds `UserExistsGuard` in a number of methods in various controllers.
- Verified bug. Without the guard, the user may will not be defined.

fix(j-s): Missing User Exists Guards

---

libs/application/templates/operating-license/src/lib/messages.ts

fix(operating-license-template): message fixes

---

apps/web/components/Organization/Wrapper/config.ts

feat(web): Add web chat to HSU organization page

---

libs/application/templates/mortgage-certificate/src/lib/mortgageCertificateTemplate.ts

fix(mortgage certificate): ready for production

---

libs/application/template-api-modules/src/lib/modules/templates/mortgage-certificate-submission/emailGenerators/syslumennNotifyError.ts
libs/application/template-api-modules/src/lib/modules/templates/mortgage-certificate-submission/emailGenerators/syslumennSubmitRequestError.ts
libs/application/template-api-modules/src/lib/modules/templates/mortgage-certificate-submission/mortgage-certificate-submission.service.ts
libs/application/template-api-modules/src/lib/modules/templates/mortgage-certificate-submission/types/index.ts
libs/application/templates/mortgage-certificate/src/dataProviders/index.ts
libs/application/templates/mortgage-certificate/src/forms/MortgageCertificateForm.ts
libs/application/templates/mortgage-certificate/src/lib/mortgageCertificateTemplate.ts
libs/application/templates/no-debt-certificate/src/dataProviders/index.ts

fix(mortgage certificate): delegation fix

---

libs/application/templates/no-debt-certificate/src/dataProviders/index.ts
libs/application/templates/no-debt-certificate/src/forms/NoDebtCertificateForm.ts
libs/application/templates/no-debt-certificate/src/lib/messages.ts
libs/application/templates/no-debt-certificate/src/lib/noDebtCertificateTemplate.ts
libs/application/templates/transport-authority/change-operator-of-vehicle/src/dataProviders/index.ts
libs/application/templates/transport-authority/change-operator-of-vehicle/src/forms/ChangeOperatorOfVehicleForm/InformationSection/ownerSubSection.ts
libs/application/templates/transport-authority/change-operator-of-vehicle/src/forms/ChangeOperatorOfVehicleForm/externalDataSection.ts
libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/ChangeOperatorOfVehicleTemplate.ts
libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/messages/externalData.ts
libs/application/templates/transport-authority/order-vehicle-license-plate/src/dataProviders/index.ts
libs/application/templates/transport-authority/order-vehicle-license-plate/src/forms/OrderVehicleLicensePlateForm/prerequisitesSection.ts
libs/application/templates/transport-authority/order-vehicle-license-plate/src/lib/OrderVehicleLicensePlateTemplate.ts
libs/application/templates/transport-authority/order-vehicle-license-plate/src/lib/messages/externalData.ts
libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/dataProviders/index.ts
libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/forms/OrderVehicleRegistrationCertificateForm/InformationSection/vehicleSubSection.ts
libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/forms/OrderVehicleRegistrationCertificateForm/prerequisitesSection.ts
libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/lib/OrderVehicleRegistrationCertificateTemplate.ts
libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/lib/messages/externalData.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/dataProviders/index.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/forms/TransferOfVehicleOwnershipForm/InformationSection/sellerSubSection.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/forms/TransferOfVehicleOwnershipForm/prerequisitesSection.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/TransferOfVehicleOwnershipTemplate.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/messages/externalData.ts

fix(transport authority): delegation fix

---

apps/judicial-system/api/src/app/modules/indictment-count/dto/updateIndictmentCount.input.ts
apps/judicial-system/api/src/app/modules/indictment-count/models/indictmentCount.model.ts
apps/judicial-system/backend/migrations/20230202164320-update-indictment-count.js
apps/judicial-system/backend/src/app/modules/indictment-count/dto/updateIndictmentCount.dto.ts
apps/judicial-system/backend/src/app/modules/indictment-count/models/indictmentCount.model.ts

[Bæta skráningarnúmeri við gagnagrunn, bakenda og api](https://app.asana.com/0/0/1203868281525958/f)
- Adds three new field to indictment count.
- Part of traffic violations.

feat(j-s): Indictment Count Fields

---

apps/services/auth/ids-api/infra/identity-server.ts
apps/services/sessions/infra/sessions.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml
charts/islandis/values.dev.yaml

feat(sessions): Configure session url for ids.

---

apps/judicial-system/backend/src/app/modules/notification/notification.service.ts

[Sleppa að senda leiðréttan vistunarseðil fyrir vistun á viðeigandi stofnun](https://app.asana.com/0/1199153462262248/1203676748219384/f)
- When the custody end time is modified, a custody notice is sent to the prison only if the defendant is already in active custody or does not have an Icelandic national id.
- The prison does not need the custody notice except in these cases.

fix(j-s): Modified Notifications

---

apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.controller.ts
apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getByIdGuards.spec.ts
apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getCourtRecordPdfGuards.spec.ts
apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getRequestPdfGuards.spec.ts
apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getRulingPdfGuards.spec.ts
apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationCases/overview.spec.ts
apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/overview.spec.ts
apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Prosecutor/components/CopyLinkForDefenderButton/CopyLinkForDefenderButton.tsx
libs/judicial-system/auth/src/lib/guards/auth.guard.ts

[Fela "afrita hlekk fyrir verjendur" hjá sækjanda þar til fyrirtöku tími hefur verið boðaður](https://app.asana.com/0/1199153462262248/1203844632938806/f)
- Disables the button "Afrita hlekk fyrir verjanda" until the case has been scheduled by the court.
- The defender will not have access until the case has been scheduled.

fix(j-s): Defender Link

---

apps/services/sessions/project.json

Add missing assets required to run migrations in the container.
To fix initContainer and worker startup.

fix(sessions): Add missing db migrations assets to project.json.

---

apps/services/sessions/esbuild.json

Add `bull` module as external in esbuild.
To fix queue errors in the worker.

fix(sessions): Add bull module as external in esbuild.json

---

apps/services/sessions/infra/sessions.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

fix: removing keepalive from sessions worker

---

apps/services/sessions/README.md
apps/services/sessions/infra/sessions.ts
apps/services/sessions/project.json
apps/services/sessions/src/app/worker/worker.ts
apps/services/sessions/src/main.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

fix: sessions worker missing startup config

---

libs/application/templates/marriage-conditions/src/forms/sharedSections/dataCollection.ts

fix(marriage-conditions): remove duplicate data provider text (#9868)

---

libs/application/templates/financial-statements-inao/src/fields/CemetryOperation/cemetryExpenses.tsx

fix(financial-statement-inao):  prevent refetching of cemetery donations

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
libs/clients/vmst/src/lib/utils.ts

fix(parental-leave): Fix rightCodePeriod and rights calculator (#9881)

---

libs/service-portal/vehicles/src/screens/DrivingLessonsBook/DrivingLessonsBook.tsx

Fixes ID bug in driving lessons book

fix(service-portal): remove unused from query (#9890)

---

apps/web/screens/Organization/Home/Home.tsx

This PR contains a cherry picked commit from main and we've been requested to add the feature to prod

feat(web): Hotfix - Add search box for Directorate of Health organization page (#9850)

---

libs/application/ui-fields/src/lib/MessageWithLinkButtonFormField/MessageWithLinkButtonFormField.tsx
libs/application/ui-forms/src/lib/formConclusionSection/formConclusionSection.ts
libs/auth/react/src/lib/auth/AuthProvider.tsx

Make sure hash parameters are included from umsoknarkerfi to service portal
For functions to work

fix(applications): Fix service portal url from application system

---

libs/application/core/src/lib/messages.ts
libs/application/template-api-modules/src/lib/modules/templates/marriage-conditions-submission/marriage-conditions-submission.service.ts
libs/application/template-api-modules/src/lib/modules/templates/marriage-conditions-submission/types.ts
libs/application/templates/marriage-conditions/src/forms/sharedSections/dataCollection.ts

fix(marriage-condtionsöapplication): error message fix

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/constants.ts
libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
libs/application/templates/parental-leave/src/constants.ts
libs/application/templates/parental-leave/src/fields/InReviewSteps/ReviewSection/index.tsx
libs/application/templates/parental-leave/src/fields/InReviewSteps/index.tsx
libs/application/templates/parental-leave/src/forms/ResidenceGrant.ts
libs/application/templates/parental-leave/src/forms/ResidenceGrantNoBirthDate.ts
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
libs/application/templates/parental-leave/src/lib/answerValidationSections/utils.ts
libs/application/templates/parental-leave/src/lib/answerValidators.spec.ts
libs/application/templates/parental-leave/src/lib/messages.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

Added upload and periods

---

apps/services/sessions/project.json

Update buildTarget for app serve locally.
To start app locally via `yarn start...`

fix(services-sessions): Fix app serve locally

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/Themes/SAkTheme/SAkFooter.css.ts
apps/web/components/Organization/Wrapper/Themes/SAkTheme/SAkFooter.tsx
apps/web/components/Organization/Wrapper/Themes/SAkTheme/SAkHeader.css.ts
apps/web/components/Organization/Wrapper/Themes/SAkTheme/SAkHeader.tsx

* SAk is missing a header and footer so we need to hotfix one since their web is going live real soon

feat(web): Hotfix - SAk header and footer

---

.github/workflows/push.yml

Fix docker build when depending on env variable.
To unblock main.

fix(core): Add docker build args

---

.github/workflows/push.yml

Fix variable access.
To fix push.yml workflow.

fix(core): Add env. to access variable.

---

libs/island-ui/core/src/lib/ActionCard/ActionCard.tsx

Progressmeter conditionally rendered
Should not always be visible

fix(ui): Actioncard conditionally render progressbar

---

apps/api/infra/api.ts
apps/services/sessions/infra/sessions.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

Grant islandis namespace for gql api access
Enable gql queries for session on dev

fix(sessions): Grant islandis namespace.

---

libs/api/domains/auth/src/lib/loaders/domain.loader.ts
libs/api/domains/auth/src/lib/resolvers/client.resolver.ts
libs/api/domains/auth/src/lib/resolvers/customDelegation.resolver.ts

Refactor domain data loader to return null.
To handle when domains are not found.

fix(api-auth): Refactor domain data loader to return null.

---

libs/application/templates/european-health-insurance-card/src/fields/Applicants/Applicants.tsx
libs/application/templates/european-health-insurance-card/src/fields/Applicants/ApplicantsController.tsx
libs/application/templates/european-health-insurance-card/src/fields/IntroScreen/IntroScreen.tsx
libs/application/templates/european-health-insurance-card/src/fields/ReviewScreen/ReviewScreen.tsx
libs/application/templates/european-health-insurance-card/src/fields/Temp/Temp.tsx
libs/application/templates/european-health-insurance-card/src/forms/EuropeanHealthInsuranceCardApplyPDF.tsx
libs/application/templates/european-health-insurance-card/src/forms/EuropeanHealthInsuranceCardApplyPlastic.tsx
libs/application/templates/european-health-insurance-card/src/forms/EuropeanHealthInsuranceCardReview.tsx
libs/application/templates/european-health-insurance-card/src/lib/dataSchema.ts

change checkbox type and state management

---

libs/application/ui-components/src/components/ApplicationList/ApplicationList.tsx
libs/island-ui/core/src/lib/ActionCard/ActionCard.tsx

fix(applications): Revert draft status bar to original design (#10072)

---

libs/service-portal/sessions/src/components/LogTable/LogTable.tsx
libs/service-portal/sessions/src/lib/messages.ts

Info bubble for location header
So users can see how the location is decided

fix(session): Info bubble for location

---

libs/application/templates/public-debt-payment-plan/src/forms/PaymentPlanForm.ts
libs/application/ui-components/src/components/ApplicationList/ApplicationList.tsx
libs/application/ui-shell/src/components/Screen.tsx
libs/application/ui-shell/src/lib/FormShell.tsx
libs/island-ui/core/src/lib/ActionCard/ActionCard.tsx

Let draft status bar count sections
Not count child elements

fix(applications): Fix for draft status bar

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.ts

Take out - before sending bank account to api
would give error from the api

fix(parental-leave): take out - when sending in bank account to api

---

libs/application/templates/parental-leave/src/lib/answerValidationSections/giveRightsValidationSection.ts

fix(parental-leave): Non-custodial father can not give days (#10107)

---

apps/services/user-notification/src/app/modules/notifications/notificationDispatch.service.ts
apps/services/user-notification/src/app/modules/notifications/notifications.module.ts
apps/services/user-notification/src/app/modules/notifications/notifications.service.ts

* maplocale and cache settings
* addressed comment

fix(user-notification): mapLocale and cache settings (#10130)

---

libs/application/templates/parental-leave/src/lib/answerValidationSections/validateLastestEmployerValidationSection.ts
libs/application/templates/parental-leave/src/lib/messages.ts

* fix(parental-leave): validate employers' ratio and phonNumber
* linting
* linting
* linting
---------

fix(parental-leave): validate employers' ratio and phonNumber (#10135)

---

apps/application-system/api/infra/application-system-api.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

chore: adding a second ingress to appplications system api

---

libs/application/templates/general-petition/src/assets/School.tsx
libs/application/templates/general-petition/src/fields/ListCreated/index.tsx
libs/application/templates/general-petition/src/fields/SignPetitionView/index.tsx
libs/application/templates/general-petition/src/forms/signPetitionForm.ts
libs/application/templates/general-petition/src/lib/messages.ts

fix(general-petitions): minor tweaks

---

libs/application/templates/driving-instructor-registrations/src/fields/StudentsOverview/index.tsx
libs/application/templates/driving-instructor-registrations/src/fields/ViewStudent/index.tsx

* format completed hours
* format completed hours
---------

fix(instructor-registration): format completed hours (#10146)

---

libs/application/template-api-modules/src/lib/modules/templates/european-health-insurance-card/european-health-insurance-card.service.ts
libs/clients/ehic-client-v1/src/openapi.json

Schema changes (api changed), service changes

---

apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
apps/judicial-system/backend/src/app/formatters/formatters.ts
apps/judicial-system/backend/src/app/formatters/index.ts
apps/judicial-system/backend/src/app/messages/notifications.ts
apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendRulingNotifications.spec.ts

[Hætta að senda viðhengi á Hólmsheiði](https://app.asana.com/0/1199153462262248/1202322622786822/f)
Remove attachment from prison email and add a link to the portal instead.
We want to direct users to view any relevant information on the legal portal rather than through attachments

feat(j-s): Remove attachment from prison email

---

apps/judicial-system/backend/src/app/formatters/indictmentPdf.ts
apps/judicial-system/backend/src/app/messages/pdfIndictment.ts

Changed tab title for indictment pdf
The previous title was aggressive

fix(j-s): Indictment pdf tab title

---

apps/services/user-notification/src/app/modules/notifications/messageProcessor.service.ts

fixes an object by reference error 

fix(user-notfication): Template-copy-fix

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
libs/application/templates/parental-leave/src/forms/EditOrAddPeriods.ts
libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts

- adapt selfEmployer old structure
- fix rightCodePeriod
- VMST right on updated status

fix(parental-leave): selfEmployer, rightCodePeriod, VMST updated status call

---

infra/src/dsl/feature-deployments.ts
infra/src/dsl/feature-values.spec.ts
infra/src/feature-env.ts

This reverts commit aaac411e18de0f4cd3d17f628f8c6fa3afc61f91.

fix: reverts issue 9455

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.spec.ts
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveTemplateUtils.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

fix(parental-leave): edit-or-add-periods-prev-state old one failed

---

apps/samradsgatt/components/Card/Card.tsx
apps/samradsgatt/components/Card/ChosenSubscriptionCard.tsx
apps/samradsgatt/components/Card/SubscriptionActionBox.tsx
apps/samradsgatt/components/Card/SubscriptionActionCard.tsx
apps/samradsgatt/components/Card/index.ts
apps/samradsgatt/components/SearchAndFilter/SearchAndFilter.tsx
apps/samradsgatt/components/StatisticBox/StatisticBox.css.ts
apps/samradsgatt/components/Tab/TabContent.tsx
apps/samradsgatt/components/Tab/index.ts
apps/samradsgatt/components/Table/SubscriptionTable.tsx
apps/samradsgatt/components/Table/SubscriptionTableItem.tsx
apps/samradsgatt/pages/askriftir/index.tsx
apps/samradsgatt/pages/index.tsx
apps/samradsgatt/types/enums.ts
apps/samradsgatt/types/interfaces.ts
apps/samradsgatt/utils/dummydata/api/Cases.ts
apps/samradsgatt/utils/dummydata/api/Types.ts
apps/samradsgatt/utils/dummydata/api/User/SubscriptionsArray.ts
apps/samradsgatt/utils/dummydata/cases.ts
apps/samradsgatt/utils/dummydata/index.ts

feat(samradsgatt): Kam to typescript

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
libs/application/templates/parental-leave/src/forms/EditOrAddPeriods.ts
libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.spec.ts
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveTemplateUtils.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

- Move back on correct state on Abort
- Revert periods when Abort
- Stop showing StartDate selection page when choosing another option than specificDate

fix(parental leave): edit and add periods

---

apps/services/license-api/src/app/modules/license/clients/firearmLicense/firearmLicenseApiClient.module.ts

Correct client import
Config failure

fix(license-api): Firearm license module import

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts

fix(parental-leave): sendApplication

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts

fix(parental-leave): sendApplication (#10205)

---

libs/application/templates/european-health-insurance-card/src/forms/EuropeanHealthInsuranceCardForm.tsx
libs/application/templates/european-health-insurance-card/src/lib/helpers/applicantHelper.ts

condition works

---

libs/application/templates/european-health-insurance-card/src/fields/CompletedScreen/CompletedScreen.tsx
libs/application/templates/european-health-insurance-card/src/forms/EuropeanHealthInsuranceCardCompleted.tsx
libs/application/templates/european-health-insurance-card/src/lib/messages.ts

confirmation screen

---

libs/application/templates/european-health-insurance-card/src/forms/EuropeanHealthInsuranceCardForm.tsx
libs/application/templates/european-health-insurance-card/src/lib/messages.ts

data collection completed screen

---

.github/CODEOWNERS
apps/api/README.md
apps/application-system/README.md
apps/service-portal/README.md
apps/services/user-profile/README.md
libs/application/core/README.md
libs/application/templates/institution-collaboration/README.md
libs/clients/documents/README.md

Name change of team
We need these changes to keep everything working right.

chore(codeowners): Change codeowners to Norda from Sendiráðið

---

libs/auth-api-lib/seeders/local/008-domains_resources.js

Added local seed for domain table
to populate local db with domains

feat(ids-admin): Create DB seed for local dev for domain

---

libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

fix(parental-leave): Could delete period until 20 of this month (#10276)

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/applicationApprovedByEmployerToEmployer.ts

fix(parental-leave): wording on email to employer

---

libs/application/templates/parental-leave/src/forms/EditsInReview.ts
libs/application/templates/parental-leave/src/forms/InReviewAdditionalDocumentsRequired.ts

fix(parental-leave): title on InReviewSteps shown twice

---

infra/src/dsl/basic.spec.ts
infra/src/dsl/egress.spec.ts
infra/src/dsl/env.spec.ts
infra/src/dsl/extraAttributes.spec.ts
infra/src/dsl/feature-values.spec.ts
infra/src/dsl/healthcheck.spec.ts
infra/src/dsl/hpa.spec.ts
infra/src/dsl/ingress.spec.ts
infra/src/dsl/initContainer.spec.ts
infra/src/dsl/postgres.spec.ts
infra/src/dsl/service-account.spec.ts
infra/src/dsl/target-port.spec.ts
infra/src/dsl/toggles.spec.ts
infra/src/dsl/volumes.spec.ts
infra/src/dsl/xroad.spec.ts

fix(infra): Test EnvironmentConfig requires redisHost

---

libs/service-portal/sessions/src/components/SessionFilter/SessionFilter.tsx

Removed Test string from datepicker
it was not supposed to be there...

fix(sessions): Removed Test string from datepicker

---

SUMMARY.md
apps/native/app/README.md
apps/native/app/codegen.yml
apps/native/app/package.json
apps/native/app/project.json
scripts/gitbook.js
yarn.lock

chore: added codegen.yml config and nx target

---

apps/services/auth/admin-api/infra/auth-admin-api.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml

Hotfix prelease with #10344 
Apply hotfix to prerelease.
N/A

fix(services-auth-admin-api): Add issuer url env variable (#10344)

---

libs/application/ui-components/src/components/ApplicationList/ApplicationList.tsx
libs/island-ui/core/src/lib/ActionCard/ActionCard.tsx

Hide application data when its not relevant

fix(application-system): Hotfix hide application data

---

apps/system-e2e/src/tests/islandis/service-portal/smoke/sessions.spec.ts
scripts/_run-aws-eks-commands.js

* Support proxies for space-directories
* Fix filter
* Fix broken list view
* Remove .only filter
---------

fix(system-e2e): Fix broken sessions tests (#10330)

---

apps/services/auth/admin-api/infra/auth-admin-api.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml

Apply hotfix from main.
For release.

fix(services-auth-admin-api): Add nginx-ingress-external. (#10350)

---

libs/api/domains/consultation-portal/src/lib/documents/documents.resolver.ts
libs/api/domains/consultation-portal/src/lib/documents/documents.service.ts

getDocument was causing issues with other resolvers. Renamed to getCaseDocument

feat: case renamed

---

libs/api/domains/consultation-portal/src/lib/documents/documents.resolver.ts
libs/api/domains/consultation-portal/src/lib/documents/documents.service.ts

fix: case renamed (#10356)

---

libs/service-portal/air-discount/src/module.tsx
libs/service-portal/air-discount/src/screens/AirDiscountOverview/AirDiscountOverview.tsx

fix(service-portal): loftbru not rendering (#10358)

---

apps/services/auth/admin-api/infra/auth-admin-api.ts
apps/services/auth/admin-api/src/environments/environment.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml
libs/api/domains/auth-admin/src/lib/tenant/tenants.service.ts

Hotfix #10371 onto prerelease.
To fix IDS Admin.

fix(services-auth-admin-api): Undo multi issuer on auth admin api (#10371)

---

libs/application/template-api-modules/src/lib/modules/templates/european-health-insurance-card/european-health-insurance-card.service.ts
libs/clients/ehic-client-v1/src/index.ts

dummy data manipulation. Remove unused code

---

libs/application/templates/driving-school-confirmation/src/fields/StudentInfo/index.tsx
libs/application/templates/driving-school-confirmation/src/graphql/queries.ts

fix(driving-school): date format in showing schools

---

libs/application/templates/passport/src/fields/PassportSelection/index.tsx
libs/application/templates/passport/src/forms/infoSection/childsPersonalInfo.ts

fix(passport): child fix

---

.github/workflows/config-values.yaml
.github/workflows/external-checks.yml
.github/workflows/pullrequest.yml
infra/scripts/ci/git-check-dirty.sh
scripts/ci/20_check-formatting.sh
scripts/gitbook.js

ci(autocommit): autocommit code generated files, gitbook, charts, nx format

---

apps/services/sessions/infra/sessions.ts
infra/src/dsl/output-generators/feature-jobs.ts

fix(dsl): missing db jobs on identical db names (#10348)

---

libs/api/domains/license-service/src/lib/client/disability-license-client/disabilityLicenseMapper.ts

Change the mapping so it reflects the pass template
It changed

fix(license-service): fix disability mapping

---

apps/web/components/Regulations/RegulationsSearchSection.tsx
apps/web/screens/Organization/Syslumenn/Auctions.tsx
apps/web/screens/Organization/Syslumenn/Homestay.tsx
apps/web/screens/Organization/Syslumenn/OperatingLicenses.tsx
libs/shared/connected/src/lib/LawyersList/LawyersList.tsx
libs/shared/connected/src/lib/RealEstateAgentsList/RealEstateAgentsList.tsx

* The Input component's props were changed recently and is breaking a lot of pages on the web

fix(web): Fix props for Input component on web causing 500 errors on prod

---

libs/service-portal/information/src/components/ChildView/ChildView.tsx

Causing errors on prod.
Requested by Þjóðskrá

fix(service-portal): remove logheimilisforeldri

---

libs/service-portal/information/src/components/ChildView/ChildView.tsx

fix(service-portal): remove logheimilisforeldri (#10404)

---

.github/workflows/push.yml
scripts/ci/00_prepare-base-tags.sh

- chore(ci): Change how docker tags are generated (#10382)
- fix(ci): prepare base tag to use new convention (#10420)

fix(ci): New docker_tag convention

---

.github/workflows/push.yml
apps/api/infra/api.ts
scripts/ci/00_prepare-base-tags.sh

* chore(ci): Change how docker tags are generated (#10382)
* Change how we generate docker tags
* dummy change
* Update main.ts
---------
* fix(ci): prepare base tag to use new convention (#10420)
---------

fix(ci): New docker_tag convention (#10426)

---

apps/web/components/Organization/Slice/PowerBiSlice/PowerBiSlice.tsx

* On /v/gagnasidur-fiskistofa we are embedding a PowerBi report containing multiple pages. These pages are using the same kind of filters which we'd like to have the same value between page changes.

feat(web): Keep state between page change for PowerBi Slices

---

apps/web/components/Organization/Slice/PowerBiSlice/PowerBiSlice.tsx

This PR contains a cherry-picked commit from main (https://github.com/island-is/island.is/pull/10423)

feat(web): Hotfix keep state between pages for powerbi slices

---

apps/consultation-portal/components/CaseOverview/CaseOverview.tsx
apps/consultation-portal/components/StackedTitleAndDescription/StackedTitleAndDescription.tsx
apps/consultation-portal/screens/Case/Case.tsx
apps/consultation-portal/screens/Case/getCase.graphql.ts
apps/consultation-portal/types/viewModels.ts

Minor fixes. 
Fix on variable names in interface/viewmodels to be in step with the api 
Fix null appearing if no contact person is found on /case

feat: minor fix on data structure in case view

---

libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

fix(parental leave): sync period

---

libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts

fix(parental-leave): pruned days

---

apps/consultation-portal/components/Layout/Layout.tsx
apps/consultation-portal/components/SEO/SEO.tsx
apps/consultation-portal/pages/tolfraedi.tsx
apps/consultation-portal/pages/um/index.tsx
apps/consultation-portal/pages/umsagnir/index.tsx
apps/consultation-portal/screens/Case/Case.tsx
apps/consultation-portal/screens/Home/Home.tsx
apps/consultation-portal/screens/Subscriptions/Subscriptions.tsx
apps/consultation-portal/types/interfaces.ts

https://veflausnir.atlassian.net/browse/KAM-890
Adding a seo title for all <Head> in pages
/
/

feat(consultation-portal): SEO component

---

apps/auth-admin-web/entities/dtos/identity-resource.dto.ts
libs/auth-api-lib/src/lib/clients/clients.service.ts
libs/auth-api-lib/src/lib/resources/dto/identity-resources.dto.ts
libs/auth-api-lib/src/lib/resources/models/identity-resource.model.ts
libs/auth-api-lib/src/lib/resources/resources.service.ts

Fix regressions in auth-admin-web
To fix auth-admin-web.

fix(auth-admin-web): Fixes in auth-api-lib for auth-admin-web

---

apps/application-system/form/src/components/Header/Header.tsx

Island.is logo in upper corner now redirects to /minarsidur/umsoknir
Better UX and request by gunnar

chore(applications): Logo header url change

---

libs/auth-api-lib/src/lib/resources/resources.service.ts

Revert removal of raw true for apiResources.
AuthAdmin Web is not getting associations so fails to display relations.

fix(auth-admin-web): Fix get for api resources in auth admin api.

---

apps/web/screens/Organization/Services.tsx

* The Input component props was changed recently and it's usage on /s/{organization}/thjonusta was not updated

fix(web): Update input props for Services page

---

apps/web/screens/Organization/Services.tsx

fix(web): Hotfix - Update input props for Services page (#10458)

---

apps/auth-admin-web/entities/dtos/identity-resource.dto.ts
apps/services/auth/admin-api/infra/auth-admin-api.ts
apps/services/auth/admin-api/src/main.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml
libs/auth-api-lib/src/lib/clients/clients.service.ts
libs/auth-api-lib/src/lib/resources/dto/identity-resources.dto.ts
libs/auth-api-lib/src/lib/resources/models/identity-resource.model.ts
libs/auth-api-lib/src/lib/resources/resources.service.ts

Fixing regression on admin-api due to ingress rewrite decodeing path and not encoding again.
Fixing regression to update methods on clients, scope and identity resources.
PRs #10415, #10448, #10449
To fix Auth Admin Web.

fix(services-auth-admin-api): Fixes api path and update methods in admin api.

---

apps/application-system/api/src/environments/environment.ts

This claim was missing from this [PR](https://github.com/island-is/island.is/pull/6729). Adding it to production config
So clients can be correctly authorized

chore(Application-system): Allow client nationalid claim for production

---

apps/air-discount-scheme/backend/esbuild.json
apps/financial-aid/backend/esbuild.json
apps/icelandic-names-registry/backend/esbuild.json
apps/judicial-system/backend/esbuild.json
apps/reference-backend/esbuild.json
apps/services/auth/ids-api/esbuild.json
apps/services/documents/esbuild.json
apps/services/endorsements/api/esbuild.json
apps/services/user-profile/esbuild.json
apps/skilavottord/ws/esbuild.json

chore: Add lru-cache to esbuild.json

---

libs/api/domains/license-service/src/lib/client/adr-license-client/genericAdrLicense.service.ts
libs/api/domains/license-service/src/lib/client/disability-license-client/genericDisabilityLicense.service.ts
libs/api/domains/license-service/src/lib/client/firearm-license-client/genericFirearmLicense.service.ts
libs/api/domains/license-service/src/lib/client/machine-license-client/genericMachineLicense.service.ts
libs/clients/smartsolutions/src/lib/graphql/queries/queries.ts

Hotfix - update graphql request for existing pkpass (#10474)

fix(license-service): Hotfix - update graphql request for existing pkpass

---

apps/consultation-portal/components/ReviewCard/ReviewCard.css.ts
apps/consultation-portal/components/ReviewCard/ReviewCard.tsx
apps/consultation-portal/screens/Case/getAdvices.graphql.ts

User can see attachments and download attachments on advices

feat: add link to download files

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/Themes/HveTheme/HveFooter.css.ts
apps/web/components/Organization/Wrapper/Themes/HveTheme/HveFooter.tsx
apps/web/components/Organization/Wrapper/Themes/HveTheme/HveHeader.css.ts
apps/web/components/Organization/Wrapper/Themes/HveTheme/HveHeader.tsx
apps/web/components/Organization/Wrapper/Themes/HveTheme/index.ts

feat(web): HVE organization page header and footer

---

apps/air-discount-scheme/api/infra/api.ts
apps/air-discount-scheme/backend/infra/backend.ts
apps/api/infra/api.ts
apps/application-system/api/infra/application-system-api.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
charts/judicial-system/values.dev.yaml
charts/judicial-system/values.prod.yaml
charts/judicial-system/values.staging.yaml
infra/src/dsl/initContainer.spec.ts
infra/src/dsl/output-generators/map-to-helm-values.ts

chore(infra): Tune requests CPU to more legitimate averages

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunSudurlandsTheme/HeilbrigdisstofnunSudurlandsHeader.css.ts
apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunSudurlandsTheme/HeilbrigdisstofnunSudurlandsHeader.tsx

* The header for HSU was updated with new visuals
* This was requested by the HSU organization

chore(web): Update HSU header visuals

---

apps/consultation-portal/codegen.yml

yarn schemas broke due to codegen.yml.
changed the file endings to .graphql to fix the issue

fix: codegen

---

libs/application/templates/parental-leave/src/fields/SelfEmployed/index.tsx
libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
libs/application/templates/parental-leave/src/lib/dataSchema.ts

fix(parental leave): self employer clear employers

---

libs/application/template-api-modules/src/lib/modules/templates/european-health-insurance-card/european-health-insurance-card.service.ts
libs/application/template-api-modules/src/lib/modules/templates/european-health-insurance-card/index.ts
libs/application/template-api-modules/src/lib/modules/templates/european-health-insurance-card/types/index.ts

feat(ehic): service refactoring

---

libs/application/template-api-modules/src/lib/modules/templates/operating-license/operatingLicense.service.ts
libs/application/templates/marriage-conditions/src/forms/spouseConfirmation.ts
libs/application/templates/operating-license/src/fields/PropertyRepeater/index.tsx
libs/application/templates/operating-license/src/forms/draft/draft.ts
libs/application/templates/operating-license/src/lib/dataSchema.ts

fix(applications): ol and mc minor fixes

---

libs/application/templates/estate/src/fields/EstateMembersRepeater/AdditionalEstateMember.tsx
libs/application/templates/estate/src/fields/TextFieldsRepeater/index.tsx
libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/form.ts
libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/overviewSection.ts
libs/application/templates/estate/src/lib/dataSchema.ts

fix(estate): bugfixes

---

scripts/ci/Dockerfile
scripts/ci/_docker.sh

fix(CI): Fix breaking docker build

---

apps/download-service/src/app/modules/documents/document.controller.ts
libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx

This reverts commit 7f5c0088dd444d6e037324a4d2a0557a9770b0f6.
Revert fixing android bug, will fix later with adding user to download service and refactor post request.

fix(service-portal): REVERT mailbox bug on firefox android (#10137)

---

scripts/ci/Dockerfile

fix(system-e2e): ACL breaking build

---

scripts/ci/_docker.sh

Add `_set_publish`, which was accidentally dead code :skull_and_crossbones:

fix(ci): Publish images

---

apps/github-actions-cache/infra/github-actions-cache.ts
scripts/ci/_retag.sh

fix: force rebuild all images

---

apps/services/regulations-admin-backend/infra/backend.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

Add grant namespace to dl service regulations
They need to communicate

fix(regulations): Add grant namespace to dl service

---

libs/application/templates/inheritance-report/src/lib/dataSchema.ts

fix(inheritance-report): application is down on dev

---

libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/components/Inputs/Email.tsx

Update when error is shown in email inputs
I missed it in code review after a large input change in the repo. 🙈

fix(service-portal): Update error handling in email input

---

libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/components/Inputs/Email.tsx

fix(service-portal): Update error handling in email input (#10596)

---

libs/application/templates/accident-notification/src/fields/HiddenInformation/index.tsx
libs/application/templates/family-matters/children-residence-change/src/fields/Overview/index.tsx
libs/application/templates/family-matters/core/src/components/ContactInfoRow.tsx
libs/application/templates/general-fishing-license/src/fields/FishingLicense/index.tsx
libs/application/templates/general-fishing-license/src/fields/ShipSelection/index.tsx

Fixing inputs that arent getting updated.
Breaking two applications

fix(Application system): Set value breaking inputs

---

libs/application/templates/accident-notification/src/fields/HiddenInformation/index.tsx
libs/application/templates/family-matters/children-residence-change/src/fields/Overview/index.tsx
libs/application/templates/family-matters/core/src/components/ContactInfoRow.tsx
libs/application/templates/general-fishing-license/src/fields/FishingLicense/index.tsx
libs/application/templates/general-fishing-license/src/fields/ShipSelection/index.tsx

Fixing inputs that arent getting updated.
Breaking two applications

fix(Application system): RHF breaking inputs

---

libs/application/core/src/lib/fieldBuilders.ts
libs/application/types/src/lib/Fields.ts
libs/application/ui-fields/src/lib/PhoneFormField/PhoneFormField.tsx
libs/application/ui-forms/src/lib/applicantInformationMultiField/applicantInformationSchema.ts
libs/island-ui/core/src/lib/PhoneInput/CountryCodeSelect/Components/index.tsx
libs/island-ui/core/src/lib/PhoneInput/CountryCodeSelect/CountryCodeSelect.css.ts
libs/island-ui/core/src/lib/PhoneInput/PhoneInput.tsx
libs/shared/form-fields/src/lib/PhoneInputController/PhoneInputController.tsx

#10598 
Feature flag now disables the country code dropdown instead of rendering a normal text input.
See #10598 

fix(phone-input): Add disable dropdown and change feature flag

---

apps/web/screens/Search/Search.tsx

* The search page (/en/search) was missing translations

chore(web): Add translations to the search page

---

apps/services/auth/ids-api/infra/identity-server.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml

feat(auth): Add config for contentful access token.

---

apps/auth-admin-web/components/Client/form/ClientCreateForm.tsx
apps/auth-admin-web/components/Resource/forms/ApiScopeCreateForm.tsx
apps/auth-admin-web/components/Resource/forms/ApiScopeGroupCreateForm.tsx
apps/auth-admin-web/components/Resource/forms/ApiScopePersonalRepresentativePermissionsForm.tsx
apps/auth-admin-web/components/common/LoadingScreen.tsx
apps/auth-admin-web/pages/admin/api-scope-group/[groupId].tsx
apps/auth-admin-web/pages/admin/api-scope-user/[apiScopeUser].tsx
apps/auth-admin-web/pages/admin/domain/[domainName].tsx
apps/auth-admin-web/pages/admin/grant-type/[grantType].tsx
apps/auth-admin-web/pages/admin/idp-provider/[idp].tsx
apps/auth-admin-web/pages/admin/language/[isoKey].tsx
apps/auth-admin-web/pages/admin/translation/[key].tsx
apps/auth-admin-web/pages/client/[client].tsx
apps/auth-admin-web/pages/resource/api-resource/[edit].tsx
apps/auth-admin-web/pages/resource/api-scope/[edit].tsx
apps/auth-admin-web/pages/resource/identity-resource/[edit].tsx

Delay rendering of IDS Admin edit pages until data has been loaded.
This is to fix react-hook-form 7 regressions which don't support delayed defaultValue.

fix(auth-admin): Add a loading state to edit pages

---

apps/auth-admin-web/components/Client/form/ClientCreateForm.tsx
apps/auth-admin-web/components/Resource/forms/ApiScopeCreateForm.tsx
apps/auth-admin-web/components/Resource/forms/ApiScopeGroupCreateForm.tsx
apps/auth-admin-web/components/Resource/forms/ApiScopePersonalRepresentativePermissionsForm.tsx
apps/auth-admin-web/components/common/LoadingScreen.tsx
apps/auth-admin-web/pages/admin/api-scope-group/[groupId].tsx
apps/auth-admin-web/pages/admin/api-scope-user/[apiScopeUser].tsx
apps/auth-admin-web/pages/admin/domain/[domainName].tsx
apps/auth-admin-web/pages/admin/grant-type/[grantType].tsx
apps/auth-admin-web/pages/admin/idp-provider/[idp].tsx
apps/auth-admin-web/pages/admin/language/[isoKey].tsx
apps/auth-admin-web/pages/admin/translation/[key].tsx
apps/auth-admin-web/pages/client/[client].tsx
apps/auth-admin-web/pages/resource/api-resource/[edit].tsx
apps/auth-admin-web/pages/resource/api-scope/[edit].tsx
apps/auth-admin-web/pages/resource/identity-resource/[edit].tsx
libs/portals/shared-modules/delegations/src/screens/GrantAccess/GrantAccess.tsx

fix: React hook form regressions (HOTFIX)

---

libs/application/templates/financial-statements-inao/src/fields/CemetryCaretaker/index.tsx
libs/application/templates/financial-statements-inao/src/forms/application/cemetry/sectionCemetryCaretaker.ts
libs/application/templates/financial-statements-inao/src/lib/constants.ts

…0594)
(cherry picked from commit 884738c3c967bdd9f5ac670674b721a38abf7002)

fix(financial-statement-inao):  validation error caretaker screen

---

libs/application/templates/inheritance-report/src/lib/dataSchema.ts

fix(inheritance-report): Fix inheritance report application bugs

---

apps/services/auth/ids-api/infra/identity-server.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml

feat(auth): Add config for contentful access token. (#10591)

---

apps/system-e2e/src/notifications/notify.ts
apps/system-e2e/src/support/disablers.ts
apps/system-e2e/src/support/email-account.ts
apps/system-e2e/src/support/login.ts
apps/system-e2e/src/support/session.ts
apps/system-e2e/src/support/utils.ts
apps/system-e2e/src/tests/islandis/web/smoke/sites-of-institutions.spec.ts

- More tests
- Fix missing import

test(system-e2e): Institution page tests (#10514)

---

apps/services/license-api/src/app/modules/license/dto/verifyLicense.dto.ts
apps/services/license-api/src/app/modules/license/license.service.ts

feat(license-api): clearer prop name

---

libs/application/templates/data-protection-complaint/src/fields/FieldAlertMessage.tsx
libs/application/templates/document-provider-onboarding/src/forms/messages.ts

[Attach a link to issue if relevant](https://app.clickup.com/t/861mj0mpf)
- Change HTML in content to markdown
- Fix AlertMessage content layout
QA

fix(dpc-dpo): Small bug fixes in Data Protection Complaint and Document Provider Onboarding

---

apps/consultation-portal/components/CaseOverview/CaseOverview.tsx

Remove truncate on labels on case info page

fix: (Samradsgatt) remove truncate

---

apps/judicial-system/web/src/components/IndictmentCaseFilesList/IndictmentCaseFilesList.tsx
apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFiles/CaseFiles.tsx
apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Prosecutor/Indictments/Processing/Processing.tsx
apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx
apps/judicial-system/web/src/utils/hooks/useSections/index.ts

[Asana](https://app.asana.com/0/1199153462262248/1204055381102394/f)
Open indictments for RVK and Sudurland as well as for a specific prosecutor in another institution.

chore(j-s): Open traffic violation indictments for RVK and Sudurland

---

libs/application/template-api-modules/src/lib/modules/templates/public-debt-payment-plan/public-debt-payment-plan.service.ts
libs/application/template-api-modules/src/lib/modules/templates/public-debt-payment-plan/types/index.ts
libs/application/templates/public-debt-payment-plan/src/fields/Overview/Overview.tsx
libs/application/templates/public-debt-payment-plan/src/fields/PaymentPlan/PaymentPlan.tsx
libs/application/templates/public-debt-payment-plan/src/lib/dataSchema.ts

Distributions were not registering correctly after react-hook-form update. 
Remove `<input type="hidden">` logic and use `setValue` instead
Application is broken because of this

fix(pdpp): Hotfix value not registering correctly in form

---

libs/auth-api-lib/seeders/data/client-licenses-atvr.ts

A new machine client for ÁTVR
ÁTVR needs to connect to the License-api to enable verification of licenses

feat(license-api): add atvr client

---

apps/services/auth/admin-api/src/app/v2/clients/test/me-clients.spec.ts
libs/auth-api-lib/src/lib/clients/admin/admin-clients.service.ts

[Notion task](https://www.notion.so/Fill-out-default-attributes-based-on-client-type-c7ad3ef5240c4d6c80ca06095b70f3cf?pvs=4)
Populating default client attributes on client creation based on the client type.
Also populating client grant type based on the client type.
To improve the client creation process.

feat(services-auth-admin-api): Add default attributes and default grant types.

---

libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
libs/application/templates/estate/src/dataProviders/EstateNoticeProvider.ts
libs/application/templates/estate/src/dataProviders/index.ts
libs/application/templates/estate/src/forms/sharedSections/dataCollection.ts
libs/application/templates/estate/src/lib/EstateTemplate.ts

fix(application-estate): Entry data provider (#10694)

---

apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
apps/judicial-system/backend/src/app/modules/file/file.controller.ts
apps/judicial-system/backend/src/app/modules/file/test/fileController/createCaseFileGuards.spec.ts
apps/judicial-system/backend/src/app/modules/file/test/fileController/createPresignedPostGuards.spec.ts
apps/judicial-system/backend/src/app/modules/file/test/fileController/deleteCaseFileGuards.spec.ts

[Aðgangsstýringar á upload á gögnum í loknum málum](https://app.asana.com/0/1199153462262248/1204289041884024/f)
- Allows case file upload and delete for completed cases.
- Disallows rejection and dismissal of indictments (not part of the Asana task description).
- So case files can be added to appealed cases.

feat(j-s): Case File Upload

---

apps/services/sessions/src/app/sessions/sessions.module.ts

fix(sessions): Revert removing queue prefix.

---

libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

fix(parental-leave): residence grant

---

apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx

[Asana](https://app.asana.com/0/1199153462262248/1204023021849836/f)
Remove the option to filter cases on the cases screen for prisons.
All cases that prisons see are of the same type and therefor no need for a filter.

feat(j-s): Remove filtering from prisons

---

infra/src/dsl/egress.spec.ts
infra/src/dsl/kubernetes-runtime.ts
infra/src/dsl/value-files-generators/helm.spec.ts

fix: disabled mountebank for this release

---

apps/portals/admin/src/auth.ts
apps/services/auth/admin-api/src/app/v2/clients/test/me-clients.spec.ts
libs/api/domains/auth-admin/src/lib/client/clients.service.spec.ts
libs/api/domains/auth-admin/src/lib/client/clients.service.ts
libs/api/domains/auth-admin/src/lib/client/dto/create-client.input.ts
libs/api/domains/auth-admin/src/lib/models/client-type.enum.ts
libs/auth-api-lib/src/lib/clients/admin/dto/admin-create-client.dto.ts
libs/auth-api-lib/src/lib/types.ts
libs/clients/auth/admin-api/src/index.ts
libs/portals/admin/ids-admin/src/components/Client/Delegation.tsx
libs/portals/admin/ids-admin/src/components/Clients/Clients.tsx
libs/portals/admin/ids-admin/src/components/TenantsList/TenantsList.tsx
libs/portals/admin/ids-admin/src/components/forms/CreateClient/CreateClient.action.ts
libs/portals/admin/ids-admin/src/components/forms/CreateClient/CreateClient.tsx
libs/portals/admin/ids-admin/src/lib/messages.ts
libs/portals/admin/ids-admin/src/lib/navigation.ts
libs/portals/admin/ids-admin/src/lib/paths.ts
libs/portals/admin/ids-admin/src/module.tsx
libs/portals/admin/ids-admin/src/screens/ApplicationsScreen.tsx
libs/portals/admin/ids-admin/src/screens/Tenant/Tenant.tsx

Hotfix #10734, #10736 and #10725 for relese
To apply for release.
N/A

fix(portals-admin-ids-admin): Hotfixes few bugs, all text in english and remove filter dropdown

---

libs/api/domains/license-service/src/lib/client/adr-license-client/genericAdrLicense.service.ts
libs/api/domains/license-service/src/lib/client/disability-license-client/genericDisabilityLicense.service.ts
libs/api/domains/license-service/src/lib/client/firearm-license-client/genericFirearmLicense.service.ts
libs/api/domains/license-service/src/lib/client/machine-license-client/genericMachineLicense.service.ts

Reduce info log spam
Too spammy

fix(license-service): reduce logging

---

libs/api/domains/license-service/src/lib/client/adr-license-client/genericAdrLicense.service.ts
libs/api/domains/license-service/src/lib/client/disability-license-client/genericDisabilityLicense.service.ts
libs/api/domains/license-service/src/lib/client/firearm-license-client/genericFirearmLicense.service.ts
libs/api/domains/license-service/src/lib/client/machine-license-client/genericMachineLicense.service.ts

[#10752](https://github.com/island-is/island.is/pull/10752)

fix(license-service): Hotfix: reduce log spam

---

libs/portals/admin/ids-admin/src/screens/IDSAdmin.tsx

Don't show the back button on the tenant list.

feat(ids-admin): Don't show the back button on the tenant list.

---

libs/api/domains/consultation-portal/src/lib/models/userCaseSubscriptionResult.model.ts
libs/api/domains/consultation-portal/src/lib/models/userSubscriptionResult.model.ts

https://veflausnir.atlassian.net/browse/KAM-1086
Types not found, need to add registerEnumType

fix(consultation-portal): fixed types not found

---

apps/consultation-portal/screens/Case/Case.tsx

https://veflausnir.atlassian.net/browse/KAM-1075
Empty state if there are no case documents

fix(consultation-portal): empty state on case documents

---

apps/consultation-portal/components/WriteReviewCard/WriteReviewCard.tsx

https://veflausnir.atlassian.net/browse/KAM-1079

feat(consultation-portal): Minimum char in input

---

apps/judicial-system/web/src/components/AppealAlertBanner/AppealAlertBanner.tsx
apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx

[Asana](https://app.asana.com/0/1199153462262248/1204271839665585/f)
Display appeal deadline alert banner for judge
So that the judge can see the appeal deadline of a case

feat(j-s):  Display appeal deadline alert banner for judge

---

apps/consultation-portal/components/Menu/Menu.tsx
apps/consultation-portal/pages/mal/[slug].tsx
apps/consultation-portal/screens/Case/Case.tsx

https://veflausnir.atlassian.net/browse/KAM-1078

feat(consultation-portal): Loggedout state á villtu senda umsögn

---

libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/ValidationErrorMessages/index.tsx

fix(transfer of vehicle ownership): Handle if buyerCoOwnerAndOperator is empty

---

apps/consultation-portal/pages/umsagnir/index.tsx
apps/consultation-portal/screens/Advices/Advices.tsx

https://veflausnir.atlassian.net/browse/KAM-1081
"unauthorized gql error does not redirect to 500"
commented code will be fixed once authorization on backend is done

fix(consultation-portal): unauthorized gql error does not redirect to 500

---

libs/portals/admin/ids-admin/src/components/Client/AdvancedSettings.tsx
libs/portals/admin/ids-admin/src/components/Client/Lifetime.tsx
libs/portals/admin/ids-admin/src/components/Client/ReadableSeconds.ts
libs/portals/admin/ids-admin/src/lib/messages.ts

Add a description text to inputs that display the given seconds in other units such as days, months, and years.
Better user experience.

feat(ids-admin): Human readable seconds

---

apps/judicial-system/web/messages/Core/sections.ts
apps/judicial-system/web/src/components/PageLayout/PageLayout.tsx

[Asana](https://app.asana.com/0/1199153462262248/1204298511753938/f)
Set the FormStepper title to "Kærumál" for court of appeal users

chore(j-s): Court of appeal FormStepper title

---

libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification.utils.ts
libs/application/templates/accident-notification/src/fields/FormOverview/index.tsx

fix(accident-notification): Parse phone number before submitting document

---

apps/application-system/api/src/app/modules/application/utils/application.ts
libs/application/ui-components/src/components/ApplicationCard/ApplicationCard.tsx
libs/application/ui-components/src/components/ApplicationCard/components/ApplicationCardProgress.tsx
libs/application/ui-components/src/components/ApplicationCard/utils/history.tsx
libs/portals/admin/application-system/src/components/ApplicationDetails/ApplicationDetails.tsx
libs/portals/admin/application-system/src/components/ApplicationsTable/ApplicationsTable.tsx
libs/portals/admin/application-system/src/components/Filters/Filters.tsx
libs/portals/admin/application-system/src/lib/messages.ts
libs/portals/admin/application-system/src/screens/Overview/Overview.tsx

Adjustments to the ui.
For better ux

fix(application-admin-portal): Adjustments to the ui

---

apps/web/components/connected/index.ts
apps/web/components/connected/syslumenn/CardLists/AlcoholLicencesList/AlcoholLicencesList.tsx
apps/web/components/connected/syslumenn/CardLists/AlcoholLicencesList/queries.ts
apps/web/components/connected/syslumenn/CardLists/TemporaryEventLicencesList/TemporaryEventLicencesList.tsx
apps/web/components/connected/syslumenn/CardLists/TemporaryEventLicencesList/queries.ts
apps/web/components/connected/syslumenn/TableLists/BrokersList/BrokersList.tsx
apps/web/components/connected/syslumenn/TableLists/BrokersList/queries.ts
apps/web/components/connected/syslumenn/index.ts
apps/web/components/connected/syslumenn/utils/csvExport.ts
apps/web/components/connected/syslumenn/utils/index.ts
apps/web/components/connected/syslumenn/utils/search.ts
apps/web/components/connected/syslumenn/utils/valueParsers.ts
apps/web/screens/Organization/Syslumenn/Auctions.tsx
apps/web/screens/Organization/Syslumenn/Homestay.tsx
apps/web/utils/richText.tsx
libs/api/domains/syslumenn/src/lib/models/alcoholLicence.ts
libs/api/domains/syslumenn/src/lib/models/broker.ts
libs/api/domains/syslumenn/src/lib/models/temporaryEventLicence.ts
libs/api/domains/syslumenn/src/lib/syslumenn.resolver.ts
libs/clients/syslumenn/src/clientConfig.json
libs/clients/syslumenn/src/lib/__mock-data__/requestHandlers.ts
libs/clients/syslumenn/src/lib/__mock-data__/responses.ts
libs/clients/syslumenn/src/lib/syslumenn.spec.ts
libs/clients/syslumenn/src/lib/syslumennClient.service.ts
libs/clients/syslumenn/src/lib/syslumennClient.types.ts
libs/clients/syslumenn/src/lib/syslumennClient.utils.ts
libs/cms/src/lib/generated/contentfulTypes.d.ts
libs/shared/connected/src/utils/localization.ts

* This PR contains three cherry picked commits from main that we'd like to hotfix
https://github.com/island-is/island.is/pull/9838
https://github.com/island-is/island.is/pull/10758
https://github.com/island-is/island.is/pull/10796
These changes involve "list pages" that display Alcohol and temporary event licenses as well as a list of brokers.

feat(web): Hotfix - Syslumenn list pages

---

apps/services/license-api/infra/license-api.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

Add DriversLicense secret
Not crashing main is good

fix(service-portal): missing secret

---

infra/src/dsl/output-generators/map-to-helm-values.ts

chore(infra): Fixing K8s access to mountebank

---

libs/clients/driving-license/src/v5/clientConfig.json

A minor update on practice permit application endpoint

feat(clients-driving-license): Updated client config

---

libs/application/templates/general-fishing-license/src/fields/FishingLicense/index.tsx

Incorrect saved value was being set
Error

fix(applications): General Fishing License bugfix

---

apps/consultation-portal/pages/user/[slug].tsx

landing page when user has confirmed their email

feat: add email verified page

---

apps/consultation-portal/infra/samradsgatt.ts
charts/islandis/values.dev.yaml

fix(consultation-portal): changing next auth url

---

apps/consultation-portal/pages/_app.tsx

Adding base path to sessionProvider in _app

feat(consultation-portal): Base path to _app

---

apps/system-e2e/src/tests/judicial-system/smoke/restriction-case.spec.ts

This is connected to island-is/helm#688

chore(system-e2e): moving judicial-system tests to e separate location to be run independently

---

apps/consultation-portal/lib/environment.ts

fix(consultation-portal): Update environment.ts

---

infra/src/dsl/egress.spec.ts
infra/src/dsl/kubernetes-runtime.ts
infra/src/dsl/value-files-generators/helm.spec.ts

* disabled mountebank for this release
* disabled relevant tests
* adding the base template but removing the tests
* adding the base template but removing the tests

fix: disabled mountebank for this release (#10745)

---

apps/services/license-api/src/app/app.module.ts
libs/clients/firearm-license/src/index.ts
libs/clients/firearm-license/src/lib/openFirearmLicenseClient.config.ts

Correct config should be loaded
For proper function

fix(license-api): fix config module loads

---

apps/services/license-api/src/app/app.module.ts
libs/clients/firearm-license/src/index.ts
libs/clients/firearm-license/src/lib/openFirearmLicenseClient.config.ts

cherry-picked from main by way of this PR(https://github.com/island-is/island.is/pull/10934)

fix(license-api): Hotfix - config module load

---

libs/portals/admin/ids-admin/src/shared/components/ContentCard.tsx

When submitting edit for client the submit button does not change to disabled like it should
So users can not submit the same changes twice

fix(auth-admin): Fix isDirty reset

---

libs/portals/admin/ids-admin/src/components/Modal/Modal.tsx
libs/portals/shared-modules/delegations/src/components/Modal/Modal.css.ts
libs/portals/shared-modules/delegations/src/components/Modal/Modal.tsx

This fixes a bug where users on iOS devices couldn't scroll within a modal.

fix(delegations): iOS scroll bug

---

libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
libs/api/domains/driving-license/src/lib/graphql/main.resolver.ts
libs/application/template-api-modules/src/lib/modules/templates/driving-learners-permit/driving-learners-permit.service.ts
libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
libs/clients/driving-license/src/v5/index.ts

fix(clients-driving-license): Correct mistaken purpose of userid

---

libs/application/ui-components/src/components/ApplicationCard/ApplicationCard.tsx

[Attach a link to issue if relevant](https://app.clickup.com/t/861mnzpw5)
Fix `ApplicationCard` scaling for small devices
Better UX for small devices

fix(application-system): ApplicationCard scaling

---

apps/consultation-portal/components/ReviewCard/ReviewCard.tsx
apps/consultation-portal/screens/Case/Case.tsx

https://veflausnir.atlassian.net/browse/KAM-1168

fix(consultation-portal): blowout icon is now add instead of open

---

libs/application/template-api-modules/src/lib/modules/templates/european-health-insurance-card/european-health-insurance-card.service.ts
libs/application/templates/european-health-insurance-card/src/fields/CompletedScreen/CompletedScreen.tsx
libs/application/templates/european-health-insurance-card/src/fields/ReviewScreen/ReviewScreen.tsx
libs/application/templates/european-health-insurance-card/src/forms/EuropeanHealthInsuranceCardForm.tsx
libs/application/templates/european-health-insurance-card/src/forms/NoApplicants.tsx
libs/application/templates/european-health-insurance-card/src/lib/helpers/applicantHelper.ts
libs/application/templates/european-health-insurance-card/src/lib/types/index.ts
libs/clients/ehic-client-v1/src/lib/ehicClientConfig.ts

feat(ehic): CR - Fix any types, simplify functions and other things after code review

---

apps/consultation-portal/components/CaseStatusCard/CaseStatusCard.tsx

Add closed status info card to case with closed status

feat(consultation-portal): add case closed card

---

apps/consultation-portal/components/CaseOverview/CaseOverview.tsx
apps/consultation-portal/screens/Case/Case.tsx

Move advice count to top of case page

feat(consultation-portal): move advice count to top of case page

---

apps/consultation-portal/components/CaseOverview/CaseOverview.tsx
apps/consultation-portal/screens/Case/Case.tsx

Move documents container (skjöl til samráðs) to leftside column

fix(consultation-portal): move documents box card left

---

apps/consultation-portal/components/CaseTimeline/CaseTimeline.tsx
apps/consultation-portal/utils/helpers/dateFormatter.ts

Add dates to timeline statuses
Til umsagnar:
Í vinnslu:
Lokið:

feat(consultation-portal): add dates to timeline

---

apps/consultation-portal/components/HeroBanner/HeroBanner.tsx
apps/consultation-portal/components/StatisticBox/StatisticBox.tsx

Fix wording in hero banner statistic box

fix(consultation-portal): Fix wording in hero banner

---

libs/application/templates/passport/src/lib/PassportTemplate.ts

When application is prunes in parent B approve state remove charge
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204522200064426

feat(passport-application): delete charge in 7 days if parentb does not approve

---

apps/consultation-portal/components/Advices/Advices.tsx
apps/consultation-portal/components/Card/SimpleCardSkeleton.tsx
apps/consultation-portal/screens/Case/Case.tsx
apps/consultation-portal/screens/Case/components/AdviceCTA.tsx
apps/consultation-portal/screens/Case/components/Stakeholders.css.ts
apps/consultation-portal/screens/Case/components/Stakeholders.tsx

feat(consultation-portal): blowout on umbodsbox

---

apps/web/components/ServiceWeb/Background/Background.tsx
apps/web/components/ServiceWeb/Background/Variations/Utlendingastofnun/Utlendingastofnun.css.ts
apps/web/components/ServiceWeb/Background/Variations/Utlendingastofnun/Utlendingastofnun.tsx
apps/web/components/ServiceWeb/config.ts

feat(web): Update directorate of immigration service web header

---

libs/application/templates/passport/src/dataProviders/index.ts

fix(passport-application): minor param fix

---

libs/application/templates/health-insurance/src/fields/PrerequisiteSummary/PrerequisiteSummary.tsx
libs/application/templates/health-insurance/src/healthInsuranceUtils.ts

fix(health-insurance): Fix health insurance prerequisite check

---

apps/consultation-portal/utils/helpers/dateFormatter.ts

Add 1 day to process ends for "Niðurstöður í vinnslu"

fix(consultation-portal): add 1 day to process ends

---

libs/application/templates/health-insurance/src/fields/PrerequisiteSummary/PrerequisiteSummary.tsx
libs/application/templates/health-insurance/src/healthInsuranceUtils.ts

Fix prerequisite check for insurance
Uninsured people were getting through and then getting denied by the service when applying.

fix(health-inurance): Fix prerequisite check for insurance

---

apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx

[Ekki leyfa FMST og fangelsi að breyta lengd gæslu. Breyta í bakenda og framenda](https://app.asana.com/0/1199153462262248/1204087537077983/f)
- FMST can no longer update the length of custody and travel bans.
- FMST is not supposed to have this privilege.

chore(j-s): Blocks FMST from Changing Valid to Date

---

libs/application/template-api-modules/src/lib/modules/templates/health-insurance/health-insurance.service.ts

Change 412 response status to 500
Sjukra returns 412 which should be >=500 error based on its severity.
We fix it on our side.

fix(applications): Health insurance 412 response to 500

---

apps/consultation-portal/graphql/errorLink.ts
apps/consultation-portal/pages/_app.tsx
apps/consultation-portal/pages/askriftir/index.tsx
apps/consultation-portal/screens/Advices/Advices.tsx
apps/consultation-portal/screens/Subscriptions/Subscriptions.tsx
apps/consultation-portal/utils/helpers/adviceFilters/useAdviceFilters.ts
apps/consultation-portal/utils/helpers/useFetchAdvices.ts

https://veflausnir.atlassian.net/browse/KAM-1209

fix(consultation-portal): my subscriptions does not go to login when logged out

---

apps/system-e2e/src/tests/islandis/web/smoke/homepage.spec.ts
apps/system-e2e/src/tests/islandis/web/smoke/search.spec.ts
apps/system-e2e/src/tests/islandis/web/smoke/sites-of-institutions.spec.ts

Landlæknir has changed content and a few other tests have been failing.

chore(qa): Attempting to remove some flakiness in basic web tests

---

libs/application/templates/operating-license/src/fields/PropertyRepeater/index.tsx
libs/application/templates/operating-license/src/lib/dataSchema.ts

Improvements on validation checks in repeater fields.

fix(operating-license-application): validation on repeater

---

infra/src/dsl/egress.spec.ts
infra/src/dsl/kubernetes-runtime.ts
infra/src/dsl/value-files-generators/helm.spec.ts

This reverts commit 0c5a35275dc5bc7cb44439152f0657e87e06e785.

Revert "fix: disabled mountebank for this release (#10745) (#11076)"

---

infra/scripts/container-scripts/create-db.sh

build: fix regression on postgres CREATE EXTENSION, should check IF EXISTS

---

scripts/ci/_retag.sh

fix: added length constraints to LAST_GOOD_BUILD_DOCKER_TAG while retagging

---

scripts/ci/00_prepare-base-tags.sh
scripts/ci/_retag.sh

- fix: added length constraints to LAST_GOOD_BUILD_DOCKER_TAG while retagging
- fixed typo in comment
- added some more text to the comment since it made very little sense in its current state
- fixed docker tag in correct location, other location removed the sha and run number

fix: last good build retag issue

---

apps/consultation-portal/components/WriteReviewCard/WriteReviewCard.tsx
apps/consultation-portal/utils/helpers/createUUIDString.ts

https://veflausnir.atlassian.net/browse/KAM-1223
- Changed from crypto to uuidv4
- crypto not defined error in beta

fix(consultation-portal): removed crypto and using UUIDv4

---

libs/application/templates/european-health-insurance-card/src/dataProviders/apiActions.enum.ts
libs/application/templates/european-health-insurance-card/src/dataProviders/index.ts
libs/application/templates/european-health-insurance-card/src/lib/template.ts

fix(Ehic): fix api actions (#11108)

---

apps/consultation-portal/pages/_app.tsx

https://veflausnir.atlassian.net/browse/KAM-1227
removing error logs in beta

fix(consultation-portal): getSession in _app takes in customContext

---

apps/web/screens/queries/Search.tsx

using relatedArticles property here is causing unnecessary api calls to contentful - removing those from gql query and cleaning up the query in general
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204545857539832

feat(search-toolkit): Remove unnecessary property

---

libs/auth-api-lib/seeders/data/scope-rsk-prokura-admin.ts

Fixing domain name in the scope name
To unblock service startup.

fix(auth-api-lib): Fix domain name of rsk scope name

---

apps/judicial-system/backend/src/app/modules/case/case.service.ts
apps/judicial-system/backend/src/app/modules/case/test/caseController/transition.spec.ts

[Skila Landsréttar úrskurði í héraðsdóms Auði. ](https://app.asana.com/0/1199153462262248/1204367226077571/f)
- Uploads appeal ruling to district court when appeal is completed by court of appeals.

feat(j-s): Upload Appeal Ruling to District Court

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/Themes/SjukratryggingarTheme/SjukratryggingarFooter.css.ts
apps/web/components/Organization/Wrapper/Themes/SjukratryggingarTheme/SjukratryggingarFooter.tsx
apps/web/hooks/useLinkResolver/useLinkResolver.ts
apps/web/layouts/main.tsx
apps/web/screens/LifeEvent/LifeEvent.tsx

This PR contains a cherry picked commit from main (#11111)

feat(web): Hotfix - Sjukratryggingar footer update (#11111)

---

apps/system-e2e/src/tests/islandis/web/smoke/sites-of-institutions.spec.ts

fix(system-e2e): Fixing assertion for an institution

---

libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/hasReviewerApproved.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/isLastReviewer.ts

Display submit button for seller to handle cases where application is stuck

fix(transfer of vehicle ownership): application not submitted after all review

---

apps/web/components/connected/syslumenn/TableLists/BrokersList/BrokersList.tsx

feat(web): Hotfix - Syslumenn Brokers / Prioritise prefix search match (#11192)

---

libs/api/domains/auth/src/lib/dto/patchConsent.input.ts
libs/api/domains/auth/src/lib/resolvers/consent.resolver.ts
libs/api/domains/auth/src/lib/services/consent.service.ts
libs/service-portal/consent/src/screens/Consent/Consent.graphql
libs/service-portal/consent/src/screens/Consent/Consent.tsx
libs/service-portal/consent/src/screens/Consent/types.ts

[Notion task](https://www.notion.so/Connect-UI-to-GraphQL-mutations-25a503d1c19e4a37873bdc073c31e128)
GQL mutation to update consent on toggle.
To store change in IDS db.
N/A

feat(service-portal-consent): Update consent mutation on toggle.

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Project/Header/FiskistofaDashboardHeader.tsx

feat(web): Display external organization links on mobile

---

libs/api/domains/driving-license/src/lib/__mock-data__/licenseWithDisqualification.json
libs/api/domains/driving-license/src/lib/__mock-data__/requestHandlers.ts
libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
libs/api/domains/driving-license/src/lib/drivingLicense.spec.ts
libs/application/templates/driving-learners-permit/src/fields/EligibilitySummary/fakeEligibility.ts

Hotfix of the following:
* #11197 
* #11141 

fix(driving-learners-permit): tests and residence removal

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Project/Header/FiskistofaDashboardHeader.tsx

https://github.com/island-is/island.is/pull/11205

feat(web): Hotfix - organization external links visible on mobile

---

libs/application/types/src/lib/ApplicationTypes.ts
libs/service-portal/vehicles/src/lib/messages.ts

Change slug for application (request from Vésteinn)

feat(order vehicle license plate): Change slug

---

apps/system-e2e/src/support/urls.ts
apps/system-e2e/src/tests/islandis/service-portal/smoke/financial-payment-application.spec.ts
apps/system-e2e/src/tests/islandis/service-portal/smoke/sessions.spec.ts

Missing data for payment plan and popup window that was stopping the test.
Someone changed the locale for the test user and that tripped the sessions tests up.

fix(system-e2e): Fixing a couple of tests

---

apps/web/components/ServiceWeb/Forms/StandardForm/StandardForm.tsx
apps/web/components/ServiceWeb/Forms/StandardForm/types.ts
apps/web/screens/ServiceWeb/Forms/Forms.tsx
apps/web/screens/ServiceWeb/Forms/utils.ts
libs/api/domains/communications/src/lib/emailTemplates/serviceWebForms.ts

feat(web): Hotfix - Sjúkratryggingar service web form changes (#11189)

---

apps/application-system/api/src/app/modules/application/tools/templateApiActionRunner.service.ts

fix(application-system): Refactor template runner

---

libs/api/domains/air-discount-scheme/src/lib/discount/discount.resolver.ts
libs/api/domains/air-discount-scheme/src/lib/flight-leg/flight-leg.resolver.ts

Update audit logging
For better breakdown of audit logs.

chore(air-discount): Update audit logging

---

apps/consultation-portal/components/SEO/SEO.tsx

https://veflausnir.atlassian.net/browse/KAM-1275
- Change url in SEO component from https://samradsgatt.island.is... to https://island.is/samradsgatt....

fix(consultation-portal): fix url in seo component

---

apps/consultation-portal/screens/Advices/Advices.tsx

https://veflausnir.atlassian.net/browse/KAM-1288
- Search and sort and card should not be shown if user is not logged in

fix(consultation-portal): Fix in mínar umsagnir

---

libs/api/domains/air-discount-scheme/src/lib/discount/discount.resolver.ts
libs/api/domains/air-discount-scheme/src/lib/flight-leg/flight-leg.resolver.ts

chore(air-discount): Hotfix - Update audit logging.

---

libs/application/templates/health-insurance/src/forms/messages.ts

fix(health-insurance): Fix duplicate message id

---

apps/consultation-portal/hooks/useAdviceFilters.ts
apps/consultation-portal/hooks/useFrontPageFilters.ts

https://veflausnir.atlassian.net/browse/KAM-1280
data from localstorage should render after data from server has rendered

fix(consultation-portal): filters from localstorage to useEffect

---

libs/api/domains/consultation-portal/src/lib/models/adviceResult.model.ts
libs/api/domains/consultation-portal/src/lib/models/caseAdviceCommand.model.ts
libs/api/domains/consultation-portal/src/lib/models/caseResult.model.ts
libs/api/domains/consultation-portal/src/lib/models/relatedCaseResult.model.ts
libs/clients/consultation-portal/src/clientConfig.json

https://veflausnir.atlassian.net/browse/KAM-1323
https://veflausnir.atlassian.net/browse/KAM-1324
https://veflausnir.atlassian.net/browse/KAM-1325

feat(consultation-portal): changes in api reflect on graphql api

---

apps/consultation-portal/components/Layout/components/Footer/components/FooterColumn.tsx

https://veflausnir.atlassian.net/browse/KAM-1328
Different footer layout in desktop vs mobile

fix(consultation-portal): fix footer in mobile

---

libs/service-portal/petitions/src/lib/messages.ts
libs/service-portal/petitions/src/screens/PetitionsTable/ExportPetition/index.tsx
libs/service-portal/petitions/src/screens/PetitionsTable/index.tsx

fix(service-portal): Petitions: adding copylink button

---

libs/application/templates/european-health-insurance-card/src/fields/ReviewScreen/ReviewScreen.tsx
libs/application/templates/european-health-insurance-card/src/lib/messages.ts

fix(ehic): update review screen with text string

---

libs/judicial-system/types/src/index.ts
libs/judicial-system/types/src/lib/case.ts

[Fjarlægja leifar af subpoena type](https://app.asana.com/0/1199153462262248/1204721288741301/f)
- Removes remnants of subpoena type.
- Dead code.

chore(j-s): Cleanup

---

libs/application/templates/european-health-insurance-card/src/lib/messages.ts
libs/application/templates/european-health-insurance-card/src/lib/template.ts

fix(ehic): update application text strings

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunAusturlandsTheme/HeilbrigdisstofnunAusturlandsFooter.css.ts
apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunAusturlandsTheme/HeilbrigdisstofnunAusturlandsFooter.tsx
apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunAusturlandsTheme/HeilbrigdisstofnunAusturlandsHeader.css.ts
apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunAusturlandsTheme/HeilbrigdisstofnunAusturlandsHeader.tsx
apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunAusturlandsTheme/index.ts

This organization is gonna be soft launched very soon so we need to have the header and footer ready on prod before then :)

feat(web): Hotfix - Add header and footer for HSA organization (#11309)

---

apps/judicial-system/backend/src/app/modules/case/state/case.state.spec.ts
apps/judicial-system/backend/src/app/modules/case/state/case.state.ts

[Landsréttur - kært í þinghaldi - yfirlitsskjár Héraðsdóms](https://app.asana.com/0/1199153462262248/1204512772398820/f)
- Fixes state transition when appealing in court.
- Allows case completion after case has been appealed.
- Appeal transition need further modifications to allow the reopening of appealed cases. That will be handled separately.

fix(j-s): Appeal in Court

---

apps/judicial-system/web/src/routes/CourtOfAppeal/Cases/Cases.tsx

[Landsréttur - R mál eiga ekki að vera með dagsetningu í afgreiddum málum.](https://app.asana.com/0/1199153462262248/1204724531400381)
- Removing duration date when a case is restriction case 
- In restriction case duration date is unnecessary

fix(j-s): Adding a is restriction case check in court of appeal table 

---

libs/service-portal/health/src/lib/navigation.ts

Hotfix - fix message id (#11289)

fix(service-portal): Hotfix - fix message id (#11289)

---

apps/judicial-system/backend/infra/judicial-system-backend.ts
charts/judicial-system/values.dev.yaml
charts/judicial-system/values.prod.yaml
charts/judicial-system/values.staging.yaml

chore(infra): Increase memory for judicial-system

---

apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudies.css.ts
apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudiesHeader.tsx

* I moved the title on desktop screens a bit down and to the left and also stopped absolute positioning it

chore(web): University studies header visual changes

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudies.css.ts
apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudiesHeader.tsx
apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/index.ts

https://github.com/island-is/island.is/pull/11344
https://github.com/island-is/island.is/pull/11361
The /s/haskolanam page that has this header might be published in the next few days so that's why we need to hotfix in this header

feat(web): Hotfix - university studies header

---

libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/getApproveAnswers.ts

We are getting many errors when individuals are approving. Also checking if this triggers update I made earlier (doesn't look like it updated on dev/prod)

fix(transfer of vehicle ownership): add console log when approving

---

libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/getApproveAnswers.ts

fix(transfer of vehicle ownership): revert add console log when approving

---

libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/dataSchema.ts

Setting negative value validation on salePrice

fix(transfer-of-vechicle-ownership): negative number validation

---

apps/api/esbuild.json

fix(web-api): Add jsdom package to api

---

libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts

fix(parental-leave): Added employers obj to employerAppr write access

---

apps/judicial-system/web/src/components/TagAppealState/TagAppealState.tsx

[Málalisti - mál á dagskrá fær ranglega taggið kært + taka út kært tagg](https://app.asana.com/0/1199153462262248/1204773298492055)
- Added feature flag to appeal state tag
- it is not suppose to be seen yet

fix(j-s): Feature hiding tag appeal state for now 

---

libs/application/templates/old-age-pension/src/forms/OldAgePensionForm.ts
libs/application/templates/old-age-pension/src/lib/answerValidators.spec.ts
libs/application/templates/old-age-pension/src/lib/answerValidators.ts
libs/application/templates/old-age-pension/src/lib/constants.ts
libs/application/templates/old-age-pension/src/lib/messages.ts
libs/application/templates/old-age-pension/src/lib/oldAgePensionUtils.ts

add validators for periods

---

libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/form.ts
libs/application/templates/estate/src/forms/EstateWithoutAssets/form.ts
libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/form.ts
libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/overviewSection.ts
libs/application/templates/estate/src/lib/dataSchema.ts

fix(estate): Seta í óskiptu búi final tweak

---

apps/web/screens/PetitionView/PetitionView.tsx
libs/portals/admin/petition/src/lib/messages.ts
libs/service-portal/petitions/src/screens/ViewSignedList/index.tsx

fix(admin-portal): Petitions texts

---

libs/application/core/src/lib/messages.ts
libs/application/templates/general-petition/src/fields/ListCreated/index.tsx
libs/application/templates/general-petition/src/fields/SignPetitionView/index.tsx
libs/application/templates/general-petition/src/lib/messages.ts
libs/application/ui-components/src/components/CopyLink/CopyLink.tsx

fix(general-petition): Copy link toast

---

apps/web/screens/PetitionView/PetitionView.tsx
libs/application/templates/general-petition/src/fields/SignPetitionView/index.tsx
libs/application/templates/general-petition/src/lib/messages.ts
libs/service-portal/petitions/src/screens/PetitionsTable/ExportPetition/index.tsx

fix(service-portal): Pdf download fix

---

libs/service-portal/core/src/components/UserInfoLine/UserInfoLine.tsx
libs/service-portal/information/src/components/ChildView/ChildView.tsx

Add skip outbound link track in userinfoline
We don't need it everywhere.

chore(service-portal): Skip outbound link track childview

---

libs/application/template-api-modules/src/lib/modules/shared/api/national-registry/national-registry.service.ts

National registry requested that we get age from date of birth rather than nationalId. For testing as well as upcoming changes to national ids.

fix(national-registry): national registry requested that we get age from date of birth

---

apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacanciesList.tsx

Fixes a bug where only the first page of results was rendered regardless of which page was selected in the paginator.

feat(web): Fix starfatorg pagination

---

apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudies.css.ts
apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudiesHeader.tsx

Fix scaling of Háskólanám page header for larger display sizes.

feat(web): Fix haskolanam header scaling

---

apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudies.css.ts
apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudiesHeader.tsx

Fixes scaling issues for `/s/haskolanam` header.
Cherry pick merge commits for PRs:
- #11422
- #11444

feat(web): Hotfix - University studies header scaling

---

apps/consultation-portal/infra/samradsgatt.ts
charts/islandis/values.staging.yaml

https://veflausnir.atlassian.net/browse/KAM-1361

fix(consultation-portal): wrong url in staging in infra

---

apps/web/components/Organization/Slice/EventSlice/EventSlice.tsx

feat(web): Hotfix - Add new background for tengjum rikid event slice

---

apps/system-e2e/src/tests/islandis/service-portal/smoke/inbox.spec.ts
libs/service-portal/documents/src/components/DocumentFilter/DocumentsFilter.tsx

Update e2e test for inbox
Tests failing, fixed now.

fix(service-portal): Update inbox e2e test fix

---

apps/web/components/Organization/Slice/EventSlice/EventSlice.tsx

New background for the Tengjum Ríkið 2023 conference.

feat(web): Add new background for tengjum rikid event slice

---

apps/consultation-portal/infra/samradsgatt.ts
charts/islandis/values.staging.yaml

Changing next-auth url in infra

fix(consultation-portal): hotfix change staging url next-auth

---

apps/api/infra/api.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

add CONSULTATION_PORTAL_SCOPE env

fix(consultation-portal): Update api.ts

---

apps/api/infra/api.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

- feat(web): Hotfix - Add new background for tengjum rikid event slice (#11472)
- fix(consultation-portal): hotfix change staging url next-auth (#11473)
- fix(consultation-portal): Update api.ts (#11482)
- Revert "fix(consultation-portal): Update api.ts (#11482)"

revert: fix(consultation-portal): Update api.ts

---

libs/api/domains/consultation-portal/src/lib/types/types.service.ts
libs/clients/consultation-portal/src/lib/consultationPortalClient.config.ts

fix(consultation-portal): Update consultationPortalClient.config.ts

---

apps/consultation-portal/screens/Case/components/AdviceCard/AdviceCard.css.ts
apps/consultation-portal/screens/Case/components/AdviceCard/AdviceCard.tsx
apps/consultation-portal/screens/Case/components/AdviceForm/AdviceForm.tsx

fix(consultation-portal): Advices hotfix

---

libs/application/templates/old-age-pension/src/fields/Review/index.tsx
libs/application/templates/old-age-pension/src/fields/Review/review-groups/Attachments.tsx
libs/application/templates/old-age-pension/src/fields/Review/review-groups/Comment.tsx
libs/application/templates/old-age-pension/src/fields/Review/review-groups/Period.tsx
libs/application/templates/old-age-pension/src/forms/OldAgePensionForm.ts
libs/application/templates/old-age-pension/src/lib/oldAgePensionUtils.ts

feat(old-age-pension): Add comment and files to Review screen

---

libs/application/templates/old-age-pension/src/forms/OldAgePensionForm.ts
libs/application/templates/old-age-pension/src/lib/constants.ts
libs/application/templates/old-age-pension/src/lib/messages.ts

added connected applications screen

---

apps/consultation-portal/screens/Case/Case.tsx

https://veflausnir.atlassian.net/browse/KAM-1359
- Not found case should show a 404 page

fix(consultation-portal): KAM-1359-related-cases-sometimes-fails

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/IcelandicNaturalDisasterInsuranceFooter.css.ts
apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/IcelandicNaturalDisasterInsuranceFooter.tsx
apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/IcelandicNaturalDisasterInsuranceHeader.css.ts
apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/IcelandicNaturalDisasterInsuranceHeader.tsx
apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/index.ts

So the organization page can be published with the header and footer we need to hotfix in this code change

feat(web): Hotfix - Add header and footer for NTÍ organization (#11368)

---

apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/IcelandicNaturalDisasterInsuranceHeader.css.ts

https://github.com/island-is/island.is/pull/11515

feat(web): Hotfix - Adjust NTÍ header title height

---

libs/application/templates/estate/src/forms/Sections/spouseOfTheDeceased.ts

fix(estate): cleanup

---

apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/IcelandicNaturalDisasterInsuranceHeader.css.ts

feat(web): Adjust NTÍ header title height

---

libs/application/template-api-modules/src/lib/modules/shared/api/national-registry/national-registry.service.ts
libs/application/templates/old-age-pension/src/dataProviders/index.ts
libs/application/templates/old-age-pension/src/fields/Review/index.tsx
libs/application/templates/old-age-pension/src/fields/Review/review-groups/Attachments.tsx
libs/application/templates/old-age-pension/src/fields/Review/review-groups/Comment.tsx
libs/application/templates/old-age-pension/src/fields/Review/review-groups/ConnectedApplications.tsx
libs/application/templates/old-age-pension/src/fields/Review/review-groups/Fishermen.tsx
libs/application/templates/old-age-pension/src/fields/Review/review-groups/ResidenceHistory.tsx
libs/application/templates/old-age-pension/src/forms/OldAgePensionForm.ts
libs/application/templates/old-age-pension/src/forms/Prerequisites.ts
libs/application/templates/old-age-pension/src/lib/OldAgePensionTemplate.ts
libs/application/templates/old-age-pension/src/lib/answerValidationSections/fileUploadHomeAllowance.ts
libs/application/templates/old-age-pension/src/lib/answerValidationSections/fileUpploadPenEarlyFisher.ts
libs/application/templates/old-age-pension/src/lib/answerValidationSections/period.ts
libs/application/templates/old-age-pension/src/lib/answerValidationSections/utils.ts
libs/application/templates/old-age-pension/src/lib/answerValidators.ts
libs/application/templates/old-age-pension/src/lib/constants.ts
libs/application/templates/old-age-pension/src/lib/dataSchema.ts
libs/application/templates/old-age-pension/src/lib/messages.ts
libs/application/templates/old-age-pension/src/lib/oldAgePensionUtils.ts
libs/clients/national-registry/v2/src/lib/nationalRegistryClient.service.ts

feat(old-age-pension): added homeAllowence

---

apps/system-e2e/entrypoint.sh
apps/system-e2e/src/playwright.config.ts
apps/system-e2e/src/support/session.ts
apps/system-e2e/src/tests/islandis/admin-portal/smoke/endorsements.spec.ts
scripts/ci/_docker.sh
scripts/ci/_podman.sh
scripts/local-e2e.sh
scripts/utils.sh

feat(system-e2e): Better DX & minor fixes

---

scripts/ci/_docker.sh

fix(ci): Call container_build instead of builder_build

---

charts/identity-server/values.staging.yaml
charts/islandis/values.staging.yaml
charts/judicial-system/values.staging.yaml
infra/src/dsl/output-generators/map-to-helm-values.ts
infra/src/dsl/types/output-types.ts

This reverts commit 1ba526dab77c9e28962483b476ec4f4c11c3b6db.

fix(dsl): Revert "chore(dsl): Disable grantNamespaces for staging (#11516)

---

apps/application-system/api/infra/application-system-api.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

fix: increased the cpu requested by application system api

---

libs/application/templates/old-age-pension/src/fields/Period/index.tsx
libs/application/templates/old-age-pension/src/forms/OldAgePensionForm.ts
libs/application/templates/old-age-pension/src/lib/answerValidationSections/fileUpploadPenEarlyFisher.ts
libs/application/templates/old-age-pension/src/lib/messages.ts
libs/application/templates/old-age-pension/src/lib/oldAgePensionUtils.ts

fix(old-age-pension): early retirement

---

libs/application/templates/financial-statements-inao/src/forms/application/application.ts
libs/application/templates/financial-statements-inao/src/lib/messages.ts

RES-101
Add usertype to datagathering screen
Must distinguish which flow the applicant is in

feat(financial-statements-inao): Added usertype to datagathering screen

---

libs/application/templates/announcement-of-death/src/lib/announcementOfDeathTemplate.ts
libs/application/templates/driving-instructor-registrations/src/lib/InstructorRegistrationsTemplate.ts
libs/application/templates/driving-school-confirmation/src/lib/DrivingSchoolConfirmationTemplate.ts
libs/application/templates/general-petition/src/lib/GeneralPetitionTemplate.ts

fix(announcement-of-death): ready for prod (#11600)

---

apps/consultation-portal/screens/Subscriptions/components/ChosenSubscriptions/ChosenSubscriptions.tsx
apps/consultation-portal/screens/Subscriptions/components/SubscriptionCard/SubscriptionCard.tsx

https://veflausnir.atlassian.net/browse/KAM-1390

fix(consultation-portal): Doesnt work clicking on checkbox

---

apps/consultation-portal/components/ActionCard/ActionCard.tsx
apps/consultation-portal/components/CardSkeleton/CardSkeleton.tsx
apps/consultation-portal/components/EmptyState/EmptyState.tsx
apps/consultation-portal/components/Eyebrows/Eyebrows.tsx
apps/consultation-portal/components/Layout/components/Menu/Menu.tsx
apps/consultation-portal/components/Layout/components/Menu/components/MenuItems/MenuItems.ts
apps/consultation-portal/screens/About/components/AboutContent/AboutContent.tsx
apps/consultation-portal/screens/About/components/TableOfContents/TableOfContents.tsx
apps/consultation-portal/screens/Case/CaseDesktop.tsx
apps/consultation-portal/screens/Case/components/CaseEmailBox/CaseEmailActionBox.tsx
apps/consultation-portal/screens/Case/components/CaseOverview/CaseOverview.tsx
apps/consultation-portal/screens/Home/components/HeroBanner/HeroBanner.tsx
apps/consultation-portal/screens/Home/components/SearchAndFilter/SearchAndFilter.tsx
apps/consultation-portal/screens/Subscriptions/components/SubscriptionsSkeleton/SubscriptionsSkeleton.tsx
apps/consultation-portal/screens/Subscriptions/components/Tabs/TabContent.tsx

https://veflausnir.atlassian.net/browse/KAM-1392

feat(consultation-portal): add data-testid's to components for testing

---

apps/system-e2e/entrypoint.sh
apps/system-e2e/src/playwright.config.ts
apps/system-e2e/src/tests/islandis/admin-portal/smoke/access-control.spec.ts
apps/system-e2e/src/tests/islandis/admin-portal/smoke/endorsements.spec.ts
apps/system-e2e/src/tests/islandis/service-portal/smoke/sessions.spec.ts
scripts/local-e2e.sh

fix(system-e2e): staging/dev inconsistencies and more niceties

---

apps/system-e2e/src/tests/judicial-system/smoke/restriction-case.spec.ts

[Laga e2e test sem klikka alltaf.](https://app.asana.com/0/1199153462262248/1204905732014164/f)
- Fixes e2e test.
- The test is causing deployment pipeline failure.

fix(j-s): E2E Test

---

apps/web/screens/LifeEvent/LifeEvent.tsx
apps/web/screens/LifeEvent/config.ts

feat(web): Add chat panel to anchor pages

---

libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
libs/application/template-api-modules/src/lib/modules/templates/driving-license-duplicate/driving-license-duplicate.service.ts
libs/application/templates/driving-license-duplicate/src/forms/applicationSections/sectionDataProviders.ts
libs/application/templates/driving-license-duplicate/src/forms/applicationSections/sectionDelivery.ts
libs/application/templates/driving-license-duplicate/src/forms/applicationSections/sectionOverview.ts
libs/application/templates/driving-license-duplicate/src/lib/drivingLicenseDuplicateTemplate.ts
libs/application/templates/driving-license-duplicate/src/lib/messages.ts
libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
libs/clients/driving-license/src/v5/clientConfig.json

* External client updates propagated to client config and services updated accordingly.
* Switched out source of jurisdictions

fix(application-driving-license-duplicate): Client and application update

---

apps/web/screens/PetitionView/PetitionView.tsx
libs/application/templates/general-petition/src/fields/SignPetitionView/index.tsx
libs/application/templates/marriage-conditions/src/lib/MarriageConditionsTemplate.ts
libs/application/templates/marriage-conditions/src/lib/messages.ts
libs/service-portal/petitions/src/screens/ViewSignedList/index.tsx

fix(general-petition): Instant mobile tweaks

---

apps/web/screens/PetitionView/PetitionView.tsx
libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
libs/application/template-api-modules/src/lib/modules/shared/api/driving-license/driving-license.service.ts
libs/application/template-api-modules/src/lib/modules/templates/driving-license-duplicate/driving-license-duplicate.service.ts
libs/application/templates/driving-license-duplicate/src/forms/applicationSections/sectionDataProviders.ts
libs/application/templates/driving-license-duplicate/src/forms/applicationSections/sectionDelivery.ts
libs/application/templates/driving-license-duplicate/src/forms/applicationSections/sectionOverview.ts
libs/application/templates/driving-license-duplicate/src/forms/applicationSections/sectionReasonForApplication.ts
libs/application/templates/driving-license-duplicate/src/lib/constants.ts
libs/application/templates/driving-license-duplicate/src/lib/dataSchema.ts
libs/application/templates/driving-license-duplicate/src/lib/drivingLicenseDuplicateTemplate.ts
libs/application/templates/driving-license-duplicate/src/lib/messages.ts
libs/application/templates/general-petition/src/fields/SignPetitionView/index.tsx
libs/application/templates/marriage-conditions/src/lib/MarriageConditionsTemplate.ts
libs/application/templates/marriage-conditions/src/lib/messages.ts
libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
libs/clients/driving-license/src/v5/clientConfig.json
libs/service-portal/petitions/src/screens/PetitionsTable/ExportPetition/index.tsx
libs/service-portal/petitions/src/screens/PetitionsTable/index.tsx
libs/service-portal/petitions/src/screens/PetitionsTable/styles.css.ts
libs/service-portal/petitions/src/screens/Skeletons/Skeleton.tsx
libs/service-portal/petitions/src/screens/ViewOwnedList/index.tsx
libs/service-portal/petitions/src/screens/ViewSignedList/index.tsx

Hotfixes:
* #11609 
* #11617 
* #11622 
* #11625 
* #11621

fix(application-templates): Round of hotfixes for application dld and petitions

---

apps/web/screens/PetitionView/PetitionView.tsx
libs/application/templates/general-petition/src/assets/Illustration.tsx
libs/application/templates/general-petition/src/fields/SignPetitionView/index.tsx
libs/application/ui-components/src/components/CopyLink/CopyLink.tsx
libs/service-portal/petitions/src/lib/messages.ts
libs/service-portal/petitions/src/screens/PetitionsTable/index.tsx
libs/service-portal/petitions/src/screens/ViewOwnedList/index.tsx
libs/service-portal/petitions/src/screens/ViewSignedList/index.tsx

Hotfix of #11632
- [X I have performed a self-review of my own code

fix(general-petitions): Fixing gp mobile (#11632)

---

libs/cms/src/lib/unions/slice.union.ts

fix(web): Fix asset mapping

---

apps/application-system/api/src/app/modules/application/application.controller.ts

Changing error log to info log
Chaning to an info as this isnt really an error, we have some applications in the db that are missing templates. Its expected.

fix(application-system): Change error to info templatenotfound

---

libs/application/template-api-modules/src/lib/modules/templates/driving-license-duplicate/driving-license-duplicate.service.ts

fix(application-driving-license-duplicate): Improve logging

---

libs/application/template-api-modules/src/lib/modules/templates/driving-license-duplicate/driving-license-duplicate.service.ts
libs/application/templates/driving-license-duplicate/src/forms/applicationSections/sectionDelivery.ts
libs/application/templates/driving-license-duplicate/src/lib/messages.ts

Hotfixes:
* #11633 
* #11639 
* #11644 
As is tradition, hotfixes for things that didn't make it into the release.
Final touches requested before lifting the feature flag :partying_face:

fix(application-driving-license-duplicate): Final touches

---

libs/service-portal/vehicles/src/screens/WorkMachinesDetail/WorkMachinesDetail.tsx
libs/service-portal/vehicles/src/screens/WorkMachinesOverview/WorkMachinesOverview.tsx

fix(service-portal): Hotfix - wrong namespace

---

libs/application/template-api-modules/src/lib/modules/templates/driving-learners-permit/driving-learners-permit.service.ts
libs/application/templates/driving-learners-permit/src/lib/DrivingLearnersPermitTemplate.ts

chore(application-driving-learners-permit): Add history logs

---

apps/services/license-api/src/app/modules/license/clients/firearmLicense/firearmLicenseApiClient.service.ts
libs/api/domains/license-service/src/lib/client/firearm-license-client/genericFirearmLicense.service.ts
libs/clients/smartsolutions/src/lib/smartSolutions.api.ts

fix(license-service): Hotfix - add expiration for firearm licenses

---

apps/web/screens/Project/Project.tsx
apps/web/screens/Project/components/ProjectFooter/ProjectFooter.tsx
apps/web/screens/Project/components/ProjectFooter/themes/OpinberNyskopun/OpinberNyskopunFooter.tsx

* Add logos
* Use different images
* Reorder imports

feat(web): Hotfix - Add logos to "Opinber Nýsköpun" footer (#11656)

---

libs/service-portal/petitions/src/lib/messages.ts
libs/service-portal/petitions/src/screens/PetitionsTable/ExportPetition/index.tsx
libs/service-portal/petitions/src/screens/PetitionsTable/index.tsx
libs/service-portal/petitions/src/screens/PetitionsTable/styles.css.ts

fix(service-portal): Download/copy link for list in mobile

---

apps/web/components/NewsList/NewsList.tsx
apps/web/components/NewsList/NewsListSidebar.tsx
apps/web/components/NewsList/utils.ts
apps/web/constants/index.ts
apps/web/screens/Home/Home.tsx
apps/web/screens/News.tsx
apps/web/screens/Organization/OrganizationNewsArticle.tsx
apps/web/screens/Organization/OrganizationNewsList.tsx
apps/web/screens/Project/ProjectNewsList.tsx
apps/web/screens/queries/News.tsx
apps/web/screens/queries/Organization.tsx
apps/web/screens/queries/Project.tsx
libs/cms/src/lib/cms.elasticsearch.service.ts
libs/cms/src/lib/dto/getNews.input.ts
libs/cms/src/lib/dto/getNewsDates.input.ts
libs/cms/src/lib/environments/environment.ts
libs/cms/src/lib/generated/contentfulTypes.d.ts
libs/cms/src/lib/models/latestNewsSlice.model.ts
libs/cms/src/lib/models/news.model.ts
libs/cms/src/lib/models/organizationPage.model.ts
libs/cms/src/lib/models/projectPage.model.ts
libs/cms/src/lib/search/importers/news.service.ts

This Hotfix PR contains the following cherry-picked changes from main:
* https://github.com/island-is/island.is/pull/11594
* https://github.com/island-is/island.is/pull/11623
* This feature was requested by Digital Iceland

feat(web): Hotfix - News filters

---

libs/application/templates/old-age-pension/src/fields/Review/review-groups/PaymentInformation.tsx
libs/application/templates/old-age-pension/src/fields/components/EmployersTable/index.tsx
libs/application/templates/old-age-pension/src/forms/OldAgePensionForm.ts
libs/application/templates/old-age-pension/src/lib/answerValidationSections/employers.ts
libs/application/templates/old-age-pension/src/lib/answerValidationSections/paymentInfo.ts
libs/application/templates/old-age-pension/src/lib/answerValidators.spec.ts
libs/application/templates/old-age-pension/src/lib/answerValidators.ts
libs/application/templates/old-age-pension/src/lib/constants.ts
libs/application/templates/old-age-pension/src/lib/dataSchema.ts
libs/application/templates/old-age-pension/src/lib/messages.ts
libs/application/templates/old-age-pension/src/lib/oldAgePensionUtils.ts

fix(old-age-pension): employers and personal allowance

---

scripts/postinstall.js

Fix inconsistency between implementation and README

fix(yarn): Better post-install env variable

---

apps/consultation-portal/screens/About/components/AboutContent/AboutRTF.tsx

https://veflausnir.atlassian.net/browse/KAM-1429

fix(consultation-portal): KAM-1429-pdf-opens-in-new-window-in-about-page

---

README.md
package.json
scripts/postinstall.js

revert: schemas in postinstall

---

apps/services/search-indexer/infra/search-indexer-service.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
libs/cms/src/lib/search/contentful.service.ts

feat(search-indexer-service): Add env variable for disabling nested resolution of entries from CMS (#11733)

---

apps/auth-admin-web/infra/auth-admin-web.ts
apps/services/auth/admin-api/infra/auth-admin-api.ts
apps/services/auth/ids-api/infra/ids-api.ts
apps/services/search-indexer/infra/search-indexer-service.ts
charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

Increased the memory and CPU requested by the search indexer and IDS based on current limits and requests from the production cluster

fix: increased ids memory limits

---

apps/api/infra/api.ts
apps/application-system/api/infra/application-system-api.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
infra/src/dsl/output-generators/map-to-helm-values.ts
infra/src/dsl/types/input-types.ts
infra/src/dsl/types/output-types.ts
infra/src/dsl/volumes.spec.ts

This reverts commit f98d4986680a43d51506a2d7875411047d0bb0b7.

revert: "chore: Move islyklar to EFS (#11754)"

---

libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/index.tsx

console.log for development

---

apps/services/search-indexer/infra/search-indexer-service.ts
charts/islandis/values.dev.yaml

chore(search-indexer-service): Temporarily disable nested entry fetching on dev

---

libs/application/template-api-modules/src/lib/modules/templates/transport-authority/transfer-of-vehicle-ownership/transfer-of-vehicle-ownership.service.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/index.tsx
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/getApproveAnswers.ts
libs/application/ui-components/src/components/PaymentPending/PaymentPending.tsx

fix(transfer vehicle ownership): submit and approve race condition 

---

apps/services/license-api/src/app/modules/license/clients/drivingLicense/drivingLicenseApiClient.service.ts

Fully check drivers license pkpass validity
Missing check

feat(license-api): add drivers license check

---

apps/judicial-system/backend/src/app/messages/notifications.ts

[Laga  format tilkynninga til sækjenda þegar krafa er tekin fyrir án boðunar í þinghald](https://app.asana.com/0/1199153462262248/1205268614076254/f)
- Correct a Contentful string used for court date notifications to prosecutors.

fix(j-s): Court Date Email

---

apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/IcelandicNaturalDisasterInsuranceHeader.tsx

* There was a tiny change for the NTÍ header image so I decided to simply update the link in the code even though there is a way to change it in the CMS (the way the image url is changed in the CMS involves essentially defining the css entirely, so that's why this image url change in the code is a bit nicer for now :) )

feat(web): Update NTÍ header image link

---

libs/application/templates/driving-instructor-registrations/src/fields/ViewStudent/index.tsx

fix(application-dir): Exams filter

---

libs/portals/admin/ids-admin/src/lib/messages.ts
libs/portals/admin/ids-admin/src/screens/Client/components/AdvancedSettings.tsx

Fixing the description text for custom claims 
It should be a description for custom claims

feat(auth-admin): Fixed text for custom claims

---

libs/service-portal/finance/src/module.tsx
libs/service-portal/finance/src/screens/FinanceRoutes.loader.ts
libs/service-portal/finance/src/screens/FinanceTransactions/FinanceTransactions.tsx

* Fix data loading for finance screens with dynamic routes.
* Fix data display for transaction screen.
* Waiting for incorrect data load for transaction screen.
* In some rare cases a flash of 404 page could be displayed for finance screens with dynamic routes. The new data loader fixes that.

fix(service-portal): Update finance loading in service portal

---

apps/air-discount-scheme/web/pages/_app.tsx

https://github.com/island-is/island.is/pull/11909

fix(ADS): Removing router from getinitialprops (#11909)

---

.github/workflows/push.yml
scripts/ci/30_test.sh

* Add DD API key to unit tests on main
* Set default env to ci
* Set DD_SERVICE
* Default test service to APP name
---------

feat(ci): Add DD test integration to `main` (#11908)

---

apps/system-e2e/src/support/login.ts
apps/system-e2e/src/tests/islandis/consultation-portal/smoke/consultation-portal-authenticated.spec.ts

https://veflausnir.atlassian.net/browse/KAM-1548
authenticated tests were failing

fix(consultation-portal): KAM-1548-failed-test

---

apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacanciesList.css.ts
apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacanciesList.tsx
apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacancyDetails.tsx
libs/api/domains/icelandic-government-institution-vacancies/src/lib/icelandic-government-institution-vacancies.resolver.ts
libs/api/domains/icelandic-government-institution-vacancies/src/lib/models/icelandicGovernmentInstitutionVacancy.model.ts
libs/api/domains/icelandic-government-institution-vacancies/src/lib/utils.ts
libs/cms/src/lib/cms.contentful.service.ts
libs/cms/src/lib/dto/getOrganizations.input.ts
libs/cms/src/lib/models/organization.model.ts

feat(web): Hotfix - Match institutions via reference identifier for vacancies (#11917)

---

libs/application/templates/driving-license-duplicate/src/fields/PaymentCharge/index.tsx

Updated code from AY113 → AY137 to reflect price change

chore(application-driving-license-duplicate): Update charge code

---

libs/clients/tryggingastofnun/.eslintrc.json
libs/clients/tryggingastofnun/README.md
libs/clients/tryggingastofnun/jest.config.ts
libs/clients/tryggingastofnun/project.json
libs/clients/tryggingastofnun/src/clientConfig.yaml
libs/clients/tryggingastofnun/src/index.ts
libs/clients/tryggingastofnun/src/lib/clients-tryggingastofnun.module.ts
libs/clients/tryggingastofnun/src/lib/utils.ts
libs/clients/tryggingastofnun/tsconfig.json
libs/clients/tryggingastofnun/tsconfig.lib.json
libs/clients/tryggingastofnun/tsconfig.spec.json
tsconfig.base.json

feat(old-age-pension): getting connect to TR X-road endpoint

---

libs/application/templates/driving-license-duplicate/src/fields/PaymentCharge/index.tsx

Hotfix of 
* #11931 
* #11914 

fix(application-dlp): Charge codes

---

libs/api/domains/icelandic-government-institution-vacancies/src/lib/icelandic-government-institution-vacancies.resolver.ts
libs/api/domains/icelandic-government-institution-vacancies/src/lib/utils.ts

fix(web): Hotfix - Convert numeric "stofnunNr" field to string for vacancy institutions (#11951)

---

apps/judicial-system/api/src/app/modules/auth/auth.controller.ts
apps/judicial-system/api/src/app/modules/auth/auth.service.ts

Added audience verification and selecting the public key according to kid of the JWT token, also cleaned up code
To verify the validity of the id token when more than one public key is available, and make code more readable

fix(j-s): Token verification and refactor

---

libs/service-portal/licenses/src/screens/LicensesOverview/index.tsx

fix(service-portal): Hotfix - add included types to licenses query

---

libs/island-ui/core/src/lib/DatePicker/react-datepicker.css.ts

The media query in react datepicker css was malformed.
To fix consultation portal app using the react datepicker.
N/A

fix(island-ui): Fix react datepicker media query quote mark.

---

apps/system-e2e/src/tests/judicial-system/smoke/custody-prosecutor.spec.ts

[Keyra nýja regression testið í pípunni](https://app.asana.com/0/1199153462262248/1205345648991746/f)
- Runs the test in the dev pipeline.
- Automation

chore(j-s): Run Smoke Test in Pipeline

---

apps/judicial-system/api/src/app/modules/file/dto/createFile.input.ts
apps/judicial-system/api/src/app/modules/police/models/policeCaseFile.model.ts
apps/judicial-system/backend/src/app/modules/file/dto/createFile.dto.ts
apps/judicial-system/backend/src/app/modules/police/models/policeCaseFile.model.ts
apps/judicial-system/backend/src/app/modules/police/police.service.ts
apps/judicial-system/web/src/components/AccordionItems/IndictmentsCaseFilesAccordionItem/IndictmentsCaseFilesAccordionItem.tsx
apps/judicial-system/web/src/routes/Prosecutor/Indictments/PoliceCaseFiles/PoliceCaseFilesRoute.tsx
apps/judicial-system/web/src/routes/Prosecutor/Indictments/PoliceCaseFiles/getIndictmentPoliceCaseFiles.graphql
apps/judicial-system/web/src/routes/Prosecutor/components/CaseFiles/CaseFiles.tsx
apps/judicial-system/web/src/routes/Prosecutor/components/CaseFiles/getPoliceCaseFiles.graphql
apps/judicial-system/web/src/utils/hooks/useS3Upload/useS3Upload.ts
libs/judicial-system/types/src/lib/policeFile.ts

[Asana](https://app.asana.com/0/1199153462262248/1204853378242952/f)
Save `created` date on police case files when uploading to RVG.

feat(j-s): Date field from LÖKE

---

libs/api/domains/rights-portal/src/lib/rightsPortal.service.ts

Fix format
The formatting is wrong on main, but the dirty files bot is requesting Hugsmiðjan review on every pull request that pulls main since the formatting is wrong!

fix(service-portal): formatting

---

apps/judicial-system/api/src/app/modules/case/models/case.model.ts
apps/judicial-system/web/messages/Core/laws.ts
apps/judicial-system/web/src/components/AccordionItems/PoliceRequestAccordionItem/PoliceRequestAccordionItem.tsx
apps/judicial-system/web/src/routes/Court/RestrictionCase/Overview/Overview.tsx
apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/Overview.tsx
apps/judicial-system/web/src/types/index.ts
apps/judicial-system/web/src/utils/laws.ts
libs/api/domains/rights-portal/src/lib/rightsPortal.service.ts

[Asana](https://app.asana.com/0/0/1205359397922660/f)
Use generated caseLegalProvisions type in frontend
We are moving towards using generated GraphQL types in the frontend

chore(j-s): Use generated caseLegalProvisions type in frontend

---

libs/api/domains/icelandic-government-institution-vacancies/src/lib/icelandic-government-institution-vacancies.resolver.ts

fix(web): Hotfix - load institution title if logo is missing (#11967)

---

apps/judicial-system/api/src/app/modules/case/models/case.model.ts
apps/judicial-system/web/messages/Core/restrictions.ts
apps/judicial-system/web/src/components/RestrictionTags/RestrictionTags.spec.tsx
apps/judicial-system/web/src/components/RestrictionTags/RestrictionTags.tsx
apps/judicial-system/web/src/routes/Court/RestrictionCase/HearingArrangements/HearingArrangements.tsx
apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/PoliceDemands/PoliceDemands.spec.tsx
apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/PoliceDemands/PoliceDemands.tsx
apps/judicial-system/web/src/types/index.ts
apps/judicial-system/web/src/utils/restrictions.spec.tsx
apps/judicial-system/web/src/utils/restrictions.ts
apps/judicial-system/web/src/utils/stepHelper.ts
libs/api/domains/rights-portal/src/lib/rightsPortal.service.ts

[Asana](https://app.asana.com/0/1199153462262248/1205359398381996/f)
Use generated CaseCustodyRestrictions type
We are moving towards using generated GraphQL types in the front end

chore(j-s): Use generated CaseCustodyRestrictions type

---

libs/application/ui-shell/src/lib/ApplicationForm.tsx

Hot reload always resulted in a error screen because of missing null check
Dev X

fix(application-system): Hot reload error screen 

---

apps/web/screens/queries/fragments.ts
libs/cms/src/lib/generated/contentfulTypes.d.ts
libs/cms/src/lib/models/form.model.ts

* We need a way to update the default labels and placeholders for the form content type
This PR updates the model and a later PR will use this updated model to edit the frontent visuals

feat(web): Add new field to Form model

---

.github/CODEOWNERS

Adding Aranja as codeowner for `clients-rsk-relationships`
Aranja integrated the new service.

fix(clients-rsk-relationships): Add aranja as codeowners for relationships integration.

---

libs/clients/rsk/relationships/src/lib/RskRelationshipsClientConfig.ts

What
Applying https://github.com/island-is/island.is/pull/12029 as fix to pre-release
Why
To fix for release.

fix(clients-rsk-relationships): Removing admin scope from fallback value

---

libs/api/domains/occupational-licenses/src/lib/occupationalLicenses.module.ts
libs/api/domains/occupational-licenses/src/lib/occupationalLicenses.resolver.ts
libs/api/domains/occupational-licenses/src/lib/occupationalLicenses.service.ts
libs/feature-flags/src/lib/features.ts

* Add feature flag to Health directorate license resolver
Some doubts regarding prod availability

fix(service-portal): occupational license feature flag

---

libs/api/domains/occupational-licenses/src/lib/occupationalLicenses.module.ts
libs/api/domains/occupational-licenses/src/lib/occupationalLicenses.resolver.ts
libs/api/domains/occupational-licenses/src/lib/occupationalLicenses.service.ts
libs/feature-flags/src/lib/features.ts

fix(service-portal): Hotfix - occupational license feature flag

---

libs/application/templates/old-age-pension/src/lib/OldAgePensionTemplate.ts
libs/application/templates/old-age-pension/src/lib/constants.ts

fix(old-age-pension): Add event between submitted to inReview

---

apps/download-service/infra/download-service.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

fix(service-portal): Hotfix - education xroad config

---

libs/application/templates/general-petition/src/forms/form.ts
libs/application/templates/general-petition/src/lib/GeneralPetitionTemplate.ts

fix(petitions): dateTil with a max

---

libs/service-portal/information/src/screens/Child/Child.tsx

fix(service-portal): hotfix - user information child (#12076)

---

libs/service-portal/core/src/lib/messages.ts
libs/service-portal/core/src/lib/navigation/masterNavigation.ts
libs/service-portal/occupational-licenses/src/lib/messages.ts
libs/service-portal/occupational-licenses/src/lib/navigation.ts
libs/service-portal/occupational-licenses/src/module.tsx

Added api scope to routes, fixed wrong message in navigation and fixed messages file
Enable extract-strings script to correctly extract strings from messages file and adding scopes to routes.
To display correct messages and have correct scopes.

fix(service-portal): Adding scope, fixing messages

---

libs/service-portal/core/src/lib/messages.ts
libs/service-portal/core/src/lib/navigation/masterNavigation.ts
libs/service-portal/occupational-licenses/src/lib/messages.ts
libs/service-portal/occupational-licenses/src/lib/navigation.ts
libs/service-portal/occupational-licenses/src/module.tsx

* Added api scope to routes, fixed wrong message in navigation, and fixed messages file
* Same id in messages twice now fixed
* One more duplicate key in core messages, fixed now

fix(service-portal): Adding scope, fixing messages (#12073)

---

infra/helm/Chart.yaml

Fix wrong template locations
To make them work

fix(helm): Use right repository locations

---

libs/application/templates/parental-leave/src/constants.ts
libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
libs/application/templates/parental-leave/src/lib/answerValidationSections/utils.ts
libs/application/templates/parental-leave/src/lib/answerValidators.spec.ts
libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts

1. Allow less than 14 days periods which are in the past
2. Drop past periods which are not in VMST
3. Take out pre-fill companyID
4. Always show question about benefits

fix(parental leave): few errors

---

libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx

fix(service-portal): hotfix - HTML display on complete in document inbox

---

apps/application-system/form/src/auth.ts
libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/ChangeCoOwnerOfVehicleTemplate.ts
libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/ChangeOperatorOfVehicleTemplate.ts
libs/application/templates/transport-authority/license-plate-renewal/src/lib/LicensePlateRenewalTemplate.ts
libs/application/templates/transport-authority/order-vehicle-license-plate/src/lib/OrderVehicleLicensePlateTemplate.ts
libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/lib/OrderVehicleRegistrationCertificateTemplate.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/TransferOfVehicleOwnershipTemplate.ts
libs/auth/scopes/src/lib/api.scope.ts
libs/feature-flags/src/lib/features.ts

Add custom delegation to all Transport Authority applications that were using Procuration delegation

feat(transport authority applications): Add custom delegation

---

apps/download-service/src/app/modules/occupational-licenses/education-license.controller.ts
libs/api/domains/occupational-licenses/src/lib/occupationalLicenses.resolver.ts
libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
libs/service-portal/occupational-licenses/src/screens/EducationalDetail/EducationalDetail.tsx
libs/service-portal/occupational-licenses/src/screens/HealthDirectorateDetail/HealthDirectorateDetail.tsx
libs/service-portal/occupational-licenses/src/screens/OccupationalLicensesOverview/OccupationalLicensesOverview.tsx

https://github.com/island-is/island.is/pull/12118

fix(service-portal): hotfix - dl-service occupation license

---

libs/nest/feature-flags/src/lib/feature-flag.client.ts

fix: import configcat-node typo

---

libs/service-portal/information/src/screens/Child/Child.tsx

Remove fate from Child UI
It should not be shown.

fix(service-portal): Remove fate from child ui

---

apps/api/infra/api.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
libs/api/domains/license-service/src/lib/graphql/main.resolver.ts

Add failsafe to licenses resolver and turn on failsafe.

fix(api-domain-licenses): Licenses failsafe

---

libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
libs/service-portal/information/src/screens/Child/Child.tsx

fix(service-portal): fate UI hotfix

---

apps/web/components/ChatPanel/types.ts
apps/web/components/Organization/Wrapper/config.ts
apps/web/components/ServiceWeb/config.ts
apps/web/screens/Article/components/ArticleChatPanel/config.ts
libs/cms/src/lib/cms.contentful.service.ts
libs/cms/src/lib/cms.elasticsearch.service.ts

* Display chatbot for Icelandic Health Insurance articles, organization pages as well as on the service web
* Add filters to prevent graphql errors on serviceweb when fetching supportqnas without slugs (can happen for english qna's since the cms doesn't force english slugs and titles like it does for Icelandic)

feat(web): Add config for Icelandic Health Insurance chatbot

---

apps/services/search-indexer/infra/search-indexer-service.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

As a temporary solution to allow it to successfully complete it's initialisation process here is an attempt by increasing it's memory

fix(search-indexer-service): Increase memory limit for search-indexer

---

libs/application/templates/old-age-pension/src/forms/Prerequisites.ts
libs/application/templates/old-age-pension/src/lib/messages.ts

fix(old-age-pension): final version for external page

---

libs/api/domains/transport-authority/src/lib/graphql/main.resolver.ts
libs/api/domains/vehicles/src/lib/api-domains-vehicles.resolver.ts

fix(transport authority custom delegation): Add missing scope to endpoints that are used

---

apps/services/user-profile/src/app/user-profile/e2e/userProfile.spec.ts
apps/services/user-profile/src/app/user-profile/userProfile.controller.ts

fix(user-profile): hotfix no user found

---

apps/web/components/ChatPanel/LiveChatIncChatPanel/LiveChatIncChatPanel.tsx
apps/web/components/ChatPanel/types.ts
apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/config.ts
apps/web/screens/Article/components/ArticleChatPanel/ArticleChatPanel.tsx
apps/web/screens/Article/components/ArticleChatPanel/config.ts

feat(web): Hotfix - Add livechat config for transport authority (#12097)

---

libs/application/templates/passport/src/dataProviders/index.ts
libs/application/templates/passport/src/forms/ParentB.ts
libs/application/templates/passport/src/lib/PassportTemplate.ts

fix(application-passport): Passport domicile requirement amendment

---

libs/application/templates/passport/src/dataProviders/index.ts
libs/application/templates/passport/src/forms/ParentB.ts
libs/application/templates/passport/src/lib/PassportTemplate.ts

fix(application-passport): Hotfix/r242 passport domicile fix

---

libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/CoOwner/index.tsx

Loading state never changed to false, fixed that

fix(medeigandi-okutaekis): loading state fix

---

libs/api/domains/rights-portal/src/lib/rightsPortal.service.ts
libs/api/domains/rights-portal/src/lib/rightsPortal.types.ts
libs/service-portal/health/src/screens/AidsAndNutrition/AidsTable.tsx

- added missing properties in model
- improved typings in service
- adjusted frontend to model changes
Fixing typeguard so that data is returned to frontend
So users can get the data they are looking for 

fix(service-portal): Aids and nutrition service not returning data

---

libs/api/domains/national-registry/src/lib/shared/models/spouse.model.ts

fix(national-registry-v3): Update spouse model marital status text

fix(domains): Updating spouse model marital status text

---

libs/service-portal/occupational-licenses/README.md

Forcing new commit to release branch, adviced to do so from dev support team.
To fix spinnaker deployment bug, 

fix(domains): Force new commit to release branch.

---

libs/service-portal/occupational-licenses/src/components/LicenceActionCard.tsx

Removing unused import so that actions will start on merge
To fix bug on spinnaker

fix(domains): New empty commit to fix spinnaker

---

apps/web/components/connected/vehicles/AircraftSearch.tsx

* This was requested by the transport authority

feat(web): Display aircraft registration number in table

---

libs/cms/src/lib/models/powerBiSlice.model.ts

feat(web): Hotfix - Skip caching powerbi token

---

apps/web/components/connected/vehicles/AircraftSearch.tsx

feat(web): Hotfix - aircraft registry regno column

---

apps/web/components/ServiceWeb/config.ts

feat(web): Add directorate of immigration chat to service web

---

libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/CoOwner/index.tsx

fix(medeigandi-okutaekis): Adding logs

---

.github/workflows/pullrequest.yml
.github/workflows/push.yml

Move scanflags job from #12207 from pullrequest.yml to push.yml
To run on merges to `main` and release branches

chore(core): Move scanflags from pullrequest.yml to push.yml

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/applicationApprovedByEmployerToEmployer.ts
libs/application/templates/parental-leave/src/fields/FirstPeriodStart/index.tsx

- Move dateOfBirth option to be first choice
- Add applicant's name to confirmation email to Employer

fix(parental-leave): few changes requested by VMST

---

libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/applicationApprovedByEmployerToEmployer.ts

fix(parental-leave): Add applicant name to email subject text

---

apps/services/auth/admin-api/src/app/v2/secrets/client-secrets.service.ts
libs/auth-api-lib/src/lib/clients/admin/admin-clients.service.ts
libs/auth-api-lib/src/lib/clients/clients-translation.service.ts
libs/auth-api-lib/src/lib/resources/resource-translation.service.ts
libs/auth-api-lib/src/lib/translation/translation.service.spec.ts
libs/auth-api-lib/src/lib/translation/translation.service.ts

Applying #12162 to release 24.3.0
To apply fixes into production.

fix(auth-admin): Hotfix - fix flaky client creation (#12162)

---

apps/judicial-system/web/src/routes/Prosecutor/components/CaseFiles/CaseFiles.tsx

[Rof á reynslulausn (Krafa um afplánun eftirstöðva reynsluslausnar)](https://app.asana.com/0/1199153462262248/1205268262276871/f)
- Fixes LÖKE file updates in R-Cases.
https://github.com/island-is/island.is/assets/795382/cb11dcfd-1702-4bd7-bae1-fc0a55fa4896

fix(j-s): LÖKE file updates in R-Cases

---

libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts

Schema changes coupled with type assertions led to broken properties.
Fixed by anchoring properties to the estate schema

fix(application-estate): Desynced types causing issues

---

apps/web/screens/Organization/Home/Home.tsx
libs/api/domains/communications/src/lib/communications.service.ts

* There's an ongoing issue with the hsn form on dev/staging/prod and the logs don't tell us enough information so we need to log the entire error instead (the error doesn't happen on feature deploys nor locally)

feat(web): Log error for hsn form response

---

scripts/clean.sh

fix: error when cleaning

---

apps/services/sessions/infra/sessions.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml

Remove stale pvc for maxmind data

fix: remove unneeded tmp pvc

---

libs/api/domains/communications/src/lib/communications.service.ts

feat(web): Hotfix - Log error for hsn form response (#12230)

---

libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts

fix(application-estate): Desynced types in estate

---

libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
libs/application/template-api-modules/src/lib/modules/templates/estate/utils.ts
libs/application/templates/estate/src/fields/AssetsRepeater/index.tsx
libs/application/templates/estate/src/fields/Cards/index.tsx
libs/application/templates/estate/src/fields/EstateMembersRepeater/index.tsx
libs/application/templates/estate/src/fields/RealEstateRepeater/index.tsx
libs/application/templates/estate/src/fields/TextFieldsRepeater/index.tsx
libs/application/templates/estate/src/forms/OverviewSections/commonFields.ts
libs/application/templates/estate/src/forms/Sections/estateAssets.ts
libs/application/templates/estate/src/lib/dataSchema.ts
libs/application/templates/estate/src/lib/messages.ts

fix(application-estate): Email and phone validation

---

libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/CoOwner/index.tsx

fix(medeigandi-okutaekis): removing console logs

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/Themes/HmsTheme/HmsHeader.css.ts
apps/web/components/Organization/Wrapper/Themes/HmsTheme/HmsHeader.tsx
apps/web/components/Organization/Wrapper/Themes/HmsTheme/index.ts
libs/cms/src/lib/generated/contentfulTypes.d.ts
libs/island-ui/core/src/lib/AsyncSearch/AsyncSearch.tsx
libs/island-ui/core/src/lib/AsyncSearch/shared/Input/Input.css.ts
libs/island-ui/core/src/lib/AsyncSearch/shared/Input/Input.tsx
libs/island-ui/core/src/lib/Button/Button.css.ts
libs/island-ui/core/src/lib/FocusableBox/FocusableBox.css.ts
libs/island-ui/core/src/lib/context/ColorSchemeContext/ColorSchemeContext.ts

feat(web): Hotfix - Add header for HMS (#12232)

---

apps/consultation-portal/screens/Subscriptions/components/SubscriptionTable/SubscriptionTable.tsx

https://veflausnir.atlassian.net/browse/KAM-1748

fix(consultation-portal): KAM-1748: Fix bg color of subscription table in my subscriptions

---

apps/web/components/ServiceWeb/Forms/StandardForm/StandardForm.tsx
apps/web/screens/ServiceWeb/Forms/utils.ts
libs/api/domains/communications/src/lib/emailTemplates/serviceWebForms.ts

* Remove confirmation checkbox from service web contact forms
* Add default translations to service web contact forms
* Display more fields and categories in contact form for directorate of immigration

feat(web): Directorate of immigration - service web iteration

---

apps/judicial-system/web/src/routes/Prosecutor/components/PoliceCaseFiles/PoliceCaseFiles.tsx

[Laga virkni í rannsóknargögnum þegar stök skjöl eru valin úr löke með sama nafni.](https://app.asana.com/0/1199153462262248/1205458086259286/f)
- Fixes message when there are no LÖKE files.

fix(j-s): No LÖKE Files

---

apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacanciesList.tsx

* Use 'organization' version of the footer on /starfatorg

feat(web): Change /starfatorg footer

---

libs/clients/smartsolutions/codegen.yml
libs/clients/smartsolutions/fetchGraphql.yml
libs/clients/smartsolutions/project.json
libs/clients/smartsolutions/smartsolutions-api.graphql

* Fetch the remote graphql schema and store it locally
Makes us independant of the external service

feat(smart-solutions): add local smart graphql source

---

libs/api/domains/rights-portal/src/lib/models/healthCenter.model.ts
libs/api/domains/rights-portal/src/lib/rightsPortal.service.ts
libs/clients/icelandic-health-insurance/rights-portal/src/clientConfig.json
libs/service-portal/health/src/lib/messages.ts
libs/service-portal/health/src/screens/HealthCenter/HealthCenter.graphql
libs/service-portal/health/src/screens/HealthCenter/HealthCenter.tsx
libs/service-portal/health/src/screens/HealthCenter/HistoryTable.tsx

* Updated health center api, added can register funcitonality for health centers
* Replacing dash with correct string
* Removing unused messages
Fixing bugs in UI

fix(service portal): Add can register property to health centers

---

.github/workflows/stale-prs.yml

ci: better cron

---

.github/workflows/stale-prs.yml

ci: stop removing newlines

---

.github/workflows/stale-prs.yml

ci: set stalebot to run at 8 am

---

libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/ChangeCoOwnerOfVehicleTemplate.ts
libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/ChangeOperatorOfVehicleTemplate.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/TransferOfVehicleOwnershipTemplate.ts

fix(samgongustofa applications): Make sure charge is deleted on payment state (if fulfilled)

---

apps/contentful-apps/pages/fields/custom-location-input-field.tsx
apps/contentful-apps/pages/fields/formatted-location-input-field.tsx
apps/contentful-apps/pages/fields/time-duration-field.tsx

* There's a new content type called event which'll use these contentful apps

feat(contentful-apps): Time duration and formatted location contentful apps

---

libs/service-portal/health/src/screens/AidsAndNutrition/AidsAndNutrition.tsx

Check for length
length will return 0 on no items

fix(service-portal): Aids and nutrition tab check.

---

libs/service-portal/documents/src/components/DocumentLine/DocumentLine.css.ts
libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
libs/service-portal/health/src/screens/AidsAndNutrition/AidsAndNutrition.tsx

Hotfix new inbox UI issue:
#12359
https://github.com/island-is/island.is/pull/12352

fix(service-portal): hotfix - New inbox document line 

---

libs/portals/shared-modules/delegations/src/components/delegations/DelegationsEmptyState.tsx
libs/portals/shared-modules/delegations/src/hooks/useDomains/useDomains.ts

Apply #12356 
To make it into release 25.1.0
N/A

fix(access-control): Fix access control

---

libs/cms/src/lib/search/importers/utils.ts

* Continuation of #12345 
* Now there's a case where[ /s/fiskistofa](https://beta.dev01.devland.is/s/fiskistofa) gets synced with missing data, that's due to the pruning process for entry-hyperlink nodes actually doesn't create a sufficient copy and deleted fields are actually from the original organizationPage.
This PR changes the pruning process (yet again) so that it does not delete any fields but instead "changes pointers". That way we are not at a risk of removing a field from something which is in fact a circular reference and will therefore be indexed half empty

fix(search-indexer): Extract fields rather than deleting for entry-hyperlink nodes

---

libs/cms/src/lib/search/importers/utils.ts

fix(search-indexer): Hotfix - Extract fields rather than deleting for entry-hyperlink nodes (#12363)

---

apps/judicial-system/backend/src/app/modules/case/case.service.ts
apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
apps/judicial-system/backend/src/app/modules/case/test/caseController/transition.spec.ts
apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverCaseToPolice.spec.ts
apps/judicial-system/backend/src/app/modules/police/police.service.ts
apps/judicial-system/backend/src/app/modules/police/test/updatePoliceCase.spec.ts

This reverts commit 69dfb334f105494f3ced52980f49ebda310e2290.
Revert commit
Because police service is broken and so it blocks our deployments

revert(j-s): Deliver Appeal Ruling To Police (#12295)

---

libs/api/domains/documents/src/lib/document.resolver.ts
libs/api/domains/documents/src/lib/document.service.ts
libs/api/domains/documents/src/lib/dto/postBulkMailActionInput.ts
libs/api/domains/documents/src/lib/models/bulkMailAction.model.ts
libs/clients/documents/src/lib/documentClient.ts
libs/clients/documents/src/lib/models/BulkMailActionDTO.ts
libs/service-portal/documents/codegen.yml
libs/service-portal/documents/project.json
libs/service-portal/documents/src/components/DocumentLine/AvatarImage.tsx
libs/service-portal/documents/src/components/DocumentLine/DocumentLine.css.ts
libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
libs/service-portal/documents/src/components/FavAndStash/index.tsx
libs/service-portal/documents/src/screens/Overview/BatchMailAction.graphql
libs/service-portal/documents/src/screens/Overview/Overview.tsx
libs/service-portal/documents/src/utils/messages.ts

Add bulk archive and favourite options to new inbox.
UI and service updates.
New functionality ✨

feat(service-portal): Add bulk archive and fav

---

apps/judicial-system/backend/src/app/modules/case/case.service.ts
apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
apps/judicial-system/backend/src/app/modules/case/test/caseController/transition.spec.ts
apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverCaseToPolice.spec.ts
apps/judicial-system/backend/src/app/modules/police/police.service.ts
apps/judicial-system/backend/src/app/modules/police/test/updatePoliceCase.spec.ts

[Skila úrskurði Landsréttar til LÖKE](https://app.asana.com/0/1199153462262248/1205570629152972/f)
- Delivers the court of appeals ruling to the police on appeal conclusion.
- Less manual work.

feat(j-s): Deliver Appeal Ruling to Police

---

libs/api/domains/transport-authority/src/lib/graphql/dto/ownerChangeAnswers.input.ts
libs/api/domains/transport-authority/src/lib/transportAuthority.service.ts
libs/application/template-api-modules/src/lib/modules/templates/transport-authority/transfer-of-vehicle-ownership/transfer-of-vehicle-ownership.service.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/index.tsx
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/sections/VehicleSection.tsx
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/ValidationErrorMessages/index.tsx
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/forms/TransferOfVehicleOwnershipForm/InformationSection/vehicleSubSection.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/dataSchema.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/messages/information.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/messages/overview.ts
libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/index.ts
libs/clients/transport-authority/vehicle-owner-change/src/clientConfig.json
libs/clients/transport-authority/vehicle-owner-change/src/lib/vehicleOwnerChangeClient.service.ts
libs/clients/transport-authority/vehicle-owner-change/src/lib/vehicleOwnerChangeClient.types.ts

Add new optional number field: "Kílómetrar", to the application Transfer of vehicle ownership

feat(transfer of vehicle ownerchange): Add mileage input field

---

apps/services/sessions/src/deleteme.ts

chore: remove deleteme from sessions

---

apps/services/sessions/infra/sessions.ts
apps/services/sessions/src/deleteme.ts
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
infra/src/dsl/output-generators/map-to-helm-values.ts
infra/src/dsl/output-generators/map-to-localrun.ts
infra/src/dsl/utils/scale-value.spec.ts
infra/src/dsl/utils/scale-value.ts

- fix(sessions): use jobs for geoip (#12371)
- chore(sessions): remove deleteme

fix(sessions): use jobs for geoip

---

libs/cms/src/lib/search/importers/utils.spec.ts
libs/cms/src/lib/search/importers/utils.ts

fix(search-indexer): Hotfix - entry hyperlink circularity pruning (#12372)

---

libs/application/templates/estate/src/forms/OverviewSections/representative.ts

fix(estate): fixing phone for representative in overview

---

libs/service-portal/documents/src/components/DocumentActionBar/DocumentActionBar.tsx
libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
libs/service-portal/documents/src/screens/Overview/Overview.tsx

fix(service-portal): Hotfix - file viewing for new inbox

---

scripts/generate-changelog.sh

Helper for generating changelogs instead of manually checking for two most recent release branches

chore: util script for changelogs

---

apps/service-portal/src/components/Layout/FullWidthLayout.tsx
apps/service-portal/src/screens/Dashboard/Dashboard.tsx

* Add testing ID
* Only render shown layout tab items
No need for extra rendering most of the times not all tabs will be used.
Testing ID is for e2e.

fix(service-portal): Add fixes that fix e2e tests in service-portal

---

apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
apps/web/components/Organization/Wrapper/Themes/RettindagaeslaFatladsFolksTheme/RettindagaeslaFatladsFolksHeader.css.ts
apps/web/components/Organization/Wrapper/Themes/RettindagaeslaFatladsFolksTheme/RettindagaeslaFatladsFolksHeader.tsx
apps/web/components/Organization/Wrapper/Themes/RettindagaeslaFatladsFolksTheme/index.ts

https://github.com/island-is/island.is/pull/12391

feat(web): rettindagaesla fatlads folks footer

---

libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/messages/application.ts

fix(transfer-vehicle-ownership): text change in history logs

---

charts/identity-server/values.dev.yaml
charts/identity-server/values.prod.yaml
charts/identity-server/values.staging.yaml
charts/islandis/values.dev.yaml
charts/islandis/values.prod.yaml
charts/islandis/values.staging.yaml
charts/judicial-system/values.dev.yaml
charts/judicial-system/values.prod.yaml
charts/judicial-system/values.staging.yaml
infra/src/environments.ts

fix(helm): Remove latest_master as default image

---

apps/contentful-apps/pages/fields/form-default-namespace-field.tsx
apps/web/components/Form/Form.tsx

* Forms as they are right now require an email and name always but after this change, those fields can be omitted.
* #12398
* #12383

feat(web): Hotfix - anonymous form submit on web

---

libs/api/domains/national-registry/src/lib/nationalRegistry.service.ts
libs/api/domains/national-registry/src/lib/v1/soffia.service.ts

Change response for children in v1 service national-registry
Address issue fixed.

fix(national-registry): Update children response for v1

---

libs/api/domains/national-registry/src/lib/nationalRegistry.service.ts
libs/api/domains/national-registry/src/lib/v1/soffia.service.ts

Hotfix ▶️  https://github.com/island-is/island.is/pull/12443

fix(national-registry): Hotfix - Update children response for v1

---

scripts/Dockerfile.proxy

Fix: proxies failing due to permissions

---

apps/skilavottord/web/next.config.js
apps/skilavottord/ws/docker-compose.yml
apps/skilavottord/ws/src/environments/environment.ts
apps/skilavottord/ws/src/main.ts

feat(car-recycling): change skilavottord local backend port

---

apps/services/license-api/src/app/modules/license/clients/disabilityLicense/disabilityLicenseClient.service.ts
apps/services/license-api/src/app/modules/license/clients/drivingLicense/drivingLicenseApiClient.service.ts
apps/services/license-api/src/app/modules/license/clients/drivingLicense/drivingLicenseMapper.ts
apps/services/license-api/src/app/modules/license/clients/firearmLicense/firearmLicenseApiClient.service.ts
apps/services/license-api/src/app/modules/license/clients/firearmLicense/firearmLicenseMapper.ts
apps/services/license-api/src/app/modules/license/dto/revokeLicense.dto.ts
apps/services/license-api/src/app/modules/license/dto/updateLicense.dto.ts
apps/services/license-api/src/app/modules/license/license.controller.ts
apps/services/license-api/src/app/modules/license/license.module.ts
apps/services/license-api/src/app/modules/license/license.service.ts
apps/services/license-api/src/app/modules/license/license.types.ts
apps/services/license-api/src/app/modules/license/test/license.service.spec.ts
libs/api/domains/license-service/src/lib/client/adr-license-client/genericAdrLicense.service.ts
libs/api/domains/license-service/src/lib/client/disability-license-client/genericDisabilityLicense.service.ts
libs/api/domains/license-service/src/lib/client/driving-license-client/genericDrivingLicense.service.ts
libs/api/domains/license-service/src/lib/client/firearm-license-client/genericFirearmLicense.service.ts
libs/api/domains/license-service/src/lib/client/machine-license-client/genericMachineLicense.service.ts
libs/clients/smartsolutions/smartsolutions-api.graphql
libs/clients/smartsolutions/src/lib/graphql/queries/mutations.ts
libs/clients/smartsolutions/src/lib/smartSolutions.api.ts
libs/clients/smartsolutions/src/lib/smartSolutions.types.ts

* Implement SmartSolutions api schema changes
* Improved logging
SmartSolutions are releasing a schema change tomorrow. We need to update as well. This should fix the issue that RLS is having with updates (hopefully)

fix(license-api): smartsolutions updates

---

apps/consultation-portal/components/DebouncedSearch/DebouncedSearch.tsx

https://veflausnir.atlassian.net/browse/KAM-1831
Search was reset when fetching

fix(consultation-portal): KAM-1831: removal of useEffect

---

libs/auth-api-lib/src/lib/delegations/DelegationConfig.ts

Add `Custom` delegation type to custom delegation scope rule to allow access control users to grant this scope in delegations.
N/A

chore(auth-api-lib): Add Custom delegation type to allow for Samráðsgátt.

---

libs/auth-api-lib/src/lib/delegations/DelegationConfig.ts

Apply #12469 to relese.
To enable users to grant delegation for company.
N/A

chore(auth-api-lib): Update delegation config

---

libs/api/domains/national-registry/src/lib/shared/models/child.model.ts
libs/api/domains/national-registry/src/lib/shared/models/personBase.model.ts

Add fate to model
It is still being relied on by some services. Will remove completely before next release

fix(national-registry): Add fate to model

---

libs/api/domains/national-registry/src/lib/shared/models/child.model.ts
libs/api/domains/national-registry/src/lib/shared/models/personBase.model.ts

fix(national-registry): Hotfix - Add fate to model (#12488)

---

libs/service-portal/health/src/module.tsx

fix(service-portal): hotfix - add ff to health detail 

---

libs/service-portal/information/src/screens/UserInfo/UserInfo.tsx

Use lazy query to load NationalRegistryPerson when the feature flag has loaded, never before.
Don't want any unecessary queries to Soffía

fix(service-portal): UserInfoDetail double query

---

libs/api/domains/license-service/src/lib/licenseService.service.ts

* Only return the available licenses
Fix mobile app bug

fix(license-service): only return available licenses

---

libs/service-portal/health/src/screens/HealthOverview/HealthOverview.tsx

Using correct feature flag
To correctly display the feature to correct users

fix(service-portal): Fixing wrong feature flag
